### ISSUE TITLE
Castoroides is missing

### ISSUE THREAD

**Issue by axi92** [cadon/ARKStatsExtractor#10]
Found these in the wiki, http://ark.gamepedia.com/Castoroides
Maybe incomplete

Castoroides
420,0.2,0.54,0,0
180,0.1,0.1,0,0
380,0.1,0.1,0,0
2000,0.1,0.1,0,0.0
300,0.02,0.04,0,0
45,0.05,0.17,0.0,0.0
1,0,0.425,0.7,0
350,0.06,0,0.0,0

**Comment by cadon** [comment]
Hi, thanks, I've added it. You can get the entry in the app by clicking on ? -> Check for Updated Stats.
