### ISSUE TITLE
Wild 120 rex with 6380 health

### ISSUE THREAD

**Issue by Esurnir** [cadon/ARKStatsExtractor#100]
screen shot attached
![rex](https://cloud.githubusercontent.com/assets/6799814/18227207/a99aecee-71ea-11e6-9437-83de144d9f78.PNG)

**Comment by keiraskye** [comment]
![image](https://cloud.githubusercontent.com/assets/21988700/18232639/28c7e528-72a2-11e6-831b-066f9ed9248e.png)

Same issue except when I levelled up speed on my 203 rex the speed and health came out red

**Comment by keiraskye** [comment]
![image](https://cloud.githubusercontent.com/assets/21988700/18232642/54ed787a-72a2-11e6-97c9-b19ba763110a.png)

![image](https://cloud.githubusercontent.com/assets/21988700/18232645/5dc0bc46-72a2-11e6-86c6-014fd6c6d191.png)

Having the same issue except I levelled up speed to try and fix it and now the speed is showing as red as well.

**Comment by keiraskye** [comment]
![20160904132136_1](https://cloud.githubusercontent.com/assets/21988700/18232658/9a169fe4-72a2-11e6-95e4-9fa2a4a3365b.jpg)

![image](https://cloud.githubusercontent.com/assets/21988700/18232662/9e20c498-72a2-11e6-8965-49677467cf5e.png)

Having the same issue with a tamed 203 rex. I tried levelling speed to see if it would fix anything and now even the speed is showing up red.

**Comment by Fabibi81** [comment]
rex's base-health is now : 1100

**Comment by cadon** [comment]
Hi, thanks for the reports. I'll update the HP-stat soon.
