### ISSUE TITLE
Automatic read of Game.ini & GameUserSetting.ini not working

### ISSUE THREAD

**Issue by Plopsi** [cadon/ARKStatsExtractor#1013]
The Settings window says you can drag&drop the Game.ini and/or GameUserSettings.ini into it to automatic import all multipliers, but that does not work. The drag&drop icon is crossed telling not drag&drop is possible there.

Using Windows 10 Pro 1909 (Build 18363.535)

**Comment by VolatilePulse** [comment]
The feature does work as intended. What you're experiencing is Windows telling you that you can't drop that file there. Either it doesn't "belong" to you, it's not the correct extension, or ASB has been elevated with admin privileges or sandboxed. 

Simple troubleshooting steps can be to make sure not to run ASB with admin privileges, make sure the file exists on the physical operating system (not in a network shared directory), and make sure ASB isn't being blocked by antivirus software. 

There have also been reports of remote desktop access interfering with the drag & drop feature, but again, that's something with windows and something we aren't aware of being an issue.
