### ISSUE TITLE
Stat Testing colors are in the wrong order.

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#1017]
In the Stat Testing tab, the color regions are in the order 0 1 4 2 3 5.

**Comment by cadon** [comment]
It looks correct for me (012345). Do you have a screenshot? Does it show the correct order in the extractor? Is this a new behaviour? Does it change for species that have not all color regions (e.g. Argentavis doesn't use region 1).

**Comment by cadon** [comment]
I hope it's resolved, if not, feel free to reopen.
