### ISSUE TITLE
Additional creatures not in creature list

### ISSUE THREAD

**Issue by PGMvlaar** [cadon/ARKStatsExtractor#1022]
If extra .json for mods are installed, those creatures will not be listed in the big list of all creatures. Confirmed with Gryphons and Small Dragons.

**Comment by cadon** [comment]
Hi,
I just added the mod Gryphons in the mod manager and could select the species `Pygmy Gryphon` in the species selector. It seems to work for me. What species don't appear for you?

**Comment by PGMvlaar** [comment]
It seems to have fixed itself now for some reason, but when I reported this, all creatures from those mods were not listed. Searching for 'gr' would only give the vanilla Griffin.

**Comment by cadon** [comment]
Good to hear! If you happen to see this issue again and can reproduce it, feel free to reopen this issue.
