### ISSUE TITLE
Exporting Imported Dinos to "Imported" Subfolder Doesn't Work

### ISSUE THREAD

**Issue by amazonianwarrior** [cadon/ARKStatsExtractor#1023]
Since I updated, I have not been able to successfully export imported dinos to the "imported" subfolder. I have already successfully exported once before I kept getting a popup saying 
"E:/Program Files (x86)\Steam\steamapps\common\Ark\Shootergame\Saved\DinoExports\76561198977130741\DinoExport_33887715973505065.ini could not be moved. The following files will not be moved either. "

If there is a way to fix this, please let me know. Since I am in charge of breeding on my server, I am going crazy having to reload over 50 to 100 exports each time I add a new dino to the library. 

Thanks in advance. :)

**Comment by amazonianwarrior** [comment]
Note: I go to "Import Exported Data" then "Files" then "Move all imported files to "imported" subfolder". I get a confirmation that I want to transfer the files and I hit "Yes." That is when I get the pop-up.

**Comment by cadon** [comment]
This error message means that there was an issue while the application tried to move the files. Common reasons are that the file is not available anymore, the file is currently in use (e.g. opened in a text-editor), the destination folder is protected or there is not enough disk space. The next release will display the reason why the moving could not be done.
