### ISSUE TITLE
Stats not calculating thus not extracting

### ISSUE THREAD

**Issue by Sethz** [cadon/ARKStatsExtractor#1024]
Value for Stamina, Oxygen, food, weight and speed is not calculated - it's shown on the graph though.
For Health, Damage and Torpor values are calculated correct.

![Capture](https://user-images.githubusercontent.com/18222630/75605209-0bc7b400-5ae1-11ea-9ef4-139d77d71237.PNG)

**Comment by cadon** [comment]
Hi, probably you have selected the wrong Therizinosaur-variant for the extraction. The new DLC added a lot of variants. The next release of ASB will make the correct selection easier.
