### ISSUE TITLE
All dinos in library lost after update

### ISSUE THREAD

**Issue by bigredfan** [cadon/ARKStatsExtractor#1026]
Hello I updated yesterday to the new version when prompted and lost all my dino data, this has happened before. Very frustrating! almost 1600 dinos worth of info gone. https://gyazo.com/c008c948f7336cac98a10af835541712

**Comment by cadon** [comment]
That sounds bad. Can you upload the library-file for further inspection?

**Comment by bigredfan** [comment]
I can, what file am I looking for?
________________________________

**Comment by cadon** [comment]
`My Dinos_5.asb`

**Comment by bigredfan** [comment]
This file contain just under 500 dinos, basically it's what I have imported individually using the pie wheel method in the past few months.
________________________________

**Comment by cadon** [comment]
The dinos are back in the library?

**Comment by bigredfan** [comment]
That was some of them but after some digging I manage to just now find the up to date library so I have them all now. I just don't understand why they don't stay in my exported dino folder and also how to properly back up and save my dino library

________________________________

**Comment by cadon** [comment]
There's an option in ASB that imported files are removed or moved to a subfolder. By default this setting is disabled, so unless you enabled it, I don't know why the files are gone.
Good to hear the creatures are back. To backup the library just copy the file with the extension `.asb` to a safe location.

**Comment by harry323** [comment]
I'm not sure if this is exactly the same problem as you experienced but I have had moments where (it seems like after an update) that my dinos vanish from ASB. What I usually do is first, not panic and second close ASB and reopen it. That usually gets everything back to displaying properly. But in my experience that happens very rarely and I've always been able to access my data after reopening ASB.

**Comment by cadon** [comment]
Is the number of creatures in the library different if there are missing ones in the statusbar at the bottom?

**Comment by harry323** [comment]
@cadon if you are asking me, I haven't noticed when the issue arose. If it happens again I'll keep in mind to check it and report back.

**Comment by cadon** [comment]
Looks like the issue is resolved. If not, please reopen the issue.
