### ISSUE TITLE
App Exits When Modifying Any Dino

### ISSUE THREAD

**Issue by neostryder** [cadon/ARKStatsExtractor#1027]
I was happily adding all my dinos, then suddenly it started crashing on every import.  Tried to update status/change name, and any action that modifies my library results in a crash.  :/  Library and config attached.
[ASB.zip](https://github.com/cadon/ARKStatsExtractor/files/4272247/ASB.zip)

**Comment by neostryder** [comment]
Also any modification to settings exits app.  It seems to open and function fine except for that.

**Comment by neostryder** [comment]
Enable Overlay also exits.  I also noticed that the config file does not appear to have the settings that I had configured previously, such as turning on autosave.

**Comment by cadon** [comment]
The library you sent works fine for me.
Is there an error-message when the application crashes? If not, please check the event viewer in windows (see e.g. https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/) if in `Windows protocols` - `Applications` is any info about the crash.

**Comment by neostryder** [comment]
Faulting application name: ARK Smart Breeding.exe, version: 0.37.1.0, time stamp: 0x5e5b9b43
Faulting module name: KERNEL32.dll, version: 10.0.18362.329, time stamp: 0x7b5427ec
Exception code: 0xc00000fd
Fault offset: 0x0001a76b
Faulting process id: 0x4ae0
Faulting application start time: 0x01d5effa5745cbcf
Faulting application path: C:\Games\ARK Smart Breeding\ARK Smart Breeding.exe
Faulting module path: C:\WINDOWS\System32\KERNEL32.dll
Report Id: c31701f0-9d91-45a2-915d-60a74325613b
Faulting package full name: 
Faulting package-relative application ID: 

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-03-01T18:51:54.159356000Z" /> 
  <EventRecordID>27201</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Angband</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>ARK Smart Breeding.exe</Data> 
  <Data>0.37.1.0</Data> 
  <Data>5e5b9b43</Data> 
  <Data>KERNEL32.dll</Data> 
  <Data>10.0.18362.329</Data> 
  <Data>7b5427ec</Data> 
  <Data>c00000fd</Data> 
  <Data>0001a76b</Data> 
  <Data>4ae0</Data> 
  <Data>01d5effa5745cbcf</Data> 
  <Data>C:\Games\ARK Smart Breeding\ARK Smart Breeding.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNEL32.dll</Data> 
  <Data>c31701f0-9d91-45a2-915d-60a74325613b</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>


Will try exit ARK and re-open, then restart computer.

**Comment by cadon** [comment]
Thanks! There should be another entry in the log, usually just below the one you posted, which displays the method in the code that caused the exception, that would be useful as well.

**Comment by neostryder** [comment]
Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: ARK Smart Breeding.exe
P2: 0.37.1.0
P3: 5e5b9b43
P4: KERNEL32.dll
P5: 10.0.18362.329
P6: 7b5427ec
P7: c00000fd
P8: 0001a76b
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2E9.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_ARK Smart Breedi_dd12395d8d1b23d54b161e9f28ebd5966c5400_9a4c0ac1_73221771-9c5e-4f79-834d-8c5ffea017ee

Analysis symbol: 
Rechecking for solution: 0
Report Id: c31701f0-9d91-45a2-915d-60a74325613b
Report Status: 524388
Hashed bucket: 
Cab Guid: 0

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-03-01T18:52:01.768291300Z" /> 
  <EventRecordID>27210</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Angband</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data /> 
  <Data>0</Data> 
  <Data>APPCRASH</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>ARK Smart Breeding.exe</Data> 
  <Data>0.37.1.0</Data> 
  <Data>5e5b9b43</Data> 
  <Data>KERNEL32.dll</Data> 
  <Data>10.0.18362.329</Data> 
  <Data>7b5427ec</Data> 
  <Data>c00000fd</Data> 
  <Data>0001a76b</Data> 
  <Data /> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2E9.tmp.WERInternalMetadata.xml</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_ARK Smart Breedi_dd12395d8d1b23d54b161e9f28ebd5966c5400_9a4c0ac1_73221771-9c5e-4f79-834d-8c5ffea017ee</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>c31701f0-9d91-45a2-915d-60a74325613b</Data> 
  <Data>524388</Data> 
  <Data /> 
  <Data>0</Data> 
  </EventData>
  </Event>

**Comment by neostryder** [comment]
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Windows Error Reporting" /> 
  <EventID Qualifiers="0">1001</EventID> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-03-01T18:52:01.768291300Z" /> 
  <EventRecordID>27210</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Angband</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data /> 
  <Data>0</Data> 
  <Data>APPCRASH</Data> 
  <Data>Not available</Data> 
  <Data>0</Data> 
  <Data>ARK Smart Breeding.exe</Data> 
  <Data>0.37.1.0</Data> 
  <Data>5e5b9b43</Data> 
  <Data>KERNEL32.dll</Data> 
  <Data>10.0.18362.329</Data> 
  <Data>7b5427ec</Data> 
  <Data>c00000fd</Data> 
  <Data>0001a76b</Data> 
  <Data /> 
  <Data /> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA2E9.tmp.WERInternalMetadata.xml</Data> 
  <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_ARK Smart Breedi_dd12395d8d1b23d54b161e9f28ebd5966c5400_9a4c0ac1_73221771-9c5e-4f79-834d-8c5ffea017ee</Data> 
  <Data /> 
  <Data>0</Data> 
  <Data>c31701f0-9d91-45a2-915d-60a74325613b</Data> 
  <Data>524388</Data> 
  <Data /> 
  <Data>0</Data> 
  </EventData>
  </Event>

**Comment by neostryder** [comment]
ugh, xml doesn't paste in right.  save that to file for you?

**Comment by cadon** [comment]
In the source column it's usually `.NET Runtime` for the entry I'm looking for.
It should look similar to
```
Application: ARK Smart Breeding.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at ARKBreedingStats.Form1..ctor()
   at ARKBreedingStats.Program.Main()
```

**Comment by neostryder** [comment]
There are no entries for ASB with source .NET Runtime.  :/  XML for 3 entries included here.  They seem to all be from one crash.  Restart had no effect.

[ASB Error.zip](https://github.com/cadon/ARKStatsExtractor/files/4272290/ASB.Error.zip)

**Comment by neostryder** [comment]
Is the config file in the install directory just a default?  Can I look elsewhere for my modified config?

**Comment by neostryder** [comment]
Don't know if you can interpret crash dump, but...
[ARK Smart Breeding.exe.4512.dmp.zip](https://github.com/cadon/ARKStatsExtractor/files/4272295/ARK.Smart.Breeding.exe.4512.dmp.zip)

**Comment by cadon** [comment]
Yes, the settings-file in the application-folder are the default settings. Your settings can be found in a folder in `%localappdata%\ARKBreedingStats`. Each version has it's own folder which is some kind of hash-value.

Unfortunately the logs so far have no information where exception happened. What I need for this is something called a `Stack Trace`

To be sure, the application crashes for you if you open the library-file you attached in the first post, select any creature and change the `Status`, e.g. to `Unavailable`?

**Comment by neostryder** [comment]
Yes, changing status (to dead), editing name, import from ARK Export Dino, change config all cause it to exit without error message.  I will look for stack trace and test config file refresh.

**Comment by neostryder** [comment]
[Config.zip](https://github.com/cadon/ARKStatsExtractor/files/4272317/Config.zip)

**Comment by neostryder** [comment]
Delete config file seems to have corrected it.  Not crashing now.

**Comment by cadon** [comment]
Can you try the following things and see if it crashes?
* disable autosave and check if changing a creature make it crash
* save manually after a change
* create a new library without creatures and save it
* create a new library, import or extract a creature and save it

**Comment by neostryder** [comment]
Unfortunately, I seem to be okay now.  I think the last setting that I had changed was to tick Delete expired timers when saving library.  Maybe that had something to do with the error?  I really appreciate your quick attention.  I'm getting back to cataloging everything now.

**Comment by cadon** [comment]
Thank you, that's it! The timer deletion causes a crash when autosave is enabled. I'll fix that soon.
