### ISSUE TITLE
Import extraction issue in update 0.37.1.0

### ISSUE THREAD

**Issue by MangoChutney82** [cadon/ARKStatsExtractor#1028]
Hi, After the recent update I have several dinos that are showing red stats, mainly weight but these dinos used to export/import fine. One of the main ones seems to be Allosaurus, I have 2 that all the numbers work and it imports fine, the rest all show red in weight.

Many thanks

**Comment by cadon** [comment]
For fixing this issue the export-file(s) would be great.

**Comment by neostryder** [comment]
I have noticed this, too.  I have to manually extract on those.  :/

**Comment by cadon** [comment]
Uploading the export-files will help to fix that issue.

**Comment by MangoChutney82** [comment]
sorry im a bit of a computer noob...how would i get the export files to you?

**Comment by cadon** [comment]
The latest release (0.37.2) should fix that issue. If it's still not working, just drop the export-file on the text-box here, like you probably did with the screenshots.

**Comment by MangoChutney82** [comment]
Will take a look asap and let you know either way. Much appreciated and many thanks again!!

**Comment by MangoChutney82** [comment]
Amazing, all my Allo's work thank you
