### ISSUE TITLE
Name Generator removed feature?

### ISSUE THREAD

**Issue by PGMvlaar** [cadon/ARKStatsExtractor#1029]
In the past, we could generate the lowest unique number (like with {n}), but with two digits long: for example, the first number would be 01, not 1. From what I see, this feature is removed, and I did not see a replacement for it. Is this intended?

**Comment by cadon** [comment]
Hi, the naming pattern was reworked and made more flexible. You can now set the number format like you want. For example you can use `{{#padleft: {n} | 2 | 0 }}` for the old format that will pad the number with a `0` if it's only one digit, so the numbers will look like `01`, `09`, `10` etc.. `{{#padleft: {n} | 4 | 0 }}` would create numbers like `0001`, `0023`, `0241` etc.
You could also use the `format` function like `{{#format: {n} | 00 }}` to get the same effect with 2 digits. The new functions make the resulting name much more flexible.
