### ISSUE TITLE
Timer - columns width is not stored.

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#1032]
"Finished at" and "time left" are too short by default, at least for my settings/font so I tried to make it wider, but after restarting it is back to default.
Tried changing "notes" and "server" in library and both kept their new width between sessions, Seems like issue is specific to timers table.

**Comment by EmkioA** [comment]
Hello i have a fix for this here 
https://github.com/EmkioA/ARKStatsExtractor/commit/9f833b51de553945013136bd1a3051978ccd2d76
i cant do a pull request since my branch is messed up. I try to clean it
