### ISSUE TITLE
Ferox Baby classified as Ferox (Small), prevents assigning parents that are classified as Ferox

### ISSUE THREAD

**Issue by thor79** [cadon/ARKStatsExtractor#1036]
Steps to reproduce:
1. Breed a pair of feroxes so you get a baby
2. Export baby's stats and import them into Smart Breeding
3. Species displays as Ferox on Extractor screen. The baby's parents are not selected as the parents and you cannot manually select them since they are not "Ferox (Small)". Save new Ferox to the library.
4. The new Ferox baby is now classified as Ferox (Small) and is in a separate category from it's parents event though it's just a baby of them.

The small version of the Ferox, whether an adult or a baby, should have the class name Shapeshifter_Small_Character_BP_C
The large mutated version of the Ferox has the class name
Shapeshifter_Large_Character_BP_C

![image](https://user-images.githubusercontent.com/299155/76156606-bdab4580-60ca-11ea-8dbe-77027295974f.png)
In this screenshot:
The parents are "(F 205) Breeder 2" and "(M 209) H41 St29"
The baby is "(F 223) H41"

**Comment by VolatilePulse** [comment]
Yes, in Ark the Ferox (Small and Large) are treated as completely different species and can not mate. That is why ASB doesn't allow you to select a Large to be the parent of a Small. There are also tons of issues with the Ferox. My recommendation is to either only extract them while they're enraged or only when they're small. I know element is expensive, but I've discovered numerous bugs with stat calculations on the Ferox until it's been enraged at least once (twice if you're planning to extract only the large variants) but you need to extract at some point **after** the creature returns from being enraged at least once.

**Comment by thor79** [comment]
The "Ferox" in the screenshot are the small variety...adults of the small variety. The "Ferox (Small)" is a baby of the small variety. These are the same species but are not treated that way in ASB. I have not tried to extract any of my ferox while they are in their large form yet since breeding the small ones just takes up much less room. I suppose it does make sense to track the stats on the large versions since that's where I want the actual impact from the stats to be.
But thank you for the tips on when to extract them.

**Comment by VolatilePulse** [comment]
Right, that was my fault then for not reading more carefully. I really want to love the Ferox but Wildcard really messed them up. Unfortunately breeding them hasn't been something I've gotten around to yet. If you can, could you upload the export files so I can take a look to see what's going on?

I don't recall there being 3 variants, only the Large and Small variants. It is something I'm going to take a better look at as well.

**Comment by thor79** [comment]
Absolutely. 
Note: All of these have been successfully imported to ASB except "DinoExport_399477757228843404". That one I haven't been able to import due to red stat boxes.
[ArkDinoExport.zip](https://github.com/cadon/ARKStatsExtractor/files/4303796/ArkDinoExport.zip)
Here are my settings for the server I play on. (note: currently not sure if these settings allow someone to always imprint to 100% for all dinos...one of my to do things to review)
![image](https://user-images.githubusercontent.com/299155/76170213-28ee2980-6156-11ea-8da7-269e58a74850.png)

**Comment by thor79** [comment]
Ok, I see what you mean by extracting them only after they have been enraged once. The wild levels change when enraged and the small version retains the increased levels after the enragement.
Here's three females that I have exported after they have been enraged to breed.
[ArkDinoExport-3F-Enraged.zip](https://github.com/cadon/ARKStatsExtractor/files/4303896/ArkDinoExport-3F-Enraged.zip)

This is grandmother, mother, child.
Grandmother - (F 199) Breeder
Mother - (F 205) Breeder 2
Child - (F 223) H41

All have been enraged at least once to prepare them for breeding.

**Comment by VolatilePulse** [comment]
Sorry for the late response, I've been a bit busy. The reason I asked for the export files was to figure out why it categorized the baby Ferox differently than the others. I have a feeling that I know what's going on, but I'll need some more testing or one of those export files that import "incorrectly".

As far as the enraging goes, we are not troubleshooting the Ferox unless it has been enraged and returned to normal at least once. There are numerous issues with them and unless Wildcard fixes them (not likely), enraging them is the only workaround we can find.

If you prefer, we have a discord you could join for quicker responses as well.
