### ISSUE TITLE
Therizinos not calculating correctly, Oxygen stat not showing

### ISSUE THREAD

**Issue by jpyno** [cadon/ARKStatsExtractor#1037]
The Therizino is not extracting correctly, other dinos are fine but when I read the stats from OCR it collapses the oxygen stat and other stats are red, All values it does read are correct and I have tried on bred and tamed dinos. Latest version and Json
![image](https://user-images.githubusercontent.com/18641290/76162538-968a5d80-6136-11ea-802f-35db10e08947.png)

**Comment by cadon** [comment]
Hi, it's probably the wrong variant of the Therizinosaur. Select the correct variant and it should work.

**Comment by jpyno** [comment]
Hi Cadon,

Thanks for the reply. I have tried selecting the correct vanilla varient but it seems to revert to the mission one when reading via OCR, I have not got guess species checked. I can confirm that removing the mission Theri from the Json removes this issue
