### ISSUE TITLE
Breeding Plan 

### ISSUE THREAD

**Issue by CbRio85** [cadon/ARKStatsExtractor#1038]
in the breeding plan if you click on "these parents just mated" you no longer have the option to go back to the best pairings screen.
Can you put a button or tell me if there is another way?

**Comment by cadon** [comment]
Hi, what do you mean with `Best pairings screen`?

**Comment by DodoCooker** [comment]
I think he means to go back to include the "just mated" dinos: When you press this button the female gets a cooldown timer set - you can see this in the library under "Cooldown/Growing". You can reset this if you right-click on the dino in the library and select "Set to mature / ready to mate". Then it will show up again in the breeding plan.
![image](https://user-images.githubusercontent.com/4038417/77138258-a9275f80-6a71-11ea-96ed-15e9f3789ef6.png)

**Comment by cadon** [comment]
Ah. You can also just keep these creatures in the list by enabling the checkbox `Include Creatures with Cooldown`.
