### ISSUE TITLE
Import savegame error: "An item with the same key has already been added"

### ISSUE THREAD

**Issue by jasontbright** [cadon/ARKStatsExtractor#1039]
Since the latest update, whenever I try to import my local game, I get the error "An item with the same key has already been added", and the import fails.

**Comment by gbusoni** [comment]
same problem here

**Comment by cadon** [comment]
Is there more of the error text?

**Comment by PaulaMoz** [comment]
Same here. (Not sure why the "same key" info switches to Polish, but it's the same in English. )

The scenario is pretty simle, every time I click "importing from save game" it just spits this error. 

![2020-03-15 14 35 42](https://user-images.githubusercontent.com/42382968/76702515-b25ba980-66ca-11ea-9db5-173381e0be4f.png)

**Comment by cadon** [comment]
The thing that was changed in this version is the import of cryopodded creatures, so an issue while importing cryopods is most probably the cause. I could not reproduce this exception yet, I can import savefiles with cryopods in the inventory or in a cryofridge.
To further narrow down the issue, how many cryopodded creatures do you have in the savefile (rough estimate is good) and what are the places the cryopods are stored?

**Comment by cadon** [comment]
The new release 0.38.1 will display a better exception message for that error. Can you post a screenshot of the message?

**Comment by schadowstown** [comment]
![Unbenannt](https://user-images.githubusercontent.com/23734697/76706394-6c610e80-66e7-11ea-8c51-0bbb5cb7a5ba.PNG)

**Comment by gbusoni** [comment]
exactly same message here, so won't double post

**Comment by cadon** [comment]
As far as I can tell, it's a strange exception to happen there, especially because the code explicitely checks for that possibility.
To further narrow down why that exception happens, a savefile would be the best. A savefile contains all informations what is built and which creatures are owned on a server, so if someone is willing to send me the savefile for fixing that bug it would be best to do so privately, I think on discord per pm might be good. Zipping the file will reduce the file size significantly to a couple of MB.

**Comment by gbusoni** [comment]
ok i can try to zip and send. Why not adding an option to enable/disable cryopod extraction though? could be a fast way to make the program usable again, and also somehting might come handy also to players who might not want to import them

**Comment by jasontbright** [comment]
I have 5 cryofridges with all my podded dinos, so around 300.  

I'm going to try to export them in lots to a different map, see if it is associated with a specific cryopod or if there's a max limit.

I updated to 0.38.1.0, and my error message is identical to schadowstown.  That the message switches to Polish for PaulaMoz indicates to me that it might be some error in crafting a data table using native functions, thus why the generic error message was translated.

**Comment by PaulaMoz** [comment]
About 200 cryopods in cryofreezers + character inventory + argentavis inventory.

**Comment by cadon** [comment]
If you're on discord, you can send it there to me (`cadaei#4308`), or if you don't mind that other people can see the savefile, you can post it here (just drag&drop in the reply-textbox). It's best to zip the savefile first.
