### ISSUE TITLE
[Question]maxium level settings 

### ISSUE THREAD

**Issue by GoogleBeEvil** [cadon/ARKStatsExtractor#1040]
- On my playing server,dino max level is 200/240(tek dino),tamed  is 299/359 ,but there was an celebration activities ,all max lvl get extra 40 lvls，the max level used to be 240/280,tamed 359/419，though the activities lasted 7days，so what the settings should be about maxium lvl on servers
 “max lev 240; max  tamed lvlup 119” or “max lev 280 ;max  tamed lvlup 139”？

**Comment by cadon** [comment]
Take the higher values.
Using too low values will prevent the extraction of creatures with higher levels. Using too high levels may show some additional impossible level combination during the extraction, so no harm. If you won't extract any tamed creatures from that event, you can revert the settings to the lower values. Bred creatures are not affected by the max wild settings.
