### ISSUE TITLE
where are import savegame settings stored?

### ISSUE THREAD

**Issue by gbusoni** [cadon/ARKStatsExtractor#1041]
I'm trying to roolback to previous version, due to the duplicated key issue of the latest one, I copied the config file, but the import savegame settigns are not migrated in this way. I checked all files of the folder, no sign of any relevant difference. I wonder where these settings are stored...

**Comment by cadon** [comment]
The settings are stored in `%localappdata%\ARKBreedingStats`.
The bug is probably #1039
