### ISSUE TITLE
Breeding Error

### ISSUE THREAD

**Issue by powrwolf** [cadon/ARKStatsExtractor#1045]
I keep getting errors in the breeding calc. Here are the images.
https://gyazo.com/f6229684566a024600661d6500716f79
https://gyazo.com/dc8e2f01d9960925e4232bd93fc91d9b
https://gyazo.com/350c0c5e7d86441793ac4a201b68e4c5

**Comment by VolatilePulse** [comment]
It appears that your server multipliers are incorrect. Are you the server owner or have access to the `game.ini` and `gameusersettings.ini` files? These contain the specific multipliers needed for the stat extractor.

**Comment by powrwolf** [comment]
where can I get that version?

**Comment by VolatilePulse** [comment]
https://github.com/cadon/ARKStatsExtractor/releases/latest

**Comment by powrwolf** [comment]
https://gyazo.com/919a01eb90cae6b52bb05a8801e34ddb
https://gyazo.com/4c67a4fa8d11301030ecf2071223dd02
still getting an error and I went over the settings with the admin and double checked and those were the correct settings is there a way I can get access to the game.ini or gameusersettings.ini file just to be sure?

**Comment by VolatilePulse** [comment]
They can only come from a server owner and they typically aren't willing to provide them due to security reasons. If the admin does have access to the files, you can request that he sends you the lines that start with:

```ini
bUseSingleplayerSettings

PerLevelStatsMultiplier_DinoWild
PerLevelStatsMultiplier_DinoTamed
PerLevelStatsMultiplier_DinoTamed_Add
PerLevelStatsMultiplier_DinoTamed_Affinity

BabyImprintingStatScaleMultiplier
```

All other multipliers are purely for the taming and breeding portion and are unrelated to the stat extractor. They are also typically well known amongst the server admins and can be easily discovered.

**Comment by powrwolf** [comment]
you wouldnt happen do know the location would you

**Comment by VolatilePulse** [comment]
In the two files? Not specifically. Depending on who wrote it or what program was used to generate it, it could literally be anywhere. Using the text search feature for those keywords I pasted will make life much easier. The single player and imprinting ones may not exist, but I'm almost positive you will have multiples of the other 4 entries (there can be up to 12 of each one actually).

**Comment by powrwolf** [comment]
https://gyazo.com/31644a063d138ac44a38534a8159d375
https://gyazo.com/53379ae142817ad134134b0c9c81127a
https://gyazo.com/538993d443ce8b5cd1edc0d171fb1b7e
https://gyazo.com/3f064301f74dc6056b0db86c8b2de5f0
for some reason still getting errors.  heres the game.ini file with the settings i put in plus i redid the extraction after the settings and those were the results

**Comment by VolatilePulse** [comment]
It will take me a moment to go over these, but do you have any mods installed on the server?

**Comment by powrwolf** [comment]
nope

**Comment by VolatilePulse** [comment]
I'm going to need some more information from you. Is there any way you can join us on [Discord](https://discord.gg/qCYYbQK)?

**Comment by powrwolf** [comment]
Yeah I can do that :)

**Comment by VolatilePulse** [comment]
Server admin failed to provide the `bUseSingleplayerSettings=true` property and everything appears to be extracting properly now.
