### ISSUE TITLE
Library View - Tribe Column

### ISSUE THREAD

**Issue by VolatilePulse** [cadon/ARKStatsExtractor#1047]
As requested in #412, separating the owner and tribe into respective columns could improve readability. Unaware of any reasons not to do this aside from additional clutter and some users may prefer a single column for this. Personally, I'd prefer to read part of the owner name and part of the tribe name as opposed to only being able to read a long owner name and having the tribe name cut off by "acceptable" column widths.

This issue is open to debate for user feedback. Please share concerns or interest in this feature.

**Comment by cadon** [comment]
An extra column for tribes was added.
