### ISSUE TITLE
Negative Mutation Counts Problem

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#1048]
So when your trying to filter out mutation counts it doesn't pay attention to when the counter gets broken and starts issuing negative amounts.  It does record it, but doesn't filter it out when breeding.  Can still manually mark them as podded or unavailable tho.

**Comment by VolatilePulse** [comment]
This is by design and reproduces the same logic that Ark uses. A negative mutation counter is still less than 20 and can contribute to more mutations.
