### ISSUE TITLE
Timer sorting.

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#1049]
Something is wrong with my timers order.
![mytimers]( https://i.gyazo.com/fc9702b493acf459efa922d568b6a649.png)
As I understand it should not be possible with any of available sorting methods available to me (name, finished, left). Just trying to sort by time left, but can't find a way to do it.

**Comment by cadon** [comment]
The sorting is applied to the time left string, having timers with 10 days or more in the list sorts wrong. It will be fixed in the next release.
