### ISSUE TITLE
Can't get stats to read correctly with changed stats Multipliers.

### ISSUE THREAD

**Issue by Robcor4** [cadon/ARKStatsExtractor#105]
Me and a friend can't get the multipliers to work correctly with the stat extractor. Also Dragging and dropping the Game.ini of Gameusersetting.ini does'nt seem to work. We changed the miltipliers on our server but i can't get the extraxtor working. Maby i am doing something wrong. I would apreciate any help

If you need any other info just ask i'll get it for you.

**Comment by cadon** [comment]
Hi, can you send a screenshot of the stats of a creature that doesn't work and the multipliers you use?

**Comment by Robcor4** [comment]
![357 wolf](https://cloud.githubusercontent.com/assets/22221569/18586698/2af439d4-7c1e-11e6-9e4d-3ccdd7deffb3.png) These stats are from a direwolf with 0 levels they are fresh post tame stats.
![raptor error](https://cloud.githubusercontent.com/assets/22221569/18586996/02bd0462-7c20-11e6-8bf1-b5c6ed034dbf.png) this one is a raptor (Not sure but i thing server restarted)

I'll copy paste paste the part if the Game.ini thet has the multipliers.

PerLevelStatsMultiplier_DinoTamed[0]=0.30
PerLevelStatsMultiplier_DinoTamed[1]=2.00
PerLevelStatsMultiplier_DinoTamed[2]=2.00
PerLevelStatsMultiplier_DinoTamed[3]=2.00
PerLevelStatsMultiplier_DinoTamed[4]=2.00
PerLevelStatsMultiplier_DinoTamed[5]=2.00
PerLevelStatsMultiplier_DinoTamed[6]=2.00
PerLevelStatsMultiplier_DinoTamed[7]=3.00
PerLevelStatsMultiplier_DinoTamed[8]=0.30
PerLevelStatsMultiplier_DinoTamed[9]=2.00
PerLevelStatsMultiplier_DinoTamed[10]=2.00
PerLevelStatsMultiplier_DinoTamed[11]=2.00
PerLevelStatsMultiplier_DinoTamed_Add[0]=0.75
PerLevelStatsMultiplier_DinoTamed_Add[8]=0.75
PerLevelStatsMultiplier_DinoTamed_Affinity[0]=0.30
PerLevelStatsMultiplier_DinoTamed_Affinity[8]=0.30
PerLevelStatsMultiplier_DinoWild[0]=2.00
PerLevelStatsMultiplier_DinoWild[1]=2.00
PerLevelStatsMultiplier_DinoWild[2]=2.00
PerLevelStatsMultiplier_DinoWild[3]=2.00
PerLevelStatsMultiplier_DinoWild[4]=2.00
PerLevelStatsMultiplier_DinoWild[5]=2.00
PerLevelStatsMultiplier_DinoWild[6]=2.00
PerLevelStatsMultiplier_DinoWild[7]=2.00
PerLevelStatsMultiplier_DinoWild[8]=2.00
PerLevelStatsMultiplier_DinoWild[9]=2.00
PerLevelStatsMultiplier_DinoWild[10]=2.00
PerLevelStatsMultiplier_DinoWild[11]=2.00

I also have other dino's that won't extract 
I tried adding the multipliers manual but stil get errors on some stats.
![extractor error](https://cloud.githubusercontent.com/assets/22221569/18586900/77a6aa36-7c1f-11e6-9873-8ec4b5e4d83b.png)

We do run mods on the server maby they alter some settings too Idk much about al this stuff.
We run difficulty 8+ (lvl 240 wild dino's and increased player lvl) and some other but i don't think they alter dino's

**Comment by cadon** [comment]
Hi, some of your multipliers were switched, and the wild-torpor-multiplier doesn't seem to be applied in the game. Maybe the `PerLevelStatsMultiplier_DinoWild[2]=2.00` is not affecting the torpor. Anyway, by using the displayed values the provided creatures worked. Happy breeding :)

![multipliers](https://cloud.githubusercontent.com/assets/8763269/18607299/92cc0630-7cc9-11e6-98e0-fe84df4b0a04.png)

**Comment by Robcor4** [comment]
Thanks a Lot I tested it myself with the multipliers you gave me and it work without any hickups. Breeding is so much easier with this tool. I have been using it for 5 Months now and never had any complaints or issues. Keep Up the good work

Greetings From Belgium
