### ISSUE TITLE
Unable to extract extinction dinos.

### ISSUE THREAD

**Issue by TheRealMondo** [cadon/ARKStatsExtractor#1051]
I have tried with Snow Owls, Velinos, and Gachas, they will not extract what so ever. Dung beetles and others that I have around the base have no issues. I do have speedy flyers, but the mod is installed in SB. Myself and my server mate are having the same issue.

**Comment by cadon** [comment]
Hi, please post a screenshot of the multiplier settings and attach an export file of a creature that doesn't work.

**Comment by TheRealMondo** [comment]
![image](https://user-images.githubusercontent.com/32818268/77574640-b3e65800-6ea8-11ea-98a6-25b59944df80.png)

[DinoExport_275366697244267527.txt](https://github.com/cadon/ARKStatsExtractor/files/4382937/DinoExport_275366697244267527.txt)

**Comment by cadon** [comment]
It seems the BabyImprintingStatScaleMultiplier is `1.0`, not `0.2`.

**Comment by TheRealMondo** [comment]
I dragged my game and game user settings into the program to get those
stats. I will check the program and my server soon.

**Comment by TheRealMondo** [comment]
Seems that the BabyImprintingStatScaleMultiplier was not taking effect on the server side, but ASB was still detecting it in GameUserSettings.ini. Thanks for the help!

**Comment by cadon** [comment]
Can you check that ini file, if maybe that line is commented out? I don't know if that's possible, but currently ASB cannot handle that. If you know why the server didn't took that value, let me know.
