### ISSUE TITLE
Configure extraction from Nvida GeforceNOW

### ISSUE THREAD

**Issue by julienbck2020** [cadon/ARKStatsExtractor#1059]
Hello, 

I'm using NVIDA GeForce NOW,
I can't configure the game's steam window, 
I don't know what to put in the "Custom" field

Thank you

**Comment by cadon** [comment]
Usually the name of the process is displayed in the task manager. Press <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>ESC</kbd> to open it and then try the name that is displayed there. Maybe it's the name in the `Details` tab.

**Comment by julienbck2020** [comment]
for some reason i don't know it doesn't seem to read in the game window.

Thank you

**Comment by cadon** [comment]
I added a dropdown selection for an easier selection of the correct process. Check if you can find the correct process in the latest version 0.39.3.

**Comment by julienbck2020** [comment]
thank you for your answer, I installed the new version and I see the function that allows you to choose NVIDA now.

The OCR is random but works more or less.

Thank you

**Comment by cadon** [comment]
Good to hear. The OCR is not very good with text. If an error is done consitently, you can tweak the recognitin a bit (https://github.com/cadon/ARKStatsExtractor/wiki/OCR).
