### ISSUE TITLE
Last 3 versions didn't autoupdate successfully.

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#1060]
ASB would notify me of update available and after I accept to download and install, it closes the application and nothing happens.
 Couldn't find any sort of log in its folder so not sure what is going on.
Manually downloading and updating via zip works fine.

**Comment by cadon** [comment]
Yes, there were some issues with the updater in some releases, where the update process got canceled due to some invalid folder names. The one in 0.39.3 is supposed to work.

**Comment by VolatilePulse** [comment]
We will continue to monitor the updater in future versions, but as the latest version should now be working properly, the issue will be closed. If it doesn't work properly for the next release, a new issue should be created, or this one reopened. 

Thanks for your feedback!
