### ISSUE TITLE
Pedigree not being imported

### ISSUE THREAD

**Issue by FiremanDJ** [cadon/ARKStatsExtractor#1063]
Unofficial server with 15x rates.
Ragnarok map.
Classic Flyers.

Smart Breeder isn't importing (or ark isn't Exporting any more) the pedigree information.
So, parents aren't automatically selected and mutations not detected.

This has occurred on Doeds, Pteras, Argies and Rexs (the only tames I've bred so far).

I'm sure in the past this was done automatically, unless I'm quite mistaken.

**Comment by VolatilePulse** [comment]
This is a known Ark issue. To work around it, we recommend opening up the ancestry tab on a creature to force the data to be downloaded from the server before exporting.
