### ISSUE TITLE
377 vs 362 max born?

### ISSUE THREAD

**Issue by Xtasroth** [cadon/ARKStatsExtractor#1068]
It's my understanding that the max born at is now 362 instead of the old 377. Anything listed not able to be fully leveled always showed up in red for me but I dont think this is reflected in current release. Old gainable levels was 73 now its 88.

**Comment by Xtasroth** [comment]
Apparently that's X-Creatures and Genesis exclusive creatures only that can go 88.

**Comment by VolatilePulse** [comment]
The max of 88 levels apparently only applies to X species from Genesis.

While we are aware of this, we are currently unaware of how to provide this data to ASB at the moment and suggest everyone to be aware of it while playing on official servers until we can find a way to distinguish these species.
