### ISSUE TITLE
Cant figure out how to get dino into library

### ISSUE THREAD

**Issue by jasjr** [cadon/ARKStatsExtractor#107]
Ok followed these steps but missing a huge section at the end

-  Click "Extract Level Distribution"
-  Now you can see the wild- and domesticated levelups of the different stats. If stats or controls are   yellow or red, see below.

So far so good.

-  Store your creature in the library to compare it to others and see which one is the best for your next breeding session.

How do you store the dino?  I see no button that says save dino, but i do see where i can save library,  I can copy to test but not to library.  Um am i missing something?    Also there are button it looks like under cool down and grow in on the extractor tab but they are cut off and can not see the buttons except the very top of them.  Any help would be great, thanks.  Over all I like what i see in this program.

**Comment by jasjr** [comment]
Ok so after adjusting window size did not do any thing, i closed the app and reopened it and now it shows every thing,

**Comment by cadon** [comment]
Hi, that's something I experienced once, but never could it reproduce. Glad it worked for you after reopening the app.

**Comment by cloakedninjas** [comment]
Yes this happened to me, Windows 10. First open the corner resize toggle doesn't affect the app, just Window's own window. Have to restart for it to take affect.
