### ISSUE TITLE
Library - half the columns weak colouring / ignored

### ISSUE THREAD

**Issue by temar96** [cadon/ARKStatsExtractor#1070]
Column Oxygen, Weight, Damage and Speed seams to lack correct colouring
none are a strong green 
and Tp% will show 100 even so those stats might be low
Top doesn't count those stats even if they are highest
https://i.gyazo.com/9f639850e712efc7eaf9f7c7c95bd929.png

**Comment by temar96** [comment]
Also all stat weighting under Breeding plan are set to 1.0, I tried playing about to no effect.
tried re-downloading, tried new save file, tried previous version

**Comment by cadon** [comment]
There's a setting for that in the library-tab: Bottom left, the tab `Stats`. You may need to click on the small arrow heads to the right to see that tab.

**Comment by temar96** [comment]
on never noticed there was tabs there, thank you
