### ISSUE TITLE
Mutation count

### ISSUE THREAD

**Issue by temar96** [cadon/ARKStatsExtractor#1071]
I noticed 1 of the dinos had +3 mutation while everything else had nothing
I assume this is due to parents not being set on them all
so I went and set the parent on the relevant dinos
I could see the +1 on the parent when looking at stats under pedigree however it still shows +0 mut
instead of +1
https://i.gyazo.com/671d373ea30868436e9cbb7a4b03b16a.png

**Comment by cadon** [comment]
If the creatures are imported, the mutation counter is set automatically. If you entered the stats manually, you have to set the mutations manually as well. You can edit the creature by pressing F2 in the library and then setting the mutations accordingly.

**Comment by temar96** [comment]
odd we do use import
and edit even lists ark-id because we imported
https://gyazo.com/ca7edfbc3dacc31ad5bf93edfa734ba8

**Comment by temar96** [comment]
here is the dino ingame
https://gyazo.com/adc6354f3471332631ca49c94b58c5ae

I tried to export again and it seams to work fine, so unable to reproduce
here is the original export file:

[DinoExport_35394376418200638.txt](https://github.com/cadon/ARKStatsExtractor/files/4536876/DinoExport_35394376418200638.txt)

this is the new export file

[DinoExport_35394376418200638.txt](https://github.com/cadon/ARKStatsExtractor/files/4536878/DinoExport_35394376418200638.txt)

**Comment by cadon** [comment]
You probably didn't open the ancester view of the creature before you exported the first file. ARK won't include ancestor information unless you open that window once.
