### ISSUE TITLE
Check for new Colors 

### ISSUE THREAD

**Issue by blubstar86** [cadon/ARKStatsExtractor#1074]
Hello, it would be awesome, when you extract the stats from the Last Exportet Dino, to see if this dino has any new colors you dont have in your library, like you see Yellow higlightet stats if you dont have them in your library.

A second wish would be to see the stats from the parants in the "Extractor" page, like something simular to the Pedigree page but without the need to add the creature to the library.

![image](https://user-images.githubusercontent.com/47928255/80584097-7af25380-8a11-11ea-9633-b941da3de4a1.png)

**Comment by Worldgate** [comment]
It would be pretty awesome if it could export the color table of colors you have and filter colors you want.  For example, lets say you want all dinos with 'white (ID 18)' and 0 mutations, it would filter anything that doesn't have at least 1 white region and 0 mutations.
