### ISSUE TITLE
Name generation issue

### ISSUE THREAD

**Issue by Juggernaut1994** [cadon/ARKStatsExtractor#1077]
Hello
I've got issue recently with name generation
My last tamed Rex called "RexM61 G0 GN26" 
Formula is simple: {species}{sex_short}{sn} G{gen} GN{genn}
But after new tame, generator wants to name new Rex the same name which is already exists, where it should be "RexM62 G0 GN27"
In happens for no reason and in some cases, which breaks naming of the next dinos
They have different date, arkID, color and etc. so it's not possible to mistake them for no reason

**Comment by VolatilePulse** [comment]
This is difficult to troubleshoot without also having your library. Are you able to upload the library (.asb file) here or on our Discord (you can send it privately to one of the developers).

**Comment by VolatilePulse** [comment]
Resolved with a recent release.
