### ISSUE TITLE
software problem with high level dino

### ISSUE THREAD

**Issue by matracers** [cadon/ARKStatsExtractor#1078]
Hi guys, 
I play on an unofficial server with wild Dinos up to level 450. 
and the software doesn't handle the high level very well.

**Comment by VolatilePulse** [comment]
In what regard? We haven't ran into any issues with a max wild level of 600 on our server and other users have no issues with creatures with levels exceeding 1200.

**Comment by matracers** [comment]
Okay, it may be a bad setting of my game I will send screens during the day of the problem I encounter when recording statistics Manual or automatic.
Thank’s

**Comment by matracers** [comment]
![image](https://user-images.githubusercontent.com/4290299/82470000-10d74680-9ac5-11ea-8418-2fc192ed37e8.png)

**Comment by matracers** [comment]
here are the dino statistics.
![image](https://user-images.githubusercontent.com/4290299/82470162-47ad5c80-9ac5-11ea-9681-f1e7773f4068.png)

**Comment by cadon** [comment]
It works fine for me with the default settings. I guess you have set some multipliers to wrong values.

**Comment by matracers** [comment]
My settings 
![image](https://user-images.githubusercontent.com/4290299/82474704-bdb4c200-9acb-11ea-941d-b552564ad805.png)

**Comment by cadon** [comment]
If you set the BabyImprintingStatScaleMultiplier to the default value of `1`, it works.
If you only recently changed that multiplier, some creatures may not have considered that new value yet.

**Comment by matracers** [comment]
ok I made the change but it doesn't work every time

**Comment by cadon** [comment]
Then I'd need a screenshot of a creature where it doesn't work with the new multiplier.

**Comment by VolatilePulse** [comment]
There is also a known bug in Ark where imprinting doesn't always increase the stat values. To work around this, you need to force the creature to recalculate it's stat values. You can use a cryopod (highly recommended), unload/download the creature from a beacon or obelisk (may not always work or be prohibited on your server), or re-render the creature (all players must leave the area for a period of time or after a server restart).

**Comment by cadon** [comment]
Closed due to inactivity.
