### ISSUE TITLE
BUG: Added date resets with every import

### ISSUE THREAD

**Issue by BigKahuna3** [cadon/ARKStatsExtractor#1080]
I have 577 dino's in my library 361 of them have started updating their Added date/time to be every time I import from saved game.  This has been happening for about 3 weeks now.

[BigKahunaArk.zip](https://github.com/cadon/ARKStatsExtractor/files/4669852/BigKahunaArk.zip)

**Comment by cadon** [comment]
thanks for the report. This will be fixed in the next release
