### ISSUE TITLE
Tiny issue in latest update and feature idea

### ISSUE THREAD

**Issue by neostryder** [cadon/ARKStatsExtractor#1082]
Hey, Cadon, as always, thank you for what you do!  I love your tool!  One minor change in the latest update has affected my ability to rapid-fire export and evaluate dinos.  It's not a huge deal, but I wonder if it was an unintentional change.  When I would export previously, with auto-import turned on, of course, I would be dropped on the Extractor tab.  I got used to Ctrl-tabbing to get back to the Library, where I would be conveniently taken back to the same dino I had been on previously.  Since this update, however, when I get back to the Library tab, every time, it switches the selection to All instead of taking me back to the class of dino I had been on.  If this was unintentional, might you have a look and see if you can either a) change it so it takes us back to the last selection we were on in the Library or b) automatically select the class in Library of the latest import.  With how many I process during breeding, this would make a HUGE difference for me.

Now the feature request.  Please forgive me if you have already explored this.  I really like the new filter functionality that you added.  It is awesome to be able to filter for colors now, and I thought the implementation for conditional filters was very clever!  Do you suppose, in addition to this new functionality, it would be possible to add a live search field in the Library, and maybe Breeding Plan tabs, where it could filter down as you type to list only the dinos where certain fields (name, species, gender, note) match the search string?  Obviously, I don't know how complicated it would be to do something like this, but it would make your already great app even greater.  :)  I particularly like how the live search in ARK inventory works.  You can type multiple space-delimited terms and it returns everything that matches all terms typed, if that inspires you in any way.

Anyway, I probably shouldn't have combined the feature idea with the issue report, but I don't know where else I would have communicated it to you.  Please forgive if my feedback etiquette is lacking.  Thank you again, for your time and hard work!

-Aaron

**Comment by cadon** [comment]
Hi, in the next release the species selection will select the species of the last import.
Why do you tab to the library, what infos do you want to look up there? Maybe if you enable the overlay (button on the right top), you don't have to tab back to ASB at all.
In general it's better to have one issue per report, so each can be worked on independent. I'll move the second part to a new one.

**Comment by Xtasroth** [comment]
The title was changed to the correct issue, but appears to be closed. Issue is still happening. Is this working as intended?

**Comment by cadon** [comment]
The issue is fixed in the code, but not yet released.
