### ISSUE TITLE
Would it feasible to have the pedigree tab show entire pedigree instead of clicking through each parent?

### ISSUE THREAD

**Issue by Dakintosh** [cadon/ARKStatsExtractor#1084]
If this is already a feature please point me in the right direction. I've moseyed through the settings to no avail.

**Comment by VolatilePulse** [comment]
I'm not sure that idea is practical for large, complex trees. I think a better option might be to allow the creatures shown in the Pedigree to be clicked on for quick navigation. Even showing 2 generations (instead of the current 1) can get messy and complicated.

**Comment by cadon** [comment]
New views for displaying large pedigrees have been added in version 0.47, depending on the screensize it can display around 7 generations on one screen.
