### ISSUE TITLE
Web version/Mod

### ISSUE THREAD

**Issue by PaulLiuEngineering** [cadon/ARKStatsExtractor#1086]
Hello there! I am willing to contribute making this calculator in to a web-app, or maybe even better-making it into a mod people can install so they don't even have to type in the calculator, but extracting the data directly from the game.

**Comment by VolatilePulse** [comment]
The extractor is necessary to convert status values into stat levels. This isn't necessary if you have access to the game data as the levels are stored and can be written directly (this is how the Spyglass mods work). A mod wouldn't support every platform that ASB currently supports, doesn't support official servers, and is at the mercy of a server owner to add.

That being said, we have attempted a web version previously to address many of the short comings of the program, however, we were unable to find a platform that met all of our criteria and we're met with numerous financial issues with the approaches we selected. It's not impossible to create a web version and we're willing to provide any information you'd like to help, but there are plenty of downfalls associated with creating and ASB equivalent on the web. An extractor by itself is feasible, but the issues will be how you store and access user data.

If you would like to talk about this further, I'd invite you to chat with us on Discord.

**Comment by PaulLiuEngineering** [comment]
Yes of course! That will be great!

**Comment by PaulLiuEngineering** [comment]
My discord name is SmightyCreep#1468

**Comment by VolatilePulse** [comment]
I'm unable to contact you, but the server's link is https://discord.gg/qCYYbQK
