### ISSUE TITLE
Error opening library

### ISSUE THREAD

**Issue by relentl3ss** [cadon/ARKStatsExtractor#1087]
Has been flawless until tonight and I'm definitely losing my mind as all my breed info is not accessible. When I open Ark SB, I receive the error in the screenshot. How can I fix this or at least somehow pull the data into a new library?!!!!

Screenshot: https://imgur.com/0knug3t

**Comment by VolatilePulse** [comment]
I can't make out what the error actually is due to low resolution or compression. I'd suggest trying a backup file but I'm not sure what caused the issue to begin with.

**Comment by relentl3ss** [comment]
Not sure why you can't read it. Did you click on the magnifier to expand the image? Either way, here is the error:
[file path] is just to shorten that path to the file.

Error while trying to read the library-file [file path]\Retribution.asb

File
[file path] Retribution.asb couldn't be opened or read.
Errormessage:

Unterminated string. Expected delimiter: ". Path
'creatures[23].motherguid', line 1, position 20480.

Unfortunately, no backup as I just joined the tribe a little over a week ago on Crystal Isles and have been frantically trying to make heads or tails of their current tames/breeds. or is there an automatic backup I'm not aware of? Still pretty new to SB. It's a mess. I can send you the file or I posted on my amazon drive. Hopefully the file link works. I opened in Excel and it almost appears as if the data was cut off, but I don't know how the data structure works so I am not sure the best path to opening and trying to troubleshoot it myself. Either way, guessing it's corrupted which means a ton of damn work to rebuild it. https://www.amazon.com/clouddrive/share/zyNrrZqhKsLQGxqb58a7WH2buuU6gtXQcGt1gD3AB2i

Appreciate any help!

**Comment by cadon** [comment]
Hi, it seems some parts of the file are missing (VolatilePulse, you can click on the image for a better resolution). The only reason why this could happen I can think of is an error while the file was synchronized; do you have that file shared with dropbox, googledrive or similar?
If you have enabled the backup setting, you should have some backup files of your library. If not, you can delete the broken data from the file to open it again (with some data missing). I suggest using a json-editor to see where the file is corrupt, e.g. https://jsoneditoronline.org/.

**Comment by VolatilePulse** [comment]
Imgur has that feature disabled on mobile devices apparently. But it looks like the library isn't corrupt and as per Cad's suggestion, eliminating the offending data will resolve the issue. If you can't work it out before I'm out of work (about 8 hours), I'll take care of it then.

**Comment by cadon** [comment]
Here's your library file repaired (remove the extension `.txt`), but all the settings, including the server multipliers are in the part that got cut off. Maybe you hit some kind of file size limit where you saved that file, the length of the corrupted file with 20 480 doesn't look random.
[RetributionRepaired.asb.txt](https://github.com/cadon/ARKStatsExtractor/files/4832777/RetributionRepaired.asb.txt)

**Comment by relentl3ss** [comment]
Thank you. Much appreciated. I lost a lot, but can start to recover. Appreciate the help. I auto back up pretty much everything in my life. Don’t ask why this isn’t lol
