### ISSUE TITLE
Image zip file name changed

### ISSUE THREAD

**Issue by Toriansel** [cadon/ARKStatsExtractor#1089]
The file containing the images is now named img.zip and the various readme files and changelogs use the file name images.zip. The links to download the file with dino images are all now broken.

**Comment by cadon** [comment]
Thanks for the report. I removed the info in the readme, it's no longer needed, the images can be downloaded automatically from the app now. The links in the old release notes are just outdated and probably never used again. Did you find other invalid links?

**Comment by Toriansel** [comment]
Nope, just the main readme. I didn't even realize the images can be pulled from the gui. I was still following old instructions I  half remembered.
