### ISSUE TITLE
Ankylosaurus Body Natural Coloring

### ISSUE THREAD

**Issue by VenomX1241** [cadon/ARKStatsExtractor#109]
Hi, the color selection of my ankylosaurus' back displays all possible colors regardless of the "Natural Colors" box is checked. I just updated to the latest release, 20.7, and the problem persists.

Separately, this tool is absolutely amazing. Exceptional job in the development.

![ank_body_coloring](https://cloud.githubusercontent.com/assets/12982766/19019325/da049cca-8849-11e6-862e-de41bcd93458.PNG)

**Comment by cadon** [comment]
Hi, thanks for the report. Strangely, I haven't found any specific colors for the Back-region, so I didn't exlude any. If I find them, I'll add them.

**Comment by VolatilePulse** [comment]
This issue got lost amongst other features and bug fixes but has finally been tested and will be fixed in the next release.
