### ISSUE TITLE
Torpidity Failing Extract?

### ISSUE THREAD

**Issue by khade123** [cadon/ARKStatsExtractor#1091]
Most of my tames are failing to extract properly (screenshot below). It seems to be pointing towards Torpidity each time as the issue. I have updated my settings to match our server settings, cryo-ed/un-cryo-ed, uploaded and downloaded, etc.

I have one Carbo that seems to extract fine for some reason. It works for that one even without changing the settings.

![image](https://user-images.githubusercontent.com/67708605/86279896-cb6c6580-bba8-11ea-8539-a7347ddfbd3b.png)

**Comment by khade123** [comment]
![image](https://user-images.githubusercontent.com/67708605/86280130-3a49be80-bba9-11ea-98e3-0d9e128a1f05.png)

**Comment by cadon** [comment]
The first screenshot is cropped, so it's not clear which species you tried to extract, but most likely the issue is a wrong value of the BabyStatScaleImprintingBonus (as written in the first possible reason for the failed extraction). Ask your admin for that value and set it in the settings of Smart Breeding, probably it's just that.

**Comment by khade123** [comment]
The error message says to check BabyStatScaleImprintingBonus, but the settings only seem to have BabyImprintingStatScaleMultiplier. Are these the same? I assumed they were and it does match BabyImprintingStatScaleMultiplier on our server, which is set to 1 (default).

Better Image of a failing upload with species:
![image](https://user-images.githubusercontent.com/67708605/86394220-35017800-bc6c-11ea-8331-b2092886f2c9.png)

**Comment by khade123** [comment]
Settings screen:
![image](https://user-images.githubusercontent.com/67708605/86394306-5d897200-bc6c-11ea-884f-f65fe89b4f66.png)

**Comment by cadon** [comment]
Oh, you're right, the name is wrong. `BabyImprintingStatScaleMultiplier` is meant in both cases, I'll fix that.
Regarding your issue, it's probably something else. I checked some combinations, and it works for the mammoth and the carbonemys if you set the multiplier for the wildLevel of weight to `2`. It's not garuanteed that's the correct value, but it's a strong hint that at least one stat multiplier is not equal to the value of the server.

**Comment by khade123** [comment]
I went through all the settings again for like the fourth time and yep that and one other I had missed! Thank you so much for the help and the great app!
