### ISSUE TITLE
Torpor values correct but not loading

### ISSUE THREAD

**Issue by jaksusthedragon** [cadon/ARKStatsExtractor#1093]
![Capture](https://user-images.githubusercontent.com/67761616/86406435-19549c80-bc81-11ea-8258-87bbe172208e.PNG)

I don't know what the problem is, but I've tried redownloading the page. I tested many different dinosaurs and the errors are exactly the same every time. Torpor values are correct, as well as all other stats. Stat multipliers are default, and I adjusted the breeding settings to what we have in my private server.

**Comment by VolatilePulse** [comment]
I haven't tested it yet, but at a quick glance, it looks like you may have forgot to set the Singleplayer setting for your multipliers. This is common on Single Player games, as well as some custom servers.

**Comment by jaksusthedragon** [comment]
I don't know why but you were right, that was the problem, thank you! :3
