### ISSUE TITLE
Experimental OCR tab won't accept images

### ISSUE THREAD

**Issue by Silverr12** [cadon/ARKStatsExtractor#1096]
I am trying to create a config file for my resolution (1920x1200) and am trying to follow along with the guide but the large grey space does not accept images and dragging it anywhere else leads to an error popup about either incorrect resolution if any are open and an error for no ocr configured when none is loaded

(Logging and Editting) is enabled
Screenshot resolution is 1920x1200
![Screenshot (661)](https://user-images.githubusercontent.com/48173453/88063021-e846f800-cbac-11ea-8375-3fa036013011.png)

Apologies if I am doing something wrong the custom OCR window is a bit hard to read

**Comment by cadon** [comment]
Apparently that doesn't work anymore, must be quite a while. Usually people use the import exported method now, as it's pretty fast, very reliable and also includes the colors and ancestors (if the ancestry screen is opened before the export).
Anyway, to create a new OCR-config, in the `Expreimental OCR`-tab go to the `Labels` tab, at the bottom set the resolution to 1920 x 1200, then in the `OCR Info` tab click `save OCR config as…` and name it e.g. `ocr_1920x1200_100.json`. Then you can proceed with the manual on https://github.com/cadon/ARKStatsExtractor/wiki/OCR. Again, be sure to check out the import exported method first, it may be more comfortable.
