### ISSUE TITLE
Dimorphodon Health stat can't be validated for import.

### ISSUE THREAD

**Issue by Pingger** [cadon/ARKStatsExtractor#1097]
No matter which Dimorphodon I try to import, the validation for the health attribute fails and I can't click import ...
This occurs with OCR and manually entering the values.

PS:
ARK: 312.57
ASE: 0.40.4.0

![image](https://user-images.githubusercontent.com/4761298/88459205-d9ee2a00-ce93-11ea-8955-caa3ba9ed83d.png)
![image](https://user-images.githubusercontent.com/4761298/88459220-030eba80-ce94-11ea-9f79-1f25de40e83a.png)

The Servers configuration files
[GameUserSettings.txt](https://github.com/cadon/ARKStatsExtractor/files/4975708/GameUserSettings.txt)
[Game.txt](https://github.com/cadon/ARKStatsExtractor/files/4975709/Game.txt)

**Comment by VolatilePulse** [comment]
It appears to work fine for me using default settings for the stat multipliers and single player beging disabled (per your ini files). I'm not sure what is causing your issue, but I did notice there are multiple dimorphodons and you may have picked the wrong one or your stat settings may be incorrect. 

![Screenshot_20200725-124553.png](https://user-images.githubusercontent.com/6995232/88461812-d26b5880-ce74-11ea-8a1a-c81b7367ad93.png)

**Comment by Pingger** [comment]
I double checked the settings ... still doesn't work
![image](https://user-images.githubusercontent.com/4761298/88466362-dffffd00-cecb-11ea-9f56-925fea78efe0.png)

**Comment by Pingger** [comment]
OK ... I found the issue ... There are 2 Dimorphodon Listings ... The OCR and myself always picked the wrong one ... 
One is "Dimorph_Character_BP.Dimorph_Character_BP"
The other is "Dimorph_Character_BP_Agressive.Dimorph_Character_BP_Agressive" (with this one it breaks, but without looking at the tooltip for the canonical name, there is no visual indicator which one is selected ...)
