### ISSUE TITLE
Casteroides speed

### ISSUE THREAD

**Issue by axi92** [cadon/ARKStatsExtractor#11]
Something at the Casteroides speed is wrong:

These are the stats of the casteroides we have tamed.
But the calculator wont accept the stats only if I change speed to 100 it will work.
http://steamcommunity.com/sharedfiles/filedetails/?id=641185596
![1](https://cloud.githubusercontent.com/assets/1394837/13613552/e0bee9a6-e56c-11e5-9f3c-d6eba5648ea4.jpg)

**Comment by cadon** [comment]
Hi, thanks for the feedback! There was an error in the speed-stat. You can get a fixed stat-version by clicking on ? -> Check for updated Stats... in the menu.
