### ISSUE TITLE
Bred Argent stats not recognised

### ISSUE THREAD

**Issue by richie2838** [cadon/ARKStatsExtractor#110]
Hi, I'm new to this tool, it seems pretty amazing, but I can't seem to get it working with my bred argent.  I've attached a screenshot.  Any help muchly appreciated!
![ark](https://cloud.githubusercontent.com/assets/22636783/19111706/e83706be-8af8-11e6-8eb7-1af613e192b6.png)

**Comment by cadon** [comment]
Hi, imprinted stats cannot be recognized by the tool, so you have to input them before you start the imprinting.

You could also try to find the values in the tester-tab by setting the wild-levels manually, with the imprinting bonus applied. The game sometimes doesn't apply the bonus to all stats, so it may work or not so well. This unreliability of the game makes it hard for the tool to do this automatically.

**Comment by richie2838** [comment]
Ah ok I hadn’t realised that the tool couldn’t recognise imprinted stats.  It maybe is there already and I missed it, but it would be useful to have that flashed up somewhere?

Thanks for your help.
Richie
