### ISSUE TITLE
Imprinted dino - doesnt import

### ISSUE THREAD

**Issue by JM4nG** [cadon/ARKStatsExtractor#1104]
Hi Mate,

Me again just raised first dino 100% imprint and i cant get it to work, can you do your magic please?
[DinoExport_209924241157754300.txt](https://github.com/cadon/ARKStatsExtractor/files/5044562/DinoExport_209924241157754300.txt)

**Comment by VolatilePulse** [comment]
Setting `BabyImprintingStatScaleMultiplier` to `2.0` appears to work fine for you.
![image](https://user-images.githubusercontent.com/6995232/89703843-8c0a0500-d91c-11ea-92fe-844217441d2c.png)
