### ISSUE TITLE
Autoload causes weird behaviors in several screens

### ISSUE THREAD

**Issue by iamwyza** [cadon/ARKStatsExtractor#1105]
When setup to be shared by multiple people, whenever autoload occurs and the library updates, certain parts of the interface lose where they are.  The more people with the library open, the worse it gets (it's annoying with 2 people, it's almost unusable with 5).

1. Pedigree Window - Sometimes whatever creature you have selected will just become unselected.
2. Breeding Plan - Everything below the "Best possible" block will disappear
3. The Stat-Chart in both stat testing and library will reset to 0.
4. The Selected Species seems to also persist across saves, so if you change the species you're working on, the next time another person saves, the selected species goes to theirs.

[Edit: added item 4]

**Comment by cadon** [comment]
Hi, the latest version v0.42 should have adressed these issues. How does it work now?

**Comment by iamwyza** [comment]
Definitely a big improvement thanks!
