### ISSUE TITLE
Do not add to library

### ISSUE THREAD

**Issue by JennyPh** [cadon/ARKStatsExtractor#1107]
Whenever I'm going to add an exported dino to the library, it doesn't export even if I put all the settings correctly. This is from an epic cross server with steam

**Comment by cadon** [comment]
Hi, does the export file appear in the export folder? If the creature values appear in ASB and the extraction fails, check the possible reasons in the list on the right in the app.

**Comment by cadon** [comment]
Closed due to inactivity
