### ISSUE TITLE
Speed <> Torpor bug on "Stat testing" tab

### ISSUE THREAD

**Issue by Copperfild** [cadon/ARKStatsExtractor#111]
![torpor](https://cloud.githubusercontent.com/assets/22907759/19470536/92c68792-9528-11e6-9c8b-1e0caa8ce0d8.JPG)
When changing "speed" field on "stat testing/editing" tab, values "current value" and "breeding value" (of speed) do not changing, but changing "Torpor wild" field....

**Comment by cadon** [comment]
Hi, the speed does not increase for any creature in the wild, so increasing the wild-level of speed does nothing to the speed-value. The torpor-level on the other hand is just the sum of all other stat-levels, so the torpor does get increased by that.

**Comment by Copperfild** [comment]
Aaah! Understand! Thank you!
