### ISSUE TITLE
Tech Raptor 100% imprint doesnt wrk 

### ISSUE THREAD

**Issue by JM4nG** [cadon/ARKStatsExtractor#1111]
Hi Mate,

Got a tech raptor that doesnt want to import, can you work your magic on it please?
[DinoExport_493156973119661693.txt](https://github.com/cadon/ARKStatsExtractor/files/5090714/DinoExport_493156973119661693.txt)

**Comment by cadon** [comment]
The stat multipliers are not set correctly. It's best to ask the admin of the server for the correct settings. This is a combination that works, but it might be only this creature that will work. Just drag & drop the file on the settings window.
[ASBMultipliers.txt](https://github.com/cadon/ARKStatsExtractor/files/5090986/ASBMultipliers.txt)
