### ISSUE TITLE
Extract Level Distribution not working

### ISSUE THREAD

**Issue by randomsteve777** [cadon/ARKStatsExtractor#1112]

**Comment by cadon** [comment]
Hi, good to hear it's resolved. It sounds like you used the OCR-feature, which sometimes cannot recognize the species correctly. If you're using the steam version, the import exported method is recommended, it's more precise and also includes the colors and ancestors (you need to open the ancestry tab ingame first for that). For more infos see https://github.com/cadon/ARKStatsExtractor/wiki/Importing-Creatures
