### ISSUE TITLE
Am I doing something wrong?

### ISSUE THREAD

**Issue by xObscuritas** [cadon/ARKStatsExtractor#1113]
I want to add this quetzal to my libary, but the extract option isnt really "satisfied" with the health field.
Im playing on my own server, so I have all the custom files and dragged them into the settings:
![Unbenannt](https://user-images.githubusercontent.com/40633324/90967324-e6d75b00-e4dd-11ea-8821-c2f0474c1800.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/40633324/90967325-eb037880-e4dd-11ea-82f8-2b3053df8a9f.PNG)

**Comment by cadon** [comment]
Hi, you probably have solved it already. It seems you have enabled a mod like Classic Flyers which changes the stat values of species. Enabling the mod classic flyers in ASB will make it work.
