### ISSUE TITLE
Red extraction on health that won't go away no matter what I do

### ISSUE THREAD

**Issue by azhefa** [cadon/ARKStatsExtractor#1115]
I have tried multiple times to get this argent into my library as well as another, but every time the health is marked red and unable to be extracted. All of the settings are the same as what I'm using in my solo play through and all of the stats are correctly inputted. I'm also on a PS4 and not pc so I put everything in manually.

![2020-08-27 (2)](https://user-images.githubusercontent.com/70332805/91459772-08757100-e855-11ea-8c9b-4522fbae2fb0.png)

**Comment by VolatilePulse** [comment]
Best guess, you forgot to enable Single Player settings in ASB. I assume no other tamed creatures work for you either. That should fix you right up.

**Comment by azhefa** [comment]
All my other tames worked fine when I added them from Ragnorak but now it's not working on the Island, everything is the same settings wise. I'll try the single player settings in the morning and see if that fixes it.

**Comment by cadon** [comment]
With singleplayer enabled and assuming a tamed creature with a total level of 161, it works. I'm closing this issue for now, if you're still having problems, feel free to reopen it.
