### ISSUE TITLE
Imprinted dinos and leveled dinos wont extract

### ISSUE THREAD

**Issue by kame321** [cadon/ARKStatsExtractor#1118]
HI, I am playing on a unofficial server and I was able to get the game.ini and gus.ini files from the admin. I dragged them over to the settings in ark smart breeder and the imprinted dinos and leveled dinos wont extract.
![ark 1](https://user-images.githubusercontent.com/70610139/91913164-94830080-ec7a-11ea-9553-6f0b5832f40d.PNG)
![ark 2](https://user-images.githubusercontent.com/70610139/91913168-94830080-ec7a-11ea-9ca9-1b6695818750.PNG)
[gus.ini.txt](https://github.com/cadon/ARKStatsExtractor/files/5159146/gus.ini.txt)
[Game.ini notpad vers.txt](https://github.com/cadon/ARKStatsExtractor/files/5159150/Game.ini.notpad.vers.txt)

pls help. ive been trying to get this to work for a two weeks now

**Comment by cadon** [comment]
Hi, the reason is most likely the imprinting bug, described in the red box in the second screenshot at the bottom right. Did you try to cryo/uncryo the creature? Do other non-imprinted creatures work?

**Comment by kame321** [comment]
The admin gave me outdated files. problem solved
