### ISSUE TITLE
Ankylosaure add problem

### ISSUE THREAD

**Issue by Vykan** [cadon/ARKStatsExtractor#112]
Hello, i've claimed 2 ankylosaure and i can't add them to my library, i've try a lot of solution but don't find the right one...
Could you help me ?

Thanks for your really good and usefull job :)
![tdp f smart](https://cloud.githubusercontent.com/assets/22913843/19480593/a240b3de-9553-11e6-9bf9-3c07d6057c9d.png)
![tdp m smart](https://cloud.githubusercontent.com/assets/22913843/19480596/a25f5ce4-9553-11e6-993b-06f2e53d5fa6.png)
![tete de pioche f](https://cloud.githubusercontent.com/assets/22913843/19480595/a2499ad0-9553-11e6-9838-7d4fdba82486.png)
![tete de pioche m](https://cloud.githubusercontent.com/assets/22913843/19480594/a2460d48-9553-11e6-9b37-06d82c89daaf.png)

**Comment by cadon** [comment]
Hi, the tool cannot handle imprinted creatures, as the game shows only a rounded number for that (e.g. 98%) instead of the real number used (e.g. 97.84%), so it's complicated to extract the correct values. For now you cannot extract the creatures. A work-around that works with creatures you haven't leveled up yet is to go to the Tester-tab in the tool, check the "bred"-checkbox, set the imprinting-quality and increase the wild-level until the value is close to the value in the game.

Also see #59.

**Comment by Vykan** [comment]
Hello, what you said is what i've understood when i see how to make it.
But still one doubt how could i be sure to have good stat level because it is a claimed pet and the old owner had certainly made up some stats ?

Thank you for soon answering.

**Comment by cadon** [comment]
The anky "Tete de Pioche M" wasn't leveled up (the next experience-goal is still at 10, which is the first levelup), so for this one it should be not so hard to get the wild-levelups. The other one already has 28 domesticated levelups (see https://ark.gamepedia.com/Levels, the 4350 is for level 29), so you could try a bit if you find the correct combination. Mostly HP or Melee are leveled up. Currently there's no easier way to find the correct levels, the game is just too unprecise with the displayed imprinting quality.

**Comment by Vykan** [comment]
i've tryed this combination, but i think it's not true because the torpor doesnt indicate correct now.
I've increased "Weight" by 7 level.
I will make some test to find correct value, i think that excel will help me to find correct value.
I've read on ark.gamepedia that the torpor doesnt increase after dino are tamed, what happens when they are breeded ?
I use this value to determine what is the exact "Imprinting Bonus" : 90,29%

So, if i understand correctly, the dino "Tête de Pioche F" was adult at level 230 ?

![tdp f apres 7 lvl weight](https://cloud.githubusercontent.com/assets/22913843/19516836/ac99dc1c-9606-11e6-8600-49a0b22a9d21.png)

**Comment by cadon** [comment]
You haven't increased the Speed-stat yet. As the wild levels don't increase the speed-value, you can increase it until the torpor is correct. Keep in mind that the imprinting also affects the torpor-value, so the Imprinting might be less after the speed-increase. The Female was level 230 when hatched according to the xp-values. That also means, the torpor has to be level 229 (one less than the sum of the wild-levels).
