### ISSUE TITLE
Extract Level Distributions on Tapejara

### ISSUE THREAD

**Issue by Roach009** [cadon/ARKStatsExtractor#1120]
Hello,

I'm trying to add my Tapejaras on an unofficial Ark Extinction server, but keep getting issues with the stamina and weight numbers.  I have tried responding myself and cryopoding the tapejaras, but neither change any of the stats.

![Ark Tapejara F 209](https://user-images.githubusercontent.com/53878700/93008807-bfa10600-f53e-11ea-8a90-6f108067463d.jpg)

![ArkSmartBreeding Multi;ilers Settings](https://user-images.githubusercontent.com/53878700/93008777-6afd8b00-f53e-11ea-8023-a037d49bfaf8.PNG)

**Comment by VolatilePulse** [comment]
The Tapejara that you posted isn't an official Tapejara, they normally can't level speed. I found that Classic Flyers works fine, but you didn't indicate if you're using any mods.
![image](https://user-images.githubusercontent.com/6995232/93011271-e113e900-f562-11ea-85f4-7467d79cda78.png)
You can add mods to ASB by going to `Settings` -> `Mod value manager...` and adding it by selecting the mod in the left column and clicking `>` to transfer it to the `Mods loaded in library` column. ASB will as you if you'd like to download the necessary files, just select `Yes`.
![image](https://user-images.githubusercontent.com/6995232/93011323-4b2c8e00-f563-11ea-95db-2acf6cafff36.png)

**Comment by Roach009** [comment]
Yes, the server has classic flyers mod, but I am still getting the same red stat boxes.  And this is what I get when I enter the points manually on the Stat Tester tab.  For some reason, it is not recognizing after adding and downloading the classic Flyers mod to the library.  As you can see the stamina and weight stats are still off even though the points are correct.  Thanks for your help I know it is just some minor issue that I don't have set correctly.

![image](https://user-images.githubusercontent.com/53878700/93150757-a6739300-f6bf-11ea-830a-0988917c1170.png)

**Comment by Roach009** [comment]
Server Mods:
- Classic Flyers 
- Castles, Keeps, and Forts (Legacy)
- Castles Keeps and Forts Remastered 
- Structures Plus (Open Source) 
- Resource Stacks

**Comment by VolatilePulse** [comment]
When you select a species from the Species Multi-box, you need to make sure that you select the one from the Classic Flyers mod, as highlighted in red. I strongly recommend that you use the Dino Export feature instead of manual entry as it will prevent issues like this from happening again. You can read more about setting up the Dino Export feature [here](https://github.com/cadon/ARKStatsExtractor/wiki/Importing-Creatures#ark-exports)
![image](https://user-images.githubusercontent.com/6995232/93155436-1855d780-f6d4-11ea-9d99-be05a3682210.png)

**Comment by Roach009** [comment]
That worked perfectly, sorry for the last mistaking that classic fliers is a different breed.  Thank you for all of your time and understanding!
