### ISSUE TITLE
Conditional Text?

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#1121]
Is there a way to have it show conditional text?  For example, if a dino has no mutations it shows [00] but instead it would just omit it and name it as if there was no code there to show the mutation.

**Comment by Worldgate** [comment]
Basically my suggestion for a feature is having the ability to have a naming scheme for a clean dino, and one for a mutated dino.  I keep them separate.

Argentavis [C] M-### <--- Clean

Argentavis [D] M-### <--- Dirty

Wondering if there was a was a way to have the [D] only show up if its mutated.

**Comment by VolatilePulse** [comment]
Something like this should work for you:
```
{species} [{{#ifexpr: {muta} > 0 | D | C }}] {sex_short}-{{#padleft: {n} | 3 | 0 }}
```
