### ISSUE TITLE
Allo 

### ISSUE THREAD

**Issue by Zacharyhaas** [cadon/ARKStatsExtractor#1123]
![image](https://user-images.githubusercontent.com/70070238/93108048-99c74e80-f66f-11ea-9c0c-095d3ce1cc6a.png)

I have double checked all entered values. I cannot figure out what is wrong.

**Comment by VolatilePulse** [comment]
You haven't provided enough information at the moment for us to help you, but it looks like the server multipliers haven't been correctly entered into ASB. Do other creatures extract for you?

**Comment by Zacharyhaas** [comment]
it was the single player values box. thank you for the fast response.
