### ISSUE TITLE
Question: Add old leveled dino data? 

### ISSUE THREAD

**Issue by Offerel** [cadon/ARKStatsExtractor#1125]
To bad that I found this app not some weeks ago, as I stated to play Ark. Sure, now I add a dinosaur right after taming it or when it's new to get the right data. But I have a handful of older dinosaurs where I don't have the original levels, because they had several level ups before. Unfortunately, I play the Windows Store version, so I import all dinosaurs by screenshot. Since I'm playing on official server, I wonder if there is a way (manually or maybe some logfile) to get the dinosaurs data from the time where they are tamed originally? Is there some way?

**Comment by VolatilePulse** [comment]
ASB already supports extracting leveled creatures and if you're playing on an official server, there shouldn't be anything you need to change to support it. Can you provide a screenshot of the creature's inventory in game and a screenshot of the failed stat extraction in ASB (please don't crop images).

**Comment by Offerel** [comment]
Oh, extraction works. At least it will import the dinosaur. But if i remember correctly, import will be with leveled data and not the original data. And breeding works with the original data and not the leveled ones. Or do i get this wrong? Im new to ark not really sure.

**Comment by cadon** [comment]
Smart Breding imports both the base/wild levels which are relevant for breeding and the levels applied manually after the domestication (which are not relevant for breeding). The application usually displays the wild levels, sometimes additionally the domesticated levels are shown as well.

**Comment by Offerel** [comment]
Interesting. I didn't know that both levels could be imported from a simple screenshot. Nice.

**Comment by cadon** [comment]
Yes, that's basically what this application was made for initially. It checks all possibilities of wild and domesticated levels until a valid combination is found. Sometimes there are multiple possible combinations and the stat will be colored yellow after the extraction; then the user has to choose the correct combination from a list. See https://github.com/cadon/ARKStatsExtractor/wiki/Manual for more infos about that.
