### ISSUE TITLE
[Feature Request] make the  column hideable

### ISSUE THREAD

**Issue by GoogleBeEvil** [cadon/ARKStatsExtractor#1126]
![](https://s1.ax1x.com/2020/09/24/wzapi4.jpg)
As the pic shows, some columns are useless to me, can make it hide by rightclick menu

**Comment by VolatilePulse** [comment]
You can hide columns by resizing them so they have a width of 0 pixels and are hidden. If you accidentally hide a column that you need, you can expand the column adjacent to it to have it reappear. This has been supported for quite some time.
