### ISSUE TITLE
can asb show the lowest level plan？

### ISSUE THREAD

**Issue by GoogleBeEvil** [cadon/ARKStatsExtractor#1128]
Sometimes we need low level dino to clone, level 1 is the best ,if  asb make an option to revert the highest level plan，that will be help

**Comment by cadon** [comment]
Do you mean the suggestions in the breeding plan? You can set the stat weightings in the bottom left to negative values to favour lower levels.

**Comment by GoogleBeEvil** [comment]
that helps

**Comment by GoogleBeEvil** [comment]
Nevermind，have found that option
