### ISSUE TITLE
Speed levels extracting wrong

### ISSUE THREAD

**Issue by Stephanichiwa** [cadon/ARKStatsExtractor#113]
Wild speed points are coming out way too high, it says 100+ wild levels, where before it was usually in the 20's or 30's. as an example, I've attached a screenshot of a rex and 2 thorny dragons that have too many points in speed to be correct. 
![samore](https://cloud.githubusercontent.com/assets/22990482/19616951/a72a64fa-97d6-11e6-9055-3ead5650ff94.png)
![dragons](https://cloud.githubusercontent.com/assets/22990482/19617499/1ea0368a-97e7-11e6-915e-8d214d8d71d0.png)
![dragon breeding](https://cloud.githubusercontent.com/assets/22990482/19617695/d6c087b6-97eb-11e6-9a2c-4ea89ee9544d.png)

**Comment by cadon** [comment]
Hi, you probably forgot to check the checkbox "Since Taming No Server-Restart". That's necessary because of a bug in the game that displays a way too high torpor-value, which results in the end in a too high speed-level.

**Comment by Stephanichiwa** [comment]
Oh you're right. Thank you!
