### ISSUE TITLE
Taming Speed Multiplier needs to be updated to latest ARK version

### ISSUE THREAD

**Issue by NeoTiger** [cadon/ARKStatsExtractor#1132]
The base game's internal taming speed has recently been doubled, so 1.0000 is now what was previously 2.0000. The taming speed calculator does not currently reflect this this change as of version 0.42.0 (Workaround is to set the taming speed in the Settings menu to half the actual value of the server.)

**Comment by cadon** [comment]
Thanks for the report! This will be fixed in the next release.
