### ISSUE TITLE
Unknown creature from mod

### ISSUE THREAD

**Issue by stevedwray** [cadon/ARKStatsExtractor#1133]
I get an error when I load a save game, screen shot attached. It refers to TargetActor_C
I'm not aware of having mods that add creatures. How might I go about finding which creatures or which mod are causing the problem?
Thanks
![Capture](https://user-images.githubusercontent.com/5320456/95930349-b7c8d000-0e22-11eb-9b86-930788f501ef.PNG)

**Comment by cadon** [comment]
Hi, `TargetActor_C` sounds pretty unspecific. It sounds like a mod you're using has an entity that could be a creature (but the name suggests it's not). Vehicles like rafts also are considered creatures in ARK, so it's probably something like that. Do you have a mod that adds an item that can be mounted or in a similar way be used like a creature?

**Comment by stevedwray** [comment]
I do have a mod that adds rafts, though I haven't built any on this server. 
Does this message come up for 'creatures' that exist in the game, eg from mods, but hadn't been spawned in? 
Or had been spawned in but hadn't been 'tamed'?

**Comment by cadon** [comment]
That message appears if the savegame contains an object that could be a creature, but it's not recognized in the list of known species. It has to be spawned in for that to happen. An object is considered to be a creature if it is based on the base creature object. Almost all of these objects are indeed creatures, but e.g. rafts are also based on that base object in ARK.
It's probably safe to assume that `TargetActor_C` is not a species that needs to be considered when importing creatures. I'll add it to the list of ignored classes, that message should not appear in the next release anymore.
