### ISSUE TITLE
Windows defender detects "Trojan:Win32/Emali.A!cl" in "asb-updater.exe"

### ISSUE THREAD

**Issue by Draconium84** [cadon/ARKStatsExtractor#1135]
The windows defend told me immediately at the moment i extracted the file that there was a Trojan in the updater executable. It also said that it was considered as a "severe" threat before i allow it and delete it. Is the app safe? 

![image](https://user-images.githubusercontent.com/72878223/96010710-1e90be00-0e10-11eb-9e6e-327a1d4ceb33.png)

**Comment by cadon** [comment]
New versions are often flagged as false positives by heuristic anti virus software. If you downloaded the file from this site, it should be safe. For more info about this issue see #1102, #724, #572, #461, #460, #458, #453.
