### ISSUE TITLE
Mutation Export Bug

### ISSUE THREAD

**Issue by djupiterr** [cadon/ARKStatsExtractor#1136]
Hi! It seems that the mutation doesn't show up when you export baby Crystal Wyverns. Once it reaches adulthood. I had to re-export and update it just to show the mutation.

**Comment by coldino** [comment]
This is a limitation of Ark.

You need to open the parental info screen in Ark before it will be included in the export. There's nothing ASB can do about this.

We have other similar issues listed in Discord in the `#known-issues` channel, but perhaps a wiki page would help.
