### ISSUE TITLE
Name Generator {sn} off by one

### ISSUE THREAD

**Issue by JasperNuesslein** [cadon/ARKStatsExtractor#1137]
I have 5 Females in my library but the naming pattern names the 6th F5 even though it says in the description for the tag that it should add one to the total number per gender. Also I have not found a way to just say {{sn}+1} f.e. Or is there a way to do calculations?

heres my pattern:
{{#if: {owner} | [{{#substring: {owner} | 0 | 1 }}]}} {species} {sex_short}{sn}
It should be [H]  Velonasaur F6 but it is [H] Velonasaur F5.

**Comment by cadon** [comment]
Hi, thanks for the report. That's a bug, it will be fixed in the next release.
Calculations are not possible, maybe I'll add them later.
