### ISSUE TITLE
Double XP/Taming/Harvest

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#114]
During double taming weekend the stats extract to significantly high levels on speed and level.  Level 200 quetz claims to be 333.  Maybe a taming speed per dino could be set so they extract properly?

**Comment by knifesk** [comment]
You can set the multiplier in the settings before extracting each dino

**Comment by cadon** [comment]
Hi, the taming-speed only affects the taming-calculator, not the stat-extracting. If you speed-level is too high, you probably haven't checked "Since Taming no Server-Restart".
