### ISSUE TITLE
Name Generator Keybinding is off by 1

### ISSUE THREAD

**Issue by transphenomenal** [cadon/ARKStatsExtractor#1143]
When using {n} in an automatically generated name with the keyboard binding (ctlr G), it always uses the second lowest value it can, instead of the lowest. Manually editing the dino and pressing the Generate Automatic Name button works as it should.

I'm using 0.42.1.0, but it happened in at least 1 other previous version.

**Comment by cadon** [comment]
Thanks for the report, this will be fixed in the next release. The reason was that pressing the key combination Ctrl + G both triggered the naming generation by a keyboard event and also the assigned hotkey from the context menu.
