### ISSUE TITLE
Species in library / Breeding plan

### ISSUE THREAD

**Issue by AissuLegris** [cadon/ARKStatsExtractor#1145]
Hello,

Sorry for this poorly translated English.

I encounter a stupid problem, and cannot find the solution: 

on my server on the The Island, I have different "species" of Argentavis, and I cannot find a way to ensure that I have the breeding plan between species, is it possible to do this?
In play, they can reproduce ...

Thank you !

![Sans titre](https://user-images.githubusercontent.com/74288154/98777667-73186080-23f1-11eb-96c9-b62f47e99691.png)

**Comment by cadon** [comment]
Hi, different species generally cannot breed. If these creatures can breed ingame, you probably have selected the wrong species when you added them to Smart Breeding. You can change the species by selecting creatures in the library, press F3 and then select the species you want to set to the creatures.
It's recommended to use the import exported method to add creatures to the library, that way it's ensured the species is always correct. To export a creature ingame, look at the creature, hold E - Options - Export. Then in Smart Breeding click on the button `Last Export` or select the menu File - import exported creatures and select the ones you want to import.

**Comment by AissuLegris** [comment]
Hi, thanks for this reply, i use this solution.
