### ISSUE TITLE
Localization bug

### ISSUE THREAD

**Issue by knifesk** [cadon/ARKStatsExtractor#115]
I'm from Argentina, and my operating system is in Spanish. Spanish locale for numbers and dates and other stuffs is different than in English. 

Long story short, if your locale for decimal separator and thousand separator is not "." and "," respectively then all the stats fields appear red, even with correct stats, and of course, this makes the program to mis-behave.. 

In order to be able to use the program I changed my system settings to match the original locale, something that no everyone will know how to do. 

Also, I know this was the issue because I'm a programmer myself and I had this problem in the past..

**Comment by cadon** [comment]
hi, thanks for the report. Can you clarify when this issue happens? If you just type in the numbers with a comma "," as decimal-separator with your original OS-settings, it doesn't work? Or does the OCR always assume a dot as decimal separator and then it fails?

**Comment by cadon** [comment]
There were some fixes regarding the decimal-separator, I hope that was covered as well, so I'm closing this for now.
