### ISSUE TITLE
Number of mutations and parents are not imported

### ISSUE THREAD

**Issue by piotrch** [cadon/ARKStatsExtractor#1154]
Hi,

ASB is not importing numbers of mutations despite this information being included in the export ini files.
Also, program could be setting parents if they are found in it's database (their IDs are also present in the export file)

**Comment by coldino** [comment]
ASB should already be importing both mutation counts and parents. If the parents don't already exist then placeholders are created.

There is an Ark issue which my have led you to believe ASB is not working. If you play on a server then the export file will only include mutation and parent information **if you open the ancestry tab** before doing the export. Sadly there's nothing we can do about this.

**Comment by piotrch** [comment]
Oh, that was the problem, thanks for explanation - it is working as expected now. I was pretty sure I saw these info imported few times but could not find a difference. This bug may be worth mentioning in the "Import Exported" tab as it is not obvious.

**Comment by cadon** [comment]
Good idea, I added a note there.
