### ISSUE TITLE
Question: Exporting from one library to another

### ISSUE THREAD

**Issue by arathein** [cadon/ARKStatsExtractor#1155]
Hello - This is a question not an issue.
I just wanted to see what is the best way to export a subset of your library to another?
For example if I wanted to move Lit Wyvs from the main Library (which has everything in it so it is running a little slow now) to its own library but would like to keep the pedigree and everything.

**Comment by cadon** [comment]
Hi,
for that I'd save the library in a new file (`File` - `Save as…`), then delete all creatures you don't want.
If you then want to add them to an existing library, you can choose `File` - `Load and add…`.

**Comment by arathein** [comment]
ok that is what I was thinking just wanted to check, Thanks!
