### ISSUE TITLE
[question]any method make {n}surport 000~xxx

### ISSUE THREAD

**Issue by GoogleBeEvil** [cadon/ARKStatsExtractor#1156]
If the reg pattern is  A-{sexforshort}-{n}
the version now names the dino as follow:

A-F-0 
A-F-1 
A-F-2 
.......
A-F-10

Then if sort buy name,it will be 

A-F-1
**A-F-10**
A-F-2
...
Can it be 
A-F-000 , 
A-F-001 ,
A-F-002
....
A-F-010
So  names can be sorted correctly

A-{sexforshort}-{n,**3**}?

**Comment by cadon** [comment]
This pattern should work for that:
`A-{sexforshort}-{{#format: {n} | 000 }}`
