### ISSUE TITLE
Extractor tab does not show image for Crystal Wyvern

### ISSUE THREAD

**Issue by slinkhi** [cadon/ARKStatsExtractor#1159]
In-game, on a blood crystal wyvern, I click on Options > Export Dino.

Then, in your ARK Smart Breeding client, I go to File > Import exported creatures > [my ./DinoExports folder]

New window pops up showing creatures. I click on "Copy Values to Extractor" button.

Stats, region color swatches, etc. show up, but the image of blood crystal wyvern itself isn't displayed.  

Seems to work okay for other random dinos I import. 

I've made sure ASB is up-to-date. I've also done ? > "Download species Images" even overwriting current. 

![image](https://user-images.githubusercontent.com/76788250/103371545-60d3ae00-4a95-11eb-85c0-d7d95d7707a4.png)

**Comment by slinkhi** [comment]
Not sure if this in any way helps, but also note that I do not play with any mods, and I only play on PVE Official servers.

**Comment by coldino** [comment]
Yup, sorry we don't have full coverage of images for all species. Not really a bug as such, just one we haven't covered yet 😎

**Comment by cadon** [comment]
Images for the Crystal Isles Wyverns are added and can be now downloaded via the menu ? - Download species images.

**Comment by slinkhi** [comment]
sorry to bother you again, but I don't think it's working? I made sure client is up to date and i (re) downloaded species (including overwrite existing) and still doesn't show up?

**Comment by cadon** [comment]
The image is only in the developer branch and not yet on the master branch, so the ingame menu will not download the latest file. I didn't think of that earlier, sorry.
You can download the file manually here: https://github.com/cadon/ARKStatsExtractor/raw/dev/img.zip and extract the images to the img-folder of ASB. To find this, go to the menu `Settings` - `Open json data folder`, then go up one folder and there you can see the `img` folder, where the images can be extracted.
