### ISSUE TITLE
Remove untamable variants

### ISSUE THREAD

**Issue by piotrch** [cadon/ARKStatsExtractor#1161]
I don't now why all untamable species variants are present in the ASB database but I'd like to have option to hide them because for some species it is hard to select proper one when there is 5 or 6 variants displayed in the list.

**Comment by coldino** [comment]
Some people like to put force-tamed creatures in their library so we strive to cover all species.

You can however filter the species list in various ways. When you click on the species selector you have some options:
![image](https://user-images.githubusercontent.com/28345893/103779661-fb9b3200-502b-11eb-92f7-53c19f510d2c.png)

When the 'display non-domesticable species' tick box is off you should not see most untameables listed. If you want to be more specific there are a selection of variants you can hide too (the Variant Filter button).

**Comment by piotrch** [comment]
Thanks for pointning to these filters - somehow I missed them. However I still think that untamable species, mission, cave etc variants should be hidden by default as there is a vast majority of people not using them.
