### ISSUE TITLE
Copy name to Clipboard setting is not working

### ISSUE THREAD

**Issue by arathein** [cadon/ARKStatsExtractor#1163]
OS: Win10 Pro Version 1909
The option under settings -> Import Exported -> "When applied, copy name to clipboard" is not actually copying the name to the clipboard

**Comment by cadon** [comment]
Maybe the app is somehow blocked to interact with the clipboard, maybe by an anti virus app? Does it copy the InfoGraphic to the clipboard if you click on the colored creature image in the library (then paste it in an image app, e.g. Paint)?

**Comment by arathein** [comment]
Yea, no problem copying stats to clipboard or copying the info graphic is no problem, just for some reason the name doesn't copy.
I'll do some checks on my end too

**Comment by arathein** [comment]
So I updated Windows and still had the issue
I installed the EXE installer (had always used the ZIP before) in a location different than the ZIP and still have the issue
Tried running the program as administrator for S&G and still had the issue.
Infographic still works fine, it just isn't copying the name to the clipboard when I add a new dino, tried doing it with multiple name generation buttons.
I tried it on my laptop too, same behavior.
Both machines just use the OS Windows Defender, no special AVS

**Comment by cadon** [comment]
The naming pattern used for the auto import is the first one, can you post the pattern you use there? And what exactly are your auto import settings?

**Comment by arathein** [comment]
![image](https://user-images.githubusercontent.com/28239481/104112659-3238ad00-52b7-11eb-9157-ad7faece5f3f.png)
I'm not auto importing either, I'm Exporting, and then clicking Copy Values to Extractor.  
I don't see how coying the name would be useful if you are using the Import All as usually you do that for multiple things you don't have so haveint the name of 1 on your clipboard isn't going to help.
Also extractor issues when there could be multiple potential values to a stat break the auto import.
Having the name copy to clipboard when the creature is added would be rather helpful.

**Comment by cadon** [comment]
With the setting on the screenshot it shouldn't apply any names, at least one checkbox of the first three has to be checked. Do you apply the name by manually clicking on the `G` button?

**Comment by arathein** [comment]
I've tried it with no boxes, and with both 2nd and third and still the same behavior.  and yes I am generating the name by clicking a G button and then clicking Save and it does not go to clipboard.

**Comment by arathein** [comment]
I made a video for you https://youtu.be/EB9ZC23ES3Y

**Comment by cadon** [comment]
The auto naming is only working if creatures are imported using the auto-import. The next version will also apply the name pattern for manual imports.
Is there a reason why you don't use the auto import? In general it's much faster because you don't need to open the import window, copy the values over and add the creature to the library manually.
Until the new version is released, you can copy the name of the creature by clicking on the underlined label `Name` directly left of the name edit box.

**Comment by arathein** [comment]
Is the auto import the bulk import?
If so it isn't helpful because I have to name the dino, I don't know what I am going to name the dino until I put it in ASB and generate its name?  
Like I export 50 Allos from Ark all named Allosaurus how do I know what to name what after the import without digging through and matching Ark ID?
I use the Bulk import when I am importing a bunch of stuff that I have already named, Like I was hatching a butt ton of Wyvs so I just named the all LW-M01 (02, 03 etc) or LW-F01, 02, 03.  So in that case I had already named them, but most of the time they aren't named before I export.
It is entirely possible there was a new feature that I just didn't catch on to LOL

**Comment by cadon** [comment]
Yes, the auto import is something different, it's importing exported creatures automatically. You just export it in ARK and ASB imports it in the background automatically without the need to tab over to ASB and click buttons etc. You only need to do extra work if the import needs extra user inputs, i.e. if there are yellow stats where you have to choose from a list of possible entries. If you use the auto import, the name is generated and copied to the clipboard, so the workflow becomes
  * Export the creature in ARK
  * Listen to the import sound if it was successful
  * open the creature's name option
  * Press Ctrl + V to insert the generated name

You can also enable the overlay (button at the right top) to have extra info about the exported creature.

**Comment by arathein** [comment]
OMG this would have saved me so much time!
Literal game changer!
☕ Time for you!

**Comment by arathein** [comment]
How does one donate to the cause these days?

**Comment by cadon** [comment]
This is the link for [donations / coffee](https://ko-fi.com/826WMCII3B24), glad you enjoy the app!
