### ISSUE TITLE
Overlay button doestnt work

### ISSUE THREAD

**Issue by midn8toker** [cadon/ARKStatsExtractor#1169]
After todays update it seems the overlay button doesnt work anymore. Any1 else have this issue? and any sollutions?

**Comment by cadon** [comment]
What exactly doesn't work anymore? The overlay itself should work like before. The OCR configuration was changed, it does already work, but the config files are not yet ready.

**Comment by midn8toker** [comment]
I use the ARK stats extractor for quite a while now. I have my own server and use it to get all the highest stats. 
Its like i said. the overlay button doesnt do anything anymore. normaly it fills in all the stats i need,  sometimes i need te correct the species. Now i could fill in all the stats myself but thats too much work.. i know .. im spoiled with the program

**Comment by midn8toker** [comment]
even a re-install doesnt help... please help

**Comment by cadon** [comment]
If you're playing on steam or epic I recommend to use the import export method (holding E when looking at a creature, select Options - Export), see https://github.com/cadon/ARKStatsExtractor/wiki/Importing-Creatures#ark-exports for more info.
Regarding the OCR, what resolution do you have on the monitor you play on?

**Comment by midn8toker** [comment]
1920x1080 full screen windowed did always work. I clicked the extract button and it got the data.. usually correct.
But this is a new method of extracting data. it also includes the collours and i am at the moment busy breeding pteradons in all collours so.. thats a whole new experience.
Thanks for the good tip!
I work now with the version 42.2 and got the extract button to work again.. It took some time to find the right download link though..
