### ISSUE TITLE
Add Folders?

### ISSUE THREAD

**Issue by artoni** [cadon/ARKStatsExtractor#1176]
Any chance we could add in the option to group our tames in to specific folders - eg, put all the dead otters in a folder so while their data is still there, they're not in the 'main' otter window? Would be useful in case we have specific lines we're working on.

**Comment by cadon** [comment]
Hi, you can add tags to do this. Select the creatures you want to hide, then right clickt - Edit all selected (or press F3). In the new window on the right bottom enter the name of a tag, e.g. `Breeding Line 1`, `Unused Creatures`, etc. and create the tag with the `+` button. Then apply the tag to the selected creatures by checking both checkboxes of that tag.
To filter the library view, click on Filter library in the menu and selecte / deselect the tags.
