### ISSUE TITLE
Newest Dinos

### ISSUE THREAD

**Issue by purplewargreymon** [cadon/ARKStatsExtractor#118]
its been a lil while so id like to ask if u could put in the most recent dinos, ie, chalico, diplocalus kaprosuchus if u havent already, the last update i have is the scorched earth one so i apologize if uve already done this

**Comment by cadon** [comment]
Hi, these dinos should be in the tool for some weeks. Maybe you have to update your stats-file. In the tool click on ? -> Check for Updates to get the newest version.

**Comment by purplewargreymon** [comment]
it says i already have the newest version of the tool, at 20.7, none of the new stuff is showing

**Comment by cadon** [comment]
Hm, then try to redownload the tool. I just tried that and after starting it asks to update the values-file, then the new creatures are there.

**Comment by purplewargreymon** [comment]
thank u it works now, i will ask tho, could u put the version into a new release for people who may be having the same issue?

**Comment by purplewargreymon** [comment]
Please Update gig stats due to nerf and add the other 4 new dinos <3 sorry to bother

**Comment by cadon** [comment]
Hi, the Giganotosaurus-nerf is added, also the 4 new creatures. Get the new file by clicking on "Check for Updates" in the ?-menu.

**Comment by purplewargreymon** [comment]
mk thank u very mmuch

**Comment by purplewargreymon** [comment]
Final thing they nerfed herbivore hps per lvl, can u update that please? after that i will close this :)

**Comment by cadon** [comment]
I just uploaded the new values, they should be available automatically or by clicking on ? -> Check for Updates.

**Comment by purplewargreymon** [comment]
Worked. Thank u oh so much, I super appreciate it, and how useful ur tool is :D
