### ISSUE TITLE
Having issues extracting tames from Crystal Isles

### ISSUE THREAD

**Issue by alykins08** [cadon/ARKStatsExtractor#1181]
I've just begun using your program to help keep myself organized when I start breeding. The previous tames I've manually added have all worked as they're meant to, but since we started on Crystal Isles I've had issues with every single one I've tried to add in. All of their stats read green until it comes to the torpidity which always shows as red, and there's no steps or anything I can find to fix it. Once that happens I can't add it to a library or keep track of it. I'm on Xbox and so I have no mods to add into your program. I decided to add what I could find regarding Crystal Isles just in case they're considered mods, but nothing I've done has helped. Obviously I have no idea what I'm doing and just need a nudge in the right direction. I'm attempting to add a picture to show what I mean. I've tried extracting a Dimorph and Therizino with same results. After we tame we usually change the name, then grab a screenshot and cryo right away. I've just taken out all of these tames to see if maybe the stats read incorrectly before we cryo'd but they show the same as they did upon taming. 
![Screenshot (1)](https://user-images.githubusercontent.com/79721931/109349195-8e459980-7843-11eb-8c2c-e0ae57a60a1d.png)

**Comment by VolatilePulse** [comment]
Torpor is showing as red since the calculated value conflicts with the creature's level. Is the creature really level 140?

**Comment by alykins08** [comment]
Oh. I'm an idiot, huh? It was 140 wild, but I still need to put in the level it is after taming and it will calculate the wild level for me. While I was putting in the wild level myself. Goodness sorry for wasting your time but you figured it out for me.
