### ISSUE TITLE
Is there a way to mark those dinos that are not needed anymore?

### ISSUE THREAD

**Issue by xxBLoS** [cadon/ARKStatsExtractor#1184]
Currently I just breed them together without mutation, to get to the max possible level. Is there a way to mark those dinos that aren't needed for this process? So my base isn't full with a bunch of low level dinos I don't need anymore?

I don't just want to throw them away. Maybe I need them later for a single stat that I overlook.

Thanks

**Comment by cadon** [comment]
Hi, you can assign arbitrary tags to creatures and filter by these. To do so, select them in the library, right click - `Edit all selected…`, then on the right bottom enter a tag name, e.g. `not needed`, press the `+` button to create the tag and assign it to the selected creatures. Click on the apply button. Now you can deselect in the menu `Filter library…` the entry for the created tag to not display the according creatures anymore. That tag can be used in the breeding planner as well to exclude these creatures.

**Comment by xxBLoS** [comment]
Thanks. But I think you missunderstood my question. How do I know that I don‘t need those stats in the future?

**Comment by cadon** [comment]
If a creature has top levels (i.e. the highest level in a stat of a species) it has a green background in the library (the according stat has a higher contrast compared to non-top stats). If a creature has only top stats, its background is gold/yellow. So if a creature has no top stat, its background is plain and it's not needed for breeding for high levels. Note that if you need a low level in a stat, e.g. you want oxygen to be as low as possible, this will not be considered in the background color, so check if you need a low level of a creature before discarding it.

**Comment by xxBLoS** [comment]
Thank you very much. 
Just because im intereseted:
Why would I want a low oxygen tame? Does it affect something negative?

**Comment by cadon** [comment]
On official servers there's a level cap of 450, i.e. a creature with more or equal 450 total levels will be deleted. If you want to increase the levels of desired stats, e.g. HP and damage, you have to keep other levels low to not pass the level cap. That is an issue if you breed for a longer time and only if you play on official servers where this level cap is active. Unofficial servers don't have that limit.
