### ISSUE TITLE
Highlighting high stats not highlighting in every column

### ISSUE THREAD

**Issue by Uskaanax** [cadon/ARKStatsExtractor#1189]
[Imgur](https://imgur.com/UrzvEoG)

I'm not a pro with ASB by any means, so correct me if I'm wrong. The documentation [states](https://github.com/cadon/ARKStatsExtractor/wiki/Library#stat-levels) that the highest stats are strongly colored, but it seems like the implementation is not looking at each column. Is this configurable and I missed it, or is there a section of the documentation that explains how this should work? I nearly missed out on an anglerfish that has the highest weight when I was about to cull my collection, especially now that I have all my mutators set up.

**Comment by cadon** [comment]
It looks like the weight stat is disabled for the highlighting in your library. You can adjust the stats that are considered for highlighting in the library - bottom-left in the tab `Stats`.
