### ISSUE TITLE
Direwolf lvl 200 tame

### ISSUE THREAD

**Issue by irmandos** [cadon/ARKStatsExtractor#119]
Hello,

I downloaded your software and was trying to use it on my first tame I intend on making a breeding pair with on the server.

I have attached a screenshot of the Direwolf level 200 as I was feeding it narcotics while waiting for the prime meat. The tame finished with a 93.7% effectiveness (I forgot to make a screenshot then) with a 93 level increase resulting in a level 293 Direwolf after tame.

I however try to enter the stats in your application and I keep on getting red boxes, what am I missing here?
![346110_screenshots_20161117191822_1](https://cloud.githubusercontent.com/assets/5756234/20420530/168b0868-ad67-11e6-9f39-888653967b7b.jpg)
![lvl200direwolf](https://cloud.githubusercontent.com/assets/5756234/20420531/16cee1c8-ad67-11e6-821c-cda9876062cb.PNG)

**Comment by cadon** [comment]
Hi, you made a mistake with the torpor, with 5823.0 it should work.
