### ISSUE TITLE
Index changes

### ISSUE THREAD

**Issue by HubMiner** [cadon/ARKStatsExtractor#1191]
We use "Index" to generate unique names and "tribe" field as purpose for an animal
boss.F.1, boss.F.2, boss.F.3

We often update the purpose, and when updating names, unexpectedly index shifts:
boss.F.1, boss.F.2, breeder.F.2

This is a messy when dealing with a large lists, implying that all animals should be renamed to have matching names.  One possible cause is that an earlier animal (boss.F.1) is deleted, but there may be other causes.

Would it be possible to change index functionality so it never changes, or make a new key that would be short, unique, and never changing?

Cosmetic issue - index is mentioned in pop up help in the app, but not in online document: https://github.com/cadon/ARKStatsExtractor/wiki/Name-Generator

**Comment by cadon** [comment]
How would a creature know on what index it was earlier? And if it would save its index and it changes multiple times, what entry would be the correct one?
I think for your purpose the `{index}` key word is not suitable. If you want to keep the name of a creature and only apply a name if it it not yet named, you could use `{{#if: {alreadyexists} | {oldname} | <pattern of new name> }}`. If you want a number for a creature that is fixed, you can use `{arkid}` (or a part of it, e.g. `{{#substring: {arkid} | 0 | -4 }}` to get the last 4 digits of the id, but when using only a part of it, it's not guaranteed to be unique, of course).

**Comment by HubMiner** [comment]
@cadon, thanks for the response!

> How would a creature know on what index it was earlier?
I guess a unique index would need to be saved in the data file.  Would this be hard to add?

Alternatively, would it be possible to add a function that takes arkid and outputs a short (3-4 char) hex checksum?  Unlike saving index, this approach might produce a duplicate index.

If anyone is trying to follow along, the proper syntax for getting the last 4 digits of the arkid seems to be: `{{#substring: {arkid} | -4 | 4 }}`

**Comment by cadon** [comment]
Saving the index wouldn't solve the initial issue that there could be duplicates, e.g. the first creature would get the index `1`, the second the index `2`, if you then delete the first creature and add a third one, that would again get the index `2`.

You can convert the arkid to a hexadecimal representation with `{{#format_int: {{#substring: {arkid} | 9 }} | X }}` (the substring is needed to not exceed the maximum value of a 32 bit integer), then take the last couple of digits of that, e.g. `{{#substring: {{#format_int: {{#substring: {arkid} | 9 }} | X }} | -4 }}`. That way you have a chance of 1 / 2^16 = 1 / 65536 of a duplicate id.

Thanks for correcting the substring function!

**Comment by HubMiner** [comment]
I tested this for a few days, this seems to work very well!
Please consider adding this as an example on the name generator page.

Thanks for your help!
