### ISSUE TITLE
Extraction Failed

### ISSUE THREAD

**Issue by DKSorc** [cadon/ARKStatsExtractor#1192]
this has happened to me both on single player and, now, my own dedicated server.  I tame a wild critter and when putting its stats in the extractor, it fails.  only happened 2 times, didn't get screenshot of first times.  the first time it was a raptor, second (with SS) is a tek parasaur.  I didn't touch stat multipliers on either the single player game, nor on the dedicated server.  only setting that I changed is the taming speed, as I am playing solo (without using singleplayer settings).  let me know if you want the game.ini or the gameusersettings.ini copied/pasted for verification.

![tekparasaurstats](https://user-images.githubusercontent.com/82771371/115153000-54219880-a039-11eb-868a-fa633ba30b4e.png)

**Comment by VolatilePulse** [comment]
You are using a significantly out of date version of ASB. The current version is `0.45.1` and you are using `0.24.4`. Download the latest version and try again. Also, I would recommend using the creature export method listed [here]().
