### ISSUE TITLE
How to export ASM settings?

### ISSUE THREAD

**Issue by gbusoni** [cadon/ARKStatsExtractor#1195]
I need to use ASM on multiple PC. Is very tiring to config it everutime. Is there a setting file I can just copy over?

**Comment by cadon** [comment]
Hi,
the multiplier settings can be saved in a file and then imported via drag&drop in the settings window on the other computer. To export these settings click on `Settings` - `Multiplier` - `Export multiplier settings to file…` (right bottom).
The application settings (e.g. server import configuration) are stored in `%localappdata%\ARKBreedingStats\ARK_Smart_Breeding.exe_Url_<UID>\1.0.0.0\user.config` (check the folder `%localappdata%\ARKBreedingStats` and select the newest folder there). On the other computer start Smart Breeding at least once, then open the same folder and copy the file `user.config` over.
