### ISSUE TITLE
Creature Pics Not Showing Up in ASB for Several People

### ISSUE THREAD

**Issue by Anokhta** [cadon/ARKStatsExtractor#1198]
We were having a discussion in my alliance about ASB suddenly not showing images since a recent patch/update.  All of us seem to be affected.  Also, the most recent update seems to have added a color wheel in place of the critter.

**Comment by coldino** [comment]
The functionality has moved to Settings -> Extra Data. You should be able to simple re-enable it.

It was meant to automatically switch over if you had it enabled previously, but unfortunately this failed for some people so you'll have to do it manually. Sorry for the confusion!

I would encourage someone from your group to join our Discord server where we post about issues like this as soon as we learn about them.
