### ISSUE TITLE
Custom PerLevelStatsMultiplier_DinoWild Values

### ISSUE THREAD

**Issue by BinarySavage** [cadon/ARKStatsExtractor#12]
Is there a place to enter custom server-side values for PerLevelStatsMultiplier_DinoWild? From what I could gather the multipliers.txt just handles custom values for PerLevelStatsMultiplier_DinoTamed.

**Comment by cadon** [comment]
Not yet, haven't thought about servers that have custom values for the wild-levelups. I'll add it in the next version.

**Comment by BinarySavage** [comment]
Thank you.

**Comment by cadon** [comment]
Hi, the newest version now supports custom values for PerLevelStatsMultiplier_DinoWild. Just add it as another comma-separated-value in the file multipliers.txt.
