### ISSUE TITLE
Procoptodon Stats Incorrect

### ISSUE THREAD

**Issue by fluffkit** [cadon/ARKStatsExtractor#120]
**Fuzzerfluffs**
[Ark](http://steamcommunity.com/sharedfiles/filedetails/?id=807300959)
[Program](https://gyazo.com/9435e77247db553e56f590ab46595500)

**Fluffers**
[Ark](http://steamcommunity.com/sharedfiles/filedetails/?id=807306823)
[Program](https://i.gyazo.com/5b8a65f63e4c8ccfd767f67a71049dbd.png)

It keeps telling me that the stats are not able to add up, and I have no clue why. The server stats are all at official stats, it is an unofficial server but we typically do not change all that much.

Really all that is changed is the tame rate, and hatching/ maturation rate.

**Comment by cadon** [comment]
Hi, maybe it's related to that issue: #19. Currently I've not the time to investigate it further, sorry.

**Comment by fluffkit** [comment]
Awesome thank you. I am so obsessed with your program so I am excited about helping to make sure everything works.

**Comment by cadon** [comment]
Closing this issue, as it's probably the same as #19.
