### ISSUE TITLE
Add shortcuts

### ISSUE THREAD

**Issue by HubMiner** [cadon/ARKStatsExtractor#1201]
The tab based interface is very logical.  Please consider adding numbers to each tab's name, and matching shortcut, for example:
"Library" -> "3. Library", Alt-3, or Alt-L

**Comment by coldino** [comment]
Numbers in the tabs will look bad, but the idea of shortcuts is good.

Maybe the traditional old style of underlining the key needed would work, like underlining the L in Library for Alt+L.

**Comment by HubMiner** [comment]
May be the number could the shown when Alt is presses?
Or just the traditional underlined letter...
