### ISSUE TITLE
Handle negative value for mutations

### ISSUE THREAD

**Issue by HubMiner** [cadon/ARKStatsExtractor#1206]
Looking at two dinos, one with a negative mutations value - it has green highlight.  A second dino with identical stats but large positive mutations value - it has no green highlight.

The green highlight is probably only looking at values above a threshold.  It should also check for negative mutation values as bad.

**Comment by coldino** [comment]
Green creature highlights have nothing to do with mutations - are you sure there weren't any stat differences, perhaps in a column you've hidden?

Besides, negative mutation counts are actually very good - the are effectively always below the mutation cap.

**Comment by HubMiner** [comment]
Thanks!
