### ISSUE TITLE
Naming pattern to change the word 'Aberrant'

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#1209]
Due to the length of the word 'Aberrant', we can't always use the automated names due to a 24-character limit. Things like "Aberrant Pulmonoscorpius M01" is 28 characters. It would be nice if the naming pattern had some syntax to just replace the word 'Aberrant' with something else, something shorter.

**Comment by cadon** [comment]
Hi, you can use the replace function for that, e.g. `{{#replace: {species} | Aberrant | Ab }} {sex_short}{{#format: {n} | 00 }}`

**Comment by soepie7** [comment]
Oh, I must have overlooked that when I was looking through the tags, thank you!
