### ISSUE TITLE
Pteranadon Speed Always in the Red

### ISSUE THREAD

**Issue by Divinion** [cadon/ARKStatsExtractor#121]
After the update that happened today (12/12/2016) Every Pteranadon, bred and in the wild is showing up as Red now for speed (135%).  Not sure why, but it seems to be the only dino I have been having problems with since this update.

**Comment by cadon** [comment]
Hi, thanks for the note. The stats in the game seem to have changed again. I'll update the tool soon.

**Comment by Tpampel** [comment]
Hope this helps.  From patch notes for 252.9:
* 20% per Tamed Ptero Level reduction in Speed (~15% average reduction in Ptero Speed to Tamed Pteros)

**Comment by Divinion** [comment]
I'm looking at the previous Pteranadons I have on the Smart Breeding
already.  It was 136.5% and now it's 135.0% as default speed.  I did try
again to input the newer ones, and it still does not work.  Also went and
made sure I checked for updates on Smart Breeding, and it couldn't find
any.  Not sure what is going on.

**Comment by cadon** [comment]
Hi, the new values are uploaded. Should work again.
