### ISSUE TITLE
Library conversion causes library to fail to load

### ISSUE THREAD

**Issue by zerassar** [cadon/ARKStatsExtractor#1210]
My library was last edited 15/09/2019, I dont recall the version number... But I was somewhat up to date at this time.
On launching the software today the auto updater asked me to update which I did.
On launching the updated software V0.46.5.0 i was warned that my library was going to be converted to the new format.

I noted that my xml of 351KB was then converted to an ASB file of 169KB.
However, within ASB software the library appears completely blank.
Tried reopening the ASB library file and the library tab is still blank.
Running ASB as admin, changing directory permissions. No fix.
Reopening the original xml file simply redoes the conversion and saves to a new filename_number.asb file.

If I add a dino manually to the library, and then save to a new file. This works.
I can then close and re open the new file and the library tab in ASB populates and shows stats as per normal.

It looks like something is failing in the conversion process rendering the file unreadable to ASB.

How can this be fixed?

**Comment by zerassar** [comment]
Just some further info.

I have tested this in both recent versions 0.46.5.0 and 0.46.4.0. Same effect.
Both installed, and portable versions.

Located and scrolled through the releases and identified the version that the gacha format was implemented. V0.33.1.0.
Downloaded and tested this version against my XML library.
The library was converted to ASB and appeared correctly in the library tab.

I copied this known working ASB file and tried to open it with 0.46.5.0 and the same issue occurred.

So the same ASB file works in 0.33.1.0 but not 0.46.5.0. For now, I'm going to stick with this legacy version as it appears to be working ok. Seems there is something in the converted file that newer versions dont like very much.

I have attached a copy of my original xml file as well as the ASB created by V0.33.1.0.


[Breed.zip](https://github.com/cadon/ARKStatsExtractor/files/6588691/Breed.zip)

**Comment by coldino** [comment]
Thanks for investigating. This is indeed weird, especially given the size of the `.asb` file.

We'll take a look!

**Comment by cadon** [comment]
Thanks for the save file!
The issue was that in some point of the development the handling of mod files was changed, which resulted that after converting an xml-file with no additional mod file, the app still tried to load the mods, but because no mods are selected that kinda failed (i.e. nothing was loaded), that was interpreted by the converter that something went wrong, and the library file was considered to be corrupt. This will be fixed in the next release.
