### ISSUE TITLE
Breeding plan for Maewing

### ISSUE THREAD

**Issue by HubMiner** [cadon/ARKStatsExtractor#1214]
The tool is confused about maewings:
- Imported gender is reported as female (instead of genderless).  This is very cosmetic.
- The tool is not able to generate Breeding plan - due to lack of both genders.

**Comment by coldino** [comment]
As a temporary workaround you can change the breeding planner setting to ignore gender entirely, which can be found in Settings -> General.  This is app-wide so less than ideal, but it will unblock you for now.

**Comment by cadon** [comment]
Fixed in 0.47.1
