### ISSUE TITLE
Dinos Image

### ISSUE THREAD

**Issue by NatalieLima** [cadon/ARKStatsExtractor#1216]
Where can I enable to see the dinos as before the last updates, now it only shows colors and the names of the regions, it doesn't show the dinos anymore, would it be possible to provide some place to get the image as before?

**Comment by Anokhta** [comment]
I am also wondering this, as the update before this recent one rendered (once again) us unable to download dino images.  The setting (Settings > Extra Data) to download images has been removed from this version, unlike before...

**Comment by cadon** [comment]
Does it work with the latest version 0.47.2?

**Comment by NatalieLima** [comment]
Hey Yes, I came here 
![image](https://user-images.githubusercontent.com/50057572/122690099-d6773600-d1fd-11eb-87ff-9411c84e8479.png)
and here
![image](https://user-images.githubusercontent.com/50057572/122690104-e262f800-d1fd-11eb-8e8d-ec47eefe0960.png)
and then I dowload the images, and done :)
Thanks a lot!!

**Comment by NatalieLima** [comment]
There was a button when I could download the images. Really easy! Thanks :)

**Comment by Anokhta** [comment]
There is no button there anymore to download images though, like there was once before.

**Comment by cadon** [comment]
If there is no button, the images seem to be already downloaded. You can download them again if you delete the images folder. You can find this by clicking on `Settings` - `Open json data folder…`, go up one folder, go in the folder `images` and delete the folder `speciesImages`.
