### ISSUE TITLE
New User, This dosen't look quite right?

### ISSUE THREAD

**Issue by XPChainLightning** [cadon/ARKStatsExtractor#122]
![ark stats](https://cloud.githubusercontent.com/assets/24571256/21190678/a224dd52-c1f0-11e6-9736-927b45cc76e4.JPG)

**Comment by cadon** [comment]
Hi, do you play on an unofficial server? Then you might adjust the multipliers in the settings of the tool, ask your server-admin for the values. If you're on an official, it should work out of the box, then please post a screenshot of the Ptera-inventory.

**Comment by XPChainLightning** [comment]
I think i figured out what was wrong or at least a workaround. now my only problem is the speed stat showing up;)
Thanks for the making the program, and for the quick response!!!

**Comment by cadon** [comment]
Hi, the new values are uploaded, get them by clicking on ? -> Check for Updates in the tool.
