### ISSUE TITLE
Contribution: R giga image template for smart breeding

### ISSUE THREAD

**Issue by MatiPlayzzYT** [cadon/ARKStatsExtractor#1222]
since i've been waiting for a R giga template to see the colors on the dino in smart breeding and no image has been added, i decided to make my own giga template which i will share with you all and if it's possible it can be officially uploaded to smart breeding:

![R-Giganotosaurus](https://user-images.githubusercontent.com/84147369/125190844-dd91d280-e204-11eb-888b-3b54ac3afc80.png)
### **^^^^IMPORTANT: NAME THIS ONE AS "R-Giganotosaurus.png"**
.

.
![R-Giganotosaurus_m](https://user-images.githubusercontent.com/84147369/125190845-de2a6900-e204-11eb-95d7-9e566a10183e.png)
### **^^^^IMPORTANT: NAME THIS ONE AS "R-Giganotosaurus_m.png"**
.

.
to install this template simply follow this two steps:

- go to "AppData\Local\ARK Smart Breeding\images\speciesImages" and delete the "cache folder"
-paste in "AppData\Local\ARK Smart Breeding\images\speciesImages" the two pictures above

and done! enjoy the template ^^

here are some examples of the result:

![](https://cdn.discordapp.com/attachments/788130855775502336/863698025069936660/unknown.png)

![](https://cdn.discordapp.com/attachments/788130855775502336/863697984595820564/unknown.png)

**Comment by cadon** [comment]
Hi, thanks a lot! I wasn't able to create image files for the R-Giga because to get it all on the screen I had to go back so far that the color command in the console didn't work anymore because of the distance. How did you create these images?

**Comment by MatiPlayzzYT** [comment]
> Hi, thanks a lot! I wasn't able to create image files for the R-Giga because to get it all on the screen I had to go back so far that the color command in the console didn't work anymore because of the distance. How did you create these images?

i did use the tutorial listed on this wiki, what i found out when i had the same issue as you is that if you don't aim at a specific part of the giga the selection will be aiming at the green screen structures behind it, to aim properly i used the creative mode rifle on the green mode and started moving the mouse until it showed me the Giga name and then i know i was aiming at it properly. After that i just followed all the next steps :D

**Comment by cadon** [comment]
Oh, so it's not an issue of the distance, but rather the aiming. Thanks a lot for that info and the trick with the creative mode rifle!
