### ISSUE TITLE
Extractor won't calculate negative mutations.

### ISSUE THREAD

**Issue by dbushcny** [cadon/ARKStatsExtractor#1223]
When I input negative mutations in the extractor it will not calculate the number. For example If I put one positive number in the maternal side and one negative in the paternal side, the sum will be the maternal mutation count. Is this correct?
![Desktop Screenshot 2021 07 29 - 16 16 04 44 (2)](https://user-images.githubusercontent.com/88163200/127559966-2387db91-8e51-4be2-b7a2-cded386e188d.png)

If I put a negative number mutation in both maternal and paternal it will not be calculated at all. Is 2 negatives not possible?
![Desktop Screenshot 2021 07 29 - 15 40 19 54 (2)](https://user-images.githubusercontent.com/88163200/127559964-d8c77e16-2fdb-4d4e-9507-1eb2c8cec060.png)

However if the sum of the number is greater than 2,147,483,647 it will calculate the negative mutation count. You might not be able to see it clearly, but there is a (-) after the (+). Was the application built to be able to calculate this scenario?
![Desktop Screenshot 2021 07 29 - 15 56 13 16 (2)](https://user-images.githubusercontent.com/88163200/127559965-650e062a-513c-48a7-b103-ca56370bc7ee.png)

This might not be an issue, maybe I have it all wrong. I'm not sure if the negative means I can mutate further. I do understand how to calculate the number if the sum exceeds 2,147,483,647 and look like the application did the equation for me. But what about if I input a negative in the maternal or paternal side in the extractor?

**Comment by cadon** [comment]
Hi, the number with the violet background displays the new mutations of a creature, i.e. it's an indicator if the creature received a new mutation (or multiple). To be precise, the sum of the mutations of both parents are substracted from the creature's mutations, if a parent is set and if the mutation counter of that parent is lower than the one of the offspring.
If you enter a number that is lower than the mutation of the parent (i.e. a negative number while the parent's mutation counter is 0), this is a situation that is almost always impossible, so the app ignores it when calculating the new mutations of a creature. The only case where a mutation counter of an offspring can be lower than the one of its according parent, assuming there's a maximum of 3 mutations (like on official servers), is if the mutation counter is in the range (int32.Max - 2) to (int32.Max) and the mutation counter of the child has a value of max (int32.Min + 2). I guess this case probably never happened yet, but I'll add a proper handling for that.

**Comment by dbushcny** [comment]
Thank you for you knowledge, I will keep note of the information.
