### ISSUE TITLE
Tek, Gen-X, and Gen-R variants sorted in the wrong place.

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#1224]
Aberrant variants are sorted right after their normal version. For example, my file would have Carbonemys, then Aberrant Carbonemys, then Chalicotherium, instead of having the Aberrant Carbonemys be at the top of the list.

The same does not hold true for Tek, Gen-X, and Gen-R variants. They are still sorted as if 'Tek', 'X-', and 'R-' is part of their name. It would be nice if these were also sorted with those parts of their names ignored.

**Comment by cadon** [comment]
Hi, thanks for the report. There will be a menu option to set the sorting of these variants to their vanilla counterparts. Until then, you can edit the file to set that sorting: Menu `Settings` - `open json data folder`. Open the file `sortNames.txt` in that folder. Replace the content with `^(Aberrant |Tek |R\-|X\-)(.*)$@$2$1`. After a restart, the sorting is fixed for these variants.
