### ISSUE TITLE
Ancestors not importing 

### ISSUE THREAD

**Issue by JeffreyOI** [cadon/ARKStatsExtractor#1225]
I am trying ASB for the first time, and I’ve successfully imported a few of my dinos' stats from the "Dino Export" selection in the wheel menu. Unfortunately, even though I opened the "Show Ancestors" view from the inventory right before exporting, that data isn’t brought into ASB.

**Comment by coldino** [comment]
The import data for ancestors really only includes their identity, not their full data, and ASB should have recorded that. If you now import a parent you should find they are correctly linked up.

**Comment by cadon** [comment]
Did you import the parents already? If not, they will not show up in ASB. If you import them, ASB should then link them correctly.

**Comment by cadon** [comment]
ASB can only read the data in the export file. Regarding the parents, in this file there are the names and the ids of the creature's parents (and the name and ids of their parents etc.), but no further information about stats or colors of the ancestors. ASB only imports the id and uses that to link the creatures if the parents are imported later. The names of the parents are not imported. If these placeholder are displayed in ASB (I think you can only see them in the pedigree), they have generic names, e.g. the mother of a creature names `Beasty` is named `Mother of Beasty`.

**Comment by JeffreyOI** [comment]
Ok, I added a line on the Importing page of the Wiki to clarify this point. With that I will close this issue. Thanks all for the help!
