### ISSUE TITLE
Not reading stats right, did I fill these in right?

### ISSUE THREAD

**Issue by owletra** [cadon/ARKStatsExtractor#123]
I am on an unofficial server, [here ](https://imgur.com/a/pKcZY)are the settings my admin gave me. I can get the stats all green on some creatures, but only about half the time. This is a bred Direbear before imprinting. I'm not sure if I filled in the settings correctly. Can anyone see what is wrong?
![babybear](https://cloud.githubusercontent.com/assets/17544432/21328066/03268b74-c5e7-11e6-9da6-ddab6215d541.PNG)
![babybear2](https://cloud.githubusercontent.com/assets/17544432/21328069/06197f8a-c5e7-11e6-8366-9a8396f99948.PNG)
![babybear3](https://cloud.githubusercontent.com/assets/17544432/21328070/07442806-c5e7-11e6-9360-8455a6ccb27a.PNG)

Also here is my level maxed out mother bear
![babybear4](https://cloud.githubusercontent.com/assets/17544432/21328272/f1588d60-c5e7-11e6-8b90-725b21ad1f12.PNG)
![babybear5](https://cloud.githubusercontent.com/assets/17544432/21328307/1c8e3eee-c5e8-11e6-947a-1738f2c7ca48.PNG)

**Comment by cadon** [comment]
Hi, that's a nice report I can work with :)
It's an easy fix: The default-values on the screenshots by your admin are outdated. To fix it, set the multipliers in the tool to the official values (button under the multipliers), then only change the numbers, that are explicitely set in the server-settings, i.e. only the wild and tamed multipliers, and not the first to columns in the tool. Or easier, change the 0.45 to 0.44 and the 0.15 to 0.14 to make them the default values.

**Comment by owletra** [comment]
Thank you so much! I could NOT figure out what was wrong. :smiley:
