### ISSUE TITLE
Health stat for Argentavis doesn't match with what ASB says it should be.

### ISSUE THREAD

**Issue by JRos2011** [cadon/ARKStatsExtractor#1232]
When I try to extract the stats from my Argis I get a red bar around the health stat even though I entered it exactly as it says on the screen.  I never had this problem until 2 updates ago and then it started happening.  Can anyone help me figure out what the problem is?

**Comment by cadon** [comment]
Hi, did you check all the possible causes of that issue that are listed in the app on the right?
If that doesn't help, we need the export file of the creature and if you play on an unofficial server, all the changed stat multipliers or a screenshot of the settings in Smart Breeding.

**Comment by JRos2011** [comment]
I did try all of the possible causes and none of them worked sadly.  I think the file below is an export file but if its not let me know.  Also I have attached a screenshot of the settings
[ASB_issue_2021-09-21_12-35-25.zip](https://github.com/cadon/ARKStatsExtractor/files/7204827/ASB_issue_2021-09-21_12-35-25.zip)
<img width="617" alt="ASB settings" src="https://user-images.githubusercontent.com/91076775/134211735-ff30c0d4-0ef1-44ba-a2e5-179174339ac2.PNG">

**Comment by cadon** [comment]
Hi, that Argentavis works fine for me. Can you post a screenshot of the failed extraction?

**Comment by JRos2011** [comment]
<img width="642" alt="Argi JB stats" src="https://user-images.githubusercontent.com/91076775/134236257-34f1e5b2-944d-4445-ade7-b545a10caddc.PNG">

**Comment by cadon** [comment]
Did you enter these values manually or did you import an exported file? If you used an export file, does it work if you click on the `Extract Level Distribution` button manually?
The file you posted helped partially, but it doesn't contain the original data from the export file. You can get to this file if you import a file, then click on the file info at the top of the Smart Breeding window where it displays the file path. After clicking that, the folder containing the file opens, then you can post that file here.

**Comment by JRos2011** [comment]
I input the values manually.  I just exported the file and now all the stats are green!!  Thank you for your help!!
