### ISSUE TITLE
Dino Image

### ISSUE THREAD

**Issue by TaraSilver** [cadon/ARKStatsExtractor#1233]
My Smart Breeder no longer shows me what my dino would look like with the colors in smart breeder.  How do I get the image back?  I looked in the image folder and the creatures are all in there but my smart breeder no longer shows.

**Comment by cadon** [comment]
Hi, go to the menu `Settings` - `Extra Data…` and select `Species Images`.

**Comment by TaraSilver** [comment]
thank you so much for your help worked like a charm!!!
