### ISSUE TITLE
ASB updates reset SortNames.txt

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#1234]
I was once in a ticket (https://github.com/cadon/ARKStatsExtractor/issues/1224) told to edit SortNames.txt, but is it possible to have ASB updates not reset this file if the update doesn't have anything to do with the file?

**Comment by cadon** [comment]
Hi, thanks for that report. The initial default sorting file was not deleted from the publish folder. Sorry for that.
