### ISSUE TITLE
FEATURE REQUEST: Allow pulling screenshot from clipboard for OCR

### ISSUE THREAD

**Issue by nortonmi** [cadon/ARKStatsExtractor#1236]
On Windows 10 Store edition this would help tremendously... the auto screenshot capture feature will crash the game sometimes.
Instead... after I take a screenshot I can click a button and you can pull it form the clipboard.

Thanks!!

- Michael

**Comment by cadon** [comment]
Hi, crashing sounds bad. I heard the screenshot taking doesn't work sometimes, but there were no crashes reported so far. What process do you have selected for taking the screenshot in the ASB settings? I can't test that for myself, I don't own the Win10 store version.
Regarding your request, how is the workflow exactly? Do you take a screenshot with the Prnt-key on the keyboard? That way it would probably only work for people with one monitor, or rather, it would need options to set which part of the screenshot is of the game.

**Comment by nortonmi** [comment]
I think it would work exactly as you have it now... if they have two monitors they need to configure the capture settings for the labels... no change.
And yes... the "Print Screen" key on the keyboard sends it to the clipboard.
You could have a button that would allow you to pull from the clipboard.

**Comment by nortonmi** [comment]
This only happens on Win 10 version... it will "change" the window size and then it crashes.
If it did a print screen capture it would be easier.
