### ISSUE TITLE
Make reading easier

### ISSUE THREAD

**Issue by Vykan** [cadon/ARKStatsExtractor#1239]
Would it be possible to display the counters of mutations in separator of thousand in order to make the reading easier?
When I want to reset the mutation counters, the large numbers are difficult to read and the popup does not stay displayed long enough ...
Currently : 630331664
Would be more readable with : 630 331 664
![SeparateurDeMillier](https://user-images.githubusercontent.com/22913843/140485974-c0f786ce-1bae-4aec-9e57-f78a41a5d3c7.png)

**Comment by cadon** [comment]
Hi, thanks for the suggestion, the next release will have better readability for that.
