### ISSUE TITLE
Red boxes

### ISSUE THREAD

**Issue by Skatha127** [cadon/ARKStatsExtractor#124]
Getting red boxes with this newly bred creature. 
Server stats:
https://imgur.com/a/nCd6z

![20161226195647_1](https://cloud.githubusercontent.com/assets/24785823/21490103/b7c6533e-cba5-11e6-9060-c923aeef98c8.jpg)

are my program settings wrong?

**Comment by Zhinjio** [comment]
It can't handle imprinted stats.

**Comment by Skatha127** [comment]
It was having that issue though before i imprinted.

**Comment by cadon** [comment]
Hi, once a creature is imprinted, it's hard to extract it with the tool. Do you have by chance a screenshot before you started the imprinting-process?

**Comment by cadon** [comment]
Hi, once a creature is imprinted, it's hard to extract it with the tool. Do you have by chance a screenshot before you started the imprinting-process?

**Comment by cadon** [comment]
The tool can now handle imprinted creatures.
