### ISSUE TITLE
ASB Swapping Colors?

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#1240]
So the game says the color is 'Green Coloring #206" but ASB reads it as 'Green'.  Normally not a big deal to normal people, but sort of annoying to people trying to collect all the mute only regions to merge together.  Is this a ASB issue or is it a feature?

**Comment by coldino** [comment]
These colours are identical in terms of colour components, so they appear identically in the export files.

ASB has no way to distinguish between them, so chooses the first matching option.

If you look up the color IDs on the wiki you'll see there are something like four cases of this.
