### ISSUE TITLE
Food calculations on Raising tab are wrong

### ISSUE THREAD

**Issue by gpdeb** [cadon/ARKStatsExtractor#1242]
The food calculations for the Baby Phase and Total Maturation on the Raising tab seem to be wildly off.

For example, with BabyMatureSpeedMultiplier = 4 and BabyFoodConsumptionSpeedMultiplier = 2, it reports that a Spino needs 725 Raw Meat for the baby phase, and 3949 Raw Meat for total maturation.

Using a different breeding calculator (which I find to be accurate) with the same multipliers, I get 258 Raw Meat for the baby phase, and 1452 Raw Meat to reach adulthood.

**Comment by cadon** [comment]
Hi, thanks for the report. This calculator will be fixed in the next release. There were some missing multipliers that alter the food consumption of creatures after they're tamed.
