### ISSUE TITLE
How to display and export dinosaur pictures

### ISSUE THREAD

**Issue by lihaha12355** [cadon/ARKStatsExtractor#1243]
![W`}S)KQH9YB}P37JGJW(LF2](https://user-images.githubusercontent.com/87006342/144328671-36fcf107-e2c6-492c-aa25-ed633417eb6f.png)

**Comment by lihaha12355** [comment]
How can I turn this fan-shaped picture into a dinosaur picture

**Comment by coldino** [comment]
You need to install the species images. To do this go to the Extra Data window which you can find in the Settings menu. Once there, tick Species Images.

Note that not all species have images, and I'm not able check right now if Reaper King is included.

I'll close this issue, but please let us know if you still have a problem.

**Comment by lihaha12355** [comment]
![image](https://user-images.githubusercontent.com/87006342/144360141-fc54f516-71ec-44c0-adf6-df0d672744d7.png)

**Comment by lihaha12355** [comment]
I can't download this package

**Comment by lihaha12355** [comment]
I can't download this package

**Comment by lihaha12355** [comment]
> 
I can't download this package

**Comment by cadon** [comment]
This means that site is somehow blocked for you. Maybe it's a firewall or an anti virus application on your computer?

**Comment by lihaha12355** [comment]
![image](https://user-images.githubusercontent.com/87006342/144729982-61dfcc73-5930-4be6-aab2-619ca1586528.png)
I got this compressed package. Which file directory should I put it in，
![image](https://user-images.githubusercontent.com/87006342/144730000-9a6f4da6-a08a-4df0-b622-eeee04eb6858.png)
