### ISSUE TITLE
Library Favourites

### ISSUE THREAD

**Issue by PyroAnimus** [cadon/ARKStatsExtractor#1247]
This is a suggestion, not really an issue, but I usually keep all my breeding dinos in one save file, so when wanting to view a dino type in the library when it's starting letter is near the end of the alphabet (like Rock Drake or Yutyrannus) I usually have to scroll through the whole list of dinos to look for it.
I think it would be helpful to be able to 'pin' or 'favourite' dinos to move them to the top of the list, or have a tab within/next to the library where you can see just the dinos that you look at a lot :)

**Comment by cadon** [comment]
Hi,
there are multiple ways you can solve that.
### Changing the order of the species
You can change the order of the species in the application. Usually it's sorted alphabetically, but that can be adjusted like you want. Go to the menu `Settings` - `Species sorting` - `Edit sorting`. An editor opens, usually there's already one line that sorts the Tek-/X- and R- variants to their vanilla counterparts. Just add a line with your new sorting, the file then could look like
```
^(Aberrant |Tek |R\-|X\-)(.*)$@$2$1
Rock Drake@a
Yutyrannus@a
```
This will tell the application, that you want `Rock Drake` and `Yutyrannus` sorted like it would be `a`, i.e. at the beginning.
You need to restart the application so the sorting will be used.

For more info about the sorting, see https://github.com/cadon/ARKStatsExtractor/wiki/Library#order-of-the-species-in-the-library.

### Applying tags and filter the library
Apply a tag to creatures you like to see often, e.g. `Favourite`, and another tag to creatures you want to hide most of the time, e.g. `Hide`. To do so, select all the creature you want to apply a tag, press the F3 key, at the right bottom enter the name of the tag, click on the plus and click on `apply`. Then in the library click on the menu `Filter library…`. In the `tags` column, uncheck the empty tag and check the tag of the creatures you want to see. Now only the creatures are shown that have that tag.
