### ISSUE TITLE
ASB crashes when using "Import Exported Data"

### ISSUE THREAD

**Issue by Tavarya** [cadon/ARKStatsExtractor#1248]
I have over 1.400 dinos in my database.
When I now want to scan new dinos via the "Import Exported Data" button another little window opens, freezes and closes itself after maybe 4-5 minutes.

Can you help me solving this issue?

**Comment by coldino** [comment]
There are a couple of possibilities here:

Your dino export folder may have become excessively large if you haven't cleared it out at all. You can navigate to the folder (see settings -> import exported for the location) and archive the files manually - or delete if you want. In future you can some of these options to remove or archive entries once imported:
![image](https://user-images.githubusercontent.com/28345893/146542605-94a4e0cb-8226-4feb-8dbe-c278e942fb91.png)

Alternatively there may be an invalid file in there causing problems. Clearing out the existing files would also fix this.

**Comment by cadon** [comment]
By default there is a warning if the export folder contains more than 50 files, reading many files can slow down the app. Do you have set a limit for the files to be read in `Settings` - `Import Exported` - `Warn when importing many creatures`? The default value is 50.

**Comment by Tavarya** [comment]
Thanks a lot for the quick answer!
The issue is solved -> It helped to just archive my files, simple as that.
