### ISSUE TITLE
Food and melee red, Anky

### ISSUE THREAD

**Issue by TotallyOutofIdeas** [cadon/ARKStatsExtractor#125]
Hi there, first time user of your tool so I haven't really figured out how to use it properly yet. This means it might be an issue with the tool or with the user (or possibly both).

So, I'm trying to add a bred, 0% imprinted, Ankylosaurus and I get red boxes on food and melee, all of the other stats are green. I've done everything mentioned in the "common causes"-list but nothing works.

We play on an unofficial server with official/vanilla statsmultiplier settings, but with max wild level 120 and taming speed x3 (I've changed both settings).

I've tried with Allo and Rex as well to see if I'm able to add any of them but so far I've not been able to.  

Since I get red boxes with all of them (not on food for rexes but melee), I must be doing something wrong, but what?

**Comment by cadon** [comment]
Hi, the best is you post a screenshot of the inventory of the not-working creature with all the stats and the total level.

**Comment by TotallyOutofIdeas** [comment]
Thank you for answering. I tried entering the stats once more before posting a screenshot, but to no avail.

Okay, I can't post a screenshot for some reason.

Maybe a link to imgur then: http://imgur.com/a/uLzAR

**Comment by TotallyOutofIdeas** [comment]
I didn't mean to close it, sorry about that.

**Comment by cadon** [comment]
Hi, if it's only food and melee, the issue are in most cases wrong multipliers. The official multipliers did change every couple of months lately, so maybe the server once used the official multipliers, but not anymore. Better ask the admin for the explicit numbers they used in the game.ini.

**Comment by TotallyOutofIdeas** [comment]
I've talked to the server admin and we have never changed any stat multipliers so that's probably not the issue. I've tested with more animals that I have screenshots of, tamed and bred and have gotten different results.

With anky, allo, tapejara and pelagornis I get food and melee error, and with rex and kapros I get melee error (food is green). So far, the only animal I've been able to add is pachyrhino. I feel that if it was the multipliers, I would get the same error with all of them unless there's something I'm missing.

**Comment by cadon** [comment]
The tameAffinity-multiplier only affects melee and food, and for some species it's only melee. So it sounds as if this particular multiplier is wrong in the settings. Can you post a screenshot of a creature that failed to extract and has no domesticated levels yet? Maybe we can work it out with its data.

**Comment by TotallyOutofIdeas** [comment]
Absolutely and thanks for helping out.

Tapejara right after taming:
http://imgur.com/a/Sf0Qu

**Comment by cadon** [comment]
Hi, sorry for the late reply. I can't find any good combination to solve it. A common cause is, that the game does show wrong numbers, especially after a multiplier or a stat was changed by the admins or wildcard. Usually leveling the stat solves that.

**Comment by TotallyOutofIdeas** [comment]
I've tried leveling the melee on the anky and it didn't work, unfortunately. It's a shame as the tool seems very handy for breeding nuts. I'll try using it again in a couple of months, maybe something have changed that might've fixed it then.

Thanks for all the help. :)

**Comment by cadon** [comment]
Hi, don't give up so fast, it's not solved yet :) can you send a screenshot of the inventar with the new values? Is it the Anky "Headbutt"?

**Comment by JackHammer2** [comment]
I have this issue too. When i try to add a newley tamed dino the food and melee damage are red most of the times. Although all the numbers are correct. And another thing, When you click on a stat that are red or yellow there should pop up a new menu, right? It never happens to me. I'm on singleplayer.

**Comment by cadon** [comment]
If you're on an official server, then the issue is most probably the settings for these stats.

A red stat means there is no way for the tool to work with the input. A yellow stat is very common and does only mean, there are more possibilities for that stat. clicking on a yellow stat shows a list of levels on the right to choose from. If that list is not shown, try to resize the window.

**Comment by JackHammer2** [comment]
I have expanded the window to almost the whole screen but that list just won't show up.

**Comment by JackHammer2** [comment]
"Reinstalled" the tool and it works fine now.

**Comment by cadon** [comment]
According to the author, the multipliers on the server were different, it's working now.
