### ISSUE TITLE
Generations & Mutations not showing

### ISSUE THREAD

**Issue by MrBazibaz** [cadon/ARKStatsExtractor#1256]
Hello.

I have an issue where generation and Mutations wont show.
Neither in the app or when i extract the data. Is there a setting i have overlooked?
![image](https://user-images.githubusercontent.com/64749594/149742044-69fa11cf-a6fc-484d-bd31-b98e1facf705.png)

**Comment by coldino** [comment]
This is a oddness in Ark. You need to view the ancestry window of a creature before you export if you are on a server, else this data simply isn't included in the exported data.

**Comment by MrBazibaz** [comment]
oh, fantastic! Thank you so much, will be so much easier to keep track of now!
No biggie at all to open the ancestry window!
