### ISSUE TITLE
Kapro Melee Wrong?

### ISSUE THREAD

**Issue by CloudedLeopard** [cadon/ARKStatsExtractor#126]
When I use the online stat calculators they all say my Kapro has 47 points in melee, but when I input the stats in the ark smart breeding program it says the melee is 36 points. Any idea's why?

**Comment by cadon** [comment]
Probably the other extractors you used don't support tamed creatures. The calculation for wild creatures is easy and there are a couple of extractors for that, but once a creature is tamed it gets complicated.
