### ISSUE TITLE
Import generated name into Ark

### ISSUE THREAD

**Issue by Rumspringa90** [cadon/ARKStatsExtractor#1264]
Hello Sir,
is there any way to re-import the generated Name into an privat Ark server? Or musst I change every name manuel?

Thank you Sir for your Work an have a nice day

**Comment by cadon** [comment]
Hi,
Smart Breeding can automatically copy the generated name to the clipboard after a creature was imported (see the settings for that option), then all you have to do is open the rename textbox of the creature and press Ctrl + V to paste that name. Smart Breeding cannot directly change the name of the creature.

**Comment by Rumspringa90** [comment]
Nice to know. Thanks. :)
