### ISSUE TITLE
Division by zero - Pteranodon?

### ISSUE THREAD

**Issue by jasin** [cadon/ARKStatsExtractor#127]
Extraction.cs - Line 184

`else if (Values.V.species[speciesI].breeding != null)
                imprintingBonus = Math.Round(imprintingBonusRounded * Values.V.species[speciesI].breeding.maturationTimeAdjusted / 14400) * 14400 / Values.V.species[speciesI].breeding.maturationTimeAdjusted;`

maturationTimeAdjusted in my use case was 0 and you obviously can't do this. I am not sure what is intended here, but give me a clue or a hint and I will fix it. Where are these values.V.species[speciesI] coming from?

I did not look very hard

**Comment by jasin** [comment]
After a little more review, you sure this is not just a typo? Could be that you are trying to divide by the maturationTime instead of the maturationTimeAdjusted?

Let me know, I am testing this theory now. As I am still unsure of what is exactly intended. But I am assuming I understand

**Comment by cadon** [comment]
Hi, thanks for the feedback. Which species has a maturationTime of zero? They all should have a number >0 or don't have it at all.

The numbers come from the file values.json from the parameter 'maturationTime'. The variable maturationTimeAdjusted is the one that has to be used in the app, it is the maturationTime with with the set multiplier applied that can be changed in the settings of the app.

That line of code calculates the number of caring-actions (the part that is rounded) and then multiplies it with the percentage each caring-action gives for the total imprintingBonusPercentage.

As said, the maturationTimeAdjusted should be never zero if it exists, but an extra check for that sounds like a good idea.

**Comment by jasin** [comment]
> Did the Pteranodon had a maturationTimeAdjusted of zero?

Yes! But even then I failed to really follow through with this as soon as I saw it was incapable of tracking mutations. Regardless of what I did, I was unable to do what I needed to do. Unless I am missing something. Would help if I could understand why maturationTimeAdjusted was **ZERO**

**Comment by cadon** [comment]
Hm, I have no idea. With the default maturationTimeMultiplier it should be 133334. Can you reproduce this error and post the steps for that? Maybe you have an outdated values.json?

**Comment by jasin** [comment]
Upon closer review to give you somewhere to look. I tried to set a breakpoint at line 120 of Values.cs. I then ran the app in debug and ended up with the division by zero error and never hit the breakpoint where maturationTimeAdjusted is set at **line 120 of Values.cs**

Seems like the code is never being run

**Comment by jasin** [comment]
Just so we are clear

`maturationTime` from values.json is correct when running in debug. The issue is the setting of the `maturationTimeAdjusted` value where it seems the code is not being run.

**Comment by cadon** [comment]
Hm, is the function applyMultipliersToValues() in Form1.cs, line 965 executed for you?

**Comment by jasin** [comment]
nope

**Comment by cadon** [comment]
Strange. I'd pull the source again, it seems something is messed up there.

**Comment by jasin** [comment]
Well, I fixed it here. I simply created a new creature library. Not sure if that is intended or if it should be automated when app is first run.
Where should this code be called from on first run with no creature collection?

Strange, because 3 weeks ago I did not have this issue when I first ran the app. New clone, new directory, new build. be a first for a corrupt clone to compile and run for me

**Comment by cadon** [comment]
Ah, found that bug. It was caused, if there was no default-library loaded automatically at the start. I always had a library opened that was again loaded when starting the tool, so the multipliers got applied automatically.

That bug will be fixed in the next release, thanks for figuring that out!
