### ISSUE TITLE
Limit females to one partner (male) in breeding plan.

### ISSUE THREAD

**Issue by orcoth** [cadon/ARKStatsExtractor#1273]
Im on a slower breeding server, Id like to know how to limit the breeding plan, to show me only the 10 best pairings, excluding partners that are already occupied above.

example image.
849198 F242 MM 0 PM 0 is the first suggestion, and again the fourth suggestion, with a different male.

![image](https://user-images.githubusercontent.com/62999316/178015886-f3aedb89-0d88-48e7-99f6-89cfcd7b260c.png)

**Comment by cadon** [comment]
Hi,
at the left there's the option `Only best suggestion for females`, that will only display the best pairing for each female.
To change the displayed total pairs, see `Settings` - `General` - `Breeding Planner` - `Max Breeding Pair Suggestions`.

**Comment by orcoth** [comment]
Thank you,  problem solved.
