### ISSUE TITLE
Breed Plan apply library filters not working

### ISSUE THREAD

**Issue by Drizzt1990** [cadon/ARKStatsExtractor#1275]
Setting up library filters and ckecking filters in breed plan doesn't seem to apply said filters. 

can be easily reproduced by filtering the library for one tribe and checking "tribe filter from libary" checkbox in the breed plan.

These are the Argents available for the tribe that is not filterd:
![grafik](https://user-images.githubusercontent.com/59632954/178974012-d27a1c48-3fa7-450f-9d7a-98d673ba5423.png)

as one can see there are creatures in the breeding plan that are filter by the the tribe filter in the library, even after chekcing the option

![grafik](https://user-images.githubusercontent.com/59632954/178974548-193630af-26fa-46f2-b807-81fe428714c1.png)

**Comment by cadon** [comment]
Hi, thanks for the report. The checkbox didn't trigger an update of the breeding plan, this will be fixed in the next release. Until then, trigger an update by checking/unchecking a different filert, e.g. the Owner Filter.
