### ISSUE TITLE
v0.50.1.0 issues

### ISSUE THREAD

**Issue by ricnunes** [cadon/ARKStatsExtractor#1277]
Updated to the latest version:

Library doesn't have groups by species and I'm unable to import .ark:

Save file import error - ARK Smart Breeding v0.50.1.0

An error occurred while importing the file E:\TheIsland.ark.

Sorting is not allowed in a virtual ListView.

System.InvalidOperationException in System.Windows.Forms

Method throwing the error: System.Windows.Forms.ListView.Sort

StackTrace:
   at System.Windows.Forms.ListView.Sort()
   at ARKBreedingStats.Form1.<RunSavegameImport>d__646.MoveNext()

**Comment by Drizzt1990** [comment]
Throws error when clicking on unicorn after fresh import: https://pastebin.com/brke1VDh

**Comment by ricnunes** [comment]
Confirming it works, and the group is just a matter of getting used to filter instead, which isn't bad at all.

Thank you.
