### ISSUE TITLE
Lightning Wyvern found on Fjordur has different health value from app

### ISSUE THREAD

**Issue by joncooke** [cadon/ARKStatsExtractor#1279]
Currently on the Smart Breeding app the health scaling for the Lightning Wyvern doesn't match what is seen on the new Fjordur map.
For a bred 100% lightning wyvern with 68 wild points in health (zero dom) the app says it should have 16,619.8 HP, the actual value I see is 22,134.0 HP, which is a 33% difference!

I am running my own server and am using, amongst others, the Dino Storage, Awesome Spyglass and Classic Flyers mods.
Both game and Smart Breeding app are latest versions.

I mention the first two of those because until recently they were also showing some slightly incorrect stats for some dinos, which makes me think that Fjordur is using different models for some dinos?

**Comment by cadon** [comment]
Hi, you can export a creature and import it into Smart Breeding, then the class name of the species is used to make sure it's the correct species variant. Smart Breeding will notify you if the variant of the game species is not found in its data. If it's the correct species, then you might have not set the stat multipliers as they're on your server. To be sure, you can drag & drop the game.ini and gameusersettings.ini onto the settings window of Smart Breeding to import all the needed values. For bred creatures there's also a bug in ARK where they don't show the correct values directly after imprinting them, cryo and uncryo them to get the correct values before importing them.

**Comment by joncooke** [comment]
Ok, thank you for the response :)

I've tried import my .ark savegame and can see my wyverns but they still show the 16k health rather than their actual health.
All of my active wyverns have been in and out of pods, so there's no possibility of the imprint bug being applicable.
The imported data shows the wyverns as the scorched earth ones, rather than something new, but could Wildcard have changed the stat scalings for Fjordur but used the same model?

According to the wiki importing with the .ark file shouldn't require the .ini files, but I tried that anyway and it didn't make a difference (not that I'd actually made any changes on stat scaling or anything).

**Comment by cadon** [comment]
When using the .ark file for the import, only the levels are imported, not the stat values. The stat values are calculated in ASB according to the species properties and the set server stat multipliers.
By drag & drop the ini files you make sure the stat values are displayed correctly (indeed they're not needed for just the import and if you only care about the levels).
Maybe it's just the checkbox for the Singleplayer settings, or it could be more stat multipliers that cause that difference.
If the stats of the Fjordur Wyverns would be different, the class name would be different as well.

**Comment by joncooke** [comment]
It's running on a PvP server with default server settings initially and then increased taming speeds etc, but nothing that should actively change stats either globally or for specific dino species.
It's not a singleplayer setup, which I know does tinker with some things.

I've bred (with mutations) several different dino species and so far on Fjordur and it's only the lightning wyvern that I've noticed with any variation from the expected stats.

I raised the ticket originally because I thought that maybe there was a new model being used, but since that's not the case then maybe we just close the ticket? (and assume it's my game that's weird).
The difference isn't on any dino that I use for boss fights, so I'm not getting anything game-breaking from it.

**Comment by cadon** [comment]
Can you export one  of these  wyverns (walk to it, hold E, select options, then Export Data), open the export file (it's located in a folder similar to `SteamLibrary\steamapps\common\ARK\ShooterGame\Saved\DinoExports\<long number>`) and check if the entry in the 4th row is
`DinoClass=/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Lightning.Wyvern_Character_BP_Lightning`?
Just to make sure the species is not a variant we haven't yet included in the app.

**Comment by joncooke** [comment]
Because I've got classic flyers my line shows up as:
DinoClass=/Game/Mods/ClassicFlyers/Dinos/Wyvern/Wyvern_Character_BP_Lightning.Wyvern_Character_BP_Lightning_C

I didn't think classic flyer changed the stat scaling, but maybe the base wyvern changed since the mod was updated.

**Comment by joncooke** [comment]
Well, as an experiment I switched from classic flyers to speedy flyers, which made no change to the health.
Then to no flyer mod at all, at which point the health reverted back to 16k.

So I think we can say, that even if they aren't doing it intentionally the flyer mods are adjusting the health somehow.
Whether this is because there was a base stat scaling they missed or just a bug in both, but either way it's a bit weird that they both come out with the same value.

The side effect of this is that it somehow wiped my tek engrams, so now I gotta do the bosses again :'(

**Comment by cadon** [comment]
That explains the difference. The Classic Flyers Wyvern has a base HP of 1725, the vanilla Wyvern has 1295. To fix that, just add the mod Classic Flyers in the mod manager in Smart Breeding (menu Settings - Mod value manager). When importing an exported creature, the whole class path of the species is included, so Smart Breeding can exactly chose the matchin species. When importing from a save file, only the last part of the class name is included in the data and there can be ambiguous species, e.g. the Wyvern of Classic Flyers. By adding the mod in ASB, it will choose the mod variant over the vanilla variant if in doubt and the stat values should match again.
The HP was probably nerfed along with the speed back then with the flyer nerf which caused the need of mods like Classic Flyers which kept the original HP values.
Sorry it caused the loss of the engrams, if you're admin you may unlock them again with console commands maybe?

**Comment by alex4401** [comment]
Health has been nerfed in the same patch that made Wyverns breedable, [316.18](https://ark.wiki.gg/wiki/316.18) (TLC3).

**Comment by joncooke** [comment]
I think we close this, I understand where the difference came from :)
