### ISSUE TITLE
Issue W/ Read Values And Extract Level

### ISSUE THREAD

**Issue by Dokumashin** [cadon/ARKStatsExtractor#128]
I'll admit I'm new to your program so I could be doing something wrong and I'll keep lookin but currently every time I press either "Read Values From Ark Window" or "Extract Level Distribution" it does the blink to my ark and back, updates the stats then a window pops up saying "unhandled exception has occured in your application" "Value was either too large or too small for a Decimal". I'm kinda at a loss here lol.

**Comment by cadon** [comment]
Hi, thanks for the feedback. Can you post a screenshot of the inventory you tried to use the OCR on that caused the error?

**Comment by cadon** [comment]
Should be resolved since v0.20.8.3

**Comment by Dokumashin** [comment]
Thanks for trying to help but server got wiped so not playing Ark any more.
I apologize for the bother.
