### ISSUE TITLE
Name generator AND gate?

### ISSUE THREAD

**Issue by Joebosh** [cadon/ARKStatsExtractor#1281]
I was wondering if it is possible to do logic gates in the automatic name generator? I am trying to setup automatic name generation to test two different factors simultaneously. An AND gate would be helpful, but I have no clue how to do it. Something like this
**{{#ifexpr: {topPercent} == 100 AND {sex} == Male | King }}**

**Comment by cadon** [comment]
Hi,
to test two conditions with an and, you can nest the if statements, to use your example, do `{{#ifexpr: {topPercent} == 100 | {{#ifexpr: {sex} == Male | King | {{#ifexpr: {sex} == Female | Queen }} }} }}` to name a male creature with all top stat King and a female Queen.
