### ISSUE TITLE
Gacha

### ISSUE THREAD

**Issue by yacinemp** [cadon/ARKStatsExtractor#1282]

**Comment by coldino** [comment]
?

**Comment by yacinemp** [comment]
> ?

i don't understand this app

**Comment by cadon** [comment]
This section of this page is rather for reporting issues or suggestions. See the [manual](https://github.com/cadon/ARKStatsExtractor/wiki/Manual) for infos how to use Smart Breeding, e.g. [this video series](https://www.youtube.com/watch?v=zOYvKhLAHL4&list=PLyuGYZtaM40p3VI7N0xluPAiRMALGCG4-). For specific questions you can join our [discord server](https://discord.gg/qCYYbQK).
