### ISSUE TITLE
Pedigree tab render issue

### ISSUE THREAD

**Issue by harry323** [cadon/ARKStatsExtractor#1283]
The pedigree tab is missing the column headers on the previous generation. I've tried readjusting the window but the column headers will not display. Maybe it's not supposed to but it would be nice to have.

![image](https://user-images.githubusercontent.com/46381622/183313689-49a35f07-9995-41a2-891f-eb4f84352067.png)

**Comment by cadon** [comment]
Hi, there are no stat name headers for the previous generations, only in the middle. I'll add some.

**Comment by harry323** [comment]
Thanks Cadon. Really appreciate all the work you do on this mod especially after so many years.
