### ISSUE TITLE
library filtering by mutated flag does not work

### ISSUE THREAD

**Issue by vulli321** [cadon/ARKStatsExtractor#1286]
using the library filtering to filter (exclude or include) for mutated state does not work since the flags attribute of creatures deserialized from JSON is empty
i'm adding a pull request which fixes this for me, please take a look

**Comment by cadon** [comment]
Hi, thank you for the report and especially for your proposed solution!
It seems the flag initialization was unintendedly removed in https://github.com/cadon/ARKStatsExtractor/commit/b98f894741cd8da7601c75a71285965683970b9b. I'll readd this after the file was loaded (no need to initialize the flags for every filtering), I also added another fix related to a not set mutated-flag after adding a creature. Thanks again for pointing this out.
