### ISSUE TITLE
Errors and crashes on imprinted creatures

### ISSUE THREAD

**Issue by Zhinjio** [cadon/ARKStatsExtractor#129]
I will provide screenshots when I get back from kid's soccer. I have three argies. 2 with 92% and one with 100%. The two 92% are producing a crash bug. The 100% is producing the error that a reset is sometimes needed. These were all bred many resets ago, so shouldn't be producing that. More to come...

**Comment by Zhinjio** [comment]
Lystro, 65%, crash, screenie and extract attached

![lindsey](https://cloud.githubusercontent.com/assets/4079037/21747170/11f4d8ec-d51c-11e6-896e-8dfe5c6f6e30.png)
[Lindsey_dump.txt](https://github.com/cadon/ARKStatsExtractor/files/691870/Lindsey_dump.txt)
![lindsey_extract](https://cloud.githubusercontent.com/assets/4079037/21747171/11f878c6-d51c-11e6-9e94-9f562b329cdf.png)

**Comment by Zhinjio** [comment]
cyrus, 100% imprinted saber. no crash, just wouldn't correctly get values. screenie and extract attached.

![cyrus](https://cloud.githubusercontent.com/assets/4079037/21747180/41714b6e-d51c-11e6-8255-6771558d27c4.png)
![cyrus_extract](https://cloud.githubusercontent.com/assets/4079037/21747179/417146d2-d51c-11e6-8cb1-7971edca8493.png)

**Comment by Zhinjio** [comment]
settings, in case they are relevant (and I suspect they are):

![extract_settings](https://cloud.githubusercontent.com/assets/4079037/21747205/840c35c4-d51c-11e6-85b1-5cc3d456e942.png)

**Comment by Zhinjio** [comment]
roxy, raptor. 100%. no crash, just fails to get good values...

![roxy](https://cloud.githubusercontent.com/assets/4079037/21747209/bcd1034e-d51c-11e6-8ebc-bd87c49115ea.png)
![roxy_extract](https://cloud.githubusercontent.com/assets/4079037/21747210/bcd29164-d51c-11e6-90ba-95efcbb519c1.png)

**Comment by Zhinjio** [comment]
arsenic, first of a twin pair of argies, 92% imprinted. Crash, screenie and extract attached...

![arsenic](https://cloud.githubusercontent.com/assets/4079037/21747214/f800f76c-d51c-11e6-8c7c-5a816b97bc1e.png)
[Arsenic_dump.txt](https://github.com/cadon/ARKStatsExtractor/files/691875/Arsenic_dump.txt)
![arsenic_extract](https://cloud.githubusercontent.com/assets/4079037/21747215/f8033450-d51c-11e6-9116-2ef5197bdd65.png)

**Comment by Zhinjio** [comment]
And finally, absinthe, second of the twins, 92% argie. crash, screenie and extract attached.

![absinthe](https://cloud.githubusercontent.com/assets/4079037/21747243/75562570-d51d-11e6-8ad3-c9950b10379e.png)
[Absinthe_dump.txt](https://github.com/cadon/ARKStatsExtractor/files/691877/Absinthe_dump.txt)
![absinthe_extract](https://cloud.githubusercontent.com/assets/4079037/21747242/75008796-d51d-11e6-8406-e10ac3946252.png)

**Comment by Zhinjio** [comment]
Anecdotally, it seems like the crashes only occur when the taming percentage is less than 100%. Sample size is very low, obviously, so that could be just coincidence. Absinthe and Arsenic might be interesting since they were twins, but were levelled differently (weight vs. melee). SO their starting stats, and imprinted stats were identical, but after breeding/imprinting, I raised them differently.

Hope all this helps...

- ZJ

**Comment by cadon** [comment]
Hi, thanks a lot!

I think I fixed the crash (fix is in v0.20.8.3, I'll release that soon today).

For the extraction I haven't found a solution yet. Are you playing on an unofficial server with modified cuddleIntervall? If yes, that's probably the reason for the extraction-fails. The Imprinting-percentage of the first Lystro isn't possible with the official settings, as they should increase each cuddle about 25.9%. There's a new setting in the tool ("Cuddle Intervall") that should fix that.

Also, does the server have a modified ImprintingBonus-multiplier? For the 100% imprinted creatures the cuddleIntervall shouldn't cause any problems, but the ImprintingBonusMultiplier could.

**Comment by Zhinjio** [comment]
I believe our current settings are:

BabyImprintingStatScaleMultiplier=1.2
BabyCuddleIntervalMultiplier=0.5

**Comment by cadon** [comment]
Nice, that works for Lindsey, Arsenic and Absinthe (I hope the others, too)! Thanks for all the reports, could fix some bugs with that. Let me know if you have other creatures that don't work, I'll close that issue for now.

**Comment by Zhinjio** [comment]
Confirmed working. I also had "base stats" prior to imprinting for almost all of them, so I was able to compare and confirm that it calculated right. Awesome job. So happy to finally have these in there properly.
