### ISSUE TITLE
Royal Griffin is not in the list

### ISSUE THREAD

**Issue by saurabhtyagi00** [cadon/ARKStatsExtractor#1291]
Hi,

Please add Royal griffin in the dino list, as Royal Griffin's stat is not matching with Griffin

**Comment by cadon** [comment]
Hi, is that a species from a mod?

**Comment by saurabhtyagi00** [comment]
Royal Griffin is from Ark Survival Evolved Mobile. He has different stats in Weight than Griffin on PC

**Comment by Alluraden** [comment]
How would I go about modifying the value of amber on multiplayer to create token accounts

**Comment by coldino** [comment]
Previous comment hidden. This is not the place to talk about cheating in Ark Mobile.

**Comment by Alluraden** [comment]
I’m actually trying to write an anti hacking esp that can detect changes of
values outside normal gameplay
