### ISSUE TITLE
Pachycephalosaurus Erroring During Extraction.

### ISSUE THREAD

**Issue by IvanCGray** [cadon/ARKStatsExtractor#131]
https://imgur.com/a/lprWy

HP has one level invested. Tried with and without leveling it, and have tried unchecking the no restart box, but it reticks every time.

**Comment by cadon** [comment]
Hi, that extraction works for me. Maybe you have altered the multipliers in the settings? Try to click on "Set to Official" under the inputs in the settings and try again.
