### ISSUE TITLE
Found unknown Version 11

### ISSUE THREAD

**Issue by KaitlynnUK** [cadon/ARKStatsExtractor#1311]
Hi, getting this error as of today 27th July 2023), not played or imported since the patch the other day. I download the latest save from (i.e. 'TheVolcano_27.07.2023_18.20.06.ark.gz'), extract the archive and then rename the file to 'TheVolcano.ark', and then do File > Importing from savegame.

```
Save file import error - ARK Smart Breeding v0.55.0.0

An error occurred while importing the file D:\Nitrado ARK Server Backups\TheVolcano.ark.

Found unknown Version 11

System.NotSupportedException in SavegameToolkit

Method throwing the error: SavegameToolkit.ArkSavegame.readBinaryHeader

StackTrace:
   at SavegameToolkit.ArkSavegame.readBinaryHeader(ArkArchive archive)
   at SavegameToolkit.ArkSavegame.ReadBinary(ArkArchive archive, ReadingOptions options)
   at ARKBreedingStats.ImportSavegame.ReadSavegameFile(String fileName)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ARKBreedingStats.ImportSavegame.<ImportCollectionFromSavegame>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ARKBreedingStats.Form1.<RunSavegameImport>d__671.MoveNext()
```

**Comment by cadon** [comment]
Hi, thanks for the report. I just tested the current singleplayer version of ARK (Steam), that still uses the save file version 9. If the server save file version changed, we need to find out what exactly changed to support that version.
Does your server save file is from the vanilla ARK, or may it be changed by any modifications?

**Comment by KaitlynnUK** [comment]
I use:-

The Volcano, Stop The Steal (Pegomastax/Ichthyornis), Death Recovery Mod (v1.13), HoloScuba, Alternate stacks v1.7, Awesome Teleporters!, Castles, Keeps, and Forts Remastered, Ultra Stacks, Castles, Keeps, and Forts: Science Fiction, Dino Storage v2, Balanced Kibble, Better Vaults & BoxesVersion, Awesome SpyGlass!, All Dinos Allow Guns, Structures Plus (S+) and Upgrade Station v1.8i

**Comment by KaitlynnUK** [comment]
Happy to send you a save file if needed.

**Comment by cadon** [comment]
Yes, a save file would be good to analyze that further. Zipping/compressing the save file reduces the file size significantly. If you have discord, you can send it to me there (user `cadaei`), or upload it to the cloud and send the link. Thanks!

**Comment by RodRich1991** [comment]
Have the same issue here. I Saw your folder's path and guess you are using Nitrado server too. The difference here is, my server have no mods, but I get the same error. It was working before. Some weeks ago started

**Comment by cadon** [comment]
alex4401 analyzed the new format and found out the new version is probably used by Nitrado servers to increase performance for large save files and mods are unlikely to be able to alter the save format. Some parts of the new format are not yet understood. Due to vacations a release with an updated save file importer will be released probably in around 3 weeks.

**Comment by miragedmuk** [comment]
I'm also looking into this one.  So far the main change for me seems to be the additional headers, one of which is a pointer to the new location within the save file for cryopod'd creatures.  These were previously stored as a bit array within the cryopod container object and aren't in V11.

Not sure how much time I'm going to have before the weekend but will update you if/when I find out more.

**Comment by tylercasson** [comment]
I've been racking my brain on this as well and am trying to get the data from the new location merged. The best I have to go on is the byte blob leftover after a normal read that leaves a cryopod looking like this after it fails to read `CustomItemDatas` as a `StructPropertyList`:

```jsonc
{
  "Id": 16186,
  "Class": "PrimalItem_WeaponEmptyCryopod_C",
  "Item": true,
  "Names": [
    "PrimalItem_WeaponEmptyCryopod_C_2089"
  ],
  "Properties": [
        ...,
    {
      "name": "CustomItemDatas",
      "type": "ArrayProperty",
      "arrayType": "StructProperty",
      "value": "AQAAAAIA+EYDAAAAAAAAAAAAAQAAAAEAAAAzCAAAAAAAAA==" // 01 00 00 00 02 00 F8 46 03 00 00 00 00 00 00 00 00 00 01 00 00 00 01 00 00 00 33 08 00 00 00 00 00 00
    }
  ],
  "Extra": null
}
```

**Comment by miragedmuk** [comment]
Yeah I'm throwin the towel in for tonight - new cryopod section seems to contain the summary as seen when viewing the cryopod as well as the objects that contain the creature data.  

Doesn't seem to fit any existing model so might have to create a new one to read this in.  Not looked into it too much but believe the CustomItemDatas in a cryopod object probably now contains the creature id or some other pointer to the new location of the cryopod'd creature data in the save file.

**Comment by miragedmuk** [comment]
Anybody had any luck with this yet?  I've figured there is an additional 48 bytes added to the header and know that the first is an INT pointer to the offset of the cryo stored creature data.

Reading past these additional bytes allows the toolkit to load everything with the exception of the cryo creatures.. and various unknown data messages in the log output to investigate.

Once in the cryo stored creature data I have this so far...

String > Record Type? (Dino)
Int > Uknown
String > ClassName
String > Name, Level and Type ("PodRex2 - Lvl 19 (Rex)")
String > Csv color #s ("20,36,0,14,22,22,")
Int > Unknown
String > Gender

After skipping 114 unknown bytes in my data I then get to 

Int > Count of color names
{loop until count of color names} .... String > Color name

A few more bytes of this "summary" record til the end and start of what looks to be normal GameObject components relating to the actual stored creature data: DinoStatusComponent, TamedInventoryComponent etc.

This then starts again after the GameObjects for each remaining stored creature.

**Comment by miragedmuk** [comment]
.. the summary so far for a single stored creature data:

`            archive.Position = storedOffset;

            //how to know how many we have to create a loop?

            var objectType = archive.ReadString(); //type?
            var unknown1 = archive.ReadInt(); //unknown
            var className = archive.ReadString(); //classname
            var nameAndLevel = archive.ReadString(); //name and level
            var colorCodeCsv = archive.ReadString(); //csv list of color #
            var unknown2 = archive.ReadInt();
            var gender = archive.ReadString(); //gender

            archive.SkipBytes(14); //unknown, need to identify

            var hp = archive.ReadFloat();
            var stamina = archive.ReadFloat();
            var weight = archive.ReadFloat();
            var oxy =  archive.ReadFloat();
            var food = archive.ReadFloat();
            var speed = archive.ReadFloat();
            var imprint = archive.ReadFloat();
            var torpor = archive.ReadFloat();


            archive.SkipBytes(16); //unknown, need to identify

            var hpMax = archive.ReadFloat();
            var staminaMax = archive.ReadFloat();
            var weightMax = archive.ReadFloat();
            var oxyMax = archive.ReadFloat();
            var foodMax = archive.ReadFloat();
            var speedMax = archive.ReadFloat();
            var imprintMax = archive.ReadFloat();
            var torporMax = archive.ReadFloat();


            archive.SkipBytes(20);//?

            var colorCount = archive.ReadInt(); //color name count
            List<string> colorNames = new List<string>();
            while(colorCount-- > 0)
            {
                var colorName = archive.ReadString();
                colorNames.Add(colorName);
            }`

**Comment by tylercasson** [comment]
@miragedmuk Nice! I've been looking into the bytes in the `CustomItemDatas` value. It seems to contain, among other unknowns, an offset relative to the new offset for each cryopod. So for me, my first cryopod dino has the following in the `CustomItemDatas` value:

```
01  00  00  00  02  00 [64  17  00  00] 00  00  00  00  00  00
00  00  01  00  00  00  01  00  00  00  D8  07  00  00  00  00
00  00
```

My new cryo offset is `55 C3 98 03 (60343125)`, and adding the `64 17 00 00 (5988)` takes me to the start of that dino's data

![image](https://github.com/cadon/ARKStatsExtractor/assets/3677369/112189b4-0687-4b67-a999-5aca3d631389)

**Comment by tylercasson** [comment]
I'm trying to see if I can get this "pointer" integrated into the normal read process where it used to be able to just read `CustomItemDatas`, but at this point, I'm just throwing things at a wall until something sticks lol

**Comment by miragedmuk** [comment]
I was working more towards a "readBinaryObjectsStored" method which would be called out to instead of the "extractBinaryObjectStoredCreatures" if Version > 10.  

Thanks for the info on the cryopod pointers - will see if I can make more progress after the day job this evening.

**Comment by miragedmuk** [comment]
@tylercasson Thanks man - your pointer for the Cryopod.CustomItemDatas containing an offset for the creature data was a big piece I hadn't worked out yet. 

Hacking away and attempting to identify what I can but still a way to go before I reach the "TamedDinoInventoryComponent_" object. Once we get there though it should just load in as a standard GameObject and that will contain the appropriate creature data for us to query as normal.

`
        private void readBinaryStoredObjects(ArkArchive archive, ReadingOptions options)
        {


            var validStored = Objects
                .Where(o =>
                        (o.ClassName.Name.Contains("Cryopod") || o.ClassString.Contains("SoulTrap_") || o.ClassString.Contains("Vivarium_"))
                        && o.HasAnyProperty("CustomItemDatas")
                )
                .ToList();

            foreach(var o in validStored)
            {
                var customData = o.Properties.First(p => p.NameString == "CustomItemDatas") as PropertyArray;

                if(customData != null)
                {
                    var dataByteArray = customData?.Value as ArkArrayUnknown;
                    if(dataByteArray != null && dataByteArray.Count >= 34)
                    {
                        var dataBytes = dataByteArray?.ToArray<byte>();
                        MemoryStream ms = new MemoryStream(dataBytes);
                        ArkArchive a = new ArkArchive(ms);

                        var cryoUnknown1 = a.ReadShort();
                        var cryoUnknown2 = a.ReadInt();
                        var cryoDataOffset = a.ReadInt();
                        var cryoUnknown3 = a.ReadInt();
                        var cryoUnknown4 = a.ReadInt();
                        var cryoUnknown5 = a.ReadInt();
                        var cryoUnknown6 = a.ReadInt();
                        var cryoUnknown7 = a.ReadInt();
                        var cryoUnknown8 = a.ReadInt();
                        var creatureDataOffset = cryoDataOffset + storedOffset;

                        archive.Position = creatureDataOffset;

                        var objectType = archive.ReadString(); //type?
                        if (objectType.Equals("dino", StringComparison.InvariantCultureIgnoreCase))
                        {
                            var unknown1 = archive.ReadInt(); //unknown
                            var className = archive.ReadString(); //classname
                            var nameAndLevel = archive.ReadString(); //name and level
                            var colorCodeCsv = archive.ReadString(); //csv list of color #
                            var unknown2 = archive.ReadInt();//?
                            var gender = archive.ReadString(); //gender

                            archive.SkipBytes(14);//?

                            var hp = archive.ReadFloat();
                            var stamina = archive.ReadFloat();
                            var weight = archive.ReadFloat();
                            var oxy = archive.ReadFloat();
                            var food = archive.ReadFloat();
                            var speed = archive.ReadFloat();
                            var imprint = archive.ReadFloat();
                            var torpor = archive.ReadFloat();


                            archive.SkipBytes(16); //unknown, need to identify

                            var hpMax = archive.ReadFloat();
                            var staminaMax = archive.ReadFloat();
                            var weightMax = archive.ReadFloat();
                            var oxyMax = archive.ReadFloat();
                            var foodMax = archive.ReadFloat();
                            var speedMax = archive.ReadFloat();
                            var imprintMax = archive.ReadFloat();
                            var torporMax = archive.ReadFloat();

                            archive.SkipBytes(20);//?

                            var colorCount = archive.ReadInt(); //color name count
                            List<string> colorNames = new List<string>();
                            while (colorCount-- > 0)
                            {
                                var colorName = archive.ReadString();
                                colorNames.Add(colorName);
                            }

                        }

                        archive.SkipBytes(28); //?


                        var storedUnknown1 = archive.ReadString(); //classstring
                        var storedUnknown2 = archive.ReadInt();

                        var nameCount = archive.ReadInt();
                        List<ArkName> names = new List<ArkName>();
                        while (nameCount-- > 0)
                        {
                            names.Add(ArkName.From(archive.ReadString()));
                        }
                    }
                }
            }
        }
`

**Comment by miragedmuk** [comment]
It's very hacky but I got as far as loading a lot of the summary information, the DinoCharacterStatusCompont_ and the DinoTamedInventoryComponent_ objects for each cryo creature.

Need to work out what to add to each of these property offsets to get the actual creature property data on GameObject.LoadProperties()
```

        private void readBinaryStoredObjects(ArkArchive archive, ReadingOptions options)
        {


            var validStored = Objects
                .Where(o =>
                        (o.ClassName.Name.Contains("Cryopod") || o.ClassString.Contains("SoulTrap_") || o.ClassString.Contains("Vivarium_"))
                        && o.HasAnyProperty("CustomItemDatas")
                )
                .ToList();

            foreach(var o in validStored)
            {
                var customData = o.Properties.First(p => p.NameString == "CustomItemDatas") as PropertyArray;
                var cryoDataOffset = 0;

                if (customData != null)
                {
                    
                    var dataByteArray = customData?.Value as ArkArrayUnknown;
                    if (dataByteArray != null)
                    {
                        var dataBytes = dataByteArray?.ToArray<byte>();

                        if (dataBytes != null && dataBytes.Length > 0)
                        {
                            using (MemoryStream ms = new MemoryStream(dataBytes))
                            {
                                using (ArkArchive a = new ArkArchive(ms))
                                {

                                    if (dataByteArray?.Count >= 34)
                                    {
                                        var cryoUnknown1 = a.ReadShort();
                                        var cryoUnknown2 = a.ReadInt();

                                        cryoDataOffset = a.ReadInt();

                                        var cryoUnknown3 = a.ReadInt();
                                        var cryoUnknown4 = a.ReadInt();
                                        var cryoUnknown5 = a.ReadInt();
                                        var cryoUnknown6 = a.ReadInt();
                                        var cryoUnknown7 = a.ReadInt();
                                        var cryoUnknown8 = a.ReadInt();

                                    }
                                    else
                                    {
                                        cryoDataOffset = 0;
                                    }
                                }
                            }
                        }
                    }
                    

                    var creatureDataOffset = cryoDataOffset + storedOffset;
                    archive.Position = creatureDataOffset;

                    var objectType = archive.ReadString(); //type?
                    if (objectType.Equals("dino", StringComparison.InvariantCultureIgnoreCase))
                    {
                        var unknown1 = archive.ReadInt(); //unknown
                        var className = archive.ReadString(); //classname
                        var nameAndLevel = archive.ReadString(); //name and level
                        var colorCodeCsv = archive.ReadString(); //csv list of color #
                        var unknown2 = archive.ReadInt();//?
                        var gender = archive.ReadString(); //gender

                        archive.SkipBytes(14);//?

                        var hp = archive.ReadFloat();
                        var stamina = archive.ReadFloat();
                        var weight = archive.ReadFloat();
                        var oxy = archive.ReadFloat();
                        var food = archive.ReadFloat();
                        var speed = archive.ReadFloat();
                        var imprint = archive.ReadFloat();
                        var torpor = archive.ReadFloat();


                        archive.SkipBytes(16); //unknown, need to identify

                        var hpMax = archive.ReadFloat();
                        var staminaMax = archive.ReadFloat();
                        var weightMax = archive.ReadFloat();
                        var oxyMax = archive.ReadFloat();
                        var foodMax = archive.ReadFloat();
                        var speedMax = archive.ReadFloat();
                        var imprintMax = archive.ReadFloat();
                        var torporMax = archive.ReadFloat();

                        archive.SkipBytes(20);//?

                        var colorCount = archive.ReadInt(); //color name count
                        List<string> colorNames = new List<string>();
                        while (colorCount-- > 0)
                        {
                            var colorName = archive.ReadString();
                            colorNames.Add(colorName);
                        }

                    }

                    archive.SkipBytes(28); //?


                    var storedUnknown1 = archive.ReadString(); //classstring
                    var storedUnknown2 = archive.ReadInt();

                    //name table?
                    var nameCount = archive.ReadInt();
                    List<string> names = new List<string>();
                    while (nameCount-- > 0)
                    {
                        names.Add(archive.ReadString());
                    }



                    archive.SkipBytes(44); //?

                    bool useNameTable = archive.UseNameTable;
                    archive.UseNameTable = false;

                    var dinoCharacterStatusComponent = new GameObject(archive);
                    var dinoTamedInventoryComponent = new GameObject(archive);

                    archive.UseNameTable = useNameTable;

                }
            }
        }
```

**Comment by miragedmuk** [comment]
Right, good night sleep and a fresh head.  Day job to finish before I do any coding but I believe the GameObject.propertiesOffset needs to be added to the offset for the start GameObject read for each creature.  

So storing the archive.position before reading in the "dinoComponent = new GameObject...." should be the value needed to pass in to each object's "LoadProperties" as the offset.

I don't understand the name table stuff but I had to set Archive.UseNameTable to false before parsing the GameObjects or exceptions were thrown so any advice on that stuff would be much appreciated.

I'll update the code to check my theory after work and update you guys on my findings.

**Comment by coldino** [comment]
To keep all the relevant data here, @miragedmuk just let us know some console server hosts are seeing a v12 identifier, although it appears the same as v11 currently.

**Comment by cadon** [comment]
Thanks to @miragedmuk and @alex4401 the new savegame file format should be supported with the latest release 0.56.0.1.

**Comment by KaitlynnUK** [comment]
Thank you for your work on his, its appreciated.
