### ISSUE TITLE
Missing S-Variant Dinos (Svartalfheim Mod) in the JSON

### ISSUE THREAD

**Issue by XephSteam** [cadon/ARKStatsExtractor#1312]
Hi there.  I am not sure if I should be contacting ASB or the modder itself, whomever is responsible for updating the mod file data for modded dinos.  The one in question, S-Dino Variants [Svartalfheim Dino Mod] does indeed have a JSON file, however it is missing at least a couple of S-Dinos in it's JSON data.  The ones I have found to be missing are entries for the S-Deinonychus and S-Thylacoleo.  

Please advise where or who I should make a request to in order to update the JSON.  Thank you.

**Comment by coldino** [comment]
That would be me. Interesting - I thought this mod is already covered in our automatic runs. I'll look into it.

**Comment by coldino** [comment]
Oh boy I can see the S-Baryonyx, S-Ravager and S-Deinonychus are missing. Still don't know why they haven't been updating, but this issue could possibly be affecting many other mods too.

**Comment by coldino** [comment]
I made a change to fix this. If it works the bot will update the mod in around 4 hours, then you can ask ASB to check for updates and it should pick it up.

**Comment by coldino** [comment]
Well that didn't work so I'm trying again with a new set of changes tonight.

**Comment by coldino** [comment]
The mod's data is now [updated](https://github.com/arkutils/Obelisk/commit/7d781afa12b12f73cbc62a18d6ea89eb4692b3b8) and is included in the automatic bot for future updates.
