### ISSUE TITLE
Ark smart breeding is not working.

### ISSUE THREAD

**Issue by atilla2240** [cadon/ARKStatsExtractor#1316]
I just intstalled windows 10 nothing is happening when i start it. I see ARK Smart Breeding.exe in Task Manager but nothing on screen. It was working before re-install windows, maybe i should install some requiredements to work ? It  needs any requiredments ?

**Comment by cadon** [comment]
The app needs the .NET framework 4.8, this should be included in the latest windows updates. You can also download it manually here: https://learn.microsoft.com/en-us/dotnet/framework/install/on-windows-10
Another reason could be that an anti virus application is blocking Smart Breeding.

**Comment by atilla2240** [comment]
I loaded Framework 4.8 and antivirus disabled didn't work again. Re-installed from .exe edition and worked, i was using .zip edition. Thank you very much.
