### ISSUE TITLE
Can't extract data of imprinted Dino

### ISSUE THREAD

**Issue by van-dell** [cadon/ARKStatsExtractor#132]
![parents wrong spino](https://cloud.githubusercontent.com/assets/7930420/21749321/f09b3890-d59c-11e6-8a9c-aaabc763cf88.png)
![wrong bred spino](https://cloud.githubusercontent.com/assets/7930420/21749322/f09bdf66-d59c-11e6-98e0-1a3e4120e11a.png)

I attached a screnshot of the parents' stats as well. I haven't changed any of the regular multipliers. 30x maturation, 16x hatch speed, 0.775 cuddleInterval (I can only set 0.78 in smart breeding), but afaik that shouldn't be important. I leveled up once in damage but that made the recognition even worse.

Edit: I set the imprinting percentage to 35 - before the one level-up in damage, it corrected it to 33.xx%, now it's corrected to 0.

Edit 2: This would be the correct baby stats if that helps:
"baseLevel":187,"wildLevels":{"health":27,"stamina":22,"oxygen":24,"food":27,"weight":27,"melee":34,"speed":25},"fullLevel":188,"tamedLevels":{"melee":1}

**Comment by cadon** [comment]
Hi, thanks for the report.

I increased the number of decimals for the cuddleInterval to 3, it's important to have the correct number in there. Do you know if even finer adjustments are common here, i.e. is it necessary to have more decimals in the settings?

The cuddleInterval-setting had a bug, it's fixed in v0.20.8.3. Do you also have the ImprintingBonus-Multiplier changed?

**Comment by van-dell** [comment]
BabyImprintingStatScaleMultiplier=1.0 if that's what you're asking. 

So you're saying this might not work because the cuddle interval doesn't match? That could be the problem, I'm changing that around all the time in order to be able to get 100% imprints on specific species. I think I don't know anymore what it was when this dino was born. Will start to take note from now on.

I don't know how many people use this https://drive.google.com/file/d/0Bz7m6sPGUUA0TE8wTE02RE9PblE/view spreadsheet to calculate their cuddleInterval, but since that uses 3 decimal places, it should be enough for you, too.

**Comment by cadon** [comment]
Then it's probably the cuddle-Interval. The tool has to know exactly which steps the imprinting does for each caring, as the UI does only display the rounded values. So e.g. the tool get's 35% for the Spino you posted and figures out, that the value is 34,8 in reality for example, and uses this preciser number for the extraction.

If the cuddleInterval changes, the steps each cuddle gives to the total Imprinting also changes, so the tool has to know that Interval exactly. AFAIK only the multiplier that was set once the creature hatched / was born counts, later changes are not applied. So you would need to know the multiplier only when the creature hatched and set that in the tool.

**Comment by van-dell** [comment]
I can't figure out what I had set it to when it hatched, but I've written down the current one and the last one so I can just try all of them in case it doesn't work in the future. I'm closing the issue and will reopen it if I encounter any more problems.
