### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by hi-fox** [cadon/ARKStatsExtractor#1320]
No more to add really - is there plans for a dark mode? This tool is invaluable whilst playing and I always have it open on a side monitor but the intense bright light when playing at night causes me headaches.

**Comment by Romaq** [comment]
Please. Or invoke "systemcolors" which are set "dark."

**Comment by cadon** [comment]
Unfortunately hard to do with the currently used framework. Also see #1166 .
