### ISSUE TITLE
wild babies support please?

### ISSUE THREAD

**Issue by cgprincess** [cadon/ARKStatsExtractor#1321]
ASB does not know what to do with wild babies that you have domesticated. The "Wild, Tamed, Bred" selector from the extractor tab doesn't know what to do with that info, nor does it understand why it has an actual dino as one of its parents and wild dinos as its other parent.

**Comment by coldino** [comment]
Some species did already import just fine as wild babies - they are trateted just like they are bred.

We also made a release of ASB since this report that will help with ASA support. Chack out the new option in Settings.
