### ISSUE TITLE
Blueprint path missing and request 

### ISSUE THREAD

**Issue by XephSteam** [cadon/ARKStatsExtractor#1322]
Hi there!  

In the Paleo Ark Legends Expansion, the R-Greater Yuty is missing a blueprint path and gives the error when trying to extract.  Is it possible to get this fixed? Everything else seems to be working in this mod as far as I can see.  

I have a request as well to add the following:

Caballus Custom Map - The Equestrian Land mod (might also be in the Variants of Caballus mod), the following will not extract and do not have paths:
Shimmer griffin
Shimmer Unicorn
Shimmer Pegasus

The RR-StarPegasus mod, is it possible to get these pegasus variants as extractable?

Thanks for your consideration.

**Comment by cadon** [comment]
Hi, the `R-Greater Ytyrannus` with the blueprint path `/Game/Mods/PaleoARKlegends/PaleoVariants/GreaterYuty/Eden_Yutyrannus_Character_BP_Paleo.Eden_Yutyrannus_Character_BP_Paleo` is included in the mod file. Is there a typo in the blueprint path or do you need a different species variant?
I'll give the mod request to the data team.

**Comment by cadon** [comment]
The mod was added.

**Comment by XephSteam** [comment]
> Hi, the `R-Greater Ytyrannus` with the blueprint path `/Game/Mods/PaleoARKlegends/PaleoVariants/GreaterYuty/Eden_Yutyrannus_Character_BP_Paleo.Eden_Yutyrannus_Character_BP_Paleo` is included in the mod file. Is there a typo in the blueprint path or do you need a different species variant? I'll give the mod request to the data team.

Yes, that is the correct variant: Eden_Yutyrannus_Character_BP_Paleo.Eden_Yutyrannus_Character_BP_Paleo
However it gives the error it is an unknown species when trying to extract one (I made sure my ASB was up to date before trying again).  

![image](https://github.com/cadon/ARKStatsExtractor/assets/140844032/b34014fe-de0b-43b8-943f-d738bf815827)

The Export file I just tried has this line:
DinoClass=/Game/Mods/PaleoARKLegends/PaleoVariants/GreaterYuty/Eden_Yutyrannus_Character_BP_Paleo.Eden_Yutyrannus_Character_BP_Paleo_C

Seeing there is a C on the end of that, which is not in your path?  Could this be the disparity? If there is anything else I can provide to help troubleshoot it, please let me know.

**Comment by cadon** [comment]
Hi, the C at the end is no problem, but the different casing of the `L` in `legends` is, because it changes the mod name of that species.
Do other species of that mod also use a capital L in their export files?

**Comment by XephSteam** [comment]
> Hi, the C at the end is no problem, but the different casing of the `L` in `legends` is, because it changes the mod name of that species. Do other species of that mod also use a capital L in their export files?

I checked the other exports for Paleos I had on hand, the rest of them have a lower case legends.  If I run into any other's with the capital Legends, I will let you know.

**Comment by cadon** [comment]
I talked to the mod dev, they said the mod is concluded and won't get any updates anyway. Also they couldn't find the reason why this one species contains a different casing of the L in the blueprintpath, the folders all have the lower case variant.
Does ASB import the file if you change the L in the export file manually to a lower case L?
I'm not yet convinced to adjust the import procedure or how the blueprints are handled internally only because of this one mod species. It doesn't feel clean and would add quite some overhead just to handle this one case.

**Comment by XephSteam** [comment]
I'm not sure why it would come out as a capital L either, this has happened on two different servers with the mod.  

I did, just now try to edit the file to a lower case L and it does import it if I do that (which is much less work than manually entering the ones I want in the database).

Although, this kind of thing is way out of my purview, I understand your predicament of it not being a strong enough case to warrant that amount of work (especially since whatever is causing the error has nothing to do with you), I'll work with this solution when I need to import one, I never thought to change the case in the file until you mentioned it.    I appreciate your work and the time you take to answer these inquiries.  Thanks again for your help, I would feel "naked" in ark without ASB.
