### ISSUE TITLE
Mutated ASA colours not properly displaty

### ISSUE THREAD

**Issue by KalisCoraven** [cadon/ARKStatsExtractor#1324]
My mutated argy baby with pink 0 slot is showing incorrect colour in ASB.  Checking the file, the RGB values for the 0 slot do not match the 2 slot, but they are displayed as the same colour.  This issue seems to only happen with mutations but is happening with all of my mutated dinos.  I also have a visually number 2 blue dodo who's mutation is showing as wyvern purple in the export. 
--------------------------------------
![image](https://github.com/cadon/ARKStatsExtractor/assets/152026492/8f395c55-5fb1-4a1d-a983-65f4fe7ded46)
![image](https://github.com/cadon/ARKStatsExtractor/assets/152026492/5f6c9953-f1d6-4dcf-bbaf-23bad43cddbb)
--------------------------------------
![image](https://github.com/cadon/ARKStatsExtractor/assets/152026492/5eb115e7-3089-4360-b152-da3fca6f8730)
![image](https://github.com/cadon/ARKStatsExtractor/assets/152026492/fd3f65aa-88d4-4077-9dd3-6257f4faaa68)
![image](https://github.com/cadon/ARKStatsExtractor/assets/152026492/e5c8104a-e00c-4a43-aa2c-7246f8802419)

**Comment by cadon** [comment]
Do you have enabled the ASA mode in the settings?

**Comment by KalisCoraven** [comment]
In the Multiplier section?  or somewhere else?  cause I have it set to ASA multipliers

**Comment by cadon** [comment]
Yes. Settings - Multipliers - at the top there's the option `ASE` and `ASA`. If you check `ASA`, the new colors of ASA are loaded, else the imported creatures can't use them.
