### ISSUE TITLE
[Bag] Breeding plan work incorrect

### ISSUE THREAD

**Issue by OxxxHayFay** [cadon/ARKStatsExtractor#1327]
I breed Deinonychus and try to use breeding plan, but it show me better variant for this library wrong.
It show better damage 28, but I have 31, same for weight
![изображение](https://github.com/cadon/ARKStatsExtractor/assets/32496272/ca2cdff5-6475-4834-9de8-caf71d4abb70)
The same problem for other dinos
![изображение](https://github.com/cadon/ARKStatsExtractor/assets/32496272/6fbfc799-6698-4b41-8a86-5fe77e85c9aa)
As result, I see worst breed suggestions.

**Comment by cadon** [comment]
Hi, probably you changed some settings so some stats are not considered as top stats. E.g. you can exclude even or odd levels when breeding for high levels by clicking on the button right of the stat weighting at the bottom left. If on these buttons there is a `1` or `2`, that means you only want odd or even levels as top stat.
