### ISSUE TITLE
App doesn't seem to work correctly with ASA

### ISSUE THREAD

**Issue by JEBBandit** [cadon/ARKStatsExtractor#1329]
A new version of the app, or an option within the app for players who are playing Ark Survival: Ascended would be cool!

**Comment by cadon** [comment]
More details about the issue you would be helpful.
Currently you can check the `ASA` mode in the setting, which will allow you to import the newly introduced colors of ASA. For extracting the dinos make sure you set the `AllowSpeedLeveling` options as they're on your server or singleplayer settings. The newly introduced mutated levels (in ASA separate from the wild levels) are not yet fully implemented, but that doesn't prevent the creatures to be added.

**Comment by cadon** [comment]
Closing assuming it works.
