### ISSUE TITLE
Null reference exception on start

### ISSUE THREAD

**Issue by velocity7** [cadon/ARKStatsExtractor#1332]
Had to add this into the code to get it to compile and run without crashing:
![image](https://github.com/cadon/ARKStatsExtractor/assets/11874183/7b8133c7-df8c-4e42-b563-600e468c0a2c)

**Comment by cadon** [comment]
Hi, thanks for the report and fix! It's resolved in https://github.com/cadon/ARKStatsExtractor/releases/tag/v0.59.3.2
