### ISSUE TITLE
Share list

### ISSUE THREAD

**Issue by xXDxVaXx** [cadon/ARKStatsExtractor#1338]
My tribe mate and I would like to share our list. we shared it via onedrive but unfortunately it doesn't update when someone adds a dino. what could be the reason?

**Comment by Romaq** [comment]
On our tiny whitelist server, we are using a spreadsheet to manage this data. I seriously want to switch to directly exporting the data and "sharing" ... "something"... I'm not clear what, so all those who wish to participate in the breeding program have access to the data I would see in ASB. I will eagerly follow this to see how things shake out towards that end.

**Comment by cadon** [comment]
All users have to enable `Autosave` and `Autoload` in settings - general. Dropbox seems to have a good synchronization time.
