### ISSUE TITLE
Add SFTP Support

### ISSUE THREAD

**Issue by iComputerfreak** [cadon/ARKStatsExtractor#1345]
First of all, your software is amazing and I love it.
But the one thing that is missing for me would be SFTP support.
Currently the programm supports importing savegame files via FTP, but as FTP transmits passwords in plain text, connections via SFTP or FTPS would be preferred.
For me, the main reason is also that the Pterodactyl Server Panel I use to host my server only offers SFTP access.

**Comment by cadon** [comment]
The used framework only supports FTPS (and not SFTP), in the latest release it tries to use that if possible. Does that resolve it for you?

**Comment by iComputerfreak** [comment]
Unfortunately the game server panel I use only supports SFTP, but thank you for the effort 🙂
