### ISSUE TITLE
Sizes get messed up when I import on Windows 11

### ISSUE THREAD

**Issue by RuudRietvink** [cadon/ARKStatsExtractor#1351]
When I click on import and extract the values to the value extractor, the window gets messed up.
![image](https://github.com/cadon/ARKStatsExtractor/assets/48518006/fdeeb288-d01c-4fb6-a4c0-a1bf40197275)

**Comment by cadon** [comment]
It's probably the same reason as in #1350 , try if the solution there also resolves it for you.
