### ISSUE TITLE
Is the health increase per domesticated levels correct?

### ISSUE THREAD

**Issue by KyleSnell1** [cadon/ARKStatsExtractor#1356]
Several creature health increase per domesticated levels are 27% (.27) in the fullstatsraw.  All the websites that list those same stats say they are 5.4%.  Was the value multiplied by 5 in an update?

**Comment by cadon** [comment]
Hi, the default server stat multiplier per domestic level for HP is 0.2, so the value 0.27 on servers that don't change the default stat multiplier results in 0.27 * 0.2 = 0.54 = 5.4 %. See https://ark.wiki.gg/wiki/Server_configuration#PerLevelStatsMultiplier for the default stat multipliers.
The default stat multipliers all were 1.0 on the initial release of the early access but HP and damage got adjusted / nerfed in early access, that was probably around 2017 or 2018.

**Comment by KyleSnell1** [comment]
> Hi, the default server stat multiplier per domestic level for HP is 0.2, so the value 0.27 on servers that don't change the default stat multiplier results in 0.27 * 0.2 = 0.54 = 5.4 %. See https://ark.wiki.gg/wiki/Server_configuration#PerLevelStatsMultiplier for the default stat multipliers. The default stat multipliers all were 1.0 on the initial release of the early access but HP and damage got adjusted / nerfed in early access, that was probably around 2017 or 2018.

So the health and damage domestic level increases (id) listed on ark community wiki, ark Fandom,  and dododex all take in to account the domestic level increase modifier (idM)?

**Comment by cadon** [comment]
Yes, by default these websites display the values which are valid for official servers. On unofficial servers admins can change all stat multipliers (i.e. also wild levels, taming bonus etc. can be adjusted), so the values can be very different there. Afaik Dododex only displays values for wild creatures, so the domestic level multiplier has no effect there.

**Comment by KyleSnell1** [comment]
Thank you! It has been driving me crazy why I could never get the right health stat in my calculations when I was using the equation on the ark community wiki.

**Comment by KyleSnell1** [comment]
Thank you! It has been driving me crazy why I could never get the right health stat in my calculations when I was using the equation on the ark community wiki.

**Comment by cadon** [comment]
You can check https://ark.wiki.gg/wiki/Creature_stats_calculation for the exact formula. The first example calculation handles HP also explaining that extra default server multiplier of 0.2 for domestic levels.
