### ISSUE TITLE
pyroman after update 24/09/2024 does'n extract

### ISSUE THREAD

**Issue by numminorih-git** [cadon/ARKStatsExtractor#1361]
Hi,

pyroman after nerf/update 24/09/2024 does'n extract. Please advise how to proceed

**Comment by DmytroMyronenko** [comment]
The same issue. Looks like Pyroman doesn't extract damage stat properly due to nerf

> Reduced Pyromane's damage scaling by approximately 20%

**Comment by cadon** [comment]
Update of the species data is published. If the app doesn't update automatically click the menu `?` - `check for updates`.

**Comment by numminorih-git** [comment]
fixed THX!
