### ISSUE TITLE
DPI Scaling Issues at 125% Display Scaling (Windows)

### ISSUE THREAD

**Issue by Morat2255** [cadon/ARKStatsExtractor#1363]
Description:
Ark Smart Breeding encounters window scaling and layout issues when running on Windows with a display scaling set to 125%. The program's window and text elements do not render correctly after importing creatures, and the UI becomes scrunched into a small portion of the screen. After re-maximizing, the content is confined to the top-left corner, with the rest of the window space left blank. The error persists until the program is closed and re-opened.

Steps to Reproduce:
Set Windows display scaling to 125% (via Settings > Display > Scale and Layout).
Open Ark Smart Breeding and maximize the window.
Import a creature using the "Import exported data" feature.
Click "Copy values to extractor" in the import dialog box.
After importing, the window will remain maximized, but UI elements will be confined to the corner of the screen, with font sizes reduced and most of the window space empty.
Expected Behavior:
The program should scale properly at 125% DPI and retain correct layout and font size after importing creatures, without needing a restart.

Workaround:
The issue can be temporarily resolved by overriding the program’s DPI scaling settings in Windows Compatibility options:

Right-click on the Ark Smart Breeding executable.
Select Properties.
Go to the Compatibility tab.
Click Change high DPI settings.
Check Override high DPI scaling behavior and set it to System (Enhanced).
Apply and restart the program.
This workaround forces Windows to handle the DPI scaling, fixing the layout and text rendering issues.

Additional Information:
Operating System: Windows 10 
Display Scaling: 125%
Version of Ark Smart Breeding: v0.63.1.3
It seems that Ark Smart Breeding might not be DPI-aware, causing it to misrender on higher DPI settings. Adding explicit support for high DPI displays or allowing the program to scale properly when Windows DPI settings are at values other than 100% could resolve this issue.

(Disclaimer: This was written with the help of ChatGPT. I used it as my tech support to find this fix, so I figured it clearly understands the problem better than I do.)

**Comment by cadon** [comment]
Hi, we haven't figured out why this rescaling happens, or why it happens when importing a creature. The workaround you posted is the only one we have found so far. The used framework is rather outdated and not well suited for dpi aware scaling.
(also see duplicate issues #1350 and #1351)
