### ISSUE TITLE
Clicking "last export" gores the UI when using display scaling on Windows

### ISSUE THREAD

**Issue by dadas190** [cadon/ARKStatsExtractor#1364]
Hello, I just want to report what happens on my system when I import last dino.
The app is usable and I can do pretty much everything else, like check best breeding mates etc, but the moment I import a dino, it just gores the UI, see attached screenshots.

The screenshots are taken using printscreen, it shows both of my screens. On top is my secondary screen, a 1080p full hd screen.
On the bottom is my laptop screen, 2560x1600 14 inch screen. The FHD screen has 100% scaling (no scaling) and the laptop screen has 175% scaling.

Screenshot 1 is what I see before importing. Screenshot 2 is what happens immediately after I click the last export button. Screenshot 3 is how it looks like after maximizing the tool again and Screenshot 4 is how breeding tab looks like. To fix this, i save the imported dino and restart the app, but its kinda annoying.

![1-before importing](https://github.com/user-attachments/assets/05cccb35-1d37-4c60-a81d-993e5db9434f)
![2-after clicking import last exported](https://github.com/user-attachments/assets/f8f95321-0186-4a4c-be31-dd6e6f7e365d)
![3-maximizing smart breeding again](https://github.com/user-attachments/assets/2516dd0a-6e2f-442f-bb87-1813b106ecc5)
![4-breeding tab](https://github.com/user-attachments/assets/9971118e-a938-40ae-81b0-14ff9439dfb7)

Thanks, hope this report helps

**Comment by cadon** [comment]
Hi, see #1350 for a workaround.
