### ISSUE TITLE
OCR reads "i" as "l" 100% of the time in creatures' names.

### ISSUE THREAD

**Issue by van-dell** [cadon/ARKStatsExtractor#137]
I'm using 1080p and this happens every single time. Is there something I can do to help OCR, like gamma down or up?

If you say I just have to live with it and manually correct it, that's fine. Just thought I'd bring it up.

On a related note: Do you think it'd be possible to integrate automatic removal of the prefixes "Baby", "Adolescent", "Juvenile" before names? That'd be really nice.

**Comment by cadon** [comment]
Hi, sadly, as a user you cannot do anything to improve the OCR. The OCR works with comparing pixels of the recognized letters with a dictionary of letters, and the one with the biggest accordance is used. With these narrow letters there's often an issue with anti-aliasing, so that it's hard for the tool to see where the letter actually begins, and errors occur. The user @tsebring did work on the OCR algorithm and uses some external libraries for improving that. I haven't tried it out yet, but give it a look here: https://github.com/tsebring/ARKStatsExtractor . Keep in mind though, that updates on this branch might not be merged over to their branch. You might ask them to merge in the newest patches though, if you like their new OCR.

Good idea with the removing of the prefixes of the names, I'll include that in the next release.

**Comment by cadon** [comment]
Hi, can you send me a screenshot where a dino has an 'i' in its name and the tool recognizes it as 'l'? Maybe I can use that to finetune the OCR.

**Comment by Zhinjio** [comment]
I have dozens. This happens to me all the time. h -> k, k -> h, i to I or l, u -> o and vice versa. Do you maybe want one example of each? And what do you want a screenie of, the ARK screen at the top where the name is shown? And I assume what it turns into once in the tool?

**Comment by cadon** [comment]
I'd need a fullscreen screenshot of the inventory in the game, i.e. the screen the tool uses to read the letters. Maybe first send a case that seems promising, I guess the 'i' -> 'l' one would be a start.

**Comment by Zhinjio** [comment]
No problem. I'll get a few of them either tonight (assuming too much beer doesn't happen) or tomorrow.

:)

**Comment by Zhinjio** [comment]
here you go...
![absinthe_extract](https://cloud.githubusercontent.com/assets/4079037/21957611/4bb2b4ce-da57-11e6-8c61-a0548054fca9.png)
![absinthe_extract2](https://cloud.githubusercontent.com/assets/4079037/21957622/4c087062-da57-11e6-9c8f-b9d04f9f50b8.png)
![pestilence](https://cloud.githubusercontent.com/assets/4079037/21957613/4bb3b810-da57-11e6-98db-2b3a8cfb7075.png)
![pestilence_extract](https://cloud.githubusercontent.com/assets/4079037/21957612/4bb3677a-da57-11e6-9f69-bf1ee2564b5d.png)
![sabine](https://cloud.githubusercontent.com/assets/4079037/21957615/4bb4f662-da57-11e6-8213-33a365e9ca5e.png)
![sabine_extract](https://cloud.githubusercontent.com/assets/4079037/21957614/4bb3a974-da57-11e6-9b7d-9354f20b10c5.png)
![sacrifice](https://cloud.githubusercontent.com/assets/4079037/21957616/4bbf1f16-da57-11e6-8907-d23f55bda4c1.png)
![sacrifice_extract](https://cloud.githubusercontent.com/assets/4079037/21957617/4bc08568-da57-11e6-9435-ae2565711372.png)
![sanctimonious](https://cloud.githubusercontent.com/assets/4079037/21957619/4bc106c8-da57-11e6-83d3-57c7fe89e8ea.png)
![sanctimonious_extract](https://cloud.githubusercontent.com/assets/4079037/21957618/4bc0e0ee-da57-11e6-99e5-b99b82a3fe81.png)
![suki_extract2](https://cloud.githubusercontent.com/assets/4079037/21957620/4bc2e416-da57-11e6-8922-499fc3906b07.png)
![suki2](https://cloud.githubusercontent.com/assets/4079037/21957621/4bcb917e-da57-11e6-8aa8-ca13e71ea9fd.png)

**Comment by Zhinjio** [comment]
Looks like I include the image for th extraction of Absinthe, but not the image.

**Comment by Zhinjio** [comment]
ack
you said fullscreen. should I redo them?

**Comment by van-dell** [comment]
![miss selfridge](https://cloud.githubusercontent.com/assets/7930420/21961360/4dc63946-db08-11e6-9ca0-1050e1ba3225.jpg)
recognizes MlssSel6ldge

![adidas](https://cloud.githubusercontent.com/assets/7930420/21961395/fba03940-db08-11e6-82fb-bcc1d84d922b.png)
recognizes adIdas

The second screenshot should be lossless, first is Steam screenshot jpg. This is on gamma 2, because gamma 1 had even worse results. Just tell me what else you need and I can provide it.

**Comment by cadon** [comment]
OCR-system was redone in 0.23, should be improved now.
