### ISSUE TITLE
Taming Calculations are wrong

### ISSUE THREAD

**Issue by FireCulex** [cadon/ARKStatsExtractor#138]
they dont agree with ark survival taming calculator
http://i.imgur.com/4wLpv1k.png
http://i.imgur.com/W84kTkU.png

**Comment by cadon** [comment]
Thanks for the report! That's from the 2x taming they introduced a while ago, I forgot to adjust that in the tool. It'll be fixed in the next release. Until then you can set the taming-multiplier to 2 in the settings.

**Comment by FireCulex** [comment]
got it thanks. technically the official servers are 1x but your program requires all multipliers to be double, for example 1.5x evolution event requires 3x to be set. it lists 0 narcoberries and 0 narcotics, and i'm not sure about the 55 minute train time while ark taming calculator shows 2:45

**Comment by FireCulex** [comment]
http://i.imgur.com/sGm9sti.png

**Comment by cadon** [comment]
Hi, the calculator at http://www.survive-ark.com/taming-calculator/ also shows me 50:23 for the lvl 90 Anky, the same as the tool.

If I type in the values of your first linked image, I can extract the creature's values with the official multipliers. But how did all the controls get disabled? I never saw this, that shouldn't happen. Do you remember how they turned disabled?

**Comment by cadon** [comment]
The initial reported bug with the taming-multiplier is fixed now. If you still have issues with it now, feel free to reopen this issue or to create a new one.

**Comment by FireCulex** [comment]
http://i.imgur.com/AA9vvWa.png
http://i.imgur.com/WLiasul.png

still wrong
http://i.imgur.com/2bWL1fh.png appears to be correct as it took 5 hours not 3.

**Comment by cadon** [comment]
Hi, thanks for the report. The values of the Therizinosaurus were adjusted in one of the latest patches. Get the new values by clicking on ? -> Check for Updates.

Remember to set the Taming-multiplier to 1 for official servers now, the tool is internally adjusted to the new 2x multipliers.
