### ISSUE TITLE
Direwolf stats not working - Directly after the tame.

### ISSUE THREAD

**Issue by LeylaArk** [cadon/ARKStatsExtractor#14]
Are the dino stats updated again so that it is not working or am I doing something wrong?

I have tamed a direwolf, and screenshotted the stats directly after the tame. So I **know** that I haven't increased any of the stats.

![346110_20160322030626_1](https://cloud.githubusercontent.com/assets/18007828/13952886/576914c4-f039-11e5-884a-8e0842b0e66c.png)

That's my wolf and his stats.

![2016-03-22](https://cloud.githubusercontent.com/assets/18007828/13952915/728e337e-f039-11e5-9ac2-970cca45305e.png)

And that's a creenshot of your tool.

P.S: I play on a private server, but with regular dino stats. There is just a Taming (time) multiplier auf 3x. Does that make any difference, do I have to set it somewhere? Guess it affects Taming-Effiency?

**Comment by LeylaArk** [comment]
Okay, I tried calculating the stats of several of my dinos now. Some leveled already, so that aren't.
Seems to be a generel problem with all that the settings on the right are orange-red and the stats Health, Food and Damage are red, not working.

I am confused. Does that mean we have different multipliers on the server maybe? Or is the tool not working for private servers?

**Comment by NakramR** [comment]
If you want to check the stats directly after a tame, be sure to check the
checkbox "Since Taming No Server Restart". This is due to the torpor value
being inaccurate until the server is restarted for new tames.

**Comment by LeylaArk** [comment]
@NakramR tried it with on and off. Tried it with Dinos that I have far longer than the last server restart. Doesn't work. Always health, food and damage red.

![2016-03-22 1](https://cloud.githubusercontent.com/assets/18007828/13955255/414d26e8-f044-11e5-9b51-71128d2a50b3.png)

**Comment by NakramR** [comment]
Is the server up to date with the latest patches?

Does it only apply to your direwolves or other dinos too?

**Comment by LeylaArk** [comment]
Servers version is v236.6 (taken from the data under "Esc").

And yes, as I said it applies to all dinos I have tested. Health, Food and Damage, with all. I have tried Direwolf, Ankylo, Argentavis, Mesopithicus and Gigantopithecus.

If it's important, the server I am playing on is http://ark-servers.net/server/25681/

**Comment by cadon** [comment]
Hi, I just checked the Direwolf ingame, the health seems to be unchanged. I set all multipliers to 1 and the values could be extracted. To do this, make a copy the file multipliers.txt, name it multipliers_myServer.txt (or something else, doesn't matter), open it and set all the values to 1 (most of them are 1 anyway). In the tool choose File -> Load Multiplier-File and select the just edited file.

Of course that is only useful, if your server has these multiplier, else the levels will be wrong and of no use. If they are correct, it looks like you found an amazing wolf with 36 levels in Health. Keep it and breed it ;)

**Comment by LeylaArk** [comment]
Okay, I have changed the two lines in my multiplier file which weren't `1,1,1`, loaded it and tried again. Now it's working, everything green!

![2016-03-22 2](https://cloud.githubusercontent.com/assets/18007828/13958196/8773d300-f04f-11e5-8364-8c7ad8bab418.png)

That's amazing. Don't know what's wrong still, but now I can use your tool ^.^
Thank you for that quick help.

Oh and yeah, it's even black, which is the best color, so that will be the male base of my breed :P 

Two last questions here, if I can "abuse" this issue thread:
1. Have you ever seen the "Wild Stats Level-up" table in the ark wiki? I like the tooltips which show how good your tame/breed really is compared to probabilities. I am quite sure there is a stochastical function in the background. Ever thought about adding something similar? I have seen the colored bars under the stats, but I am not sure what they really mean.
2. Any way to donate you something? Amazing tool you did there.

**Comment by cadon** [comment]
Good to hear it worked :)
1. Yes, I saw that Wild-Stats-Level-up on the wiki, I made it ;) I'll add the percentages to the tool as well, that's a good idea. The colored bars under the stat represent the levels spend in that stat. The bar-length is zero for level zero and goes up to the right when the level is 40 (never heard of a higher level than this). So the longer the bar, the better the level.
2. Never thought about that. I'll have a look for the possibilities. Thanks for the offer anyway :)

**Comment by LeylaArk** [comment]
Even more reasons to donate you when you made that too :D 
1. Okay, so the bars represent just the "wild" stats? That's good. So it should be similar to the color scheme you get when you enter your stats in the wiki. The percentages would be even cooler though, waiting for it.
2. I'll check in the future if you've added a way. Otherwise it won't hurt me if I can't donate, was just a suggestion :P
