### ISSUE TITLE
Pteranodon Speed Issue

### ISSUE THREAD

**Issue by MDLeide** [cadon/ARKStatsExtractor#140]
I just updated to the newest version, and Pteranodons are getting an extraction failure on the movement speed stat. I freshly tamed 3, and they all fail on speed. Same happens on some older Pteras, too, that are already in the library from the previous version. All settings are official.

I can provide some screenshots if you need them.

**Comment by MDLeide** [comment]
So, I did a little digging, and discovered the issue probably lies with the stat multipliers for Ptera speed in the values.json file. The values.json version that shipped with 0.20.7.0 works, but the newest does not. Have there been modifications to increase values or affinity bonuses? I host a dedicated server, and I try to keep my stat settings official, but maybe I missed a change?

**Comment by cadon** [comment]
Hi, yes, the additive bonus for the Pteranodon's speed was nerfed from +36.5% to+35%, around Dec 24. I couldn't find it in the patchnotes, though, so it could be a bit earlier.

After such a change, the values of the creatures are often not updated immediately, but only after a stat of the creature is changed/leveled, so all stats are updated with the new value.

**Comment by MDLeide** [comment]
Yup, that explains everything. Thanks a lot for the response, and the software. It's great. Do you accept contributions?

**Comment by cadon** [comment]
Glad you like it :) You can contribute by posting new ideas for cool features, bug-reports or a coffee (link is on the main-page).
