### ISSUE TITLE
Extractor Problem when switching between tamed and bred creatures

### ISSUE THREAD

**Issue by noheals** [cadon/ARKStatsExtractor#141]
Hi,
when switching from a bred creature with an imprinting bonus greater than 0% to a tamed creature, the Extractor gets confused and everything is red and yellow.

Workaround: Switch back to bred creature and set imprint bonus to 0% (click in another field, so it gets saved). Then switch back to tamed creature and extract with no problems.

**Comment by cadon** [comment]
Hi, thanks for that! It'll be fixed in the next release.
