### ISSUE TITLE
Imprinting Bonus rounded wrong

### ISSUE THREAD

**Issue by cadon** [cadon/ARKStatsExtractor#143]
From #77
> Sure thing, here you go. Imprinting done to 91%, but program calculates 97%
>
> BabyCuddleIntervalMultilper is 0.01
>
> ![capture](https://cloud.githubusercontent.com/assets/1366816/21963671/c9ea893e-db92-11e6-8997-355584a7b251.PNG)

I moved that over to a new issue, as it's independant and unsolved yet.

There might be something else wrong. I could extract Stamina, Ox, Weight, Melee and Speed with these data, all settings on official, only cuddleInterval on 0.01. The tool found an Imprinting Bonus of 90.72 %.

This could be the issue that not all stat-values are increased after a cuddle, i.e. some stat-values behave as if they received one or more cuddles less. Are your multipliers different from the official ones?

**Comment by cyberangel67** [comment]
A little different.

If there is something else you need let me know.

![capture](https://cloud.githubusercontent.com/assets/1366816/21965792/13a85d44-dbbb-11e6-85e0-7303cd32ee89.PNG)

**Comment by cadon** [comment]
Could it be the BabyMatureSpeedMultiplier or the BabyCuddleIntervalMultiplier were different when that beaver was born? With a matureSpeed of 500 each cuddle gives +32.40 % Imprinting Bonus according to my calculations (14400 / maturetime = 14400 / (222222. / 500) = 32.40 % ), so if you cuddled it 3 times, the imprinting can only be ~97%. Or is the imprinting Bonus decaying after some time on your server? I haven't dealt with that yet, not sure if that's even possible to implement.

**Comment by cyberangel67** [comment]
Not sure, the mature speed possibly, I can check with another a bit later and let you know with the imprint side.

**Comment by cyberangel67** [comment]
Ok tried it on a more recent imprint I did.

As you can see the Extractor came back wrong for the imprint, marginally different but different none the less. I copied the values to the tester and adjusted the values to match as per screen shot.

![capture](https://cloud.githubusercontent.com/assets/1366816/21966153/3fe6dba4-dbc2-11e6-98c8-13c95e7ec4e0.PNG)
![capture1](https://cloud.githubusercontent.com/assets/1366816/21966154/43110d18-dbc2-11e6-96ee-74c49f16dcaf.PNG)

**Comment by cadon** [comment]
Found the reasons:
* first it's a rounding problem, that occurs with these high multipliers. I'll release a new version shortly that solves that.
* The beaver Misha works with a maturingMultiplier of 350. For the creatures only the multiplier that was set at birth / hatching count for them.

**Comment by cadon** [comment]
Should be solved now, as usual thanks for the feedback to solve these bugs!

**Comment by cyberangel67** [comment]
Yeah that sounds about right for Misha and you're welcome
