### ISSUE TITLE
A way to know the multipliers of the server u are playing without asking the admins?

### ISSUE THREAD

**Issue by luismi183** [cadon/ARKStatsExtractor#145]
theres a way to get the multippliers without having to ask the admins for a file?
oh and if there sint, which file do i have to ask for?

**Comment by cadon** [comment]
Hi, there are too many combinations the multiplier can be set. I'd just ask to have the right numbers for sure. All relevant multipliers are in the files game.ini and gameUserSettings.ini, but many server-provider offer a nicer way to adjust these multipliers, so I'd just ask for the multipliers you need. I.e. the stat-multiplier, breeding-/hatching- and taming-multipliers.

**Comment by luismi183** [comment]
okei thanks
