### ISSUE TITLE
Decimal point needed for Ark Chat

### ISSUE THREAD

**Issue by noheals** [cadon/ARKStatsExtractor#148]
When exporting a dinos stats for Ark Chat (both breeding and current values) the Color numbers are seperated by comma, but your decimal values also use a comma instead of a decimal point which results in too many numbers for the Color. 

Example:
Right now: `<RichColor Color="0,2,0,67,1,1">`
Should be: `<RichColor Color="0.2,0.67,1,1">`

**Comment by cadon** [comment]
Hi, thanks for that report. That's probably an issue on systems that have set the comma as decimal separator. I'll set that to a dot, regardless of the system-settings in the next release.

**Comment by cadon** [comment]
Should be solved now in 0.20.9.3.
