### ISSUE TITLE
.ArgumentOutOfRangeException while entering data in Extractor

### ISSUE THREAD

**Issue by LeylaArk** [cadon/ARKStatsExtractor#15]
Heya. Me again. I am not really sure how to reproduce, it's a bit difficult, but sometimes (and more than a few times) I get an exception when extracting stats. I can just dismiss it and go on, nothing happens, but maybe you can see something in the exception log?

> Informationen über das Aufrufen von JIT-Debuggen
> anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.
> 
> ************** Ausnahmetext **************
> System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Auflistung sein.
> Parametername: index
>    bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>    bei ARKBreedingStats.Form1.findParentSimilarities(List`1[] parents, Creature creature)
>    bei ARKBreedingStats.Form1.updateParentListInput(CreatureInfoInput input)
>    bei ARKBreedingStats.Form1.creatureInfoInput_ParentListRequested(CreatureInfoInput sender)
>    bei ARKBreedingStats.CreatureInfoInput.groupBox1_Enter(Object sender, EventArgs e)
>    bei System.Windows.Forms.Control.OnEnter(EventArgs e)
>    bei System.Windows.Forms.Control.NotifyEnter()
>    bei System.Windows.Forms.ContainerControl.UpdateFocusedControl()
> 
> 
> ************** Geladene Assemblys **************
> mscorlib
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1073.0 built by: NETFXREL3STAGE.
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.
> ----------------------------------------
> ARK Smart Breeding
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 0.17.5.0.
>     CodeBase: file:///D:/SkyDrive/Stuff/Ark/Ark%20Smart%20Breeding/ARK%20Smart%20Breeding.exe.
> ----------------------------------------
> System.Windows.Forms
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1038.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
> ----------------------------------------
> System
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1038.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
> ----------------------------------------
> System.Drawing
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1068.2 built by: NETFXREL3STAGE.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
> ----------------------------------------
> System.Configuration
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1038.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
> ----------------------------------------
> System.Core
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1038.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
> ----------------------------------------
> System.Xml
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1064.2 built by: NETFXREL3STAGE.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> System.Windows.Forms.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1038.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly-Version: 1.0.0.0.
>     Win32-Version: 4.6.1064.2 built by: NETFXREL3STAGE.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
> ----------------------------------------
> Accessibility
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1038.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
> ----------------------------------------
> mscorlib.resources
>     Assembly-Version: 4.0.0.0.
>     Win32-Version: 4.6.1038.0 built by: NETFXREL2.
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
> ----------------------------------------
> 
> ************** JIT-Debuggen **************
> Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
> Konfigurationsdatei der Anwendung oder des Computers
> (machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
> Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.
> 
> Zum Beispiel:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
> Ausnahmen an den JIT-Debugger gesendet, der auf dem
> Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

Sorry for german text, I use a german OS; but I think the important parts are the code lines, right?

If you need more details, please tell me.

**Comment by cadon** [comment]
Hi,
I think I fixed that bug in one of the last versions, but could be it's not yet released. Do you have the [latest version](https://github.com/cadon/ARKStatsExtractor/releases/latest) 0.17.7?

**Comment by LeylaArk** [comment]
Tool Info says 0.17.5.0
Downloaded it like 3 or 4 days ago. So I'll just update it and check :D

**Comment by LeylaArk** [comment]
Hasn't happened again since updating, and I added a few dinos.
So seems to be solved, thank you.
