### ISSUE TITLE
Critical Bug in 0.20.9.3 Breeding Plan

### ISSUE THREAD

**Issue by noheals** [cadon/ARKStatsExtractor#150]
Selecting any Species in the new version in the Breeding Plan tab results in an error:

http://pastebin.com/ZvrxVCRu

My Database: http://www39.zippyshare.com/v/5asNFCL4/file.html

Edit: Searching for best breeding partner for a specific dino works

**Comment by cadon** [comment]
Thanks! Just released a fixed version.
