### ISSUE TITLE
Suggestion: "Finished in" field for Timer

### ISSUE THREAD

**Issue by noheals** [cadon/ARKStatsExtractor#153]
Right now i have to calculate the "Finished at" time for imprints and other stuff in my head. It would be nice to have a "Finished in" field where you can put in the amount of time in a format like this: `h:m:s`.
Maybe have a whole new "Add Timer" widget right below the existing one so we have the best of both methods.

**Comment by cadon** [comment]
Good idea, will be added in the next release.

**Comment by cadon** [comment]
it's added in v.0.20.10
