### ISSUE TITLE
Suggestion: "Grown in" automatically

### ISSUE THREAD

**Issue by noheals** [cadon/ARKStatsExtractor#155]
I might be wrong but is it not possible to calculate the "Grown in" time like this: `maturationTime-currentWeight/matureWeight*maturationTime`. If so couldn't you make a field for current weight (instead/additionally to "hours") so it calculates the time automatically? Also maybe the OCR could read the current Weight automatically too?

**Comment by noheals** [comment]
hm i never could get the overlay to work. the overlay process is running and when i tab in to it its empty and i can type things in to it which get deleted after a second.
But what i originally meant was that with setting the grown timer the dino doesnt show up in the breeding planer until its grown. And right now i have to set the grown in time manually.

**Comment by cadon** [comment]
The OCR works best with a resolution of 1920x1080, 1680x1050 works kinda, and all other resolution probably work only seldom.

I'll add the weight-input to set the maturation-counter.

**Comment by noheals** [comment]
yes the ocr works fine but the overlay does not

**Comment by cadon** [comment]
After rereading the previous comment, the overlay is just there and displays infos in the game if you open an inventory, there's no possibility to input data into it.

For example, if you have the overlay enabled and open the inventory of a baby, the overlay displays (in the game) the time the baby needs to complete the baby-phase or the maturation as a whole.

**Comment by noheals** [comment]
oh its only in the inventory ok ok it works

**Comment by cadon** [comment]
it's added in v.0.20.10
