### ISSUE TITLE
Use Xamarin to port existing code to other platforms.

### ISSUE THREAD

**Issue by vanstinator** [cadon/ARKStatsExtractor#156]
I'm considering forking this and retooling it with Xamarin so we can target PC as now but also Android and iOS phones and tablets. Any concerns on your part and are you open to exploring this if I throw something together?

**Comment by cadon** [comment]
Hi, sounds good. I started to play around with Xamarin with the same intention, but haven't gotten really far yet. Currently, I'm more inclined to rewrite it as web-application, but no ETA yet.

You can use all of the code under the MIT-license (roughly: do what you want as long as you include the copyright-info with the things you make out of it).

**Comment by vanstinator** [comment]
I'll probably take a stab at it and see about getting an Android port
working with some basic features. If you like it we can talk about merging
something together. If you do end up doing a web rewrite I'd probably just
deprecate my work and help out where I can. Either way I'll take a stab at
something over the weekend.

**Comment by cadon** [comment]
Currently no plans to port the application. Closing this for now.
