### ISSUE TITLE
"read values from ARK window" button is not working when using multiple screens

### ISSUE THREAD

**Issue by KaptainZ** [cadon/ARKStatsExtractor#157]
I have looked in the help and this site and can't find anything regarding this type of issue. I have tried multiple times with different dinos and have also restarted server, and it continues to do nothing. Also I'm playing in a single player world. I hope I can get this fixed soon, also I appreciate any help thanks :)

**Comment by cadon** [comment]
Hi, the OCR-feature does not work very well, especially in resolutions other than 1920x1080. You have to open the inventory of a creature you want to read the values from, Alt-Tab to the tool and click the button. It's reported that it's not working if you have multiple monitors, too. If it's not doing anything, you still can type in the values manually.

**Comment by KaptainZ** [comment]
ya i have been typing them in i just wanted to report that and ya i have 2 monitors 

ty for responding and for making this tool it is beyond very helpful

**Comment by Maximo101** [comment]
I am also having this issue. I have two monitors but then have one disabled. I use my home theatre (hdmi through amp to projector) and no matter what I do, the Read Values from Ark Window button does not work. When I click it, it just goes back to ark, then does not re open Ark Smart breeding.
I would really like to have this feature working :(

**Comment by cadon** [comment]
The OCR now is independent from the resolution, as long as you have a correct config-file. How such a config file can be created is described here: https://github.com/cadon/ARKStatsExtractor/wiki/OCR. IF you have created config-files for specific resolutions, you can post them here and I'll include them in the repository. I'm closing this issue for now, if there are more issues, reopen this one or create a new one.
