### ISSUE TITLE
Pinning of Imprint percentages seems wrong

### ISSUE THREAD

**Issue by Dessa** [cadon/ARKStatsExtractor#159]
![ib_ase](https://cloud.githubusercontent.com/assets/110693/22407806/f46a1fe0-e66d-11e6-9405-3f59e2c334b2.jpg)

imprinting Quality is "0.9165331721305847" as extracted from the Save File

**Comment by cadon** [comment]
If the imprinting-percentage does not match, it's most probably the BabyCuddleIntervalMultiplier that's not set correctly to the server-setting.

**Comment by Dessa** [comment]
it is set to 0.2 (though im still trying to figure out a sane setting; without thinking that setting itself might affect the imprint gains) it is set that way in the app as well

...yes i really thought a lower BabyCuddleIntervalMultiplier might make the possibility of getting 100% imprinted dinos higher; since we also use a x16 BabyMatureSpeedMultiplier i thought that would be kind of required, but thats probably not correct then (but thats out of scope for this bug report i suppose

**Comment by cadon** [comment]
If you want the intervals and gaining per cuddle to be the same, you have to set the cuddleIntervalMultiplier to the inverse of the MatureSpeedMultiplier (i.e. setting the MatureSpeed to x requires to set the cuddleInterval to 1/x, e.g. matureSpeed = 16 => cuddleInterval = 1/16 = 0.0625). If the cuddleInterval is set to a larger number than 1/x, as it is in your case, the interval is longer and you gain more imprinting per cuddle. But at the same time it's harder to hit the 100%.

Back to the issue: AFAIK the cuddleInterval is set for a creature once it hatches / is born, regardless of later changes of the multiplier. So you have to set both the cuddleInterval- and the maturationSpeed-multiplier to the value that were valid when the Argentavis hatched.

**Comment by Dessa** [comment]
> AFAIK the cuddleInterval is set for a creature once it hatches / is born, regardless of later changes of the multiplier.

indeed it was, sorry about the "bug" report then; many thanks for the explanation of the system, though!

**Comment by cadon** [comment]
You're welcome :) Issues are not only for bugs but also for questions, so it's all fine.
