### ISSUE TITLE
Health red tried everything

### ISSUE THREAD

**Issue by vickyb75** [cadon/ARKStatsExtractor#162]
The health stat is red with zero points in it and I have tried everything suggested .

![scorpian](https://cloud.githubusercontent.com/assets/25471018/22492485/fcffc258-e821-11e6-90e4-1e2376ab2f2a.png)

**Comment by cadon** [comment]
Hi,

the good old Scorpion... I guess they will never work. They got nerfed/buffed a year ago, and the game still seems to use the old values sometimes. I'll close this issue by being a duplicate of #16, see there for more infos.
