### ISSUE TITLE
Export to Clipboard -> In plain text , export from breeding tab hypotheticals

### ISSUE THREAD

**Issue by xenocidic** [cadon/ARKStatsExtractor#163]
This would be a nice QOL feature, to be able to send stats to friends/trading partners over steam chat, etc.

It would also be nice to be able to Export to Clipboard when right clicking on "Best possible" offspring (and, I guess, "Worst possible", for consistency) rather than having to copy to Tester, then save as a hypothetical dino before exporting to clipboard.

**Comment by cadon** [comment]
Good idea, it'll be added in the next release.

**Comment by cadon** [comment]
It's released.

**Comment by xenocidic** [comment]
Thanks very much! It seems the export to plaintext has a trailing "0" on the bracketed values though. (370 instead of 37, etc.)

Morellatops (lvl 243): HP: 3360.1 (370); St: 1034 (370); Ox: 660 (340); Fo: 21600 (260); We: 765.6 (370); Dm: 325.8% (340); Sp: 196.4% (370); To: 4889.3 (2420);

**Comment by cadon** [comment]
Yes, that'll be fixed soon, see #165.
