### ISSUE TITLE
Problem adding Pteranodon to library

### ISSUE THREAD

**Issue by CourteousDisruption** [cadon/ARKStatsExtractor#164]
Out of the last batch of pteranodons I bred, I had four that failed. This is one example - I can provide others if it helps to fix it. This is on an unofficial server, 10x maturation rate, otherwise pretty sure relevant settings are vanilla.
![20170130185325_1](https://cloud.githubusercontent.com/assets/25478210/22502602/4d1657ce-e8b9-11e6-8928-d0fa4ea2cea4.jpg)

**Comment by cadon** [comment]
Hi, that works for me. Maybe you changed some other settings? Set them to vanilla-settings by clicking on "Set to official" and all multipliers (except maturation-speed) to 1.

**Comment by CourteousDisruption** [comment]
![image](https://cloud.githubusercontent.com/assets/25478210/22541309/55c739fc-e971-11e6-9aa6-82726fa67bb5.png)
I believe I've done as you suggested, same result I'm afraid. I've attached a pic of the settings screen (after having clicked 'Set to Official', and ensuring the multipliers were as I expected. I forgot to mention previously we have TamingSpeedMultiplier set to 2x also, but that doesn't seem to make any difference.

Any other ideas? This is version 0.20.10.0 of the app.

**Comment by cadon** [comment]
Ah, that was a bug with creatures that had 100% imprinting. That was fixed in later versions (Click on ?-> Check for Updates).

**Comment by CourteousDisruption** [comment]
That sorted it, thanks. I thought I had the latest version but you've obviously just updated it.
