### ISSUE TITLE
Exporting for Plain text issue

### ISSUE THREAD

**Issue by noheals** [cadon/ARKStatsExtractor#165]
When exporting for plain text it concatenates the wild and domesticated points (both for selecting wild and current values) like this:
Carbonemys (lvl 266 Impr: 52%, Male): HP: 17862,2 (**3535**); St: 840 (**320**); Fo: 11588,6 (**250**); We: 518,5 (**370**); Dm: 332,7% (**300**); To: 4492,5 (**2300**);

**Comment by cadon** [comment]
Thanks, will be fixed in the next release.

**Comment by cadon** [comment]
Fix is released.
