### ISSUE TITLE
Problem with new version

### ISSUE THREAD

**Issue by Chita88** [cadon/ARKStatsExtractor#166]
After upgrading to new version I can't write any stats. It doesn't matter if it new or old library.

![nowy obraz mapy bitowej](https://cloud.githubusercontent.com/assets/23618733/22571732/4e25ae92-e9a1-11e6-8836-2c62ac1e5d5c.jpg)

**Comment by cadon** [comment]
Hi, try the newest version 0.20.11.2: https://github.com/cadon/ARKStatsExtractor/releases/latest

**Comment by Chita88** [comment]
It works now. Thank you.
