### ISSUE TITLE
Resize window

### ISSUE THREAD

**Issue by syQ** [cadon/ARKStatsExtractor#167]
Been having issues adding dinos to my library, due to not being able to click the buttons...
When dragging windows size up, it reveals nothing more than before.. Same goes to maximizing

![window_size](https://cloud.githubusercontent.com/assets/894334/22573385/0d389220-e9a9-11e6-95d5-7cd75ab4cf11.png)

**Comment by cadon** [comment]
Hi, I had this issue once the last year, never could it reproduce, though. I suggest to restart the computer. It's probably an issue with .NET.

**Comment by Dessa** [comment]
it helps when you maximize the application directly after starting

**Comment by thalantyrdsl** [comment]
I have this issue also. When adjusting the size of the program it doesn't actually expand the workable area. Let me find a screenshot.

**Comment by cadon** [comment]
Just had the issue myself. But as soon as I restarted the tool it worked again. Does it keep staying for any of you guys or is it just a sporadic issue?

**Comment by Dessa** [comment]
yes restarting works.

i have been able to pin it down further though: it seems to happen every 
time i have red stat boxes after reading values from ark; in other 
cases, its fine.

**Comment by Sorha2** [comment]
Not really my area. But in Form1.extractLevels() could calling SuspendLayout up top then exiting via one of the return false; statements without a ResumeLayout make sads?

**Comment by cadon** [comment]
@Sorha2 you're the man! And I blamed the framework. Thanks a lot for finding and mentioning that! The fix will be in the next release.

**Comment by Sorha2** [comment]
^_^ Hopefully it was just that and works. And thanks for the tool, makes arklife a lot easier :D

**Comment by cadon** [comment]
Fix is released. Thanks again for pointing this out, it seems so obvious now.
