### ISSUE TITLE
Basilosaurus Stats

### ISSUE THREAD

**Issue by thalantyrdsl** [cadon/ARKStatsExtractor#168]
Hi Cad,

I'm having some issues getting the stats for a Basilo to work. I've triple checked them, been over all of your extraction fail directions, added a level, but just can't seem to get it to do the health & torpor. It was tamed with mutton, so not sure if that's affecting things? Please see the below.

![screenshot_2017020501](https://cloud.githubusercontent.com/assets/25558931/22623383/5d65e152-ebad-11e6-9e35-4d32ed94c8ba.PNG)

Regards,
Thalantyr.

**Comment by cadon** [comment]
Hi, are you on an unofficial server with modified multipliers? The torpor value doesn't fit any valid level with the official multipliers. I'll check if the core-values have changed, could be a reason as well.

**Comment by thalantyrdsl** [comment]
May have changed? Definitely the value, but good chance I'm blind.

![screenshot_2017020601](https://cloud.githubusercontent.com/assets/25558931/22630557/6815b020-ec50-11e6-929c-86c7e522d665.PNG)

**Comment by thalantyrdsl** [comment]
It's also an official server. Thank you.

**Comment by thalantyrdsl** [comment]
Hi Cad, any luck with this one bud?

**Comment by cadon** [comment]
Sorry for the late reply. I couldn't find an explanation. Did you try to level up the creature ingame? The numbers seem not possible with the base-values I currently have for the Basilosaur. Probably its values were changed after the release and your fish still has the old ones. Leveling up the creature should trigger a recalculation, which might  making it work.

**Comment by thalantyrdsl** [comment]
Yes, we've leveled the Basi up from 100% movement to 135% movement now. That is all. Nothing changed. You'll be able to see that in the above screenshot. The torpor stayed the same.

**Comment by cadon** [comment]
Hi, finally checked the values ingame, the stats were updated with a patch. Get the current values by clicking on ? -> Check for Updates in the tool. Happy breeding (or at least taming with the Basilo).
