### ISSUE TITLE
Dino ID#

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#169]
Any chance you could have a field for the ID# of the dino and use that for dam/sire?  The game doesn't update the names so if you for some reason change them it makes it hard to figure out who is whats daddy.

**Comment by cadon** [comment]
You mean the sample # that is shown in the imprinting-row on bred creatures? I'll add a field for that. Until then you can use the Notes-field to save that number.

What do you mean with "use that for dam/sire"?

**Comment by Dessa** [comment]
> You mean the sample # that is shown in the imprinting-row on bred creatures?

i think he thinks of the *actual* Dino ID as shown in the Ancestral Line, adding that instead of the sample # as the sample # wouldn't allow him to go "back" in the tree to find the parents

**Comment by cadon** [comment]
Oh, these are different numbers? Haven't checked that out yet. Does the sample# has any meaning then?

**Comment by Dessa** [comment]
right, i just found that the Sample # displayed is the sample # of the imprinter. i didn't know that until now either 😛

**Comment by cadon** [comment]
ah, you mean the sample number is the same as the number of the arm implant? does that also mean, the imprinting-bonus (+30% damage and health) when riding the imprinted creatures isn't working after you respawn?

**Comment by Dessa** [comment]
no, i don't think the number ever changes, maybe when you actually create a new character? i never tried that.

**Comment by Worldgate** [comment]
If you look at the dino ancestry it shows a huge long number.  Not sure how to extract it, maybe a second button that you click when in that menu.  I've ben using the notes to keep track for now cause we have dinos that got renamed and i have to recheck them when i add their geneology.

**Comment by JuicyJuuce** [comment]
@cadon Just came here to suggest this same idea and found this issue.

It would be a huge help to have a field with the ID as well as a "Read Ancestry from ARK Window" button on the "Extractor" tab that you press after selecting the dino's ancestry screen that will automatically scan in this dino's ID as well as the parents' IDs and fill in the "Mother" and "Father" fields.
