### ISSUE TITLE
Bug with top stats

### ISSUE THREAD

**Issue by LeylaArk** [cadon/ARKStatsExtractor#17]
![2016-04-01 3](https://cloud.githubusercontent.com/assets/18007828/14217802/7c1b60d2-f850-11e5-9c00-cb7dae3206b2.png)

I got this problem. I mean I am not sure what "Top" column means. But I guess it means the amount of stats where this dino is top.

So what is wrong with "Shisha's Jet" in my list here? It doesn't have 4 Top Stats.

Is that a bug?
Or do I understand something wrong?

**Comment by cadon** [comment]
Ah ja, danke. Hatte das wegen des Breding-Planers verändert. Wird in der nächsten Version gefixt. Zur Zeit berücksichtigt das Tool alle Stats bei der Zählung, bei Shisha's Jet also St, Fo, Sp und To, sollte aber natürlich nur die gewünschten zählen.

**Comment by LeylaArk** [comment]
Oh, Deutsch? Das macht es ja einfacher :D 
Also werden aktuell alle Top-Stats angezeigt und in der neuen Version dann nur die eigentlich gewählten relevanten Top-Stats. Okay, sehr gut. Danke schön.
