### ISSUE TITLE
Unable to eneter stats for extraction under mono since 0.20.11

### ISSUE THREAD

**Issue by TheFeshy** [cadon/ARKStatsExtractor#171]
I run ARKStatsExtractor under mono, on linux.  0.20.10 is the last version I have been able to use, as starting in 0.20.11 the boxes to enter stats on the extractor tab (such as health, oxygen, etc.) have been grayed out.  Other controls on that form work, such as gender, the spay selector, etc.

**Comment by cadon** [comment]
Hi, I'll look into it. Can you try to change the species? That probably re-enables the stat-inputs.

**Comment by TheFeshy** [comment]
Sorry, that was the first thing I tried.  I should have mentioned that in the bug report.  Changing to different species does update the tab (for instance, changing to a non-breedable species removes the breed timer info) but does not enable the input boxes.

**Comment by cadon** [comment]
Hi, can you test it with the newest version? There was a rare occuring bug, that could have caused that.

**Comment by TheFeshy** [comment]
I seem able to enter stats normally now, thanks!
