### ISSUE TITLE
Suggestion Cooldown tab in library.

### ISSUE THREAD

**Issue by Pyr088** [cadon/ARKStatsExtractor#172]
When adding a cooldown on a dino in the library can we get a column showing it?

Also small bug but the Tuso taming calculator time is a bit off.

**Comment by cadon** [comment]
Hi, good idea, I'll add the cooldown-column.

Just checked the Tusotheutis, I guess the stack-taming screws up the calculations. Thanks for pointing it out!

**Comment by Pyr088** [comment]
Thanks so much. I can't imagine playing this game without your tool!!!!!

**Comment by noheals** [comment]
If you are at it already a Grown Tab would be usefull too i think.

**Comment by cadon** [comment]
You mean a tab that shows which dinos are currently growing and when they are finished?

**Comment by noheals** [comment]
yep

**Comment by noheals** [comment]
Only working for Cooldown field right now. Growing Creatures have nothing in the tab.

**Comment by cadon** [comment]
Forgot that, growing-time will be added for that column in the next release.

**Comment by Gamerscd** [comment]
+1
Also can we get the ability on the breeding plan tab to see the plan with both showing cooldown dinos and hide them

**Comment by cadon** [comment]
new version with raising-tab is released.
