### ISSUE TITLE
Melee Damage is always too low

### ISSUE THREAD

**Issue by MishaZoltan** [cadon/ARKStatsExtractor#173]
The Stats come out right but the melee is always to low

**Comment by Pyr088** [comment]
I would say check your settings. I have used this tool on many different server settings and its always correct. If you can get the game.ini and the gameusersettings.ini file from your server owner or singleplayer then drag those to the settings window it will set all the settings do what they are for that server.

**Comment by MishaZoltan** [comment]
Its an official server, i havent changed any settings.?

**Comment by Pyr088** [comment]
Go into the settings file and click official. See if that helps.

**Comment by MishaZoltan** [comment]
Still wrong, i have a chalico i just tested, its dmg is 296.2%, with no levels into it. The tool is correct on all values other than dmg, where it says there are 30 points in it, where it should be 39.

**Comment by cadon** [comment]
Hi, do you mean the tool shows a correctly extracted level for damage (color is green or yellow), but you think the level-number is too low? Maybe you're just expecting too much ;)

**Comment by MishaZoltan** [comment]
yes it extracted a number, the tool is green, and i am fairly certain the number is to low given that all the other calculators i can find give the higher number for melee and equal for everything else?

**Comment by cadon** [comment]
It's because all the other calculators you tested are probably wrong as soon as you test them with a tamed creature. They should and probably have a small note that says the calculator is only for wild-creatures.

**Comment by MishaZoltan** [comment]
so the other calculators overestimate the bonus melee damage from tame bonus levels. Makes sense, Thank You.

**Comment by cadon** [comment]
Not the tame bonus-levels, but the taming-bonus. Melee damage and sometimes food get's an extra increase once the creature is tamed. All the other stats are mostly fine, and the small taming-bonus of e.g. health is rounded to the correct level. But melee gets a bigger bonus that is in the scale of a couple of wild-levels.
