### ISSUE TITLE
Level points not matching Stat values

### ISSUE THREAD

**Issue by Duffamongus** [cadon/ARKStatsExtractor#174]
I've tamed a couple creatures tonight, and each has had some stats that are not extracting the correct point value. The biggest problem one is a Megaloceros. It has a melee of 337.4, and is extracting 36 points. It should actually be 47 I believe. If there is something that I'm missing, I don't know what it is. I've tried tweaking it like crazy, but I'm out of ideas.
![arksmartbreeding](https://cloud.githubusercontent.com/assets/25656037/22772008/6644b800-ee57-11e6-9db7-b63b968ee262.jpg)

**Comment by cadon** [comment]
Dododex is not made to extract the levels of tamed-creatures.
![re](https://cloud.githubusercontent.com/assets/8763269/22791445/ad0f2ca6-eee9-11e6-827d-e71404e0d7df.png)

The 36 is already a very good stat for this level, 47 is pretty unrealistic (not impossible, to be exact, the chance of getting a stat with 47 levels for that creature is a bit less than 1 : 14000).

**Comment by Duffamongus** [comment]
You are quite right. I'm sorry for misunderstanding that. Looks great. Thanks.
