### ISSUE TITLE
Make Timers Sort by Time Left

### ISSUE THREAD

**Issue by noheals** [cadon/ARKStatsExtractor#176]
I think it wouold be nice if you could make Timers sortable by "Time Left" or "Finished at" or make it so that if you add a new timer it gets sorted automatically by time left.

**Comment by cadon** [comment]
I'll add the sorting. If you add a new timer, it should be already added according to the time left.

**Comment by noheals** [comment]
No sometimes it doesnt. Otherwise i wouldnt have noticed that they are not sorted by time left i think.

**Comment by cadon** [comment]
issue resolved in v0.21.2
