### ISSUE TITLE
Mu not remembered upon Editing

### ISSUE THREAD

**Issue by Bobnine** [cadon/ARKStatsExtractor#178]
When editing a dinosaur that has a non-zero mutation count, the counter field in the edit window defaults to 0.  The screenshots below are from 0.21.1, but the problem was first observed in 0.21.0.

As seen in Library Prior to editing:
![library](https://cloud.githubusercontent.com/assets/25716244/22859584/3e44f8c0-f095-11e6-9228-d55ff9e03f74.PNG)
The Stat Testing window where edits would be made.  Note the Mu field:
![stat testing](https://cloud.githubusercontent.com/assets/25716244/22859591/801ead22-f095-11e6-8c39-9698d4bc135e.PNG)
After saving changes (and not modifying the Mu field), The library shows the Mu as zero.
![library2](https://cloud.githubusercontent.com/assets/25716244/22859600/db8b0638-f095-11e6-9954-6f1b69812e6b.PNG)

I tried an initial value of 10 Mu on the same dinosaur, as well as a value of 10 on a different species of dinosaur.  I also tried in a new library with default settings on a third species of dinosaur.  All of these resulted in the same outcome.

**Comment by cadon** [comment]
Hi, thanks for the report, I'll fix that in the next release.

**Comment by cadon** [comment]
issue resolved in v0.21.2
