### ISSUE TITLE
Simple improvement of taming tab

### ISSUE THREAD

**Issue by ShidMD** [cadon/ARKStatsExtractor#179]
It would be awesome to get the following features in the taming tab, this way i woudnt need any other place to look up for them:
Starve section: Food decrease needed and autocreation starve timer (given current food and a configurable time gap)
Knockout: ideal timing torpor infliction with various weaps, to have a rough idea
and timer to feed narcotics/bio/nberri too.
If need help i coud grab a few hours to make a pull, im rusty in c# thoug 😄
or simply look up for rates or info needed.
Just make a brand new gihub for this :'D cya gl

**Comment by cadon** [comment]
Hi, a new version with improved taming-info is released. I'm leaving this issue open, as the timer is only settable once, could still be improved.

**Comment by cadon** [comment]
Taming-timers are included.
