### ISSUE TITLE
Multipliers

### ISSUE THREAD

**Issue by CrepemyrtleSL** [cadon/ARKStatsExtractor#18]
I am having trouble matching the stats when I tame my dinos.  I am currently using the new version and the stats from wild to tame are not matching.  I am the server admin and I just don't know which multipliers I should be looking at to adjust my setting.  The server we have has 3x taming, 3x hatch, and 5x mature.  Thank you.

**Comment by cadon** [comment]
Hi, if you haven't changed the stat-multipliers (PerLevelStatsMultiplier_DinoTamed[0] etc.) , you don't have to adjust them in the tool. If you changed them, set them in the settings of the tool.
