### ISSUE TITLE
Baryonyx: Breeding for max. Level

### ISSUE THREAD

**Issue by milaan-muc** [cadon/ARKStatsExtractor#181]
Hi!

Would love to breed my Baryonyxes for max. Level with your Tool but its somewhat hard to take Oyxgen and Speed into account since you cannot enter an Oxygen value.

If i use the Mod "Super Spyglass" on a Baryonyx i can see that the game is actually giving them for example 990 Oxygen which is of course not shown normally. For max level breeding it would be important to enter those levels into your tool.

![2017-02-15 2](https://cloud.githubusercontent.com/assets/3469112/22993856/ce6cf25e-f3c4-11e6-8afb-b5024f21c195.png)

**Comment by milaan-muc** [comment]
Oh its actually not only important if you go for max level. If you just look what level your tool predicts when mating two Baryonyxes, this might be off from the level the offspring actually is.

Of course all that stuff is also true for other dino's which have Oxygen hidden.

**Comment by cadon** [comment]
Hi, that's a thing I mostly ignored by now, but it'll be definitely an issue once the marine species will become breedable as well.

I'll try to get the oxygen-values for the non-oxygen species and add an option so they can be entered as well.

Regarding the max-level in the breeding-planner, there should be a small +sign that indicates it's probably more than the displayed level.

The mod looks nice, btw, thanks for bringing it to my attention.

**Comment by milaan-muc** [comment]
Yeah but you cant really tell if this dino or the other has more oxygen or speed. If only speed is hidden, its no problem but as soon as you have two hidden stats it makes it hard to predict the needed level for the offspring.

**Comment by milaan-muc** [comment]
Hey, i saw that you unlocked oxygen in the current release. Any eta when you add the value of Oxygen?

**Comment by cadon** [comment]
probably today (in the next 8h).

**Comment by milaan-muc** [comment]
Awesome. Thank you :-)
