### ISSUE TITLE
Breeding Plan not considering all dinos in library

### ISSUE THREAD

**Issue by Darwolia** [cadon/ARKStatsExtractor#183]
When using the breeding plan feature it won't consider all dinos in the library, this problem occurs across all species. Rightclick in the library -> Best Breeding partners won't work aswell.
![bug1](https://cloud.githubusercontent.com/assets/24816639/23023918/1bb4380e-f458-11e6-874d-0fe20dc7e2e4.png)
![bug2](https://cloud.githubusercontent.com/assets/24816639/23023921/1f175ecc-f458-11e6-948e-e6c89982a95d.png)
![bug3](https://cloud.githubusercontent.com/assets/24816639/23023922/208782aa-f458-11e6-8fd9-549d6a7ed703.png)

**Comment by Nova900** [comment]
I can confirm this. Maybe I just did overlook some setting or don't know about a property which makes breeding that dinos impossible for the planner.

**Comment by neimi23** [comment]
Have you checkt the field with current weight?
If there is a number which isn't the max. weight the animal can't breed ;)

**Comment by Dessa** [comment]
it usually happens with newly added dinos, so restarting the app should fix this.

**Comment by cadon** [comment]
Hi, couldn't reproduce this yet. Did restarting help? If not, can you send me the library-file that has the issue?

**Comment by Darwolia** [comment]
No, restarting does not help. But sometimes some of the missing dinos will start to show up.
I'll test the current weight tomorrow, as that might be a clue since most of the dinos I add are bred (adding them right after hatching). But the ones I tame sometimes won't show up untill they do few days later.
[Here is the library file](https://github.com/cadon/ARKStatsExtractor/files/781814/library.zip)

**Comment by Nova900** [comment]
Restarting the program didn't help.

@neimi23: That was the solution, thank you. :)
I don't know why the current weight was set to 0, but changing that has fixed this.

**Comment by Darwolia** [comment]
I can confirm aswell that changing the current weight to the max. weight solves this issue!
Thanks everyone.

**Comment by cadon** [comment]
I'll look into it, maybe there's still a bug. Still growing dinos are ignored in the general breeding plan, because they cannot be bred yet, but right-clicking - best partners should show a list regardless.

**Comment by Nova900** [comment]
Well, that is a reasonable feature, cadon. Maybe a small note that this dino can't breed would be good.

**Comment by Theladybug10** [comment]
Having  this same problem I have reset the program and changed current weight and its still not working...what do I do?
![image](https://cloud.githubusercontent.com/assets/25977045/23252377/7b0b18ce-f965-11e6-92b2-d95bfc14674b.png)
![image](https://cloud.githubusercontent.com/assets/25977045/23252417/9ecc1af6-f965-11e6-8c19-c8ee0c38cc78.png)
![image](https://cloud.githubusercontent.com/assets/25977045/23252461/bb9710f0-f965-11e6-82ec-e0181303ab43.png)

**Comment by neimi23** [comment]
Your Lucky and Rain on Fire aren't grown. If you look right the last collum is purple, the date inside is the moment when your animals are able to breed.
Change the current weight to max. and both animals will be shown in the breeding plan :)

**Comment by Theladybug10** [comment]
oh they are full grown otherwise I wouldn't be able  to ride them

**Comment by cadon** [comment]
Then tell the tool they're adults by changing the growing-timer to 0.

**Comment by cadon** [comment]
Option to include creatures on cooldown is included.
