### ISSUE TITLE
Torpor always red

### ISSUE THREAD

**Issue by markuswhiteus** [cadon/ARKStatsExtractor#184]
Hi just got this to use with a private xbox server, I have edited the values to match that of the servers however whenever I try and calculate torpor is always shown as red.
![arksettings](https://cloud.githubusercontent.com/assets/16180510/23036578/40ef64d6-f47b-11e6-9d52-103d3cdfef7b.png)

![arkbreeder](https://cloud.githubusercontent.com/assets/16180510/23036581/4106c068-f47b-11e6-9238-a32ede63754b.png)

![img_20170216_190037](https://cloud.githubusercontent.com/assets/16180510/23036599/58ade7dc-f47b-11e6-93da-9e3b005c8e40.jpg)

**Comment by cadon** [comment]
Hi, were the multipliers changed since the direbear was tamed?

**Comment by markuswhiteus** [comment]
No no server settings have been altered


On 16 Feb 2017 8:23 pm, cadon <notifications@github.com> wrote:

Hi, were the multipliers changed since the direbear was tamed?

**Comment by cadon** [comment]
Sorry for the late reply. Did it work in the meantime? If not, can you post the stat-multipliers you're using?

**Comment by cadon** [comment]
I hope it's resolved by now, if not or if you got another question, just reopen this issue.
