### ISSUE TITLE
Argentavis not reading from Extractors.

### ISSUE THREAD

**Issue by bensen19br** [cadon/ARKStatsExtractor#185]
It's not working for my Argentavis. I'll post screenshots below. 

https://gyazo.com/34bac5bde991eeb9e9877566fc23062d

**Comment by cadon** [comment]
Hi, it's the issue with ARK that is described in the red box. Wait for a server restart and try again. Most stats have only received a 12× cuddle-bonus yet, only HP has the 100% imprinting bonus.

**Comment by Dessa** [comment]
btw for my server i have observed that relogging in ark works too (or even getting the pet into stasis and then out of it again, but im not 100% sure on *that*)
