### ISSUE TITLE
Breeding Score calculation

### ISSUE THREAD

**Issue by Nova900** [cadon/ARKStatsExtractor#186]
I'm confused. How is the breeding score calculated?
I have one female rex and two male. Both males are nearly identical - except for one stat. The breeding planner now gives me two possible pairings as "top possibilities", but the male with the better stats is the second place, while the male with the slightly less good stats is the first place. o_O
Why exactly is that? Does the breeding planner take parents into account? (The "better" rex, Churchill, has the lesser one (Julius) as father.) if that is the answer, why does the breedings planner do that? As far as I know there are no negative consequences of inbreeding in ARK.

![image](https://cloud.githubusercontent.com/assets/15316424/23052791/6753fc50-f4d4-11e6-8eac-6bdec3be8628.png)

**Comment by cadon** [comment]
It's complex, and that is definitely a bad recommendation of the planner. I'll look into it. Thanks for reporting that!

**Comment by cadon** [comment]
The algorithm is changed, I hope it gives better recommendations now in the conservative-mode. I'll leave this open for a while in case it does not yet.
