### ISSUE TITLE
Breeding Planer getting slower over time

### ISSUE THREAD

**Issue by noheals** [cadon/ARKStatsExtractor#187]
When using the program for a longer time the program and the Breeding Planer especially get slow. Switching tabs is sluggish and drawing Dinopairs in the Breeding planer is delayed.
Restarting the program makes it fast again.

**Comment by cadon** [comment]
Hi, thanks for noticing and reporting that. There was a memory-leak in the breeding-planner. It'll be fixed in the next release.

**Comment by cadon** [comment]
The memory leak is fixed, additionally the overall performance of the breeding-planner should be better now.
