### ISSUE TITLE
Can't imput the proper imprinting values in the extractor.

### ISSUE THREAD

**Issue by smop95** [cadon/ARKStatsExtractor#188]
As the title says, the extractor is rejecting the proper imprint values. My trike has a 97% imprint, but when I enter this in, or have the extractor read from the window, it changes it to 95% or 100%. It seems to work fine with dinos that have a 100% imprint, but it doesn't seem to like anything else.

**Comment by cadon** [comment]
Hi, that means you have not set the correct values for `BabyMatureSpeedMultiplier` or `BabyCuddleIntervalMultiplier` in the settings.

The values have to be the values that were valid on the server when the dino hatched, which may be different values than the current ones.

**Comment by smop95** [comment]
I already have my settings matched, as far as I know. Maybe I'm not understanding the numbers?
![extractor settings](https://cloud.githubusercontent.com/assets/25868568/23104767/fcf301c4-f688-11e6-89f4-1e851f534804.png)
![game settings](https://cloud.githubusercontent.com/assets/25868568/23104768/ff05b2c2-f688-11e6-9891-809bc7302bbc.png)

**Comment by cadon** [comment]
Hi, were the values changed since the baby hatched? It also could be that the imprintingquality lost some progress due to the BabyCuddleLoseImrintQualitySpeedMultiplier. Can't you set this to 0 if you want to disable that?

**Comment by smop95** [comment]
Now that I think about it, I believe I did change the mature speed and egg incubation values since I hatched it. And I was not aware that I could simply set the value to zero to disable it, so thanks for letting me know. I'll test changing the settings to the values that I think I had when the trike was hatched.
