### ISSUE TITLE
Unable to extract any data!

### ISSUE THREAD

**Issue by eeqw** [cadon/ARKStatsExtractor#189]
hi i donwloaded this program when i had windows 7 and it didnt extract anything so i went to Fullscreen mode > nothing > window mode > nothing > reformatted pc > windows 10 pro  > same thing happens !

i cannot get it to work!!

**Comment by cadon** [comment]
Hi, do you mean the reading-feature does not work, or the typed in numbers don't lead to a valid level-extraction? The OCR does only work with a resolution of 1920x1080, and not so well in 1680x1050. Other resolutions are not supported. Also see #96.

**Comment by eeqw** [comment]
ive watched many videos on smart breed app > i download then unpack it start it up have windows on 1920-1080 and ark in 1920 1080 windowmode fullscreen go to inventory of PT then go to the smart breed fill in the pter and click on tamed and extract it goes in ark then out ark to the page
and get only to see 0 0 0 0 0 0 on each stat when i tried the ocr it shows the picture of inventory > and stats but same again Extracting it does not work at all i realy want to get this app working but its not working for me :S

**Comment by cadon** [comment]
The OCR is just a small helper that reduces the need to type all the numbers manually. The tool totally works without that if you type in the numbers.

The OCR is known to not work when used with multiple monitors, I haven't found a good solution for that yet. If you don't have multiple monitors, could you post a fullscreen-screenshot (in 1920x1080) here of an inventory of a dino?

**Comment by cadon** [comment]
Did you try the windowmode "Fullscreen-Windowed" yet?

**Comment by eeqw** [comment]
yes in windows 10 1920:1080 and ingame > tried windowed mode > and fullscreen windowed mode manual works fine just the screen capture is not working the ocr sees the screen but doesnt extract the data out of it

**Comment by eeqw** [comment]
how do i make a screenshot in this site ?

**Comment by cadon** [comment]
Hi, sorry for the late reply. Did it work in the meantime? To post a screenshot you can just drag'n'drop them in the area where you're writing a reply.

**Comment by eeqw** [comment]
its ok ill just do everything manual :> to much hassle trying to fix this

2017-03-26 13:55 GMT+02:00 cadon <notifications@github.com>:

**Comment by cadon** [comment]
I hope it has worked out somehow in the meantime. If you've more questions, just reopen this issue.
