### ISSUE TITLE
Finding the stat-multipliers of a server

### ISSUE THREAD

**Issue by anthonydebrincat** [cadon/ARKStatsExtractor#190]
Hi Cadon love your work.

Is it possible to calculate the server multipliers to make this work? I'm currently on Nerd Parade Servers and they seem really reluctant to provide this information. Is it worth the effort to figure this out do you have any resources to calc this. 

Could this even potentially be a feature later on?

I love this application just trying to get it to work properly on Nerd Parade normally use it on official but so tedious breeding and constantly getting wiped.

Thanks

**Comment by cadon** [comment]
Hi, this involves some trial and error and isn't always garantueed to give you the correct numbers, mainly because of the game does only display rounded numbers, but it's possible. I wrote a short guide here: https://github.com/cadon/ARKStatsExtractor/wiki/How-to-find-out-the-stat-multipliers.

**Comment by cadon** [comment]
In 0.27.2 a stat-multiplier-testing was added, which can be enabled in the settings - general - dev-tools. It allows in an easy way to change all relevant settings to find the correct ones. You also can calculate multipliers dependant on the other multipliers. It's not fully automatic, but makes the process much easier.
