### ISSUE TITLE
Oxygen and aquatics

### ISSUE THREAD

**Issue by smop95** [cadon/ARKStatsExtractor#191]
Just so you know, the extractor appears to be broken with dinos that have no oxygen stat. I've been unable to use the extractor for my Icthy because of this. The extractor always sets Oxygen to zero, rather than disregarding it, so that stat is always red.

**Comment by cadon** [comment]
Hi, do you have enabled the checkbox in the settings at the bottom-right that says "Enable Oxygen for all Species"? If yes, uncheck it.

**Comment by fragzem** [comment]
I am trying this with a megalodon and the oxygen stat is red. I have unchecked the box that said Enable Oxygen for All.    Nothing changed. I've also noticed problems entering the whale into the ARK Smart Breeding program.  None of this is terribly important... but thought I'd post.
