### ISSUE TITLE
Thylacoleo weight stats consistently low or red

### ISSUE THREAD

**Issue by Rocketowl** [cadon/ARKStatsExtractor#195]
After doing some testing on my personal server I've noticed that every thylacoleo I input had either 'very low' weight stats, according to the smart breeder, or the weight stat is straight up red and they cannot be added to the library at all.

I've tested this on eight different thylacoleo, double checked all the stat inputs. Three of them still came up red in the weight stat despite troubleshooting each time, and those that didn't were all consistently well below average. Is this a problem with the smart breeder's library for them? They're still pretty new...

**Comment by cadon** [comment]
Hi, the data I currently have says 400 base-weight, 2% increase per wildlevel and 4% increase per domesticated level. Do you maybe have changed the multipliers on your server?

**Comment by Rocketowl** [comment]
I have the multipliers changed, but I also input the changes into the server settings of the calculator.

**Comment by cadon** [comment]
Hi, I just tested some Thylacoleos with the default settings, the values seem to be correct. I've no other idea that the multipliers on your server might be different from the one in the tool.

**Comment by Rocketowl** [comment]
Hm. I'll do some more testing on my end. If I find the problem I'll let you know.
