### ISSUE TITLE
ark stats extractor doesnt work

### ISSUE THREAD

**Issue by CaileanH** [cadon/ARKStatsExtractor#196]
ive downloaded the latest version and when i want to extract stats form my game , its says "extraction failed". I checked all the common causes already but it just doesnt work.
This is what i get if i extract it: https://gyazo.com/d443ec8da0071894f4807f152a1cfbe5

**Comment by cadon** [comment]
You forgot to type in the total level and some of the stat-values.

**Comment by CaileanH** [comment]
in a youtube video i saw a guy that didnt put te stat values in but the program extracted it itself ?

**Comment by cadon** [comment]
The tool needs all of the stats the creature uses. The only exceptions currently are creatures that don't show an oxygen stat.

It could be, the guy used the "Quick Wild-Creature Check" (there's a checkbox on the top right), that can be used to check the stats on wild(!) creatures. This feature can produce wrong numbers if a creature is tamed.

**Comment by CaileanH** [comment]
it still doesnt work i just typed in all the stats , the base level and i pressed "bred" and nothing happens : https://gyazo.com/2fbc01382b361744d3957d07e27f911c 
their are some boxes that become red i checked everything but it doesnt work.

**Comment by cadon** [comment]
What do you mean with "i just typed in all the stats"? The only stat with a reasonable number I see is Oxygen. All the other stats have a 0 or a 1, also the total level is 0, which is not possible. You have to type in the number for all stats and the total level.

Have a look at some of the video-guides that exist: https://youtu.be/zOYvKhLAHL4?t=10m58s or https://youtu.be/KOpXpU-mcP0?t=46s

**Comment by CaileanH** [comment]
Alright i will look at it thnx man , but i have trouble with the settings, my server has a 10x multiplier on everything but i dont know how to get the settings right. Because thats an important thing i guess

**Comment by cadon** [comment]
Hi, mostly "10x on everything" only means XP, Taming, Harvesting and sometimes Breeding-Times. The stats are often separately. If the extraction fails with the default-multipliers it's best to ask the server-admin to give you the stat-multipliers.

**Comment by CaileanH** [comment]
sorry man i maybe sound stupid but i don't understand what i have to fill in in the settings menu , the owner told me the weight and health are 2x so help me plz : https://gyazo.com/04f60f9bfe4271003317702d628ba468

**Comment by cadon** [comment]
Hi, that was not very precise of the server-admin, to be honest. Most probable it's the values in the last rows (in the rows health and weight respectively). If that does not work, try the WildLevel column.

**Comment by CaileanH** [comment]
Thnx man , im very sorry that im taking your time with my stupid questions but is the settings thing neccesary ? Because even if i fill the stats in manually , it doesnt work.

**Comment by cadon** [comment]
Yes, all the values change drastically if the multipliers are changed. The multipliers have to be exactly as they are on the server, or all the extractions will not work or produce wrong numbers.

Maybe you can tell the server-owner you need the settings for this tool, so they can give you more specifically what you need.

**Comment by CaileanH** [comment]
i have everything right now he says and i still get this : https://gyazo.com/fae5513116c5924c7492de1c70b3a71c

**Comment by cadon** [comment]
Does it work with non-imprinted creatures? The imprinting does not update all stats at once, sometimes some are behind a bit and only show the correct value (see also the red notice at the bottom).

**Comment by CaileanH** [comment]
this is what i get when i try it with non bred creatures https://gyazo.com/33d5de6587c41430ebbe5bc874bff92a

**Comment by cadon** [comment]
Then there's still a multiplier not set correctly. Can you try it with a wild one (knocking it unconcious and access the inventory)? If it works there, the wildLevel multipliers are probably correct. Then try it on a freshly tamed one, with no domesticated levels (that makes sure the tameAdd and tameAff multipliers are correct).

**Comment by cadon** [comment]
I hope it's resolved by now and I'm closing this. If you have more questions, just reopen this issue.
