### ISSUE TITLE
OCR stats extraction with images

### ISSUE THREAD

**Issue by mle-ii** [cadon/ARKStatsExtractor#197]
Was thinking a cool feature would be to be able to extract stats from images.  The reason for this is that I play on the Xbox and so there's no way for the app to interact with my console.  But I normally do screen captures after I tame and around breeding so it might be possible to extract the stats from those images.  So you could either have it point to a window and capture from that or perhaps have an image upload ability for the pngs that you can download from the xbox live page.  Perhaps PS4 has something similar though I'm not very familiar with it.

If I get a chance I'll take a look at the code to see if I can create a PR, though I'm guessing you know your code a bit better.  :)

**Comment by cadon** [comment]
Hi, if you have a screenshot with the supported resolution of 1920x1080 or 1680x1050, you can drag&drop it onto the violet area in the OCR-tab to read the values from that (it also works directly from a browser). I guess it also would be nice to have a dropable area in the extractor-tab, I'll add that.

**Comment by mle-ii** [comment]
Thanks, looks like I might have to figure something different out or figure out how to get the images in a higher resolution.  Xbox doesn't quite have the same resolutions as a PC does, at least for Ark.  Images from Xbox live are around 1138 x 640 as I think Ark is sub 720p on Xbox One.

**Comment by GhostlyCrowd** [comment]
Xbox screenshots are always 1920x1080

Also the game streaming app for box renders in this resolution in full screen.

**Comment by mle-ii** [comment]
@GhostlyCrowd Weird, can you point me to one that's 1920x1080 for Ark?  When I try to get a copy of one they were at that resolution I mentioned earlier.  I'll look again as perhaps I copied the wrong image down from xbox live.

**Comment by GhostlyCrowd** [comment]
Thanks for looking into it. Right Now i have been working around the OCR limitations by naming vlc.exe to ShooterGame.exe and opening my Screenshots in that as a slide show.  It works.

I hope that some day the Xbox app for game streaming would be included in the code for screen OCR that would be convenient.  :)

**Comment by cadon** [comment]
New version with selection of the app used for OCR is released. Also images with the supported resolutions can be dropped on the extractor-tab.

**Comment by cadon** [comment]
see also #227
