### ISSUE TITLE
Change in stats after wipe 

### ISSUE THREAD

**Issue by oxygen2202** [cadon/ARKStatsExtractor#198]
Hi, 

There was a server wipe and all the stats of dinos were reset so i set the app in multiplier options to official and everything was great.

The admin decided later to then buff the tamed dinos to 1.5 apart from weight which was set to 2. What should i change the multiplier settings to? as some are different, e.g. (HP 0.14, 0.44 , 1.00, 0.20.)

And will i have to re add all the dinos i added to the library prior to the change in stats? 

On a side note another issue i have is that bred dinos just wont extract data even if i put the values in manually, i add some images to this issue i have had. 
![ss 2017-03-05 at 10 47 24](https://cloud.githubusercontent.com/assets/26198740/23586709/af950a5c-0192-11e7-86a4-11b571eaea2a.png)
![ss 2017-03-05 at 10 48 04](https://cloud.githubusercontent.com/assets/26198740/23586710/af9677d4-0192-11e7-808f-8515d3485beb.png)
![ss 2017-03-05 at 10 48 26](https://cloud.githubusercontent.com/assets/26198740/23586711/af9690e8-0192-11e7-9afe-286586a7ca8f.png)

**Comment by cadon** [comment]
Hi, if the tamed dinos were buffed, it sounds like the column "TameLevel" is the one you have to adjust in the settings of the tool.

The tool saves the stat-levels, the stat-values are always calculated, so you can just adjust the multipliers in the settings and all stat-values of the creatures should adjust themselves. No readding is needed.

If the extraction fails, it's mostly one of the multipliers that is not yet set correctly. Maybe it's the BabyImprintingStatScaleMultiplier (which influences how much bonus is given by imprinting).
