### ISSUE TITLE
Extracted Impriting level wrong

### ISSUE THREAD

**Issue by SCMass** [cadon/ARKStatsExtractor#199]
Hi,

first of all thank you for this wonderful tool. 
I have been trouble with some of my bred creatures. It seems to extract the wrong Imprinting value for my bred dinos. I can't change it manually. The server has been restartet a few times. Is there anything I can do?

![imprint](https://cloud.githubusercontent.com/assets/21180120/23588415/97b40548-01bd-11e7-92f0-b4e744de93cc.jpg)

**Comment by Dessa** [comment]
please see https://github.com/cadon/ARKStatsExtractor/issues/159#issuecomment-275948566 on why that can happen.

**Comment by SCMass** [comment]
Hi,

thanks for the quick answer!
I checked that out already though. We did change the maturation speed, but never the BabyCuddleIntervalMultiplier. I played around with the Maturation speed settings (we had different ones for different dinos), but it never worked out. Is there anything else influencing that extracted value?

**Comment by cadon** [comment]
Hi, the possible imprinting-percentages are dependant on the BabyCuddleIntervalMultiplier and the BabyMatureSpeedMultiplier. The tool always changes the input imprinting-percentag to the closest possible number. If that's not the one you can see in the game, it means at least one of the beforementioned multipliers is not set correctly. It seems the correct number is the one that was set on the server when the creature hatched / was born, even if the multiplier on the server was changed later.

**Comment by SCMass** [comment]
Thank you! Then I'll look more into the MatureSpeed Multiplier. Again, thank you for the fast answer.
