### ISSUE TITLE
Suggestion: Remember Library sort order

### ISSUE THREAD

**Issue by Jagged** [cadon/ARKStatsExtractor#20]
Every time I start ASB I have to resort the dino's, which in my case is by Top%, but I'm sure others will have their own preferences.  Any chance ASB could remember the sort order?

ps Thanks for a great tool, you saved me from manually doing this in Excel!!!

**Comment by cadon** [comment]
Hi, that's a good idea, I'll add it.

**Comment by cadon** [comment]
Feature added.

**Comment by Jagged** [comment]
Do I need to say it again? Thanks!! =)
