### ISSUE TITLE
Is Pteranodon base damage % wrong in the tool? 

### ISSUE THREAD

**Issue by orangepinkman** [cadon/ARKStatsExtractor#201]
Ok so the issue is, playing on official, tamed a few new 150 pteras out at 223 with current 1.5x. Dododex app shows 48 points into melee(340%) but this tool shows 36 points into melee(340%).... Everywhere I have looked it shows lvl 1 ptera base damage as 100% but the tool has it much higher. This is causing on issue with the speed stat as those extra 12 points are saying they are wasted on speed. 

Which of these base % is correct?

**Comment by cadon** [comment]
Most other stat-calculators are only for wild-creatures and show false-high values especially for damage.
