### ISSUE TITLE
Import Error from Game.ini and GameUserSettings.ini

### ISSUE THREAD

**Issue by Ancharakh** [cadon/ARKStatsExtractor#202]
I have a problem with importing the multiplier from the Game.ini and GameUserSettings.ini. When using the method to drag & drop the files to set the values, these values are multiplied by 10 for some reason, and i wonder if this behavior is correct?

I've leased a server from Nitrado and as far as i know its a windowsServer (according to the folder-tree in my ftp). I tried to download the files and use them for configuring. But with drag & drop, for example,, my (normally 3) taming mulitplier will be set to 30. This also happens for all the other values. Ill append the files in question to this issue (cleaned some of my server-settings, but nothing that should influence this). I am using version 0.21.4

Edit: Had to rename them to ".txt" for GitHub, so you have to change it back to ".ini" :)

[Game.txt](https://github.com/cadon/ARKStatsExtractor/files/819715/Game.txt)
[GameUserSettings.txt](https://github.com/cadon/ARKStatsExtractor/files/819716/GameUserSettings.txt)

**Comment by Ancharakh** [comment]
I gues there is a problem with punctuation. As far as i see the program uses ",", but in the ini-file its "."?

**Comment by Ancharakh** [comment]
After taking a look at the source, i might have found the problem. It seems like a problem with "double.TryParse()" starting at https://github.com/cadon/ARKStatsExtractor/blob/master/ARKBreedingStats/Settings.cs#L179. According to the documentation it takes the localization settings at runtime into account, which dont work for any locale where the dot is used as thousands separator instead the comma.

**Comment by cadon** [comment]
Hi, sorry for the late reply. You already found the reason for that bug, thanks for that :) I'll fix it in the next release.

**Comment by cadon** [comment]
fix is released.
