### ISSUE TITLE
Suggestion: Add checkbox to hide dead Dinos

### ISSUE THREAD

**Issue by noheals** [cadon/ARKStatsExtractor#203]
I'd like a checkbox to hide dead dinos from the library and the counter in the bottom left could maybe show alive/total or alive/dead creatures.

**Comment by cadon** [comment]
Hi, I'll add these extra numbers. You can show/hide dinos with the different status (dead / unavailable / neutered) in the library in the tab "Other" at the bottom left.

**Comment by noheals** [comment]
oh sorry thanks for that :D

**Comment by cadon** [comment]
New version with a checkbox for that is released.
