### ISSUE TITLE
OCR for Xbox One  users

### ISSUE THREAD

**Issue by GhostlyCrowd** [cadon/ARKStatsExtractor#206]
I've been using your app manually, and love it. I was wondering if you would include the Xbox streaming app (Xbox app and Xbox app beta) executable in your OCR screen grabbing. 

I see your hard-coded to look for "ShooterGame.exe" as i changed VLC players executable to that and was able to OCR grab from a screen shot i made from the Xbox one.

Much appreciated!

**Comment by cadon** [comment]
Hi, is VLC a common used application for xbox-users to play the stream, do you know of other apps that could be usefull to also include?

**Comment by GhostlyCrowd** [comment]
Hello, No VLC I used as a test, renamed its executable to "ShooterGame.exe" and played a small clip i recorded of my dino stats and tested your app and it treated it as an Ark window and OCR worked. 
Just to see how your app worked.

The windows 10 app that Xbox users use to stream is called "Xbox" or "Xbox (beta)" Both of which use the executable name "XboxApp.exe"

Including VLC would be useful thought if users decide to record clips or screenshots slideshows and then use them at a later date for data entry to the Application you are developing. 

Aside from these two executable/apps i am not sure what else might be useful to others, I do not own a PS4 to see what would be useful to them, but VLC they could use if your OCR can be coded to detect it with out renaming to shootergame.

**Comment by cadon** [comment]
New version with manual selection of the process that is used for the OCR is released. You can choose between ARK, XboxApp or input a name manually.

**Comment by cadon** [comment]
doesn't work yet, see #227
