### ISSUE TITLE
Trying to add dinos to library by hand just dups last dino added stats

### ISSUE THREAD

**Issue by Taiine** [cadon/ARKStatsExtractor#208]
So before we found this app, we were using an excel sheet. It was done by a tribe member and did all the highlighting, keeping tracks of mutations and the like...

Your app is clearly a LOT easier and less time consuming filling out all the details on fresh tames/fully grown babys.
However we have tried to add in the dinos stats from the excel sheet by hand but your app does not seem to allow this. Instead ot just dupes the stats of the last dino entered. The creature info changes, but not the stats. Is this ment to allow you to add in dinos stats by hand or no? If not could you add it in? We want to switch to this so badly but we can't add in any of our past dinos.

**Comment by cadon** [comment]
Hi, can you describe more precisely what you mean by "add the stats by hand", did you put the stat-values in the extractor and pressed the Extract-button? If you already know the stat-levels, you can enter the dinos in the Tester-tab by just entering the levels.

**Comment by Taiine** [comment]
Yes that is what I try to do. We try and place them in the tester tab but outside the creature info it just dupes the stats of the last dino added.

**Comment by cadon** [comment]
Still can't follow. Are you using the tester- or the extractor-tab to add the creatures? If you're using the extractor-tab, you have to press "Extract Level Distribution" after each dino you entered.
