### ISSUE TITLE
Red stats on Quetzal

### ISSUE THREAD

**Issue by jghake** [cadon/ARKStatsExtractor#209]
I'm getting red stats on my newly tamed Quetzal. I don't see any issues with the setup in Ark Smart Breeding.

http://imgur.com/a/56S4r

**Comment by cadon** [comment]
Check the controls that are red. In your case, the Taming-effectiveness range is too narrow. Possible values for the TE are 20.6% or 45.2%.

**Comment by jghake** [comment]
But the Quetzal was level 72 wild, and I tamed it using a box on top of another Quetzal. The taming efficiency was 100%.

**Comment by cadon** [comment]
Are you on an official server? 100% TE is not possible, at most 99.9%. If you're on an unofficial server, the stat-multipliers may be different.

**Comment by jghake** [comment]
Its my own server. Taming x10.

**Comment by cadon** [comment]
Then I don't know. The game sometimes displays wrong numbers which usually will be corrected after a levelup or a server-restart. I'd level up food and damage to see if that works.

**Comment by jghake** [comment]
It happened again with a Direwolf

http://i.imgur.com/xavbN0H.png

**Comment by cadon** [comment]
Can you post your stat-multipliers?

**Comment by jghake** [comment]
```
PerLevelStatsMultiplier_Player[0]=1.00
PerLevelStatsMultiplier_Player[1]=1.00
PerLevelStatsMultiplier_Player[2]=1.00
PerLevelStatsMultiplier_Player[3]=10.00
PerLevelStatsMultiplier_Player[4]=1.00
PerLevelStatsMultiplier_Player[5]=1.00
PerLevelStatsMultiplier_Player[6]=1.00
PerLevelStatsMultiplier_Player[7]=4.00
PerLevelStatsMultiplier_Player[8]=1.00
PerLevelStatsMultiplier_Player[9]=1.00
PerLevelStatsMultiplier_Player[10]=3.00
PerLevelStatsMultiplier_Player[11]=10.00
PerLevelStatsMultiplier_DinoTamed[0]=0.15
PerLevelStatsMultiplier_DinoTamed[1]=1.00
PerLevelStatsMultiplier_DinoTamed[2]=1.00
PerLevelStatsMultiplier_DinoTamed[3]=1.00
PerLevelStatsMultiplier_DinoTamed[4]=1.00
PerLevelStatsMultiplier_DinoTamed[5]=1.00
PerLevelStatsMultiplier_DinoTamed[6]=1.00
PerLevelStatsMultiplier_DinoTamed[7]=1.00
PerLevelStatsMultiplier_DinoTamed[8]=0.15
PerLevelStatsMultiplier_DinoTamed[9]=1.00
PerLevelStatsMultiplier_DinoTamed[10]=1.00
PerLevelStatsMultiplier_DinoTamed[11]=1.00
PerLevelStatsMultiplier_DinoTamed_Add[0]=0.38
PerLevelStatsMultiplier_DinoTamed_Add[8]=0.38
PerLevelStatsMultiplier_DinoTamed_Affinity[0]=0.15
PerLevelStatsMultiplier_DinoTamed_Affinity[8]=0.15
PerLevelStatsMultiplier_DinoWild[0]=1.00
PerLevelStatsMultiplier_DinoWild[1]=1.00
PerLevelStatsMultiplier_DinoWild[2]=1.00
PerLevelStatsMultiplier_DinoWild[3]=1.00
PerLevelStatsMultiplier_DinoWild[4]=1.00
PerLevelStatsMultiplier_DinoWild[5]=1.00
PerLevelStatsMultiplier_DinoWild[6]=1.00
PerLevelStatsMultiplier_DinoWild[7]=1.00
PerLevelStatsMultiplier_DinoWild[8]=1.00
PerLevelStatsMultiplier_DinoWild[9]=1.00
PerLevelStatsMultiplier_DinoWild[10]=1.00
PerLevelStatsMultiplier_DinoWild[11]=1.00
```

**Comment by cadon** [comment]
Ok, I found the reason for the failing extractions. The (compared to the official server settings) small value of the Tamed_Affinity settings for the damage-stat causes rounding errors for the calculation of the taming effectiveness that are too large for the current tolerance bounds. I'll have to look in more detail how I can adjust the algorithms to take this in account.

Thanks for the reports and the data so far! Until I find a solution, you can try to extract the non-working creatures by copying them into the tester (there's a button under the menu "Copy to Tester") and adjust the damage and food levels until they match the ingame-values. Then increase the speed-level until the torpor level is equal to the total level minus 1. That way you can extract them with exact levels.

**Comment by Xzirus** [comment]
I Just have a quick question, I am having the same issues and it looks like my server settings are the same as this users, could you tell me what server settings that I could change to make my game work with your tool? Any direction would be appreciated, thanks for your time.

**Comment by cadon** [comment]
I guess it's the low value of PerLevelStatsMultiplier_DinoTamed_Affinity[8]=0.15 (the default value is 0.44) that causes the rounding error.

**Comment by cadon** [comment]
The latest release can handle the rounding-issues better.
