### ISSUE TITLE
Breeding stats no good

### ISSUE THREAD

**Issue by Luin71** [cadon/ARKStatsExtractor#210]
![domestic](https://cloud.githubusercontent.com/assets/26408461/23902519/c13a1fd2-08c1-11e7-9bbb-ba010662b0b4.jpg)

I have big problems with Breding Dinos now after lastest patch... All points/stats are right but still geting red on all except Stamina and Oxygen... Doesnt matter what Dino i try..
Imprinting seems wrong in som cases but when i change it just change back

Tamed works fine.

**Comment by cadon** [comment]
Hi, is the imprinting-Quality of the creature larger than 0%?

**Comment by Luin71** [comment]
Sometime yes, but when i change it it goes back to what it found before .. .. like if it found out its has 29%... but i see that is 26% .. its still want it to be 29% what i do to change that

**Comment by cadon** [comment]
The imprinting-percentage can only have certain values depening on the BabyMatureSpeedMultiplier and the BabyCuddleIntervalMultiplier. If one of those is not set correctly, imprinted creatures cannot be extracted.

**Comment by Luin71** [comment]
Still have this problem ... and still its only Breeding dinos

![untitled2](https://cloud.githubusercontent.com/assets/26408461/24083337/7d3be0aa-0cd5-11e7-8428-1acce528772b.jpg)

**Comment by cadon** [comment]
Some multiplier is not yet correct. Can you post the game.ini?

**Comment by Luin71** [comment]
[Game (1).zip](https://github.com/cadon/ARKStatsExtractor/files/853596/Game.1.zip)

**Comment by cadon** [comment]
I don't see a problem, the extraction works fine with this game.ini.

Do you have BabyMatureSpeedMultiplier = 10, BabyCuddleIntervalMultiplier = 0.3 and BabyImprintingStatScaleMultiplier = 3?
