### ISSUE TITLE
A Notes Section

### ISSUE THREAD

**Issue by xWolfx93** [cadon/ARKStatsExtractor#211]
The smart breeding app is a great tool, but i think it could really use a "notes" tab. it would be easier to keep breeding related notes in the tool instead of having them flying arround the computer.

**Comment by cadon** [comment]
Hi, sounds like a good idea. Do you mean just a list of notes, like a list of note-titles on the left and a display of the selected note on the right?

What kind of notes are you taking, are they creature-related like "try to breed Fluffer next", species-related like "we need an OP rex" or more general like "need to build a breeding-shed"? Or are they more like a todo-list?

**Comment by xWolfx93** [comment]
currently creature related, like "breed rexi with rexo" stuff like that, since it gets kinda confusing sometimes if you have different breeding pairs. also something like a shared todo list would be great aswell. my tribe really breeds alot, and everyone likes different color mutations, so everyone needs to keep their own notes about which rex has which color mutation. even though that could be solved by just adding the colors in via the color thingy in libary tab we are all to lazy to do it. but the main use I (and my tribe) would have is to keep tab of breeding pairs better, since the question comes up alot "with which male do i breed this female again?"

**Comment by cadon** [comment]
New version with notes-tab is released. It's very basic, feel free to suggest improvements here.

**Comment by xWolfx93** [comment]
how do i make titles for notes? also when i delete a note an error message appears (something about index value of 0 is not valid).

**Comment by cadon** [comment]
Ah, sorry. I worked on the list some weeks ago and apparently I neglected that badly. I'll fix it soon.

**Comment by cadon** [comment]
Now it should work in a basic way.

**Comment by xWolfx93** [comment]
i cant get notes to save, i click add note, type in a title and a text, when i restart the tool the note is gone. i did try a manual save to, normaly i have autosave enabled.

also it would be nice to be able to start a new line by pressing enter, but that is a minor thing

**Comment by cadon** [comment]
So, finally the notes should work. Sorry for the long delay, I forgot them. Also, enter and tab can now be used in the notes.
