### ISSUE TITLE
Toggle Overylay

### ISSUE THREAD

**Issue by Gamerscd** [cadon/ARKStatsExtractor#212]
When i toggle the overly it only shows for a second not sure why wanted to see what this feature does.

**Comment by cadon** [comment]
Hi, if the OCR-feature does work for you, the overlay should as well. Everytime you open an inventory, it shows additional informations like the levels from the stat-values.

**Comment by cadon** [comment]
There is a bug, that the overlay will not show any info if the OCR wasn't used before. This will be fixed in the next release. Until then make sure you click on "Read values from ARK-window" at least once to make the overlay work.

**Comment by cadon** [comment]
New version with fix is released.
