### ISSUE TITLE
Aquatic Breeding - 0 Levels in Speed

### ISSUE THREAD

**Issue by KevinCollmer** [cadon/ARKStatsExtractor#213]
Hey,

aquatic (non-oxygen) Dinos are still not extracted correctly. After entering all info it is still showing 0 levels in speed (glamour-level).

This is preventing you from getting the exact breeding-values (which level your baby could be).

I havent tested with many creatures yet but I can definitly tell, that Carbonemys is one of those where it isnt working probably.

**Comment by cadon** [comment]
Sure. If you have any idea how these levels could be extracted, I'd be happy to know. If the oxygen stat is unknown, you have two unknown stat-levels (oxygen and speed) and I can't think of a way to determine them.

There's a mod (it's called super-magnifying glass or similar) that lets you see the oxygen value even if the creature doesn't use that stat. If you use this mod, you can enbale the setting "Enable oxygen for all creatures" in the tool and enter the oxygen value to get all the levels like with the other species.

**Comment by KevinCollmer** [comment]
Hey, I am playing on official. I would recommend to just show that there are X levels in oxygen/speed or just show all levels in speed... It would help get the levels of babys right and would at least give a little bit of an hint where those levels went in without calculating them by hand.

**Comment by cadon** [comment]
There's no certainty which levels a baby will inherit (from mother or father), so you can't calculate the possible levels of the offspring. If the mother has 10 levels in oxygen and 15 levels in speed, and the father 20 levels in oxygen and 10 levels in speed (all not possible to extract and thus unknown), the possible levels for the offspring is the displayed level, plus 20 to 35 extra-levels from these unknown levels. And for higher-level creatures that range gets bigger.

If you think it's helpful, I can display a rough-estimate what the level could be (in the example above it would be ~27), but as said, the exact level has a wide range, in the example it would be +- 7.

**Comment by cyberangel67** [comment]
How are you calculating parents then, I would assume it would be the same with imprint bonus. I am able to add a Mosa without issues if tamed, but babies fail. The parents don't use Oxygen to get it right, so how does imprinting differ?

**Comment by cyberangel67** [comment]
And just so you know even with Super Spy Glass the Mosa baby can't be added to the library.

I have also noticed that extracting seems to still calculate wrong Imprinting percentage too, changing it to try and match the correct YOU recalculate the Imprinting percentage back again. I know I had this isssue once before, which I am sure I created a ticket for, where making slight adjustments to the Imprint % was able to get it to extract, but recalculating that makes it near impossible to now extract anything with imprint on it.

**Comment by cyberangel67** [comment]
Btw Xbox doesn't have these mods, so there will be a lot of people on their that will not like this.

**Comment by cadon** [comment]
@cyberangel67 the oxygen bug should be resolved now (showing an enabled oxygen for species that don't have oxygen). The imprinting-percentage being changed is usually caused by not correct cuddleInterval- and / or babyMatureSpeedMultiplier. Did it work in the meantime?

**Comment by cyberangel67** [comment]
Not sure what you mean here, do you mean the setting to tun Oxygen on and Off?

This will not work for Console, there is no way to get the Oxygen value on Console. But like I said before this, tames without Oxygen have an Oxygen value and you seem to be able to calculate them ok, what is the difference now?

**Comment by cadon** [comment]
There was a bug in the extractor, that sometimes displayed / enabled the input for oxygen, even if the species doesn't have oxygen and the settings "Enable oxygen for all species" was disabled. Then it was not possible to extract the creature, because the tool expected (falsely) a value for oxygen, which the user couldn't provide without the super-spyglass-mod.

**Comment by cyberangel67** [comment]
So are you saying that the super spy glass is not needed and we don't need to enter oxygen for non oxygen water breeds?

**Comment by cadon** [comment]
Yes. The advantage of using the super-spyglass-mod and entering the oxygen for non-oxygen-species is that the oxygen level and thus also the speed-level can be extracted. If the oxygen is diabled and not entered, the creature can be extracted, but without the levels of oxygen and speed.
