### ISSUE TITLE
Selecting Dragon in the Taming section crashes the app

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#216]
As the subject suggests.

Btw is this the Boss or DragonFly or a Wyvern?

**Comment by cadon** [comment]
It's the boss. The bug will be fixed. I added it to the list because it is rideable with cheats and in SotF.

**Comment by cyberangel67** [comment]
I don't think there is anything wrong with ahving the bosses in there, depending on how much further you're wanting to take the app. But a flag could be used to identify it as a boss and handled in the code maybe.

**Comment by cadon** [comment]
New version with fix is released.
