### ISSUE TITLE
Cant add breeding Rex

### ISSUE THREAD

**Issue by l1l1th85** [cadon/ARKStatsExtractor#219]
Everytime i try to add my rexes with extractor all sts get red. I already checked all values, the program is updated, already waited for server restart and even i restarted the game. Still not working :|

**Comment by cadon** [comment]
Hi, then it's probably a multiplier you didn't set correct. If you have multipliers that are very different from the official ones (very large or very small), that could be an issue, too.

**Comment by cadon** [comment]
Hi, I hope it's resolved by now, if not, just reopen the issue.
