### ISSUE TITLE
Suggestion: Fully replace dino editing with Stat Testing window

### ISSUE THREAD

**Issue by Jagged** [cadon/ARKStatsExtractor#22]
I love the new right-click to edit feature!  However, the Name, Owner, Gender and Parents aren't filled in correctly with the details of the selected dino, nor are any edits to them saved.

**Comment by cadon** [comment]
The normal way to edit the creature is via the box in the library. The right-click method is only intended to adjust the wild-levels. Do you think it's easier to edit the parents, gender, owner and name with this method, too?

**Comment by cadon** [comment]
I added the saving of the name, owner, gender and parents. Not editable in the Tester are Status and Notes yet. I might add them later.

**Comment by Jagged** [comment]
> Do you think it's easier to edit the parents, gender, owner and name with this method, too?

Definitely.  The screen is more featured and also easier to work with as not all squished up in a corner.  Maybe add/edit/testing/extract could eventually be merged into a single screen?

> I added the saving of the name, owner, gender and parents.

Brilliant!
