### ISSUE TITLE
Giganotosaurus bug with speed

### ISSUE THREAD

**Issue by dshombre** [cadon/ARKStatsExtractor#220]
I am trying to extract my new Giga, but when I do that and I put 100% Speed, Extractor keeps telling me, that 100% are 110 levels and don't let me to save my Giga.
![arksmartbreeding](https://cloud.githubusercontent.com/assets/26548064/24106209/87d3c944-0d87-11e7-9543-e0fdcb4cb987.PNG)

**Comment by cadon** [comment]
Hi, Giganotosaurs are special. For this one, click on the button "Copy to Tester" and adjust the speed-level until the torpor-level is 135 (one less than the total level). Then you have the correct levels and can add it to the library.

It's a bug, I'll look into it, if it's solvable.

**Comment by cadon** [comment]
Now the tool recognizes this and sets the speed-level to unknown.
