### ISSUE TITLE
Troodon is missing colors

### ISSUE THREAD

**Issue by KattaLord** [cadon/ARKStatsExtractor#221]
As I wanted to add my Troodons colors to the tool I noticed that they are missing.
These are my Troodons in the game:
![20170320213127_1](https://cloud.githubusercontent.com/assets/26555317/24120676/c04c9f02-0db5-11e7-8b49-d8dff5652213.jpg)
And this is a list of the available colors in the tool:
![tool](https://cloud.githubusercontent.com/assets/26555317/24120519/3512c786-0db5-11e7-8600-6b0977e7393d.png)
I searched the wiki to find out if my Troodons are just bugged/spawned with the wrong color or if it's a bug in the tool and this is what I found in the wiki:
![wiki content](https://cloud.githubusercontent.com/assets/26555317/24120520/351955f6-0db5-11e7-9025-0198b703de4c.PNG)

**Comment by cadon** [comment]
Thanks for the note, these are the "new" colors. I'll add them in the next release. Until then, just disable "Show only natural occuring" and choose the colors there (the missing ones are the ones with numbers from 42-56).

**Comment by cadon** [comment]
New version with added colors is released.
