### ISSUE TITLE
Can't add Kappro / Also can't manually add in dinos

### ISSUE THREAD

**Issue by Taiine** [cadon/ARKStatsExtractor#222]
http://i.imgur.com/qYXieIK.jpg
Just got this stunning pinkish red color mutated kappro but it can't be added to the list. 9x server max 150lv. Setting's are set right.

Also how do you properly add in the dinos manually? I do this and click copy to tester and it just puts all the red parts to zero. The extract level distribution just makes the whole window flash. These are the two ways I've been told on how to manually add in dinos.. but neither work. 

Can you please make adding them in manually easier, like somewhere to really type in the stats? We have a whole excel sheet with all our dinos base info before we found this, but we can't manually add any of them. We can't edit the values when we pull with the extracter to put in the normal stats from our sheet and the stat testing that everyone keeps telling me to use to add them only has a two digit value to add. 

We just want to type in the stats and add them... so far we can only add in new tames/bred dinos, but wer still need to use the excel sheet to keep tabs on all the rest.

**Comment by cadon** [comment]
Hi, it's probably an issue that the game does not yet show the correct values (some stats have the full imprinting bonus, other don't have it yet). After a day or so it should be displayed correctly.

To add dinos manually, you have to input the levels. You cannot input dinos with any stat-values. Either the extractor can extract the exact levels, or you have to input the levels. The input in the tester is not for values, but for levels.

If you're sure the settings are all correct and if other creatures can be extracted fine, it's probably the issue with the wrong displayed values in the game. Then just try it again after a day.

**Comment by VolatilePulse** [comment]
Closing due to age of issue, lack of information, and numerous updates and changes since the initial issue was submitted.

If you feel the issue hasn't been corrected yet, please reopen the issue and provide screenshots or export files of the creatures you're failing to extract. ASB is more than capable of extracting creatures with post-tame levels (read: domestic levels) and is preferred over using old and potentially incorrect data from a spreadsheet.
