### ISSUE TITLE
Cant do anything

### ISSUE THREAD

**Issue by bNarFInfe** [cadon/ARKStatsExtractor#223]
So basically I think i am a moron but I dont know what i am doing wrong.
Got your App from [https://youtu.be/zOYvKhLAHL4?t=12m38s](url) who explains you app and I cant help but notice this is freaking awesome. So I download the app start the game and try it.
![ark10](https://cloud.githubusercontent.com/assets/26623398/24273773/7d44eb1c-1024-11e7-8723-93699c6cd1b0.png)
First Screen is what i get from every Dino I tried.
I have to select the Dino everytime by myself and he wont put any lvl in it. Even though the stats are like 99,8% right all the time from like 200 trys.
![ark11](https://cloud.githubusercontent.com/assets/26623398/24273796/9c72fc9a-1024-11e7-8993-303292b2de61.png)
Second Screen Looks like this. Its not like in the Video that the programm shows me what wild lvl my Dino was. I cant change anything on the right side like in the Video.
Its always like that and I cant do anything or I am just a moron. Sorry to bother you.

**Comment by cadon** [comment]
Hi, probably you mixed the multipliers for "TameAdd" (the bonus you get after taming depending on the taming effectiveness) and "TameLevel" (the amount you get per levelup after taming). Also the "TameAdd" of Health and Damage seems to be still the official value of 0.14. And don't forget to set the total level, sometimes the OCR can't recognize that (it's at 0 in the first screenshot). With these settings it works fine:

![multipliers](https://cloud.githubusercontent.com/assets/8763269/24304381/6fbd910c-10b9-11e7-8927-e8520035b4e4.png)

**Comment by bNarFInfe** [comment]
![ark12](https://cloud.githubusercontent.com/assets/26623398/24314720/5be9aed4-10e3-11e7-8a0d-4baf6252987c.png)
![ark13](https://cloud.githubusercontent.com/assets/26623398/24314719/5be66238-10e3-11e7-899c-c8f5aabf43df.png)
![ark14](https://cloud.githubusercontent.com/assets/26623398/24314718/5be24ae0-10e3-11e7-9be8-9fc6ae248a29.png)
Well sorry to bother you again. Really dont know what I am doing wrong. Added the Server config in the first Picture.
App still dont show me the wild dino lvl before tamed and I cant change something in the app.

**Comment by cadon** [comment]
You still haven't fixed the multiplier-settings. See my previous answer for the ones that should work.

**Comment by bNarFInfe** [comment]
![ark15](https://cloud.githubusercontent.com/assets/26623398/24316705/9586fb94-10f0-11e7-8f8f-f1dd98eb4e6a.png)
So I think it should be like that. I am still not to set the options on the right side.

**Comment by cadon** [comment]
Oh, das sind jetzt aber nochmal geänderte Multiplier? Solange nicht alle stats extrahiert werden konnten, kann man die Möglichkeiten bei den gelben nicht auswählen, da alle stats von einander abhängen. Die Geschwindigkeit ist mit den eingestellten Multiplikatoren nicht möglich, schau nochmal in die game.ini, ob da noch andere Werte für PerLevelStatsMultiplier_DinoTamed[9], PerLevelStatsMultiplier_DinoWild[9], PerLevelStatsMultiplier_DinoWild_Add[9] oder PerLevelStatsMultiplier_DinoWild_Affinity[9] stehen. Oder noch einfacher, wenn die game.ini als Datei vorhanden ist, oder die Werte in einer Textdatei gespeichert werden, einfach die Datei auf das Einstellungsfeld ziehen, dann werden alle Werte daraus richtig eingelesen.

**Comment by bNarFInfe** [comment]
Hab jetzt drag drop Game Inn gemacht.
Funktiniert jetzt danke.
Der hatte die Game Inn werte allerdings verzehnfacht reingesetzt. Also anstatt Health 1.00 10.00

**Comment by cadon** [comment]
Gut zu hören, dass es funktioniert 👍 

Beim Auslesen erwartet das Programm einen Punkt als Dezimaltrennzeichen , kann sein, dass die Werte ein Komma hatten, so dass "1,0" als "10" erkannt wurde, da das Komma ignoriert wird.
