### ISSUE TITLE
Stat Testing showing wrong value in stat potentials for Damage

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#224]
I went looking through the code, couldn't find where you calculate either of these values or even where the original Damage comes from stat wise as it appears to not be in the raw stats of the Dino.

Anyway as you can see by the image something is off, I was hoping to fix it if I knew how this was being calculated.
![capture](https://cloud.githubusercontent.com/assets/1366816/24324848/e9fa87e4-11e1-11e7-8a9f-b1097eaa0994.PNG)

**Comment by cadon** [comment]
Thanks. The displayed value was always with 100% TE, will be fixed in the next release. It will also not show the imprinting-column (blue) for non-bred creatures as they cannot be imprinted.

**Comment by cyberangel67** [comment]
np, was actually trying to find out if the 122.1 for Damage was actually a bug. Everything else I looked at assumes Damage is 100% wild before any stats applied.

**Comment by cadon** [comment]
After thinking about it, I reverted the changes to the current state. That box is an outlook on what the single stats could be, if that creature is used for breeding and the offspring is imprinted with 100%.

The stat-values of an individual creature can be checked on the controls in the left and with the TE and imprinting-input. I think that way both infos (from the current creature and the potentials of the "genes" of that creature) are available.

**Comment by cyberangel67** [comment]
While I understand what you're saying, however if it is a Wild or Tamed selection then imprinting doesn't play a role in those values and can be confusing to other users.

Still, I would like to know why either Wild or Tamed has a value of 122.2, when everyone else has a flat value of 100 for Damage. When nothing has been entered that is.

**Comment by henrik123098** [comment]
only wild dinos lvl 1 has 100%. wild levels does apliy on the stats. which is why when you shoot a ptera lvl 60 or something down it haves maybe 170% dmg with others stats also grown

**Comment by cadon** [comment]
Hi, sorry for the late reply. The wild Achatina has a damage value of 100 %, once tamed it get's an additive bonus of 7% and additional 17% × taming-effectiveness.
I'll close this issue for the clarity of the issue-section, if you have more remarks or opinions on that topic, just reopen it.
