### ISSUE TITLE
Problem with bred Dimorphodon extraction

### ISSUE THREAD

**Issue by Asmo57** [cadon/ARKStatsExtractor#225]
Hi,
First of all, thanks for your great tool!
I have a problem with the Extractor with my bred Dimorphodon. I tried all your suggestions but I was not able to correct it.
Here are the screenshots if you have some time to look after.
http://imgur.com/a/3nz45

Thanks.
Asmo

**Comment by cadon** [comment]
Hi, you haven't set the imprinting-progress. If it's still not working, send me your multiplier-settings. Also note that imprinting does not increase the stat-values instantly, sometimes it takes up to a day until the values are correct and the tool can extract them.

**Comment by Asmo57** [comment]
I think I understood the problem: we changed some multipliers on our server, and the Dimos which I can not extract are all from the old multipliers. The new ones I have no problem with.
Is it possible to change the multipliers in your tool, Extracts the old Dimos and set it back to current values after?

**Comment by cadon** [comment]
Yes, that would be the best way to do it! Another way could be to levelup the ones that are not working, that usually forces a recalculation with the new multipliers.
