### ISSUE TITLE
Read Values From Ark Window Not working For Me

### ISSUE THREAD

**Issue by CamBigRed** [cadon/ARKStatsExtractor#226]
I just downloaded this and when I opened up ark and accessed a dinos inventory to try it out I had an issue. When I press the real values from ark window button with the dinos inventory open, it just minimizes itself and nothing happens. I made sure to set it to tamed dino and stuff but when I try to press the button it just keeps minimizing the smart breeding window, nothing happens, and I'm just left looking at the dino inventory. Any help with this issue would be appreciated.

**Comment by cadon** [comment]
Hi, what is written in the OCR-tab in the right window?

**Comment by cadon** [comment]
Hm, that should be correct. Do you have multiple monitors? That could be a reason it's not working.

**Comment by CamBigRed** [comment]
hmmm the smart breeding window still keeps minimizing, even though I've lowered the resolution to several different settings like 1680x1050 etc and I'm just using my laptop so I don't have multiple monitors

**Comment by cadon** [comment]
1920x1080 should be the best resolution for it to work. Ah, do you have set the window-mode to "windowed-fullscreen" in the ARK-settings?

**Comment by CamBigRed** [comment]
I switched it back to 1920x1080, and yes it's set to windowed-fullscreen mode, but still the same issue

**Comment by cadon** [comment]
can you do a screenshot of a creature-inventory with the keys [Windows] + [Print Scrn], that should create a screenshot in the images folder, and post it here?

**Comment by CamBigRed** [comment]
![ark](https://cloud.githubusercontent.com/assets/26696278/24335628/771ac162-124f-11e7-853b-57dc95b05451.png)


My native resolution is 1920x1080

**Comment by cadon** [comment]
Hm, what happens if you drag&drop this image-file onto the extractor? That works for me (ignoring the small error it's doing on oxygen, 51.0 instead of 510).

**Comment by CamBigRed** [comment]
![arrk](https://cloud.githubusercontent.com/assets/26696278/24335743/4856bd8e-1251-11e7-8359-171ff93aefa2.png)

Yea that seemed to work! So for now on I just have to take a screenshot of the dinos inventory and drag it to the extractor?

**Comment by cadon** [comment]
That's strange. Basically, the tool does exactly this: taking a screenshot and extracting the data. It seems the process is still different. Indeed that's good to know, as many people have issues with the OCR, and that seems to be the reason. I'll look into this.

**Comment by Yuuriny** [comment]
Hi there, 

I kinda have same problem, the button Read Value from ARK Windows isnt working at all for me and i dont know why, i've none error msg at all. 
So i tried couple of things like : Checking Admin access, Compatility with windows, also settings inside asb, Resolution, OCR, everything i read while searching to fix that issue. 
I also tried to just change the  asb.exe with a old one i got from long time ago and there the ASB windows react with ARK windows but nothing at all is copied (the windows switch each others and copy 0 value everywhere), on New asb.exe, nothing react, nothing copy like if ARK wasnt here.
Both .exe are working fine if i copy values by hand, but if u guys got a idea to fix it, i'd appreciate :)

idk if its important but:
My resolution is 1680x1050 (Windowedfullscreen & Win10)

**Comment by cadon** [comment]
Hi @Yuuriny , currently the OCR does only work with 1920×1080, so sadly for now there's nothing you can do about it.

**Comment by cassfalg** [comment]
I'm having issues with the screenshot beeing all grey when I click on "Read Values From Ark Window". It works better when I drag a file in. Maybe the game is not ready yet when the screenshot is taken? It seems to sometimes take even a couple of seconds before I see the game instead of a black screen when I tab into the game. Maybe an adjustable delay before the screenshot is taken would help?

**Comment by cadon** [comment]
Hi @cassfalg, I created a separate issue for this: #280

**Comment by fireeyedpixie** [comment]
@cadon,  i don't believe the extractor will ever work correctly for me as I'm on a laptop and it doesn't let me select higher than 1600 for my res in ark so 1960 is definitely out, however even trying to drag and drop the screenshots of the stats into the smartbreeder still does not work for me. Am I destined to manually fill it out forever or am i doing something wrong? I take the screenshot, drag it to the smartbreed to drop but nothing ever populates from it.

**Comment by cadon** [comment]
Hi @fireeyedpixie, you need to create an OCR-config-file that matches exactly the resolution you have. See https://github.com/cadon/ARKStatsExtractor/wiki/OCR for more infos. If you have created such a file, you can post it here and I can include it in the next release for others to use.

**Comment by VolatilePulse** [comment]
As a final follow up, the OCR library used in ASB is a rather rudimentary one. It works most of the time as long as the screen resolution in game is 1920x1080. Any other resolutions are not accurate enough to consider, even though some of them show as being supported (these are mostly user submitted files we felt others may benefit from). Even the optimal resolution (1920x1080) is not 100% accurate and we advise all users to switch to [Importing Creatures](../wiki/Importing-Creatures) that are able to.

We are aware that the current library does not support the Win10 version of Ark and have not found a workaround. OCR is something we have discussed in the past, but I don't believe there will be any attempts soon to optimize it without someone literally presenting a better library for us.
