### ISSUE TITLE
OCR Doesn't work for Xbox App, took screen shot to test it with and same issue

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#227]
So I noticed that you have added the ability to capture for Xbox Users, have been waiting for this option for a long time and decided to give it a run for its money today.

Selecting the option in the settings, saving it and even restarting the program doesn't seem to get it to work. The window doesn't pop up like it does for the PC user, any way I took a screen shot and decided to try it that way through the OCR tab.

Yeah it doesn't work.

First image is the results from dropping the image into the image area

![capture](https://cloud.githubusercontent.com/assets/1366816/24344073/7d19b480-1315-11e7-8d79-2321aa414e48.PNG)

This is the image that I used to test it with.

![xbox 6_01_2017 4_01_03 pm](https://cloud.githubusercontent.com/assets/1366816/24344096/9653dafc-1315-11e7-958a-1c1cc23a5657.png)

I must admit I didn't expect it to work first go, but hopefully this will give you what is needed to have something going soon.

**Comment by cyberangel67** [comment]
I did a line debug on the OCR off the running process.

        public static Bitmap GetSreenshotOfProcess(string processName)
        {
            Process[] p = Process.GetProcessesByName(processName);
            if (p.Length == 0)
                return null;
        }

It apparently fails getting the process name XboxApp.exe, the length is zero, so whether this is a Windows 10 issue or an Issue getting the running process I am not sure, will see what I can dig up.

**Comment by cyberangel67** [comment]
Ok on further investigation it appears to work with getting the process if the exe is removed from the name. But the main handle isn't. From what I am seeing is the screen grab is failing as it is null when being returned.

**Comment by cyberangel67** [comment]
Ok I am getting somewhere but my limitations end here with processes, when getting the Xbox App you need to do it like this

ProcessModule proc = p[0].MainModule;

As this is no longer an IntPtr I would need to research it more.

**Comment by cadon** [comment]
Thanks for the feedback, I have no xbox so I assumed it's enough to just change the name of the process. Someone said when they renamed the XboxApp.exe to ShooterGame.exe (the executable of ARK) it worked with the previous version.

I also noticed, the stats have different positions on the xbox, so that needs to be adjusted as well.

**Comment by cyberangel67** [comment]
Yeah that test they did was with VLC itself and not the Xbox App. From what I am reading this issue is with any Windows 10 Store App, where the main window is a container and then the App runs as a child under that.

As VLC is a standalone executable I am not surprised it worked.

**Comment by cadon** [comment]
What do you mean with "container-app"? Do you think it would work if the child-app is used directly? I've no xbox to test this, so I'm happy about any info how to solve that.

**Comment by cyberangel67** [comment]
I don't know to be honest it is what I was reading on getting the handler to Windows Store Apps.

For example for native standalone programs you would do

IntPtr proc = p[0].MainWindowHandle;

Which is what you do, but this returns null on Windows 10 Store apps and you need to use

ProcessModule proc = p[0].MainModule;

After that I have no idea what to do, I haven't been able to find much more information.

**Comment by VolatilePulse** [comment]
Closing due to age, numerous changes, and #226.
