### ISSUE TITLE
Incubation-Timers in the Raising-tab cannot be deleted

### ISSUE THREAD

**Issue by xWolfx93** [cadon/ARKStatsExtractor#228]
First of: its great. i really like it.
but i have some issues with it.
https://www.dropbox.com/s/u0gbvgu3p5rb7y8/smartbreedingissue.PNG?dl=0
as you can see there are "empty egg timers" which i cant remove. the only option is to "extract values from the baby" i did that, but the egg timer is still there.

**Comment by cadon** [comment]
Thanks for pointing that out, I'll add a "remove-timer" button.

**Comment by cadon** [comment]
Version with fix was released.
