### ISSUE TITLE
Breeding Plan - one female several males?

### ISSUE THREAD

**Issue by MrMotte** [cadon/ARKStatsExtractor#229]
Hey :)
can you add an feature (like a setting or checkbox) That the breeding plan only Suggest the best male for each female?
for 10 suggestions in breeding plan my top 4 suggestions are the same female only with other males, but i cant breed one female with 4 male at a time :D so it would be nice to see only one sugeestion per female :)

**Comment by cadon** [comment]
Hi, I'm thinking about that. For the meantime, you can right-click a female that just mated and click on "Set cooldown for next 2h" to exclude that female from the plan.
