### ISSUE TITLE
Suggestion: Deleting dino shouldn't change Species filter to All

### ISSUE THREAD

**Issue by Jagged** [cadon/ARKStatsExtractor#23]
While I'm working on a species I just have that one shown via the Species filter.  When I remove a dino it changes the filter to All and I'm suddenly presented with an overload of information (I'm might have a few dinos!!!), forcing me to reselect the Species filter.  

Can it please stay on the selected species?  Thanks! =)

**Comment by cadon** [comment]
Thanks for all the suggestions! I'll make the tool remember what was selected in the next version.

**Comment by cadon** [comment]
Feature added.

**Comment by Jagged** [comment]
Awesome, ty!
