### ISSUE TITLE
Red high lighting over WILD TAMED BRED and Level

### ISSUE THREAD

**Issue by thedreadedplague** [cadon/ARKStatsExtractor#231]
Every time I input a new dino and it's stats, it highlights in red the "Wild Tamed Bred" options and the "Since taming no Server-Restart" option. The no tame box is unchecked and the dino is tamed. Everything else seems to be fine except for this. I am playing on official, just cleanly downloaded the program. Changed the wild dino level. I've tried with multiple different dinos. I appreciate your help

**Comment by cadon** [comment]
Hi, the best would be to post a screenshot of the inventory of a creature that does not work. What do you mean with "The no tame box is unchecked"?

**Comment by cadon** [comment]
I hope it's resolved, so I'm closing this issue now. If not, reopen the issue and optimally attach a screenshot.
