### ISSUE TITLE
New UI has bugged us

### ISSUE THREAD

**Issue by strassern** [cadon/ARKStatsExtractor#232]
Hello Dedicated Program Dev!!!
    I know in anticipation of the new format of the UI we would be up agains some challenges with this beautiful application.  I just want say that I love this app and it has changed breeding and this game for me (with or without the stat pull feature working!).  Not having to enter all of the numbers manually is utter genius.  

Moving forward and not meaning to play the part of Captain Obvious here, I did want to throw this out. 
 Another thing I noticed with the recent flier nerf (which I'm sure will have a counter measure to follow shortly from the devs).  This may not be worth doing anything about now but from what I can tell, they have eliminated the points currently that went towards speed as 'dead points' so to speak (the wasted points).  A bird that previously was over 400 and maxed, received 90 points back (to spend) and none of which were spent on other stats that I can tell (weight, hp, etc seem spot on where they were) with the exception of stamina which may have come down along with this nerf.  Nearest I can tell is they may have reduced those dead point in some way as the bird is now 297 with 90 points to spend and seems to have lost some original leveling points (150 lvl wild max and +200 dom pts on this server).  This was originally a tamed bird so best assumption is it would have been 215-224 when tamed and should have reach 414-424 maxed.   I can't narrow down for certain as this is the only argie I use for moving around and was not stat'd early on.  Time will probably need to set in whatever fix they are going to use for this to balance.

Back to the original question, do you foresee this being a quick fix relocating the code to view the new stat area within Ark?  The lettering is smaller but seemingly more crisp so this may help with some of the issues where it might not pull 100% accuracy.  So that is a plus.  Some of the downsides I can see would be that the name of the Argie does not show up in the UI so the name may not be able to show up in your data going forward, working with what we have right now.  Let me know your thoughts.  

Again, my buds and I really strongly appreciate your work on this application.  Genius.  +100

Strassern

Quick edit: This argie was a bred dino early on not a tamed one.  It was definitely remembered as over 400 and in the range I previously mentioned.

**Comment by cadon** [comment]
Hi, I read that the level- / stat-mismatch seems to be a bug, but I haven't looked into that myself. The new values with the flyer-nerf and the new species were just uploaded, you can get them in the menu with ? -> Check for Updates.

I'm working on the OCR. The font seems to be better recognizable, but the different informations now use different font-sizes, which makes some more tweaks necessary. Also, the name has disappeared, and also the baby-weight, which is a bit disappointing. On the plus-side, the species-name is always displayed, which makes the species-recognition more simple.

**Comment by cadon** [comment]
New version is out. The OCR is not very optimized yet, but recognizes most of the text.

**Comment by strassern** [comment]
Thank you!
