### ISSUE TITLE
Lack of an ingame oxygen stat is causing OCR stats to be offset

### ISSUE THREAD

**Issue by Ligraph** [cadon/ARKStatsExtractor#234]
When I am using the OCR, because there is no oxygen value ingame, the ORC reads the food value into the oxygen box, weight into food, etc.  
Example: 
![plesi](https://cloud.githubusercontent.com/assets/17717986/24590989/406248d6-17ac-11e7-8f84-fd7691cda2d2.PNG)

![reader](https://cloud.githubusercontent.com/assets/17717986/24590993/5c017c1a-17ac-11e7-8ff4-27aa6aa1e4de.PNG)

**Comment by cadon** [comment]
Oh my, yes, that's another issue with the new ui. I'll put it on the todo-list. Thanks for the note!

**Comment by cadon** [comment]
It's fixed. Redownload 0.22.2 for the fix.
