### ISSUE TITLE
[Feature Request] Imprint Timer

### ISSUE THREAD

**Issue by Ligraph** [cadon/ARKStatsExtractor#235]
It would be nice to have an average imprint time in the same area as the incubation, baby, and maturation times.  Like the mating timer.

**Comment by cadon** [comment]
Hi, iirc the imprinting time is always 3-4 h with the official settings, so it's not very precise. If the times can be calculated more precisely, it would be a nice addition. What's your experience with the ingame times, are they the same for all species in a reproducible way?

**Comment by Ligraph** [comment]
I think you're right about the times.  The few I looked at were all 6-7.5 h (custom settings).

**Comment by cadon** [comment]
Hm, that's still a wide range. I suppose if someone wants to know when to set an alarm e.g. in the night, it should be with a precision of at most 5 mins to be usefull. Unless I oversee something, it's probably easier to look in the game what the creature-cuddle-timer says ("wants care in xx:yy mins) and set a timer accordingly.

**Comment by cadon** [comment]
I don't think that feature is useful enough to implement it. If there are new ideas for that, feel free to reopen this issue.
