### ISSUE TITLE
Pteranodons values no longer accurate

### ISSUE THREAD

**Issue by Brewfasa** [cadon/ARKStatsExtractor#238]
The HP values of the pteranodons after the nerf are no longer the same as they were. Our 55 pteranodon suddenly has the HP point value of 49, and if i try to calculated a 97% imprinted with x hp, that value isn't to be found anywhere near, not 1% higher or lower, they need to get a new formula.

**Comment by Brewfasa** [comment]
Same issue with carbonemy's, their hp also got nerfed, the 55 stats also became 49 stats (in the calculator) Not sure if the imprinting is still correct or may also need a new formula like pteranodons

**Comment by cadon** [comment]
Hi, a new version that considers the new HP-nerf is released.
