### ISSUE TITLE
Settings: Bredding-Multiplier >>Maturation<<

### ISSUE THREAD

**Issue by axi92** [cadon/ARKStatsExtractor#24]
The Maturation multiplier is set wrong I think.
I got in on 1 its about 5h on set it up to 8 (then its over 1 day) and it got more time on the Baby and Maturation time.
But on the serversetting is called "BabyMatureSpeedMultiplier" so if you set this higher the time is faster that the baby will grow up.

**Comment by cadon** [comment]
Hi, thanks. The calculation multiplied the times instead of dividing it. Will be fixed in the next version.

**Comment by cadon** [comment]
Fixed
