### ISSUE TITLE
Can't Add A Bront

### ISSUE THREAD

**Issue by Tivra** [cadon/ARKStatsExtractor#240]
Can't seem to add this bront
Was a wild tame

Server Settings At The Time:
Max wild dinos level: 150
Harvest x2
XP multiplier x1.5
Taming speed x4
Dino food consumption x1
Gestation speed x12
Breeding speed x8
Baby cuddle interval x0.75 and Human food and water consumption x0.5
Decay Multiplier x1.5
Dino Decay Multiplier x2.5

Screenshot
http://s368.photobucket.com/user/Coolagoreelass/media/Untitled_zpsldcx2ky7.jpg.html

**Comment by Tivra** [comment]
Also can't add the offspring, can provide a screenshot of that too if u want

**Comment by cadon** [comment]
Hi, I guess there was also a nerf for the HP of the bronto, so that doesn't work right now. The devs are currently changing the stats a lot, so in the next days that might occur more frequently. I'm updating the data-file when I get the new values.

**Comment by Tivra** [comment]
Thanks, keep up the amazing work

**Comment by Letoric** [comment]
FYI, taming a : 
level 1 bronto with 2300 wild health, ends up at level 1 with 2070.1 health
level 8 bronto with 2760 wild health, ends up at level 12 with 2484.1 health
level 16 bronto with 2760 wild health, ends up at level 24 with 2898.1 health

Not sure if that will help you figure out the multipliers, since it seems they are late on putting out the dev kit, but can't say I didn't try!! :)

**Comment by Letoric** [comment]
I looked in the dev kit for 256.3 and it appears there is a 'Tamed Base Health Multiplier, set to 0.9' which accounts for how the health is turning out now. Does this require a code modification on your side? I don't see where I can set that in the JSON.

**Comment by cadon** [comment]
Yes, thanks for looking that up. Another multiplier, oh my :P

It needs code-adjustments, I'll see if I can release a new version soon. First I have to check which creatures are affected from that.

**Comment by cadon** [comment]
New version with the bronto-nerf is released.
