### ISSUE TITLE
Cannot add Doeds

### ISSUE THREAD

**Issue by Everdyne** [cadon/ARKStatsExtractor#241]
![image](https://cloud.githubusercontent.com/assets/26937699/24722638/56f32044-19f9-11e7-8cdb-e6d6d2a07769.png)

On a private server, but server setttings are correct and multiple people having same issue. Thanks for all your hard work! Cannot live without this app.

**Comment by cadon** [comment]
Hi, sorry for the late reply. Doed was nerfed, I'm still collecting the new data (flyer-nerf etc.).

**Comment by Everdyne** [comment]
No worries! Just wanted to make sure you were aware. :-)

**Comment by cadon** [comment]
New version with the HP-nerf is released.
