### ISSUE TITLE
Cannot add Carbonemys Health stat failing to validate

### ISSUE THREAD

**Issue by Letoric** [cadon/ARKStatsExtractor#242]
http://steamcommunity.com/sharedfiles/filedetails/?id=899780425
Health stat is 5292.1 at level 227, fresh tame. TE was from kibble, 99.??%

**Comment by cadon** [comment]
Hi, do you have changed multipliers on your server?

**Comment by Letoric** [comment]
Hi Cadon,
 The health is not modified, which is the stat in question.
As far as other stats:
 I have weight set with TameAdd 3x, and TameLevel 3x
 I have speed set with TameAdd 2x

Hope that helps. FYI, the dev kit shows that they added a 'Tamed Base Health Multiplier' to the turtle (bronto/doed too) which is set to 0.9, and that accounts for the health mismatch from what I can tell. I haven't spent a lot of time in the dev kit, so maybe you're already familiar with it and coding for it..but I didn't see any way to set it in the JSON, so thought I would throw it out there!

**Comment by cadon** [comment]
Hi, the new release with the new multiplier is released. Thanks again for pointing out this new variable!
