### ISSUE TITLE
Adding Rex - stats not calculating proper

### ISSUE THREAD

**Issue by valarhan** [cadon/ARKStatsExtractor#243]
Snapshot of dino in question
![image](https://cloud.githubusercontent.com/assets/27072415/24829674/29980252-1c2b-11e7-9e65-5635777e98b9.png)
-stat that refuses to 'verify' is the Speed value.

**Comment by cadon** [comment]
Hi, that works for me. Did you check if the OCR did some errors? Lately it's often confused by 5 <-> 6 and / or 3 <-> 8.
The data I extracted is:
Rex (Lvl 257, Impr: 90.72%): HP: 11356.4 (28, 6); St: 1915.2 (28, 2); Ox: 540 (26, 0); Fo: 15595 (34, 0); We: 921.5 (28, 0); Dm: 533.3% (34, 23); Sp: 174.3% (28, 19); To: 24465.8 (206);
