### ISSUE TITLE
Cant add pteranadon and doed

### ISSUE THREAD

**Issue by cocoonish** [cadon/ARKStatsExtractor#245]
![raccoon](https://cloud.githubusercontent.com/assets/27086243/24831494/f9404542-1ca2-11e7-8cf2-62678d73b8a8.PNG)
![doed](https://cloud.githubusercontent.com/assets/27086243/24831495/f94067fc-1ca2-11e7-82dc-fcceb01d0d72.PNG)

idk if im doing something or or it is just a bug?

**Comment by cocoonish** [comment]
in doed's screenshot, it looks like rex option is selected, but doed option is selected. idk why it says rex, i tried again lol :)

**Comment by cadon** [comment]
Hi, the stats of some species (flyers, doed, bronto, maybe some others) were changed. I'm still gathering the data of the new values.

**Comment by Letoric** [comment]
Hi Cadon,
 It seems as though the json incorrectly lists the health modifier for bronto, and some others 0.19 for the 2nd modifier, and that's been 0.2 for a bit as far as I can tell. Is it possible there were some mistaken edits to the json before it shipped out? I haven't been backing up my json, but I know when I entered brontos on 3/29 and 3/27, they entered successfully, if that's any help.

**Comment by cadon** [comment]
New version with the new multipliers is out.
