### ISSUE TITLE
Ankylo stats failing to validate

### ISSUE THREAD

**Issue by funkonline** [cadon/ARKStatsExtractor#246]
I have tripled checked the stats inputted and they are all correct but the sum is not validating.

![image](https://cloud.githubusercontent.com/assets/4774830/24833779/79dac56a-1ccb-11e7-9485-3baa06def8df.png)

**Comment by cadon** [comment]
Hi, if a stat is yellow, you have to choose from the available options (click on the yellow stat and choose in the right list). In this case, changing the weight-stat to 36, 13 yields a valid combination:

Ankylosaurus (Lvl 269, TE: 99.2%): HP: 4340.1 (26, 0); St: 682.5 (29, 0); Ox: 660 (34, 0); Fo: 13785.6 (30, 0); We: 653.6 (36, 13); Dm: 511.1% (29, 40); Sp: 150% (31, 0); To: 5838.5 (215);
