### ISSUE TITLE
[Feature Request] Custom Dinos

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#247]
I would like to use mods that add dinos or change dino stats, but the only thing holding me back is that this program is only using vanilla data.

Can we maybe add our own dinos, or, if it is possible with the 'values' file, how would that work?

**Comment by Letoric** [comment]
Here's a copy/paste from his response to the Classic Flyers post, which may help you work through it.

"It's already kind of implemented. You only need a json-file with the content of
{"species":[{"name":"Pteranodon","statsRaw":[[200,0.1],null,null,null,[1000,0.08,0.9,0,0]]},{"name":"Quetzal","statsRaw":[[200,0.1],null,null,null,[1000,0.08,0.9,0,0]]}]}
(these values are not the correct ones for the mod, just as an example), and load them via File -> Load additional values. All values that are null or left, stay the original ones from the official servers. Order of the stats is: Base, wildLevel, tamedLevel, tamingAdd, tamingAffinity. The stat's order is HP, St, Ox, Fo, We, Dm, Sp, To."

**Comment by cadon** [comment]
Thanks Letoric :)
I wrote a short tutorial how to create such a file here: https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values
