### ISSUE TITLE
Issue with multiple dinos HP stat showing red!

### ISSUE THREAD

**Issue by michaellaughter** [cadon/ARKStatsExtractor#248]
I have been trying to put in many of my new dinos for breeding and roughly 7-8 of them keep telling me that the HP stat is wrong. I have included one photo but I can get more.

![image](https://cloud.githubusercontent.com/assets/27217687/24864965/d426657a-1dd3-11e7-94c6-758a13719dad.png)

**Comment by cadon** [comment]
Hi, update to 0.22.4, the issue is solved there.
