### ISSUE TITLE
Extraction failed

### ISSUE THREAD

**Issue by kofler92** [cadon/ARKStatsExtractor#249]
Extraction of stats failed on a lv224 Pteranodon!
During the tame the server was really laggy... Any possible solutions to that ? What is the problem here?

Best Regards
Christof

![capture](https://cloud.githubusercontent.com/assets/27206614/24870303/2a0f14fe-1e16-11e7-9615-e46d2819c41c.PNG)

**Comment by cadon** [comment]
Hi, are you on an unofficial server? Did you check if all the multipliers are correct? Is the total level really 224?

**Comment by kofler92** [comment]
Hello, no it is an official server primitiv plus. Yeah the stats and the level are correct. As mentioned the server was super laggy during tame. 
Do you know where to check the multipliers on the official server ?

Best Regards

**Comment by kofler92** [comment]
The next Pteranodon failed now... 
![capture](https://cloud.githubusercontent.com/assets/27206614/25066449/f51b871e-2225-11e7-9a3c-36af9d0af297.PNG)

**Comment by kofler92** [comment]
I could solve the problem by using an older json file ... Is there any table which shows me what json file should be used for which version of the game? By the way i am gaming on the ps4..

Regards

**Comment by cadon** [comment]
Hi, sorry for the late reply and thanks for the feedback! Mostly the consoles are some versions behind the pc-version. You can see for which PC-version the values-file is at the very beginning or at the bottom in the tool. Currently there's no list of version to use for the different console-versions.
