### ISSUE TITLE
Suggestion: Show maximum Level of tamed/breeded dino

### ISSUE THREAD

**Issue by LeylaArk** [cadon/ARKStatsExtractor#25]
Heya. I like the "Stat Testing" window. But it would be really cool to see how high I can pump my dino, also to check how I will spread the levels I can do.

There is a maximum number of domesticated levels you can do. I don't know the exact number, but it is a server setting as far as I know.

So what I want is two things: Display the maximum level of a dino in the library. Cause it is important if you want to consider leveling a dino.  
Second, I want to see the maximum level in the "stat testing" if I have chosen a dino of my library. And I want the dom level boxes thingy to stop when maximum level is reached, go red or something. I guess you understand what I mean.
To see the "current level" of a dino with the given statspoints when I chose a library dino in that testing window would be cool too.

**Comment by cadon** [comment]
Hi, sounds cool. I'll add it in the next version.
