### ISSUE TITLE
No Issue just a Question. Alphas and Stuff

### ISSUE THREAD

**Issue by bNarFInfe** [cadon/ARKStatsExtractor#250]
Since i am playing a lot Extincore lately are you planing to update the Extractor recognising Alphas Broodmothers and Drakes?

**Comment by cadon** [comment]
Hi, is this a mod? You can add modded species with an extra file, see here for more details: https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values

**Comment by bNarFInfe** [comment]
[](http://steamcommunity.com/sharedfiles/filedetails/?id=817096835&searchtext=Extinction+Core)
Yes its a mod

**Comment by cadon** [comment]
For infos on how to create a file for a mod, see the [wiki](https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values).
