### ISSUE TITLE
Problems with Adding Imprinted Dinos

### ISSUE THREAD

**Issue by Tivra** [cadon/ARKStatsExtractor#251]
Hi just wondering if u could help. I'm can't seem to add a dino into my Library once it has been imprinted. It's fine before hand, but after it keeps coming up with error messages (Direbears btw). I have double checked and all the stats are correct as are all the settings. 
I have waited until the server has been saved and restarted and it's still not working.

Any suggestions on what else I can try.

**Comment by cadon** [comment]
Hi, sometimes the game doesn't update the imprinting-bonus for a stat, then you've to wait some days or update a stat. What is the error-message that comes up?

**Comment by Tivra** [comment]
Says extraction failed: common issues

**Comment by cadon** [comment]
If it's only for the imprinted creatures, check if the BabyImprintingStatScaleMultiplier is set correctly. Also do you have the latest version 0.22.4?

**Comment by Tivra** [comment]
Yeh it's only for imprinted creatures. I've checked with my servers admins and I have the correct settings. Just downloaded the latest version and I'm still having the same problem.

**Comment by cadon** [comment]
Was one of the BabyMatureSpeedMultiplier or BabyCuddleIntervalMultiplier changed recently? That's the only thing that can explain it then.

**Comment by Tivra** [comment]
Yeh it was changed to what it is now for an event has changed again since

**Comment by cadon** [comment]
What I know so far is that for the extraction the values have to be like they where when the creature hatched / was born. If you know the old values, you can try it with these.

**Comment by Tivra** [comment]
Sorry the long time in getting back. I've tried it with the old values and the new values and I'm still not able to add anything that has been imprinted.

**Comment by Tivra** [comment]
This is a link to the server
http://steamcommunity.com/groups/nerdsevolved

**Comment by cadon** [comment]
Hi, what were the old values? The link says: matureSpeed=4; cuddleInterval=0.75. Are these the values that were valid when the bear was born?

**Comment by Tivra** [comment]
Thanks will have to try again the only values that changed were mating interval, Gestation speed, Breeding speed. But all those settings were changed when I tried extraction.

At the moment we are having to move server to another one in the cluster hopeing that may help

**Comment by cadon** [comment]
I'm closing this for now. If the issue persists, feel free to reopen.
