### ISSUE TITLE
Ptera extraction

### ISSUE THREAD

**Issue by TheWhiteRussian** [cadon/ARKStatsExtractor#252]
Can't get any of my bred pteras to extract
![ptera 230](https://cloud.githubusercontent.com/assets/17101104/24888915/0095644e-1e24-11e7-839f-04d979c2b314.jpg)

**Comment by TheWhiteRussian** [comment]
![ptera 217](https://cloud.githubusercontent.com/assets/17101104/24888984/901de5a0-1e24-11e7-8f62-6dec898042a6.jpg)

**Comment by cadon** [comment]
Hi, you're using an outdated version, the latest release has a fix for that.
