### ISSUE TITLE
Can't "Add New to Library"

### ISSUE THREAD

**Issue by Sando999** [cadon/ARKStatsExtractor#254]
Hey cadon, super pumped to use the tool but cant seem to get it to work.  I have the latest as of today, having some problems with the OCR but manually working around that.  Main problem is I cant "Add new to library" once i get stats in.  Also having problems getting the right wild and dom numbers but im wondering if that cause the server im on (unofficial) is tweaked.  I have asked the admin for settings file.

heres my screen

https://www.dropbox.com/s/4yk4jcoo2vj7fg4/breed1.PNG?dl=0

Any insight why I can't "Add new to library"  button is greyed out.

Sando

**Comment by wmrojer** [comment]
You have stats that are red, meaning they cant be decoded. Click the button named "Stat boxes are red: Online-help"

**Comment by cyberangel67** [comment]
The OCR is an experimental feature at the moment and is not 100% accurate, if you read the extract values you will notice that the red ones have not been read correctly. Once you adjust those values, you will have no issue going forward.
