### ISSUE TITLE
Species sometimes not really chosen

### ISSUE THREAD

**Issue by darthginger** [cadon/ARKStatsExtractor#256]
I do the following quite often:
1. Open Dino inventory
2. Click "Read Values from Ark Window"
3. Everything gets read in correctly
4. red fields...
Then i just click the dropdown menu for Species and click the Species that was already correctly chosen and hit Extract Level Distribution -> all fields green.
I figured this out because when this happens with water dinos it doesnt disable the oxygen field even when Species is scanned correctly at first. Then after clicking it the field gets disabled as it should.

**Comment by cadon** [comment]
Hi, thanks a lot for mentioning that! I'll look into it. There were some strange cases when the oxygen was not enabled/disabled correctly, looks like that's the reason.

**Comment by cadon** [comment]
Should be resolved now. See also #272.
