### ISSUE TITLE
OCR doesn't work

### ISSUE THREAD

**Issue by nomind9** [cadon/ARKStatsExtractor#259]
it took me a long time to figure out how it works..bu the latest updates from ark are preventing me from figuring out how to use smart breeding again.  im not a pc geek so i need some help. when i open the inventory and click on the extract values from ark window or  extract level distriution....it does nothing . any and all help would be greatly appreciated.  also , i play on an official sever.

**Comment by cyberangel67** [comment]
A couple of things to try, is the game running in full window or screen mode and the resolution is one of the currently supported resolutions for OCR.

**Comment by nomind9** [comment]
yes.. im in fullscreen windowed and 1920 x 1080

**Comment by nomind9** [comment]
i think its the server settings.. or the UI but im not sure. like i said... i had it working.. i watched all the videos and read all online stuff to make it work. and it did. after the new ui came out i havent been able to get it to extract.

**Comment by cyberangel67** [comment]
probably the server settings, while the OCR is not perfect you do have to double check what it says the stats are and what they actually are too.

**Comment by nomind9** [comment]
ya, i know that. so how tdo i confirm that the 'official sever' settings are correct?  and is there a way to see if the OCR is working or that i have it set up right cause it doesnt read the stats at all.  ive tried numerous tames , fresh tames, breed dinos.. newly breed ~ before imprints.. i have to imput all the stats ... maybe ..maybe itll work.

**Comment by cyberangel67** [comment]
Official Server settings are the default values, so if you have made changes there is a button to set it to default values. You can tell if the OCR is no picking things up correctly, by double checking the stats it has read with what the stats of the Dino has.

Couldn't be much simpler than that.

Other things to take note, if this is a Bred Dino and whether you have the correct TE and level and other things like selecting the Since Server Restart, sometimes you need to remove that check and other times it is needed for new new Tames.

**Comment by nomind9** [comment]
the thing is..its not reading the stats..

**Comment by Yuuriny** [comment]
Got exactly same problem :)

**Comment by cadon** [comment]
Hi, probably the game-resolution is not supported. There's an issue that even when the resolution of the game and the screen is set to 1920×1080, the tool somehow get's screenshots with a different resolution and then it can't read it at all.

You can look at the OCR-tab in the tool, sometimes there's a message why the reading didn't work.

Thanks @cyberangel67 for helping out!

**Comment by cadon** [comment]
The OCR is slightly improved and adjusted for the new ui-font.
