### ISSUE TITLE
Adding Terror Bird - Doesn't like the Health stat

### ISSUE THREAD

**Issue by MarcOrtego** [cadon/ARKStatsExtractor#260]
It does not like the Health of the Terror Bird.  I set the multipliers according to what the admin said.
Thanks in advance for any help!  :)

![shootergame_2017-04-15_13-46-15](https://cloud.githubusercontent.com/assets/27581933/25066713/380d914a-21e3-11e7-999c-a32765ee9b10.jpg)
![ark smart breeding_2017-04-15_13-55-04](https://cloud.githubusercontent.com/assets/27581933/25066714/3bb24f3e-21e3-11e7-9c2c-62ee0a32a392.png)

**Comment by cyberangel67** [comment]
I am not aware that you could even change the max number of tamed level ups

**Comment by VolatilePulse** [comment]
Closing due to outdated information and lack of follow-up. Numerous enhancements have made the extractor better and have likely since resolved this issue.
