### ISSUE TITLE
Finding the dino stat values to make a custom Json file

### ISSUE THREAD

**Issue by NachoArcade** [cadon/ARKStatsExtractor#262]
I am well aware the issue of creating a Json file has been discussed before, and I understand the turotial posted by Cadon, but what the tutorial doesnt tell us is where to find these values. Where do we find the stat values on the dinos we want to add in? Cause one thing is for certain, I cannot create the Json file if i do not know how to find the information to create it.

Any help would be appreciated

Nacho

**Comment by cyberangel67** [comment]
Not sure what stats you're talking about. If you're referring to the Dino's stats for health etc., they come from the Ark SDK.

**Comment by NachoArcade** [comment]
I realise by now that i shoudlve specified im specifically talking about creating said Json file for Extinction core so that ArkSmartBreeding works with the mod extinction core. As for the specific stats im talking about:

https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values

The real question is just how to get said values of for instance an alpha anky. So what im asking for here is, where do i find that info?

**Comment by cyberangel67** [comment]
All those values come from the Ark SDK, the only thing is I am not sure if Extinction is in the SDK or not.

**Comment by cadon** [comment]
Hi, the best way is to ask the creator of the mod if they can send you the values. Another way is to create a spreadsheet, (force-)tame a lot of the dinos and find out their values this way, but it's cumbersome.

**Comment by floofnsweet** [comment]
How would you pull these values from the Ark SDK?

**Comment by cadon** [comment]
Hi @floofnsweet, for the vanilla creatures the data can be found in the files `DinoCharacterStatusComponent_BP_[Creature]` where `[Creature]` is specifying the species (it's not always called exactly like in the game). Some numbers for taming (e.g. needed affinity) are located usually in a file called `[Creature]_Character_BP`. If you have access to the devkit-mod-files, you might find them there.

The easiest way is to ask the creator of the mod if they can send the data, though.
