### ISSUE TITLE
[Bug] Auto loading file when deleting a dino causes dino to be undeleted by second client

### ISSUE THREAD

**Issue by vanstinator** [cadon/ARKStatsExtractor#263]
I started sharing my XML DB with my tribe today via dropbox after some months of using it. Overall with auto load and auto save turned on it works quite well. There's one pesky bug I've found though 

Bug: When deleting a dino on one client if another client is open it auto loads the change, saves the DB _WITH_ the deleted dino, and uploads again. The first client now has the recently deleted dino in its library again.

Steps to reproduce: Open 2 clients that use the same ark DB. Ensure auto load and auto save are turned on for both clients. Delete a Create in one client. Observe the second client register the change, save, and the first client load the newly saved DB. The first client should now show the deleted creature again.

This isn't a _huge_ problem as we don't often delete things but when we do it's now impossible if more than one client is open.

**Comment by cadon** [comment]
Hi, this is a known bug/feature/annoyance. The tool cannot know if a creature it hasn't loaded itself is a newly added one or a just deleted one, so it assumes the former. If you have a clever idea on how to solve this, I'm open for suggestions :)
