### ISSUE TITLE
What is the max graph setting for?

### ISSUE THREAD

**Issue by Dragnier** [cadon/ARKStatsExtractor#265]
I can't find any instructions or explanations of this setting in the wiki or the app.

**Comment by cyberangel67** [comment]
It is the Stat Chart on Stat Testing max boundary

**Comment by cadon** [comment]
It's the max level for all the charts in the tool, e.g. the colored bars under the stats, the radar-chart or the colors in the library. If you set the max-graph-level to 10, all numbers of 10 or more are displayed green and have the maximum lenght. If you set the max-graph-level to 1000, levels of 10 are displayed red and have very small bars.

This value does only affect the visuals, it doesn't interfere with any calculations, so you can set it to a value that makes the graphs for your library good-looking. Usually it's good to set the value to a third of the max wild level, e.g. on an official server to 50.
