### ISSUE TITLE
Baryonyx calculating incorrectly

### ISSUE THREAD

**Issue by Letoric** [cadon/ARKStatsExtractor#266]
![image](https://cloud.githubusercontent.com/assets/26984630/25309455/3296c5fa-2793-11e7-8361-4b9626641f3d.png)
When input into Ark Smart Breeding, it is not calculating speed levels, even after I change to a different species and change back. 
![image](https://cloud.githubusercontent.com/assets/26984630/25309461/5ea0364a-2793-11e7-916d-a949c9b307ff.png)

Please let me know if there's anything else you need. Server modifiers for stats are:
PerLevelStatsMultiplier_DinoTamed_Add[7]=3
PerLevelStatsMultiplier_DinoTamed[7]=3
PerLevelStatsMultiplier_DinoTamed_Add[9]=2

**Comment by cadon** [comment]
Hi, the speed cannot be calculated for species that have no oxygen. For other species the level of speed is just the difference of the total wild levels and the not used levels, but with e.g. the baryonyx these non-explicite levels are shared between oxygen (even if it has no oxygen-stat is still spends levels in it) and speed and cannot be determined exactly.
