### ISSUE TITLE
Problems inputting bred and imprinted dinos PS4

### ISSUE THREAD

**Issue by SwiftFox2k17** [cadon/ARKStatsExtractor#267]
Loving the app just started using it today, currently adding tamed dinos no problem at all problem arises when I try to input bred imprinted dinos, rex's to be exact.
![dsc_0887](https://cloud.githubusercontent.com/assets/27927514/25316864/cb8a4a0c-2865-11e7-80d5-ae1e91357a77.JPG) 
![dsc_0886](https://cloud.githubusercontent.com/assets/27927514/25316826/3b86ac16-2865-11e7-92d5-2aa1f8a56928.JPG)
![dsc_0885](https://cloud.githubusercontent.com/assets/27927514/25316834/474060f6-2865-11e7-9834-433b08b5d095.JPG)

I run the dedicated Ps4 server and have tried a server restart and double/triple checked settings there all inputted into the app 100%. If you need anymore screenshots or info let me know :)

Thanks SwiftFox2k17

**Comment by cyberangel67** [comment]
Can you do me a huge favour, stop using your phone to take screenshots. Sorry but it irks me when people do this and can't be bothered to rotate the image or it some small image and hard to read.

There is an application called Snipping Tool that has been a part of Windows for a very long time, you find it very easy to use and quicker than reaching over to your phone downloading the image and then uploading it.

**Comment by SwiftFox2k17** [comment]
Thats all good for pc but not all shots are from pc and the images uploaded that way, click them and they will be the right way round. But ill keep your recommendation in mind.

**Comment by cyberangel67** [comment]
I have no issues taking a screen shot on the Xbox and uploading it here.

**Comment by cadon** [comment]
Hi @SwiftFox2k17 , it seems the stat-multipliers are not yet correct. Also, in your second screenshot with the tool, there's Achatina as selected species. Sometimes the tool doesn't recognizes the correct one, so make sure it's the species you want to extract.
