### ISSUE TITLE
Does read values from window work with the new UI

### ISSUE THREAD

**Issue by PikeyMcfloggingtosser** [cadon/ARKStatsExtractor#268]
Ever since new UI I can't get anything to work, is that normal now or is there other people getting it to work with new UI.

I have the recommended resolution and windowed fullscreen. Worked last time I played ark a few month ago with the old UI.

**Comment by blwinfrey** [comment]
I am experiencing the same issue even after the latest update. I play on a unofficial server with the classic flyers mod and even after downloading the Jasonfile  it still doesn't work. if the person who created this reads this plz plz plz send help lol I love this app and wish I could use it again. aslo if u could make one for iPhone that would be amazing.

**Comment by cyberangel67** [comment]
Yes it does work with the new UI, still has an issue with some text but it is still experimental at that moment.

**Comment by nomind9** [comment]
If you adjust the UI sliders will that stop the OCR from reading the inventory screen? Also, does OCR box need to be 'checked'?

**Comment by cadon** [comment]
There's an issue with the resolution, sometimes the OCR doesn't work even if the game-resolution is set to 1920×1080. The OCR has to be enabled to work. Also the UI-slider that changes the size will prevent the OCR to work.

Other reasons it doesn't work can be:
- Game resolution is not set to 1920×1080
- Window-mode is not set to Fullscreen-windowed

**Comment by blwinfrey** [comment]
Mine is set at 1920x1080 and ui slider is maxed and I still cannot extract, and if I put in stats manually still doesn't work ? I have uninstalled and reinstalled this 10 times and same issue , I love this app and it makes me sad I can't use it . To the creator you are awesome and plz fix it so I can enjoy your masterpiece again.

**Comment by cadon** [comment]
Hi @blwinfrey, the ocr and the extraction are two different things. If the extraction does not work, it's probably because of the classic-flyers-mod, the current file seems to be not quite correct. See #244 for more infos, the guys over there seem to have found the numbers that make it work. I'll include them in the file for download soon. Until then, you can just copy&past the values from there in your json-file.

**Comment by TATTOOGUY** [comment]
yes, we've got them almost all set... I can show here the latest version I have for the pre-nerfed stats.. This can fix the ptera, argent and quetz so far. At least I haven't had any issues adding them once this has been added to the prog. Hope it helps others...

create filename : classicalflyers.json

add the following lines :

{"species":[{"name":"Argentavis","statsRaw":[null,[750,0.1,0.1],null,null,[350,0.02,0.04,0,0],null,[null,null,0.025],null],"doesNotUseOxygen":false,"NoImprintingForSpeed":false},{"name":"Lymantria","statsRaw":[null,[180,0.1,0.1],null,null,null,null,[null,null,0.025],null]},{"name":"Pelagornis","statsRaw":[[210,0.2,0.27,0.5,0],[320,0.1,0.1],null,null,[135,0.02,0.04,0,0],null,[null,null,0.025],null],"doesNotUseOxygen":false,"TamedBaseHealthMultiplier":1,"NoImprintingForSpeed":false},{"name":"Pteranodon","statsRaw":[[210,0.2,0.27,0.5,0],[300,0.1,0.1],null,null,[150,0.02,0.04,0,0],null,[null,null,0.02],null],"doesNotUseOxygen":false,"TamedBaseHealthMultiplier":1,"NoImprintingForSpeed":false},{"name":"Quetzal","statsRaw":[[1200,0.2,0.27,0.5,0],[750,0.1,0.1],null,null,[780,0.02,0.04,0,0],null,[null,null,0.025],null],"doesNotUseOxygen":false,"TamedBaseHealthMultiplier":1,"NoImprintingForSpeed":false},{"name":"Tapejara","statsRaw":[null,[450,0.1,0.1],null,null,null,null,[null,null,0.025],null],"NoImprintingForSpeed":false},{"name":"Fire Wyvern","statsRaw":[null,[400,0.1,0.1],null,null,null,null,[null,null,0.025],null],"NoImprintingForSpeed":false},{"name":"Lightning Wyvern","statsRaw":[null,[400,0.1,0.1],null,null,null,null,[null,null,0.025],null],"NoImprintingForSpeed":false},{"name":"Poison Wyvern","statsRaw":[null,[400,0.1,0.1],null,null,null,null,[null,null,0.025],null],"NoImprintingForSpeed":false}]}

Load these additional values into ARK Smart Breeding app. 

Cross fingers!

**Comment by blwinfrey** [comment]
Wow y'all work quick . Also ty @cado for the reply

**Comment by cado** [comment]
Sure! Happy to help!

**Comment by THBTX** [comment]
I also am unable to capture the correct numbers via the OCR.  I have rez set to 1680 x 1050 and WindowsFullsreen mode selected.  One thing I noticed which may mean nothing; After attempting to "Read Values From Ark", when I tab back to Ark, there appears to be some "flash" like there were two copies of the stats on the screen (or maybe the screengrab itself?).
THB

**Comment by cadon** [comment]
The ui-font was changed, I've updated the tool to adjust for that, it should be better now.

**Comment by blwinfrey** [comment]
When can we expect an updated version? Or a new jason file ? No rush just wondering

**Comment by cadon** [comment]
Doesn't it work? The new version was released around 2h ago.

**Comment by blwinfrey** [comment]
Didn't know it was released

**Comment by cadon** [comment]
closing this for now.

**Comment by blwinfrey** [comment]
Closing what? App still isn't letting me use the extractor maybe I'm doing it wrong or something

**Comment by cadon** [comment]
Hi @blwinfrey, is the OCR / reading-from-ARK not working, or is the extractor not working, even if you input all the values manually? Do you have the latest version with the loaded classicalflyers.sjon loaded?

**Comment by blwinfrey** [comment]
I have the latest one and I have tried to input the numbers manually and tried extracting and it still won't work for me. I play in full screen mode and 1920x1080 . It worked fine before this ui update / flyer nerf. I play on a Classic Flyers server and have put the Jason file in .

**Comment by cadon** [comment]
So it's not an issue of the OCR, but the classical flyers? I.e. the OCR puts some values from the screen in the extractor, but the extraction itself does not work? Can you post a screenshot of a creature that does not work along with the stat-multipliers of the server?

**Comment by blwinfrey** [comment]
Ok I'll upload one later today

**Comment by cadon** [comment]
Importing exported creatures is now recommended over using OCR. There are no plans on improving OCR for now.
