### ISSUE TITLE
Can't extract values from imprinted dinos

### ISSUE THREAD

**Issue by acesplit** [cadon/ARKStatsExtractor#270]
Can't seem to add bred dinos. Have tried Rex and Therizino. See screenshots. Have had mixed results with locking some values that weren't changed but still unable to add.

![arkrex](https://cloud.githubusercontent.com/assets/20708353/25442569/031239c4-2a6b-11e7-9a31-42dbe9af6651.PNG)

![thero](https://cloud.githubusercontent.com/assets/20708353/25442574/056fe7f2-2a6b-11e7-98aa-1f3726caabdb.PNG)

**Comment by cadon** [comment]
Hi, sometimes it takes a day or two after the game does display the correct values. If you're on an unofficial server, make sure the BabyImprintingStatScaleMultiplier is set correctly.

**Comment by arathein** [comment]
I'm 
![asb_breddinoissue](https://cloud.githubusercontent.com/assets/28239481/25569182/85d6ba5a-2dd7-11e7-8489-1181d061914a.png)
having the same issue and there have been multiple server restarts since these dinos were born

**Comment by cadon** [comment]
Hi @arathein, in your case it's most probably a wrong setting of the BabyCuddleIntervalMultiplier and / or the BabyMatureSpeedMultiplier. It could be the settings have to be set to the values they had when the Rex hatched, even if these multipliers were changed in the meantime.

**Comment by acesplit** [comment]
Cadon - thanks for your help. It was the stat multiplier value!

**Comment by arathein** [comment]
@cadon So I am on an official server. So if these critters were hatched saying during the Valentines day, or an Evo when they do 1.5 maturation they would error out?  Is there any way to manually put in the maturation?
I don't the one pictures falls into either of those, though it would be good information to know.  This rex was hatched when imprinting was out but breedlines hadn't been pushed yet.  Just trying to see if there is a way to work around it, if not then thats cool I can always breed and see what comes out :)

**Comment by cadon** [comment]
Yes, then the extraction probably fails, because the multipliers were different. Just try to set the multiplier and see if it's working.

**Comment by ancilla-x** [comment]
@cadon  Hi, hijacking this thread instead of starting a new one, would you say it's best to add the dinos when bred into the program only when they've been fully imprinted? For example, would I enter a new baby as soon as it's born, even though I will gain extra stats from imprinting?

**Comment by cadon** [comment]
Hi @ancilla-x, that shouldn't matter. You can always edit a creature in the tool and set the imprinting later if it changed.
