### ISSUE TITLE
Error with updated ARK.Smart.Breeding_0.22.4 app

### ISSUE THREAD

**Issue by WhiteRiderDeath** [cadon/ARKStatsExtractor#271]
Can any one help identify the issue with a fix for the latest app update.

![image](https://cloud.githubusercontent.com/assets/28096578/25480393/c65006f6-2b87-11e7-8344-2e745e1756a9.png)

**Comment by cadon** [comment]
Hi, maybe your .NET-version needs to be updated to version 4.5. Usually it's preinstalled, you can download it here: https://www.microsoft.com/en-us/download/details.aspx?id=30653
