### ISSUE TITLE
Can't add dinos with no oxygen stat

### ISSUE THREAD

**Issue by Tivra** [cadon/ARKStatsExtractor#272]
Since I installed the last patch/update I can no longer add dinos that don't have an oxygen stat. I have the "Enable Oxygen For All Species" unchecked. I have tried checking it saving and closing program, restarting and unchecking then closing and opening again. Still not working, am I doing something wrong?

**Comment by cadon** [comment]
Hi, is the oxygen stat enabled in the extractor for creatures that have no oxygen? E.g. can you enter a value for oxygen for an Ichthy?

**Comment by arathein** [comment]
@Tivra one thing I found is that if I had just entered or pulled up a critter that has an o2 stat, then switch the drop down box to something like Carbo (Turtle) the O2 stat entry remains, but I also realized I was not on the extractor.  If you are on the extractor tab then click to another tab, then click back and O2 should be greyed out.

**Comment by Tivra** [comment]
Yes Cadon i can enter the stat for oxygen for all creatures despite having "Enable Oxygen For All Species" unchecked.

Thanks arathein i will try that

**Comment by Tivra** [comment]
Well that seems to be working, squishes so much for the tip arathein

**Comment by cadon** [comment]
Thanks alot @arathein , that was probably the reason, it'll be fixed in the next release.
