### ISSUE TITLE
TRP Rates

### ISSUE THREAD

**Issue by Mistergamer811** [cadon/ARKStatsExtractor#273]
![20170501151657_1](https://cloud.githubusercontent.com/assets/26526790/25592140/9c490d66-2e85-11e7-9346-f11440da769f.jpg)
I can't get the multipliers out of the admins, and I don't fault them, but I want to use this app on the server, could someone help me figure out the rates.  Would be appreciated

**Comment by cadon** [comment]
Hi, that's a tough thing to do. You could try often used multipliers (1, 2, 5) for the stat-multipliers, another way is to knock out many level 1 creatures, level them and check their increases. It's probably a cumbersome task, but you might be lucky with some probable guesses on the numbers
