### ISSUE TITLE
OCR Custom Config for 4k

### ISSUE THREAD

**Issue by Cacharoes** [cadon/ARKStatsExtractor#274]
Is it possible to configure the OCR for a 4K resolution because it seems like the OCR is capped at size 20 font and 4K text for the stats seems to require the detection blocks to be 26 or 27 tall, or perhaps I am just confusing how to do the configuration.

**Comment by cadon** [comment]
Ah yes, I haven't considered such a large resolution. Are you really playing it in 4k O_o? I'll increase the size of the letters.

**Comment by Cacharoes** [comment]
My monitor is 4k, due to performance and optimizations I play Ark at 1080p but the OCR does not work unless I set the monitor to 1080p as well which looks funny on a non native display.

**Comment by cadon** [comment]
Hi, the letter templates can now have a size of up to 31x31 px.

**Comment by Cacharoes** [comment]
My font size still seems to be stuck with 20 as the highest, and i have replaced the files several times now, unless I am mistaking what is suppose to go up to 31 now.

**Comment by cadon** [comment]
Sorry, I forgot to increase the number-input. I'll write here again, when the fixed version is released.

**Comment by cadon** [comment]
Sorry for the delay, the font-size finally can be increased to 31.

**Comment by focabr** [comment]
@Cacharoes Were you able to calibrate OCR for 4k?
I can not calibrate.

@cadon Voce tem um OCR calibrado para 4k?


![2017-06-21 20_08_27-ark_ survival evolved](https://user-images.githubusercontent.com/4109361/27410641-3083aeb2-56bf-11e7-9ef1-f1691ef2af5d.jpg)

**Comment by Cacharoes** [comment]
I was not able to get it to work even with the adjustments, I figured it was because the Calibrate from font option is still locked at size 20, and ended up giving up, since Cadon closed it.

**Comment by cadon** [comment]
Hi @Cacharoes , sorry, I assumed everything was working now, but forgot about the calibrating-from-input.
However, this input is only needed if you have a text-font that is used as a starting-point, usually manual adjustments still have to be made. Creating templates should already work. The missing input will be fixed in the next release.

Hi @focabr , what does not work with the calibration?

**Comment by focabr** [comment]
Hi, 

My error is the calibrated for this font-size error.


![untitled](https://user-images.githubusercontent.com/4109361/27985100-0edf0960-63bb-11e7-8a92-7651415e1eac.jpg)

**Comment by cadon** [comment]
This means there are no character-templates for this font-size. See https://github.com/cadon/ARKStatsExtractor/wiki/OCR how you can create the templates.

**Comment by cadon** [comment]
Using import exported is recommended over OCR. Currently there are no plans to improve the OCR.
