### ISSUE TITLE
Please create setting for level increments

### ISSUE THREAD

**Issue by Wardjp** [cadon/ARKStatsExtractor#276]
When extracting levels, your server is always going to increment based on whether it's difficulty 1, 2, 3, 4, 5, or more. I believe it would be of significant help when narrowing down that extraction if we could set a predetermined level increment. Would this be a reasonable/doable setting to add to help players narrow down their dino extractions more effectively?

**Comment by cadon** [comment]
Hi, good idea, but that wouldn't help for the determination. The total level is needed for the extraction anyway, and the stat-levels can have any integer number lower than the total level, regardless of the difficulty.

**Comment by Wardjp** [comment]
I understand, just would be nice if we could narrow the stat-levels down to multiples of the difficulty set to.

**Comment by cadon** [comment]
You mean the total level? That still can have every number, because after taming a level 1 creature you can level it up in steps of 1.

**Comment by Wardjp** [comment]
Negative, when you get the yellow blocks and it gives you the selection box in the middle with the different stats and it'll have the WLvl listed in there. It'll list like 208, 209, 210, 212, 213, 215. But if my server only allows multiples of 5, those other options are just more to sort through. I understand if the task is too monumental or not worth it to do, just thought it was an idea to help with narrowing down the results, if whatever options are given, the program were able to limit to multiples of the server's difficulty.

**Comment by cadon** [comment]
Ah, now I get it. That's a good idea! I'll include it.

**Comment by cadon** [comment]
Feature is included in the newest release. Thanks for the suggestion!
