### ISSUE TITLE
Add Dino Filters to Stat Weights

### ISSUE THREAD

**Issue by Wardjp** [cadon/ARKStatsExtractor#277]
I am looking for different stat weights for different dinos, would it be difficult to break down the stat weights so that I could have like boost health and dmg weights for my rexes, but then a heavily dmg based weight saved to all anky breeding?

**Comment by cadon** [comment]
Hi, you can right-click on the stat-weights to set some presets. The automatic saving per species is not yet implemented. Also see #29.

**Comment by Wardjp** [comment]
Interesting idea, I'll use that for now, thanks! I will say, related to that thread, with what you have now is more than sufficient, the preset per dino is just one of those things where it's nice to have a set and forget. There's so many other things we have to constantly remember to change and adjust between ark and the app and everything else. It's more of a QoL thing where we can determine what settings we want per dino and have that always apply, in case we start working a breeding plan, only to realize we forget to change those presets to those that apply to that particular dino. Btw, I pmed you on Reddit about the idea of a Patreon, @cadon :)
