### ISSUE TITLE
Clicking "These Parents Just Mated" does nothing

### ISSUE THREAD

**Issue by Wardjp** [cadon/ARKStatsExtractor#278]
I have 2 rexes I just mated, when I click this button, it does not initiate a cooldown on the female and a mating count for the male.

**Comment by cadon** [comment]
Hi, thanks for that. It seems as that wasn't yet implemented at all. Will be in the next release.

**Comment by cadon** [comment]
New version with this feature is released.

**Comment by Wardjp** [comment]
Thank you!
