### ISSUE TITLE
Stat problems

### ISSUE THREAD

**Issue by turbo-donkey** [cadon/ARKStatsExtractor#28]
I attempted to add my dinos into the library last night and had lots of problems with the stat extraction, it was particularly bad with the Direwolf for me, picture attached...

![capture](https://cloud.githubusercontent.com/assets/18444998/14498100/3137e17c-0191-11e6-9e8b-b8fe5c1f8422.PNG)

Most of my bred wolves cannot be added.

Official PVE server, official multipliers AFAIK.

**Comment by cadon** [comment]
Hi, in the screenshot you locked the domesticated levels of Melee Damage to zero. Did you never levelup that stat? If you unlock the domesticated levels there, there are possible combinations.

**Comment by turbo-donkey** [comment]
Pretty sure I was trying everything at the point I took the screenshot but I will reconfirm shortly...

**Comment by turbo-donkey** [comment]
Indeed you are right! I obviously had myself in a muddle!

**Comment by cadon** [comment]
Good to hear it's solved.
