### ISSUE TITLE
OCR recognizing multiple digits at once

### ISSUE THREAD

**Issue by Brewfasa** [cadon/ARKStatsExtractor#281]
I've been trying to set up the OCR for my 1440*900 resolution, but it recognizes multiple digits at once since the pixels slightly overlap:

![636384c6c283944dc5a634480ac4536f](https://cloud.githubusercontent.com/assets/20604229/25741943/66910416-318d-11e7-9448-ff5ee4d46bb1.png)

Which results in:
![583334538c65a5fe714f50a63fa98b81](https://cloud.githubusercontent.com/assets/20604229/25741929/526abb12-318d-11e7-9823-8f5985f9930a.png)

Normally you would just type in all 3 digits when it sees those 3 at once, but the program doesn't allow that right now. I dont know how to seperate them myself, the  only solution i would have is allowing the option to just save the characters as 680.

How would you fix this?

**Comment by Brewfasa** [comment]
Here is a fullscreen screenshot of my 1440*900 resolution in case you want to try it for yourself:

![1440x900](https://cloud.githubusercontent.com/assets/20604229/25741834/ece2a796-318c-11e7-8963-5662b68a0ea9.png)

**Comment by cadon** [comment]
Hi, that's an open issue, it's hard to separate these characters if they overlap that much. You could try to increase the white-threshold, so the letters should be separated more. If the threshold is increased too much, the characters itself may vanish, though. The best is to take a screenshot-file, drag&drop it on the OCR-tab and adjust the threshold until you find a good balance.

I'll look on how to separate the characters better and am open for any hints for that.

**Comment by cassfalg** [comment]
Can you give hints to the OCR what the characters should be? Like a regex expression? That might help too. I could probably create those with some pointers to where to apply them and maybe docs/info on the OCR you use.

**Comment by cadon** [comment]
The new version can recognize these concatenated numbers, that improved it a lot. If you have a finished config-file for your resolution, can you post it here?

**Comment by Brewfasa** [comment]
For some reason it program doesn't always take the letter with the highest matching %.
For example:
![e955514d0b92e60814cfdf716348aaa3](https://cloud.githubusercontent.com/assets/20604229/26033473/7bea97ec-38ad-11e7-8db2-233043ecdca9.png)  ![491782f5b74dbc73dac6fd6abc85cea6](https://cloud.githubusercontent.com/assets/20604229/26033476/8fafdb84-38ad-11e7-8615-0a1956898927.png)
As you see, it recognizes it as a 1 at the right, while you see in the 2nd screenshot that the 2 has a higher matching %.. Re-dragging the image into the OCR window doesnt change that either.

The same here:
![49ddf8f933623954fa23e8c085eed128](https://cloud.githubusercontent.com/assets/20604229/26033485/c6cc328e-38ad-11e7-8c47-7dbf06efe496.png) ![1c649c82202566a5f3f9802f8a489040](https://cloud.githubusercontent.com/assets/20604229/26033487/c95c5e70-38ad-11e7-8558-1f93f253d15b.png)

**Comment by cadon** [comment]
Yes, that confused me as well. It's explaned simply: The ocr does check the letter for matches, then shifts the template one pixel to the right and checks again. This double-checking is a main-reason for the improved recognition, as some letters are just shifted. Unluckily, this shifting also introduces new issues. The matching-percentag only shows the matching for the original match, if another letter is choosen, it's because the shifted match was better (which is not shown as percentage).

I'm open for suggestions on how to improve this further.

**Comment by cadon** [comment]
The multiple-character-recognition should be resolved mainly.
