### ISSUE TITLE
Red Stats at Thylacoleo

### ISSUE THREAD

**Issue by MissGaudete** [cadon/ARKStatsExtractor#282]
![thyla wred stats](https://cloud.githubusercontent.com/assets/28447553/25751378/16b66c1a-31b5-11e7-8fa6-c0a75be65997.PNG)

Hey :)
I'm getting red stats with a Thylacoleo. The stats were triple checked, but they are right.

**Comment by cadon** [comment]
Hi, are you on a console or an unofficial server?

**Comment by MissGaudete** [comment]
I'm on PC singleplayer and gave the tool all my multiplier changes.

**Comment by cadon** [comment]
Can you post the stat-multipliers you use?

**Comment by cadon** [comment]
Hi, the ingame-rounding of the Taming-effectivess caused this. The next release will have a better handling for this. For now, here are the stats of this thylacoleo:
Thylacoleo (Lvl 11, TE: 35.8%): HP: 840.1 (1, 0); St: 520 (3, 0); Ox: 220 (1, 0); Fo: 1896.7 (2, 0); We: 400 (0, 0); Dm: 122% (2, 0); Sp: 130% (1, 0); To: 1120.5 (10);

**Comment by cadon** [comment]
Fixed in 0.23.5
