### ISSUE TITLE
Ingame rounding of Imprinting to 100% not handled correctly

### ISSUE THREAD

**Issue by Merick001** [cadon/ARKStatsExtractor#283]
This was one I got a 100% imprint on (and didn't think to capture stats until after of course).  I know the speed wasn't updated because it changed after server reboot.  Attached are the two screenshots of its stats and the tool.
![tool](https://cloud.githubusercontent.com/assets/28489974/25774580/ecc420c0-3257-11e7-918d-8a6afdf7b82a.JPG)
![gigastats](https://cloud.githubusercontent.com/assets/28489974/25774581/ecc4fc66-3257-11e7-99e7-a301a385a93c.JPG)

**Comment by Wardjp** [comment]
Are you on an unofficial? If so, you need to include multipliers and mods that could potentially change these stats from vanilla.

**Comment by Merick001** [comment]
it is an official server - sorry, meant to include that.

**Comment by cadon** [comment]
Hi @Merick001, the ingame rounding causes this, it works if you put in 99.792 % for the imprinting. I'll put it on the todo list to recognize these cases.

**Comment by cadon** [comment]
Fixed in 0.23.5
