### ISSUE TITLE
Red Stats - Argent - v257.4 [v0.23.0]

### ISSUE THREAD

**Issue by randomgbvfdcer** [cadon/ARKStatsExtractor#286]
Hi im getting red stats on a recently tamed Argent. Im on a unofficial PC, Game.ini and GameUserSettings.ini were dragged across to the settings. Taming speed set at 7x, kibble tamed. Flyernerf json was loaded but i dont know what this does or how to adjust (if i even need to adjust it). I just discovered this app and love it - thanks. 
![argent](https://cloud.githubusercontent.com/assets/28006944/25789495/70ca8d30-33f4-11e7-94de-1f2a14d44ec4.PNG)

**Comment by cadon** [comment]
Hi, sorry for the late reply. I tried to reproduce, and it seems it can be extracted with the latest version.
