### ISSUE TITLE
Suggestion: Remember stat weight per species.

### ISSUE THREAD

**Issue by mitzzz** [cadon/ARKStatsExtractor#29]
Remember stat weight set per species instead of universal weights.

**Comment by noheals** [comment]
Also save them in the database.

**Comment by noheals** [comment]
Oh i just found this feature: If you right click in the stat weighting field you can create custom stat weight presets! BUT: they are not saved in the .xml and cannot be shared with friends easily.

**Comment by cadon** [comment]
they're saved in the tool's settings, i.e. somewhere hidden in the windows user-folder, it's all done by the .NET-environment.

Is there really the need for species-specific stat-weights? I see that one species is rather focused on gaining weight, another on HP and damage. Do you guys think it should be saved in the library-file as well?

**Comment by noheals** [comment]
For me personally it would be best if the tool saves the weight for each species seperatly in the xml file.
