### ISSUE TITLE
Extraction failing on Argent with Classic Flyers

### ISSUE THREAD

**Issue by HarrisonPotter** [cadon/ARKStatsExtractor#290]
I have the classical flyers json file loaded as additional values, and am playing on an unofficial where the admin has provided the settings for the program, but the program still doesn't like the health value on my argent. 
in-game http://puu.sh/vLMZc/63237e4ef6.jpg
app http://puu.sh/vLN0S/9792d74761.png
multipliers http://puu.sh/vLN1j/13a46594b8.png

Help is appreciated, still love this program.

**Comment by HarrisonPotter** [comment]
Quick followup, I attempted copying the stats into the tester and re-assigned the health levels until it matched what I had assigned (3 post-tame levels into health) and the value turned out to be 2194.6 instead of what the game showed, so perhaps an issue in health calculation?

**Comment by cadon** [comment]
Hi, it could be the classical-flyers mod was adjusted, I'll put it on the todo-list.

**Comment by Aarondorn2** [comment]
Experiencing the same issue, thanks!

**Comment by cadon** [comment]
Hi, sorry for the late reply. I checked the numbers, and spawned some classicFlyer Argents, they all could be extracted without issue. Did you try to levelup the health? Maybe the number of the HP is somehow still calculated with the post-nerf-numbers and needs a refresh?

**Comment by Aarondorn2** [comment]
I haven't tried it in the past couple days, but when I last checked, I was only having issues with ones that I _had_ leveled health in.  I think the value of health per level is incorrect.

**Comment by cadon** [comment]
Can you post a screenshot of the inventory? And are you using the official multipliers with the classicFlyers-mod or are multipliers changed additionally?

**Comment by cadon** [comment]
I'm closing this for now, if new issues arise with classicFlyers, feel free to open a new issue.
