### ISSUE TITLE
Cannot build due to missing resources

### ISSUE THREAD

**Issue by tsebring** [cadon/ARKStatsExtractor#291]
Hey,

"ARKBreedingStats/Properties/Resources.resx" reference multiple ARKCalibration`nn`.png files in "ARKBreedingStats/Resources/" that are missing in the repository.

Thanks in advance!

**Comment by cadon** [comment]
Hi, these files were removed, they were part of the calibration of the old OCR-algorithm, but not used anymore. They should've beed removed from the resources as well. If you still need them, you can find them in the older commits, e.g. https://github.com/cadon/ARKStatsExtractor/tree/01d8abb28214779b6b84ede6d3beb6ab523773c1/ARKBreedingStats/Resources

**Comment by tsebring** [comment]
They are still in the Resources.resx on the master branch though.
https://github.com/cadon/ARKStatsExtractor/blob/master/ARKBreedingStats/Properties/Resources.resx

**Comment by cadon** [comment]
Oh, I haven't commited that change yet, I forgot it for the last commit. I'll do it with the other changes.
