### ISSUE TITLE
Cannot extract imprinted dinos

### ISSUE THREAD

**Issue by fractalwolfe** [cadon/ARKStatsExtractor#294]
Hi, I'm having issues with extracting imprinted dinos. I've set up the settings properly to match the server config, but the extraction of imprinted dinos anywhere between 0 and 100% fails with the following error, in this case I'm trying to set the imprinting quality to 57% (this is a second generation Thylacoleo):
![image](https://cloud.githubusercontent.com/assets/670705/26025219/362d311e-37eb-11e7-8123-54f0215c59cd.png)

The server settings are:
```
BabyMatureSpeedMultiplier=50.0
BabyCuddleIntervalMultiplier=0.0464
BabyImprintingStatScaleMultiplier=3.0
```

I've noticed however that the app only shows 3 decimals for the cuddle interval, but checking the saved json, the setting is stored correctly. Is it possible that the setting is rounded off when used and thus makes it fail? Here's a screenshot of the settings:

![image](https://cloud.githubusercontent.com/assets/670705/26025192/a80b8052-37ea-11e7-97e1-2cf3a2c5f321.png)

**Comment by cadon** [comment]
Thanks for the report, a fix will be released soon. Currently custom breeding-multipliers are not handled correctly.

**Comment by cadon** [comment]
Release with a fix is uploaded.
