### ISSUE TITLE
Extraiction failed, can't seem to get food and melee at green

### ISSUE THREAD

**Issue by Smokeyboy** [cadon/ARKStatsExtractor#295]
https://steamuserimages-a.akamaihd.net/ugc/832448860123113807/CB4898DE82779518A37A8BDBD57C79D38F29DF62/

I cant seem to get food and melee damage at green. I use latest version of Smart Breeding, filled in the numbers manually (several times). As you can see, the baby is just born so nothing is added yet (no levels and or imprints). I play on official server and haven't changed settings in Smart Breeding. I followed all the steps of common causes (obviously I didn't leveled anything up), but no chances in the extraction.
![sb](https://cloud.githubusercontent.com/assets/28672327/26025735/562a9efe-37ee-11e7-97af-9d57889186ba.jpg)

I can do my first imprint in 2:20 hours. Ill let you know if that helps

**Comment by cadon** [comment]
Hi, in the current version there's a bug with that. A temporary fix is to disable "Consider Wild level steps" in the settings.

**Comment by Smokeyboy** [comment]
Thx for the fast response and solution. This did help indeed :)
