### ISSUE TITLE
Xfering previous app version library to another without error?

### ISSUE THREAD

**Issue by SwiftFox2k17** [cadon/ARKStatsExtractor#298]
Dear Cadon
       Still loving your app, but have come up against an error message switching from 22.4 to 23 and 23 to 23.2.  Im pretty sure its something simple but cant figure out what. I've tried loading the values.json from within the versions folder or from the folder the backup was originally but still get the following error.

![arkextractor error](https://cloud.githubusercontent.com/assets/27927514/26036787/97eb115e-38dc-11e7-8b27-dd017a789bee.png)

**Comment by cadon** [comment]
Hi, the values.json-file is now saved in a subfolder called "json". If you download the application and extract all of the files in a folder, everything is there where it should be.

The error-message you get is related to "additional values" you tried to load. This can be done if a mod is used, like the classical-flyers-mod for example. If you don't use a mod that changes the stat-values, you don't need to load additional values via the file-menu. Only make sure, the file values.json is in the folder "json", which has to be in the same folder as the application.
