### ISSUE TITLE
Melee not calculating on 3 of 4 newborn rexs

### ISSUE THREAD

**Issue by arathein** [cadon/ARKStatsExtractor#299]
Hello - I am on an official server so standard breeding values apply.
I just hatched 4 rex eggs, the first one I put in went in without any issue, but the other 3 wont go in.  They all get a red box on the melee even though it is the same melee as the first one.
"rex255" is the one that went in, the other three are shown with their values in Ark and the app's input.  no inprints have happened as they are just over an hour old.

![rex289](https://cloud.githubusercontent.com/assets/28239481/26048992/02cb6bee-391f-11e7-81b0-c6c6b9e9719c.png)
![rex255](https://cloud.githubusercontent.com/assets/28239481/26048994/02cea034-391f-11e7-9cc5-8a88d47d63f2.png)
![rex268](https://cloud.githubusercontent.com/assets/28239481/26048993/02cd7844-391f-11e7-9800-5f10b095ea5c.png)
![rex282](https://cloud.githubusercontent.com/assets/28239481/26048991/02cae5de-391f-11e7-86af-c4eee2070240.png)

**Comment by cadon** [comment]
Hi, these work for me. Do you have the latest version? (click on ? -> Check for Updates)?

**Comment by arathein** [comment]
Hi cadon - I'm on v 0.23.1 and I just redownloaded it from the site to make sure and I still can't put in the values.  Should I be pulling something other than the zip file?  It does say there is an update when I click Check for updates, which is why I redownloaded.

**Comment by arathein** [comment]
It does say there is an update even though I just downloaded it again

**Comment by arathein** [comment]
UPDATE: Apparently for whatever reason it redownloaded 23.1 this morning, maybe i went to the wrong link.  I just downloaded 23.2 and am good to go.  Thank you for having an awesome app and being responsive.  I'll buy you some coffee :)
