### ISSUE TITLE
Feature request: Multi-column sort in lists

### ISSUE THREAD

**Issue by LeylaArk** [cadon/ARKStatsExtractor#30]
Heya.
It's cool that you have the sort order saved now. That helps a lot. I usually sort by top stats.
But what would be even cooler is when you can sort on multiple columns.
At the moment I guess it's random how list items with the same value are sorted, right?

I guess you know that feature from Excel or other lists already.
For me, I would really love to sort with "Top stats DESC, Tp% DESC" for example. Or sometimes just "Top stats DESC, Name ASC" so that the dinos are ordered alphabetically.

**Comment by cadon** [comment]
Hi, currently the sorting can be done with two columns. In your case, sort the rows by Tp% Desc, then sort them by Top Desc. The resulting order then is sorted by Top and all rows that have an equal value at Top are sorted by Tp%.
