### ISSUE TITLE
Red stats with Bred Rex (scratching head)

### ISSUE THREAD

**Issue by randomgbvfdcer** [cadon/ARKStatsExtractor#304]
Hello, i have a rex which was bred last weekend, an evolution event but not one affecting breeding. I saw in another post about disabling the wild-step up option but deactivating this didn't help. Unofficial server, no levels applied since maturation.
![rex_b241v1](https://cloud.githubusercontent.com/assets/28006944/26247080/8f5a3e0a-3cdf-11e7-8a48-5a8516801ae2.PNG)

**Comment by cadon** [comment]
Hi, it seems your server uses the official multipliers. Click on "Set to official" under the stat-multipliers to set them accordingly.

**Comment by randomgbvfdcer** [comment]
Legend, thanks cadon. All stats green 👍

**Comment by asoldier** [comment]
I have the same issue, All multipliers are input into the application and still getting red stats.

**Comment by cadon** [comment]
Hi @asoldier, please post a screenshot like the one above.
