### ISSUE TITLE
Bad Score for Better Breeding Pair

### ISSUE THREAD

**Issue by ijabit** [cadon/ARKStatsExtractor#305]
![low score](https://cloud.githubusercontent.com/assets/557752/26249947/66465f76-3c76-11e7-8eff-4e15ca271d97.jpg)

Thylacoleo (237) has better stats in every single category, so why would it get such a low score compared to "Missy"? I'm using v0.23.2.

Thanks!

**Comment by cadon** [comment]
Hi, the mode "Top stats conservative" that you've chosen is trying to bring you to the best creature that is possible with your library. The algorithm recognizes if the possible offspring is worse or equal to an existing creature, which would not beneficial to your overall gene-pool. So these possiblities get worse scores. In your case, the female Thylacoleo has already all of the top-stats, so there is no creature that can be better. Your goal, of getting all best stats in one creature is already reached, so the "top stats conservative"-mode is done, it has reached its goal.

For now it's recommend that you choose the Top-stats-lucky- or the High-stats-mode, which will give you rather the pairings for the best possible offspring of a species.
