### ISSUE TITLE
OCR 2560x1600

### ISSUE THREAD

**Issue by Methos2178** [cadon/ARKStatsExtractor#306]
Hello,

I have created a custom OCR for my above resolution, and it is working rather well. My issue is the Food, Weight, and Topor is being recognized correctly, however when using extractor it is using the current Food, Weight, and Topor instead of the max. 

1. Should the label box cover both current/max or only the max?
2. For the name should the box cover the entire name or just the "()"?

 Thanks!

**Comment by cadon** [comment]
Hi,
1. the max-value should be sufficient, but reading both values should work as well
2. including the whole name is better, then the tool can also recognize the given name

If the config-file works well, you can send the file to me and I'll include it in the next release for other users, if you want.

**Comment by Methos2178** [comment]
So doing just the max won't work. A dilo that has 100 health (only 3 chars) versus a rex with 90k (6 chars) there are too many numbers to properly box. 

I haven't been able to figure out this problem: i go into the OCR tab and it reads the weight as 20.0/235.1 which is perfect, but when i go to extractor it is using "20.0" as the weight instead of the "235.1" any ideas how to fix this?

**Comment by cadon** [comment]
Hi, is it exactly `20.0/235.1` what is written in the OCR-log for the weight? Can you post the screenshot that caused this behaviour?
I'll increase the possible font-size in the next release.

**Comment by Methos2178** [comment]
Thank you for increasing the font size in the next release.
It is exactly right in the OCR-log. I have attached the 2 screenshots below. Thanks for looking into this.

Also, is there a way to make it ignore the gender symbol in the name? As you can tell it breaks it up into many characters.

![capture 1](https://cloud.githubusercontent.com/assets/28817295/26284557/fa9916bc-3e03-11e7-8f80-f86ff92b3d9e.png)
![capture 2](https://cloud.githubusercontent.com/assets/28817295/26284556/fa986b5e-3e03-11e7-909b-8ee3a376111d.png)

**Comment by cadon** [comment]
Import exported is recommended over using OCR. There are currently no plans on improving OCR.
