### ISSUE TITLE
ToolTip Incorrect.

### ISSUE THREAD

**Issue by UberSlackr** [cadon/ARKStatsExtractor#307]
In settings on the Multipliers Tab, the ToolTip for WildLevel says "PerLevelStatsMultiplier_DinoTamed"
For TameLevel it says "PerLevelStatsMultiplier_DinoWild"

Or the Column header is backwards.

**Comment by cadon** [comment]
Hi, thanks for the report. The tooltips were wrong, I'll fix it in the next release.
