### ISSUE TITLE
ARK extractor not working for my rex

### ISSUE THREAD

**Issue by stijni20** [cadon/ARKStatsExtractor#308]
![image](https://cloud.githubusercontent.com/assets/28830964/26279233/6889b4d4-3dae-11e7-98f4-7b247b145b02.png)
![image](https://cloud.githubusercontent.com/assets/28830964/26279234/6d949b10-3dae-11e7-9948-543ab20eca08.png)

Two images, the stats dont show up with nice colours and dont get recognized.

Thanks for your help

**Comment by Methos2178** [comment]
Manually correct the torpor value and it should work. You will have to make choices on the stats that are yellow to indicate where you applied levels after taming.

**Comment by stijni20** [comment]
Thanks a lot, i was a nub and maybe a little blind.

Loving the software now, although I dont get it to work for my Quetzel unless I have to believe myself for upgrading his food stats xD
