### ISSUE TITLE
Identifying mutations. 

### ISSUE THREAD

**Issue by ancilla-x** [cadon/ARKStatsExtractor#309]
![image](https://cloud.githubusercontent.com/assets/25284960/26279447/38dedff4-3dac-11e7-87ff-ac2284b5d63b.png)

Firstly, just a thanks for the usefulness of this program and for your regular updates... Now my issue is that, if you refer to my screenshot attached, is that a mutation on the top dino, in HP? I'm relatively new to breeding and as such, don't really know for sure, however it doesn't auto update the mutations integer to indicate that it is. Is it something I would need to identify and update manually? Thanks,

**Comment by cadon** [comment]
Hi, if the listed creatures include the parents of the first one, it's a mutation in HP. An offspring cannot have different stat-levels than its parents, except it's a mutation. Currently a mutation also means exactly two more levels in a stat.

The tool cannot say for sure if a stat is mutated in all cases, so it's not an automatic process, you have to identify and set it manually.

**Comment by ancilla-x** [comment]
Hi mate sorry to comment again, so it looks as though that HP stat is mutated, would I just edit the dino and select "1" mutation?

**Comment by cadon** [comment]
No problem! Yes, just adjust the counter manually.
