### ISSUE TITLE
Feature request: Make dinos (temporary) hideable from Breeding Plan

### ISSUE THREAD

**Issue by LeylaArk** [cadon/ARKStatsExtractor#31]
Heya.
Aaand another feature request from me :blush: 

I have a small problem with the Breeding Plan. It's so cool and helpful, but for example now I've bred some Quetzals. 8, to be honest xD And all have great stats. But they are still babies. That means I can't mate them. But the whole list ist clustered with suggested pairing with those Quetzals. So I can't find pairing that I really can do at the moment.
The workaround would be to mark them as "unavailable" in my library, but that can't be the solution.
Same goes for multiple pairings that I want to mate. I have a very good female in a species. That means nearly all of the suggestions are other males mated with her. But she can only mate once, and I want to get other pairings, that may be a bit lower, but still can have good stats.

So I don't know how far you thought to improve your tool. Adding babies with an automatic timer when they will be matured, etc.

But that's not even needed. For me, it would really help to make Dinos in a pairing "excludable" for the new Breeding Score calculations. Doesn't need to be saved, just as long as I have the tool open, so that I can see other pairings.

Is it understandable what I mean? xD

**Comment by cadon** [comment]
That sounds very useful, thanks for the suggestions! I'll add it in a next version.

**Comment by cadon** [comment]
Creatures can now be set to a cooldown, which ignores them in the breeding planner until the timer has finished.
