### ISSUE TITLE
Can't use Extractor or OCR after UI update

### ISSUE THREAD

**Issue by khova** [cadon/ARKStatsExtractor#311]
Hey, 

I can't extract at all, it just minimizes the app and does nothing. I saw a similar issue posted and I have the same error;
Error while calibrating: probably game-resolution is not supported by this OCR-configuration.
The tested image has a resolution of 1680×1050 px.

However I can't drag screenshots to the OCR. Nothing happens.

My setting for my rez is 1920 : 1080, full-screen windowed and no scale.
I'm on a private server but no stat alteration mods. 

Thanks for the app its been great. I would love to be able to use it again!

**Comment by cadon** [comment]
Hi, do you use 1680 x 1050 as resolution in windows? Probably you need a OCR-config-file for this resolution. You can try to create one yourself, it's explained here: https://github.com/cadon/ARKStatsExtractor/wiki/OCR
It's planned to extend the support for other resolutions, if you have created a config-file for your resolution, I'd be happy to include it in the next releases.

**Comment by khova** [comment]
Yeah it was windows' resolution. Thanks for the help. 

Also the screenshot didn't work because I didn't take it from windows. But that's working now so I can mess with the OCR.

I can get the value to the right font size, or so it seems but it has trouble getting the numbers right. My gamma was up so I'll get back and take a new screenshot. I doubt I'll be able to get this right though. xD

**Comment by cadon** [comment]
You have to teach the OCR what the different numbers look like first, so it can recognize them. I'll try to setup a config-file for 1680 later in the evening.
