### ISSUE TITLE
Friend getting this error - W7 - NetFramework reinstalled error persists.

### ISSUE THREAD

**Issue by nswitcher** [cadon/ARKStatsExtractor#312]
![error](https://cloud.githubusercontent.com/assets/28868234/26314852/8c16f3b4-3f0f-11e7-8e85-1007c1f8cd3f.jpg)

**Comment by cadon** [comment]
Hi, the application is built for .NET 4.5, it seems on this pc only .NET 4.0 is installed. You can get .NET 4.5 here:  https://www.microsoft.com/en-us/download/details.aspx?id=30653

**Comment by nswitcher** [comment]
Thanks a lot!

**Comment by cadon** [comment]
Does it work?

**Comment by nswitcher** [comment]
He is Offline now, I will get back to you when he tries, He is gonna  love your app dude, when he saw what you could do with it he was amazed, he's been breeding a lot.
