### ISSUE TITLE
Red stat on Tapejara 

### ISSUE THREAD

**Issue by Underfire21** [cadon/ARKStatsExtractor#313]
I run unofficial server and my stats are prenerf. I dont know what went did wrong.   
     ![capture](https://cloud.githubusercontent.com/assets/28870975/26319468/22e9ef9e-3eed-11e7-9bfc-cedb70feab73.JPG)

**Comment by cadon** [comment]
Hi, the value for the weight hasn't been affected by the imprinting bonus yet. Sometimes the game forgets to update a value. You can try to levelup the weight once, this should trigger a recalculation, the real weight-value should be 1125.
It's strange that the speed has so few levels (8), that seems like a very improbable number, but not impossible.

**Comment by cadon** [comment]
Sorry, forget what I wrote before. I changed some multipliers, and the above said is only true if the multiplier for the increase of the wild-level of weight is 3.
Did you change this multiplier on the server? The value of the weight with a multiplier of 1 is very high.

**Comment by Underfire21** [comment]
No  I did not change the multiplier on the server. It works just fine with the other dinos I have but not with the tapejara's. I tryed to level up the weight and the weight went to green but a different stat would change to red.  I spawned in a tapejara and now stamina is red so Im gonna take a wild guess and just say I spawned in a parent of Lala and it has messed her stats up?

**Comment by cadon** [comment]
yes, that could be. You can try to disable "consider wild level-steps" in the settings, maybe that'll allow it to extract.

**Comment by cadon** [comment]
I'll close it for now, if the issue persist, feel free to add a reply / to reopen.
