### ISSUE TITLE
OCR with UI Scaling - Can't Create Custom OCR

### ISSUE THREAD

**Issue by Aarondorn2** [cadon/ARKStatsExtractor#314]
I use 125% UI scaling in Windows.  I'm not sure if I can launch Ark without this scaling - I plan on trying when I get home.

Because of the scaling, the OCR doesn't recognize the 'resolution'.  I tried creating my own using: https://github.com/cadon/ARKStatsExtractor/wiki/OCR, but am having issues.  The only option for loading a screenshot is drag and drop, but when I do this, it doesn't load the screenshot.  Does it need to be a specific file type?  I've tried .jpg, .jpeg, .gif, and .png.  Also, if I try to edit the image with a different program after dragging and dropping, it tells me the image is in use by your program (it just doesn't display).  Any thoughts?

Thanks for this tool, it looks super useful!

**Comment by Methos2178** [comment]
In the "Experimental OCR" tab click on the "Output" sub-tab, is "Enable Logging and Editing" checked?

**Comment by Aarondorn2** [comment]
Will check as soon as I get home from work!

**Comment by Aarondorn2** [comment]
That did it, thanks!
