### ISSUE TITLE
[Enhancement] More dynamic params for the name generator

### ISSUE THREAD

**Issue by ghost** [cadon/ARKStatsExtractor#315]
I liked the idea of having a name automatically generated, but the implemented function is too basic and lacks some functionality.

Instead of "Rex F11" i would like to have the option to include the stats in the name, that way i can easily read the tamed/hatched stats instantly from ingame instead of having to open the tool.

Example:
F230517404336402649I004

Female
Registered in the Extractor at 05/23/17 (above is european format)
HP = 40P
Stam = 43P
Oxy = 36P
Food = 40P
Weight = 26P
It was a raised Rex, so "I" means "imprinting" and the 3 digit number after means "4% imprinted"

The length of that name also does not exceed the maximum length of a displayable name in the game, that is 24 chars, the "compressed" info is 23 chars.

Ofc the user should be able to choose on his own what he want to include and what not.

For the purpose of that, i will add the following list of dynamic parameters:
cpr, date_short, date_compressed, time_short, time_compressed, hp, stam, oxy, food, weight, dmg, spd, trp, effImp, rnd

cpr represents the above naming convention, rnd will just use a random number between 100000 and 999999 and effImp will display either "Z" for no imprint and no efficiency or IXXX for imprint value or EXXX for taming efficiency value

I forked the project and when i implemented everything, i will create a pullrequest.
(see https://github.com/SkyDotNET/ARKStatsExtractor for progress)

- [x] Implemented the new initially planned parameters
- [x] Split d/m/y and h/i/s into single params so ppl can align them to their own countries date format easily.
- [x] Create wiki page with further info about the params
- [x] Rewrite the unique-check to make sure there are no duplicate entries in the creature database
- [x] Add parameter that just counts up automatically based on the total amount of creatures with the given species already in the database
- [x] Add check for the generated creature name that will give a warning if the name length exceeds 24 characters (thats the max displayed length in the game, the rest gets cut off)
- [x] (suggested by @kestnuts ) Add Tamed/Born level as parameter
- [x] (suggested by @ancilla-x ) Add abbreviations for all species
- [x] Add upper/lower/caseignore parameters

**Comment by SkyDotNET** [comment]
Status update:
- Implemented the new params
Todo:
- Split d/m/y and h/i/s into single params so ppl can align them to their own countries date format easily.
- Create wiki page with further info about the params
- Rewrite the unique-check to make sure there are no duplicate entries in the creature database
- Add parameter that just counts up automatically based on the total amount of creatures with the given species already in the database

**Comment by kestnuts** [comment]
May i suggest adding a parameter for Level at tame/birth?

**Comment by ancilla-x** [comment]
Is there any way we can set our own parameters without being experts at coding? For example I name my animals a 4 letter string followed by gender followed by tame or bred level such as ARGT-M-T201x1 for the first tamed male Argent tamed at 201. Is it unrealistic to be able to auto generate these names?

**Comment by cadon** [comment]
In the meantime all requests are added, closing this issue.
