### ISSUE TITLE
Unofficial Server Consistent Red Box on Tamed

### ISSUE THREAD

**Issue by marateon** [cadon/ARKStatsExtractor#316]
Hey,

So I am having issues only extracting tamed values. I have access to the .ini files and dragged them to update multipliers, plus manually checked them to verify. All multipliers are correct. I do not use OCR (multiple monitors) and hand key in all my values. Bred creatures, and wild creatures always extract correctly. 

However there are some tamed creatures that just will not work. So far I cannot seem to extract on wolves or sabers. At least the tamed ones. I have tried at least 3-4 of both species. I also pumped all the stats to see if they just needed updating, no luck. It seems that I consistently get red boxes for both food and damage. Any suggestions? I can snag some screenshots if needed.

Also no mods on server that affect dinos.

I have correctly extracted tamed rexs and theris so far. Will update if I run into any other issues as I put all my dinos in the library.

Thanks

Edit: Tamed argents red box consistently also. Bred are good.

**Comment by Vasney** [comment]
I just downloaded the latest version and I am having a similar issue. Every time I try to uncheck the Since Tame no Server Reset box, it rechecks it for me and I am getting red boxes and almost double expected levels.

**Comment by cadon** [comment]
Hi, a screenshot like [this](https://cloud.githubusercontent.com/assets/28870975/26319468/22e9ef9e-3eed-11e7-9bfc-cedb70feab73.JPG) would be good.

**Comment by Fainean** [comment]
Hi, I'm having the same problem, here are my screenshots.

![error1](https://cloud.githubusercontent.com/assets/29026764/26532410/6b4d8fc6-4400-11e7-80e9-a3f9f3057695.png)
![error2](https://cloud.githubusercontent.com/assets/29026764/26532411/6b51b236-4400-11e7-95ac-f3e9d39c0ae6.png)

Additionally, it doesn't work for me with Argis and Rexes.

Thanks for looking into it.

**Comment by cadon** [comment]
Hi @Fainean, you have a typo in the damage-value.

**Comment by Fainean** [comment]
@cadon sry, here is another one 
![arg screenshot 2](https://cloud.githubusercontent.com/assets/29026764/26559665/4d41cce8-44b1-11e7-9e2e-ef875fd2854a.PNG)
fresh tamed

**Comment by Fainean** [comment]
here are 2 more

![104 rex post tame](https://cloud.githubusercontent.com/assets/29026764/26560632/81c2c8c6-44b8-11e7-8ef2-2954df1a5bbe.PNG)
![104 rex pre tame](https://cloud.githubusercontent.com/assets/29026764/26560631/8189add4-44b8-11e7-9b3d-dddd192b006d.PNG)

**Comment by cadon** [comment]
Hi, it seems these birds were tamed when the max-wild-level was 120, or they were spawned in by an admin. The reason they cannot be extracted is their impossible wild-level, which is a multiple of 4 (instead of 5, like the creatures have it by default with a max-wild-level of 150).

You can extract these creatures if you disable the "Consider Wild level steps" in the settings.
