### ISSUE TITLE
Woolly Rhino Stats can't be calculated

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#32]
Hard to explain so I will leave it up to the screen shot, I have double checked the settings to make sure they match the game and see no errors there.

![capture](https://cloud.githubusercontent.com/assets/1366816/14876187/a84d3288-0d55-11e6-9fa8-7582cc14ab3b.PNG)

**Comment by cadon** [comment]
Hi, can you post the stat-multipliers you use in the game? A speed value of 332.9% shouldn't be possible with the vanilla-settings with no levelups. Maybe the xbox-version uses different values, though. Do all of your tamed/bred rhinos have at least 300% movement-speed?

**Comment by cyberangel67** [comment]
It is not vanilla settings, that is why I said I double checked the
settings matched what they should be. Every other Dino works well so far
that I have added, just the Rhino seems wrong.

Regards,
Andrew Scott


​

**Comment by cadon** [comment]
Hi, found the cause. The values were not yet from the devkit but from ingame-testing and obviously the weight-numbers were wrong. I corrected them. You can get the fixed stats by clicking on ? -> Check for Updates... in the tool.
Thanks for the report!
