### ISSUE TITLE
Red stat on Trex

### ISSUE THREAD

**Issue by schraplau** [cadon/ARKStatsExtractor#320]
I have 2 trexes where the Damage % shows up red but I can't seem to get it to show up green when extracting.  See screen shots
![suetrex](https://cloud.githubusercontent.com/assets/29105501/26649726/9a53a52c-460c-11e7-96d5-6d7f17f46d1c.jpg)
![suetrex1](https://cloud.githubusercontent.com/assets/29105501/26649725/9a4ec19c-460c-11e7-84e0-4ca0057ccbee.JPG)

**Comment by cadon** [comment]
Hi, what are the stat-multipliers you're using on your server, did you change them?

**Comment by schraplau** [comment]
Only stat multiplier I changed was for players which was weight and
fortitude. I didn't change the multiiers on the dinos.

**Comment by cadon** [comment]
Apparently you didn't lowered the lower threshold of the taming-effectiveness far enough. With a TE of 16.6% I can extract it.

**Comment by schraplau** [comment]
I thought I dropped it that low. I will do it again. Thank you for the help.
