### ISSUE TITLE
Problem with Turtles

### ISSUE THREAD

**Issue by strauss23** [cadon/ARKStatsExtractor#321]
I'm trying to breed turtles but it keeps saying 0 for oxygen and 0 for speed in the breeding plan. Thanks for the help.

**Comment by cadon** [comment]
Hi, species that don't have an oxygen stat also cannot have their speed-stat-level determined, both stats remain unknown. There are mods that enable the display of the oxygen-value even for species that don't use it. With that you can enter the oxygen stat (enable the "show oxygen for all species" in the settings) and then also the speed-level can be extracted. A mod that can do this is e.g. "super spyglass".
