### ISSUE TITLE
Quetzal stat pops in red

### ISSUE THREAD

**Issue by CheekyPJ** [cadon/ARKStatsExtractor#322]
Hey there, I have tamed a quetzal yesterday and straight after the tame I rushed to put the stats into the app, but health pops on red for some reason :/
I asked a friend who knows the app longer than me and he said to wait for server restart because of the possible torpor bug. The server I believe has restarted overnight and the torpor and other stats look the same to me. Providing a screenshot via imgur:  http://i.imgur.com/yansXwx.png
Anyone knows what's up?
(140 tamed with kibble without evo event)
Thanks
EDIT:
I upped it's weight by a few points, these are his current stats: http://i.imgur.com/StNpMNy.png

**Comment by cadon** [comment]
Hi, it appears you're using a very outdated version of the app. Usually the app should tell you to update at least after a day. Download the latest version here: https://github.com/cadon/ARKStatsExtractor/releases/latest

**Comment by CheekyPJ** [comment]
Thank you a lot, this helped. Have a good day.
