### ISSUE TITLE
Cannot Scan Old Doeds

### ISSUE THREAD

**Issue by BobbehYYC** [cadon/ARKStatsExtractor#323]
We Cannot Scan any old doeds they all dont compute with either their melee or food stats

First one
Male 228 tame

H:7550.7
St:1080
O:585
F:12377.4
W: 471.2
M:394.2
Ms: 230.6
T: 9008.5

Second:
Fem 230 Tame

H:5874.7
St:1140
O:540
F:15732.0
W: 621.6
M:402.2
Ms: 225.0
T: 9104.5

Third:
Male 264 Tame

H:5967.1
St1023
O:540
F:15508.9
W: 842.4
M:433.5
Ms: 225
T: 10784.5

**Comment by cadon** [comment]
Hi, it's mostly related to the now outdated wild-level-steps (earlier wild creatures had only multiples of 4 as level-number, now it's multiples of 5). Uncheck the "consider wild level steps" in the settings.

**Comment by cadon** [comment]
I'm closing this for now. Feel free to add an answer if the issue persists.
