### ISSUE TITLE
Trouble with Thylacoleo

### ISSUE THREAD

**Issue by nwm1991** [cadon/ARKStatsExtractor#324]
so i recently decided to start trying to beed thylacoleo's and came across your wonderfull tool but ive haveing trouble geting some of my dinos in there. at present i have 5 leos 2 wild tames an admin present and 2 bred, ive only been able to get 1 wild and the admin into the program properly 

que the screen shots

set up  (playing on the island so max lvl 120)
![server multypliers](https://cloud.githubusercontent.com/assets/8328145/26730602/63df77e8-47a9-11e7-94ca-567afa797e0d.png)
![multyplier setup](https://cloud.githubusercontent.com/assets/8328145/26730704/b4cac3ce-47a9-11e7-8268-208ba51b7e6e.png)

Wild tame works 
![m1g1p](https://cloud.githubusercontent.com/assets/8328145/26730944/71e2a1a2-47aa-11e7-97bd-f820d888d46a.png)
![m1g1g](https://cloud.githubusercontent.com/assets/8328145/26730990/8dfa6276-47aa-11e7-92b3-942aa9569d08.png)

wild tame not working (was given 1 level into melle damage to see if the lack of demstic levels was causeing issues, i rember he was a wild tame lvl 105 at about 96%)
![m2g1p](https://cloud.githubusercontent.com/assets/8328145/26731182/1f6f6ed6-47ab-11e7-805c-04637bace8f7.png)
![m2g1g](https://cloud.githubusercontent.com/assets/8328145/26731221/39f2843c-47ab-11e7-845d-f02658ba37c6.png)

admin spawned working
![f1g1p](https://cloud.githubusercontent.com/assets/8328145/26731500/34ac484a-47ac-11e7-91d2-bde8efa90d34.png)
![f1g1g](https://cloud.githubusercontent.com/assets/8328145/26731556/58abf812-47ac-11e7-8e52-dfc2c4a4bb19.png)

child of both working dinos not working
![f1g2p](https://cloud.githubusercontent.com/assets/8328145/26733139/d032c492-47b1-11e7-8fd4-17d8f9c23a61.png)
![f1g2g](https://cloud.githubusercontent.com/assets/8328145/26731784/1533a516-47ad-11e7-8033-2d34d857a8d9.png)

child of not working wild and other not working bred
![m1g3p](https://cloud.githubusercontent.com/assets/8328145/26733154/db042c4e-47b1-11e7-975a-edc8bccc55a7.png)
![m1g3g](https://cloud.githubusercontent.com/assets/8328145/26733144/d546dfc2-47b1-11e7-855e-2aafe2226fdf.png)

the problem seems to be with food and damge. hopefully this is something small and stupdip on my part thats easy to fix

**Comment by cadon** [comment]
Hi, were the stat-multipliers changed recently? Sometimes creatures keep their stat-values, even if the multipliers were changed. A levelup in a stat usually triggers a recalculation.

**Comment by cadon** [comment]
Hi, I found the reason for this issue. It's related to a rounding error. The real damage for the last Thylacoleo is 221.25% which is displayed as 221.2% in the game. This 0.5 difference causes too much rounding error in the further extraction-process. I'll hope to include a fix for this in the next release.

**Comment by cadon** [comment]
Fixed in 0.23.5
