### ISSUE TITLE
Megalosaurus No Oxygen

### ISSUE THREAD

**Issue by DragoValhar** [cadon/ARKStatsExtractor#325]
Seems that the Megalosaurus as of the latest update has oxygen disabled, I assume this is because of it's proximity to Megaladon. Seems that it does not want to calculate correctly the levels due to this.

**Comment by cadon** [comment]
Hi, thanks for the note. The Megalosaurus can't drown in the game, despite having an oxygen stat. Maybe that's a bug in the game. Megalosaurus and Megalodon are not closely related, they just share a similar name.
I'll add the oxygen back in the tool. Until then just enable "Show oxygen for all species" in the settings if you want to extract a Megalodon.
