### ISSUE TITLE
OCR doesn't work with multiple monitors

### ISSUE THREAD

**Issue by Choachy** [cadon/ARKStatsExtractor#327]
Just downloaded latest stable release. Im running 1920x1080 res (multiple monitors). When I try to scan, I get 'gibberish' in the name and tribe fields, and the stats are not read correctly. Screenshot attached. I tried reading values from tamed dinos and bred dinos. It doesn't seem to read that either. This screenshot is from a crappy tamed parasaur. The two values it read are correct. But it won't ever read anything else.
![image](https://cloud.githubusercontent.com/assets/29206109/26791351/d1ad4830-49e4-11e7-8f50-8b81c6e0abd7.png)

**Comment by mattnguyenn** [comment]
i am getting the same problem

**Comment by Taiine** [comment]
I run duel monitor and not had this issue, only once on one dino did a single stat not get read and was easy to fix manually.

**Comment by cadon** [comment]
This issue seems to be resolved, works for me with two monitors.
