### ISSUE TITLE
Stat issues

### ISSUE THREAD

**Issue by Ner0me** [cadon/ARKStatsExtractor#328]
I play on my unoffical server with 2.5 taming and max lvl of 210 and since I updated to the latest version of Ark Smart Breeding  (v.0.23.5) I get data errors for pretty much every creature I want to add. As an example I have the Daeodon I tamed.

![20170605175952_2](https://cloud.githubusercontent.com/assets/24465396/26792204/f80deaea-4a19-11e7-87cf-cf56e8dce701.jpg)

![unbenannt](https://cloud.githubusercontent.com/assets/24465396/26792470/d38145f4-4a1a-11e7-992c-77d12b7431ca.jpg)

![unbenannt2](https://cloud.githubusercontent.com/assets/24465396/26792463/c9bf4ae8-4a1a-11e7-924f-99c70860acc2.jpg)

Edit: Wanted to add, that I already tried unchecking the "Consider wild lvl-steps" box and it didn't help.

**Comment by Gluupor** [comment]
having the same issue on a freshly hatched / born baby with food and damage. this issue occured on the thylacoleo / tapejara. reverting back to version 0.23.4 has made it possible again to add creatures without errors.

**Comment by Ner0me** [comment]
OMG! I noticed my own error for the Daeodon, must have locked the food value >_> Just another case of stupid user... case closed! :)

**Comment by cadon** [comment]
@Ner0me nice one, didn't thought of that, the daeodon might be the first species which people will levelup the food.

Hi @Gluupor, please post the screenshots with the stat-values and your multipliers.
