### ISSUE TITLE
Not allowing insert of new Yutyrannus

### ISSUE THREAD

**Issue by valarhan** [cadon/ARKStatsExtractor#329]
![image](https://cloud.githubusercontent.com/assets/27072415/26806681/11e52522-4a07-11e7-8cd8-24701138ab32.png)
![image](https://cloud.githubusercontent.com/assets/27072415/26806688/203d1a26-4a07-11e7-80d4-3106bcda18ab.png)

**Comment by valarhan** [comment]
When I try to raise the imprint to 39% I get an error, too, btw -- 
![image](https://cloud.githubusercontent.com/assets/27072415/26806752/62d0eb60-4a07-11e7-862c-11f8da8c52e6.png)

**Comment by cadon** [comment]
So, did you make sure these two multipliers are set correctly in the settings? Are you on an unofficial server? Has this Yuty been hatched during an event?

**Comment by valarhan** [comment]
Hatched and matured during 2.0 breeding event (Ark Anniversary) but that shouldn't affect stats, should it? Just the rate at which it matures...

PVE-OfficialServer

**Comment by cadon** [comment]
The stats are dependant on the imprinting, the imprinting is dependant on the mature-speed and cuddle-interval, and the mature-speed was different during the event. Make sure you set all the multipliers accordingly.

Also, there's a bug in the game, that some imprints are not counted immediately, the game forgets to apply them to some stats, and only does it later. It seems only health got the bonus of the 9th imprinting, the other stats are still waiting for the increase and got only 8 imprintings (35%).

To extract this Yuty, set the imprinting to 35%, only for HP it is at 39% (or wait a day or two, the stats should be ok then). The changed multiplier often cancel each other out (mature-speed is 2x, cuddle-interval is 0.5, they are multiplied in the formula, so it results in the same).
