### ISSUE TITLE
Red stats on bred allo

### ISSUE THREAD

**Issue by borssos555** [cadon/ARKStatsExtractor#330]
I'm playing on official server and I bred an allo 2 weeks ago. When I tried to extract the levels I got errors in damage and food. I leveled up once in damage now I get yellow stats:
![image](https://cloud.githubusercontent.com/assets/29229850/26831278/1b90c93a-4acc-11e7-912b-914899164694.png)
Father:
![image](https://cloud.githubusercontent.com/assets/29229850/26831334/4f78dc88-4acc-11e7-8ef1-e90231500db4.png)
Mother:
![image](https://cloud.githubusercontent.com/assets/29229850/26831448/9d6817ce-4acc-11e7-8f36-6cbc3872cca1.png)

**Comment by cadon** [comment]
Hi, thanks for the report. It's a bug with the new taming-effectivness algorithm. I'll be fixed in the next release.

**Comment by cadon** [comment]
fixed in 0.23.6.
