### ISSUE TITLE
Red stats on Dunkleosteus, torpor is the issue

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#331]
According to this image, the Dunkleosteus has way more torpor than it should have according to your calculator. All the other stats could be re-created in the stat tester.

![afbeelding](https://user-images.githubusercontent.com/21133200/26836425-1999d22a-4adb-11e7-84c3-73c6625f9cea.png)

**Comment by cadon** [comment]
Hi, the high torpor is caused by the torpor-bug (after taming the displayed torpor-value is too high). The issue is probably some stat-multipliers. Are you on an unofficial server with adjusted multipliers? Make sure you set them all correctly in the settings.
