### ISSUE TITLE
Still can't extract 100% imprinted creatures (Rex)

### ISSUE THREAD

**Issue by jal45** [cadon/ARKStatsExtractor#332]
I'm on offical servers and still can't seem to extract creatures with 100% imprinting, 95% worked fine to extract. I've updated the newest release as well.

**Comment by cadon** [comment]
Hi, did you update to 0.23.6, which was release just some minutes ago? If it's not working with this, please post a screenshot of the stats.

**Comment by jal45** [comment]
Just updated and it's working now! Thanks a lot for making such a program, it's really handy and easy to use. 👍
