### ISSUE TITLE
Cant extract when imprinted

### ISSUE THREAD

**Issue by Ocean15** [cadon/ARKStatsExtractor#333]
Hey man!

First of all: Rly rly nice software you made there ! 👍 

Now the problem:
Whenever one of our dinos is imprinted (doesnt matter what kind of dino or what the imprinted stat is) i'm not able to extract the dino anymore.

Im with your new version (0.23.6).
My server settings: [Settings](https://gyazo.com/a7c41d00a4242e8adc13b3477aca61a6)
The dino stats: [Stats](https://gyazo.com/9d428af04c5a48e2afa207cfbb0801b5)

Greetings from germany
Ocean15

**Comment by cadon** [comment]
Hi, this is caused by a mismatch between the cuddleInterval- and / or the matureSpeedMultiplier. Probably the server-settings of these two multipliers were different when the rex hatched or was raised.

Did you ever change them recently? And are you 100% sure these settings are the one used on the server when the rex hatched?

**Comment by Ocean15** [comment]
Whe changed those settings but i dont know if it was before or after the breeding. Just hatching some new rexes to test it again without any changes. Ill give you an update in about an hour

**Comment by Ocean15** [comment]
[Here](https://gyazo.com/f6189dd4788e831859afd207613f8d49) the stats from a new hatched rex. Still dont work (same config). Im the server owner btw, so the settings are correct for sure

**Comment by cadon** [comment]
Neue Überlegung: vielleicht gelten die Multiplikatoren für den Rex die gültig waren, als das Ei gelegt wurde? War das ein frisches Ei, oder evtl. eines das entstanden ist, als noch die alten Multiplikatoren gültig waren? Funktioniert es, wenn die alten Multiplikatoren im Extraktor eingegeben werden?

**Comment by Ocean15** [comment]
Die Eier wurden frisch gelegt mit den aktuellen Multiplikatoren, daran kann es nicht liegen. Die Stats passen auch. Ich hab vor dem imprinten die Stats extracted. Nach dem imprinten sind die hp angestiegen. 
Die Software erkennt die hp auch als richtig (grün) aber die anderen unverändertend Stats sind nach dem imprinten auf einmal "falsch" laut der Software. [Hier](https://gyazo.com/d182297dc815e6a56573edbf8cd5bcdf) mal seine Stats VOR dem imprinten, die er erkannt hat

**Comment by cadon** [comment]
Ah, bei dem ist das Problem klar: Das Spiel erhöht manchmal nicht gleich die Stat-Werte beim Prägen, so dass einige Stats noch die Werte haben, als ob der Dino eine Prägung von 0% hätte. Wenn man bei Prägung 0% eingibt, funktionieren alle Stats, die bei 9% nicht funktioniert haben. Normalerweise werden die Werte nach einiger Zeit (nach einem Server-restart?, Dino in stasis?, Stat aufgelevelt?) aktualisiert, so dass es dann regulär funktioniert. Ansonsten kann man einfach den Dino nach dem Schlüpfen eintragen und die Prägung später bearbeiten. Das wichtige fürs Züchten sind ja die Level, die durch das Prägen nicht verändert werden.

**Comment by Ocean15** [comment]
Also ich kann Restart ausschließen. Das hab ich schon probiert (wegen deinem Hinweis im Programm). Es kann höchstens Stasis oder oder lvln sein, wobei ich Stasis auch für unwahrscheinlich halte.

Naja gut, dann bleibt mir wohl nichts anderes übrig als die Dinos direkt nach dem schlüpfen einzutragen. Ist halt nur blöd wenn grad jemand anders aus dem Tribe sich ums Breeden kümmert, der die Software nicht benutzt. Dann hat sich das mit dem nachtragen erledigt :samoa:

**Comment by cadon** [comment]
Wann genau die Werte aktualisiert werden, hab ich noch nicht rausgefunden, es scheint aber nach einiger Zeit neu berechnet zu werden (genau wie der Torpor-Bug sich irgendwann korrigiert). Im Zweifel einen Tag warten oder aufleveln.

**Comment by Ocean15** [comment]
Der älteste den ich getestet habe ist jetzt 6 Tage alt und hat demnach schon 6 restarts erlebt (Server startet täglich neu). Bei dem bin ich mir auch zu 99% sicher, dass er mit den gleichen Settings gezüchtet wurde wie sie aktuell auf dem Server sind. Ich glaube irgendwie nicht, dass sich seine Stats nochmal ändern. Ich vermute ein anderes Problem dahinter 🤔

**Comment by cadon** [comment]
Wurden die problematischen Stats mal gelevelt? Vielleicht ist es das einzige, was eine Neuberechnung erzwingt.

**Comment by Ocean15** [comment]
Okay ich habs jetzt 👍 

Anscheinend war es dieser eine Prozent Unsicherheit was die Settings angeht 😆 

Die Stats aktualisieren sich beim reloggen auf jeden Fall. Vorher aktualisiert sich nur das Leben der Dinos. Kannst du ja vielleicht so in deinen Info Text aufnehmen.
Die Berechnung funktioniert jetzt jedenfalls.

Also für die Zukunft: Wichtig ist ein reloggen nach dem imprinten um die aktuellen Stats zu sehen. Und Ob man jetzt ein neues Ei breeden muss oder ein bereits vorhandenes Ei breeden kann nachdem die Settings geändert wurden kann ich nach meinen Tests aber auch noch nicht sagen, da müsste ich mal genauer drauf achten.

Naja, dank dir für deine Bemühungen 👍

**Comment by cadon** [comment]
Hi, mit reloggen meinst du, den Server verlassen und wieder joinen, oder das Spiel neustarten? Oder den Server neustarten? Danke für's Testen!

**Comment by Ocean15** [comment]
Hab den Server verlassen und wieder gejoint, das hat gereicht :)
