### ISSUE TITLE
Library level stat is wrong

### ISSUE THREAD

**Issue by Ocean15** [cadon/ARKStatsExtractor#334]
Every level shown in the library tab is 1 lvl lower than it should be.

In the stat testing view the "total levels" stat is shown correctly.

**Comment by cadon** [comment]
Hi, do you mean the column "To"? That is the level of the torpor, which is always one level lower than the sum of the wild-levels, thus one level lower than the total level if the creature has not yet been leveled manually. For the abbreviations see https://github.com/cadon/ARKStatsExtractor/wiki/Abbrevations
