### ISSUE TITLE
Extractor Issue: Pulmonoscorpiu's Health (Max tamed Vanilla)

### ISSUE THREAD

**Issue by PeterManize** [cadon/ARKStatsExtractor#335]
The extractor, just doesn't accept the "scorpion" health value.

I've used the stat testing to try and see why it does that, i think the reason is that there is no value like 1428,1, the closest for its stats distribution is: 1468,1.

This a perfect tame with spoiled meat, the Level and taming effectiveness is literally the same has the dodo dex.

This is singleplayer, there wasn't any server restart, I didn't accidentally hit the creature while it was taming.

I did a level up on health, still refuses to accept the health value (actual value is 1610,6)

![untitled](https://user-images.githubusercontent.com/29291128/26953834-b32ba9ac-4ca4-11e7-8793-e5a941c7b5d1.png) - before the level up.

**Comment by cadon** [comment]
Hi, scorpions are bugged. See #2, #16, #60, #92, #162, #207, #300 or #326.
