### ISSUE TITLE
Wyvern color regions

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#336]
On all creatures with less than 6 color regions, those region buttons are completely removed. On the lightning wyvern (with your classic flyer json), although not on the fire wyvern, there is a color region that just says "Not Used".

Also, the fire wyvern shows color region 3, while it is not present on the wiki. I do not know if this is a fault by you or the wiki.
EDIT: using commands to paint color egion 3 on a fire wyvern had no visible results.

![afbeelding](https://user-images.githubusercontent.com/21133200/26954201-fdefa13c-4cae-11e7-93d5-28514e47c7f9.png)

**Comment by cadon** [comment]
Hi, thanks for the report, this is fixed in the latest release (0.23.7).
Note, the newly added Ice Wyvern does not have color-regions yet (it just shows all regions with all colors), I hope to get it fixed soon.
