### ISSUE TITLE
Cannot extract values from Daeodon

### ISSUE THREAD

**Issue by SturmhartEisenkeil** [cadon/ARKStatsExtractor#339]
I bred a Daeodon today and I cannot extract the stats.
I already restarted the server to update the stats and we did not change any of the breeding values since we started the server.

The tool tells me this: "The imprinting percentage given is not possible with the current multipliers and may cause wrong values during the extraction process."
And then it enters 98,496 % imprint and then obviously the extraction fails because my dino has 100% imprint.

We use a mod on our server that lets us craft a special kibbel that raises imprint to 100 %.

It is nice that the tool tries to keep users from getting false data but in my case, I have no way to get this dino into the library.

An option whould be nice to tell the tool that it should not check the imprint percentage for possibility.
Since the new version of the magnifying glass tells you the breeding stats as well as manual levelups it whould also be nice to simply add a dino to the library by entering the number of levels in each stat without having to use the extractor at all.

**Comment by cadon** [comment]
Hi, the checking for the possible imprinting-stat is elementary for the extraction, it wouldn't work else. I'll put the option for a "surely 100% imprinted"-checkbox on the todo-list.
Until then, if you have the levels, you can just enter the levels of the creature in the tester as you said and save it in the library.

**Comment by SturmhartEisenkeil** [comment]
Hi, thanks for the fast reply. I did not realize that I can use the tester to add creatures to the library so I take everything back what I said about an alternate method of adding dinos :)

**Comment by cadon** [comment]
Hi, the option was added in the latest release (0.23.7). Disable the "Adjust to possible imprinting" in the settings if you used this special 100%-imprinting-kibble. Make sure to reenable it once you want to extract a creature that hasn't got it.
