### ISSUE TITLE
Pteranodon RED Stat Values

### ISSUE THREAD

**Issue by apoullie** [cadon/ARKStatsExtractor#340]
So I play on an unofficial server with the rates in the image that I got from the admin, but I still receive these red stat boxes. I haven't leveled the ptera at all and my server has classic flyers.  I'm new to the Smart Breeding program so if you could help or give me a good guide to follow that would be great!
![image](https://user-images.githubusercontent.com/19809398/27016663-14d0a6f4-4ee8-11e7-89b0-f28ae84f58b2.png)

**Comment by cadon** [comment]
Hi, obviously the server has the classicFlyers-mod installed, which changes a lot of stats on flyers. Also your version is outdated, there should have been a messagebox telling you about an update, didn't it pop up?

There's a file called classicFlyers.json in the json-folder, copy this to the same folder as your library, click File -> Load additional values... and choose that file. It should work then.
