### ISSUE TITLE
Cannot set maximum dino spawn level above 1000 in settings

### ISSUE THREAD

**Issue by TechDweebGaming** [cadon/ARKStatsExtractor#341]
As the title states, in settings I can not set the maximum wild dino level above 1000 (it is 1500 on my server). However, I CAN go above in the extractor, so I assume its just a hard-coded cap in the selection box rather then a logical issue. It isn't a huge deal, as I would think it still works fine due to the extractor, and therefore library, accepting the higher values, but it's something to look into. Thanks, and awesome program! :)

**Comment by cadon** [comment]
Hi, I'll increase the possible input in the next release. I never thought more than 1000 is necessary.

**Comment by TechDweebGaming** [comment]
Ok, thanks! Keep up the good work! :)

**Comment by cadon** [comment]
I added some orders of magnitude to the upper limit of most numeric inputs in the newest release.
