### ISSUE TITLE
problem add my direbear in library

### ISSUE THREAD

**Issue by focabr** [cadon/ARKStatsExtractor#347]
Hi,
i am having problems in adding my direbear into library. I sending my images.

![image](https://user-images.githubusercontent.com/4109361/27248595-348d0e68-52dc-11e7-8fee-48342f6160e6.png)

![image](https://user-images.githubusercontent.com/4109361/27248598-42b7adcc-52dc-11e7-8242-b61f95b50f48.png)

**Comment by cadon** [comment]
Hi, there should have been a messagebox telling you about an issue with the babyCuddleInterval- and the babyMatureSpeedMultiplier. Did you make sure they are correct?

**Comment by focabr** [comment]
Hi,

I play in server official. My settings. for me is correct!!

![image](https://user-images.githubusercontent.com/4109361/27256466-e537839c-538b-11e7-8fa2-89e1693c59e3.png)

**Comment by cadon** [comment]
Then the only reson for a deviation in the imprinting can be a breeding-event. Did you raise this bear during an event with increased mature-speed?

**Comment by focabr** [comment]
Hi, 

I set mature-speed to 1.5x, now is error (sum 45 diff Should be 49):
![image](https://user-images.githubusercontent.com/4109361/27311743-5b6014f4-5539-11e7-8bdc-3ac6ea393368.png)

thx for help me!

**Comment by cadon** [comment]
Hi, it seems the weight-stat has only 20 wild-levels. Also see https://github.com/cadon/ARKStatsExtractor/wiki/Manual#what-to-do-if-a-stat-is-yellow

**Comment by focabr** [comment]
Cadon, 

Thx for help me again!!! Is work fine now!

![image](https://user-images.githubusercontent.com/4109361/27359101-47042402-55f0-11e7-8351-1dd1f5aebc5e.png)
