### ISSUE TITLE
Stat mismatch with ClassicFlyers Mod on custom server

### ISSUE THREAD

**Issue by timegrinder** [cadon/ARKStatsExtractor#348]
Hello!

Thanks for this fantastic app, I only found it a few hours ago and I already think it's amazing.

I do however have a similar issue to what others are facing with my flyers and the ClassicFlyers mod.
(I didn't want to jump on their issues and say "hey me too" in case it wasn't the same, because if you manage to fix it for one of us we can likely all mark the issues fixed as we go)

I've followed the instructions and set it up to use the classicFlyers.json and it corrected some stat errors, however new ones arose. (running 0.23.7 version of app)

I'm also having the problem of stats coming out red because the app considers them impossible, as well as the stat calculation coming out mismatched to the game. (Because the taming multiplier on the server is so high (x8) any generic tame usually comes out 95%+ taming efficiency, most of them being 98-99, so the efficiency range is generally set high for the calculation.

I'll preface with a copy of the game.ini and multiplier settings as I understand them:
[Relevant game.ini section and settings window](http://i.imgur.com/6kJHc7u.png)
The server has been running for 3-4 weeks with the current settings, so there have been no recent changes (and it restarts twice a day to install potential updates)

Here are some screenshots with brief explanations for each:
[An Argentavis with broken stats according to the extractor](http://i.imgur.com/tnxsK8t.jpg)
The results are exactly the same if I remove the locks, I just couldn't be bothered re-editing the screenshot (sorry :P)

[A Pteranodon with mismatched levels](http://i.imgur.com/hu85WUo.png)
This one has about the right taming effectiveness except it was tamed at something like Level 106-110

[Pelagornis with mismatched level counts and the yellow stats cannot be changed to values that will fit](http://i.imgur.com/mj9yEKI.png)
The Pelagornis is mismatched by 2 levels but I can't change the yellow ones to fit (eg would have to change  weight down to 20 but it won't let me). The taming efficiency / wild level are accurate from my records though.

Overall I'm thinking there's a mismatch between the ClassicFlyers stats (possible rounding from my multipliers) or something similar as I've tested with various land based dinosaurs and they all extract the correct stats and levels.

Sorry if I've omitted anything or made errors in my screenshots, I'll provide any new tests you need with what I can work with (I do not have admin spawn permissions so can only work with existing tames).

**Comment by cadon** [comment]
Hi, I checked the HP (which seems to be mostly the issue) again on singleplayer with classicFlyers, I couldn't find an issue there. I guess it's because of a change in the stats in the classicFlyers mod that the current creatures haven't yet applied. Stat-values sometimes stay outdated for a long time, until the according level gets upleveld and the value is recalculated.

Could you try it with freshly tamed creatures? Or level up HP on a creature that didn't work?

**Comment by timegrinder** [comment]
I'll see what I can get done and get back to you, but as a preliminary response I can say that any flyer of a lower tame level (or lower stat amount) registers fine, and all bred flyers are accepted by the program as well no matter how high their stats are.

**Comment by timegrinder** [comment]
Hey there,

Here's a freshly tamed Tapejara, level 120, 99.9% taming effectiveness (Level 179)
[In game stats + Extractor screenshot](http://i.imgur.com/AY1zzOR.png)

Noticing that it's registering a level way above what it's level actually is.

No multipliers, stats or anything else have been changed on the server for almost a month now, and as I found the bred flyers all work properly, so for some reason it's just not calculating tamed creatures properly.

**Comment by timegrinder** [comment]
I've found that using the extractor to get wild levels (Eg, after tame but without levelling up the creature) is entirely accurate.

The extract however breaks down (registering both wild and tamed levels) once the creature has been levelled after taming.

Example - Quetzal recently tamed (ie since this discussion)
[Freshly tamed, no levels](http://i.imgur.com/gdvCTQC.png)
[After taming and quite a few levels](http://i.imgur.com/0RG3I5X.png)

**Comment by cadon** [comment]
Thanks for this info! I'll hope to look into this in the next few days. If you want to experiment with this yourself, have a look at https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values, it seems the tamedLevel-value is not correct then.

**Comment by timegrinder** [comment]
It crossed my mind, I'm only basically familiar with JSON (I'm guessing it's just a big string of valuename:value kind of thing, but the formatting is a b*tch.

If I manage to throw it into a spreadsheet and re-adjust the calculations I'll let you know what I come out with, I'll have to find a tame that I know the EXACT tame-levels on and see what I can find :)

**Comment by timegrinder** [comment]
Well I did a test calculation, I can't say I'm sure it's right but I used the following formula to do a manual level extraction in a spreadsheet:
(CurrentStat-BaseStat)/gain per level (in the case of an argentavis with 1533.2 HP it was (1533.2-365(the base HP @ level 1))/73 (the base wild gain per level) which netted me a result of 16.0027397 (and your program shows 16 as well)

Does that sound like I'm on the right track? I assume there is magic math the program itself iterates through until it finds a match to get the mixture of wild + tame levels for extraction so I'm going to find a new tame and then level it up to do the testing so that I know exactly how many levels went into what.

**Comment by cadon** [comment]
Hi, yes, that's exactly what the application does. Also have a look at the [formula on the stat-calculations](https://ark.gamepedia.com/Creature_Stats_Calculation) if you have questions about it, but for wild levels it's just the thing you did.
It get's more complicated with tamed creatures, at least for Food and Damage, as these two stats get an additive bonus and another multiplicative bonus dependant on the taming-effectiveness.
As far as I understood, the issues for now only happen for tamed creatures in stats that were leveled up, right? That sounds as if this value of the levelup is wrong in the classicFlyers.json.

Btw, it's best to use a json-editor like http://jsoneditoronline.org/ for easier editing this file.

**Comment by timegrinder** [comment]
Hiya,

Yeah I used a JSON editor to reformat it so I could read it more easily, got to the additive + taming bonuses and saw how complicated it was to manually do it in a spreadsheet, but yes overall it looks like the numbers are wrong somewhere after taming.

I'll be testing the tame stats after levelling from known wild stats to see which tamed stats come out wrong (if I get around to it before you happen to find out / patch it).
