### ISSUE TITLE
Parasaur Weight

### ISSUE THREAD

**Issue by Maedean** [cadon/ARKStatsExtractor#35]
Hi,

The Parasaur starting weight is 280 (lvl 1) but it says 200 in the stats-file.

Corrected it in mine after I had multiple errors which didn't make sense.

Regards

**Comment by cadon** [comment]
Hi, thanks for the report. You can check for the most uptodate stats-file by clicking ? -> Check for Updates in the tool. There were some other stats that got corrected in the last couple of days.
