### ISSUE TITLE
Unable to extract stats from tamed Equus

### ISSUE THREAD

**Issue by LiungArkeanda** [cadon/ARKStatsExtractor#350]
![ark smart breeding issue](https://user-images.githubusercontent.com/29542501/27283458-632e74ea-54c2-11e7-97f1-a1c83d4dae92.png)
I asked the server owner if we had any multipliers and was told no, only players have a multiplier on weight, no multipliers on dinos.

I put levels into health, melee damage, and I think also stamina and weight. I'm pretty sure it was tamed at 100% efficiency. I've logged off since taming it. Unlocking the lock symbols still returns an error.
![ark smart breeding issue2](https://user-images.githubusercontent.com/29542501/27283588-0130dfca-54c3-11e7-8f85-dba9c39b0aed.png)

I'm at a total loss, what am I doing wrong here?

**Comment by LiungArkeanda** [comment]
I thought maybe it was really hard for the program to figure out what the levels were from a tamed dino when honestly I can't even remember what level it started at/what stats I levelled/etc so I went ahead and bred a baby and
![ark smart breeding issue3](https://user-images.githubusercontent.com/29542501/27288212-0b04c0b4-54d4-11e7-87a2-170ac974bb5a.png)
It's still showing the same problem.

**Comment by LiungArkeanda** [comment]
If it helps, here's my settings and what my server owner said was the multipliers on the other things.
![ark smart breeding issue4](https://user-images.githubusercontent.com/29542501/27288984-6b98a196-54d6-11e7-8713-d8fb08cb4f48.png)
He also said baby food consumption 0.5 and taming 2.0, but that definitely he didn't change the multipliers on dino stats.

**Comment by LiungArkeanda** [comment]
And I just realized, these dinos do not have mutations, it's just a "Any Coloured Dino" mod that allows wild dinos to spawn in any colour possible.

**Comment by cadon** [comment]
Hi, it seems the server you're on has changed multipliers, more precisely, all multipliers are set to 1. The default (what the official servers are using) is different for HP and Dmg. Just go to the settings and click on the "Set all to 1"-button.

**Comment by LiungArkeanda** [comment]
That seemed to fix the baby, thanks! But the tame is still throwing up an error, this time on Stamina, I think, and Damage again.
![ark smart breeding issue5](https://user-images.githubusercontent.com/29542501/27318165-dd1e8330-5558-11e7-98a4-eff4136214b6.png)

**Comment by LiungArkeanda** [comment]
I tried a different Equus and that worked alright. The only thing I can really see that is different for this one is the taming efficiency, maybe? But I don't even know if this is right, I'm completely guessing. And if I expand it to test between 20-100, it changes things. All I remember is when I was running around taming I was accidentally hopping off most of them at least once.

![ark smart breeding issue6](https://user-images.githubusercontent.com/29542501/27318882-93eacf62-555c-11e7-8296-a4c9429433c4.png)

But with Echo I was reasonably sure it was 100% taming efficiency.

**Comment by cadon** [comment]
Hi, are you 100 % they were tamed with a taming efficiency (TE) of 100 %? When they work with a TE of 90-100% it's probably the true value.

For the imprinted creatures it seems there are different multipliers for the mature-speed or the cuddle-interval multiplier. You can ask your admin if they can send you the game.ini and the gameusersettings.ini, so you can drag&drop them in the settings-window to read all the values automatically. Or if they can send you the actual numbers.

**Comment by LiungArkeanda** [comment]
Setting Echo's TE to 80-100% fixed the error and I was able to add him, so maybe it wasn't 100% after all.

But then, I got the game.ini and the gameusersettings.ini from my admin and it did indeed change some values! But I'm still getting the error about the imprinting, and putting any of the tamed dinos I'd managed to get through again, Echo included, saw the return of the error, even if TE was set at 0-100. 

I really don't know what to do here.

Settings:
https://pastebin.com/ZTBsPCxA
https://pastebin.com/kqkCs24m

Offspring I haven't put any levels at all into; the first had 52% imprinting, the other two 100%:
![ark smart breeding issue8](https://user-images.githubusercontent.com/29542501/27353610-9c6624cc-55d2-11e7-9567-90eaf79a165d.png)
![ark smart breeding issue9](https://user-images.githubusercontent.com/29542501/27353821-7a41f05a-55d3-11e7-8cbf-3e62d78b8c9a.png)
![ark smart breeding issue10](https://user-images.githubusercontent.com/29542501/27354001-143036c2-55d4-11e7-8df9-ff01c6822322.png)

Tamed Dino, back to giving an error:
![ark smart breeding issue11](https://user-images.githubusercontent.com/29542501/27354187-bc7d0b70-55d4-11e7-8ccc-ea645fd2aa7a.png)

**Comment by LiungArkeanda** [comment]
Baby I just bred, has no imprinting yet so it's not giving the imprint error, but it's giving the same error as the tames.
![ark smart breeding issue12](https://user-images.githubusercontent.com/29542501/27355716-0228e950-55da-11e7-8278-c0d4def2c05e.png)
But, if I go into settings and set all the stat-multipliers to 1, it works
![ark smart breeding issue13](https://user-images.githubusercontent.com/29542501/27355739-1818075a-55da-11e7-89ae-fa18a11bb7ca.png)
But that's not what is in the settings my server admin gave me! I dragged and dropped and that's when it stops working!

**Comment by cadon** [comment]
Hi, strangely the settings-file has a 0 for some values of HP and Dmg. And it appears the game interprets a zero as a 1, so setting the stat-multipliers all to 1 seems correct. I'll update the application so it will interpret a zero also as a one.

For the imprinting-issue, it seems if you set the matureSpeed to 10 (as it already is) and the cuddleIntervall to 0.25 that the extraction works. Even if these numbers are not the one used on the server, the extracted values will be correct, so I'd just use that. It could be that after a changing of these numbers on the server, the old number will be valid for some creatures that already were born.

**Comment by LiungArkeanda** [comment]
That seems to have fixed everything! Thank you SO MUCH. I'm still not entirely sure what it means when the extraction gives yellow stats and I have to choose, but I suppose that's what the manual is for!

The one thing I would like to know, since babies inherit their parents' wild stats, does that mean that if a baby comes out with stats that don't seem to match either of the parents, there's an error with the extraction values of the parents?
![ark smart breeding issue14](https://user-images.githubusercontent.com/29542501/27392538-edd19c72-5674-11e7-9ad9-afaefdd75c92.png)
And how do I fix that?

**Comment by cadon** [comment]
A yellow stat means, that there are multiple possible level-numbers, which can not be differentiated mathematically. Then the user has to choose the level-combination that is correct in the appearing list on the right.
If the baby has a stat that is neither of any parent, it could be that there was a mutation (then the stat-number is exactly 2 higher than the inherited stat), or that there was an extraction-error, probably you haven't chosen the correct combination if a stat was yellow.
An extraction is always unique, if you extract a creature before you put any level in it.

**Comment by LiungArkeanda** [comment]
I think I got it, by looking at the babies to make sure that the stats match, then working out what the correct stat is, using the extractor to mess around until they're right, and then editing the dino to match. So I've been doing that and I ran into a tiny issue. It doesn't seem like it matters much, except that if I'm doing something wrong I could be messing other things up too.

So I looked at Kaze's two children in the pedigree window, and was able to get his stats to work out properly. (My highlighter colours: green for a match, yellow for unconfirmed, orange for one mismatched parent, red for two mismatched parents)
![ark smart breeding issue15](https://user-images.githubusercontent.com/29542501/27397158-68de89a8-5683-11e7-8ac8-0ccf6a9451af.png)

And I was super happy about this, until I went to the library and noticed his daughter's torpor stat is one off.
![ark smart breeding issue16](https://user-images.githubusercontent.com/29542501/27397208-8c7bb566-5683-11e7-863a-f68ba092abc4.png)
Torpor doesn't show up on the pedigree, only the library and extractor. I can raise the torpor stat in the edit mode, but then the level is too high. And even with TE at 0-100, the options for the yellow stats that match what his children's stats say they should be don't change the torpor at all (though at first extraction there's a wrong number of points in Speed, despite it being green, and clicking the correct options in the yellow stats fixes it).

So if it's just a weird thing with torpor not displaying correctly or something else restricted to this small error, I don't care much, 1 point in an unchangeable stat like torpor isn't a big deal, but I would like to know if, yet again, I've screwed something up somewhere.

Thank you by the way for being so helpful! Now that it's working this program is WONDERFUL, breeding has always seemed so huge and daunting to me I never even wanted to try. This makes it so convenient, you truly are a genius!

**Comment by cadon** [comment]
The torpor is not shown in some views, because it plays no role in breeding, the torpor-level is always just the sum of the other wild levels. Torpor also is not inherited to the baby from either parent, but it's again just the sum of the baby's wild levels, which can be completely different than the torpor level of both parents.
One thing to consider, maybe that's the issue you're having: the speed-level never can be extracted directly, it's always just the leftover levels to the total wild-levels, so changing the wild speed-levels can maybe fix this, without changing the other wild levels.

**Comment by cadon** [comment]
The extraction issue looks resolved. For the DPI-scaling issue see #151.
