### ISSUE TITLE
Stat chart for library

### ISSUE THREAD

**Issue by ToeiRei** [cadon/ARKStatsExtractor#351]
I often sit here at the ASE Library trying to get my dinos organized, looking at which ones to keep or which ones to get rid of. The stat chart from the "Start Testing" window offers quite a nice overview if it's worth keeping a dino without doing a lot of number crunching.

**Comment by cadon** [comment]
Hi, I added a radar-chart to the library in the freshly released 0.23.8, see in the new tab in the bottom-left.
Is that how you imagined it for a better comparison or should it be placed somewhere else?

**Comment by ToeiRei** [comment]
Quite close, but not a cigar ;)
![image](https://user-images.githubusercontent.com/5990591/27511799-85f8c6f0-592d-11e7-9080-deaee24523b6.png)

**Comment by cadon** [comment]
haha, that doesn't look right. I'll fix that.

**Comment by cadon** [comment]
Should now be fixed in 0.23.9.
