### ISSUE TITLE
Bred Baby not reading properly

### ISSUE THREAD

**Issue by Myzfit4life** [cadon/ARKStatsExtractor#352]
So part of the problem is the server owner changed the speed of maturation while this baby Therizino was still maturing. But now we have this and one other baby (both matured at the same time) that will not scan into the app. I am going to include screenshots of both, as well as how they're appearing in the Smart Breeding app so maybe you can help w/ this issue. It would be super helpful to have a way to manually add dinos when something like this occurs in the future.
![stat issue zeus](https://user-images.githubusercontent.com/29603950/27387786-a5dd4edc-5667-11e7-9ef3-6787c1f184e4.png)
![stat issue ravenclaw](https://user-images.githubusercontent.com/29603950/27387794-ac5f26ae-5667-11e7-9601-f8bb77af95a0.png)

Thank you in advance for any help you have on this issue... It would be nice to include them in the breeding calculator because I have a hunch that Zeus is better than Zino for breeding, but I'm not sure.

Sincerely,
Myz

**Comment by Myzfit4life** [comment]
Never mind. I started messing with the multiplier stat in the settings and managed to get them both in properly.

**Comment by cadon** [comment]
Good to hear! You can always add creatures manually to the app in the Tester-tab. Just set all the levels and the taming-effectiveness / imprinting and click on "add to library".
