### ISSUE TITLE
Looking at the smaller probability graph values

### ISSUE THREAD

**Issue by LiungArkeanda** [cadon/ARKStatsExtractor#353]
It's not exactly an issue as in a bug, but I have a morbid desire to know exactly how bad my luck is to get ALL the lower stats. The graph bars are too small, even going over pixel by pixel I can't get the pop-up.
![ark smart breeding the worst luck ever](https://user-images.githubusercontent.com/29542501/27400740-1183572c-568f-11e7-911c-dbe082c6cf76.png)
Is there a way to make the graph easier to read?

**Comment by cadon** [comment]
I've also seen this on your other posts, it seems you're having the issue described in #151.
Using a different pixel-scaling on windows causes some controls to show weirdly offset. You can try if right click desktop -> Screen resolution -> Make text and other items larger or smaller -> Set to 100% (or 150%?) fixes the probability-chart and the pedigree-view. Sadly I haven't found a solution to fix the display for other pixel-scalings.

**Comment by LiungArkeanda** [comment]
Wow I hadn't even realized everything was so messed up! I can see things like breeding scores that I hadn't even known were supposed to be there! The graph hasn't changed at all--the issue is that the lower level bars are so small I literally can't get my curser on it in a way that the tooltip shows the label for it--but honestly it's not a huge deal. Clearly it's lower than the next smallest one that I can get to show up, at 0.1%. 

Thanks a lot!
