### ISSUE TITLE
Can't add any griffen, stam always red.

### ISSUE THREAD

**Issue by Taiine** [cadon/ARKStatsExtractor#354]
http://i.imgur.com/cbI3bKx.png
Every griffen we have it does the same thing. Stam is always in the red. 

Is there any way at all to add a 'add anyway' button when we know 100% that the stats are right? So we don't have to hold off on lving them to wait for a fix or just saying eff it and not adding them at all? 

Maybe a check box that says 'these stats are right' so the add new turns on?

**Comment by cadon** [comment]
Hi, if your server has custom stat-multipliers, please also post them.

The application does only store the extracted levels, so if a level cannot be determined, you cannot save the creature. You can set the level manually in the Tester-tab, though, and then save the creature. In this case, you could click on "Copy to Tester" in the toolbar, and only adjust the stamina until you think that could be the correct level.

**Comment by Taiine** [comment]
No custom stat-multipliers, Only thing edited for this server is baby raising is 4x.

**Comment by cadon** [comment]
Can you post a screenshot of the multiplier-settings of Smart Breeding? With the default-multipliers I get different values than you and cannot extract damage and food. Something seems different there.
