### ISSUE TITLE
Greetings and suggestion

### ISSUE THREAD

**Issue by lnewlfe** [cadon/ARKStatsExtractor#356]
Hello all! Great little app, by far the most indepth I have found. New to Github, still learning the layout. Unsure where general posts go, so sorry for cloggin up the issues forum.

A tip to those trying to get the wild/picked stats for dinos, try out the mod Super Spyglass. It gives all wild and player picked stats from a glance, among other useful info.

I have no affiliation to said mod, just suggesting from my own experience.

Thanks for this.

Lonewolfe

**Comment by cadon** [comment]
Hi, thanks for this post, this mod is very useful. I added it to the https://github.com/cadon/ARKStatsExtractor/wiki/FAQ
