### ISSUE TITLE
Sabertooth Reds (Speed, Food, Damage)

### ISSUE THREAD

**Issue by KJTau** [cadon/ARKStatsExtractor#358]
I originally submitted this via a reddit PM, but after coming here to see others having the Rex Speed issue, I figured I'd share this here in case others are having this issue.

My server is on the latest patch.

I tamed two Sabers today and attempted to input their data into my library. In doing so, the female gets an error with her speed, and the male an error with his speed, food AND damage. 
Both were kibble tamed at 99.8% effectiveness (the female) and 99.7% (the male). The female was wild 150, the male wild 145. 

I've done everything suggested concerning seeing red data fields, including having rebooted my server three times since taming them AND leveling each of them up once or even twice - and then, obviously, re-entering the new stats. I've also gone back and fixed my incorrect multiplier for taming speed (it's x5, so the value should read 5.00 but I messed up with this new library) and that hasn't fixed it. Other tames have worked fine today (such as an Equus and Direwolf) but my rexes are also failing the input due to speed stat.

Thanks for looking!

http://i.imgur.com/ToJPaJG.png
http://i.imgur.com/gdOxZyv.png

**Comment by cadon** [comment]
Hi, the stat-values, especially for speed were changed in ARK v259, I updated the values in 0.23.8, it should work again.
