### ISSUE TITLE
Elk calculating wrong wild level in extractor

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#359]
![capture](https://user-images.githubusercontent.com/1366816/27471165-2dbb8b10-583a-11e7-9df9-f65c02956997.PNG)

As you can see by the image, the stats on the elk is not calculating right.

**Comment by cadon** [comment]
Hi, did you try to change the yellow stats, is there a possible combination, e.g. maybe there is a possible combination with 5 tamed levelups for weight?

**Comment by cyberangel67** [comment]
Yeah I did try, no combination would fix this. But look at the WildLevel it is saying 151

**Comment by cadon** [comment]
The extracted wild-level changes with the extracted taming-effectiveness, which is dependant on the chosen combination of Damage and sometimes Food.
In the last major update for the pc a few days ago there was a nerf to almost all species regarding the speed, sometimes some other values as well. I'm not sure if that already has hit the xbox. It could be related to that.

**Comment by cyberangel67** [comment]
That is a possibility, will keep an eye on it then.

**Comment by cadon** [comment]
I'm closing this for now, hoping it's resolved. If the issue persists, feel free to answer again / reopen.
