### ISSUE TITLE
Include a taming calc

### ISSUE THREAD

**Issue by Asmageddon** [cadon/ARKStatsExtractor#36]
While technically somewhat out of scope of this tool, I think it would be useful to be able to input info on how you're taming a creature, and get stuff like probabilities of stats reaching certain levels(on hover), snapping TE of tamed but leveled creatures to known TE values(honestly, right now I use the online calcs to get the TE value, because the guesses are often wrong)

**Comment by Asmageddon** [comment]
Related: Show an alert when a creature has probably been bred(e.g. estimated TE is 100%)

**Comment by cadon** [comment]
Hi, can you elaborate the last part abut snapping TE to known TE values and "right now I use the online calcs to get the TE value, because the guesses are often wrong"? Do you mean the TE of some entries in the possibilities-list is wrong?

For the other suggestions, I'll add them if I have time (so no promises yet).

**Comment by Asmageddon** [comment]
No, what I mean is that sometimes you get 2000 possible TE values, when in reality it's almost always the TE you get our of a kibble/prime/simple tame, or very close to it, but the extractor doesn't tell you that, and you often end up with creatures described as "Found wild 150, tamed with TE 21.3%", or "Found wild 103, tamed with TE 100%", in addition to stats often being guessed wrong.

**Comment by cadon** [comment]
I understand. For the latter issue, that should be resolved. If you still have a creature showing an impossible wild-level after you extracted it with the current version, send me its stats. That should not occur anymore.

For the other issue, it's like you said, I'd have to add a taming-calculator.
