### ISSUE TITLE
Unable to add breed direwolf

### ISSUE THREAD

**Issue by ToeiRei** [cadon/ARKStatsExtractor#360]
Direwolf baby:
![20170623113339_1](https://user-images.githubusercontent.com/5990591/27476282-6b2fbc14-5808-11e7-839b-bccdbf098bb7.jpg)

ASB Extractor:
![image](https://user-images.githubusercontent.com/5990591/27476144-db9d8824-5807-11e7-8821-10bc045ef623.png)

Multiplicators used on the server:
![image](https://user-images.githubusercontent.com/5990591/27476311-90113184-5808-11e7-8fb2-5c96fb593e3f.png)

**Comment by cadon** [comment]
Hi, that is strange. Do other direwolves work? And other imprinted creatures?

**Comment by ToeiRei** [comment]
others did. The parents are in the library as usual.

**Comment by cadon** [comment]
The values are very strange. Some stat-values would fit to a direwolf with 0% imprinting:
Direwolf (Lvl 102): HP: 3432.1 (47, 0); St: 260 (0, 0); Ox: 480 (22, 0); Fo: 1380 (0, 0); We: 173.4 (1, 0); Dm: 300.7% (31, 0);
I guess the server hasn't updated the stat-values for this creature, i.e. the imprinting-bonus isn't yet applied to all stats, that can happen sometimes. I'd give it a day and then try it again.

**Comment by ToeiRei** [comment]
As the direwolves are a bad breed, they're already dead.
What about some 'whatever - just add it'-button?

**Comment by cadon** [comment]
That's another way to solve this issue :P

The issue with just adding a creature that couldn't be extracted is, the tool internally only saves the level-numbers, not the stat-values. Everything is based on the levelnumber, the stat-value is only shown for the user, but never used in a calculation or elsewhere. A creature without level-numbers can not be handled by the application.
I'll think about an extra list for the extraction-fails, so they can be saved temporarily there and the user doesn't have to re-enter the stat-values each time until the extraction-issue is solved. But creatures from that list couldn't be used in any other functionality of the tool (breeding-planner, comparison of stats), it would be just a storage until they can be extracted.

**Comment by cadon** [comment]
A functionality to save only the stats is added. As said, only the stat-values prevent the creature to be included into anything other functionality (breeding-planner, etc.) so it's currently only a dropdownlist in the toolbar of the saved creatures. This should be probably only used if a creature cannot be extracted for now and to save the re-entering of its stats.
