### ISSUE TITLE
Can't extract bred giga

### ISSUE THREAD

**Issue by joegrace13** [cadon/ARKStatsExtractor#361]
Xbox officials
![img_1364](https://user-images.githubusercontent.com/15167259/27503966-ed10a38a-5847-11e7-866f-2f6b277ee134.JPG)

![capture](https://user-images.githubusercontent.com/15167259/27503944-b83b3968-5847-11e7-9c17-ed74be127671.JPG)

**Comment by cadon** [comment]
Hi, sorry for the late reply. Probbaly the console-multipliers are a bit behind of the steam-multipliers as it takes up to some weeks until the patches are released on the consoles. Probably that's the case here. You can try to download an older release of this software that has the older stat-values, maybe it does work with this. Or you can wait until the patches are released on the consoles. Currently the ARK devs are tweaking a lot of stat-values, so this issue might persist for some time.

**Comment by cadon** [comment]
Another reason can be that the game doesn't update all the stat-values immediately after a cuddle, sometimes it needs some time (see red box at the bottom left). I'm closing this for now, feel free to add another answer if the issue persists.
