### ISSUE TITLE
Help for Multiplers

### ISSUE THREAD

**Issue by theant2222** [cadon/ARKStatsExtractor#362]
![2](https://user-images.githubusercontent.com
![1](https://user-images.githubusercontent.com/29675510/27508752-6b9d2210-58ec-11e7-819d-6ce6e0d13104.PNG)
/29675510/27508751-6a2a80da-58ec-11e7-8321-a9d52f1c7bd2.PNG)

Hello I new to your app is great,I have my own G-portal Server
I have dragged the game ini into the Settings
But somehow not all are converted and at breeding also
How can I find my settings
![3](https://user-images.githubusercontent.com/29675510/27508806-97572328-58ed-11e7-84e8-f86b38c1e220.PNG)
![2](https://user-images.githubusercontent.com/29675510/27508815-b75b8524-58ed-11e7-8f9d-ce5806ed1aa1.PNG)

thanks for your help

**Comment by cadon** [comment]
Hi, offenbar hast du einen mod installiert, der erlaubt die Prägung auf 100% zu setzen. Für Tiere bei denen das angewandt wurde (spezielles Kibble?), stelle sicher, dass zuvor "Adjust to possible Imprinting" in den Einstellungen links unten deaktiviert ist.

**Comment by theant2222** [comment]
ok Danke erstmal habe jetzt abgehakt werde testen habe kein Mod aber mit diesen Einstellungen in 5 Stunden eben 95-100% gehen sehr fad immer wieder um die Dinos kümmern aber dafür top für solo

**Comment by theant2222** [comment]
![4](https://user-images.githubusercontent.com/29675510/27509533-b90852fa-58ff-11e7-8c38-0f90fda72b98.PNG)
schaut schon mal besser aus muss ich noch irgendwelche .json laden Flyer oder so

**Comment by cadon** [comment]
Gestern abend kam ne neue Version raus, mit der geht's: https://github.com/cadon/ARKStatsExtractor/releases/latest

**Comment by theant2222** [comment]
sorry bin nervend habe gestern schon die 0.23.8 drauf gehabt geht einiges besser aber beim gezüchtetn Rex bild oben liest er mir Speed 100 ein hat aber nach zuchtende hat er 150 Speed wenn ich 150 eingebe bleibt es rot und ich kann ihn nicht abspeichern was könnte ich noch probieren
Consider wild Level step und Adjust to possible Imprinting sind abgehakt
Danke für deine Hilfe

**Comment by cadon** [comment]
Komisch, woran mir aufgefallen ist, dass das nicht die neueste Version ist, ist dass der Rex jetzt Tyrannosaurus heißt. Ist vielleicht noch die alte values.json in Benutzung? Steht unten in der Statusleiste "values: 259.0.0"?

**Comment by theant2222** [comment]
![5](https://user-images.githubusercontent.com/29675510/27516202-773c0112-59b5-11e7-944b-a1e0d98262af.PNG)

**Comment by cadon** [comment]
Und es heißt immer noch Rex und nicht Tyrannosaurus?

**Comment by theant2222** [comment]
ja sind noch die alt eingelesenen habe alles gelöscht und nur save eingeladen kann aber jetzt mit ocr nichts einlesen

**Comment by cadon** [comment]
Löschen sollte nicht notwendig sein. Die Namensänderung verläuft automatisch.
Was ist genau das Problem mit der OCR?

**Comment by theant2222** [comment]
kommt nicht mehr in Ark rauf

**Comment by cadon** [comment]
Sorry für die späte Antwort. Ein paar multipliers haben sich geändert, 0.23.10 sollte aktuell sein, wobei noch nicht alle Probleme gelöst scheinen.
Für die OCR gehe auf den OCR-tab und lade die OCR-Datei aus dem json-Ordner, falls nicht automatisch die Standard-Einstellungen für 1920x1080 geladen wurden.
