### ISSUE TITLE
Breeding for max Dinos or Super Dinos

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#363]
I have noticed that if you get a baby with Max stats from all in the library, the program says you already have one with the max stats, but then doesn't display it so I know which one to breed it with to transfer the max stats across to have another.

![capture](https://user-images.githubusercontent.com/1366816/27510273-9c93fb46-5950-11e7-8dce-9810bd46d289.PNG)

**Comment by cadon** [comment]
Hi, it should be chosen as top-creature if you change the Breeding-mode to "High Stats". Maybe you also have to enable "Include Creatures with Cooldown" as well if that creature is currently on mating-cooldown or is not yet adult.

**Comment by cyberangel67** [comment]
I don't use the cool down option so that is not in play and I thought I had tried all the options, but I just selected them and they show up.

**Comment by cadon** [comment]
It could be that the best creature is a baby, they get their maturing-cooldown attached automatically if they're assumed to be a baby (e.g. when entered via the raising-tab).
I'll add the name of the creature to this message-box in the next release so it's easier to see which creature it is.

**Comment by cyberangel67** [comment]
How does it know it is a baby though or even assumes it is?

All I am doing is entering its details as if it is fully grown!

**Comment by cadon** [comment]
If you have an egg-hatching-timer in the raising-tab and right-click on it "Extract values of hatched / born baby" it assumes the baby is just hatched and attaches the full growing-timer to it. If you just enter the stats in the extractor, it's always assumed to be fully grown.

**Comment by cyberangel67** [comment]
Well like I said I am entering it as if it is fully grown.

**Comment by cadon** [comment]
In 0.23.9 the name and the sex of this best creature is now also displayed.
