### ISSUE TITLE
Read Values from ARK Window problems

### ISSUE THREAD

**Issue by Ihmislehma** [cadon/ARKStatsExtractor#365]
Hello,
I am new to this program, so there's the possibility I'm doing something wrong. 
The problem is this: I can't read values with the Read Values from ARK Window button. For most animals, all I get is - nothing. It simply highlights the Wild/Tamed/Bred chouse along with the Since taming no server-restart button. But it does this inconsistently. Some, few, dinos get red stats (mostly bred ones, along with a couple of tamed ones.) This is odd, and I have absolutely NO idea what's going on.
I can take screenshots if needed.
This is weird, and makes Smart Breeding up unfortunately unusable for me currently.

**Comment by cadon** [comment]
Hi, what is the screen-resolution in windows? Supported are 1920x1080, other resolutions may need additional configuration and calibration.

**Comment by Ihmislehma** [comment]
I think I'm not using the OCR feature, adn I thought it and the Read Values to be two different things.
My native resolution is 1920x1080, so that should not be a problem. The weird thing is that for some tames it partially reads the values (some values are red), while for most it reads the values, but does not highlight anything in any color aside from the Wild/Tamed/Bred and Since taming no server-restart. It also does not give level of dino and the name area shows only weird marks instead of anything logical. I have made sure that I have selected the right type of dino before reading.
![fail](https://user-images.githubusercontent.com/29692166/27519269-8adabf5e-59f8-11e7-9326-a15987624845.png)

**Comment by cadon** [comment]
In this screenshot you didn't set a level at all. If you're playing on an unofficial server, please also add the multipliers you're using.

**Comment by Ihmislehma** [comment]
I thought I had added all my settings from file. I'm playing local host. Do I need to manually set the level?

**Comment by cadon** [comment]
Yes, the application cannot know the level alone from the stat-values.

**Comment by Ihmislehma** [comment]
Ah, I see. I'll try that next time, then. Hopefully it fixes things.

**Comment by Ihmislehma** [comment]
Alright, I got it to work with everything, expect health. It shows the right value (in this case, 2952.9), but lists it as red. I don't know why, and will keep testing.

**Comment by cadon** [comment]
If you're on singleplayer see #367, the changed multipliers for sp change HP and damage.

**Comment by Ihmislehma** [comment]
After some testing: I think I'm finally getting the hang of this program (being really tired while trying to learn doesn't help, whoops.) Every now and then one or two stats go red, and stay red, no matter what I do. Usually this is health, along with weight/food. In most cases the stat number is exactly right, and it stays red for whatever reason. It doesn't seem to be able to get the wild levels for whatever reason.
I have tried to make sure the settings are right by dragging the Game.ini and GameUserSettings.ini to the settings windows. I know they are right, since they are from my own game.
![fail02](https://user-images.githubusercontent.com/29692166/27524487-fef7a8da-5a3d-11e7-8d22-57f3133e2bd9.png)
No matter what I do, the red values stay red, even while displaying the right stats.

**Comment by Ihmislehma** [comment]
Ahh, sorry, got saw that message only after writing previous post. Will try to fiddle with the stats and see if that fixes things.

**Comment by Ihmislehma** [comment]
Alright, so even after fiddling with the settings some more and making sure they are the same as in my Game.ini and GameUserSettings.ini, I still have the Health red. Only the health. I'm not sure what I'm doing wrong here.
Also, could I get a little more info on what the Taming effectiveness range to test means and how to correctly use it? I doubt it's the culprit, but I'm willing to test everything.

**Comment by cadon** [comment]
Hi, sorry for the late reply. The latest patches seem to have changed some multipliers. Try the latest release 0.23.10 if it works with that.
The taming effectiveness (TE) range narrows the possibilities of the possible levels. If you kibble-tamed a creature, the TE is usually above 90%, so you can reduce the combinations on the yellow stats by setting the TE to a close range. If you have no idea what the TE was, you can set the range from 0 - 100%, the downside being there are more options for some stat-combinations.
