### ISSUE TITLE
Tamed Dino Extraction Health is Always Red

### ISSUE THREAD

**Issue by Evehly** [cadon/ARKStatsExtractor#366]
Hello,
I've been quietly using this tool for a little awhile now (I'd say about five months) without any issues that I haven't been able to work out myself, but recently after grabbing the latest update and playing ark after a short hiatus, I've come across a problem with extraction that I just can't seem to figure out how to solve.

It seems like no matter what tamed dino I try to extract, the health is always red. I've triple-checked my multipliers to make sure they're correct, I've tried extracting with wild-level steps turned on and off, I've tried checking and un-checking the server-restart box, I've tried adjusting the taming-effectiveness range, and I've tried restarting ark to see if the stats weren't properly updated, but nothing has worked and the health still remains red. So far I've tested this with tamed Parasaurs, Pteradons, Dilos, and Dodos. Regardless of whether they have leveled stats or they're a fresh tame, they're all having the same problem.

So far I haven't had any issues extracting stats from wild dinos.

Screenshot of a wild Parasaur's stats. 
![screen1](https://user-images.githubusercontent.com/29691514/27518335-6fa92a92-59ab-11e7-8209-c977df8245de.jpg)

I extracted his stats with no problem.
![screen2](https://user-images.githubusercontent.com/29691514/27518343-a42ab024-59ab-11e7-9174-8b5de752f9fd.jpg)

Here are his stats right after taming him. He was tamed with a Taming Effectiveness of 99.8%
![screen3](https://user-images.githubusercontent.com/29691514/27518345-c4642366-59ab-11e7-9e70-2f4a05fc2d33.jpg)

After trying to extract him a second time, the health is red and the extractor is assuming that I'm pumping a bunch of levels into different stats. Especially damage.
![screen4](https://user-images.githubusercontent.com/29691514/27518354-07252312-59ac-11e7-86b7-9d68e808405e.jpg)

Lastly here are my multipliers.
![screen5](https://user-images.githubusercontent.com/29691514/27518404-4f0c95ce-59ad-11e7-891b-27c107fe9732.jpg)

After sitting here for hours trying to get the extractor to work with tamed dinos, I'm at a complete loss as to what I'm doing wrong.

**Comment by cadon** [comment]
Hi, did you recently change some multipliers on the server? It looks like the TameAdd-multiplier for HP is altered. If you set it to 0.44 (instead of the default 0.14) it works. Maybe that change was done unintentionally, or mixed with the TameAff-value of HP (which is 0.44 by default)? TameAff of the health doesn't affect any species, afaik.

**Comment by Evehly** [comment]
I just switched TameAdd value to .44 and health is no longer in the red, which is great. But now I'm left with an issue where the extractor thinks the parasaur's wild level is much lower than it actually is. As a result it's thinking that I have a bunch of levels pumped into damage (Also thinks I'm putting levels into some of the other stats, but I have the option to choose 0 with them; with damage I do not.) The parasaur has not been leveled at all.
![screen7](https://user-images.githubusercontent.com/29691514/27518772-75416f14-59b5-11e7-9e24-66ba9c20a4ed.jpg)
I tried switching the TameAdd-multiplier for Damage to .44 as well to see if that would fix it, but it did not.

Also, while switching the HP value of TameAdd did work, I don't know why that is. The TameAdd multiplier in my game.ini is .14. I checked the game options in Ark to make sure it's consistent with the config, and it is.
![screen6](https://user-images.githubusercontent.com/29691514/27518735-ac1e29c4-59b4-11e7-8469-b86eac53aee9.jpg)
Could this possibly be some sort of bug on ark's end?
I'm playing singleplayer by the way, in case that makes any difference.

**Comment by cadon** [comment]
You're the first one reporting this issue, but most people are playing multiplayer, I guess.
Changing TameAdd and TameAff both to 1.0 seems to get correct results. The damage is unusually high, with the multipliers both to 1.0 the level of the damage also seems more reasonable. Did you change any multiplier before or after you tamed the parasaur or did these issues appear just like that?

**Comment by cadon** [comment]
Hi, another user just posted this link, which explains it all: https://survivetheark.com/index.php?/forums/topic/203535-patch-259-hibernation-single-player-settings/, the multiplayer in the singleplayer were changed with the last update.

**Comment by Evehly** [comment]
Huh, I hadn't heard of this change until now.
Well after adjusting the multipliers accordingly, everything seems to be working perfectly now. Thanks for the help, man. I appreciate it!
