### ISSUE TITLE
OCR-File 'json/ocr.json' not found

### ISSUE THREAD

**Issue by Morning32** [cadon/ARKStatsExtractor#369]
So after i downloaded the new update i have been getting this error message

https://gyazo.com/cef1b46b83426d06798dbb133270b1e7

And i cannot extract stats anymore and i have no idea what it means.

**Comment by cadon** [comment]
Ah, I renamed the ocr-file. Go to the OCR-tab, click "Load OCR config", go to the json-folder of the application and choose the ocr with your resolution.

**Comment by cadon** [comment]
An automatic fix for this is now included in 0.23.9, if you haven't changed the ocr-config manually yet.
