### ISSUE TITLE
Gray out species with no valid pairings in the breeding plan.

### ISSUE THREAD

**Issue by Asmageddon** [cadon/ARKStatsExtractor#37]
Also, it could be potentially useful to further differentiate between "no valid pairings", and "valid pairings with unavailable animals".

**Comment by cadon** [comment]
In the new version species without enough (i.e. at least one male and one female) available creatures are not shown.

**Comment by Asmageddon** [comment]
Personally I'd prefer them to just be grayed out, in order to be able to see the breeding times.
