### ISSUE TITLE
Add Checkbox for "this really is 100% imprint" to extractor, not options

### ISSUE THREAD

**Issue by cassfalg** [cadon/ARKStatsExtractor#370]
I'm on official, and it is actually not that uncommon to see true 100% imprint bonus from some of the people in my tribe. Basically, imprint bonus is calculated based on total maturation time divided by four hours, when in practice the interval is random and between 3 to 4 hours. If we assume an even distribution we get an average interval of 3.5 hours, so in the time slot allocated for 7 imprints (two days), you're likely to actually manage 8 - provided you don't sleep for more than the imprint interval and don't have other appointments of course. ;)

This lead to some issues with the extractor in the past, since 100% always was rounded down to the nearest value. Now with the option to turn that off it works, but that would mean changing the options rather often. A more streamlined solution from a usability standpoint may be something like a checkbox for "yes, this is 100%"?

**Comment by cadon** [comment]
I moved the checkbox under the imprinting input.
