### ISSUE TITLE
Light/Poison Wyvern damage pops in red

### ISSUE THREAD

**Issue by CheekyPJ** [cadon/ARKStatsExtractor#372]
Hello there, I just hatched a lightning wyvern lvl 170 and for some reason the melee stat pops in red for me.  I re-wrote everything and nothing changes.
Stats: 
![image](https://user-images.githubusercontent.com/29117490/27732230-94f963be-5d90-11e7-9a10-506da0707db0.png)
In app: 
![image](https://user-images.githubusercontent.com/29117490/27732244-a9645d18-5d90-11e7-8af9-c33b1779e370.png)

TY for help.

EDIT: Same for the little poison one.
Stats: 
![image](https://user-images.githubusercontent.com/29117490/27732314-ee92ca3c-5d90-11e7-90de-194801c8a2e8.png)
In app: 
![image](https://user-images.githubusercontent.com/29117490/27732323-fb921f12-5d90-11e7-8e8b-5596490e0d7d.png)
I already used the app today on baby tapis and it worked fine.

EDIT2:
Infact every time I try to type in wyvern stats melee stat is the only one that pops in red.

**Comment by Sxw1212** [comment]
I can confirm that this is happening with mine too.

**Comment by CheekyPJ** [comment]
Hello, the recent update of the app has fixed the issue therefore I'm closing this request. Thank you.
