### ISSUE TITLE
One Red Bar

### ISSUE THREAD

**Issue by PachytheDino** [cadon/ARKStatsExtractor#374]
I just tamed a Trike named Bamboozled. He came out to be level 209. It was a Wild 140 Male Trike. For some reason the Speed Stat is always in a red bar. I followed all the ways to fix the red bars(or impossible stats) and leveled it up 1 and put it into speed. So now its 210. But It does not fix it. The last step is posting it on your GitHub. Hopefully you or somebody can help me. 

![help](https://user-images.githubusercontent.com/29826092/27766321-5b877a34-5e9a-11e7-8c65-e063c68f51a0.jpg)

**Comment by cadon** [comment]
Hi, probably you don't have the lateste release. Recently some stat-values were changed in the game.
