### ISSUE TITLE
Adding bred Unicorn stats...

### ISSUE THREAD

**Issue by valarhan** [cadon/ARKStatsExtractor#375]
Troubles adding female Unicorn - Here's the screen of settings in app and the unicorn's stats... what am I doing wrong this time? =)
![image](https://user-images.githubusercontent.com/27072415/27813194-0c51ff62-6029-11e7-9836-21ff7215078f.png)

![image](https://user-images.githubusercontent.com/27072415/27813199-1a1d9368-6029-11e7-97b8-ce0e3d934d82.png)

**Comment by cadon** [comment]
Hi, if you're on an unofficial server, do you have set all the multipliers correctly? Also make sure to uncheck the "Exactly, don't adjust"-checkbox under the imprinting, it should only be checked if you have exactly 100% imprinting.

**Comment by valarhan** [comment]
Official Server... And as far as I know all the multipliers are correct..

**Comment by valarhan** [comment]
But it's a recently aquired mare, I'm not sure of when it was raised (during an event or not)

**Comment by cadon** [comment]
Setting the cuddle-interval multiplier to 0.5 makes it work. It's probably born during an event that changed some multipliers.

**Comment by valarhan** [comment]
![image](https://user-images.githubusercontent.com/27072415/27839230-ab366cb4-60a4-11e7-939c-7ed25ba00cae.png)

**Comment by valarhan** [comment]
Okay, adjusted the settings as suggested, still no go... =(

**Comment by valarhan** [comment]
After adjusting stats it changed 'a little' 
![image](https://user-images.githubusercontent.com/27072415/27839311-20fab662-60a5-11e7-90ee-ccec56b1cadf.png)
![image](https://user-images.githubusercontent.com/27072415/27839320-355fbd28-60a5-11e7-97f9-c0f7d47b38bd.png)

**Comment by cadon** [comment]
You still have this checkbox checked.

**Comment by valarhan** [comment]
Which checkbox?? =)

**Comment by valarhan** [comment]
If I uncheck the "Exactly, don't match" it alter's the imprint to 82% (and some decimal points, and still won't go in.. like so...
![image](https://user-images.githubusercontent.com/27072415/27839602-3f8a7a5c-60a7-11e7-9fbd-9d7a158cc13a.png)

**Comment by cadon** [comment]
You don't have set the cuddle-interval to 0.5, the number of cuddles is 25x then. The extracted values are:
Unicorn (Lvl 122, Impr: 86.4%): HP: 1126 (15, 0); St: 2856 (41, 0); Ox: 465 (21, 0); Fo: 5453.5 (21, 0); We: 558.3 (18, 0); Dm: 180.6% (5, 0); Sp: 137.3% (0, 0); To: 4069.2 (121);

**Comment by valarhan** [comment]
The regular cuddle interval or the event interval? Cause the event interval IS set at .5... ?
![image](https://user-images.githubusercontent.com/27072415/27880136-c19e27ba-6178-11e7-8251-8cd7db7cdbc5.png)
I'll try changing the regular interval - I've now got two babies from this momma and I'd really like to get her stats plugged in =)

**Comment by valarhan** [comment]
NM, adding in the .4 to the imprint and adjusting both the Regular Cuddle-Interval and the Event Interval - now the momma is in the program - thanks a bunch!
