### ISSUE TITLE
Tamed Equus Stats

### ISSUE THREAD

**Issue by ghost** [cadon/ARKStatsExtractor#376]
Cant seem to get these stats to work. 

![settings](https://user-images.githubusercontent.com/13612798/27845170-03515e98-60f2-11e7-82dc-457cf169a851.jpg)
Server Settings: 
PerLevelStatsMultiplier_DinoTamed[0]=2.00
PerLevelStatsMultiplier_DinoTamed[1]=2.00
PerLevelStatsMultiplier_DinoTamed[2]=2.00
PerLevelStatsMultiplier_DinoTamed[3]=1.00
PerLevelStatsMultiplier_DinoTamed[4]=2.00
PerLevelStatsMultiplier_DinoTamed[5]=2.00
PerLevelStatsMultiplier_DinoTamed[6]=2.00
PerLevelStatsMultiplier_DinoTamed[7]=2.00
PerLevelStatsMultiplier_DinoTamed[8]=2.00
PerLevelStatsMultiplier_DinoTamed[9]=2.00
PerLevelStatsMultiplier_DinoTamed[10]=2.00
PerLevelStatsMultiplier_DinoTamed[11]=2.00
PerLevelStatsMultiplier_DinoTamed_Add[0]=2.00
PerLevelStatsMultiplier_DinoTamed_Add[8]=2.00
PerLevelStatsMultiplier_DinoTamed_Affinity[0]=2.00
PerLevelStatsMultiplier_DinoTamed_Affinity[8]=2.00

Max Wild Level = 180
Max Tamed Levelups = 255

![gamestats](https://user-images.githubusercontent.com/13612798/27845168-0337af98-60f2-11e7-9b8f-c47db10050d4.jpg)
![stats](https://user-images.githubusercontent.com/13612798/27845169-034c4002-60f2-11e7-91a7-865ef3e39ca2.jpg)

**Comment by cadon** [comment]
Hi, did you change the stat-multipliers recently? If you set HPwildLevel to 1.5 and St wildLevel to 2.0 it works with reasonable levels.

**Comment by Rinjii19** [comment]
Health is working but now stam isnt.

**Comment by Rinjii19** [comment]
Changed the stam to 1.5 wild level and it seems to work now.

**Comment by VolatilePulse** [comment]
Closing due to age and inactivity.
