### ISSUE TITLE
JSON Stat additions not fully functional

### ISSUE THREAD

**Issue by Letoric** [cadon/ARKStatsExtractor#380]
Hi Cadon,
 It appears that the custom dino input you've permitted, is not taking into account the 'Tamed Base Health Multiplier' which we discussed earlier this year, was added in. Any chance you can add that as something that can be put into the json?
![image](https://user-images.githubusercontent.com/26984630/28097689-5b2e3f98-6677-11e7-8b28-4675fa220a4b.png)

That's an example entry from a dino status component.

**Comment by cadon** [comment]
Hi, that should work, I just tested it again. Where do you see the issue exactly, which species?

**Comment by Letoric** [comment]
New dino. You haven't given us a spot to set this for new dino we introduce
through json

**Comment by cadon** [comment]
I'm still not following. Did you edit the values.json and added a new species with a TamedBaseHealthMultiplier (TBHM) that doesn't work or did you add a new species with a custom json (like the classicFlyers.json) with a TBHM that doesn't work? The TBHM has to be defined in the species-object in the json, maybe you put it in the stats-array? Can you post the json-entry for that species that doesn't work?

**Comment by Letoric** [comment]
Hi Cadon. I didn't inspect your json, I followed your post for the attributes that should be in json for custom dinos. If you've added that field as something that can be added to the custom json and just omitted updating that, or I overlooked it, that's probably where the confusion is.

**Comment by Letoric** [comment]
Looks like that's what took place. When I popped open what you did with Classic Flyers, it appears you have added that as a json entry, but just didn't update https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values

I'm all set, you can close this, but you might want to make an update to that wiki page.

**Comment by cadon** [comment]
I added it to the wiki-page, thanks for pointing this out.
