### ISSUE TITLE
Trike not being extracted right, but is in a way

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#381]
This is going to be hard to explain, but 1 Male and 1 female trike where bred and the babies where extracted right and the female parent seems to be extracted right, but the male parent seems to be wrong.

As you can see by the image the baby's picked up the correct stat on the father though.

![capture](https://user-images.githubusercontent.com/1366816/28123773-332f2a04-6765-11e7-825f-3abceaff028f.PNG)
![capture1](https://user-images.githubusercontent.com/1366816/28123776-35c0aa5e-6765-11e7-973f-054bebb70064.PNG)

**Comment by cyberangel67** [comment]
Also the actual stats of the Male

![capture](https://user-images.githubusercontent.com/1366816/28124722-d907184a-6767-11e7-8882-8a8447fb1161.PNG)

**Comment by cadon** [comment]
Hi, probably during the extraction of the father trike there were yellow stats and of the multiple combinations there is another combination that is correct. You can re-extract a creature by right-clicking it and selecting "copy values to extractor" - "current values". After the extraction choose a different combination of the possible distributions in the list on the right.

Did you switch to the PC-version or are mods possible on consoles now?

**Comment by cyberangel67** [comment]
I have tried all the combinations available and the only one that will allow for saving is the one that I have above.

When I get a chance, I will grab a screen shot of the 3 that are yellow and the combination that it allows.

**Comment by cadon** [comment]
This worked for me: 
![trike](https://user-images.githubusercontent.com/8763269/28204836-c98aa8b4-687f-11e7-895a-b1948fd1cc90.png)
