### ISSUE TITLE
Dire Bear not extracted right

### ISSUE THREAD

**Issue by 2x3m** [cadon/ARKStatsExtractor#384]
Hi there
first i want to say thanks for your awesome tool
it calculated everything right before today but now i have a problem with extracting a breeded Dire Bear i play on an official server.

Heres the Screenshot: 
![20170714165714_1](https://user-images.githubusercontent.com/30181580/28220139-aa5e4a38-68be-11e7-999e-f859622cc4b7.jpg)

i hope you can help me.
Best Regards

**Comment by cadon** [comment]
This bear was probably rised during an event that increased the mature-speed. Setting it to 1.5 makes it work.
