### ISSUE TITLE
Seemed to be faulty update that wasn't

### ISSUE THREAD

**Issue by oneofsharp** [cadon/ARKStatsExtractor#385]
It took me a week or so but I got it working.  and it was working well.  I have a screen shot of settings with some of my saves showing.  I got a notice that there was an update.  I downloaded it and the version number was the same as the download I did 10 days ago.  I extracted it and installed it anyway.  I use a quetzel mode and when I opened up the newly installed statsextractor it told me it couldn't find it so I added it and in the process I learned the json file should be in the save folder. So now when i start it it does not ask for it.  I dropped my game.ini  into the exactor and adjusted the egg hatch multiplier. It show up as 1 for some reason.  I set my server at 6 so don't know why the game.ini didn't know that.  I can not extract anything now.  I even went back to a few of the dinos that I had done and it would not read them again.  I've tried everything.  I got it to work before by not setting any multipliers my self but just dropping either .ini file and adding the new settings for the quetzal.  I have attached two screenshots and the quetzal json file for you to look at. Let me know what else you might need. 
![dino breeding multipliers](https://user-images.githubusercontent.com/30129015/28238942-3434b2ce-6914-11e7-8c2f-7aa4fa74e01e.jpg)
![smart breeding settngs](https://user-images.githubusercontent.com/30129015/28238947-4a844b70-6914-11e7-8cbd-108171f064d3.jpg)
[Ark Smart Breeding - Copy.txt](https://github.com/cadon/ARKStatsExtractor/files/1150268/Ark.Smart.Breeding.-.Copy.txt)

Bu the way when I do add the json file I get a report... Species with changes stats 0  Species added 1

I'm so missing this thing the animals that I let wander are getting way ahead of me.  Thank you so much for this (more than just a tool) tool.  Let me know what I can do...

**Comment by cadon** [comment]
Hi, do you use the "SinglePlayer settings"? This checkbox changes all multipliers again.

**Comment by cadon** [comment]
Hi again, I just noticed you're using a very outdated version of Smart Breeding. Make sure you have the most recent one from here: https://github.com/cadon/ARKStatsExtractor/releases/latest

**Comment by oneofsharp** [comment]
I did get the update and re-entered my game.ini file and the NCquetz JSon file.  Adjusted the few problems I had with OCR and it works fine now.  However I believe that it will be a challenge to use the program for every dino I have.  I use the mod Auto Trough.  It has an auto trough for the babies.  It does all the imprinting and even will allow me to speed up the growth to where the dino becomes an adult in just a few minutes.  Which I don't usually use.  I set the feeders out in the field where the herd is allowed to wander until they become so many that they clump together.  20 or 30 animals.  I've removed the ones I thought were the best to begin a more focused breading program.  When I try to use smart breading on any of those dinos I get numerous red readings.  ON any normal tamed or bred dino I get nice green and yellow readings, good totals and no red.  I'm going to assume that the math on all those auto trough raised dinos has been altered and that they will always mess up any readings.  Thanks very much for your app and the work you have put into it and the help you have been kind enough to supply.

**Comment by VolatilePulse** [comment]
This issue appears to be similar to the S+ Nanny issue from a while back. Due to some apparent desync issue between the server and the save file, stats aren't always updated due an Imprinting Bug. The age of this issue couple with more recent realizations forces me to close it.
