### ISSUE TITLE
Rex imprint not right

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#386]
I don't see what is wrong here

![capture](https://user-images.githubusercontent.com/1366816/28244780-b28ca680-6a37-11e7-8139-b9926181e23d.PNG)

**Comment by cyberangel67** [comment]
btw the Rex actually shows 11% imprinting

**Comment by cadon** [comment]
Is this a fresh hatched rex? Were the multipliers changed since it hatched? Do you remember how often do you leveled it up? It seems there's an issue with the torpor-value or the total-level-value.

The game only shows rounded values for the imprinting, e.g. 10.8% is shown as 11% ingame.

**Comment by cyberangel67** [comment]
Yes it was a freshly hatched rex, there are 3 with this issue and no the server multipliers where not changed. I am aware of the rounding issue and it goes to 10.8, when trying all 3 of these rex's have issues at the same time I was doing Trikes, Hyenas and Ankylo's and only these rex's have issues.

And yes, the server has been reset 3 times since I raised this ticket and still can't add them.

**Comment by cyberangel67** [comment]
Tried this again today and for some reason it just worked. Put it up to the Ark Gods to know why now.
