### ISSUE TITLE
Wrong health

### ISSUE THREAD

**Issue by freshrebel** [cadon/ARKStatsExtractor#388]
i'm playing single player and i entered the stats of my T-Rex but the health stat seems not to fit. i checked it and it is definitely right
![image](https://user-images.githubusercontent.com/10060982/28276410-235a50a8-6b17-11e7-8e70-1fc007207245.png)

![20170717174938_1](https://user-images.githubusercontent.com/10060982/28276904-9045d254-6b18-11e7-8dd2-5c673e67f5d5.jpg)

i think it has to do with settings but i have tried every possible setting:
- the settings from a file in the config folder
- the settings from the main menu->host/local
- the preset official player settings
- the all on 1 settings

if i check the stats with the stat testing, i see that the health should be 37860,0 but ark says 31272,8. is there a change in ark that is not implemented in the program yet? or am i doing something wrong?

**Comment by cadon** [comment]
Did you change the settings recently? Do you have "Use singleplayer options" enabled? You can try to level up health once to make it recalculate the value, sometimes it's shown not correctly after stat-multipliers are changed.

**Comment by freshrebel** [comment]
i'm playing pure vanilla so i'm not changing any settings except for the difficulty level is set to 1.
use single player options is enabled.
i'll try that and let you know

**Comment by freshrebel** [comment]
nope the health went to 32004.9 and that is also not working

**Comment by grey1209** [comment]
It seems to me that the modifiers of health and damage have been changed in a SP. After some experiments I use these settings:
![settings](https://user-images.githubusercontent.com/30283364/28400042-d3d7ce9a-6d21-11e7-9f3b-d49e509453fd.PNG)
This is what your Rex looks like:
![extracted](https://user-images.githubusercontent.com/30283364/28400052-e0c3c4ec-6d21-11e7-8dc7-c153ec90b1d0.PNG)
![extracted2](https://user-images.githubusercontent.com/30283364/28400056-e5ad659e-6d21-11e7-8921-43de09f7b150.PNG)

**Comment by freshrebel** [comment]
that worked :+1:

**Comment by cadon** [comment]
@grey1209 thanks a lot for the updated SP-values, I'll add them in the next release.
