### ISSUE TITLE
Bred argentavis stat issue

### ISSUE THREAD

**Issue by joebywan** [cadon/ARKStatsExtractor#39]
Bird I just bred

http://i.imgur.com/Mzl7iJk.png

For some reason it's not taking the damage value that has been working on all of my previous Argentavis in the software.

**Comment by joebywan** [comment]
Just checked it with 18.6, and it works.  So it's something broken in v19

**Comment by cadon** [comment]
Thanks for the report. This bug is fixed in 0.19.1.
