### ISSUE TITLE
Cannot Extract any dino information

### ISSUE THREAD

**Issue by MutantRex2** [cadon/ARKStatsExtractor#391]
Hello,

After gettings my servers config put into the settings, I went to extract data from a dino by opening its inventory and clicking read from ark window and nothing happens.

Can anyone help me get this working?

Thank you

**Comment by cadon** [comment]
Hi, probably your screen-resolution isn't supported by the tool (currently only 1920x1080 and 1680x1050 is). You can create you own OCR-profile, though, see https://github.com/cadon/ARKStatsExtractor/wiki/OCR for more infos.
Or, you can just enter the stats manually, if the OCR isn't working.

**Comment by MutantRex2** [comment]
I've been trying to follow along the OCR wiki guide there, the program keeps crashing on me when I try to line up the boxes on the manage tab of the OCR.

first on drag-n-drop OCR output gives me this error:

Error while calibrating: probably game-resolution is not supported by this OCR-configuration.
The tested image has a resolution of 2560×1440 px.
![capture1](https://user-images.githubusercontent.com/29512875/28447464-c11016be-6d85-11e7-99a8-59d8f7932bf7.PNG)

Then when trying to manually set the boxes from the labels tab I get this crash error:
![capture2](https://user-images.githubusercontent.com/29512875/28447500-f97b3dd0-6d85-11e7-893d-d17eccae58e1.PNG)

**Comment by cadon** [comment]
Hi, can you post the info that appears after you click on "Details" on the crash-message?

**Comment by cadon** [comment]
Closed due to inactivity.
