### ISSUE TITLE
Extractor reading x in x / y of stats

### ISSUE THREAD

**Issue by BevoLJ** [cadon/ARKStatsExtractor#392]
So I did a lot of OCR tweaking and no doubt messed something up.  Was hoping someone might be able to point me in a direction to correct my mistake.

version 0.23.11
Resolution: 2560x1440

I have the OCR reporting correctly for the most part (dino name and tribe name messes it up).  All the stats seem to be correctly reported my OCR.

![1](https://user-images.githubusercontent.com/5301213/28345793-0f0fd04c-6bf2-11e7-8672-c5fd3886529e.PNG)

My issue is that the when reading from Ark Window in the extractor it keeps reporting the x portion of x / y.  See food and torpor in below image (note: oddly weight seems fine): 

![2](https://user-images.githubusercontent.com/5301213/28345845-6ff2ac2c-6bf2-11e7-98e2-72e55c04fa5a.PNG)
  
and example of my current OCR settings: 

![3](https://user-images.githubusercontent.com/5301213/28345893-bf5edce0-6bf2-11e7-8359-4e976e5030d2.PNG)

**Comment by cadon** [comment]
Hi, thanks for that, it was a bug related to the OCR sometimes recognizing a comma instead of a dot. It will be fixed in the next release.

**Comment by cadon** [comment]
New version with fix is released.

**Comment by MutantRex2** [comment]
BevLo Do you think I could have your OCR profile? I have been trying to set mine up for 2560x1440 but the smart breeder kills itself every time I try to make one.

**Comment by BevoLJ** [comment]
@cadon Wanted to stop by and confirm all is working great now.  Went to coast so sorry it took a few days to confirm that for you.  Thank you for the fix, I assumed I broke it!  =D  <3

@MutantRex2 My name, level and tribe all show up a gibberish.  I enter those manually which is not an issue for me.  Although if I could get the level to work that would help speed up my extractor work.  =)

**Comment by MutantRex2** [comment]
@BevoLJ  would it be a super big inconvience for you to upload your .json here. If so no worries, I can input my stats manually.

Thanks for the reply
