### ISSUE TITLE
Raising Tab that shows Parents stats

### ISSUE THREAD

**Issue by glitchsniffer** [cadon/ARKStatsExtractor#393]
I would like to see the stats of the parents on the Raising tab.  Maybe below the info in the window on the left.  This would make it a lot easier to see if you hatched a baby to keep or to get rid of, based on the parents.  It would also keep me from adding a new creature only to find out that its got all of the worst stats from the parent.  I think the best way to show it would be to have the raw stats of the parents instead of the number of levels, or both.  Maybe even highlight what stats were highest.  That way one could easily compare the stats to the baby before adding it to the library if it is a keeper.  This would help me immensely as i would not have to keep writing down what stats to look for on the baby.

**Comment by cadon** [comment]
Hi, good idea, I'll add that in the next release.

**Comment by cadon** [comment]
New version with this feature is released.

**Comment by glitchsniffer** [comment]
This looks awesome!  Only thing is can you add the parents name to it?

**Comment by cadon** [comment]
Yes, this will be in the next release.
