### ISSUE TITLE
Mosasaurus Dmg

### ISSUE THREAD

**Issue by Maedean** [cadon/ARKStatsExtractor#394]
Hi there,

Something wrong with the dmg calculation. When extracting stats on a freshly tamed Mosasaurus (lvl 150 pre-tame, lvl 224 post-tame) it gives an error on Food and Damage.

Upon closer inspection through the use of Stat Testing and the 99.5% TE it seems that the problem lies in Damage. Damage on the mosa is at 316,2%, but on Stat Testing it jumps from 314,5% to 320,3%.

Regards,
Maedean

**Comment by cadon** [comment]
Hi, are you using the single-player-settings? They were recently changed, and the tool wasn't updated yet. If you're using the single-player options, set HP tameAdd to 0.5, HP tameLevel to 0.425, Dmg tameAdd to 0.5 and Dmg tameLevel to 0.4

If that's not working or if you're not using the SP-settings, please post your stat-multipliers and a screenshot of the inventory of the mosa.
