### ISSUE TITLE
Extractor not working for 1920x1080

### ISSUE THREAD

**Issue by Jax233** [cadon/ARKStatsExtractor#395]
If i try to extract the values from ark, it tabs to the ark screen then nothing happens. if i make a screen shot and paste it in the blank window it reads all the values correctly with out me changing anything.

When i try to use the overlay i get an error message saying "not calibrated for my display" 
What am i missing?

**Comment by cadon** [comment]
Hi, the resolution in Smart Breeding has to be set to the one that you're using in windows, not the ingame-resolution. Also, if you're using multiple screens, that could be an issue.

**Comment by Jax233** [comment]
Hi the default windows resolution is 1920 x 1080 
I only have 1 screen

**Comment by Jax233** [comment]
![image](https://user-images.githubusercontent.com/30302856/28478966-686efc14-6e52-11e7-9f8e-a269a5981a64.png)

**Comment by cadon** [comment]
Is the default-resolution of your screen also 1920x1080 ( if you look in the screen-properties from the desktop)?

**Comment by Jax233** [comment]
Yes it is

**Comment by Worldgate** [comment]
Anyone have a 1680x1050 one that works?  I've tried but no luck so far.

**Comment by cadon** [comment]
@Jax233 you can try to increase the "wait before screencapture"-value in the OCR-settings (in the settings of the application, not the OCR-tab), maybe that resolves it.

@Worldgate not yet. Did you try to make one? https://github.com/cadon/ARKStatsExtractor/wiki/OCR

**Comment by Jax233** [comment]
I have got it working sort of i found i have the desktop setting at 125% zoom so the resolution was not true 1920 x 1080 it still bugs the names on some dinos but i will try tweaking the orc

**Comment by cadon** [comment]
Thanks for the feedback! I didn't know the zoom also affects the ocr.
