### ISSUE TITLE
Bred Procoptodons not extracting correctly

### ISSUE THREAD

**Issue by rhyokin** [cadon/ARKStatsExtractor#396]
Hello,

Bred Procoptodons do not seem to be extracting correctly.  Using the default settings for multipliers on our server, so default settings configured in the program as well.   Tamed ones appear to be working normally.

Below are a couple of screenshots of a bred one and a tamed one.  Note that, for the bred one, one point was put into speed to see if it would negate any issues.

Bred:
https://gyazo.com/8af8acc73733723070e9b54e7c4e1974

Tamed:
https://gyazo.com/aec94028420c2ebd3724bb049154e080

Multiple other dino types that i've bred work fine, just not Procoptodons.

Thanks.

**Comment by cadon** [comment]
Hi, procoptodons have a long history of not working correctly (e.g. #19, #120), probably during a stat-adjustment they got shortly after being released, something is still messed up with them. Usually they work after some while, when the server recalculates their values, usually after some restarts or some days.

**Comment by VolatilePulse** [comment]
Even almost 3 years later, the Procoptodon still has these issues. This is an Ark bug and can't be resolved easily enough by us.
