### ISSUE TITLE
Dinos with no oxygen cause torpidity to be low in calc

### ISSUE THREAD

**Issue by Revenge282** [cadon/ARKStatsExtractor#397]
I am primarily testing this with Carbonemys on patch 263.0, and I have seen this on previous patches back to 262.

Extracting a Carbonemys stats works fine, adds to library accurately.  When you go to edit the creature, the stat testing tab has oxygen at 0 (expected), but torpidity is far lower than what the dino actually has (keep in mind this was correctly inputted at time of extraction).  I have to manually raise the wild level of torpidity to match the overall level of the Carbonemys.

Since torpidity is a sum of the total wild levels, the zeroed oxygen seems to negatively affect amphibious creatures when they are edited from the library.

**Comment by cadon** [comment]
Good idea, I'll improve that in the next release.

**Comment by cadon** [comment]
New version with better handling of the torpor-level is released.
