### ISSUE TITLE
Problem 1 wild level error

### ISSUE THREAD

**Issue by Simpleskill** [cadon/ARKStatsExtractor#398]
Hello
i started used this APP today and i spend all the day trying to figure out the problem, i am trying to learn about perfect dino stats in my SinglePlayer Server.
So i : 
- Spawn a Woolly Rhino level 50.
- Type " Dotame".

After the tame, the Rhino gets level 75 because i was 100% Taming Effectivness.
When i run the app is saying that my Rhino has been found at lvl 51 and not 50...
whats going on? what can i do?
on official servers i tried it with a random dodo lvl 27 and it worked...
it might be the settings, anyone can help?
![screenshot_2](https://user-images.githubusercontent.com/30311546/28405913-40ae5ae4-6d26-11e7-99ab-cdd13d557f76.png)

Thats my settings:

![screenshot_3](https://user-images.githubusercontent.com/30311546/28405947-645e3928-6d26-11e7-8849-c04bb4942e5c.png)

Thats my Game.ini:

`[/Script/ShooterGame.ShooterGameMode]
BabyImprintingStatScaleMultiplier=1.000000
BabyCuddleIntervalMultiplier=1.000000
BabyCuddleGracePeriodMultiplier=1.000000
BabyCuddleLoseImprintQualitySpeedMultiplier=1.000000
PerLevelStatsMultiplier_DinoTamed[0]=0.200000
PerLevelStatsMultiplier_DinoTamed[1]=1.000000
PerLevelStatsMultiplier_DinoTamed[2]=1.000000
PerLevelStatsMultiplier_DinoTamed[3]=1.000000
PerLevelStatsMultiplier_DinoTamed[4]=1.000000
PerLevelStatsMultiplier_DinoTamed[5]=1.000000
PerLevelStatsMultiplier_DinoTamed[6]=1.000000
PerLevelStatsMultiplier_DinoTamed[7]=1.000000
PerLevelStatsMultiplier_DinoTamed[8]=0.170000
PerLevelStatsMultiplier_DinoTamed[9]=1.000000
PerLevelStatsMultiplier_DinoTamed[10]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[0]=0.140000
PerLevelStatsMultiplier_DinoTamed_Add[1]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[2]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[3]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[4]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[5]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[6]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[7]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[8]=0.140000
PerLevelStatsMultiplier_DinoTamed_Add[9]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[10]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[0]=0.440000
PerLevelStatsMultiplier_DinoTamed_Affinity[1]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[2]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[3]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[4]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[5]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[6]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[7]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[8]=0.440000
PerLevelStatsMultiplier_DinoTamed_Affinity[9]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[10]=1.000000
PerLevelStatsMultiplier_DinoWild[0]=1.000000
PerLevelStatsMultiplier_DinoWild[1]=1.000000
PerLevelStatsMultiplier_DinoWild[2]=1.000000
PerLevelStatsMultiplier_DinoWild[3]=1.000000
PerLevelStatsMultiplier_DinoWild[4]=1.000000
PerLevelStatsMultiplier_DinoWild[5]=1.000000
PerLevelStatsMultiplier_DinoWild[6]=1.000000
PerLevelStatsMultiplier_DinoWild[7]=1.000000
PerLevelStatsMultiplier_DinoWild[8]=1.000000
PerLevelStatsMultiplier_DinoWild[9]=1.000000
PerLevelStatsMultiplier_DinoWild[10]=1.000000
PerLevelStatsMultiplier_Player[0]=1.000000
PerLevelStatsMultiplier_Player[1]=1.000000
PerLevelStatsMultiplier_Player[2]=1.000000
PerLevelStatsMultiplier_Player[3]=1.000000
PerLevelStatsMultiplier_Player[4]=1.000000
PerLevelStatsMultiplier_Player[5]=1.000000
PerLevelStatsMultiplier_Player[6]=1.000000
PerLevelStatsMultiplier_Player[7]=1.000000
PerLevelStatsMultiplier_Player[8]=1.000000
PerLevelStatsMultiplier_Player[9]=1.000000
PerLevelStatsMultiplier_Player[10]=1.000000
GlobalSpoilingTimeMultiplier=0.000000
GlobalItemDecompositionTimeMultiplier=0.000000
GlobalCorpseDecompositionTimeMultiplier=0.000000
PvPZoneStructureDamageMultiplier=6.000000
StructureDamageRepairCooldown=180.000000
IncreasePvPRespawnIntervalCheckPeriod=300.000000
IncreasePvPRespawnIntervalMultiplier=2.000000
IncreasePvPRespawnIntervalBaseAmount=59.999001
ResourceNoReplenishRadiusPlayers=1.000000
ResourceNoReplenishRadiusStructures=1.000000
CropGrowthSpeedMultiplier=1.000000
LayEggIntervalMultiplier=1.000000
PoopIntervalMultiplier=1.000000
CropDecaySpeedMultiplier=1.000000
MatingIntervalMultiplier=1.000000
EggHatchSpeedMultiplier=1.000000
BabyMatureSpeedMultiplier=1.000000
BabyFoodConsumptionSpeedMultiplier=1.000000
DinoTurretDamageMultiplier=1.000000
DinoHarvestingDamageMultiplier=3.200000
PlayerHarvestingDamageMultiplier=1.000000
CustomRecipeEffectivenessMultiplier=1.000000
CustomRecipeSkillMultiplier=1.000000
AutoPvEStartTimeSeconds=0.000000
AutoPvEStopTimeSeconds=0.000000
KillXPMultiplier=1.000000
HarvestXPMultiplier=1.000000
CraftXPMultiplier=1.000000
GenericXPMultiplier=1.000000
SpecialXPMultiplier=1.000000
bIncreasePvPRespawnInterval=True
bAutoPvETimer=False
bAutoPvEUseSystemTime=False
bDisableFriendlyFire=False
bFlyerPlatformAllowUnalignedDinoBasing=False
bDisableLootCrates=False
bAllowCustomRecipes=True
bPassiveDefensesDamageRiderlessDinos=False
bPvEAllowTribeWar=True
bPvEAllowTribeWarCancel=False
MaxDifficulty=False
bUseSingleplayerSettings=True
bUseCorpseLocator=True
bDisableStructurePlacementCollision=False
OverrideMaxExperiencePointsPlayer=0
OverrideMaxExperiencePointsDino=0
MaxNumberOfPlayersInTribe=0
SupplyCrateLootQualityMultiplier=1.000000
FishingLootQualityMultiplier=1.000000
CraftingSkillBonusMultiplier=1.000000
bAllowPlatformSaddleMultiFloors=False
bAllowUnlimitedRespecs=False
FuelConsumptionIntervalMultiplier=1.000000

[ShooterGameMode_TEMPOverrides]
SupplyCrateLootQualityMultiplier=1.000000
FishingLootQualityMultiplier=1.000000
CraftingSkillBonusMultiplier=1.000000
bAllowPlatformSaddleMultiFloors=False
bAllowUnlimitedRespecs=False
FuelConsumptionIntervalMultiplier=1.000000

`

And that's my GameUserSettings.ini:

`[/Script/ShooterGame.ShooterGameUserSettings]
MasterAudioVolume=0.257937
MusicAudioVolume=0.000000
SFXAudioVolume=0.285714
VoiceAudioVolume=1.793651
CameraShakeScale=1.000000
bFirstPersonRiding=False
bThirdPersonPlayer=False
bShowStatusNotificationMessages=True
TrueSkyQuality=0.000000
FOVMultiplier=1.000000
GroundClutterDensity=0.000000
bFilmGrain=False
bMotionBlur=False
bUseDFAO=False
bUseSSAO=False
bShowChatBox=True
bCameraViewBob=True
bInvertLookY=False
bFloatingNames=True
bChatBubbles=True
bHideServerInfo=False
bJoinNotifications=False
bCraftablesShowAllItems=True
bLocalInventoryShowAllItems=True
bRemoteInventoryShowAllItems=True
LookLeftRightSensitivity=1.000000
LookUpDownSensitivity=1.000000
GraphicsQuality=4
ActiveLingeringWorldTiles=1
ClientNetQuality=3
LastServerSearchType=2
LastServerSearchHideFull=True
LastServerSearchProtected=False
HideItemTextOverlay=True
bDistanceFieldShadowing=False
LODScalar=0.000000
bToggleToTalk=False
HighQualityMaterials=False
HighQualitySurfaces=True
bTemperatureF=False
bDisableTorporEffect=False
bChatShowSteamName=False
bChatShowTribeName=True
EmoteKeyBind1=0
EmoteKeyBind2=0
bNoBloodEffects=False
bLowQualityVFX=False
bSpectatorManualFloatingNames=False
bSuppressAdminIcon=False
bUseSimpleDistanceMovement=False
bDisableMeleeCameraSwingAnims=False
bUseVSync=False
MacroCtrl0=
MacroCtrl1=
MacroCtrl2=
MacroCtrl3=
MacroCtrl4=
MacroCtrl5=
MacroCtrl6=
MacroCtrl7=
MacroCtrl8=
MacroCtrl9=
ResolutionSizeX=1920
ResolutionSizeY=1080
LastUserConfirmedResolutionSizeX=1600
LastUserConfirmedResolutionSizeY=900
WindowPosX=-1
WindowPosY=-1
bUseDesktopResolutionForFullscreen=False
FullscreenMode=1
LastConfirmedFullscreenMode=2
Version=5
bHighQualityAnisotropicFiltering=False
bPreventInventoryOpeningSounds=False
bPreventItemCraftingSounds=False
bPreventHitMarkers=False
bPreventCrosshair=False
bPreventColorizedItemNames=False
LastDLCTypeSearchType=1
bHighQualityLODs=False
bExtraLevelStreamingDistance=False
bEnableColorGrading=False
DOFSettingInterpTime=0.000000
bDisableBloom=True
bDisableLightShafts=True
LastPVESearchType=2
bUseLowQualityLevelStreaming=False
bDisableMenuTransitions=False
VersionMetaTag=1
UIScaling=1.000000
UIQuickbarScaling=1.000000
bLocalInventoryItemsShowAllItems=False
bLocalInventoryCraftingShowAllItems=True
bRemoteInventoryItemsShowAllItems=True
bRemoteInventoryCraftingShowAllItems=False
bRemoteInventoryShowEngrams=True
bEnableInventoryItemTooltips=True
bRemoteInventoryShowCraftables=False
bNoTooltipDelay=False
LocalItemSortType=0
LocalCraftingSortType=0
RemoteItemSortType=3
RemoteCraftingSortType=0
ShowExplorerNoteSubtitles=True
DisableMenuMusic=False
DisableDefaultCharacterItems=False
bHideFloatingPlayerNames=False
bQuickToggleItemNames=True
bHideGamepadItemSelectionModifier=False
MaxAscensionLevel=0
PlayActionWheelClickSound=True

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=0
sg.AntiAliasingQuality=0
sg.ShadowQuality=0
sg.PostProcessQuality=0
sg.TextureQuality=0
sg.EffectsQuality=3
sg.TrueSkyQuality=3
sg.GroundClutterQuality=3
sg.IBLQuality=1
sg.HeightFieldShadowQuality=0
sg.GroundClutterRadius=0

[SessionSettings]
SessionName=ARK #808716

[/Script/Engine.GameSession]
MaxPlayers=70

[ServerSettings]
DifficultyOffset=1.000000
ListenServerTetherDistanceMultiplier=1.000000
GlobalVoiceChat=False
ProximityChat=False
NoTributeDownloads=False
AllowThirdPersonPlayer=True
AlwaysNotifyPlayerLeft=False
DontAlwaysNotifyPlayerJoined=False
ServerHardcore=False
ServerPVE=False
ServerCrosshair=True
ServerForceNoHUD=False
ShowMapPlayerLocation=False
EnablePvPGamma=True
DisableStructureDecayPvE=False
AllowFlyerCarryPvE=False
ActiveMods=
ActiveMapMod=0
RCONPort=27020
StructurePreventResourceRadiusMultiplier=1.000000
PvEDinoDecayPeriodMultiplier=1.000000
KickIdlePlayersPeriod=3600.000000
PerPlatformMaxStructuresMultiplier=1.000000
AutoSavePeriodMinutes=15.000000
MaxTamedDinos=5000.000000
RCONServerGameLogBuffer=600.000000
ServerPassword=
ServerAdminPassword=
RaidDinoCharacterFoodDrainMultiplier=1.000000
AllowHitMarkers=True
TheMaxStructuresInRange=10500.000000
OnlyAllowSpecifiedEngrams=False
PreventDownloadSurvivors=False
PreventDownloadItems=False
PreventDownloadDinos=False
DisablePvEGamma=False
DisableDinoDecayPvE=False
AdminLogging=False
AllowCaveBuildingPvE=False
ForceAllowCaveFlyers=False
PreventOfflinePvP=False
PvPDinoDecay=False
OverrideStructurePlatformPrevention=False
AllowAnyoneBabyImprintCuddle=False
DisableImprintDinoBuff=False
ShowFloatingDamageText=False
PreventDiseases=False
NonPermanentDiseases=False
EnableExtraStructurePreventionVolumes=False
PreventTribeAlliances=False
AllowRaidDinoFeeding=False
OxygenSwimSpeedStatMultiplier=1.000000
PreventOfflinePvPInterval=1

[/Game/Mods/LaserTurret/TestGameMode_LaserTurret.TestGameMode_LaserTurret_C]
OverrideEngramEntries=(EngramClassName=,EngramIndex=0,EngramHidden=False,EngramPointsCost=0,EngramLevelRequirement=0,RemoveEngramPreReq=False)
OverrideNamedEngramEntries=(EngramClassName=,EngramIndex=0,EngramHidden=True,EngramPointsCost=0,EngramLevelRequirement=0,RemoveEngramPreReq=False)

[Small_Dragons]
WalkSpeed=500.000000
FlyingSpeed=1000.000000
FlyingRunSpeedModifier=1.000000
RunSpeedModifier=1.000000
FireDamage=18.000000
GrabWeight=400.000000
BabyAgeSpeed=0.000030

[Player.Info]
LastMapPlayed=TheIsland
PlayedMaps=TheIsland
LastHostedMapPlayed=TheIsland

[/Game/PrimalEarth/CoreBlueprints/TestGameMode.TestGameMode_C]
PerLevelStatsMultiplier_Player[0]=1.000000
PerLevelStatsMultiplier_Player[1]=1.000000
PerLevelStatsMultiplier_Player[2]=1.000000
PerLevelStatsMultiplier_Player[3]=1.000000
PerLevelStatsMultiplier_Player[4]=1.000000
PerLevelStatsMultiplier_Player[5]=1.000000
PerLevelStatsMultiplier_Player[6]=1.000000
PerLevelStatsMultiplier_Player[7]=1.000000
PerLevelStatsMultiplier_Player[8]=1.000000
PerLevelStatsMultiplier_Player[9]=1.000000
PerLevelStatsMultiplier_DinoTamed[1]=1.000000
PerLevelStatsMultiplier_DinoTamed[2]=1.000000
PerLevelStatsMultiplier_DinoTamed[3]=1.000000
PerLevelStatsMultiplier_DinoTamed[4]=1.000000
PerLevelStatsMultiplier_DinoTamed[5]=1.000000
PerLevelStatsMultiplier_DinoTamed[6]=1.000000
PerLevelStatsMultiplier_DinoTamed[9]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[1]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[2]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[3]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[4]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[5]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[6]=1.000000
PerLevelStatsMultiplier_DinoTamed_Add[9]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[1]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[2]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[3]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[4]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[5]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[6]=1.000000
PerLevelStatsMultiplier_DinoTamed_Affinity[9]=1.000000
PerLevelStatsMultiplier_DinoWild[0]=1.000000
PerLevelStatsMultiplier_DinoWild[1]=1.000000
PerLevelStatsMultiplier_DinoWild[2]=1.000000
PerLevelStatsMultiplier_DinoWild[3]=1.000000
PerLevelStatsMultiplier_DinoWild[4]=1.000000
PerLevelStatsMultiplier_DinoWild[5]=1.000000
PerLevelStatsMultiplier_DinoWild[6]=1.000000
PerLevelStatsMultiplier_DinoWild[7]=1.000000
PerLevelStatsMultiplier_DinoWild[8]=1.000000
PerLevelStatsMultiplier_DinoWild[9]=1.000000

[/Game/Mods/century/TestGameMode_century.TestGameMode_century_C]
DinoSpawnWeightMultipliers=(DinoNameTag="Megapithecus",SpawnWeightMultiplier=0.600000,OverrideSpawnLimitPercentage=False,SpawnLimitPercentage=0.001000)
DinoSpawnWeightMultipliers=(DinoNameTag="Spino",SpawnWeightMultiplier=0.800000,OverrideSpawnLimitPercentage=False,SpawnLimitPercentage=0.015000)
DinoSpawnWeightMultipliers=(DinoNameTag="Titanboa",SpawnWeightMultiplier=0.750000,OverrideSpawnLimitPercentage=False,SpawnLimitPercentage=0.019000)
DinoSpawnWeightMultipliers=(DinoNameTag="Dimetro",SpawnWeightMultiplier=0.750000,OverrideSpawnLimitPercentage=False,SpawnLimitPercentage=0.019000)
DinoSpawnWeightMultipliers=(DinoNameTag="Sarco",SpawnWeightMultiplier=0.870000,OverrideSpawnLimitPercentage=False,SpawnLimitPercentage=0.030000)
DinoSpawnWeightMultipliers=(DinoNameTag="Kaprosuchus",SpawnWeightMultiplier=0.820000,OverrideSpawnLimitPercentage=False,SpawnLimitPercentage=0.032000)
DinoSpawnWeightMultipliers=(DinoNameTag="Mega",SpawnWeightMultiplier=0.800000,OverrideSpawnLimitPercentage=False,SpawnLimitPercentage=0.040000)
DinoSpawnWeightMultipliers=(DinoNameTag="Rex",SpawnWeightMultiplier=0.900000,OverrideSpawnLimitPercentage=False,SpawnLimitPercentage=0.700000)
BabyImprintingStatScaleMultiplier=1.000000
FuelConsumptionIntervalMultiplier=1.000000

`

**Comment by cadon** [comment]
Hi, the reason are some changed single-player-stat-multipliers. It'll be corrected in the next release, until then you manually adjust them in the settings, set HP tameAdd to 0.5, HP tameLevel to 0.425, Dmg tameAdd to 0.5 and Dmg tameLevel to 0.4.
