### ISSUE TITLE
Not accepting hp or dmg on Direbear

### ISSUE THREAD

**Issue by Disgustipated86** [cadon/ARKStatsExtractor#40]
Tamed at 120, stood up at 179 on our server. Only leveled HP, DMG and Weight so everything else should be default. I've asked the admins if there are stat modifiers on for dinos and they say no, but the level cap is much higher than a normal server and breeding rates are x2 atm. 

![baloo](https://cloud.githubusercontent.com/assets/18738789/14995126/0f6556aa-1128-11e6-908d-d05224497a2a.png)

**Comment by cadon** [comment]
Hi, the HP is only possible with a non-official multiplier for tamed levels (aka something similar before the dino-nerf). I couldn't extract the values when I set all multipliers to 1 neither. I guess the server has different multipliers than the officials or everything on 1.
