### ISSUE TITLE
stats not extracting correctly

### ISSUE THREAD

**Issue by KaptainZ** [cadon/ARKStatsExtractor#402]
i have recently started playing ark again and came back to this tool (which i have used before) and no matter what i try it doesn't seem to be extracting stats correctly it seems to have the most trouble with health.
here is one of many screenshots let he know if there is anything i can do to help thanks
https://puu.sh/wQGms/2a0f44b645.jpg

**Comment by cadon** [comment]
Hi, ARK recently introduced a new setting calles "Singleplayer-Settings", which, if enabled, changes some aspects of the game along with some stat-multipliers. To adjust Smart Breeder to that, click on "Set to official SP" in the stat-multiplier-settings. It should work then.

**Comment by KaptainZ** [comment]
ok ill try that

**Comment by KaptainZ** [comment]
thanks its all working now
