### ISSUE TITLE
Stats from Rex not extracting correctly

### ISSUE THREAD

**Issue by TreskyPlesky** [cadon/ARKStatsExtractor#403]
![rex](https://user-images.githubusercontent.com/30387005/28499244-69309710-6fb1-11e7-9561-46eb403ac375.jpg)

Hi I cannot extract stats from my rexes, server is unofficial, stats are modified.

I have server Game.ini and Drag nad Droped it on the settings tab, but it still dont work.

**Comment by cadon** [comment]
Hi, the HP seems very high for these stat-levels. Did you only level Dmg once and no other stats? Are other species working? Did you change the multipliers recently? You can try to levelup HP once, maybe the number is not correctly shown.

**Comment by TreskyPlesky** [comment]
Hi I spent only one lvl in HP to see if its not a bug. Its fresh server and i tried only rexes because others are flyers and there is a classic flyers mod too so i wanted to be sure its not the mod.

I can upload game.ini if it helps

base hp were 20020,3

**Comment by cadon** [comment]
Yes, the game.ini would be helpful. You can ommit the part with the xp per level etc.

**Comment by TreskyPlesky** [comment]
Hi I just went through ini again and find singleplayersettings true i think it was the problem now im testing. Post results lately or tomorow. Thank you for help anyway

**Comment by BillyHalley** [comment]
So you just disabled singleplayersettings and it works?

What does that change in game?

**Comment by TreskyPlesky** [comment]
yep disabled them and hp went a bit down and now extraction works
