### ISSUE TITLE
Add new baby dino to library before imprint

### ISSUE THREAD

**Issue by Bonez70** [cadon/ARKStatsExtractor#404]
Not really an issue but what is the best way to add a baby dino to library as soon as it is born?  Tried using stat test but it will not accept values over 9999.  thanks

**Comment by cadon** [comment]
Hi, the best is to enter a creature directly after it's tamed or born (i.e. without domesticated levels or imprinting). It's possible to enter them later, but it can happen that the level-distribution is not unique for the stat-values, so there might be some guessing.

The tester is to see which values the creature can get, the inputs are levels. You probably want to use the extractor where you can enter the stat-values.

**Comment by Bonez70** [comment]
Thank you, however; I must be missing something I don't see how to add a creature directly.

**Comment by cadon** [comment]
What do you mean with "directly"? If you know the levels of all the stats, you can enter them in the Tester and add it there. If you only have the stat-values from the game, you have to extract the levels first before you can add the creature to the libraray.

**Comment by Bonez70** [comment]
Thank you I got it now, great app btw
