### ISSUE TITLE
Extraction Issues Ankylosaurus

### ISSUE THREAD

**Issue by NoName941238** [cadon/ARKStatsExtractor#405]
Screen Resolution: 1920x1080
Window mode: WindowedFullscreen

Anky 2
![anky2_inv](https://user-images.githubusercontent.com/30393245/28502442-e8894480-6ff2-11e7-9299-7bc530abafb8.PNG)
![anky2_calculator](https://user-images.githubusercontent.com/30393245/28502441-e889647e-6ff2-11e7-86ee-7afa08c5abcd.PNG)

Anky 1
![anky1_calculator](https://user-images.githubusercontent.com/30393245/28502444-e88b05cc-6ff2-11e7-9461-1f5653e9afee.PNG)
![anky1_inv](https://user-images.githubusercontent.com/30393245/28502443-e88a16e4-6ff2-11e7-92bb-7bbde7d41670.PNG)

Server Settings:
[SessionSettings]
....
OxygenSwimSpeedStatMultiplier=1.0
DinoDamageMultiplier=1.5
TamedDinoDamageMultiplier=1.0
DinoResistanceMultiplier=1.0
TamedDinoResistanceMultiplier=1.0
MaxTamedDinos=5000
DinoCharacterFoodDrainMultiplier=1.0
DinoCharacterStaminaDrainMultiplier=1.0
DinoCharacterHealthRecoveryMultiplier=1.0
DinoCountMultiplier=1.0
AllowRaidDinoFeeding=True
RaidDinoCharacterFoodDrainMultiplier=1.0
DisableDinoDecayPvE=False
PvPDinoDecay=True
AutoDestroyDecayedDinos=True
PvEDinoDecayPeriodMultiplier=3.0
MaxPersonalTamedDinos=150.0
DisableImprintDinoBuff=False
AllowAnyoneBabyImprintCuddle=True
TamingSpeedMultiplier=3.0
.....

**Comment by cadon** [comment]
Hi, probably you've some stat-multipliers changed. Can you post them? Also the anky seems to have 98% imprinting, in your screenshots you entered 100%. Did you change the matureSpeedMultiplier or the CuddleIntervalMultiplier?

**Comment by NoName941238** [comment]
Thanks for you fast reply.
this is what the server owner published (http://ndm-ark.de/index.php?thread/233-komplette-servereinstellungen/&postID=1503 )  i don't see any stats modifiers there.

But it is possible that the mature has changed during an event weekend. to be honest, i have no clue 

the 100% comes from the ocr.  but it changes nothing when correcting it to 98%.

**Comment by cadon** [comment]
Ah, damit geht's. Setze BabyMatureSpeed auf 20 und BabyCuddleInterval auf 0.1, bzw. noch besser speichere die ganzen Einstellungen in eine Textdatei und ziehe diese dann in die Einstellungen, so dass es (mit den anderen Änderungen) automatisch eingetragen wird.

Lumpie (Ankylosaurus, Lvl 214, Impr: 98.5%): HP: 7373.5 (39, 0); St: 651 (21, 2); Ox: 705 (37, 0); Fo: 14040.7 (24, 0); We: 549.7 (32, 3); Dm: 388.6% (27, 7); Sp: 154.7% (21, 0); To: 6566.2 (201);

Noa (Ankylosaurus, Lvl 216, Impr: 98.5%): HP: 7771.7 (39, 1); St: 651 (21, 2); Ox: 705 (37, 0); Fo: 14040.7 (24, 0); We: 628.2 (32, 7); Dm: 370.9% (27, 4); Sp: 154.7% (21, 0); To: 6566.2 (201);
