### ISSUE TITLE
Red stats

### ISSUE THREAD

**Issue by weemaus** [cadon/ARKStatsExtractor#407]
We've got a couple of breeding programs, for which this would be invaluable, but I can't get the program to parse some of our top animals' stats.

![unicorn](https://user-images.githubusercontent.com/30399495/28539596-e77eb0a4-7077-11e7-8d7c-2db3e04c696d.PNG)
![boris](https://user-images.githubusercontent.com/30399495/28539597-e78643c8-7077-11e7-801d-7177de37deea.PNG)
![jackson](https://user-images.githubusercontent.com/30399495/28539598-e7880db6-7077-11e7-921d-722d3226a218.PNG)

This is on an official MP server, fresh install of the program, I refreshed the stat multipliers... I'm at a loss.

**Comment by cadon** [comment]
Hi, probably these creatures were raised during an event, with different matureSpeedMultipliers. Try to set it to 1.5 or 2 (or the number it was).

**Comment by maszaan** [comment]
Here are my game.ini settings if this helps 
PerLevelStatsMultiplier_DinoTamed[0]=5
PerLevelStatsMultiplier_DinoTamed[1]=3
PerLevelStatsMultiplier_DinoTamed[2]=1.0
PerLevelStatsMultiplier_DinoTamed[3]=1.0
PerLevelStatsMultiplier_DinoTamed[4]=5.0
PerLevelStatsMultiplier_DinoTamed[5]=1.0
PerLevelStatsMultiplier_DinoTamed[6]=1.0
PerLevelStatsMultiplier_DinoTamed[7]=7.5
PerLevelStatsMultiplier_DinoTamed[8]=1.0
PerLevelStatsMultiplier_DinoTamed[9]=1.0
PerLevelStatsMultiplier_DinoTamed[10]=1.0
PerLevelStatsMultiplier_DinoTamed[11]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[0]=10.0
PerLevelStatsMultiplier_DinoTamed_Add[1]=10.0
PerLevelStatsMultiplier_DinoTamed_Add[2]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[3]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[4]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[5]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[6]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[7]=10.0
PerLevelStatsMultiplier_DinoTamed_Add[8]=10.0
PerLevelStatsMultiplier_DinoTamed_Add[9]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[10]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[11]=1.0

**Comment by weemaus** [comment]
do you have any idea whether the official events affect more than BabyMatureSpeedMultiplier? I've tried 1.5 and 2 on that and a few other things, but I haven't hit on the right combination yet.

**Comment by cadon** [comment]
Hi @weemaus, good to hear you solved it. Also, for the ones with 100% imprinting it can be neccessary to enable the checkbox "Exactly, don't adjust".
