### ISSUE TITLE
Dino Image

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#408]
Would it be possible to design a dossier tab where it has all the data for the dino and you can take/paste a screenshot of the dino for easy posting on the survivetheark forums?  Obviously done when ever you have some free time if you feel like doing it.

**Comment by cadon** [comment]
Hi, can you elaborate that idea a bit? Do you mean all the levels and the stats of a dino, but as an image? If you want the stats and levels as text, you can just right-click a creature in the library or go to the menu Edit and choose "copy to clipboard" and select the data you want.

**Comment by VolatilePulse** [comment]
This should still be a low priority, but I like the idea and was something another collaborator and I talked about for quite a while. We never discussed it in ASB specifically, but it might be worth considering in the future.

Things to consider would be to have a section that covers server settings like the stat multipliers, single player, and imprinting multipliers but have the creature itself (the creature images and coloring would go nicely with this) with the current stat values and level distributions. It's just something you can take a screenshot of and share with your friends for trading creatures across servers, bragging rights, etc.
