### ISSUE TITLE
Keep getting red stats, vanilla multipliers. How do you bypass this and add em anyway?

### ISSUE THREAD

**Issue by Taiine** [cadon/ARKStatsExtractor#409]
So every so often I end up getting a stat that comes up in red, mostly HP. All the stats are right, there are no dino multipliers on the server, aside a few decour mods and a 2.5 taming its pretty much vanilla. 

I've seen others post about read stats so I wont repeat it, but what I want to know is how do I MANUALLY add the stats and add it to my library? The red stats are preventing me from adding them and is really killing our breeding. It's getting annoying being forced to keep them unleveled to some day hopefully to be able to add em or just say screw it and lv them anyway and never have them added giving us a big unknown factor in our breeding lines.

I keep hearing there is some manual way to add the stats and add them to the library bypassing this annoyance, but I've yet to sort out how. Only thing I see is the stat testing but that don't accept the dinos stats, but instead there points. 

I really can't figure this out, and am hoping you can add a bypass to the extractor so that you can add them even if the stats are red so we don't have to be forced to not add them due to program error or what not. 

I have two horses that show red health and it looks like they got a stat mutaion in said stat. Please tell me how to add them or add away to bypass the red stat error when the stats and settings are 100% correct.

**Comment by cadon** [comment]
Hi, the whole point of this tool is to have the levels, you cannot do much with a creature who's levels you don't have. If you just want a list of your creatures with the stat-values, a spreadsheet is much simpler. You can only add a creature to the library if you have its levels, it's not something I could change, a creature without levels would just not work, it couldn't be used with anything else, so you can't add it.

If you have issues with the extraction, and already looked through all points at https://github.com/cadon/ARKStatsExtractor/wiki/Extraction-issues, post a screenshot of the inventory and the multipliers you use on your server.

**Comment by Taiine** [comment]
I already said we have NO dino multipliers, outside changing taming to 2.5. 
MatingIntervalMultiplier=1.0
EggHatchSpeedMultiplier=8.0
BabyMatureSpeedMultiplier=4.0
LayEggIntervalMultiplier=1.0
DayCycleSpeedScale=0.3
DayTimeSpeedScale=0.6
NightTimeSpeedScale=2.3
StructureResistanceMultiplier=0.5
TamingSpeedMultiplier=2.5
HarvestHealthMultiplier=2.0
Harvest=1.0

Everything else is untouched and is normal default ark. All the info is correct, the stats are double checked and even typed in manually. But we still get some dinos where the stats come up red, it don't happen often but it does happen and we have no way to add them to the breeding lists. 

Why we are asking for some way to bypass it and add them anyway so we either don't have to hold off lving them until another update comes out or just say eff it and just be in the dark about them or try and compare them to others to guess where the points went. 

Why can't you just add away to 'add anyway'? It's just really annoying when we are breeding for stat mutations and want the best breeding pairs we can get but then we get red stats and have zero ways of still adding them when everything is correct. Like we have a set of horses that have stacked health and damage mutations that we use often for our raids and taming as they knock stuff out rather fast. (already knocked out a mid lv GIGA with five of them while only losing two) But right now most the babys are coming out with red health numbers. 

So we just don't lv our tames until the next patch to fix the issue? Don't bother imprinting our babys? How would it not 'work'?

**Comment by lnewlfe** [comment]
There is an add anyway button... Not at comp, but its called something like copy to tester. I have had like 65% of my scans crap out, just copy, fill the missing stats out, then add to library.

**Comment by Taiine** [comment]
But the issue with that is the 'tester' wants the dinos points for the lv, if the stat is red it imputs it as a 0, you can't just add in the dinos stats. Theres no way to manually add it in because you don't know the points it has in that stat, you only kn ow what stat value it shows in its inv.

**Comment by cadon** [comment]
> Why we are asking for some way to bypass it and add them anyway so we either don't have to hold off lving them until another update comes out

Why would you wait with leveling it up? The tool also extracts leveled creatures. The combinations may not be unique anymore, but if you note somewhere how many levels you spent in the different stats, it's 100% sure to get the correct levels, once the extraction issue is resolved.

> Why can't you just add away to 'add anyway'?

I already explained it in the previous answer. It's not something that could be done. It's the same reason why you cannot add the creatures via the tester-tab, you don't know their levels.

> So we just don't lv our tames until the next patch to fix the issue? Don't bother imprinting our babys?

No need for that. Level them up, imprint them. Once you found the correct multipliers, you can extract them later.

As writte before, post a screenshot of an inventory, your multipliers, maybe we can see what's wrong.

**Comment by caesar-17** [comment]
Maybe because it's 2am...I am failing to understand.

It is my understanding that the program "looks" at the creature's inventory...and an OCR component "reads" the numbers on the screen concerning said creature.  

Those numbers (in the creature's inventory,) seem to be all the program needs to do it's work.

So, if OCR is failing to work.  Why cannot we just type in manually the same numbers it would read, but just somehow can't read by itself?

"Mr. Dodo" name came out "Mr. Dido," but I backspaced and typed it in correctly.  Why can't I type in the numbers correctly if the program gets it wrong?

Is it doing something other than just "reading the numbers" that I am unaware of?  Thank you for your patience with me, a non-programmer.

**Comment by cadon** [comment]
Hi @caesar-17, it's exactly like you said. What's your problem, or was it just a question how things work?
