### ISSUE TITLE
Stego stats not calculating right.

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#41]
I guess the image explains it.

In addition I have noticed Trikes have the same issue as well.

![capture](https://cloud.githubusercontent.com/assets/1366816/15048422/cf9f0e4c-132c-11e6-9a9b-ac38442dde03.PNG)

**Comment by cadon** [comment]
Hi, that's strange. The values of that Stego would fit good for a level 40 one. It seems 9 levelups did not increase any of the stat-numbers, so the tool assumes these points are wild-speed-levelups. But the Torpor only allows 1 wild level.
The levels are shown incorrectly if you just leveled up a creature and don't leave and reenter the inventory. But then the total levels are shown too low, not too high as it is the case here.
The base-stats of the Stego didn't seem to have changed as well.
Can you restart the game or wait for the server to be restarted and then try it again? Currently I've no other idea.

**Comment by cyberangel67** [comment]
I have found that there is a few Dinos doing this, Stego and Trikes are one and sometimes if you level them up once and then enter the stats it will work fine. Just not when first tamed, or you have had them awhile. I am think there is a calculation issue here.

I also noticed another issue, when on the Centre on the Xbox where we have Dinos now with 150 max level and I spawned a Giga in it ended up telling me that it is not tamed as yet. Even though all the stats where entered correctly. The setting had the Max level at 150 and Dom raise level 61. However I did notice that if I took it of Auto and did the calculation it worked fine.

**Comment by cadon** [comment]
Hi,
the auto-detection of wild/tamed does not work for the Giganotosaur, its stats are different, you have to set it to wild or tamed manually.
Are you still experience that issue with Stegos and Trikes? Can you post another screenshot if that happens? Thanks.

**Comment by cyberangel67** [comment]
Yes, and just had it happen to 2 Rex's. Where both I was told where tamed at a perfect 120, but the game thinks it was tamed at 115 and 118. I have seen this with a number of Dino's now and the moment I level them one more time and try again it calcs right. It seems, could be wrong that it doesn't like the entering level to be an odd number.
![capture](https://cloud.githubusercontent.com/assets/1366816/15910650/331a54b6-2e0f-11e6-8223-7d11dcb6298c.PNG)

**Comment by cyberangel67** [comment]
Here is another one that seems to be wrong, way wrong. It says the LW was 75, how is that possible for 218 bronto?

![capture](https://cloud.githubusercontent.com/assets/1366816/15980335/25f85fbc-2fae-11e6-80b6-10e9ed32d4a1.PNG)

**Comment by cyberangel67** [comment]
Here is another one that I just tamed, it was wild 116 and came out at 166 with a TE 87.14 as per the Dododex. However as you can see the program thinks it 12 115, but the side says it was 113.
![capture](https://cloud.githubusercontent.com/assets/1366816/15989557/d156af6c-30bc-11e6-886c-ed8d79d2cc60.PNG)

**Comment by cadon** [comment]
The torpor-bug was resolved ingame, I guess this issue was partly related to this. There were also some fixes regarding the wild-level calculation in the meantime, so I'm closing this for now.
