### ISSUE TITLE
HELP Not reading values LOST

### ISSUE THREAD

**Issue by Infam0uz** [cadon/ARKStatsExtractor#410]
so From all the research just want to verify if you dont have a 1920x1080 nothing will read? i have been trying everything but nothing seems to work that is my final conclusion just was someone to berify if its correct or is there a way i can get it to work my monitor is 1600x900

**Comment by cadon** [comment]
Hi, you need a file that matches your resolution in windows, i.e. 1600 x 900. I currently don't have such a file. If you make one, you can upload / send it, so I'll include it in the releases. See here for more infos: https://github.com/cadon/ARKStatsExtractor/wiki/OCR
