### ISSUE TITLE
Breeding to Min/Max Stats?

### ISSUE THREAD

**Issue by Sera-phina** [cadon/ARKStatsExtractor#411]
We are breeding for boss fights. The weighting tool is very helpful, but is there an option to get breeding recomendations that will give max stats in selected stats and minimum stats in others?

 For example, we are trying to get Rexes with Maximum health and damage and all the other stats at base value. @cadon #

**Comment by cadon** [comment]
Hi, just set the weighting for HP and Damage very high (like 10) and leave the others at 1. Regarding the boss-fights it doesn't matter what level e.g. food is, so just ignore it. If food by chance is high, it should be not a reason to not take the rex if the HP and damage are high.

If you really want a rex with only high HP and Damage and very low levels in the other stats, you have to choose the dinos manually. Currently there's no way to set a stat-weighing to a negative value. Do you think this is necessary to have?

**Comment by Taiine** [comment]
When it comes to breeding having all 6 stats high is more idea than focusing on just one or two. With all 6 stats being high, the dinos come out at even higher lvs and that boosts all the stats over all.

**Comment by Sera-phina** [comment]
We would like them to come out at max level with all their levels in either health or damage, I can do it manually, was just wandering if it was an option.

**Comment by cadon** [comment]
As said, there is no harm in having a high level in unwanted stats. Unless you are playing on an official server and are talking about the new introduced level cap at 450. Then again, it's pretty certain that this level cap won't affect you, you'd need an average stat-level of at least 60.

**Comment by cadon** [comment]
I added negative weightings in the latest release, so now you can set food (or other unwanted stats) to a negative weighting to get suggestions with less points in these stats.
