### ISSUE TITLE
Column in library to insert dino color

### ISSUE THREAD

**Issue by defyreality** [cadon/ARKStatsExtractor#412]
i know there is the color wheel, which is awesome when flicking through each dino one by one. but when I'm looking at the big library list, it would be amazing to have a column right beside the name to enter whatever we call that dinos color. there is the note field, which i use to enter the dinos unique identifier number, but it also doesn't show in the library list view.

and long run, being able to re-order the columns, collapse them all together, and sort by them, oh baby that would be killer.  

P.S. program is unbelievable. keep up the tremendous work.

**Comment by cadon** [comment]
Hi, I'll add another column for the notes / color.
Changing the column-size and sorting is possible by dragging the column-header-separators or clicking on them. No promises regarding the reordering, yet.

**Comment by cadon** [comment]
Added a column for the notes. No column for the colors yet, not sure if that's easy doable in the current framework.

**Comment by defyreality** [comment]
looks good. the color column will help a lot with breeding for specific colors. sort by whatever the user has named their color combos, and pick the best parents from that. especially with the stupid 450lvl cap. 

your app makes it a lot easier to visualize all the data, and try and pick the best options to maximize the relevant stats, while keeping the "trash" stats lower.   

maybe in the breeding plan tab, a mode to prioritize the key stats while aiming for lvl 378. that's some crazy logic to code though.

**Comment by cadon** [comment]
A way to prioritize some stats can be achieved by setting the weighting of the desired stats to a high number, and the weight of unwanted stats to 0. Better would be a negative weight for these, I'll see if I can implement this.

**Comment by defyreality** [comment]
any way to split the Owner (- owner(tribe) - ) column in the library into it's respective Owner & tribe?

tribe is kinda a null thing for me, and i imagine most people using the program (i think Owner covers most of the things i can think of). so i could use the field for tribe as an entry point for color. although, i could use the owner field for my custom color (as it's sortable in the library), and use tribe for my "Wild/bought/imprinter.  Hmm, i'll play with it in a serperate file, see if it does what i need for sorting colors to help with keep/sell and breeding pairs based on color outcome.

**Comment by VolatilePulse** [comment]
Since this request, color ID columns have been added, the note column has been added, column reordering has recently been enabled, but separate tribe and owner columns have not yet been addressed.
