### ISSUE TITLE
Dino's not showing up in library

### ISSUE THREAD

**Issue by meggymegz88** [cadon/ARKStatsExtractor#413]
Hi there, 

I am new to this program and seem to have a basic understanding. I started extracting some dino's and then adding them one by one to my library. The problem I am having is that some of the dino's aren't showing up listed in my library. Is there a setting that is making me unable to see them? I know they are saved because they show up in the breeding plan tab just not showing up in my library. Any help is greatly appreciated.

Edit: So messing around a little further it looks like when I add that the dino has a mutation is when it doesn't appear in my library. I am still not able to figure out how to get it to show without having to remove the mutation.

**Comment by cadon** [comment]
Hi, you can filter the library with some options on the bottom left: for species, hiding dead or unavailable and for the owner. It's probably one of those.

**Comment by meggymegz88** [comment]
Hi cadon,

I have tried shuffling through species, owner and under view i have tried checking and unchecking dead, unavailable (even neutered in case I marked it by accident). It still won't seem to work.  My bf has an older version and under view, mutations used be an option to check. Is it possible this isn't a feature anymore?

**Comment by Vinciri** [comment]
I also have this problem!

**Comment by Raqtor** [comment]
Yea this must be a bug. Tried on 5 very different computers.

**Comment by cadon** [comment]
Can someone of you post a library file that has a not showing dino, along with the species and name of the dino, that's not showing?

**Comment by meggymegz88** [comment]
I feel so silly.  I seemed to have figured out what my issue was and maybe it is the same for the rest. I have been running the program in windowed mode. When I went to the view tab in the bottom left hand corner it was only showing me limited options like in this photo.

![image](https://user-images.githubusercontent.com/30509916/28799920-57914c76-75ff-11e7-92ae-512a6c8c9898.png)

I changed it to fullscreen and now I get the mutated creature checkbox that I was looking for that allows me to see my mutated dino's in my library. Haha.

Well that was a simple fix. xD 

Thank you for the help!

**Comment by Vinciri** [comment]
@cadon ![dodos](https://user-images.githubusercontent.com/11388419/28800804-47ec9f10-7603-11e7-93ac-7220210c5158.jpg)
For me My dodos are not showing maybe i had pressed something? only my pigs are showing. However when i go to my Breeding planner my dodos show up.
 ![dodos2](https://user-images.githubusercontent.com/11388419/28800838-7b85ba00-7603-11e7-8a4b-5ade9555b57a.jpg)

**Comment by Raqtor** [comment]
Dino does kinda get added. In bottom bar Alive and available number increases 1 and you can see it in pedigree but nowhere else and you cant delete it.
Tried and win 7 8 10 .. mac tablet laptop desktop.
Can anyone try if they can add this guy on a fresh install? A Rex I bought to use his good weight stat. He has **7 mutations**. _No known parents_.

![ark_ survival evolved_20170705155905](https://user-images.githubusercontent.com/11212053/28804198-f8f8dd4c-7661-11e7-9014-08ec17b3a48e.jpg)

If we can easy trigger the error its easier to pinpoint why it occurs.

**Comment by Vinciri** [comment]
hm. seems like this is mostly human error? i have fixed mine by just checking all the names in the owners section. this has seem to fix mine. /facepalm @Raqtor try this! 
![im dumb](https://user-images.githubusercontent.com/11388419/28808406-9d380e1e-7630-11e7-9375-a279d9b9d8bb.png)

**Comment by Raqtor** [comment]
Aye. Human coded the tool so it would always be true :p 
Seems "show mutated creatures" is disabled by default on all 5 installs I made. Fixed now.
Awesome tool even though its confusing and such important setting are so well hidden :)

**Comment by cadon** [comment]
Nice it's sorted out for everyone. Thanks for the feedback.

By default, all the owner-names are checked, i.e. all are shown. If you can reproduce that for a new library and a new owner-name the checkbox is disabled, let me know.

The view-options are on by default as well, it seems, the checkboxes were off if a new library had been created, but as soon it was loaded the first time, the checkboxes are right. This will be fixed in the next release.

I added another scrollbar which will make sure that these settings are always reachable (will be in the next release).

**Comment by meggymegz88** [comment]
Thank you so much for you help @cadon. I love this app so much so far and appreciate you having it for public use. :)
