### ISSUE TITLE
Extraction failing

### ISSUE THREAD

**Issue by CourteousDisruption** [cadon/ARKStatsExtractor#414]
Hi, 

I've got some mosas that won't import after imprinting. I think the server has updated since I got them. Seems to work ok pre-imprinting, but not after.

TamingSpeedMultiplier is 2.0, and BabyMatureSpeedMultiplier is 10, all others set to 1.

I can note down the pre-imprint stats for these two examples if that will help.

![20170728222009_1](https://user-images.githubusercontent.com/25478210/28717194-1de4c8da-73e4-11e7-9bc5-d6691b8d2144.jpg)
![20170728222052_1](https://user-images.githubusercontent.com/25478210/28717201-229a7f46-73e4-11e7-8029-7dc746d8b45f.jpg)

Any help appreciated, thanks

**Comment by cadon** [comment]
Hi, it works if you set the BabyImprintingStatScaleMultiplier to 1.2. Maybe the server has this setting?

**Comment by CourteousDisruption** [comment]
Thank you, it works for me with that setting also, and the levels match up with what I get when I extract the pre-imprinted stats. I'll have to check with the server admin to see if something's changed...
