### ISSUE TITLE
Sum and Should be variable 

### ISSUE THREAD

**Issue by LadiDog1950** [cadon/ARKStatsExtractor#419]
I have a couple of dinos this happens with.  Data entry 100% but Sum and Should be numbers done't match so I can't enter them into the app.
HELP.........

![image](https://user-images.githubusercontent.com/30669667/28893338-dea61c46-7785-11e7-958b-ab32f7ae813e.png)

Any help appreciated.  I know I'm just missing something simple

**Comment by cadon** [comment]
Hi, have a look at https://github.com/cadon/ARKStatsExtractor/wiki/Manual#what-to-do-if-a-stat-is-yellow

In your case, the stamina probably has 18 wild and 6 domesticated levels.

**Comment by LadiDog1950** [comment]
I really don't mean to be a problem but I have 'clicked' the yellow stat in
every part of it I can point my cursor at as well at rt mouse clicked.  NO
drop down box.  Best I can do is an up/down arrow adjust.  But since there
is no 'combination' drop down I can choose from I am flying blind.

When this is a 'bred' dino why would their be a wild stat adjustment
necessary?  Just curious.

Thanks,
Marie

**Comment by LadiDog1950** [comment]
disregard my last msg.  I found the problem.  Again, thanks for the help

**Comment by cadon** [comment]
Good to hear it's solved.
Regarding the last question: The wild-level is the level of a stat that is in the creature's genes, i.e. the levels without the manually leveled ones, these are the levels considered in breeding and passed on to the offspring. Sometimes the combination cannot be extracted uniquely (the stat turns yellow), so the user has to choose which combination is the correct one, the best way here is to try to remember how many levels are spent in this stat (represented by the domesticated level).
