### ISSUE TITLE
Weird Plesiosaur Levels

### ISSUE THREAD

**Issue by Sera-phina** [cadon/ARKStatsExtractor#420]
We have a male and female with one offspring. The offspring's stats match the fathers exactly but the offspring;s level is 31 while the father's is only 25. Why are the totals coming out differently? 

![image](https://user-images.githubusercontent.com/30477576/28921623-a9c8a06c-7824-11e7-818b-89e4b38d6c26.png)

**Comment by cadon** [comment]
Hi, the creatures that don't use oxygen do have an oxygen stat, but it's hidden. Also, the speed-levels (by not influencing the speed-value) are present and do count to the total level. So probably the son inherited the mother's oxygen and / or speed, which seems to be less than the father's.

**Comment by Sera-phina** [comment]
Thankyou!
