### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#421]
- abbreviations shifted to the right
- names are getting truncated(on selected pair it is hard to tell if it's Bob3 or Bob5)
- yellow graphs next to "breeding times" - is it possible to make transparent background for those labels?
https://i.gyazo.com/01af0249fe0186296931a53d7aab09f6.png

**Comment by cadon** [comment]
Hi, this is an issue related to the DPI-setting of windows, also see #151. I'll see if I can set the transparency to make it at least a bit better visually, if the base-issue cannot be resolved.

**Comment by VolatilePulse** [comment]
The first two are covered by the above mentioned issue. The third issue appears to have been resolved in a previous version as the text is shown under the graph now and should no longer interfere visually.
