### ISSUE TITLE
Values above 9999

### ISSUE THREAD

**Issue by Ortw1n** [cadon/ARKStatsExtractor#423]
Hey i'm playing on an unofficial server and have dino's with health and food above 9999. The program doesn't count over 9999 though. Is it possible to uncap it?

**Comment by cadon** [comment]
Hi, the upper limit for the stat-value-input is 10 000 000. You probably tried to insert the stat-value in the tester, which is for the levels. If you play on a server that has dinos with more than 9 999 levels in a single stat, this would be an issue.
