### ISSUE TITLE
Adding Dimetrodon [FeatureReq/Bug?]

### ISSUE THREAD

**Issue by Whyzerman** [cadon/ARKStatsExtractor#424]
One of the few species I have run across that does not have an Oxygen stat ingame. Due to this, the stat boxes are red, and I cannot add the creature. I disabled the "oxygen" setting and it still wouldn't take the extraction. I closed the client thinking that disabling/changing the oxygen setting would require a client restart of the app. When I loaded the client back up, I was able to sucessfully extract the dino to my library.

Wondering if you could add "Save and exit smart breeder, and reload it" to the list of troubleshooting steps, or if you can make the oxygen setting changeable without restarting the client. Either way would work for me.

**Comment by cadon** [comment]
Hi, the enabled stats are updated now after the setting was changed.

**Comment by Whyzerman** [comment]
Thanks for the quick fix.
