### ISSUE TITLE
tribe entry

### ISSUE THREAD

**Issue by defyreality** [cadon/ARKStatsExtractor#425]
there is a field in the "Player" tab for tribe. can it be made so if when entering info for a new/edited dino, and you pick an already entered owner, the tribe field will auto populate with that owners set tribe?
or have the "history" of entry's like the owner field does?

**Comment by cadon** [comment]
Hi, good idea. In the next release the tribe will have the same autocomplete, and if a player is entered a no tribe is yet entered, the tribe will be filled with that player's one.

**Comment by cadon** [comment]
New version with this feature is released.
