### ISSUE TITLE
Mutation value over 99,999

### ISSUE THREAD

**Issue by valarhan** [cadon/ARKStatsExtractor#426]
Mutations over 99999 (while pointless) creates an error that locks up the whole app.

Several times I've received this error:
_
![image](https://user-images.githubusercontent.com/27072415/29034455-29118c28-7b4d-11e7-966d-e93b31c261b8.png)

_> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.ArgumentOutOfRangeException: Value of '100000' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
> Parameter name: Value
>    at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
>    at ARKBreedingStats.CreatureInfoInput.updateMutations()
>    at ARKBreedingStats.CreatureInfoInput.parentComboBoxFather_SelectedIndexChanged(Object sender, EventArgs e)
>    at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
>    at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
>    at ARKBreedingStats.ParentComboBox.set_ParentList(List`1 value)
>    at ARKBreedingStats.CreatureInfoInput.set_Parents(List`1[] value)
>    at ARKBreedingStats.Form1.updateParentListInput(CreatureInfoInput input)
>    at ARKBreedingStats.Form1.setTesterInfoInputCreature(Creature c, Boolean virtualCreature)
>    at ARKBreedingStats.Form1.editCreatureInTester(Creature c, Boolean virtualCreature)
>    at ARKBreedingStats.Form1.toolStripMenuItemEdit_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.2101.1 built by: NET47REL1LAST
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> ARK Smart Breeding
>     Assembly Version: 1.0.0.0
>     Win32 Version: 0.23.13
>     CodeBase: file:///C:/Users/ValaRhan/Desktop/ARKBreeding/ARK%20Smart%20Breeding.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.2094.0 built by: NET47REL1LAST
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.2093.0 built by: NET47REL1LAST
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.2099.0 built by: NET47REL1LAST
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ----------------------------------------
> SMDiagnostics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
> ----------------------------------------
> System.ServiceModel.Internals
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.2046.0 built by: NET47REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box._

_

And when I click "Continue" and try to make the intended change (this particular time it's to a dino's name) it becomes completely unresponsive forcing me to close the program. (done this 3x or more)
 Occurring (for me) on Direwolf species (pics of wolf profile, formerly named "Uncle Matt" for mutation value verification).
![20170807084606_1](https://user-images.githubusercontent.com/27072415/29034361-f285e280-7b4c-11e7-8130-2cc9683a04f7.jpg)
![20170807084640_1](https://user-images.githubusercontent.com/27072415/29034362-f2903794-7b4c-11e7-81c6-85677cbff69a.jpg)

[ARKDinos.zip](https://github.com/cadon/ARKStatsExtractor/files/1205348/ARKDinos.zip)

**Comment by cadon** [comment]
Hi, thanks for the report. It'll be fixed in the next release.

**Comment by cadon** [comment]
Fix is released.
