### ISSUE TITLE
Getting the .ini's into the app?

### ISSUE THREAD

**Issue by Havouk** [cadon/ARKStatsExtractor#427]
Trying to drag&drop the two .ini's onto the settings tab, doesn't work. What gives? 
I can't get rid of the red values while extracting data, which makes me think there's something I've set up wrong in the settings. I got help setting the domestic levels up to 120 instead of the original 71 (I think?).

**Comment by cadon** [comment]
Hi, what exactly does not work if you drag'n'drop the .ini-files on the settings-window? What are your multipliers on the server? You can also enter all the multipliers by hand.

**Comment by Havouk** [comment]
The different stat multipliers is nothing I've altered in either of the .ini's, so what should I set them to? 

Also, the max wild level on my server is 120, due to that number has not been altered (The Island map), although the "domesticated/tamed level-ups" has been raised from 70/71, which is "standard" I believe, to 120 additional levels (not 70 + 120, but simply 120 levels). What I wonder though, is in the "Maximal Levels on Server" section, is if the "Max Tamed Levelups" then should be 240 or 120? And subsequently, which number of those two above, should the "Max Graph Level" be set from?

Lastly, is there some sort of template to download for the 1680x1050 resolution to use with the OCR? Because even though I try to work with the labels, it just wont get right. Thanks in advance, and keep it up on a great tool for breeding!

**Comment by cadon** [comment]
Hi,

1. set your stat-multipliers to the default multiplayer settings, or, if you have enabled the singleplayer-settings on the server, set the multipliers to the default singleplayer-settings (both settings can be set with a button below the stat-multipliers).
2. max tamed levelups is the number of levels you can level up a creature manually, so you'd set it to 120.
3. The max graph level does only affect the graph-scaling, set it to a value that you like. Usually a third of the wild-max levels is fine, i.e. 40, if your max wild level is 120.
4. I don't have an ocr-config file for 1680x1050 yet. If I get one, I'll include it in the release.
