### ISSUE TITLE
Make it runable on linux system

### ISSUE THREAD

**Issue by hudi1** [cadon/ARKStatsExtractor#428]
Hi man,
your old version of this application was runnable on linux system with mono program. Is there a chance to make it compatible with linux again ? Now there is error:
Could not load file or assembly 'System.Speech, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
becase this library exist only for windows: https://stackoverflow.com/questions/31633568/system-speech-in-mono-on-linux

**Comment by cadon** [comment]
Hi, it's a known issue (#237). Currently I don't know how I can fix this. If you know, I'd be happy to know. A solution would be to create a different build without this dependancy. To have it dynamically in the code (only use the library if it is available) would be the best solution, of course. I'll close this issue as being a duplicate to #237, feel free to give further feedback there.

**Comment by hudi1** [comment]
thx for the answer. I am java expert and dont know a lot about C but when I will have time I will try to look into this problem deeper
