### ISSUE TITLE
Raising tab not showing the proper names for the parents

### ISSUE THREAD

**Issue by glitchsniffer** [cadon/ARKStatsExtractor#430]
Noticed this first on my argents, but it may have happened on my quetzals too.  I selected parents Y1 and W1 to mate, but when I looked at the raising tab, it showed the names of W3 & W1.  The raising tab is not taking into consideration the Breeding mode.  If you select the the breeding mode conservative, it is correct.  But if you select the lucky or high stats, it just adds the conservative dinos.

**Comment by cadon** [comment]
Thanks for the report! It seems always the parents of the first row are taken. This will be fixed in the next release.

**Comment by cadon** [comment]
Fix is released.
