### ISSUE TITLE
Cant imput stats into extractor

### ISSUE THREAD

**Issue by Chivarius** [cadon/ARKStatsExtractor#431]
After selecting the dino and it's level I try to input numbers manually into the extractor but they are all greyed out and I cannot input anything. pulling from the game doesn't work either. 
![arksmartbreedingerror](https://user-images.githubusercontent.com/30882093/29149005-bc1f4d80-7d36-11e7-9303-4fd1e406ebe8.png)

**Comment by cadon** [comment]
Hi, you're using a pretty outdated version. Try it with the [latest release](https://github.com/cadon/ARKStatsExtractor/releases/latest).
