### ISSUE TITLE
Values File Missing

### ISSUE THREAD

**Issue by Kharilan** [cadon/ARKStatsExtractor#434]
I just downloaded the ARK Smart Breeding app and when i attempt to open the .exe i'm greeted with an error stating "Values-File 'json/values.json' not found. This tool will not work properly without that file." and asks me if i want to revisit the homepage and redownload it. I have all of the files downloaded and if i choose 'No', i'm greeted with "The values-file couldn't be loaded, this application does not work without it. Try redownloading the tool" of which i've tried repeatedly.

**Comment by cadon** [comment]
Hi, make sure you extract all the files and folders from the zip-archive.
