### ISSUE TITLE
Mutation and Generation number to the name generartor

### ISSUE THREAD

**Issue by glitchsniffer** [cadon/ARKStatsExtractor#435]
It would be nice to have the number of mutations and the generation added to the name generator.  I personally would like to see the generation represented as a letter vs a number though.  Either way, something for generation would be better than nothing.

**Comment by cadon** [comment]
Any preferences what the first generation (the tamed creature) should be? '0', 'A' or nothing, then the first bred generation would be 'A' or 'B'?
Also, how would it look after 26 generations, 'Z' -> 'AA' -> 'AB' etc. (like in Excel)?

**Comment by cadon** [comment]
New version with this feature is released. A tamed creature (with no known parents, i.e. generation 0) will be labeled 'A', then it's like in Excel. The keyword is `gena`. For a numbered generation use `gen`. For mutations use `muta`.
