### ISSUE TITLE
feature request - lower status bar showing creature counts in library made activeq

### ISSUE THREAD

**Issue by defyreality** [cadon/ARKStatsExtractor#436]
the status area at the very bottom that shows count on creatures in the library etc... could be made active when using the library tab, to show the counts on only the selected species/all etcc. whatever in being show in the large right hand window.  this could also be implemented elsewhere in the library window.

as a side note, while looking for a way to count my thylas without having to actually count them, i discovered the view tab within the library tab. the option in there are amazingly useful, perhaps moving them somewhere more visible (maybe a view pull down with the file/edit/?)

**Comment by cadon** [comment]
I added an extra label at the top of the library that shows some info about the selected creatures (number, number of each sex, level-range). If you have ideas for other useful infos, let me know.

Good idea also with the view-menu, I'll add that later.

**Comment by defyreality** [comment]
that's awesome.
