### ISSUE TITLE
Please add default Baryonyx colors (gold)

### ISSUE THREAD

**Issue by caesar-17** [cadon/ARKStatsExtractor#438]
![ark_gold_baryonyx_colors_ragnarok](https://user-images.githubusercontent.com/31001187/29266076-3e5b23c8-8098-11e7-9572-7619988068d8.jpg)

I can confirm on Ragnarok, wild Baryonyx have a (rare) "gold" yellow color.  Yellow comes in both "underside" and "stripes."

Stripe color (on top of animal,) is the same shade of yellow.  I cannot tell if this is #4, or #11.

Belly color comes in 2 shades of yellow: Pale and bold.  (I assume yellow #4 and #11.)  
(Shown screenshot is bold yellow belly color.)

Sorry I do not have a screenshot of the "sand" pale yellow belly; I culled all the ones I'm breeding because the pale just does not look good enough. :)  But I swear it exists.

Also Question:  Is there a way to show real dino pictures instead of just the color wheel?  I see that in old screenshots but don't know how to enable it.  Thank you Cadon for the wonderful program!

**Comment by cadon** [comment]
Maybe that's color 32 (Dino Light Brown)?
The pictures are only available for some species, it's difficult to create these images, so far only 7 species have them. You can download them here: https://github.com/cadon/ARKStatsExtractor/raw/master/images.zip and extract them in the application's folder.

**Comment by caesar-17** [comment]
![20170814043102_1](https://user-images.githubusercontent.com/31001187/29285621-e4fabae0-80e3-11e7-8f92-45821ca8b63d.jpg)


Negative, this Baryonyx's stripe seems to be Dino Light Brown.  It results in a metallic "copper" look.
The above is definitely a yellow-gold.

Thanks for image link, will check it out!

**Comment by cadon** [comment]
Are these colors maybe mutations? Here's a list of the current possible colors of the different species: https://ark.gamepedia.com/Talk:Color_IDs. Mutated creatures can have more colors. Also, it could be that mods or other maps change the possible set of colors. You can set any color for any color-region in smart breeding if you deselect "show only natural occuring colors".

**Comment by VolatilePulse** [comment]
Closing due to age and inactivity. We are now extracting the data directly from Ark and if naturally occurring colors are an issue, we will investigate them on a per species basis. With the recent Genesis DLC, each biome appears to have it's own event-style colorset that overrides the species default colorsets. This is still being investigated, but should be treated like traditional Event colorsets and manually selecting from all colors is required.
