### ISSUE TITLE
Weight value not reading correctly

### ISSUE THREAD

**Issue by Reed-Phoenix** [cadon/ARKStatsExtractor#439]
I have a low-level Tapejara, and I have classicflyers on this server, I have added the classicflyers.json. But the weight of the tape still says it's wrong.
https://gyazo.com/9927ebb9e6ee67f238dcdce174e17ba4
https://gyazo.com/11dfe3e670e2f3f59c11074e61d0b4fd
Here are the screen shots of both the game and the program. IF you need anything else, let me know.

**Comment by cadon** [comment]
Hi, are any multipliers changed on the server you're playing?

**Comment by Reed-Phoenix** [comment]
Yes, but only the taming and breading multiplier. And they are changed in the settings. I’m an admin on the server, so I looked. All my other dinos worked, just this tape did not.

Leave nothing but ash!
~Taylor Reed~

**Comment by cadon** [comment]
The weight was changed apparently. The updated values will be in the next release, until then you can download the updated file manually: https://raw.githubusercontent.com/cadon/ARKStatsExtractor/master/ARKBreedingStats/json/classicFlyers.json. Make sure to put it in the same folder where the library-file is located you're using.

**Comment by Reed-Phoenix** [comment]
Even though I already have classic flyers installed? Or is this a new version?

**Comment by cadon** [comment]
What do you mean? Just replace the new classicFlyers.json with the one you currently use.

**Comment by Reed-Phoenix** [comment]
That is what I was asking. I was wondering if that was a different version of classicFlyers.json.

Leave nothing but ash!
~Taylor Reed~

**Comment by cadon** [comment]
Yes, the weight-value of the tapejara is adjusted in the new version of the classicFlyers.json.

**Comment by Reed-Phoenix** [comment]
I will add it when I get home from work.

**Comment by Reed-Phoenix** [comment]
I just tried to download the link you gave me and all it did was take me to a page that had some text on it. What do I do?

**Comment by Reed-Phoenix** [comment]
Never mind. I fixed it. My computer was trying to render what you sent me. I was able to copy and past it into the doc.
Thanks!

**Comment by cadon** [comment]
Does it work with the new values? You can also just save the file the browser shows with right-click -> Save file, or Ctrl + S.

**Comment by VolatilePulse** [comment]
Closing due to age and inactivity.
