### ISSUE TITLE
No improvement on Breeding-mode conservative mode

### ISSUE THREAD

**Issue by permalost** [cadon/ARKStatsExtractor#44]
Just hatched three baby pteranodons and checking out my new options, but unless I miss my guess the baby of new1 and new2 will have no improvements.

the stats are identical (they were twins when hatching)  
15/32/18/17/19/12/20

![image](https://cloud.githubusercontent.com/assets/1111534/15236364/edbc66e6-1880-11e6-920a-f5a7de4d267a.png)

**Comment by cadon** [comment]
Hi and thank you very much! I thought that there was an issue with that mode, now I could track it down. This will be fixed in the next version.
