### ISSUE TITLE
the health and damage stats are not correct

### ISSUE THREAD

**Issue by simmissim** [cadon/ARKStatsExtractor#442]
i dont know if i did something wrong (i dont think i did) but the boxes are red and i cant fix it.

![2017-08-16](https://user-images.githubusercontent.com/31069994/29365541-adcb03ee-8297-11e7-8bf0-c4c7d8e94cc3.png)

i hope anyone can help me

**Comment by cadon** [comment]
Hi, you're probably have enabled the Singleplayer-Settings in your game, which changes the stat-values. Make sure you have enabled the Singleplayer-Settings-checkbox in the settings of Smart Breeding as well, then the rhino can be extracted.

**Comment by simmissim** [comment]
Thank you for the reply, ill go see if i have that enabled

**Comment by simmissim** [comment]
i have just checked if it was enabled but it isnt
anything else i could have done wrong?
![2017-08-17](https://user-images.githubusercontent.com/31069994/29405607-9d69a828-833e-11e7-935f-2dd99374ad0c.png)

**Comment by simmissim** [comment]
thank you very much, it seems to be working now.
