### ISSUE TITLE
Extractor issue

### ISSUE THREAD

**Issue by pim00107** [cadon/ARKStatsExtractor#443]
Hi,
Could somebody point out what I'm doing wrong? I play on an official server.

![naamloos](https://user-images.githubusercontent.com/31168791/29490166-1d414faa-8534-11e7-9c51-8aab251a6633.png)

**Comment by Celoain** [comment]
You are using the "," as a seperator. Try using a "." instead.

Feature request: Add option to in the config to use , as a decimal seperator. It'd make things much smoother as a german to be able to use the num block correctly.

**Comment by pim00107** [comment]
I can't use a "." as a seperator. If I typ "1.0", it will become "10,0".

**Comment by Celoain** [comment]
Then try either a server restart or getting giving it a level up. It should fix it's stats and you have to re-enter them.
I wonder how you got it to use , as a decimal as it doesnt work for me...

**Comment by pim00107** [comment]
Server restart won't work. I'm on an official server.
Giving it a level up isn't working either.
The stats still keep turning red. Isn't there something wrong in ARK Smart Breeding itself?

> I wonder how you got it to use , as a decimal as it doesn't work for me...

It just depends on the settings of your computer. For instance, my Excel also uses a comma as a decimal separator.

**Comment by cadon** [comment]
Hi @pim00107, it's the issue described in the red box below the stats. The lower stats only have 33x imprints so far, HP has 36. Wait some time, so the game applies the missing 3 cuddles to the other stats as well, it should sort out itself.

Hi @Celoain, the decimal-separator is the same as set in your system preferences. The num-block should always use the set decimal-separator.

**Comment by pim00107** [comment]
Hi @cadon it didn't sort itself out after a server restart and a few days. Is there anything else I can do?

**Comment by cadon** [comment]
Hi, you could level up a stat that doesn't work, maybe this will recalculate the other stats as well, at least the leveled up stat should be ok then. In generell it's best to extract the creatures as soon as they are born. The imprinting can be adjusted later as well.

**Comment by pim00107** [comment]
Okay, i'll try to do that later today. 

> In generell it's best to extract the creatures as soon as they are born.

I did, look at it's XP ;)

**Comment by cadon** [comment]
Before leveling, but also before imprinting.
