### ISSUE TITLE
Torpidity stays red even though values are right

### ISSUE THREAD

**Issue by Ihmislehma** [cadon/ARKStatsExtractor#447]
The issue is this: while all the values are correct, torpidity stays red. I have made sure the settings match my ini files (using the dragging feature), and enabled the Single player thing. (That btw fixed some problems I had earlier). However, no matter if I use the Read from ARK or type by hand the right values, torpidity stays stubbornly red. Animals tested on are two Equus and a Dilo (new save).

**Comment by cadon** [comment]
Hi, can you post your multipliers and a screenshot of the inventory of a creature that doesn't work?
