### ISSUE TITLE
Extractor doesn't seem to work

### ISSUE THREAD

**Issue by Panda-Macchitato** [cadon/ARKStatsExtractor#449]
Hi, I am really new to using this program, and I am trying to extract data from my dinos, but it keeps on coming out as red. I am not sure if I am putting write info, or something is not there i should be putting. 
![anklyo](https://user-images.githubusercontent.com/31391096/29753125-74c458f8-8b1f-11e7-9ec8-ee26a13c35ae.png)
![image](https://user-images.githubusercontent.com/31391096/29753134-996fff9a-8b1f-11e7-9ad8-916f85a480b8.png)

**Comment by cadon** [comment]
Uncheck "Exactly, don't adjust" below the imprinting.

**Comment by Panda-Macchitato** [comment]
Ok, i will see, if that works, if not i will let you know :D

**Comment by Panda-Macchitato** [comment]
![image](https://user-images.githubusercontent.com/31391096/29764570-781358ca-8b8c-11e7-9ecc-c7eda728ef5e.png)
It now gives me that for the extract.

**Comment by cadon** [comment]
You locked the domesticated levels of HP and speed, that prevents a valid combination. Uncheck them (click on the red lock) and it should work.
