### ISSUE TITLE
Wooly Rhino Speed bug.

### ISSUE THREAD

**Issue by xHibarix** [cadon/ARKStatsExtractor#45]
I saw this issue in one of your closed bugs. I waited until now to resend this bug. Saw you said you had fixed it so i thought maybe it would be fixed in an upcoming update. But time passed and well i'm still having this issue :(. I checked for a new version on the "?" and it says already have current version. I also manually upgraded to the newest release. Still have this issue :(
![rhino pic official server](https://cloud.githubusercontent.com/assets/18745348/15275842/6281a624-1a8b-11e6-9737-24e52a3ce73c.png)
Official server.

**Comment by cadon** [comment]
Hi, thanks for the report. Shame on me, I made a typo in the rhino-speed. It's fixed now for real and your number from the screenshot work. Check for the updated stats with ? -> Check for updates.

**Comment by xHibarix** [comment]
Working great now, thanks! :)
