### ISSUE TITLE
Breeding score formula: This must be wrong??

### ISSUE THREAD

**Issue by Raqtor** [cadon/ARKStatsExtractor#450]
I do not understand these breeding suggestions or breeding score.

This has to be some kind of glitch.

![screenshot 2017-08-28 15 40 57](https://user-images.githubusercontent.com/11212053/29776062-b7b2d2e6-8c07-11e7-8cf5-57961c3dea9e.png)

-Raq

**Comment by Raqtor** [comment]
Update:
Seems to only be on Conservative mode

![screenshot 2017-08-28 15 54 35](https://user-images.githubusercontent.com/11212053/29776576-4f2e45dc-8c09-11e7-87d0-8b76aa1ee0aa.png)

**Comment by cadon** [comment]
There should have been a message-box that explains that once you have a creature that has only top-stats, you shouldn't use conservative-mode anymore, but the high-stats-mode instead. If you didn't got this message, can you post your library, maybe there's a bug that prevents that message to appear for you.

**Comment by MalevolentSquid** [comment]
I don't think it's just him, I did not get that message either. Just fyi

**Comment by cadon** [comment]
Apparently this is due to the speed-stat not being levelable anymore. It'll be fixed in the next version. Until then, just select the high-stats-mode manually if a creature has only top-stats.

**Comment by cadon** [comment]
Fix is released.
