### ISSUE TITLE
Castoroides Stats

### ISSUE THREAD

**Issue by MalevolentSquid** [cadon/ARKStatsExtractor#452]
I'm having an issue getting the stats with Castoroides oxygen. Everything shows green but oxygen. No sp settings, all vanilla. I am on xbox though so idk if they changed Cast stats for pc's current build. On the wiki I see the base stats of cast oxygen is 750 with 75 per level. Mine tamed to 217  and I leveled it up once to see if it was a wrong stat in game. Ended up with 1713.8. On the dododex calc I see they have base oxy as 380 with +38 per level. That seems more on par with what I'm seeing.

**Comment by MalevolentSquid** [comment]
Just tamed another at the same level for verification. Same issue.

**Comment by cadon** [comment]
Hi, the oxygen for the beaver was changed. This update wasn't released on the xbox yet. You can use this old values-file with the old value until the update will be released on the xbox: https://github.com/cadon/ARKStatsExtractor/blob/151e9bb27fde2e9f7e6ccad9b0bfc89ace176227/ARKBreedingStats/json/values.json

**Comment by MalevolentSquid** [comment]
Thank you very much!
