### ISSUE TITLE
Kaspersky Malware Alert on build 23.16

### ISSUE THREAD

**Issue by Sakutera** [cadon/ARKStatsExtractor#453]
Kaspersky Malware Alert on build 23.16

**Comment by cadon** [comment]
Hi, the versions before were ok?

**Comment by Sakutera** [comment]
Yes, 23.15 that i'm using is just fine

**Comment by theant2222** [comment]
Hallo habe das selbe Problem 23.15 kein Problem 23.16 sperrt Kaspersky

**Comment by cadon** [comment]
I updated Visual Studio from version 2015 to 2017, probably that's the reason. No other changes were made that would explain that. I'll look if I can find a solution.

**Comment by theant2222** [comment]
![unbenannt](https://user-images.githubusercontent.com/29675510/30005092-2edc85f6-90db-11e7-9c0d-99b2a46f67cc.PNG)

**Comment by theant2222** [comment]
ARK.Smart.Breeding_0.23.17 no Virus Warning all fine for me thx you can Close this Issue 
Danke dir weiter top Programm!

**Comment by cadon** [comment]
Hi, thanks for the feedback. I have no clue, didn't change a thing that could cause this. Good to know it's not warning anymore.
