### ISSUE TITLE
Sex not communicated to Naming Pattern anymore

### ISSUE THREAD

**Issue by van-dell** [cadon/ARKStatsExtractor#454]
Version 0.23.16
On the Stat Testing and Extractor tabs, even though the sex is correctly saved into the library, the naming generator always lists unknown, in both short sex and sex.
Also, the counter {n} is not increased if there is a creature with the same name already in the library.
Great Progress on the app otherwise!

**Comment by cadon** [comment]
Thanks for the feedback. This will be fixed in the next release.

**Comment by van-dell** [comment]
Awesome!

**Comment by cadon** [comment]
Fix is released.
