### ISSUE TITLE
Extraction Issues

### ISSUE THREAD

**Issue by Thalen223** [cadon/ARKStatsExtractor#455]
Great App! I am really excited to start using it. 

My friends and I play on the unofficial cluster, SupremeArk - www.supremeark.com. I actually learned of your app from them. 

Here are the server's settings:
![image](https://user-images.githubusercontent.com/31707592/30129848-4746a3e2-9315-11e7-8434-b99c751c6c7c.png)

Below is the settings I manually typed into your ap:
![image](https://user-images.githubusercontent.com/31707592/30129893-7512a78a-9315-11e7-9082-bd1feb76866b.png)

I have been able to successfully upload a very limited amount of my dinos, however, most get denied.
![image](https://user-images.githubusercontent.com/31707592/30129973-b44db4ee-9315-11e7-811a-8c1905cc8384.png)

Below I will show you the errors I am getting:
Screen Shot of test Pteradon: 
![image](https://user-images.githubusercontent.com/31707592/30130224-7cac9432-9316-11e7-8ba5-2a8399767e34.png)

Result:
![image](https://user-images.githubusercontent.com/31707592/30130179-5b60c06e-9316-11e7-9053-fe3f7fdeb6fb.png)

This is what is happening 90% I try and extract a dinos stats. The one thing I notice is that the imprint on the extraction is not matching the imprint on the animal. I tried changing that number but it didn't work.

Thank you for the help!

**Comment by cadon** [comment]
Hi, two things:

- the creature was hatched during an event (Breeding Bonanza), so you need to check the "event"-checkbox below the species-selector. Make sure you enter the according multipliers in the event-column in the settings (the numbers can be found on your server's website below the standard settings.
- Apparently "classic flyers" is used on that server, you need to load the additional values that this mod changes with the classicFlyers.json-file (File -> Load additional values...). For more infos also see https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values

After doing this, you can extract the creatures (at least the ptera worked well).
