### ISSUE TITLE
Issues with the extraction

### ISSUE THREAD

**Issue by Demakrow** [cadon/ARKStatsExtractor#456]
Got a problem where values are missing by like tiny values. I am on an unofficial server where the stats are the same as an official server. This trike that i just tamed, while i was taming it i ran it through the calculator
![trike1](https://user-images.githubusercontent.com/31800565/30241375-7dbc4552-9582-11e7-9537-95795db10478.jpg)
![trike2](https://user-images.githubusercontent.com/31800565/30241379-840d3a24-9582-11e7-9fdc-7df5a11e406f.jpg)
I also tried it on my Ankylos tho it isn't working on either of them. Both are 145. I tried it on my 150 kentro as well and it just won't add in the health stat
![smart breeder](https://user-images.githubusercontent.com/31800565/30241405-0a20f222-9583-11e7-8186-a2e0869a94c4.jpg)
I have no idea if im just using the app wrong or what but I can't find anything on how to fix it

**Comment by cadon** [comment]
Hi, could it be that the max wild level is higher than 150?

**Comment by Demakrow** [comment]
No it was a 150 that was perfect tamed 74 extra levels 99.6% taming effectiveness

**Comment by cadon** [comment]
Strange. The issue is, that with a TE of 99.6 % it should have a melee damage of 307.9%. The 306.2 % contradicts all of this, so the extraction fails.
Did you drag'n'drop the game.ini and gameusersettings.ini into the settings? Sometimes users think everything is set to the default, but the game interprets things differently sometimes.

**Comment by Demakrow** [comment]
Might be. I'll get the admin to send me the files later today. I'll let you know if it helps. As long as i get the settings right I'll be able to add in all my dinos since I pretty much remember their stats

**Comment by Calestra** [comment]
I've having the same issue. Either damage or health doesn't work, and if I manually enter one, the other won't. It's either or. I have the stats from the admin, and I have the correct resolution... Is it a bug? There's nothing to adjust, and my wild/tame/bred is always red. I've been fighting it for two hours. :{

![](https://cdn.discordapp.com/attachments/359051841494843392/359148748691210241/unknown.png)

**Comment by Demakrow** [comment]
So I got mine fixed a couple of days ago. And it was as Cadon said I needed the GameUserSetting.INI File and the Game.INI from the server. As well as turning off the Consider Wild-Level steps setting off. It was causing a few issues.

**Comment by Calestra** [comment]
I turned Consider wild-level off, I'll get the from the admin.

**Comment by cadon** [comment]
Hi @Calestra, with 2 in HP-tameLevel and 5 in Weight-tameLevel the extraction works fine for me:
(Equus, Lvl 201, TE: 88.1%): HP: 4527.5 (31, 3); St: 3091.2 (36, 2); Ox: 495 (23, 0); Fo: 6450 (33, 0); We: 579.6 (19, 1); Dm: 319.5% (33, 1); Sp: 120% (18, 0); To: 5284.1 (193);

**Comment by Calestra** [comment]
It's still not working. I think the admin hid the server password from me in the file she sent, but I don't know why that would affect it since it isn't looking for that data. Just that health... 

![image](https://user-images.githubusercontent.com/32050033/30558525-9b76d540-9c66-11e7-8e6a-a3a2112303ea.png)

![image](https://user-images.githubusercontent.com/32050033/30558544-b0049ee8-9c66-11e7-9f12-26e54c6f0bd5.png)

I don't know what's wrong.

**Comment by cadon** [comment]
You have to set the changed multipliers in the tameLevel-column, you set it in the tameAdd-column.

**Comment by Calestra** [comment]
Changed it, and it still won't read health, even when manually entered, well all the stats are manually entered.

**Comment by cadon** [comment]
Do you have everything set like this?
![settingscalestra](https://user-images.githubusercontent.com/8763269/30563068-e3d33be4-9cc0-11e7-8a95-ee2b63f5ca57.png)

**Comment by Calestra** [comment]
No, I have them set to my server's unofficial stats-- this is from the gameusersettings: 
![image](https://user-images.githubusercontent.com/32050033/30570175-66137010-9c94-11e7-88c5-eabf80a48923.png)
and 
![image](https://user-images.githubusercontent.com/32050033/30570229-c81a88fc-9c94-11e7-904d-9f1f98b90474.png)

**Comment by cadon** [comment]
If you only compare the stat-multipliers, is this set for you like in the screenshot I posted?

**Comment by Calestra** [comment]
This is how I have it set. 
![image](https://user-images.githubusercontent.com/32050033/30584326-3de6fdd8-9cde-11e7-950e-4f64780aed1d.png)

**Comment by cadon** [comment]
You still have the altered multpliers in the wrong columns like last time, that's why it's still not working.

> You have to set the changed multipliers in the tameLevel-column, you set it in the tameAdd-column.

**Comment by Calestra** [comment]
Still won't anything, and I double checked the current stat value is correctly read, but Wild and Dom are still a no go. :/

![image](https://user-images.githubusercontent.com/32050033/30611272-c3b52320-9d35-11e7-876b-0a11dc192948.png)

**Comment by cadon** [comment]
Set all the stat-multipliers like they are in my screenshot first, please. After that, there still seems to be an issue with the damage, is the value really 1011.1% ?

**Comment by Calestra** [comment]
Yes, that stat is correct, I boosted for fun. The tamed is fine now, but the bred isn't. I did it as you did it in your screen shot and things came up red, and then with the multipliers for the breeding. Maybe I put that in the wrong column too. Those multipliers are:
MatingIntervalMultiplier=0.16
EggHatchSpeedMultiplier=15.0
BabyMatureSpeedMultiplier=37.0
BabyImprintingStatScaleMultiplier=1.0
BabyCuddleIntervalMultiplier=0.08
BabyCuddleGracePeriodMultiplier=5.0
BabyCuddleLoseImprintQualitySpeedMultiplier=0.1
CropGrowthSpeedMultiplier=2
CropDecayMultiplier=0.5
LayEggIntervalMultiplier=0.5

**Comment by cadon** [comment]
Hi, can you post a screenshot of the inventory with the stats of creatures that don't work?

**Comment by Calestra** [comment]
Here is the inventory of the last one, Sabertooth-- (i've added the weight carried in too, on different tests, and it didn't make a difference, but at this point I don't know anything, haha)
![image](https://user-images.githubusercontent.com/32050033/30663877-eb8d9f64-9e00-11e7-9ad4-057aeaca4a46.png)

The Triceratops - I've used her since the last screenshot, so there's a different amount of weight and she leveled up.
![image](https://user-images.githubusercontent.com/32050033/30663978-1d3b0e34-9e01-11e7-9bce-6bcc1f9acaf7.png)

I hope there are what you wanted

**Comment by cadon** [comment]
I rechecked you stat-multipliers, you have a 1 for the tameLevel in damage as well. With that it should work. If you have all the settings-files, you could just drag'n'drop them on the settings-window to set all the values automatically.

**Comment by Calestra** [comment]
I'll try that. -- Nope, dragged and dropped, still don't work. Later I'll uninstall and reinstall, then drag and drop. I'll post again to see if works, or doesn't.

**Comment by cadon** [comment]
That works fine for me. Did you select the correct level-combination for stamina (39/14) like it is described on the right?

I recommend to watch a video on how you can use this app, e.g. https://www.youtube.com/watch?v=zOYvKhLAHL4

**Comment by Calestra** [comment]
I had watched the video prior, and it seems the only thing that makes it work is leveling up a stat in the creature. So it's on Ark's side, not the program's. It appears the inventory is drastically displaying the melee in correctly.
