### ISSUE TITLE
Bred ankylo multiple red stats

### ISSUE THREAD

**Issue by freshrebel** [cadon/ARKStatsExtractor#457]
First let me say that i love the application :+1: 

Then my problem: i have an ankylo that i have bred but i get a lot of red values if i try to input him. As you can see:
![image](https://user-images.githubusercontent.com/10060982/30242917-3abab716-95a0-11e7-9a56-8c757c48eb8e.png)
so i thought the imprinting was not in yet. i restarted the server a lot of times and i even leveled melee damage by 1 lvl(to 488.3) but there was no change in the stats.
i'm playing on single player with these settings:
![image](https://user-images.githubusercontent.com/10060982/30242939-a6b90788-95a0-11e7-9e76-0f045e2d789d.png)
these are the stats from the anky(though i'm still working with the original stats as nothing changed and the changed stats also give the same result):
![image](https://user-images.githubusercontent.com/10060982/30242957-05511006-95a1-11e7-83f7-a555c58d6103.png)
my dino has 1 mutation maybe that has something to do with it. i was also thinking of the imprinting stat multiplier but that would not affect the torpor.
i recently managed to put in some dinos that i have tamed and that worked perfectly. so i really think it's something to do with the breeding/imprinting.

i have looked all over the internet but i can't find it.

added information: i dragged the Game.ini and GameUserSettings.ini files in the settings window to verify the settings and nothing changed so i think the settings are good.

**Comment by cadon** [comment]
I can't find a simple explanation for that. It could be that the singleplayer-multipliers got changed a bit. I'll check that later.

Did you change any multipliers of the server since the anky hatched?

**Comment by freshrebel** [comment]
Yes i've changed the timer how fast they grow up. But i don't think that has implications on the stats.

**Comment by cadon** [comment]
Ah, this changes the possible imprinting-values. Did you try to extract it with the old value? How much did you change that value?

**Comment by freshrebel** [comment]
same result with the old value.

Question: does the babymaturespeedmultiplier affect the stats?

**Comment by cadon** [comment]
AFAIK a creature uses the multipliers that were set once it hatched / was born, regardless what they are changed to. This could be wrong, though.
The matureSpeed and the cuddleInterval both affect the possible steps of the imprinting (e.g. with one setting possible %-values are 0,5,10,15, etc., and for different values possible values are 0,7,14,21,28, etc.). The imprinting affects the stat-value, so in the end both multipliers affect the possible stat-values.

**Comment by freshrebel** [comment]
i had the feeling that the changes really affected the growth speed when i changed it.
anyway so i'll try another one and don't change the settings and i'll let you know about the results. this one was no good anyway :)

**Comment by cadon** [comment]
If the growth-speed changed during the maturation, it's probably not possible to extract it, because two different maturation-speeds are mixed then. If the imprinting is 100% it should work, regardless of the maturation-speed, so there's a chance if you can imprint it fully.
