### ISSUE TITLE
Incorrect Breeding Generation Calculation

### ISSUE THREAD

**Issue by VolatilePulse** [cadon/ARKStatsExtractor#46]
I noticed that all dinos 2nd Gen and later were being marked incorrectly. I had a 2nd generation Dino that was listed as a 3rd generation and a 3rd generation listed as a 6th generation. I haven't looked at it closely enough, but it's definitely an issue in the recursive function. If I'm not mistaken, the "+ g" should be omitted from the return statements.

**Comment by cadon** [comment]
Hi, thanks for the report. That recursive function was really screwed up ;) The fix will be included in the next release.

**Comment by VolatilePulse** [comment]
I saw the fix. Thank you. Something else I was wondering was if the mom and dad were unknown but it is definitely a bred Dino, it shows up with a 0 for the generation. A simple return statement like as follows should work. `if (isbred && !mother && !father) return 1` I have a few dinos I was given a bit late in the server where the parents were known but already dead so there weren't any stats for it.

**Comment by cadon** [comment]
Hi, added that as well. In case the unknown parents of the creature are also bred, that still will result in false numbers, but it'll be one number more correct now.
