### ISSUE TITLE
Just an FYI, Bit defender keeps quarantining and deleting the exe for this

### ISSUE THREAD

**Issue by MutantRex2** [cadon/ARKStatsExtractor#460]
Obviously its a false positive.

I doubt its your doing. But thought I should make you aware.

**Comment by cadon** [comment]
Hi, thanks for the feedback. Some users reported this in the last days, I have no clue why Bit defender just now starts complaining, there was no change in the software that would explain it.

**Comment by MutantRex2** [comment]
The issue seems to be that it stores the save file when you create a library it auto puts it in my documents folder in the C drive. Which is a protected drive. So trying to save it there triggers bit defender, since moving mine it hasnt triggered it again.

Food for thought. Maybe its relevant maybe its not.

**Comment by vtallbloke** [comment]
well its my Anti virus keeps isolating mine, and I have mine saved in the downloads folder

**Comment by TomZandt** [comment]
I also have the same with Bullguard Anti Virus. Any Ideas?
