### ISSUE TITLE
Reported as containing Virus

### ISSUE THREAD

**Issue by vtallbloke** [cadon/ARKStatsExtractor#461]
As others have posted, my Anti virus keeps isolating both this and the previous version .15

Can you please look into this?

**Comment by cadon** [comment]
Hi, there were no changes in the tool that would explain this suddenly appearing warning. Are you using Bit defender? This is what the other users reported.

So far I've no idea why Bit defender (or others?) suddenly classifies the tool as dangerous.

**Comment by vtallbloke** [comment]
i dont use bit defender routinely
Ill link the information that my AV is telling me about the prog now.
Never used to do this, and previous versions still work.:

https://www.f-secure.com/v-descs/other_w32_generic.shtml

**Comment by vtallbloke** [comment]
i am not a programmer (sadly) maybe the information will help with tracking down the problem

**Comment by TyrelSackett** [comment]
bitdefender here as well.  just started. weird.

**Comment by TomZandt** [comment]
I have the exact same with Bullguard Antivirus. Any ideas?

**Comment by vtallbloke** [comment]
ok have updated AV today, shows (the zip) as having this:
Gen:Variant.Johnnie.55846
So I still cant use sadly :(

**Comment by cadon** [comment]
I just tried it with the newest release, there seem only 2 warnings left. Still no idea what causes them, but I uploaded it as a new release (only one small new feature), maybe it makes the application runnable on your system again.
