### ISSUE TITLE
Program will not run

### ISSUE THREAD

**Issue by BillBrasky84** [cadon/ARKStatsExtractor#464]
![capture](https://user-images.githubusercontent.com/31899266/30340273-8d16d684-97b7-11e7-91e4-b6ec13179623.PNG)

I am getting this error when attempting to run.  I have not run any previous versions.  ANyone experience this or have any advice?

**Comment by cadon** [comment]
Hi, maybe you don't have the needed .NET version? Usually it's installed with windows. You can download it here: https://www.microsoft.com/download/details.aspx?id=17718

**Comment by BillBrasky84** [comment]
Ok, I attempted this, but it still will not run. I'll keep messing around with it.  I hope I can get it to work, as I've heard it is a great tool!

**Comment by BillBrasky84** [comment]
Nevermind, I downloaded NET 4 when I needed 4.5.  After downloading 4.5 it worked.  Thanks for the help!
