### ISSUE TITLE
Fresh Install, First Allosaurus Not Saving (Error Saving)

### ISSUE THREAD

**Issue by KensonPlays** [cadon/ARKStatsExtractor#466]
Unsure of where to extract a log, or something to figure out, but this is a fresh install on a 64 bit Windows 10.

First dino I'm trying to add is my Allosaurus, but the "Add new to Library" is greyed out and will not let me save it, even though I have triple checked and all the stats are correct.

**Comment by cadon** [comment]
Hi, you have to extract the stat-levels first (the big button with "Extract Level Distribution").

**Comment by KensonPlays** [comment]
I tried that already. I hit all the buttons I could see in the interface.

I've also given up on ark for a while, lost a week's worth of stuff I was carrying, so I won't be playing for a while anyhow...

**Comment by cadon** [comment]
If the extraction fails, there is a list of things you can check to fix it. See https://github.com/cadon/ARKStatsExtractor/wiki/Extraction-issues

**Comment by KensonPlays** [comment]
I already checked that... Didn't help.

**Comment by cadon** [comment]
> if all of the above does not help the tool may have a bug => Upload a screenshot of the inventory where you can see the total-level and stat-values with the species-name, the multipliers you've set in the settings and wether you're playing on an official or unofficial server and send me the link of the image
