### ISSUE TITLE
New UI layout.

### ISSUE THREAD

**Issue by Cam7763** [cadon/ARKStatsExtractor#469]
The UI is very windows 7 looking, I myself do not do any coding but my tribe of 100 people use this program and it is very well built. I would love to see a modern UI, and i read about he community function that another user suggested. would love a response to see if the UI would be possible. 

Thanks

Cam

**Comment by cadon** [comment]
Hi, the library I use for Smart Breeding is WinForms, it's rather restrictive in how the application looks. Changing the UI-library would be a huge effort.
You can share a library with other users using cloud-services like dropbox or googledrive. https://github.com/cadon/ARKStatsExtractor/wiki/FAQ#how-can-i-share-the-list-with-my-tribe-members-and-edit-simultaneosly
