### ISSUE TITLE
Nice to have suggestions

### ISSUE THREAD

**Issue by WarBird25** [cadon/ARKStatsExtractor#470]
Hi cadon,

Working a little bit with the great application (and OCR) I have a few suggestions:
- reading the "raised by": This field could be saved or used as owner if the owner is not present. The owner field is not always present as it depends on the tribe settings.
- mutation tracking: Mutations play an important role to get the perfect tame. Currently it's only possible to set the number of mutations, I would suggest to add the possibility to be able to track the type of mutation. Tracking this information would enable a lot more possibilities:
-- mutations could automatically be inhereted (if parents are selected)
-- stat-mutations could be auto-detected after selecting the parents
-- dino color (mutations) could be tracked (entered manually at first occurrence)
-- mutations could be added better in the breeding plan (for now they are because of the higher stat, but eg. if I have a dino with 42 lvl + mutation and one with 44 lvl without mutation, the one without mutation can be prefered)

**Comment by cadon** [comment]
Hi, thanks for the feedback! I'll look into adding the extra label for the "raised by" text.

Regarding the mutations, it's not important which stat has a mutation, only the total number of mutations do matter. AFAIK even the game doesn't know which stat has a mutation, only the total mutation-number is saved for a creature.
* If you select the parents in the extractor, the current creature's mutation-counter is automatically set to the sum of the parent's mutations.
* I'll add the automatic detection of mutations, if it's clear that there was a mutation, and add it to the number of already calculated mutations.
* What do you mean exactly with the "tracking of color-mutations"? I could highlight the colors of the parents when the colors of the creature is selected if you mean this.
* I'll look into adding more possibilities to prefer non-mutated creatures in the breeding-plan.

**Comment by WarBird25** [comment]
Mh, yeah I think the game doesn't know as I had a breeded dino yesterday with the low stat and no mutation.
- Didn't know that, only figured that out after posting, sorry
- That would be great. Maybe you could also do a little flag which says "hey, this stat has a mutation" so it is easy to see at the extractor
- My idea is to be able to see and maybe prioritize colors in the breeding calculator. Don't know if that would be possible or too much work.
- I thought that ark knows the mutation and you can increase a stat of a non-mutated dino with a mutation if the mutated dino has lower health. But I guess that won't work. The second use of this would be, that the mutation counter is not increased and filled with the same mutation, but I think that was solved by ark. So I think there is no need to do that, need to have a look at.

**Comment by JuicyJuuce** [comment]
This video published a few days ago fills in gaps that are in all the other videos out there regarding mutations. The first chunk of the video covers the author's experience and the basics of breeding, so skip to 12:10 to see where he starts explaining mutations.

https://youtu.be/k3LHIjYUQZI?t=12m10s

**Comment by VolatilePulse** [comment]
All feature requests have been added. Mutation basics aren't as easy as they sound but are well documented in many places.
