### ISSUE TITLE
Ark smart breeding

### ISSUE THREAD

**Issue by miik3** [cadon/ARKStatsExtractor#472]
could you please add for 1600x900 resolution :) thanks in advance

**Comment by WarBird25** [comment]
You can adjust the OCR yourself, as I do for 3440x1440.
https://github.com/cadon/ARKStatsExtractor/wiki/OCR

**Comment by cadon** [comment]
Hi @miik3 , the best would be if you could do this. I have no monitor with this resolution, so I can't help with this. See the link that WarBird25 already posted. If you have further questions, you can ask them here.
