### ISSUE TITLE
Stat to Level issue

### ISSUE THREAD

**Issue by WarBird25** [cadon/ARKStatsExtractor#473]
I know several issues with stats have been reported, but my problem doesn't fit the others, thats why I open a new issue. I have scanend many dinos, but that's the first dino having this problem (all settings for stats are at default, server and application).
My rex has lvl 295 (bred). If I enter (or OCR) all the stats + level the meele damage is red:
![image](https://user-images.githubusercontent.com/24572064/30520943-53d82950-9bb7-11e7-8707-c1efc0e49bb7.png)

If I add 1 level in the application, meele damage goes green:
![image](https://user-images.githubusercontent.com/24572064/30520947-6542c1e6-9bb7-11e7-81d6-79d95d2e52a8.png)

The only difference I see comparing my other rex is, that this one has 51 lvl in movement speed, the others only 50 or 49 (they all have 100%)

It works for a lvl 298 rex:
![image](https://user-images.githubusercontent.com/24572064/30520990-0c06fb96-9bb8-11e7-8940-9165c70d3dc4.png)

**Comment by WarBird25** [comment]
repeating the text I get the same error with the 298 rex:
![image](https://user-images.githubusercontent.com/24572064/30521058-269423b6-9bb9-11e7-8a45-72493004e6e1.png)

but only if it is set to breed, if it's set to tamed it works:
![image](https://user-images.githubusercontent.com/24572064/30521069-42296b7c-9bb9-11e7-8f99-bae599bfe09d.png)

**Comment by WarBird25** [comment]
It also gives me different levels in the library for meele damage
![image](https://user-images.githubusercontent.com/24572064/30521112-4b2d1c22-9bba-11e7-81df-5bea0c2f2a15.png)

**Comment by cadon** [comment]
Hi, I tested the numbers, they work for me without issues. Did you check all the common causes on the right? Maybe you have enabled the singleplayer-settings in the settings of the application?

**Comment by WarBird25** [comment]
I checked all the causes. Settings are als standard (in application and server) and singleplayer is off. If any setting would be wrong, I would have the same problem with other dinos.

**Comment by cadon** [comment]
Can you post a screenshot of your settings in Smart Breeding? As I said, every creature you posted here works fine for me. Maybe there's a typo somewhere.

**Comment by WarBird25** [comment]
Here are my settings:
![image](https://user-images.githubusercontent.com/24572064/30772245-04ecd78c-a058-11e7-87f1-2849ff45f823.png)

**Comment by cadon** [comment]
It's still working for me. Can you set all the following levels in the Tester-Tab and look if the stat-values are like the ones you expect, especially if melee damage goes to 355.2%? (the first number in parenthesis is the wild-level you have to set in the Tester for each stat).

Rex (Lvl 298): HP: 11220.1 (46, 0); St: 2100 (40, 0); Ox: 720 (38, 0); Fo: 16200 (44, 0); We: 900 (40, 0); Dm: 355.2% (39, 0); Sp: 100% (50, 0); To: 29171.5 (297);

**Comment by WarBird25** [comment]
Works fine in the test tab:
![image](https://user-images.githubusercontent.com/24572064/30773246-568d4dd2-a06d-11e7-82a8-02960ef8883f.png)

I tested entering the numbers manuel and it worked (hit clear first):
![image](https://user-images.githubusercontent.com/24572064/30773292-524ed0aa-a06e-11e7-81d5-35691c92b243.png)

But the same values with OCR do not work (same error as above)

**Comment by cadon** [comment]
Thanks for the feedback! Can you post the fullscreen-screenshot of the inventory? Then I could use this to do the OCR myself and debug the steps.

**Comment by WarBird25** [comment]
Happy to help, hope you find the problem. Maybe the same happens for the other stat problem issues.

![20170924015116_1](https://user-images.githubusercontent.com/24572064/30778043-f7918736-a0ca-11e7-834d-e3f6575a0b49.jpg)
![20170924015132_1](https://user-images.githubusercontent.com/24572064/30778044-f791afd6-a0ca-11e7-9828-9365145c8626.jpg)

**Comment by cadon** [comment]
Every image works fine again when using OCR (the only issue is an additional decimal-separator in torpor in the first 1080-image).

Can you post the content of the OCR-Output when you enabled logging in the OCR-tab for the rex that doesn't work?

Is your windows using a dot or a comma for a decimal-separator? I don't think it's related to this, though.

And can you redownload the tool, maybe something weird happened to one of the OCR-template-files.

**Comment by WarBird25** [comment]
That's the output: 

Health: 11220.1/11220,1
Stamina: 2100.0/2100.0
Oxygen: 720,0/720,0
Food: 16182,4/16200.0
Weight: 20,0/900,0
MeleeDamage: 355,22,
MovementSpeed: 100.0%,
Torpor: 0,0/29171,5
Level: ::5175:::298
NameSpecies: ♀RexLw|Rex)
Tribe: ♂xp1erers

Maybe it's because of the "2," instead of %

**Comment by cadon** [comment]
Yes, that's the reason. Maybe you can adjust the character-template for the '2' and the '%', so it's not recognizing this wrong. I'll try to implement a check that removes additional decimal-places that are not possible.

**Comment by WarBird25** [comment]
I will try that, thank you! Cutting the additional decimal places would be great :)

**Comment by cadon** [comment]
fix is released

**Comment by WarBird25** [comment]
thanks!
