### ISSUE TITLE
OCR seems to be reading a different resolution?

### ISSUE THREAD

**Issue by Zordah** [cadon/ARKStatsExtractor#474]
Just started trying to use this on a Windows 10 laptop.

My native screen resolution is 1920x1080
When I take a Windows screenshot it is 1920x1080
Screenshots from Steam are 1920x1080
Ark is set to 1920x1080 WindowedFullscreen

When I select "Read Values from Ark Window" it brings Ark to the front but then nothing happens.   In the Experimental OCR tab the OCR output is

Error while calibrating: probably game-resolution is not supported by this OCR-configuration.
The tested image has a resolution of 1536×864 px.

Could this be cause the laptop has 2 video cards, an Intel HD Graphics 530 and an nVidia GeForce GTX 1070?

**Comment by cadon** [comment]
Hi, I haven't heard that kind of issue yet. It could be the switching to ARK isn't yet finished when the screenshot is taken, you can increase the waiting time in the settings under the OCR-group. The default value is 500 ms, maybe with 1000 ms it will work for you.

**Comment by Zordah** [comment]
Yeah I have taken it all the way up to 2000ms and left it for at least 5 seconds but it never returns to the calculator.

**Comment by cadon** [comment]
When you click on "Read Values", does it tab to ARK, so that you see the inventory in the game?
Do you have a second monitor with a resolution of 1536x864, or do you know where this resolution could come from?

**Comment by Zordah** [comment]
Yes.   I open the inventory of a dino in Ark, alt-tab to the calculator and click on "Read Values".   It then tabs to Ark and nothing else happens from that point on.
No second screen and I don't use that resolution at all so no idea where it is coming from.   I'm pretty sure that I have never hooked up this laptop to a second screen at any stage for it to remember an old resolution.

**Comment by cadon** [comment]
Sorry that never was resolved. Currently it's recommended to use the [import export method](https://github.com/cadon/ARKStatsExtractor/wiki/Importing-Creatures#ark-exports) which is more reliable. There are currently no plans to improve OCR.
