### ISSUE TITLE
The extractor won't extract level distribution

### ISSUE THREAD

**Issue by KimRestad** [cadon/ARKStatsExtractor#475]
It's probably I that made a mistake, but I just can't figure out what it is. As far as I can tell, the read values from the ARK window are correct (and I've also tried typing them in), as well as the settings corresponding to our server settings, but it just doesn't work. I haven't leveled up the dino as I wanted the post-tame stats (as can be seen from the xp bar in the first screenshot). I've also uploaded the stats the dino was tamed at (although it doesn't include torpidity so I can't enter the wild levels to test that). I really don't know what to do. I wish there was a way to just bypass the "level extraction" and adding the dino to the library with the stats entered, but I haven't been able to figure that out either, if it is possible.

I have tried many of my dinos and none of them has worked this far.

I have tried providing as much information as possible that could be valuable to this issue. Feel free to ask if there is something I've forgotten.

![image](https://user-images.githubusercontent.com/1381956/30560599-bbeb2432-9cb8-11e7-9e0e-5394648f8600.png)
![image](https://user-images.githubusercontent.com/1381956/30560607-c00847c0-9cb8-11e7-8197-7d0dee63cb09.png)
![pterok](https://user-images.githubusercontent.com/1381956/30560763-2c6bb64a-9cb9-11e7-8e4e-be32a7ef5616.PNG)

**Comment by cadon** [comment]
Hi, simple solution: you have enabled the singleplayer-settings in the game, which adjusts some of the multipliers. So just check the "Singleplayer-Settings" in the applications' settings.

**Comment by KimRestad** [comment]
WOW! Amazingly fast response, I thank you for that. I can also confirm that ticking the box helped. However, I don't understand why - the server is a multiplayer dedicated server so I never would have figured I _should_ tick the box that says "Singleplayer Settings". Have I set up my server weirdly?

**Comment by cadon** [comment]
Hm, I don't know, I haven't set up a dedicated server yet. Probably it's a setting in a control-panel or a starting-parameter. I guess by default this setting is disabled if it is not manually set, but I don't know.

**Comment by KimRestad** [comment]
Found a setting in the Game.ini file
`bUseSingleplayerSettings=True`
that's probably it! ;) Thank you for your help, I'm really happy I can now use your tool - it looks indispensable!

**Comment by cadon** [comment]
Good to hear :) Enabling that setting makes the game easier, most notably is probably the higher HP and damage of the leveled dinos.
