### ISSUE TITLE
Timer Not Showing in Overlay?

### ISSUE THREAD

**Issue by WallyOxen** [cadon/ARKStatsExtractor#476]
First off I'd like to say great program. I'm really in love with the overlay feature and I noticed that if I create a wake up timer for example in the taming tab and then go over to the timers tab I can right click that timer and click Add To Overlay. When I do I'm not seeing it anywhere on my overlay. I'm sure I have it on and I've tried to turn the overlay off and back on, turn it off then add the timer and turn it on, and completely restarting the program but nothing seems to work.

**Comment by cadon** [comment]
Hi, I remember this feature and IIRC this isn't working since I reworked the OCR for the UI-update of the game. Thanks for bringing it up again, I'll put it on the todo-list.

**Comment by WallyOxen** [comment]
Sweet, thanks! I'd love to be able to see the timers and not just have the windows noise (every time I hear it I keep thinking its windows and forget that its my timer. Maybe make an option for different sounds?)

**Comment by cadon** [comment]
You can change the sounds to any sound-file you want in the general settings (different sounds for Starving, Wakeup and Birth are possible).

**Comment by WallyOxen** [comment]
Oh, my bad. I'll do that now, thanks again! Great work!

**Comment by cadon** [comment]
The timers should now be displayed if you right-click and select "show in overlay".
