### ISSUE TITLE
Can not open the program 

### ISSUE THREAD

**Issue by InitalHero** [cadon/ARKStatsExtractor#478]
I'm 100% this is user error, however when I download the zip and extract it, I do not see an exe file to open. ArkBreeding Stats is an "SLN" file. Do I need a certain program to open this, or am I just looking in the wrong place? Thanks in advance for any help you can provide!  

![image](https://user-images.githubusercontent.com/32253760/30791539-bef18486-a178-11e7-821d-1b504f365517.png)

**Comment by cadon** [comment]
Hi, you downloaded the source-code. For just running the application, download a release: https://github.com/cadon/ARKStatsExtractor/releases/latest
