### ISSUE TITLE
[REQ] Additional precision for multipliers

### ISSUE THREAD

**Issue by trevorjd** [cadon/ARKStatsExtractor#479]
Hi,

From talking with one of my players this evening, I understand that the Cuddle Interval can only be specified in ASE to two decimal places. I was speaking with mod author Default last night and he said that the game calculates to six places.

We have maturity rate 25 and I had cuddle rate at 0.1 but some folks were complaining about not getting 100% imprint on some dinos.  After changing the cuddle rate to 0.0925, my calculation spreadsheet suggests they can get 100%. There's wiggle room of about +/- 0.0002 on that value :-D

So as enthusiasm and time permits, it would be nice to see extra precision in ASE.

Cheers,
Trevor

**Comment by cadon** [comment]
Hi, I'll include that in the next release. Probably you can already the extra digits and they will internally probably used, they just will be displayed as rounded value,

**Comment by cadon** [comment]
More decimal-places are now shown in the settings.
