### ISSUE TITLE
Crazy Pteranodon Stats

### ISSUE THREAD

**Issue by xwoundedbearx** [cadon/ARKStatsExtractor#48]
Perfect tame 145 on Center on Xbox One.
Current Stats do not match Breeding Stats.
Damage tamed at 360.3, but app is reporting 369.3
Food is similar.
New wild and domesticated levels are set properly.  This is on a dedicated server.

![capture1](https://cloud.githubusercontent.com/assets/19511502/15451662/75903570-1f9d-11e6-88c1-674eae8582db.JPG)

**Comment by xwoundedbearx** [comment]
Server has restarted.  Issues persist.

**Comment by cadon** [comment]
Hi, all stats are green, it seems to be a valid extraction. Melee Damage and Food get bonuses dependant on the taming-effectiveness (TE), bred creatures are considered to have 100% TE. For more infos see https://ark.gamepedia.com/Breeding#Stats_of_the_Offspring .

**Comment by xwoundedbearx** [comment]
It was strange for me to see that the the melee had technically dropped between from ~369 to ~360... Even though I know this is not the case.


That said, so long as all green is good to go, then I'm not terribly worried. Thank you!


Get Outlook for Android






On Sun, May 22, 2016 at 4:15 AM -0700, "cadon" <notifications@github.com> wrote:





Hi, all stats are green, it seems to be a valid extraction. Melee Damage and Food get bonuses dependant on the taming-effectiveness (TE), bred creatures are considered to have 100% TE. For more infos see https://ark.gamepedia.com/Breeding#Stats_of_the_Offspring .

---

**Comment by cadon** [comment]
Are you sure the ptera had a higher value for melee damage?
360.3 is the value of your current ptera, but it will inherit a value of 369.3. Some values (melee damage and sometimes food) get a bonus if bred compared to wild. That's the case here.

**Comment by xwoundedbearx** [comment]
Hello,

Thank you for the reply.

The Ptera is a tame and not a breed.  Idk if that matters.


Get Outlook for Android






On Mon, May 23, 2016 at 7:25 AM -0700, "cadon" <notifications@github.com> wrote:





Are you sure the ptera had a higher value for melee damage?
360.3 is the value of your current ptera, but it will inherit a value of 369.3. Some values (melee damage and sometimes food) get a bonus if bred compared to wild. That's the case here.

---

**Comment by cadon** [comment]
Yes, only bred creatures get that breed-bonus (aka a taming-effectiveness of 100%). Because your ptera is tamed, it has only 360.3% melee damage. If you use it for breeding, it will pass on a melee-damage-value of 369.3% to its offspring.

**Comment by xwoundedbearx** [comment]
Thank you so much. New to the app and thought I had all the answers =).

Thank you again for all your help and great job!


Get Outlook for Android






On Mon, May 23, 2016 at 11:53 AM -0700, "cadon" <notifications@github.com> wrote:





Yes, only bred creatures get that breed-bonus (aka a taming-effectiveness of 100%). Because your ptera is tamed, it has only 360.3% melee damage. If you use it for breeding, it will pass on a melee-damage-value of 369.3% to its offspring.

---
