### ISSUE TITLE
Oxygen/Speed on Water Dinos?

### ISSUE THREAD

**Issue by Joshcauchi** [cadon/ARKStatsExtractor#480]
I'm working on a little repository google doc for my tribemates to use to store their dino data post breeding for others to see, I'm trying to automate a few things and was wondering how Oxygen and Speed contribute to total level; For example, I have a Basil, its total level 466

HP: 37920 (74); 
St: 2460 (72); 
**Ox: ???? (??);**
Fo: 66240 (62); 
We: 1610 (65); 
Dm: 532.3% (68); 
**Sp: ???% (??);**

We all use the app and copy directly from it so figured the information would be within. I understand that the Oxygen stat simply doesn't exist, however I believe there must be a way to determine them. Sorry if this doesn't follow post conventions #newb

**Comment by cadon** [comment]
Hi, for aquatic creatures with no visible oxygen-stat there is no way to find out the wild levels of oxygen and speed, only their sum can be determined ([the torpor-level] - [the sum of all the other stats, except speed and oxygen]).

Basically the torpor-level is the sum of all the other stat-levels, i.e. Hp + St + Ox + Fo + We + Dm + Sp = To. All stat-levels can be determined for aquatic creatures, except Ox and Sp, so if we define a = To - (Hp + St + Fo + We + Dm), we know the value of a and can write the equation like a = Ox + Sp. This is the only equation we have, so there's no way to get the values of Ox or Sp, only the sum is known.

There is a way to get these numbers if you can use mods, then you can use the Super Spyglassmod.
