### ISSUE TITLE
Breeding Tab longer parent names

### ISSUE THREAD

**Issue by glitchsniffer** [cadon/ARKStatsExtractor#481]
Could you expand the width of the parent names to show more letters of the parent names in the Parent Stats section.  Currently I use the name generator on bred creatures to name my babies.  With my current setup, I cannot see the differentiating letters of the parents when breeding them.  It currently uses about 18 digits.  I would suggest that the Parent Stats be expanded to the same width of the General Infos and Progress windows in the Raising tab.  Also center the stats in that window and that should allow for enough letters to be displayed.

On a side note, when you use mutations on the name generator, it shows 3 digits, only 2 should ever be able to be used.  Maybe trim the digits to either the amount of digits that should be used, or only allow it to show 2 digits.

Thank you for all the support you have given me and thanks for adding all the suggestions I have given.  This program has been a huge improvement over my old spreadsheet.

**Comment by cadon** [comment]
Hi, good ideas, that will be included in the next release.
