### ISSUE TITLE
Read Values from ARK dmg bugged

### ISSUE THREAD

**Issue by Jebrero** [cadon/ARKStatsExtractor#483]
All the dinos appears with 5230342,0 of dmg

![image](https://user-images.githubusercontent.com/17874245/30973290-0f75b322-a46d-11e7-918c-9c4b6a8eb7d1.png)

**Comment by cadon** [comment]
Hi, what is the value you expect? What OCR-template are you using? Maybe you need to adjust some of the OCR-character templates for your resolution.
