### ISSUE TITLE
Lightning Wyvern extraction error

### ISSUE THREAD

**Issue by LupaPup** [cadon/ARKStatsExtractor#487]
Map is Ragnarok, No imprints have been done as seen in the picture. Taming is 10x.

![image](https://user-images.githubusercontent.com/6458365/31053881-9c393190-a674-11e7-8775-842b70522ddc.png)

**Comment by cadon** [comment]
Hi, very probably you have altered stat-multipliers on the server. Adjust the multipliers in the settings of the tool to the ones of the game. If you have the game.ini and/ or gameusersettings.ini you can drag'n'drop them onto the settings-window to set all the values automatically.

**Comment by LupaPup** [comment]
I've pulled the game.ini over from the server and its still providing red statboxes. For Stamina and Weight. I don't know if it matters that this is one Ragnarok or not, but pulling the Game.ini has provided no solution.

**Comment by cadon** [comment]
The stat numbers of Stamina and weight are odd. If you still have the issue, can you post the set stat-multipliers? As this issue is very old now, I assume it's resolved for now. If not, feel free to reopen it.
