### ISSUE TITLE
status doesn't stick when adding new dino to library

### ISSUE THREAD

**Issue by defyreality** [cadon/ARKStatsExtractor#488]
i've been added a few dozen thylas new to the library with the extractor and have been setting them as "obilisk" status before adding them (i use this to denote they are for sale). after added them they are set at "available" i have to go back in and change them to "obilisk" (which is easy as you have a feature to set status on multiple entries at once)

**Comment by cadon** [comment]
Thanks for the report, this will be fixed in the next release.

**Comment by cadon** [comment]
Fix is released.
