### ISSUE TITLE
Stats on Quetz showing up red but are fresh tame stats!!

### ISSUE THREAD

**Issue by Disneygimp** [cadon/ARKStatsExtractor#49]
![20160527120318_1](https://cloud.githubusercontent.com/assets/19608070/15606357/9d285d32-2403-11e6-8334-7940f8971e71.jpg)

Food and damage are showing up red, the rest are green.

**Comment by cadon** [comment]
Hi,
are you on an official server? Did you adjust the max wild-level in the settings if it's not 120? What Taming-efficiency was it, does the TE-range cover that?

**Comment by Faythe** [comment]
Same happens for me but it is not just the Quetz but any high level tame. We are on an unoffical server. I made sure to set the dino taming stats up in settings. This was just the first low level tame we have set up that it was still having the issues with. Our max level wild is 150.
![quetz](https://cloud.githubusercontent.com/assets/19614480/15618752/d0299c36-241d-11e6-9516-88d861ae93bd.png)

**Comment by LameDuck67** [comment]
I had similar Issues, setting Base Health for Quetzes to 1200 (down from 1500) and Base Weight to 780 (down from 820) helped.

**Comment by cadon** [comment]
Hi all,
I updated the stats-file accordingly the changes for the base-stats of the quetz (as LameDuck67 said). You can get the updated file by clicking ? -> Check for Updates in the tool.
Can you give feedback, if that helped to extract the levels?
