### ISSUE TITLE
Problem with Pegomastax Stat Extracting. (HEALTH)

### ISSUE THREAD

**Issue by 6yXJI0** [cadon/ARKStatsExtractor#491]
App can't extract their health. Tested in multiplayer and singleplayer with all options checked and unchecked.
All other dinos were extracted without issues.
![shootergame_2017-10-03_18-46-24](https://user-images.githubusercontent.com/32490288/31134657-6f8e5898-a86b-11e7-8cb7-7f00287c15b8.png)
![ark smart breeding_2017-10-03_18-47-21](https://user-images.githubusercontent.com/32490288/31134664-742c4d38-a86b-11e7-9a37-75717fb8eb77.png)

**Comment by cadon** [comment]
what are your server-settings?

**Comment by 6yXJI0** [comment]
I reset settings to default and everything is ok.

**Comment by cadon** [comment]
Hi, I adjusted the Pegomastax gain per wild level, it should work now. It could be a new multiplier, haven't figured out the reason for that change yet, for now it should work. You can get the updated values by clicking on the menu ? -> Check for Updates.
