### ISSUE TITLE
Well... I still can't extract Pegomastax HP.

### ISSUE THREAD

**Issue by 6yXJI0** [cadon/ARKStatsExtractor#494]
This is from 1.5 server (I changed settings to 1.500 Tame)
![shootergame_2017-10-04_05-55-01](https://user-images.githubusercontent.com/32490288/31158302-6eb87b84-a8c9-11e7-9dcc-d010819d0efd.png)
![ark smart breeding_2017-10-04_05-55-29](https://user-images.githubusercontent.com/32490288/31158303-703758c2-a8c9-11e7-96d8-057b28ca1db8.png)
This is My second Pegomastax on 1.5 server
![shootergame_2017-10-04_05-56-20](https://user-images.githubusercontent.com/32490288/31158307-7c196252-a8c9-11e7-8678-bac41a9b253a.png)
![ark smart breeding_2017-10-04_05-56-26](https://user-images.githubusercontent.com/32490288/31158308-7d132a08-a8c9-11e7-950c-a2fa4d9db04b.png)
And this is pegomastax i spawned and tamed on singleplayer with single player option enabled.
![shootergame_2017-10-04_06-00-20](https://user-images.githubusercontent.com/32490288/31158313-8c77dd4a-a8c9-11e7-81a3-8c1786c9158e.png)
![ark smart breeding_2017-10-04_06-00-26](https://user-images.githubusercontent.com/32490288/31158316-8d625d48-a8c9-11e7-9b4b-bcf9256876fb.png)
All other dinos can be extracted almost perfectly

**Comment by cadon** [comment]
Hi, I adjusted the Pegomastax gain per wild level, it should work now. It could be a new multiplier, haven't figured out the reason for that change yet, for now it should work. You can get the updated values by clicking on the menu ? -> Check for Updates.
