### ISSUE TITLE
Wyvern Red boxes

### ISSUE THREAD

**Issue by K0oky** [cadon/ARKStatsExtractor#499]
i manually restarted our server after i raised several wyverns. if i put it on 100% imprinting that i got some of them on then some of the red boxes go away but some do not. 
![screenshot 1](https://user-images.githubusercontent.com/32671816/31383363-bf1760b4-adf5-11e7-8eeb-2f6e2b732aea.png)
![screenshot 2](https://user-images.githubusercontent.com/32671816/31383366-c0389d8c-adf5-11e7-84b4-a66420db5a5e.png)
 the next 2 screen shots are from my first wyvern from the other day and it only had 86% imprinting. Ive added 40 levels into it already but still the same issues. even after waiting a day and doing a manual restart once. 
![screenshot 3](https://user-images.githubusercontent.com/32671816/31383531-5b31f8f6-adf6-11e7-9dbc-2acb325bd919.png)
![screenshot 4](https://user-images.githubusercontent.com/32671816/31383532-5c087bc4-adf6-11e7-97b9-0540a870cc68.png)

**Comment by K0oky** [comment]
forgot to mention that this an unofficial server that has no mods.

**Comment by cadon** [comment]
Hi, you probably haven't set the stat-multipliers in the settings to the values of the server. E.g. 405 levels in weight are not possible on a level 240 creature. Probably the weight-stat-multiplier has an increased value.

Ask your server-admin if they can provide the stat-multipliers.

**Comment by cadon** [comment]
The BabyStatScaleMultiplier has to be set to 25, then it works.
