### ISSUE TITLE
Doedicurus

### ISSUE THREAD

**Issue by ZappaBrannigan** [cadon/ARKStatsExtractor#5]
I have recently tamed a Doedicurus, I recorded his level and stats post-tame without any further levelling and I am unable to extract his stats properly. I have 'just tamed' unchecked because hovering over says 'if server has not been reset since tame' which I believe it had but not 100% so I will include an image with the box both checked and unchecked.
![doedicurus](https://cloud.githubusercontent.com/assets/16829363/12501178/377a53de-c06f-11e5-8149-4242beb4602e.jpg)
![doedicurus2](https://cloud.githubusercontent.com/assets/16829363/12501179/38c626aa-c06f-11e5-95c3-0bf803a7fc2d.jpg)

**Comment by ZappaBrannigan** [comment]
I forgot to add that he was kibble tamed with 98-99% TE . Pre-tame he was lvl 116

**Comment by cadon** [comment]
Hi, thanks for the feedback. Did you double-check the values you typed in?
The Checkbox has to be checked in your case, the torpor-stat looks like the server hasn't been restarted (there is a bug that sets the torpor too high until a restart).

If the problem persists, can you attach a screenshot of the inventar of that Doedi ingame?
