### ISSUE TITLE
OCR "comma" bug

### ISSUE THREAD

**Issue by axi92** [cadon/ARKStatsExtractor#50]
If my value is for example 1485,5
The OCR exports 14855,0
Every time the comma is one digit to the right.

158,5 gets 1585,0
.....
I hope my case is clear =)

**Comment by cadon** [comment]
Hi, what resolution do you use?

**Comment by NakramR** [comment]
And a screenshot of the ARK window would be greatly appreciated for
debugging purposes.

In this case I think I know the issue though. Do you live in a country
where the "." separator is the norm, or is it the "comma"?

**Comment by axi92** [comment]
![1](https://cloud.githubusercontent.com/assets/1394837/15719502/813d48b8-2830-11e6-930a-76ca3804005e.jpg)

**Comment by NakramR** [comment]
a fix has been submitted for this specific issue, I'll let cadon handle the
release & closing of bug reports ;-)

**Comment by cadon** [comment]
A new version that fixed that issue was just released.
