### ISSUE TITLE
extraction stats are red, megatherium official server

### ISSUE THREAD

**Issue by NovaMagic** [cadon/ARKStatsExtractor#501]
![screenshot_2](https://user-images.githubusercontent.com/32695714/31423163-f6b8a4e4-ae20-11e7-9a02-0e043c59b97c.png)

**Comment by cadon** [comment]
Hi, for imprinted creatures, there's an exception when they have exactly 100% imprinting. Then you might have to make a tic on the "Exactly, don't adjust"-checkbox (and that's usually the only exception to enable that checkbox).

**Comment by NovaMagic** [comment]
Thank you! This fixes a lot of stuff for other dinos aswell!
