### ISSUE TITLE
Can't remove multiple timers at once.

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#502]
Few timers selected. When I rightclick one of those and select 'remove', prompt is only for single entry (one that was added last).

---
And a bit unrelated, but still about timers. If you think it makes sense I can create separate request-issue for described below and if not, just ignore this section.
I was thinking maybe instead of current functionality of "set timer to end in" buttons they should have additive behavior?
 For example: I need to set timer for 30 minutes. Atm I need to type in 'finish time' or 'custom' values. If '10m' button would behave as +'10m' it would be just 3 clicks.

I do understand that it kinda opens pandora's box and comes with baggage of additional '-xx' and 'reset' buttons. And I have a hunch I'm only one who requests this stuff.

**Comment by cadon** [comment]
Hi, good ideas, thanks for that! I'll add these features in the next release.

**Comment by cadon** [comment]
Version with these feature is released.
