### ISSUE TITLE
Breeding plan not going to the species of the dino you selected

### ISSUE THREAD

**Issue by arathein** [cadon/ARKStatsExtractor#504]
Hello again -
So currently in the Drop down for Species I have "Paracer"
If I go into the library, right click one of my direwolves and chose show best breeding partners, it takes me to the breeding plan tab, but with Paracer selected, If I go back to the libary right click again, select best breeders, then this time it takes me to the breeding plan tab with my direwolves showing, but still with Paracer highlighted on the breedable species left pane
![image](https://user-images.githubusercontent.com/28239481/31571447-9b871d28-b058-11e7-82b0-95006b2367d4.png)
![image](https://user-images.githubusercontent.com/28239481/31571448-aa0c5c5a-b058-11e7-80ba-bc987027cde4.png)
![image](https://user-images.githubusercontent.com/28239481/31571451-b2e29cfe-b058-11e7-8645-b69adb66864d.png)
![image](https://user-images.githubusercontent.com/28239481/31571455-bed0d86e-b058-11e7-9043-c4eefa08a673.png)

**Comment by cadon** [comment]
Hi, thanks for the report, this will be fixed in the next release.

**Comment by cadon** [comment]
Fix is released
