### ISSUE TITLE
How to account for DinoClassDamageMultipliers

### ISSUE THREAD

**Issue by Barnabyowl** [cadon/ARKStatsExtractor#506]
I am trying to account for the following server setting: DinoClassDamageMultipliers=(ClassName="Rhino_Character_BP_C",Multiplier=0.8). I tried changing the base damage for rhinos to 0.8 in stats.json but this would still bring up the extraction failed errors, anyone able to help me get my server's settings to work with this app? I'll attach my server's settings files (i am mainly only interested in Woolly Rhinos for now)
[Settings_Oct_12 (1).txt](https://github.com/cadon/ARKStatsExtractor/files/1384416/Settings_Oct_12.1.txt)
[Game_ini_Oct_12 (1).txt](https://github.com/cadon/ARKStatsExtractor/files/1384417/Game_ini_Oct_12.1.txt)
![arksba](https://user-images.githubusercontent.com/32786966/31572658-e2ba3b74-b05f-11e7-8ee0-667c1ecb0487.PNG)

**Comment by cadon** [comment]
Hi, I'm not sure if these settings really change the displayed damage-number in the game or if they just change the dealt damage without changing the displayed stat-number. Did you try to extract the creatures without any changes in the json-files?

**Comment by Barnabyowl** [comment]
Tried on the default json, still get extraction errors on wild dinos and tamed non-lvled dinos, I doubled checked my settings and they all look like they are set correct
![asm](https://user-images.githubusercontent.com/32786966/31587115-98c30f00-b190-11e7-861a-2b0cac330ddd.PNG)

**Comment by cadon** [comment]
Did you change the multipliers since the first post? A torpor of 9600.5 is 100 levels for me, in your screenshot 36 is displayed.

**Comment by Barnabyowl** [comment]
nope same settings, I just realized there in that first extraction picture it switched the dino over to an argy for some reason,It does show 100 lvls for torpor for me as well, all my rhinos have 0 after tame levels spent and the program doesnt display choices close to the dinos wild lvl or taming effectiveness (the picture above was a 99% effective lvl 168 rhino) a couple also do this where it doesnt see the torpor value as being valid ( this one is a lvl 174  99% effective)
![ark](https://user-images.githubusercontent.com/32786966/31589170-ea1054f0-b1b1-11e7-8441-bc9d6350ec1d.PNG)
The server admin said the 2 settings file I link are the ones still be used

**Comment by cadon** [comment]
Hi, after some trial and error I guess the multiplier for torpor for the wild-level isn't 2.5 but 1.0. It works at least with that.

**Comment by Barnabyowl** [comment]
Thanks so much for your help, it does work now really appreciate it!
