### ISSUE TITLE
More Advanced Incubation/Gestation timer settings?

### ISSUE THREAD

**Issue by 6yXJI0** [cadon/ARKStatsExtractor#508]
It's kinda hard to sync those, since we usually place our eggs in fridge when they are having like 5 minutes until hatching, for later.
Would it be possible to also include a changed (with multipliers) baby timers info in General Infos tab?

**Comment by cadon** [comment]
Hi, do you think an input to edit a timer would be good, or a button to set an egg to fridge-mode which would adjust the incubation time?

What do you mean with a changed baby-timer? If you change the babyMaturationSpeedMultiplier in the settings, the baby- and maturation-time in the general infos will adjust accordingly.

**Comment by 6yXJI0** [comment]
1) Inputs would be cool
2) I restarted the App and timers got refreshed. Strange...

**Comment by cadon** [comment]
Version with timer-edit is released.

Are the timers correct now, or does "refreshed" mean they are wrong now?

**Comment by 6yXJI0** [comment]
Correct
