### ISSUE TITLE
Breeding has Dinos that are dead, no longer available or removed still showing up

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#51]
As title says, how do I remove these from breeding if they are no longer in library?

If they are unavailable and the option to show them is turned off then they should maybe be excluded as well from breeding.

**Comment by cadon** [comment]
Hi, in the breeding planner only available dinos (should) show up. Just to confirm, is a dino that is either marked as dead or unavailable still showing up in the breeding planner?

**Comment by cyberangel67** [comment]
Ok I think I see what the issue actually is.

If I have the option to show dead or unavailable, then go to the breeding plan. Then switch the show dead etc. back off, the breeding plan doesn't update.

Maybe, haven't done Form development for awhile, but maybe need to do an event here so that when certain features are changed those that rely on it are forced to update.

**Comment by cadon** [comment]
Hi, I think I found the issue. If a plan was calculated, then a creature's status is changed from available to unavailable or dead, the plan was not updated when going back to the planner-tab. I added a recalculation of the plan if a creature was changed.

**Comment by cyberangel67** [comment]
Yeah that is exactly what happens, which is why I figured that if you change the display options or anything else in the game like remove a dino from the library for example and event could be fired that the breeding side can then say does that affect me then yes, must recalc my breeding. But anyway look forward to seeing that fixed.

**Comment by cadon** [comment]
A new version that fixed that issue was just released.
