### ISSUE TITLE
can not Add some Dino in the Library

### ISSUE THREAD

**Issue by tuvok81** [cadon/ARKStatsExtractor#511]
Hello,
i have a Problem .. i can not add Dino to my Library ..  have add some data from my GUS and Game.ini and i can read some data from my screen all fine .. but .. the last window is red .. and the button will not activate .. i use the classic flyers mod .. and i have load this .json

![2017-10-16 19_43_55-ark smart breeding - hm xml](https://user-images.githubusercontent.com/30367063/31626647-d5769136-b2aa-11e7-8dd5-8e8b07f059d8.png)

![2017-10-16 19_52_56-ark_ survival evolved](https://user-images.githubusercontent.com/30367063/31626904-a9f7c9ca-b2ab-11e7-86f6-138e3a39143b.png)

What is wrong or what can i do?

**Comment by cadon** [comment]
Hi, probably one of the stat-multipliers is not correct, maybe weight? Can you post the part of your game.ini that contains the stat-multipliers?

**Comment by tuvok81** [comment]
PerLevelStatsMultiplier_DinoTamed[0]=1.0
PerLevelStatsMultiplier_DinoTamed[1]=1.0
PerLevelStatsMultiplier_DinoTamed[2]=1.0
PerLevelStatsMultiplier_DinoTamed[3]=1.0
PerLevelStatsMultiplier_DinoTamed[4]=1.0
PerLevelStatsMultiplier_DinoTamed[5]=1.0
PerLevelStatsMultiplier_DinoTamed[6]=1.0
PerLevelStatsMultiplier_DinoTamed[7]=1.0
PerLevelStatsMultiplier_DinoTamed[8]=1.0
PerLevelStatsMultiplier_DinoTamed[9]=1.0
PerLevelStatsMultiplier_DinoTamed[10]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[0]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[1]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[2]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[3]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[4]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[5]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[6]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[7]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[8]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[9]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[10]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[0]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[1]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[2]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[3]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[4]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[5]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[6]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[7]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[8]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[9]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[10]=1.0

![2017-10-17 00_36_37-ark smart breeding - hm xml](https://user-images.githubusercontent.com/30367063/31638328-4ec0386c-b2d3-11e7-8db9-3eb9fbaf1e4a.png)

is this right?
a friend have make my Game.ini and GUS.ini for a long time .. i have for a test remove some Entry to show the Dino with his stats... but this is also not correct its a DB entry bevor they have make the nerv ... and i use the classicflyer mod .. hm

**Comment by tuvok81** [comment]
Hey, gives any Information for my problem?

**Comment by jwvanderbeck** [comment]
Have you clicked in each one of the yellow boxes and selected the right value?

**Comment by tuvok81** [comment]
hm.. @jwvanderbeck what do you mean? i have add my Data what i have get from the screen.. or what can i do?

**Comment by jwvanderbeck** [comment]
I mean that when you have yellow boxes, like you do for Stamina, Weight, and Damage in your screenshot, then it means that the program found multiple combinations that could be correct, and you have to help it figure out which is right.  You do that by clicking on each yellow box and then next to it will be a list of the possible options.  You choose the correct one to help it narrow down the correct combination of stats.

It may or may not fix your issue but if you haven't done that then you need to.

**Comment by tuvok81** [comment]
Hey .. hm what must i do exactly.. sorry for my bad english

**Comment by jwvanderbeck** [comment]
https://github.com/cadon/ARKStatsExtractor/wiki/Manual

Look to the bottom where it says whats to do if a stat is yellow.

Basically it means there are multiple combinations of stat levels that could be correct and you need to help it by choosing the correct ones in the yellow stats.  Setting one yellow stat often helps fix/narrow down the others as well.

**Comment by tuvok81** [comment]
ok .. but i will not understand this system .. sorry :( this is to hard for me i have use other combinatione for the yellow stat
![grafik](https://user-images.githubusercontent.com/30367063/31832389-1e200e2a-b5c7-11e7-9a0e-5fdede11cac1.png)

**Comment by tuvok81** [comment]
hm i have tame a Gigantopithecus and this will run .. hmmm very stupid .. why will the other Animals not run hm

![grafik](https://user-images.githubusercontent.com/30367063/31852808-d03ac61a-b67e-11e7-97f0-a79af1a984c6.png)

**Comment by cadon** [comment]
Hi, sorry for the late reply. Could it be that you spent 5 levels in oxygen? If you unlock the red lock-symbols on all stats, there is a possible level-combination

Quetzal (Lvl 240, Impr: 100%): HP: 56287.1 (21, 13); St: 3600 (22, 5); Ox: 675 (20, 5); Fo: 10212 (27, 0); We: 3481.9 (12, 20); Dm: 3183% (68, 19); Sp: 241.7% (6, 1); To: 42772.5 (176);

Usually these locks prevent combinations with spent levels in oxygen or food, mostly no levels are spent in these stats.
