### ISSUE TITLE
Anky not calculating properly

### ISSUE THREAD

**Issue by Gotharic** [cadon/ARKStatsExtractor#513]
I bred this dino on a private server, moved it to single player and now I am trying to catalog it with thte rest of my 300 dinos.  This one has been one of the 300 not working.  Great app though!

![sammich](https://user-images.githubusercontent.com/32945466/31800582-0e74f8f0-b4ff-11e7-96e3-a30b3fd9462f.jpg)
![20171019184908_1](https://user-images.githubusercontent.com/32945466/31800590-17e9318a-b4ff-11e7-91ec-4dcdcaa3f396.jpg)

**Comment by cadon** [comment]
Hi, it's probably caused by the transition from different stat-multipliers or the singleplayer-settings. The imprinting-value is only possible on multiplayer-settings. The true imprinting-bonus could be 98.38 % which is only shown as rounded value ingame (98 %). Then again, the food-value doesn't seem to fit or did you level up this stat? Maybe it helps if you go out of render distance, then restart the game and come back, sometimes this helps to force a recalculation of the stat-values.

**Comment by Gotharic** [comment]
1) This was reported after I left render distance and played for a few months.2) Food was not raised afaik3) Yes I believe it us because my imprinting multipliers and taming multipliers are different in single player than they were on the server they were bred on.


Sent from my Galaxy Tab® S2
-------- Original message --------From: cadon <notifications@github.com> Date: 2017-10-22  14:46  (GMT-07:00) To: cadon/ARKStatsExtractor <ARKStatsExtractor@noreply.github.com> Cc: Gotharic <kalthouse@telus.net>, Author <author@noreply.github.com> Subject: Re: [cadon/ARKStatsExtractor] Anky not calculating properly (#513) 
Hi, it's probably caused by the transition from different stat-multipliers or the singleplayer-settings. The imprinting-value is only possible on multiplayer-settings. The true imprinting-bonus could be 98.38 % which is only shown as rounded value ingame (98 %). Then again, the food-value doesn't seem to fit or did you level up this stat? Maybe it helps if you go out of render distance, then restart the game and come back, sometimes this helps to force a recalculation of the stat-values.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cadon/ARKStatsExtractor","title":"cadon/ARKStatsExtractor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cadon/ARKStatsExtractor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cadon in #513: Hi, it's probably caused by the transition from different stat-multipliers or the singleplayer-settings. The imprinting-value is only possible on multiplayer-settings. The true imprinting-bonus could be 98.38 % which is only shown as rounded value ingame (98 %). Then again, the food-value doesn't seem to fit or did you level up this stat? Maybe it helps if you go out of render distance, then restart the game and come back, sometimes this helps to force a recalculation of the stat-values."}],"action":{"name":"View Issue","url":"https://github.com/cadon/ARKStatsExtractor/issues/513#issuecomment-338507810"}}}

**Comment by cadon** [comment]
do you have non-default stat-multipliers on the old or the new server?

**Comment by Gotharic** [comment]
Both have non default taming and breeding but both had default stat multipliers


Sent from my Galaxy Tab® S2
-------- Original message --------From: cadon <notifications@github.com> Date: 2017-10-22  15:06  (GMT-07:00) To: cadon/ARKStatsExtractor <ARKStatsExtractor@noreply.github.com> Cc: Gotharic <kalthouse@telus.net>, Author <author@noreply.github.com> Subject: Re: [cadon/ARKStatsExtractor] Anky not calculating properly (#513) 
do you have non-default stat-multipliers on the old or the new server?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cadon/ARKStatsExtractor","title":"cadon/ARKStatsExtractor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cadon/ARKStatsExtractor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cadon in #513: do you have non-default stat-multipliers on the old or the new server?"}],"action":{"name":"View Issue","url":"https://github.com/cadon/ARKStatsExtractor/issues/513#issuecomment-338509158"}}}

**Comment by cadon** [comment]
I guess the best way to get the levels is to use the super spyglass mod that shows the correct levels ingame, http://steamcommunity.com/sharedfiles/filedetails/?id=793605978
