### ISSUE TITLE
[Suggestion] Add game.ini importer and more

### ISSUE THREAD

**Issue by Inkraja** [cadon/ARKStatsExtractor#514]
Hi, 

first thank you for all your work and keep it up. And here my suggestions:
1) Like the title say, add a importer option for the settings from the game.ini or any textfile, because user are lazy 
2.) 11 Settings-stats of a Dino is possible, but not in the setting possible: in the image are 5/6 and 10 missing
https://gyazo.com/e4c3b2efbf82889207aef6d9098c1990

3.) Same image, dont mess up the sorting :D 2/Torpor should not be the last in the list.
4.) Mods: Iam currently using the Gaia Mod, Dinos from the Mods become all red/wrong stats. Something to handle that will be nice. Same for flyer mods/Primal Fear and all other Dino Mods

**Comment by cadon** [comment]
Hi,
1. you can drag&drop the game.ini or gameusersettings.ini onto the settings-window to import the values of these files.
2. Some stats are not used by dinos like crafting-speed and water, so they are not necessary in this tool.
3. The sorting is like the stats are ingame. Wildcard messed the sorting up in the game.ini-file if anyone ;)
4. For mod-values, you can create an extra json-file, for more infos see https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values
