### ISSUE TITLE
Therizi not calculating properly

### ISSUE THREAD

**Issue by Gotharic** [cadon/ARKStatsExtractor#516]
![20171021135700_1](https://user-images.githubusercontent.com/32945466/31855404-dd20ed1c-b667-11e7-868d-40fc5ad940a3.jpg)
![thereizi](https://user-images.githubusercontent.com/32945466/31855401-d88f2412-b667-11e7-88ac-08ec021e5ea1.jpg)

**Comment by cadon** [comment]
Is this the only creature that does not work? Most probably some stat-multipliers are not set correctly.
