### ISSUE TITLE
Need help calibrating OCR font

### ISSUE THREAD

**Issue by Rhandomme** [cadon/ARKStatsExtractor#517]
Hi, first of all let me say thanks for this nice tool. I find it very interesting and useful. :)
I play Ark in my laptop at 1366x768 resolution and I am trying to configure it. Just to let you know I just realised that this tool detects a higher resolution when I do a screenshot (15XXx8XX, sorry I can't remember exact numbers), I thing it is because of the scaling in the game options. And it takes the screenshot with no problem from the game.
My issue is with font calibration, when I read numbers from the game the output in the OCR says it is not calibrated. Could you please explain me how I should calibrate it?
Sorry, I tried several times but I failed to do it following the instructions you have there: https://github.com/cadon/ARKStatsExtractor/wiki/OCR
I calibrated the zones where stats are taken from, but then I don't understand how to proceed.
Could you explain me a bit more detailed what are the steps I should follow, do I have to download some font file or something? And then how I should proceed?
I tried downloading some font file such as arial and then it reads the stats, but are wrong (maybe it is not the best font to use). What I have to do then in the template zones? I tried playing a bit with green and red squares but I think I am doing it wrong.
Thanks for your help and for this nice tool 👍

**Comment by Rhandomme** [comment]
Thanks for your help, gonna try it soon and let you know the results. :)

**Comment by benjiof76** [comment]
When 2 characters are recognized as a single character, how can we separate them?

**Comment by benjiof76** [comment]
Here is the ocr file in 1680x1050 resolution (the recognition of the stats is pretty good but you have to work on the other data)
[ocr_1680x1050_100.zip](https://github.com/cadon/ARKStatsExtractor/files/1448164/ocr_1680x1050_100.zip)
