### ISSUE TITLE
Feature Request: Highest Stat Summary

### ISSUE THREAD

**Issue by mrsimicsak** [cadon/ARKStatsExtractor#519]
When I'm breeding my goal is a male and female with identical stats that have all of the highest stats of everything in my library. To that end it would be very helpful to have a summary box on the library screen that shows the highest stat in each category from the dinos in my library. 

And if hovering over the summary box highlighted the highest stat in each dino that had that highest stat that would be even better,

**Comment by Wardjp** [comment]
In a sense, it already does this. It both highlights the name of the dinos that are your top breeders green. It also colors each stat based on it's relative 'score' and you can also sort by each stat. To which, my suggestion for addition would be to add the option to filter based on multiple columns at once.

**Comment by cadon** [comment]
Top stats are marked with a high saturation color. The hue depends on the value. Like Wardjp said, all creatures with a top-stat have their name highlighted in green.

To sort the creatures according to a column, just click on the column-header. You can click on a second column to sort the creatures according to that column, and if values are equal, they are sorted according to the last column the list was sorted for.

For you goal, you should set the breeding-planner to the "Top Stats Cn" (conservative) mode, and if you have a creature with all top-stats, set it to the "High Stats"-mode until you have both a female and a male creature with all top-stats.
