### ISSUE TITLE
More Than 100% Imprinting

### ISSUE THREAD

**Issue by pezrabioso** [cadon/ARKStatsExtractor#520]
Because of a server event, I received a creature which the admin had given 200% imprinting but I cannot add it to my library since the program won't go higher than 100% imprinting. Is there a way to get the program to go higher than 100% imprinting or any other solution?

**Comment by cadon** [comment]
I didn't know that's even possible. I can change the input-range of the imprinting-input, but it probably won't work with the extraction.

**Comment by pezrabioso** [comment]
Maybe it'll work, though it probably won't like you said. Well, honestly the program already has so many features that it can't have everything.

**Comment by pinedours** [comment]
Hello ! 
I ve this problem too but with the mod who is the most used for ark, Structure +.. There is now the S+ Nanny who gives automatically 100% imprint. But for me I dont know why, I ve many creatures who are 101% or 102% imprint quality.

**Comment by cadon** [comment]
Does the inventory of these creatures show "102 %" for the imprinting?

**Comment by pinedours** [comment]
Hi Cadon, yes this that. I ve two direwolfs at 101% and two (brothers)  sabertooth at 102%.
They grew up with the S+Nanny together, the same day.

**Comment by pinedours** [comment]
If you need a screenshot ask me, I m not with my game computer now but later.

**Comment by cadon** [comment]
Hi, yes, a screenshoot would be good to see how I handle these numbers the best.

**Comment by roffelund** [comment]
![20171211172429_1](https://user-images.githubusercontent.com/24315490/33841681-b27c8478-de98-11e7-8403-2221190eb46a.jpg)

@cadon 
Here is a screenshot of my giga with the same issue

**Comment by cadon** [comment]
An option for more than 100% imprinting was added in 0.24.6.
