### ISSUE TITLE
Extractor error with no conflicts?

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#523]
2488 levels in speed seems a bit off
https://i.gyazo.com/630fa13bade132b8249625c4f8fc1303.png

**Comment by Wardjp** [comment]
Well, 300% move speed seems a bit high for what the extractor is seeing as a 0 domesticated levels bred dino. Was that a fresh breed, or had you put levels into move speed? If it is a fresh breed, this means there's likely a config change either from your admin or from a mod on your server and the application can't discern. I'd find out those two things right now, until Cadon has a chance to hop in and help.

**Comment by deedoubleu** [comment]
It was fresh breed. Baby stage to be exact.
It is official legacy pvp server (eu-crossark10) without any event going on. After full maturation with some imprinting everything calculates correctly from what I can tell.
https://i.gyazo.com/6ce363203f07263648a476c9b8b47dd9.png

**Comment by cadon** [comment]
Hi @deedoubleu , you had a typo in the torpor value in the first screenshot. I'll add a visual feedback to make this error clearer.
