### ISSUE TITLE
extraction issues

### ISSUE THREAD

**Issue by PINK1102322** [cadon/ARKStatsExtractor#525]
After this 8x I am trying to put dinos into the program. Levels don't match at all. What do I do?

**Comment by deedoubleu** [comment]
Same here. I guess program expects correct maturation speed multiplier, but rate was dynamically changing during this dino growth.

**Comment by cadon** [comment]
Hi, it's probably hard to extract it exactly. The maturationSpeedMultiplier and the cuddleIntervalMultiplier would had to be set to the exact mean of all the values that occured during the raising of the creature (which probably isn't something that could be figured out).

It's best to extract creatures after they hatch / are born, before the first imprinting is applied. Then later the imprinting-bonus can be set by editing the creature.

You can extract it, if the creature hits an imprinting-bonus of 100%. In all other cases, you could try to set the imprinting-bonus to the exact number that it has ingame and check the "Exactly, don't adjust"-checkbox under the imprinting-input. Note, that then you have to enter the exact number, with all decimals, which is usually unknown, as the game only displays a rounded number. E.g. if the game shows an imprinting of 52%, the real number could be 52.2345% or 51.67843% etc. To find the exact number is probably not feasable.

**Comment by Bubbachunk** [comment]
No matter what I do, or how I enter the values, from ARK window, from screenshot, or manually, it always says it fails, I have contacted the owner of my unofficial server and sent him a copy of the breeder settings and he gladly filled in the values and it still does not work. is this program still valid, or is it no longer a working program?

**Comment by cadon** [comment]
It should work with the newest version with "Partly Event" enabled (under the imprinting-input).
