### ISSUE TITLE
Tamed Ovis x5 weight bad calculating

### ISSUE THREAD

**Issue by BoregardL** [cadon/ARKStatsExtractor#526]
Hello, today I noticed that ARKsb calculate ovis weight with x5 multiplier wrong. Im 100% sure I have everything how it should be, cuz all my other dinos are with no problem in library. I tryed to tame new ovis and extract fresh tamed stats - all went well, but when I have put 2 points into weight, calculating wrote error. Server unofficial ofc. See for yourself
Before
![before ovis](https://user-images.githubusercontent.com/33493935/32564245-f3d46f02-c4b3-11e7-8b50-bf8b93b285f4.png)
After
![after ovis](https://user-images.githubusercontent.com/33493935/32564374-5dddaa08-c4b4-11e7-9543-8c54e47b56bb.png)
Settings
![samrtbreedersettings final](https://user-images.githubusercontent.com/33493935/32564403-77802328-c4b4-11e7-8747-156d5e31aeb1.png)

Tyvm for solution!

**Comment by cadon** [comment]
Hi, you mixed "TameAdd" with "TameLevel". The TameAdd value is for the additive taming-bonus value. What you want to change is the TameLevel-value, which affects the increase per tamed level. I.e. set TameAdd of the weight back to 1.0 and the TameLevel of the weight to 5.0.

**Comment by BoregardL** [comment]
Works now, tyvm!
