### ISSUE TITLE
Ovis have no color to choose from

### ISSUE THREAD

**Issue by BoregardL** [cadon/ARKStatsExtractor#528]
Hello, I just noticed, that I cant choose any colors for ovis. I always add colors in this tab, not sure, if theres some other way. Tyvm for response! PS: Love your app!

![ovis no mut color](https://user-images.githubusercontent.com/33493935/32614915-980936a6-c56e-11e7-9c1d-cf2339f139ed.png)

**Comment by cadon** [comment]
Finally they are added.
