### ISSUE TITLE
OCR Flaws

### ISSUE THREAD

**Issue by Ryuichiro** [cadon/ARKStatsExtractor#529]
I don't think there is a way to fix the following problems by editing the font templates or the gamma value.
The used Screenshot was taken in a game with 1080p and 100% UI-Scale.
![shootergame_2017-11-08_02-32-48](https://user-images.githubusercontent.com/4333206/32644290-e4c949dc-c5e0-11e7-80c7-f8b310788562.jpg)

OCR has very inconsistent match conditions.
Sometimes it accepts to high contrasts and connects multiple characters into one.
<img width="50%" alt="ark smart breeding_2017-11-10_06-13-14" src="https://user-images.githubusercontent.com/4333206/32643936-d2d265da-c5de-11e7-8a55-ee597d68474c.png">
Other times it ignores half of a "y" character.
<img width="50%" alt="2017-11-10_06-26-29" src="https://user-images.githubusercontent.com/4333206/32644181-4e8700a4-c5e0-11e7-9a58-49da578f2307.png">

Also the chosen character isn't always the one with the highest match rate.
<img width="50%" alt="ark smart breeding_2017-11-10_06-21-16" src="https://user-images.githubusercontent.com/4333206/32644033-69da3df4-c5df-11e7-9a12-191718f09482.png"><img width="25%" alt="ark smart breeding_2017-11-10_06-22-09" src="https://user-images.githubusercontent.com/4333206/32644049-8061e626-c5df-11e7-82d8-669999455285.png">
<img width="50%" alt="ark smart breeding_2017-11-10_06-22-49" src="https://user-images.githubusercontent.com/4333206/32644065-993b171c-c5df-11e7-8661-03af40d8ed46.png"><img width="25%" alt="ark smart breeding_2017-11-10_06-23-18" src="https://user-images.githubusercontent.com/4333206/32644074-a7926b4e-c5df-11e7-9ce6-034e9503d513.png">

**Comment by cadon** [comment]
Currently there are no plans to improve the OCR. Using the import exported is recommended.
