### ISSUE TITLE
Breeding Score all red

### ISSUE THREAD

**Issue by theant2222** [cadon/ARKStatsExtractor#533]
Alle Breeding Scores plötzlich red hast du eine Ahnung wo der Fehler liegen kann, Danke nochmals für deine exzellente Arbeit werde nochmals Cafe spenden
lg. Christian
![unbenannt](https://user-images.githubusercontent.com/29675510/32690279-ab3e529c-c6f4-11e7-98ba-97938257f3aa.PNG)

**Comment by cadon** [comment]
Hi, spontan fällt mir kein Grund ein. Hast du versucht das Programm neuzustarten?

**Comment by theant2222** [comment]
ja auch schon neu überschrieben zeigt mir Oxygen und Speed rot an zb sarco

**Comment by theant2222** [comment]
![unbenannt](https://user-images.githubusercontent.com/29675510/32695216-4fc3a582-c755-11e7-817a-5c074fd847ef.PNG)


stimmt das oder neueres habe die letzte Version

**Comment by cadon** [comment]
Kannst du die library hier hochladen? Du kannst alle anderen Tiere außer den Sarcos auch davor rauslöschen (z.B. save as..., dann alle Tiere außer den Sarcos markieren, löschen und dann hochladen).

**Comment by theant2222** [comment]
[christian 1.zip](https://github.com/cadon/ARKStatsExtractor/files/1469632/christian.1.zip)
hoffe das ist die richtige

**Comment by cadon** [comment]
Hi, in der Datei ist als "additional-values"-Datei die values.json angegeben, also schon die Grunddatei. Wahrscheinlich wurde die aus Versehen ausgewählt. Klicke am Besten mal auf File->load additional values... und dann auf Cancel, das sollte den Eintrag entfernen.
Ansonsten hab ich nichts gefunden, bei mir werden die Sarcos auch regelrecht mit Breeding-Scores höher als 0 angezeigt.
