### ISSUE TITLE
Daeodon bug

### ISSUE THREAD

**Issue by B0gdDan** [cadon/ARKStatsExtractor#535]
Don't show how many points spent in food and damage

![daeodon stats bug](https://user-images.githubusercontent.com/33638750/32748297-850205de-c8c4-11e7-80dd-c6ed74c6c5d0.png)

**Comment by cadon** [comment]
Hi, see "common causes" on the right

> 4. Uncheck all Lock-to-Zero-buttons in the stats

**Comment by B0gdDan** [comment]
thanks.
