### ISSUE TITLE
Dino Cooldown Grayed out by default

### ISSUE THREAD

**Issue by Wardjp** [cadon/ARKStatsExtractor#537]
This is only a minor issue, but when manually setting the Female cooldown like we talked recently (through Edit), by default the Cooldown section is grayed out and I cannot go in and edit this value. The only workaround I have found through this is having to go over to the Breeding Plan tab, forcing the 2 hr cooldown, then going back and modifying the cooldown in that edit window.
![image](https://user-images.githubusercontent.com/19726338/32820247-fcd7e334-c992-11e7-9fb8-3619cf4efe26.png)
![image](https://user-images.githubusercontent.com/19726338/32820297-32947e24-c993-11e7-9523-e2982dec0d1f.png)

**Comment by cadon** [comment]
That looks like a bug, can't reproduce it right now as I'm reworking the time-input, I'll consider this when finishing that.

**Comment by Wardjp** [comment]
Interesting, it's been every single time every single dino I take into edit mode. However, definitely focus on your work first, with a workaround, it's nothing more than a minor annoyance.

**Comment by cadon** [comment]
Hi, I just released a new version. Are these inputs still greyed out?
Suggestions on how to improve these inputs are welcome, they still feel a bit clumsy.

**Comment by Wardjp** [comment]
Negative, they are no longer grayed out by default now. It does look a little clunky, but the functionality is there. I'd say to mark it as something personal to come back and polish in the future if you'd like and have the spare. Otherwise it's functional and that's what matters :)
