### ISSUE TITLE
Troodon and Tapejara Not Extracting. Both Tamed and Bread

### ISSUE THREAD

**Issue by Jebula999** [cadon/ARKStatsExtractor#538]
Hey There,

Been using this tool for about a year now i think, and so far been running smoothly.

Came back to ARK and decided to get into breeding again. The tool has been working perfectly for Rex's and Allo's, but now i see some dino's aren't extracting.

I have included 2 screenshots.

Hope you can help
![tape error](https://user-images.githubusercontent.com/11380895/32972817-f2c12eca-cbfc-11e7-905a-d33db5df0d92.png)
![troodon error](https://user-images.githubusercontent.com/11380895/32972818-f383b558-cbfc-11e7-8fa9-3b7feb0e2505.png)

**Comment by cadon** [comment]
Hi, there was an issue with the Troodon-food, it should be fixed in the latest release.
For the Tapejara, it's probably the issue displayed in the bottom left. Try to extract it after some days, maybe it works then.
