### ISSUE TITLE
Pegomastax Not Extracting

### ISSUE THREAD

**Issue by blakewarren** [cadon/ARKStatsExtractor#539]
Having issues extracting for a newly tamed pegomastax on my SP game. Have included the screenshots. I have only put 2 points into health on the screens shown but wouldn't extract when newly tamed with health of 144.3 either.
![20171118205703_1](https://user-images.githubusercontent.com/32726658/32979831-f4a26078-cca7-11e7-923d-05a8684fad3f.jpg)
![2017-11-18 2](https://user-images.githubusercontent.com/32726658/32979833-f4ecb1aa-cca7-11e7-8d96-f35357f966e3.png)

**Comment by cadon** [comment]
Hi, check the checkbox "Singleplayer-Settings" in the settings of the tool.

**Comment by blakewarren** [comment]
Yeah I had already done that.
