### ISSUE TITLE
Player names and tribes

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#54]
I am at a stage where I am constantly entering a players name, would be great if there was an option to have a tribe manager and player manager that could keep a track of players.

Then I could just do a drop down or enter the players name when adding a Dino to a library.

**Comment by cadon** [comment]
Hi,
you mean something like a library for players with notes for the players and tribes? I'll think about it.

To set a property to multiple creatures at once, you can select them in the library (hold the Ctrl-key), then right-click and choose "Edit all selected...". In the appearing window you can enter an owner-name that is assigned to all the creatures.
I'll add an autocomplete-function for the owner-field in the next version, that should make it easier, too.

**Comment by cyberangel67** [comment]
An auto complete would be good to, but would be good if you did add it.
