### ISSUE TITLE
Not an issue as Such. Separating out Bloodline

### ISSUE THREAD

**Issue by Dryadia** [cadon/ARKStatsExtractor#540]
Sorry if this isn't the place to ask, but is there a way of getting the breeding plan to only pick from a certain group of dinos within a species, say a non mutated bloodline?  Thanks.

**Comment by cadon** [comment]
it's on the todo-list, not yet implemented. Do you have ideas what other criteria could be useful, beside choosing only non-mutated creatures?

**Comment by Wardjp** [comment]
Sorry if the idea isn't relevant, but allowing us to tie some sort of ID to a mutation, maybe it could be automatically assigned in the backend whenever you tick the mutation (though would probably need to split mutations into matri/patri for this), so it can know when a mutation getting passed down is the same mutation getting duplicated or if it's a new mutation.

**Comment by Dryadia** [comment]
Would it be possible to allow users to make their own groupings within an species?  Maybe by limiting the number of total subgroups allowed. I'm breeding for specific non mutation colours as well as stats. I'd like to be able to have an individual dino part of different groups at the same time, eg: part of the pure line but also part of the all black and silver/black mix group. Tick boxes on dino detail page so you can add or  take off dinos from the different groups.

**Comment by cadon** [comment]
The latest release supports tags which can be used to show breeding-plans only for certain groups.

**Comment by Dryadia** [comment]
Perfect. Thank you.
