### ISSUE TITLE
Fix Problem with [Tag]

### ISSUE THREAD

**Issue by tuvok81** [cadon/ARKStatsExtractor#541]
Hello,
we use Name Tags some [ ] is this possible and can you fix this Problem? and the Tool can better Read the Animal Name? this was very nice .. 

![2017-11-24 13_41_52-ark_ survival evolved](https://user-images.githubusercontent.com/30367063/33211186-a84a4b6c-d11d-11e7-85ab-825e8bcdd247.png)

**Comment by tuvok81** [comment]
Here the same
![2017-11-24 13_58_29-ark smart breeding - dav xml](https://user-images.githubusercontent.com/30367063/33211620-a9e989ae-d11f-11e7-97da-eef14a20c6f5.png)
![2017-11-24 13_58_37-ark_ survival evolved](https://user-images.githubusercontent.com/30367063/33211622-aa07865c-d11f-11e7-8258-cd1d1f0c3df4.png)

**Comment by cadon** [comment]
Hi, the OCR sometimes is just not very good. For long creature-names, the game decreases the size of the font, so the OCR cannot recognize the letters correctly. OCR is complex and it's only a help to make the typing easier. I'll tag this issue with enhancement, but no promise there will be improvements for that feature.

**Comment by tuvok81** [comment]
OK ...

**Comment by Wardjp** [comment]
You can go in and modify the name yourself ;) OCR almost always incorrectly reads our owner and tribe name, two seconds to correct it.

**Comment by cadon** [comment]
If the issue is mostly in the Owner- and Tribe-input, you can set it to locked, so the OCR won't modify the text in it. To do so, right-click on the label "Owner" or "Tribe" in the creature-info input.

**Comment by Wardjp** [comment]
Omg, I never noticed this, tym :)
