### ISSUE TITLE
Entrys are OK but are RED the Tool will not read correct

### ISSUE THREAD

**Issue by tuvok81** [cadon/ARKStatsExtractor#542]
Hey, what make i wrong? 

![2017-11-24 13_50_56-ark smart breeding - dav xml _](https://user-images.githubusercontent.com/30367063/33211469-f5f9382c-d11e-11e7-90e1-f82892f40bbe.png)
![2017-11-24 13_50_36-ark smart breeding - dav xml _](https://user-images.githubusercontent.com/30367063/33211470-f616d0da-d11e-11e7-8982-d80f4b3bda3b.png)

**Comment by cadon** [comment]
Hi, in food you have checked the lock, despite having spent a level in food. Uncheck the lock (make it green), it should work then.
For the damage, you have maybe to select another combination (the stat is yellow, that means the tool found multiple possible combinations).
