### ISSUE TITLE
Dino stats not working 

### ISSUE THREAD

**Issue by Nois3y** [cadon/ARKStatsExtractor#544]
I play on official and the only common multipliers are 2x breeding, mating, maturation, xp, and gathering otherwise it's 1x. 

I am trying to extract a bred rex's stats and cannot get it to work. Never had this issue before.
![20171125180423_1](https://user-images.githubusercontent.com/33976582/33228524-84a5e6f8-d20d-11e7-8e4a-23eb2efff08f.jpg)
![20171125180432_1](https://user-images.githubusercontent.com/33976582/33228525-87102f7a-d20d-11e7-8212-721bb57343d0.jpg)
![97c04c689b1443fa8ad9700631426d00](https://user-images.githubusercontent.com/33976582/33228527-a2e63122-d20d-11e7-954c-34f9a8153592.png)
![80cf115812228bb3495a3a2622afadd0](https://user-images.githubusercontent.com/33976582/33228529-a70edb82-d20d-11e7-920d-9e144b2c1c91.png)

Any ideas?

**Comment by cadon** [comment]
Hi, if you raised the rex partly during an event and partly outside the event, it's probably not possible to extract the data. It's best to extract the stats right after hatching, before the first imprinting. The imprinting value can be set later manually in the tool.
Sometimes imprinting isn't updated in the game directly and it works if you try to extract a creature after some days.

**Comment by cadon** [comment]
It works with the newest version with the "Partly Event" checkbox enabled (under the imprinting-input).
