### ISSUE TITLE
Timer issues after update.

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#545]
It seems as if final duration is picked up from "finish time", ignoring "set timer to end in" group - "finish time" is not getting updated by +x buttons.

No matter what time I set, all timers was adding in already finished state.
https://i.gyazo.com/ca6361d712f36d8dc863720caaacd386.png

**Comment by cadon** [comment]
fix is released.

**Comment by cadon** [comment]
Just realized, if you click on the "now"-button, it will only update the actual finish-time if the timer is on 0, so you have to click this button twice. This will be fixed in the next release.
