### ISSUE TITLE
Classic Flyers not adding levels to MS.

### ISSUE THREAD

**Issue by dvldogherzog** [cadon/ARKStatsExtractor#546]
![sab issue](https://user-images.githubusercontent.com/34027774/33265359-b89ac098-d3b4-11e7-9086-4ee337344e2b.jpg)

In the left image I have only leveled the Ptera twice since tamed. Once in Melee and once in movement speed and this was an attempt to fix the issue. I have no experience dealing with programs like this so I am completely lost on fixing it. Please help.

**Comment by cadon** [comment]
Hi, do you have other creatures (non-flyers) that worked? Maybe there are other server-settings you need to adjust?

**Comment by dvldogherzog** [comment]
I couldn’t get any others to work either. I think the problem does lie with the server settings, I just have no easy way of getting the settings I need. It’s a japanese unofficial server, and I don’t speak japanese.

**Comment by cadon** [comment]
Then it's probably custom stat-multipliers. Maybe you can ask in English?

**Comment by dvldogherzog** [comment]
Okay, I will see what I can get from them and post any updates if it solves it or if further issues. Thanks
