### ISSUE TITLE
Need workaround for game bug?

### ISSUE THREAD

**Issue by NeilaNuruodo** [cadon/ARKStatsExtractor#547]
I somehow got 101% imprinting on a baby dino.  Not your fault, but it seems Ark Smart Breeding doesn't know what to do with this.  If it's a common thing, might be worth allowing some kind of override for a tad over 100.  Not a big deal for me but thought you might like to know.

http://prntscr.com/hfzc3w

**Comment by cadon** [comment]
Hi, this was reported by another user as well, but they're using S+ with a "Nanny", which helps in raising creatures. Do you also use mods or is this now common in the vanilla game?
