### ISSUE TITLE
Feature request. Ability to turn of automatic species identification

### ISSUE THREAD

**Issue by wmrojer** [cadon/ARKStatsExtractor#548]
From what I understand the program automatically tries to identify what species it is reading the values for when reading the values from ARK. But unfortunately it often fails. Especially it confuses Rexes for Yutyrannus and vise versa. 

Would it be possible to and a setting in options to turn off this feature. It's annoying when you are reading stats for a lot of newly born baby rexes to often have to change it back.

**Comment by cadon** [comment]
feature is released.
