### ISSUE TITLE
Wyvern weights seem to be inaccurate

### ISSUE THREAD

**Issue by dcuoperv** [cadon/ARKStatsExtractor#549]
Have never been able to extract fire wyverns. I have no weight multipliers on my server, however the weight is always incorrect.

This is on a server with Classic flyers, and I do use the classicflyers.json

![actualwyvern](https://user-images.githubusercontent.com/29808722/33382063-73e82464-d56b-11e7-98b4-7ca548a0b1f8.JPG)

That's the actual wyvern in question. To get it into ASB, I used the ark-tools java, and extracted the actual values (and used a little bit of php trickery to make it somewhat readable.

![pullfromsave](https://user-images.githubusercontent.com/29808722/33382118-95d7c85e-d56b-11e7-94c7-4604aa7845be.JPG)

As you can see... from the first lot of H, S, etc etc numbers we have...
Health: 31
Stam: 54
Oxy: 37
Food: 29
Weight: 59
Dmg: 53 (with 1 point added)
Speed: 0

This is confirmed in game with super spyglass here

![superspyglass](https://user-images.githubusercontent.com/29808722/33382249-f25cef0a-d56b-11e7-972d-5c80619e4c4f.JPG)

However, in ASB... the weight reads differently.

![asb-results](https://user-images.githubusercontent.com/29808722/33382272-09736958-d56c-11e7-880d-b2588cc5f1e0.JPG)

This is my ASB settings, which was created by dropping game.ini onto the settings window.

![asb-settings](https://user-images.githubusercontent.com/29808722/33382355-3ff2840a-d56c-11e7-8503-fa6c73d42b3e.JPG)

Thoughts, suggestions? Am I doing something wrong here?

**Comment by MarkMoss** [comment]
I'm also trying to troubleshoot an issue with extracting Classic Flyer wyvern weights. My observation is that Classic Flier wyverns gain 7 units per level in weight vs. 8 units per level in weight for vanilla wyverns.

My guess (and only a guess), is that Classic Flyers uses the pre-256.3 (PC version) base weight of 350 units vs. the version 256.3 base weight of 400 units.

**Comment by MarkMoss** [comment]
I've been able to "fix" the issue by changing classicFlyers.json to give fire, lightning, and poison wyverns a base weight of 350 units.  I hesitate to put this into a pull request, as 1.) I don't entirely understand the structure of the data, and 2.) I don't know if 350 is the correct value, or if this is working around a temporary bug in the Classic Flyers mod.

[classicFlyers-MGH.json.txt](https://github.com/cadon/ARKStatsExtractor/files/1593918/classicFlyers-MGH.json.txt)

**Comment by dcuoperv** [comment]
Thanks Mark, that fixed the issue for me. I tried playing in that file, but it did my head in haha. That has indeed fixed it for me also.

**Comment by cadon** [comment]
@MarkMoss thanks for the fix, I'll include this in the next release.
