### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by tstrough92** [cadon/ARKStatsExtractor#55]
Is there going to be an update to allow for extracting 150 Dinos because when I use the extractor on the new map, they say that they don't work with the 150

**Comment by cadon** [comment]
Hi, did you adjust the max wild-level to 150 in the settings? The next version has this as default.

**Comment by tstrough92** [comment]
That I have not I didn't know there was a spit for it

**Comment by cadon** [comment]
I'm closing this issue for now. If the extracting was not solved by changing the settings, reopen it.
