### ISSUE TITLE
Bug: Grown In not saved when changing Current Weight when creating new breed dino.

### ISSUE THREAD

**Issue by wmrojer** [cadon/ARKStatsExtractor#551]
If you change "Current Weight" after doing a "Read Valued" from ark for a Breed dino it will change the values in the field for "Grown In". But when you hit "Add new to Library" those values in "Grown In" will not get saved. You need to manually enter a value in the fields for "Grown In" for them to get saved.

If you have a dino with "Grown In" time saved and edit it in "Stat Testing", the "Grown In" time will reset to 0 unless you manually edit one of it's fields.

**Comment by cadon** [comment]
Fix is released with 0.24.2
