### ISSUE TITLE
Question: Sort order for Male and Female parents?

### ISSUE THREAD

**Issue by wmrojer** [cadon/ARKStatsExtractor#552]
What sets the sorting order for the drop down menus for the Mother and Father in the Extractor?
Is there a way to change it? 
Preferably I would like it to be the highest matching number of stats at the top. And maybe have an option to not show dead or unavailable dinos.
This really only gets a problem when you have very large number of dinos. I currently have 124 Therizes in Smart Breeder.

**Comment by cadon** [comment]
Hi, currently the parents are first sorted alphabetically according their name. Then all creatures that are not available (i.e. unavailable or dead) are put to the end of the list. Then all creatures that have zero common stats are put to the end. So first in the list are available creatures that have at least one common stat, then all unavailables, then all creatures with no common stat. Usually a parent is found in the first group.

Sorting the creatures according to their highest matching stats would probably mostly show the siblings first, then the parents, so I left that part of the list sorted alphabetically.

**Comment by wmrojer** [comment]
Thank you
