### ISSUE TITLE
Tapejara stats not extracting?

### ISSUE THREAD

**Issue by IAMEON** [cadon/ARKStatsExtractor#553]
Hi! I'm new to this program and its awesome! But I've found that my tappys stats wont extract, I know I have several levels into speed and health, but im not sure why they were all distributed into stam? I know for sure this one was a 145 tame.
![capture](https://user-images.githubusercontent.com/34173624/33505714-57816344-d6a1-11e7-926c-3aa121157ccf.PNG)

**Comment by cadon** [comment]
Hi, I assume you're using the mod classic flyers? Probably there was a change with the values for speed and the values have to be updated. I'll look into this.

**Comment by cadon** [comment]
It works with the latest version.
