### ISSUE TITLE
Troodon food-stat bugged

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#554]
Breeding troodons. Parents are tamed. Mom has food 32, dad - 10, child - 24(0% imprinting, bred during 2x). Child has 1 mutation on mom side. Guess it wasn't food since it should have been 34 if it was.
Hate to break their family apart, but it is definitely not dad's food stat!

Sorry to waste your time if this is just a typo on my side, but I can't catch it.

Ignore child's "wrong" gender - had triplets, 2 others died with meat still inside inventory.
https://i.gyazo.com/49a4cc20a4f0f1ac41a2599e3b54a7dd.jpg

ASB v0.24.1

**Comment by cadon** [comment]
Hi, the food-stat of Troodons is bugged currently. The base value was 100 (with a wild-increase of 10 per level) and was changed to 200 (with an increase of 20 per wild-level) a couple of months ago. Strangely, the game still things the increase is 10 per level, but it uses the 200 as a base. But not always, sometimes it's using 20 as increment. In the last release I changed the increase to 10 (with a base of 200), thinking the game does use this consequently, but that's not true. So Troodons are currently not able to be extracted in some cases and / or show wrong levels for food (and speed, which is dependant on the not used levels).

There was a similar bug with the HP of scorpions (and some other species like the roo and ovis), when their base-value of health was changed in fall 2015. This bug lasted at least 1 year, I'm still not sure if it is completely resolved. So it might be that Troodons cannot be extracted by this tool for some time.

To resolve this, I could add another entry for Troodons with the other food-increase, but then you'd have to know if this Troodon uses the old or the new value, which would be plain guessing in most cases.

**Comment by deedoubleu** [comment]
Would it be possible to guess what value is in use by checking baby stat against parents?

For example, in my case it is clear that baby has impossible stat. Wonder if it will work for others or there are too many possible combinations where wrong stat will look right?

If it can't be automated then I don't think there is need for another entry. We'll have to wait for a game to be fixed.

**Comment by cadon** [comment]
If you know the parents and haven't yet leveled up or imprinted a creature, you could add it with the Testing-tab. Just increase the wild-levels until the stat-value matches the value ingame. For the food, there could be discrepancies, depending on what increase the game is currently using.
