### ISSUE TITLE
server as new field for creatures

### ISSUE THREAD

**Issue by Vykan** [cadon/ARKStatsExtractor#555]
Hello, I use your software and find it very interesting.
However, I miss one detail sometimes, I play on several servers and my dinos are scattered on all these servers, I can not always remember where to go when I need this or that dino.
Could you add to the data entered a field in which it would be possible to inform the server?
A combo box with the list of attended servers would be ideal.

Thank you for your work.

**Comment by audiopathik** [comment]
You can save your library in a file for each server seperately and load them as you need them.

Just go to File>Save as... and save the current Creature Library and Server Settings in a Creature Collection File (*.xml) and the next time you play on that server you can load that Creature Collection and Server Settings again with File>Load
