### ISSUE TITLE
Failed Stat Extraction for Any Generation 1 Bred Dinos on Unofficial Server

### ISSUE THREAD

**Issue by CriticalGravitasFailure** [cadon/ARKStatsExtractor#557]
Love the application, even got the admin to send me the .ini file to properly configure the settings.
Although everything seems fine, any stat extraction for the first generation of bred dinos fails spectacularly. Take for example this bred iguanodon: (https://i.imgur.com/dhdorCt.png)
And then the resulting stat extraction: https://i.imgur.com/Hi4AxU0.png 
Server Settings: https://i.imgur.com/viEsxKK.png

Now I know the server has been restarted several times since all of our bred dino completed maturation and imprinting, yet stat extraction still fails even with a manual stat entry after leveling a stat up to force the game to recalculate.

**Comment by cadon** [comment]
There seems to be a change in the cuddle-interval calculation. Someone reported that doubling the cuddle-interval-value in ASB made it work. I'll check this to find a fix.

**Comment by CriticalGravitasFailure** [comment]
I tried tweaking the CuddleInterval to both double and half of standard, and still had extraction failure D:

**Comment by cadon** [comment]
Hi, sorry for the late reply. The imprinting extraction should be fixed finally. The iguanodon still doesn't work, I guess some stat-multipliers are still not correct. At least the wildLevel for Torpor or the babyImprintingStatScaleMultiplier.

**Comment by cadon** [comment]
It works with `BabyImprintingStatScaleMultiplier` = 6.
