### ISSUE TITLE
Aberration Aberrant species

### ISSUE THREAD

**Issue by Zhinjio** [cadon/ARKStatsExtractor#558]
Can't seem to get extractor to work. I think maybe the aberrant variants tweaked health some. I've tried all the usual stuff to get them to import. Any thoughts, or just wait until we get more data to get the json files where they need to be for the aberrant variants? Anything I can do to help?

**Comment by reeah666** [comment]
Having the same issue! Aberrant variants do seem to have different health values. I tested it with a spino, normal ones have a base HP of 700 and aberrant 672. I don't know if the HP is lower across the board or tweaked in different amounts for different creatures

**Comment by cadon** [comment]
Hi, there are separate entries for each Aberrant-variant in the game-files, but the only thing that is different is the name. All stat-values are exactly the same. It may be that there is a new multiplier that only affects the aberrant-variants, I have to check this further.

**Comment by Zhinjio** [comment]
Let's hope its just a slight tweak and we can have a checkbox for abberant variants or something, instead of having to add all new entries into the json.

**Comment by Zhinjio** [comment]
Is there anything I can do to help gather data?

**Comment by Tecknosa** [comment]
i just updated to 24.2 and still cant see the aberrant versions or the ravager at all

**Comment by cadon** [comment]
@Tecknosa The ravager should work, if you download the latest values.json. Click on the menu ? -> Check for Updates to get the newest file (it's not included in the latest release, has to be updated from within the tool).

@Zhinjio I probably have all the data, just have to find a good way to implement it. Do you know if the aberrant-variants can be bred with the vanilla-creatures, e.g. aberrant-Spino with vanilla-Spino?

**Comment by Zhinjio** [comment]
Is it even possible to have cross-server transfers into Aberration? I haven't seen vanilla variants on the Aberration server, only Aberrant versions. Anyway, I can't test that, but I suspect they can't be cross-bred. That would make the breeding planning a complete hot mess.

**Comment by Zhinjio** [comment]
I suppose if it is possible to move dinos over, it would be interesting to see if it moves over and "becomes" an abberant variant, and suffers whatever tweak penalty there is to stats as a result. But I haven't seen a terminal to do moves from, so I can't test that either.

**Comment by Tecknosa** [comment]
tried to update from within and got 'an exception occured to a webclient request' or something very close

**Comment by Tecknosa** [comment]
it isnt possible to move dinos yet however i have been able to move fert eggs and hatch and they remain nilla versions

**Comment by Zhinjio** [comment]
Ah nice! Can you try breeding a vanilla and aberrant?

**Comment by GrantTV101** [comment]
I hope this helps https://twitter.com/bubblywums/status/941202783830757376
This is why everyone is having trouble with Variants, seems re-calculations are gonna have to be made :/

**Comment by cadon** [comment]
The latest version 0.24.3 has entries for the aberrant variant species.

**Comment by Zhinjio** [comment]
Seems to be working now. Thanks!
