### ISSUE TITLE
Imprinting gain changed, imprinted creatures cannot be extracted

### ISSUE THREAD

**Issue by ijabit** [cadon/ARKStatsExtractor#559]
![image](https://user-images.githubusercontent.com/557752/34045770-62c07222-e178-11e7-9c83-b554e7d28eeb.png)

**Comment by Jobsti** [comment]
Same here, think it's because 275:
- Imprinting intervals increased from 4hrs to 8hrs between each imprint. Each imprint gives a large amount of imprint bonus per imprinting. Will also scale with the servers mature rate.

**Comment by cadon** [comment]
Hi, I guess that giganotosaur was raised partly during an event. If you use 39.91691 % for the imprinting and check "Exactly, don't adjust", it will extract all stats except HP. It also could be that the HP-stat somehow uses the old raising-gain. Maybe it will work now, as the values should be updated in the meantime, if that was the issue.

**Comment by cadon** [comment]
I recommend to level up HP once and try it again. Probably the values didn't show the correct values in your first screenshot. I'm closing this issue for now, if the issue persists, consider to reopen.
