### ISSUE TITLE
Unable to add Bronto to Library - Red stats

### ISSUE THREAD

**Issue by Ranensol** [cadon/ARKStatsExtractor#56]
Hi there, absolutely love the program, but having issues getting Bronto's to verify so they can be added to the library.
I've got 3, but I'll only include the latest one here as I can tell you without a doubt what the stats were after taming, and it's been done since I changed the weight multiplier for dinos per wild and tamed level to 2 (the only modifier I have on our server (I'm the admin)).
The Bronto was tamed at lvl 161 and the Health/Weight/Torpor were all red. I've tried all the combinations of check boxes, and I've set the multiplier for weight in the app correctly.
I've attached screenshots of how she looked post tame, how she looked 6 levels later (all points put in speed as she was half way across the map from our base...), the attempted scan with the app (love the OCR btw), the server settings in case I missed something, and the app settings in case I've missed something there.
I'm a C# developer myself, not sure whether that's actually relevant, but I have a debug environment here I can fire up if that helps in any way, but either way please let me know if you need any more info/examples etc.
Cheers

![161 bronto - brunnhilde fresh tame](https://cloud.githubusercontent.com/assets/19820373/15896463/60e8e8e4-2d88-11e6-9e6b-ade1fb8a6468.jpg)
![167 bronto - brunnhilde 6 levels domestic all speed](https://cloud.githubusercontent.com/assets/19820373/15896456/5bd56d14-2d88-11e6-93fa-15cd613c370e.jpg)
[Game.ini.txt](https://github.com/cadon/ARKStatsExtractor/files/304907/Game.ini.txt)
[GameUserSettings.ini.txt](https://github.com/cadon/ARKStatsExtractor/files/304908/GameUserSettings.ini.txt)
![breeding app settings](https://cloud.githubusercontent.com/assets/19820373/15896457/5be30adc-2d88-11e6-87d8-b0685c08a3dd.jpg)

**Comment by Ranensol** [comment]
Oh and it's on an unofficial server I own/run, with max wild dino level 120/difficulty 1.0, just in case that wasn't clear!

**Comment by cadon** [comment]
Hi,
thanks for the report. The base-stats of the bronto were changed, I updated the stats-file. You can get it by clicking on ? -> Check for Updates. With the updated stats I was able to extract the levels of that bronto successfully.

**Comment by Ranensol** [comment]
Top man, all 3 scan in perfectly now, thanks very much!
