### ISSUE TITLE
Stat Extraction Fail

### ISSUE THREAD

**Issue by LeviJunia** [cadon/ARKStatsExtractor#560]
Fire Wyvern Stats
![image](https://user-images.githubusercontent.com/34610954/34075027-f614586c-e30e-11e7-9933-fe2ed2ebb460.png)

Dimorphodon Stats
![image](https://user-images.githubusercontent.com/34610954/34075018-c86d7178-e30e-11e7-9893-29c0daa80b5b.png)

Settings on Unofficial Server
![image](https://user-images.githubusercontent.com/34610954/34075008-8472b4ec-e30e-11e7-84c6-066386072c52.png)

The old classic, usually only a problem with Bred dinos of all makes. All 100% exact imprints, and I've had the server admin send me the unofficial server settings as well.

**Comment by Jobsti** [comment]
Same here.

**Comment by cadon** [comment]
Hi @LeviJunia, it seems some stat-multipliers are not correct, at least the wildLevel torpidity and/or the BabyImprintingStatScaleMultiplier. Try to get these values from the server-admin.

**Comment by cadon** [comment]
The BabyImprintingStatScaleMultiplier seems to be 1.25.
