### ISSUE TITLE
Megalosaurus (Aberration) Stat extraction fail

### ISSUE THREAD

**Issue by NovaMagic** [cadon/ARKStatsExtractor#561]
Playing on official aberration server

![image](https://user-images.githubusercontent.com/32695714/34224519-22c50d5a-e591-11e7-8e0a-e972e96646ce.png)

**Comment by cadon** [comment]
It should work now with the latest version 0.24.3.

**Comment by Force17** [comment]
I have the same problem with my Stegos and i have the version 0.24.3.
.

**Comment by cadon** [comment]
There was another issue with the HP for aberrant variants. It's fixed in 0.24.4.
