### ISSUE TITLE
Ravager Aberration glitch

### ISSUE THREAD

**Issue by DXgamergeek** [cadon/ARKStatsExtractor#566]
Hey there.  Just been working on trying to create my new libraries for the new Aberration creatures.  I keep running into the error where no matter what I try, based on your issue guide page, I cannot get the extractor to pull the Food and Damage levels.  They stay red and give no point breakdown.  I'm on Official, creature is right, and all stats/lvl/etc is correct.  Thanks for any help.  I know it is new and will have glitches.  :)

**Comment by smw** [comment]
Same issue.  Thanks for reporting!

**Comment by cadon** [comment]
Hi, can you post a screenshot of the inventory of the creature and your server-settings, if not on official?
Imprinted creatures currently won't work due to a change in the imprinting-gain, I will work on this in january.

**Comment by cadon** [comment]
Closed being inactive.
