### ISSUE TITLE
Rock drake, Aberrant variants not able to add health issue

### ISSUE THREAD

**Issue by Demakrow** [cadon/ARKStatsExtractor#567]
When imprinting rock drakes they do not get 20 extra movement speed. i have to manually add 20% more manually to be able to add it in.
All aberrant variants of dinos(Spinos, megalosaurus, ankylo, doedi etc) It's unable to get the health.

**Comment by cadon** [comment]
Hi, I will look for the speed on Rock Drakes in january.
For the aberrant variants, do you use the latest release of the tool and have choosen the "Aberrant Spino" etc. in the species-selector?

**Comment by cadon** [comment]
aberrant-HP issue and the rock drake speed are fixed now (0.24.2)
