### ISSUE TITLE
Dragging and dropping of .ini files not work?

### ISSUE THREAD

**Issue by Arendarr** [cadon/ARKStatsExtractor#569]
when I try to drag a file over the settings window, it just gives the not allowed or "ghostbusters" symbol.

**Comment by cadon** [comment]
Hi, maybe it's a security setting from windows or a virus-scanner that prevents that? Currently I have no idea why that could happen.

**Comment by Flachdachs** [comment]
Usually happens when the program is run as administrator, then you can't dragdrop to it as a non-admin, e.g. from Windows Explorer run as normal user.
