### ISSUE TITLE
Contribution: Reading creature collection from ARKTools

### ISSUE THREAD

**Issue by coldino** [cadon/ARKStatsExtractor#570]
I've just made a first stab at allowing your entire creature collection to be imported from a saved ARK (after ARKTools has extracted the data from it). Hope for some feedback before continuing. The commit is 0444052e8ca210342145489368440d60254f223f.

Features:
- Imports all the useful values including stats, colours and ancestry.
- ARKTools must be run first externally.
- Cleanly handles duplicates when re-importing from ARKTools.
- Does not handle duplicates with pre-existing creatures in your collection - these must be resolved manually.
- Mutations are not present in ARKTools output so are not handled.

It works, but I haven't used it in anger yet. I'm a bit worried that I missed updating something in your kinda spaghetti code once the creatures are created. I'm hoping you'll check it over and see what's what. I'm particularly worried about bred creatures parent's that have subsequently 'died', leaving one or both parents non-existent.

To test:
1. Extract [ARKTools](https://github.com/Qowyn/ark-tools/releases).
2. Run `ark-tools.exe -p --pretty-printing tamed <ark-path> <empty-output-dir> --write-all-fields --clean`
3. With an empty collection File->Import From ARKTools... and point at the output directory.
4. Library should now contain all tamed creatures.

**Comment by cadon** [comment]
Hi, sounds great and useful! I'll have a look at this in the next days.

**Comment by coldino** [comment]
After using this a fair bit I've added some updates to my branch, and also merged in your latest. It's working really well and saving time when taming and doing lots of breeding.

What are your thoughts on creating 'placeholder' creatures to complete an ancestry line? The name and unique ID of each ancestor are available, but if the creature is already dead and was never in the collection then as far as this app is concerned the ancestry line finishes there. I could make placeholders for these creatures but they would be stat-less, and I'm not sure what issues that might cause.

I have a (mapping) tool [Larkator](https://github.com/coldino/Larkator) that automatically converts the saved ARK whenever it detects changes, but I'm toying with the idea of moving that functionality into Smart Breeder along with auto-importing. There would be an impact on settings and re-use of the current file watcher, but I'm unsure if it fits the project. Comments?

**Comment by cadon** [comment]
Hi, sorry for the late reply. Currently I'm working on the extraction of imprinted creatures and haven't found time for this merge. I hope this week.
Good idea regarding the placeholder-creatures!
For now I think a separate tool is better for maps, I'm not completely sure yet. Maybe it's better if it keeps on it own, so you can update it easier. It sounds like a nice addition for breeders to find good creatures.

**Comment by coldino** [comment]
No rush. It's looking pretty solid at the moment so I've also been extending it to handle some of my own additions to ark-tools: mutation counters and knowing when creatures are dead, but it'll work just fine with the vanilla version.
Placeholder creatures are next on my list but I have a strong feeling they'll require many workarounds in the rest of the code. I'll keep that work in a different branch for now.

**Comment by coldino** [comment]
Creating placeholder creatures for dead ancestors seems to have gone quite smoothly and is contained well to just the files you would expect (e708788732aff06bf6a698dd5a70042c0018a11c). It's limited to creating placeholders for immediate parents as doing more would have required a significant re-organisation, but this is still useful as all creatures at least have named parents.

I'm happy with the state of this now. I'll bring it all together and create the pull request so you can check it more easily.
