### ISSUE TITLE
Can't seem to get the program to work with any breeds or tames on Aberration! 

### ISSUE THREAD

**Issue by Alliyanna** [cadon/ARKStatsExtractor#571]
Hai! 

Been using your program for our past two servers without issues and love it! Trying to get it to work on Aberration now, for days.. Failing. 

The dino in the ss is a bred Ankylo, I haven't given this specific one any levels as that sometimes screwed it over on the previous servers - but I did try and give another bred Ankylo levels to see if it'd help (it didn't).

I have admin on the server, so the stats are correct, triple checked and the server has been rebooted as well. 

![anky1](https://user-images.githubusercontent.com/35003500/34469567-4e84742c-ef22-11e7-8667-afe65d927586.jpg)

![anky2](https://user-images.githubusercontent.com/35003500/34469562-1e9c5784-ef22-11e7-85ed-214d2a25ceca.png)

edit: I realised the program had a recent update and I hadn't opened the right one. This is still an issue. I hope I'm doing something wrong :(
edit edit: updated anky2 ss to include ini files

**Comment by cadon** [comment]
Hi, the imprinting-gain was changed recently, the new values are not yet in the tool, so imprinted creatures don't work right now. Until this get fixed I recommend to extract the creatures before you start imprinting.

**Comment by Alliyanna** [comment]
Hi Caden, 

Thanks for the response. I've tried to import two Anky's that I haven't imprinted. They are fully grown, so I'm not sure that could now be screwing it up - but they show the exact same "stat values" in the program. In ARK they don't share stam/torpor but everything else is the same. (same dad, different mum).

I don't understand why they show the exact same values though? Something should be different, no?

(tried the same with doed's before, 5 doeds, all same stats - but I don't have ss's of that as I thought the program was just bugged.

https://puu.sh/yUgku/1f1e31cd1f.png - Stat values
https://puu.sh/yUglb/6bb67a37e9.png - [171]F program
https://puu.sh/yUgnQ/ea639d5c28.png - [180]M program
https://puu.sh/yUghb/1536bd9f12.jpg - [171]F game
https://puu.sh/yUggG/f0c3dfcf94.jpg - [180]M game

Thanks again :)
