### ISSUE TITLE
Virus detections.

### ISSUE THREAD

**Issue by Samsemilia1** [cadon/ARKStatsExtractor#572]
My Kaspersky, WindowsDefender and Emisofts Anti-malware detect the download and the execution of the exe as a virus. Any infos about this ?

**Comment by coldino** [comment]
My **personal** thoughts on this:
1) Are you sure you have a legit copy of this downloaded directly from GitHub? I've just double-checked Windows Defender does not trigger for me after forcing an update and checking the two most recently released versions.
2) Your malware checkers could be triggering based on the OCR screen grabbing ability. It's up to you if you accept this behaviour but it's no more than any screen clipping software. The source code is open and looks safe to me.

**Comment by cadon** [comment]
Hi, this happened some months ago with a couple of versions as well. I guess some code looks suspicious to some scanners, maybe the function that downloads the newest values-file or the screenshot-function as coldino pointed out. I can assure you that the tool has no malicious code, but of course you should never trust a stranger on the internet. In the past, the virus-detectors just stopped to flag the tool after a while, I recommend to wait for a newer release of ASB, maybe the scanners accept that better.
