### ISSUE TITLE
Ignore sex in breeding planner suggestions (S+)

### ISSUE THREAD

**Issue by Senzir** [cadon/ARKStatsExtractor#573]
Hey the calculation of lvl ups for Bulbdogs at Range/Meele Dmg isnt correct.
I have an base stat of 457% and its said these are 55 lvl ups but right would be 71 lvl ups

**Comment by cadon** [comment]
Why do you think it's wrong? Probably you checked it with a wild-stat calculator before, at least that's exactly the number you'd get if you assume a wild creature. Also see https://github.com/cadon/ARKStatsExtractor/wiki/FAQ#why-does-the-tool-extract-a-too-low-level-of-the-melee-damage

**Comment by Senzir** [comment]
Hey didnt know that with  the Boost, how Big ist this Boost? Also ich wanted to if  u could implemant something Like the s+ mutator. Its a Common mod and ist Change the way how to breed in such a Big way. Just like the Option to Convert all Not needed male temporaly to females give so mich extra ways to get a breeding started.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.

**Comment by cadon** [comment]
Does this mod allow to change the sex of any creature, i.e. any male could become a female temporarily and vice versa?

**Comment by cadon** [comment]
A setting to ignore the sex in the breeding planner is implemented.
