### ISSUE TITLE
Yellow stats being problematic

### ISSUE THREAD

**Issue by Ihmislehma** [cadon/ARKStatsExtractor#574]
I have a problem where I have several yellow stats, and no matter which combination I check, it refuses to be "correct".
![yellow problem](https://user-images.githubusercontent.com/29692166/34532278-3c2c732c-f0be-11e7-9228-4354c9cafaf1.png)
Example with an Aberrant Paracer. I have had this happen for Aberrant Lystros, Ravagers, Shinehorns...
I can take screenshots of the other problem tames I have, too.
Here are my settings:
![settings](https://user-images.githubusercontent.com/29692166/34532348-88818d0c-f0be-11e7-9c39-c9fb891181b6.png)
I play on my own server with mildly jacked up stat gains (mostly 2.0).

On a side note, I relatively often get red stats when extracting, but after some leveling I get yellows instead.

**Comment by Ihmislehma** [comment]
Also on a side-ish note, I sometimes get an error where everything stays white.
![stays white](https://user-images.githubusercontent.com/29692166/34534382-982b8fc0-f0c6-11e7-9959-463040a93669.png)
For some reason the extraction fails so spectacularly things don't even go red.
After leveling a couple of times, the problem is solved enough to only make the food red. Note that the taming affinity is around 99.something, so the range to test is wide enough.
![food](https://user-images.githubusercontent.com/29692166/34534439-cc5269ea-f0c6-11e7-84ae-95d5374b68d3.png)

**Comment by Ihmislehma** [comment]
I Dragged and dropped. I also forgot to mention this is on a server, not single player.
Smart Breed has updated at least once since, I'll see if this problem persists. (I've been having problems loggin to my server).

**Comment by cadon** [comment]
Hi, if you set the stat multipliers of oxygen for the wild- and tamed-level to 2.0 as well, it works. I'm closing this now, if you still have issues, consider to reopen.
