### ISSUE TITLE
Aberration Doed is not working in the extractor

### ISSUE THREAD

**Issue by shmender** [cadon/ARKStatsExtractor#575]
All values from my AB doed are correct in the extractor but the health is coming up in red.  Everything is set to defaults in the settings and i'm on an official server.  I've used this tool for many many doeds on Rag and never had this issue, it was usually my typo if i did.  This time i've checked it and restarted the game several times and it's still coming up incorrect.  Taming effectiveness is for sure between 40 and 50 as shown.  i was there when it was done.  By the way, I LOVE YOUR APP!!!!  Keep doing amazing things, you're my go to by far!  Thank you for all you do!
![smart breeding screen shot](https://user-images.githubusercontent.com/12805197/34642058-2cd12e9e-f2c2-11e7-8c38-1420ed1b86c4.png)
![doed screenshot](https://user-images.githubusercontent.com/12805197/34642059-2ce48304-f2c2-11e7-858b-9a8bd2d40aa6.png)

**Comment by cadon** [comment]
Hi, the issue with the HP of aberrant species is a bug, it will be fixed in the next release.
