### ISSUE TITLE
Stat issues - Dedicated Server - Aberration

### ISSUE THREAD

**Issue by kungfufishstick** [cadon/ARKStatsExtractor#577]
I am having issues with all the dinos I try to input. I have managed to get a couple of tamed dinos to add but it takes a lot of altering stats just to get saved to the library and then manually changing them there. 

I thought I had everything set properly. My server settings doesn't have access to the full range of stat multipliers. I have tried with setting all to 1 and setting all to official settings. I'm hoping I just messed up and its a simple fix. 

If it matters, the server hosting service is through g-portal. 

All screen caps that are hopefully necessary are in this imgur album. 

https://imgur.com/a/9sU7F

**Comment by cadon** [comment]
Hi, did you set the imprinting-percentage with an admin-command or are there any mods that influence the imprinting? With a value of exactly 80% the extraction works (you can check the "Exactly, don't adjust"-checkbox under the imprinting-input).

**Comment by kungfufishstick** [comment]
I just gave it another shot and it is all working now. 

::Face Palm:: 

Just saw the selection of Aberrant variants at the top of the drop down...... It all works fine now. checked a 100% imprinted Aberrant spino and a 100% imprinted ravager. My issue seems to have been with all of my Aberrant variant dinos were being input under non-aberrant. 

Thank you for the hard work and this tool. Ark wouldn't be the same without it!
