### ISSUE TITLE
Stat Issues - Solo Server on Aberration

### ISSUE THREAD

**Issue by Lhoskyy** [cadon/ARKStatsExtractor#579]
Hi!

I'm here because I encounter a problem with the extractor.
As you can see on my pictures, few dinos have no trouble to be extract (like my little Shinehorn) but finally I can't add vast majority of dinos to my library because of stats problems (like Spino and Megalosaurus here).
I don't understand why it works on my Shinehorn and not on others! Even if I restart the game, level up a stat, keep all "Lock to Zero" in green or anything else in this way, nothing has fix my problem at these moment so I can't use you're software for now... :'(

Hope you'll can help me to resolve it!
Keep going and thanks for this amazing tool!!!

![00asb-settings](https://user-images.githubusercontent.com/35234094/34687758-0415a5bc-f4b0-11e7-8b7b-c4752b97cf8e.png)
![00fichiersini](https://user-images.githubusercontent.com/35234094/34687759-043bfb54-f4b0-11e7-883b-4beee21442cd.png)
![01shinehorn](https://user-images.githubusercontent.com/35234094/34687760-0460a1ac-f4b0-11e7-9716-75ea9af0de18.png)
![02megalosaurus](https://user-images.githubusercontent.com/35234094/34687762-04883c4e-f4b0-11e7-9acc-20f330672624.png)
![03spino](https://user-images.githubusercontent.com/35234094/34687763-04ac99b8-f4b0-11e7-91da-87858842f64c.png)

**Comment by cadon** [comment]
Hi, without testing it, the issue is probably that aberrant (irradié) variants have different stats (mostly only HP), that's why they have an own species-entry. Select "Aberrant Spino" instead of "Spino" and try it again.

**Comment by Lhoskyy** [comment]
OoooOoooh, I'm so sorry!!!
I didn't know about stats variations on aberrant, and specify class on the software! ^^"


Thank you for your help!
