### ISSUE TITLE
150 Quetz Weight and Health Extraction Issue

### ISSUE THREAD

**Issue by EveTater** [cadon/ARKStatsExtractor#58]
Hey this is my first time using this however I believe I have a solid grasp on how it works and I'm having an issue with extracting health and weight on a 150 wild quetz we took down. The other stats are green, these two stats are red. It is on the new TheCenter official server, can get the number if needed. I also tried setting the extractor to recognize 150 max wild lvl and it stays in the settings until I close and re enter, where it resets to 120, so I'm not sure if this is the issue and it's just not taking an effect or what.
![image](https://cloud.githubusercontent.com/assets/19828545/15915052/12194322-2db4-11e6-8c49-87767edbe391.png)

Any help is much appreciated.

**Comment by cadon** [comment]
Hi, the stats of the quetzal were adjusted by the devs. Check for an updated stats-file for the tool by clicking on ? -> Check for Updates. You have to restart the tool before it works.

**Comment by cadon** [comment]
The bug with the max wild level showing always 120 will be fixed in the next version. Thanks for reporting that.

**Comment by EveTater** [comment]
Okay, this update seems to have fixed this issue, however I have another one possibly due to user error. I'm having trouble finding the dominated (after taming bonus, before adding levels when it levels up) levels. I've tried extracting it using the new level once fully tamed however it only assigns two levels into the dominated bracket and makes the wild level go over 160. I also tried manually adding it in the stats tester until the "current value" reached what we had after taming, however none of the values came out to be what they should have been. In other words, the health went from 7680 to 9120.1 after taming, however by putting in 3 dom levels you get 8924.2, and 4 dom levels =  9339.
Is there a certain way I'm supposed to do this?

**Comment by cadon** [comment]
Hi, did the extractor not work for this? The bonus-levels you get by taming are also wild levels, so 27 wild levels gave you 7680 for the untamed, once tamed it had 33 wild levels, making the value 9120.1.

Domesticated levels are only the levels you assign manually.

**Comment by EveTater** [comment]
Oh I see, thank you
