### ISSUE TITLE
 0.24.4 ch em.rg not scanning right

### ISSUE THREAD

**Issue by Zhinjio** [cadon/ARKStatsExtractor#580]
Using the newest version, this stat, for some reason, never scans right and throws off all initial attempts to reconcile the wild level. Another thing to note is that I had to uncheck the lock on the stats, as the locks were carried over from the other stat (which normally is locked). It took me a few tries before I figured that one out. I suspect others will run into similar issues.

I can provide screenies of the mis-scan if you like.

**Comment by Zhinjio** [comment]
It seems to consistently read 4.9% regardless of what the stat's value is

**Comment by audiopathik** [comment]
I have the same/similar issue just right now with Ch Regen

When you go to the Experimental OCR Tab you can try to figure/fix it yourself (Go to the Output Tab there>Click the "Read values from ARK window" and see where the wrong digits/letters are from)

**Comment by audiopathik** [comment]
I figured the problem are the rectangles OCR reads the digits from

In ARK: Smart Breeding go to Experimental OCR>Labels and click the "Read values from ARK window" button, you will see the rectangles overlap with the Text Label left to the stat values.

I'm running ARK with German text language so some words have lots more letters than the english text label has and overlaps with the rectangle OCR recognizes letters and digits from.
