### ISSUE TITLE
All Glowtails have a red Food and Ch Emission Range % - Can't Save or finish

### ISSUE THREAD

**Issue by ShadowRune** [cadon/ARKStatsExtractor#581]
Every glowtail I add is not able to save to library because of these red boxes. Can you look into this dino please as I am beginning to breed them.

**Comment by ShadowRune** [comment]
Official Server - no mods, no changes to any settings.

**Comment by audiopathik** [comment]
Try my answer to this issue:
[https://github.com/cadon/ARKStatsExtractor/issues/580](https://github.com/cadon/ARKStatsExtractor/issues/580)

**Comment by Zhinjio** [comment]
are they locked?

**Comment by ShadowRune** [comment]
I tamed 5 dinos so I didnt screenshot every one, but yes they will not allow me to hit the button to add them to library with those 2 red boxes. Its 100% fail, never works, even on my first bred glowtail also.

**Comment by audiopathik** [comment]
There is a red or green lock next to the stats in ARK: Smart Breeding, make sure none of them is red/locked. 

This is was Zhinjio said.

**Comment by cadon** [comment]
Hi @ShadowRune, can you post a screenshot of the inventory of one of them?

**Comment by Deadrot** [comment]
@cadon Check Issue #588. I posted screenshots. Same problem as ShadowRune.

**Comment by Oldskoolsmoke** [comment]
![wt 1 1](https://user-images.githubusercontent.com/35557517/35085805-21539b10-fc22-11e7-9c2b-f2a8c0779917.jpg)

That is a fresh tame no levels added, official rates

**Comment by cadon** [comment]
The issue is found and solved. A new values-file is uploaded which fixes the glowtail-extraction. Get it by clicking the menu ? -> Check for Updates.
