### ISSUE TITLE
Problem with fonds

### ISSUE THREAD

**Issue by EIchljoe** [cadon/ARKStatsExtractor#582]
Hi there,

since a few hours i am trying to configurate this thing. I got a bigger solution 1920 x 1200 and I dont know why he cant read my stats after correcting the ocr. also i looked up the serversettings and manually he also cant give me anything. I dont know where to start since already tried a lot. I set the screensolution to 1920 x 1080 ( also ingame) and took the correct ocr for it. It still couldnt display me anything. Afther that i tried to get the fonds right but he doesnt use the ones I gave him. I think there is an issue with the fonds and the settings which i still couldnt figure out.

Does anybody know where to start?

best regards
Eichljoe

**Comment by cadon** [comment]
Hi, go to the "Experimental OCR"-tab, then to the "Output"-tab and check the "Enable Logging and Editing". Try to read the Values and see if anything is written in the output-field.

**Comment by EIchljoe** [comment]
I enabled Logging and Editing, also I tried to configurate the outputefile since no value was correct. I also tried to change the fonds so he can read the values correctly with in every size.

**Comment by cadon** [comment]
So it reads numbers and letters? That's a start. It should read most of the numbers correctly and some of the letters. Don't expect it to read everything perfectly, though.

**Comment by EIchljoe** [comment]
it reads them but they are 95 % wrong with the new update i can finally add everything manually, guess i need to wait until someone has my screensolution and gives me an ocr 

can be closed
