### ISSUE TITLE
Quick Wild-Creature Check issues.

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#583]
It was peachy in older versions(2-3 versions ago). Today I tried megatherium, 3 wolves and a raptor. Their levels was 140-145. All of them seem to have a problem with damage extraction.

When I'm typing in values and jump to next field, previous calculates levels. Sometimes damage will show value that seems correct, sometimes it won't. When I filled all fields and hit extract, damage is always red (for all dinos mentioned above). One or 2 also had red food.
After taming all calculated just fine.

https://i.gyazo.com/9a83224dcd64bb9faa566a1c0e8f22a6.png

a) before pressing extract
b) after pressing extract
c) after taming

**Comment by cadon** [comment]
Hi, that's a bug with extracting wild creatures. Thanks for reporting. It will be fixed in the next release.
