### ISSUE TITLE
Therizinosaur giving incorrect breeding damage

### ISSUE THREAD

**Issue by Zamirathe** [cadon/ARKStatsExtractor#584]
I just noticed this when I started breeding my Theris for stats to take on bosses. The damage is entered correctly, but the damage used for breeding goes up by 6 points. This is happening on every one I have checked that I originally tamed, the bred ones seem fine. This throws off the numbers when breeding and makes me think there is a mutation when there isn't one.

The Father
![image](https://user-images.githubusercontent.com/11131955/34843392-90a79c5c-f6cb-11e7-89bc-2454d402ddd1.png)

The Mother
![image](https://user-images.githubusercontent.com/11131955/34843419-b2017c9c-f6cb-11e7-82d0-677d47054e7e.png)

Resulting baby pedigree
![image](https://user-images.githubusercontent.com/11131955/34843482-deff1524-f6cb-11e7-98ab-d4523d93cbb8.png)

Baby Stats
![image](https://user-images.githubusercontent.com/11131955/34843558-fe5bf806-f6cb-11e7-9ce8-9efbbc3fe577.png)

**Comment by cadon** [comment]
This is how breeding works. The offspring has values as if it was tamed with 100% taming effectiveness, this changes the values of damage and sometimes food for offsprings of tamed creatures. See https://ark.gamepedia.com/Breeding#Stats_of_the_Offspring for more infos.
