### ISSUE TITLE
OCR "read values from screen" does nothing

### ISSUE THREAD

**Issue by draganot** [cadon/ARKStatsExtractor#586]
I have been having issues with the "read values from screen" feature, when i try to use said feature the smart breeding window vanishes and im put into the ARK game window instead, when i alt-tab back out nothing has updated at all. The OCR output log gives me this message: "Error while calibrating: probably game-resolution is not supported by this OCR-configuration. The tested image has a resolution of 1536×864 px." However, my game resolution is exactly 1920x1080 and I'm running in Windowed Full-screen mode like I'm supposed to, i only have one monitor. If i take a screenshot manually with the win+prtscr command and then manually drag it over it reads everything just fine, i have tried to follow the instructions here https://github.com/cadon/ARKStatsExtractor/wiki/OCR but it didn't help at all.

**Comment by cadon** [comment]
Hi, you can try to increase the "Wait before screen capture"-value. The default value is 500 ms, maybe set it to 1000 or 1500 and see if that works.

**Comment by draganot** [comment]
Right, sorry about the delay between messages. Anyway, i just tried 1000, 1500, and 2000. none of them fixed the issue. I enabled "logging and editing" and clicked the button, it took a shot of the correct window however when i used the scroll bars to look at the image there is a chunk completely missing from the right and bottom sides of the image. The error message in the output log stays the same.

**Comment by draganot** [comment]
While not a true fix to the issue i found that adjusting the expected screenshot resolution seemed to work. Have to double check the data sometimes but its a great improvement to before. So this will work for now :)

**Comment by cadon** [comment]
It should be noted that the resolution for the automatic OCR uses the windows-resolution, not the ingame-resolution.
