### ISSUE TITLE
Karkinos Oxygen

### ISSUE THREAD

**Issue by Noodle198** [cadon/ARKStatsExtractor#587]
when extracting a karkinos values there is no oxygen stat and will not allow me to add it to the library to keep track of tribe dinos even if its not for breeding

**Comment by cadon** [comment]
Hi, can you post a screenshot of the inventory and the stat-multipliers you use on your server? The Karkinos has no oxygen stat, so that should not be the issue.

**Comment by cadon** [comment]
Does the Karkinos for you have an oxygen stat ingame? For me it has not, so the stat is disabled to allow extracting it without entering any value for the oxygen.

**Comment by Oldskoolsmoke** [comment]
Sorry for the confusion. What i mean is if you look at a creature such as a Baryonyx or something that has no in game oxygen stat, such as a Megalodon or Mossasaur. It will look like this as im sure you know
![20180118212149_1](https://user-images.githubusercontent.com/35557517/35122227-ed6ec35a-fc95-11e7-9129-0cf871c0952e.jpg)

**Comment by Oldskoolsmoke** [comment]
Which when it comes to extracting the levels accurately there is no way to see what levels have gone into oxygen/movement speed. But if you take that dino to an obelisk/transmitter or supply drop it will actually show the hidden oxygen stat in game. Its a little trick I found to fully extract a dino that has non existent stats and if you tick "include oxygen for all species" on your program it will fully extract them 100% accurate. This image is the same baryonyx next to an obelisk
![20180118212034_1](https://user-images.githubusercontent.com/35557517/35122355-63db16b0-fc96-11e7-933f-2ac87a49058f.jpg)

**Comment by Oldskoolsmoke** [comment]
I have yet to tame a Karkinos but I would imagine the hidden stat would also be shown

**Comment by cadon** [comment]
I see, didn't know you can see all the stats when a creature is uploaded. That's nice to know, especially to get the speed-levels that way. Thanks for that info!
