### ISSUE TITLE
Problem with Wild(Unleveled) & Bred (non-imprinted) GlowTails. Offical Ab Server.

### ISSUE THREAD

**Issue by Deadrot** [cadon/ARKStatsExtractor#588]
Version 0.24.4
(The Following are a few Glowtails I just hatched)
![1](https://user-images.githubusercontent.com/35438458/34923685-43e795ba-f95b-11e7-926d-66631fd95ea1.jpg)
![2](https://user-images.githubusercontent.com/35438458/34923686-43fcd1dc-f95b-11e7-94dd-2c8be4bee289.jpg)
![3](https://user-images.githubusercontent.com/35438458/34923687-44127bc2-f95b-11e7-8b7c-da890d81cbdb.jpg)
The same thing happened with four fresh tamed Glowtails two days ago.
Huge thanks for all the hard work and dedication!!!!!!! <3

**Comment by Taiine** [comment]
Can conferm also have the same issue reguarding all my glowtails, wild or bred.
https://i.imgur.com/PgkuDpU.png

**Comment by cadon** [comment]
The issue is found and solved. A new values-file is uploaded which fixes the glowtail-extraction. Get it by clicking the menu ? -> Check for Updates.
