### ISSUE TITLE
Is there an issue with Direwolves at the moment, wont extract correctly

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#589]
As the title suggest, having an issue extracting the Direwolf
![capture](https://user-images.githubusercontent.com/1366816/34972784-ee1e56cc-fad7-11e7-9ba0-b4e37e924fcc.PNG)

**Comment by cadon** [comment]
Hi, there's a typo in melee damage, maybe it's that?

**Comment by cyberangel67** [comment]
OMG, now I feel silly. I typed it in that many times and what ended up working was hitting clear and doing it again, must have just entered the right numbers :P
