### ISSUE TITLE
101% imprint fix needed

### ISSUE THREAD

**Issue by BBQsauced** [cadon/ARKStatsExtractor#590]
Hi there.  Love your program, but can you add the ability to calculate values that are above the 100% imprint?  Example:  

The server I play on, has the S+ nanny.  During the imprinting process, it sometimes pushes dino's into the 101% imprint range.  This makes it so I am unable to load this dino into the program.   

   

Thanks again for the great work.  You've saved me, EASILY, a hundred hours in data entry and management.

**Comment by cadon** [comment]
I'll add an option in the next release. I'm closing this now, as being a duplicate of #520.
