### ISSUE TITLE
UI resizing

### ISSUE THREAD

**Issue by VapeTrainGaming** [cadon/ARKStatsExtractor#591]
playing on a larger screen at 100% UI is murder to my eyes and I cant seem to get the reader to read any of the stats after shrinking the UI in game.  So anyone know a better way to make it function ive messed around with ALOT of the features trying to get the OCR to read with no avail.

**Comment by cadon** [comment]
Hi, if you use another UI-scaling, you need a completely new OCR-config-file. If nobody has already created one for your settings, you can create one yourself, see https://github.com/cadon/ARKStatsExtractor/wiki/OCR for more infos.
