### ISSUE TITLE
Bred Megalos can't be added. Might be s+'s nanny's 100% imprinter 

### ISSUE THREAD

**Issue by Taiine** [cadon/ARKStatsExtractor#592]
https://i.imgur.com/6bhPd1j.png
We have 6 wilds that we tamed, all of them added fine. The babys all display the same issue here. We are using S+ Nanny to give 100% imprint. May have something to do with it. 
https://i.imgur.com/oLt0dAy.png
Server setting's are correct. If it's the imprint causing issues may need an extra setting to allow for s+'s nanny so values can still be added.

**Comment by cadon** [comment]
Hi, the aberrant variants have different stats (mostly only HP), so you need to select them separately in the species-selector ("Aberrant Megalosaurus" instead of just "Megalosaurus"). It works then.
