### ISSUE TITLE
Exception with Imprint value extraction beta

### ISSUE THREAD

**Issue by enohka** [cadon/ARKStatsExtractor#593]
A picture says more then 1000 words. I attached a screenshot with the exception message + all the values I put in.

![exception](https://user-images.githubusercontent.com/5359558/35177902-2e1b9d58-fd84-11e7-9193-5097fb119e8c.png)

**Comment by cadon** [comment]
Hi, thanks for the report. I'll fix that exception in the next release.
It should be noted that with that feature the imprinting-quality still has to be entered like it is displayed ingame. The advantage is, that partly event-raised creatures should be possible to extract with that, which the old algorithm couldn't.

**Comment by BBQsauced** [comment]
I'm not able to read what that exception says, but I was having issues with the beta function as well.  I don't know if this helps or not, but here is a screenshot from my attempt to use the new extraction(beta) function:  

![image](https://user-images.githubusercontent.com/35502619/35188530-37f53654-fdfc-11e7-8cf9-b0cb0cbc2e1e.png)

**Comment by cadon** [comment]
@enohka the bug is fixed in 0.24.7.

@BBQsauced it works with the latest version (0.24.7). Note that you need to check "Allow more than 100% imprinting" in the settings.
