### ISSUE TITLE
Error in OCR panel when adjusting labels

### ISSUE THREAD

**Issue by BIOSOIB** [cadon/ARKStatsExtractor#594]
Trying to position the labels for my resolution (1920x1200) but when i attempt to move anything it pops an error. 

![image](https://user-images.githubusercontent.com/35636293/35186457-6f031298-fdc9-11e7-85b6-0a3a1f9c62ed.png)

**Comment by cadon** [comment]
Thanks for the report. This is fixed in the latest release 0.24.7.
