### ISSUE TITLE
Amount of kibble is incorrect.

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#595]
Am I doing it wrong or is there a problem with taming requirements that ASB suggests?

https://i.gyazo.com/639341f6dff933ad4257a38c66d08ef2.png

**Comment by cadon** [comment]
That seems to be a bug. To get reliable taming information until the bug is fixed, go to the Taming-tab, the data there is correct.

**Comment by cadon** [comment]
The taming data is dependent on the level, which is calculated from the torpor value when the Quick Wild-Creature Check is used. Maybe that's the issue. At least the displayed taming info now is correct.
