### ISSUE TITLE
Imprint Percentage >100% Error

### ISSUE THREAD

**Issue by ShakreeElmi** [cadon/ARKStatsExtractor#597]
Hello, as the title says, I can't get the app to extract the level distribution because it wont let me enter imprint percentage more than 100%. Everytime I type in 101% and hit the extract button, it will reset the percentage to 100% and shows error. I'm using the latest version of the app since it says that has been fixed. Thank you.

**Comment by coldino** [comment]
Dumb question of the day... Have you tried enabling the setting? Settings -> Multipliers -> "Allow more than 100% imprinting".
