### ISSUE TITLE
My resolution on my laptop isnt supported 

### ISSUE THREAD

**Issue by PandaLabs0** [cadon/ARKStatsExtractor#598]
my resolution is 1366x768 it says error it is not supported you should add an auto calibration so that all resolutions can be used or make it so mine can

**Comment by cadon** [comment]
Hi, creating a configuration for a resolution can be done manually. For more infos see https://github.com/cadon/ARKStatsExtractor/wiki/OCR

To do this automatically would be technically complicated.

**Comment by Reikal** [comment]
I tried to write an OCR config for 1366x768 but couldn't get reliable results. I think that resolution might simply be to low for the OCR to work well.

**Comment by Shadin23** [comment]
i have the same issue... i followed every step from the manual. i have the font, i have the labels positioning set, just cant get the app to read characters from screenshot, i've tried different font sizes and label positions still cant get it to work
can someone with more expertise create a OCR file for this reso plz ?

**Comment by cadon** [comment]
@Shadin23 does it work a bit, or does it not read anything at all? You can join the discord-server, if someone with the knowledge has time, it's more efficient to help there.
