### ISSUE TITLE
Tablets and mobiles

### ISSUE THREAD

**Issue by Dabala** [cadon/ARKStatsExtractor#6]
Can this all be downloaded on teblets or phones? :)

**Comment by cadon** [comment]
Hi, not yet. Maybe I'll create a mobile version in the future, but that's not a promise :)

**Comment by axi92** [comment]
Maybe a website version? So its multi-platform =)

**Comment by cassfalg** [comment]
In what language is this written anyway?

**Comment by axi92** [comment]
@cassfalg C#

**Comment by kgarms** [comment]
For those still interested in a mobile app I have been working on one for myself.  It is in the early stages of development, and it works for the most part. At least the features i have been able to implement.
[Ark Breeder](https://play.google.com/store/apps/details?id=com.bladeandfeather.arkbreeding)

**Comment by cadon** [comment]
Currently there are no plans for a mobile or web-based app, so I'm closing this question.
