### ISSUE TITLE
Can't extract stats from 137 Scorp

### ISSUE THREAD

**Issue by Ranensol** [cadon/ARKStatsExtractor#60]
Hi again, tamed a scorp with 98.5% effectiveness (ish) ending up with a lvl 137 in the attached image. 
Only relevant server setting stat wise is weight x 2 for tamed and wild dino per level which is set in the app.
In the ARK image attached he's just been tamed and has had no level ups.
It might be the health that's the issue, I had a quick look at the stats.txt and noticed the long value for wild health per level increase and also noticed on the site below that they claim the base health for scorps is 300 not 280 (though the reddit post it came from was 11 months old...), which would give you 0.2 on per level instead of 0.214285714285714.
I did change those health stats, though I can't remember what I flipping set them to sorry (was either "280,0.2" or "300,0.2), and he scanned in before being tamed (though again forgot to take a screenshot), but won't now (I've since reset the stats to your settings), which kinda suggests the tame bonus might need a tweak.
Anyway, if the above helps then great, but let me know if you need any more info, I can always do a before and after tame if you want better stats to work with!

https://docs.google.com/spreadsheets/d/1c7ETWp_aiRTeX4X_yKo-2ugJjFabksR30jwBVrQyUow/edit#gid=0

![extract attempt](https://cloud.githubusercontent.com/assets/19820373/15964261/78686f20-2f0f-11e6-9cfe-bc89919d15bc.jpg)
![scorp](https://cloud.githubusercontent.com/assets/19820373/15964260/78685116-2f0f-11e6-90dc-38a29ae488f2.jpg)

**Comment by Ranensol** [comment]
Felt bad giving half-a**ed info, so did a before and after.

Pre-Tame:
![scorp lvl 24 - pre-tame](https://cloud.githubusercontent.com/assets/19820373/15965286/c383669a-2f14-11e6-8ec6-812dad121f9c.jpg)

Post-Tame:
![scorp](https://cloud.githubusercontent.com/assets/19820373/15965316/05567d28-2f15-11e6-81e3-07ce8b364f71.jpg)


Using the default stats.txt:

Pre-tame fail:
![attempted extract with 280 214285714285714 0 27 0 5 0](https://cloud.githubusercontent.com/assets/19820373/15965294/d42076aa-2f14-11e6-9570-119b3d2bf303.jpg)

Post-Tame fail:
![attempted extract post-tame with 280 214285714285714 0 27 0 5 0](https://cloud.githubusercontent.com/assets/19820373/15965297/dba9db28-2f14-11e6-8a0a-b4c4fd6a496d.jpg)


Using 280,0.2,0.27,0.5,0 for health:

Pre-Tame success:
![successful extract with 280 0 2 0 27 0 5 0](https://cloud.githubusercontent.com/assets/19820373/15965328/1af02486-2f15-11e6-9859-2f968e8417dd.jpg)

Post-Tame success:
![successful extract post-tame with 280 0 2 0 27 0 5 0](https://cloud.githubusercontent.com/assets/19820373/15965336/26d10f04-2f15-11e6-890a-da1a0c6189a0.jpg)

What I can't get my head around though is the scorp I tamed not an hour ago (the one in the initial screenshots) won't extract at all, the one I just did will (with the changes to stat.txt), but to confuse things further I've an old scorp I tamed a looong time ago that's had various level up's etc (none of which I can remember I'm afraid) which extracts fine :/
Apologies if I'm missing something obvious here, but hopefully this data is a bit more useful than the first post :)

![old scorp](https://cloud.githubusercontent.com/assets/19820373/15965394/753296a4-2f15-11e6-9ecb-c40d3653bbb7.jpg)

**Comment by cadon** [comment]
Hi, thanks for the feedback and images. The scorpion is buggy since its base HP got nerfed from 300 to 280 months ago, which mainly screwed up the wild-increase. The long decimal-number fixed it for most cases, but strangely it's still not working sometimes. It seems there are still two versions of the calculation of the HP. I haven't figured out yet what's going on here neither.

**Comment by Ranensol** [comment]
Ahhh, there's nothing quite as annoying as someone else shifting the goal posts and you getting "issues" raised for your software by end users as a result :/
Read that previous discussion (apologies for not looking for previous issues of the same type first) and it fits what's happening with me and the scorps I have, so I'll just leave this one be for now and hopefully they'll sort it out in game at some point. 
I am glad I hadn't missed something obvious/simple though!
Tbh I'm more of an Quetz/Argy/DireWolf man anyway (which all work great), I just got carried away with the app and flying around with the sole purpose of finding high level tames to see what kind of super monsters I could create, whether I actually need them or not :p

**Comment by Ranensol** [comment]
Thanks for the reply btw, I'll close this one off now!
