### ISSUE TITLE
I cannot calibrate the OCR partly because I cannot scroll down to the resolution :/

### ISSUE THREAD

**Issue by WolfieBloodstrider** [cadon/ARKStatsExtractor#600]
Hi there, Im new to the Breeding App and Im just about getting the hang of it, But I'm getting really frustrated with needing to put each of my dino's into the app one by one because the god damn OCR wont capture a screenie and read it.

I play on a bigger monitor which makes it a bit more difficult, But not impossible, I looked up how to recalibrate it so that it uses a custom resolution- But no matter how closely I follow EVERY step I can't get it to work and I suspect this has something to do with it:

Down at the bottom right of the page, within the "Labels" tab, I can clearly see that there's a space for "resolution" and on the guide I see that that part of the options allows you to select to take resolution directly from the screenshot thats in there- well heres the thing, I can't bloody well get to the resolution section. Tried scrolling, zooming, minimizing and maximising the page, I even tried that stupid pressing the mouse button in thing that no one ever really uses apart from by accident, and nothing works. My mouse is fine, I can scroll elsewhere but when it comes to this app, specifically THAT page I can't get down to the "resolution" section despite being able to (frustratingly enough) see the top half of the letters at the bottom of the screen. I've put a SS so you can see what I mean, As I'm that frustrated at this point I'm probably making no sense.

If I could get someone to help with this, or even just help with getting it set up so I dont have to input every. single. Bloody. Dino. that'd be great, Non of the default templates are any good, and evidently, being able to reach the option to set the resolution isn't within reach for me now either, so any and all solutions would be appreciated.

Please see the screenshots, one of the app (and the just out of reach resolution section) and one of my dino's inventory so you might be able to set something up for me if need be, Im not sure if thats possible but I wanted to give as much info as possible. Thanks alot- and sorry if I sound annoyed or salty, it's been a long day and I'm worried that might've come through in my writing.

Thanks in advance, Wolf.

![image](https://user-images.githubusercontent.com/35743412/35297610-6fa2ccba-0077-11e8-954d-7ea1d1ac8d62.png)
![20180123192224_1](https://user-images.githubusercontent.com/35743412/35297622-78849930-0077-11e8-8ae9-e8f8d5a8e1d6.jpg)

**Comment by cadon** [comment]
Hi, sorry for the late reply. Probably you have set the UI-scaling in windows to a value higher than 100% or set the resolution to a low value, causing the application to be cut off. I'll add a scrollbar for these tabs so you can scroll down.

**Comment by cadon** [comment]
version with scrollbars is released.
