### ISSUE TITLE
Cant Extract Dino States(Not even manualy)

### ISSUE THREAD

**Issue by alex1988310** [cadon/ARKStatsExtractor#601]
Below are the screens from the game and from the program .Im playing on unoficial server .
![image](https://user-images.githubusercontent.com/35820678/35417158-e204c286-0234-11e8-97c2-065cc7524d3e.png)

![20180123023852_1](https://user-images.githubusercontent.com/35820678/35417102-94d592b0-0234-11e8-97a2-fbef928a8643.jpg)

**Comment by cadon** [comment]
You have a typo in the oxygen.
