### ISSUE TITLE
Newest version causing unknown crash

### ISSUE THREAD

**Issue by ReptilianEyes** [cadon/ARKStatsExtractor#602]
I'm using an older model laptop running Windows 10. I don't use it for much, but I wasn't expecting any problems with this program. My older version (0.23.something) still runs fine. I downloaded and extracted 0.24.6 but when I open it my laptop crashes. I can only assume it has something to do with the resolution/graphics, as the screen flashes black several times while trying to start the program and I have to power it down and try again. My native resolution is 1366x768. Is there any way I can resolve this? I've tried troubleshooting and changing some of the options in the properties menu before opening, but with the same results.

**Comment by ReptilianEyes** [comment]
Update: after waiting on black screen for a while it gives an error code saying video tdr and saying imgdk64 sys failed. May not have copied both of those exactly, the laptop restarted itself.

**Comment by cadon** [comment]
Hi, in the latest release (0.24.7) I fixed a memory leak, but that should only affect the tool if you edited an OCR-config-file. I don't think that's related to that. AFAIK the error you describe usually is caused by an outdated graphics-driver. ASB isn't really demanding what concerns graphics, so I don't know how this error could be caused.

**Comment by ReptilianEyes** [comment]
I figured that may be the case and I've been planning on getting a new laptop anyways. I will try the new version, but if I don't have any luck I'll just use a previous version that still works. Thanks for taking the time to respond. I love your tool, it has helped me to breed some of the most powerful dinos on every server I join.
