### ISSUE TITLE
Stat Extraction Issue 

### ISSUE THREAD

**Issue by Sassi0586** [cadon/ARKStatsExtractor#603]
Ich bin echt verzweifelt. Hab das Tool auf mein Windows 7 Notebook geladen. Meine frisch gezüchteten Tiere eingetragen... Nichts. Bekomme immer nur Fehlermeldung. Die Felder für Wild, Tamed, Bred und das Level sind rot hinterlegt, alles andere grau. Extraction failed. Wenn ich die Werte Bei Stat Testing eingebe geht es zwar die Tiere dann der Bibliothek hinzuzufügen, aber dann stimmen die Level hinten und vorn nicht. Hab alle Werte von meinem Privatserver (spiele auf PS4) eingegeben.
Wenn es aber ein Freund auf seinem Laptop mit all meinen Werten versucht, klappt es. Brauch ich irgendein bestimmtes Programm zusätzlich auf meinem Notebook oder was könnte ich noch tun? Probiere seit 3 Tagen rum, dreh bald durch :(

**Comment by cadon** [comment]
Kannst du einen Screenshot von deinen Einstellungen in ASB posten und von den Einstellungen auf dem PS4-server?

**Comment by Sassi0586** [comment]
Ähm... Was ist ASB? 😅

**Comment by Sassi0586** [comment]
Ach sorry, komplett verpeilt XD
https://picload.org/view/ddprwopi/20180124_202836.jpg.html

https://picload.org/view/ddprwocl/serverstats.jpg.html

https://picload.org/view/ddprwoci/argentavisasb.jpg.html

**Comment by cadon** [comment]
Es funktioniert, wenn du die Stat-Multiplikatoren von Torpor alle auf 1,0 setzt. Die sind auf dem Server offensichtlich nicht verändert.

**Comment by Sassi0586** [comment]
Okay... Dachte eigentlich schon. Aber danke dir
:) werd ich machen
