### ISSUE TITLE
Oxygen less dinos and Breeding Plan

### ISSUE THREAD

**Issue by Niwaun** [cadon/ARKStatsExtractor#604]
Hi there!

Just before I say anything more, I'd like to say this program is fucking amazing!!
I just have a quick question. 
Why is the "Best Possible" lvl so low on dinos without the Oxygen stat, and why don't they have a speed lvl?

![image](https://user-images.githubusercontent.com/11661058/35479070-e019adf0-03ed-11e8-8dd4-d10cb621b5e8.png)

Because as the picture shows, the max lvl I could get should be 175, but in reality it's 248.
Where do the missing lvls go? 😄

**Comment by cadon** [comment]
Hi, the oxygen- and speed-stat for species without an oxygen-value cannot be extracted. Usually ASB will save the level for these two stats as -1, which is considered as unknown. In the breeding-plan these cases are shown with the minimum-level, like in your screenshot, but with the extra remark, that the true level will be higher.

Somehow the oxygen and speed level in your screenshot is displayed as 0, so the tool expects these levels to be the known levels, when probably they are just unknown. In both cases, there's no way to know the exact maximum level for these creatures.
One way would be to use mods like the super spy glass to get to know the oxygen and speed level of these creatures.

**Comment by Niwaun** [comment]
Ahh ok 😄 

Thanks for clarifying 
And again thanks for an awesome program!!!
