### ISSUE TITLE
Carbonemys Incorrectly display HP

### ISSUE THREAD

**Issue by TheDonnARK** [cadon/ARKStatsExtractor#605]
I couldn't find information about the Carbonemys losing HP after tame (similar to giga and griffin) but the smart-breeding app shows this Carbo I tamed with 5040 HP as 35 points, and I can only feel that this is an error.  5040 HP is 31 points, 35 points is 5600 HP.  It has an additive bonus from the arkpedia site of .07 to HP, but this could hardly account for such a gross discrepancy.

Just wanted to let you know.

**Comment by cadon** [comment]
Hi, why do you think the data is wrong? Where do you read that 5040 is 31 points instead of 35? Different stat-values can be caused by different stat-multipliers, maybe you're playing on a server that has changed them.

**Comment by TheDonnARK** [comment]
Naah, its 1x official servers.  Dododex reads it differently, and I know Dododex is only 100% reliable for pre-tame stats, but also the stat calculator on arkpedia read 5040 HP as 31 points.  TE bonuses do not make enough of a difference for Dododex or the arkpedia stat calc to be off by 4 points, it just simply isn't that high.  Not sure why it reads 35, but it certainly isn't 35.

Carbo base hp is 700, adding 31 wild levels at 140 per level means total HP is 700+(140*31).  140*31 is 4340, adding 700 for a total of 5040.  Add on the .07, you get 5040.07, which Ark rounds to 5040.1

**Comment by cadon** [comment]
I just rechecked all the stats for the Carbonemys and it seems it also has one of the extra HP-multipliers introduced some months ago. Specifically for the Carbonemys it's 0.9, meaning after taming the base-value is multiplied by 0.9 resulting in a new base-value of 630.
The calculator on the wiki is (like Dododex) only for wild creatures and doesn't consider this ExtraTameHealthMultiplier.
I'll put it on the todo-list to include this extra multiplier on the wiki-pages.

**Comment by TheDonnARK** [comment]
That still doesn't add up.  35 points at 140 per point comes out to 4900 HP added from the 35 points.  Plus the new base, puts it at 5530 HP.

**Comment by TheDonnARK** [comment]
I mean, the only reason I feel it is an error is because it is calculated exactly as the wiki says now, to within one tenth of a HP.

**Comment by TheDonnARK** [comment]
Did some experimenting in singleplayer, and looks like the .9 not only applies to the base, but also the levelup amount.  And a level one turtle does have 700 HP, so turtles are now just included in the group of things that get their overall HP wrecked when you tame them!  Sweet.  Gotta love those ~10-15% nerfs.

**Comment by cadon** [comment]
Yes, the increase per domesticated level is always a percentage of the stat-value after all post-tame-boni are applied, so the 0.9 multiplier also affects that. You can check https://ark.gamepedia.com/Creature_Stats_Calculation for the complete formula.

It seems the devs like to introduce new multipliers to further fine-tune the stats. Probably too much complains about turret-soaking with carbonemys in this case ;)
