### ISSUE TITLE
Manual Input

### ISSUE THREAD

**Issue by gwenferox** [cadon/ARKStatsExtractor#606]
I'm on a sever with tools that allow me to see the base/wild level and stats of any dino, so I don't need the extractor, but would love this tool for simply keeping track of best stats and pedigree. However, I don't have the settings info needed from the server admins despite asking. I'd love a way to be able to manually input information and just use the tool as a tracker.

**Comment by coldino** [comment]
You can enter the wild/tamed levels into the "Stat Testing" tab and add to the library from there. Simply ignore the stats. The breeding planner, etc, all work on levels so should work as you want.
