### ISSUE TITLE
OCR Misreading

### ISSUE THREAD

**Issue by Aussieguyx** [cadon/ARKStatsExtractor#607]
For some reason reading values from ark window is not working for me. I'm on 1920x1080, windowed fullscreen, and setup that way in the OCR. The oxygen stat reads as 0.0, the stamina is showing oxygen, and health is showing stamina. All the other values are loading in correctly. Made sure my UI and resolution scale are both full.
https://puu.sh/zcLGY/ab231bf03e.png

**Comment by Aussieguyx** [comment]
Just realised it cut out the ark window. http://puu.sh/zcLRu/8948e5a51b.jpg

**Comment by cadon** [comment]
Hi, is 1920x1080 both your ingame resolution and your windows-resolution?

**Comment by Aussieguyx** [comment]
Yes

**Comment by Promite** [comment]
did you try default gamma?

**Comment by Aussieguyx** [comment]
Wow that was it, thanks :)
