### ISSUE TITLE
Wont Accurately Add a Tame Q

### ISSUE THREAD

**Issue by PreshusRoze** [cadon/ARKStatsExtractor#608]
![image](https://user-images.githubusercontent.com/36016275/35651367-758819aa-06ad-11e8-943e-b8353900fa81.png)

![image](https://user-images.githubusercontent.com/36016275/35651445-b5d41036-06ad-11e8-94f4-c69a6ef69046.png)

![image](https://user-images.githubusercontent.com/36016275/35651504-ef23fc70-06ad-11e8-8727-2c3d13264c10.png)

We've had this Q since before we started using Smart Breeder. And no matter how we adjust things it either gives us 51 base points in weight either BEFORE we added points or it says we had to have added 51 points into the weight stat to reach the level of weight carry our Q obviously has on it.

It's adding TOO MANY LEVELS. It's only had 56 points added into stats since we tamed it.

We have no issues loading 2 other post tame Q's nor the 2 that we've hatched (pre-imprint).
Smart Breeder seems to HATE this one though.

**Comment by cadon** [comment]
You have to choose the level-combination out of the possible entries for all yellow marked stats. Also see https://github.com/cadon/ARKStatsExtractor/wiki/Manual#what-to-do-if-a-stat-is-yellow

The following is a possible solution:  (Quetzal, Lvl 249, TE: 98.3%): HP: 8160.1 (35, 0); St: 3024 (43, 4); Ox: 750 (40, 0); Fo: 3993.3 (19, 0); We: 4771.2 (34, 51); Dm: 226.2% (21, 1); Sp: 136.5% (0, 0); To: 23162.5 (192);
