### ISSUE TITLE
Tab-out issue

### ISSUE THREAD

**Issue by Waffleso0** [cadon/ARKStatsExtractor#609]
Smartbreed doesnt seem to tab back in after it attempts to read the values, non of the stat boxes update nothing seems to change.
Though, when putting a screenshot into the experimental OCR it reads it perfectly.

**Comment by cadon** [comment]
Hi, go to the "Experimental OCR"-tab, there to the "Output"-tab, enable "Enable Logging and Editing" and see what the output-window displays after an attempt to read the values. Usually the reason is displayed there.

**Comment by Waffleso0** [comment]
Hey, Thanks for the quick response.
I've did this and for some reason the image it takes comes out in a lower resolution than it should be, Also still no tabbing back in after i press the ''read values'' button. (screenshot below).
i am using a 4k monitor which we made a custom OCR for, the weird thing is if i would make a sceenshot manually and drag it into the experimental OCR it reads it perfectly fine. 
![screenshot ocr](https://user-images.githubusercontent.com/34446217/35705714-8ae78afa-07a3-11e8-84bc-d6b31ee028ec.png)

**Comment by cadon** [comment]
what's the resolution in windows and ingame? I got some reports about this issue, maybe the size of screenshots that ASB does has some kind of restrictions.

**Comment by Waffleso0** [comment]
Resolution in windows is 3840x2160, in-game it's 1920x1080. The logical solution (at least thats what i was thinking) that its because those are 2 different resolutions, though i tested this by setting the game resolution to 3840x2160, still doesnt seem to work. gives the same error.

**Comment by cadon** [comment]
The resolution of the needed config is displayed in the OCR output, in this case it seems to be 1536×864 px, not sure what the reason for these numbers is. Currently it's recommended to use the import exported method.
