### ISSUE TITLE
Still having issues with quetz stats

### ISSUE THREAD

**Issue by Faythe** [cadon/ARKStatsExtractor#61]
Tamed a 135 Quetz fully kibble tamed, had 97.0 taming efficiency so was +65 levels (200 after tame). Still not showing the food or damage even if I take the TE down to 10%. We are an unofficial server, max dino is set on the program as 150. We have all basic stats with a 3x taming. The server has been restarted before I took the image.
![quetz 6-10](https://cloud.githubusercontent.com/assets/19614480/15981474/03ee7ec0-2f44-11e6-95bb-d75ab1f1fd13.png)

I do have the most recent version 0.19.5

**Comment by cadon** [comment]
Hi, couldn't find what is wrong here. The official multipliers for TameAdd for Health and Damage are 0.14, but changing that didn't make it work, though. Maybe the multipliers are different?

**Comment by Faythe** [comment]
We've double and triple checked the multipliers, and did it once more when I was trying to get his stats just to be sure but that was how it shows.. Another one it shows like that on is a bred creature before imprinting:
![doed-bred](https://cloud.githubusercontent.com/assets/19614480/15985440/e5e8f668-2fba-11e6-8cb6-b81fe078ad70.png)

**Comment by cadon** [comment]
Was the issue sorted out? I still can't explain it other than that there are different multipliers for the damage. The best way is to drag & drop the game.ini and the gameusersetting.ini on the settings-window to get the exact values. I'm closing this for now, if you still have the problem, feel free to reopen it.
