### ISSUE TITLE
How to video for creating an OCR config

### ISSUE THREAD

**Issue by Sindor-Nex** [cadon/ARKStatsExtractor#611]
So not as much as a issue but a request. sorry if this is the wrong spot for this. 

A how to video of setting up an ocr config properly would be huge. Trying to do it from just the help page isnt good enough. I dont know if im the only one (but it looks like im not) its to confusing / not clear enough what to do in all the stuff that needs to be done. I like many others learn a lot better visually.

My other solution is someone just do it for me lol. Which wont happen. So if someone sees this or the app owner plz make a video of hot to setup ocr properly.

**Comment by cadon** [comment]
The currently available info can be seen here: https://github.com/cadon/ARKStatsExtractor/wiki/OCR, afaik there's no video about that so far. It's recommended to use the import export method.
