### ISSUE TITLE
Breeding fields for non-breedable dinos

### ISSUE THREAD

**Issue by xellok** [cadon/ARKStatsExtractor#612]
Would be nice if those fields in the extractor tab (# of mutations, cooldowns) were enabled as well, since some mods (S+, for example, which is very popular and used often) allow for breeding of non-breedables. 
It is kind of weird, actually, since they are off for Karkinos and Basilisk (which I miss), but enabled for Rock Drakes and Reaper Kings.

**Comment by cadon** [comment]
Mod species can now be loaded via the mod-manager, and if these new species are breedable, they're supported in ASB.
