### ISSUE TITLE
Sorting numbers in names

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#614]
When auto-generating names there is the function to give a number at the end if the name is not unique. This is very nice, but: the library sorts for example 'Rex M10' between 'Rex M1' and 'Rex M2'.

Can it either be made to sort that correctly, or make it for example always count in double or triple digits, (thus starting at 01 or 001)

**Comment by cadon** [comment]
The number now has at least 2 digits. Let me know if 3 are better. For now I limited it to 2, to not use too many characters.
