### ISSUE TITLE
Won't add a bred Theri

### ISSUE THREAD

**Issue by TurdFergusen** [cadon/ARKStatsExtractor#615]
![346110_screenshots_20180207043234_1](https://user-images.githubusercontent.com/36231237/35917094-a7585328-0bc1-11e8-8bca-bf5191640d8f.jpg)
![untitled](https://user-images.githubusercontent.com/36231237/35917097-aabe6e6c-0bc1-11e8-8094-cb8afd4c31c2.png)

**Comment by cadon** [comment]
Hi,
this therizinosaurus was probably imprinted before the imprinting-nerf, so you need to use the other algorithm for the imprinting-extraction: disable "Exactly, don't adjust" and enable "Partly Event" to extract it.
