### ISSUE TITLE
Tooltips on group names request.

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#619]
Remember that issues with non-standard font size that messes up tables? Most noticeable in breeding plan.
Since there is no easy way to fix it, can you please add tooltips for dino names? Atm I can't tell if it's 3 or 5 in names and levels there and it would be nice if I could hover it and read info without it being obstructed.

**Comment by cadon** [comment]
Hi, a user just found out how to fix that probably, see #620. Maybe that will help to fix it in the app, even without needing to disable that setting.

**Comment by deedoubleu** [comment]
Win7 has different compatibility options 8(

**Comment by cadon** [comment]
The layout issues in the breeding planner should be fixed now. closing as being a duplicate of #151.
