### ISSUE TITLE
Manual entry no longer calcuates speed

### ISSUE THREAD

**Issue by coldino** [cadon/ARKStatsExtractor#621]
Entering every stat into the Extractor should enable it to calculate how many wild points went into speed. However, since ~0.24.9 (better handling for unknown levels 64547704) this has stopped working, leaving an unknown stat in its place.

**Comment by coldino** [comment]
Scrub the specific version - it seems to have happened before 0.24.9, but after 0.24.5.
Thanks to Kraven for the report.

**Comment by cadon** [comment]
Should work again.
