### ISSUE TITLE
Cannot Extract Griffin Stats

### ISSUE THREAD

**Issue by DAYuki90** [cadon/ARKStatsExtractor#623]
So I am playing on a unofficial Crystal Isles map with the multipliers noted. All other dinos are extracted fine but whenever its the Griffin it always gives me error for HP and Stamina. I tried everything but nothing fixes it. Anyone can help me out?
![1](https://user-images.githubusercontent.com/36484490/36218654-b9bd8a74-117a-11e8-8786-887d334a48ed.PNG)
![2](https://user-images.githubusercontent.com/36484490/36218656-bbbd9878-117a-11e8-91c8-17e6baf063b2.PNG)

**Comment by cadon** [comment]
updated classicFlyers.json is released.
