### ISSUE TITLE
Contribution: New creature images

### ISSUE THREAD

**Issue by coldino** [cadon/ARKStatsExtractor#624]
As discussed... TCL phase 1 images and a bunch of others: [color-regions.zip](https://github.com/cadon/ARKStatsExtractor/files/1726112/color-regions.zip)

**Comment by DahMuffinMahn** [comment]
Thank you for all of the creatures. I am no wondering where exactly I need to extract the img files to... I cant seem to get them to appear in the application.

**Comment by cadon** [comment]
In the folder of ASB create a folder named img and put all the image-files in there.

**Comment by DahMuffinMahn** [comment]
I believe I did that... is the folder related to ASB named json?

**Comment by DahMuffinMahn** [comment]
![ark smart](https://user-images.githubusercontent.com/36363185/36345343-60acb2c4-13dd-11e8-8bf1-a28b98411f23.PNG)

**Comment by cadon** [comment]
Not in the json-folder. Put it directly in the ASB-folder.

**Comment by DahMuffinMahn** [comment]
Ok, I am getting really confused. There is no folder related to the application with the same name... I don't know If I am blind or did something wrong during installation but I am not seeing an ASB folder in which I could put the IMG

**Comment by DahMuffinMahn** [comment]
I just want to see the silly pictures. I just need help finding this stupid folder, or replacing it if I was an idiot and messed up somehow. When I downloaded ASB, all that was in it was the json folder and the application itself which had to be extracted.

**Comment by cadon** [comment]
Sorry for the misunderstanding. With ASB-folder I mean the folder where you have ARK Smart Breeding installed, in most cases it's probably called "ARK Smart Breeding". I.e. create a folder named "img" in the same folder where the .exe is located.

**Comment by DahMuffinMahn** [comment]
That did it! Thank for you assistance and time.
