### ISSUE TITLE
Dino file corruption?

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#625]
In library I noticed 3 pteras with no name, unavailable status and all stats at 0.
I delete creatures, but they reappear on next launch every time.
https://i.gyazo.com/e95155bfc1a82caeb3a9a2bcc70834ed.png

File is not in read only, changes get saved and remain after application restart, apart from these pteras that is.

crossarkXX.xml
https://drive.google.com/open?id=1QRqAR7ypUOFxxT03h_TcFz088psvxLwo
Tags inside seem to be alright, alas that's all I can check myself.

ASB v0.25.2, win7

-----
Unrelated, but feels line not separate thread worthy. What are those columns after cooldown named C0, C1 ... C5?

**Comment by cadon** [comment]
Hi, these Pteras are the unknown parents of some of the Pteras in the library. They are now created as a placeholder for the pedigree display. To remove them completely, you have to set the father of S46_2, the mother of temp9_mal and the mother of W46_2 to "n/a".
In the next version I'll give these placeholder-creatures a descriptive name, so it's known whose ancestors they are.

The C0 - C5 columns are the colors of the creatures.
