### ISSUE TITLE
Enhancement request: library headers for charge critters

### ISSUE THREAD

**Issue by Zhinjio** [cadon/ARKStatsExtractor#626]
Can the headings for the stats in the library be changed if the critter selected is a charge critter?

**Comment by cadon** [comment]
It's added. Are the abbreviations (Ch Capacity -> CC, Ch Regen -> CRe, Ch Emission Range -> CRa) clear enough?

**Comment by Zhinjio** [comment]
Awesome. Yeah, those work.
