### ISSUE TITLE
Give option to not show "Top-creature is already available" again

### ISSUE THREAD

**Issue by Freso** [cadon/ARKStatsExtractor#627]
For some species I already have "top-creatures", and when I'm just arrow-up/down'ing through the list, it breaks the key pressing flow having to close the dialog. It would be good if there was a setting (either in settings or in the dialog) to not show it again.

Possibly with some options like "for this creature", "for this session", "ever"? But anything to not have to dismiss that dialog over and over and over. :)

**Comment by cadon** [comment]
You mean in the breeding planner? You can set the breeding mode to "High Stats", the message will not appear then. I'll move that message to another place, so it will not pop up in the next release.
