### ISSUE TITLE
Directly enter stat levels

### ISSUE THREAD

**Issue by Nikko112** [cadon/ARKStatsExtractor#628]
I use the Super Spyglass mod which allows me to directly see how many levels in each stat a dino has. Thus my current taming spreadsheets are all tabulated by number of levels, not value of the stat. 

I want to use this software for the Breeding Plan function, I don't need the stats extractor.

I'd like to be able to directly enter the levels into the Extractor or Library tabs, so I can smoothly and easily enter my dinos' stats that way.

(if this is already supported, I'm really sorry; I looked for ages and couldn't find it)

Thanks.

**Comment by wmrojer** [comment]
Use the Stat Testing tab instead of the Extractor tab to input you dinos. In the stat testing tab to specify number of vild and domestic levels in in each stat.

**Comment by Nikko112** [comment]
My mistake, thank you.
