### ISSUE TITLE
OCR Font calibration limited to Size 31 Maximum

### ISSUE THREAD

**Issue by Reikal** [cadon/ARKStatsExtractor#629]
OCR calibration for very high resolution screen requires larger font calibration.
Can this be increased to allow for fonts up to at least 52?

I have this mostly working, but the Dino Level text is too large to reliably extract

**Comment by cadon** [comment]
What resolution do you use that you need this font-size? Currently the character templates are saved as an array of 32-bit integers, which means the maximal width of a character can be only 32 pixels. Some characters are even too big for that. Maybe an internal downscaling of large resolutions will be enough to solve that.

**Comment by Reikal** [comment]
I'm setting it up for 4K, though the dynamic text scaling is casing some issues.
I think about 34 would be the top end required as the characters at 31 are still too narrow to capture correctly.

Text size for the name field changes depending on the length (aberrant variant use a smaller font)
I doubt in the current implementation name and gender extraction will be possible, but the stat extraction is working.

Just needs slightly larger letters available to grab the level

**Comment by Reikal** [comment]
Initial 4K OCR for anyone interested.
Only reads stats / imprint.
Will not read Tribe,Owner,Species/Name.
Can read most levels under 200, but has trouble with 0s in the level due to character size limits. (fixing this breaks stats extraction)

[ocr_3840x2160_100_ALPHA.zip](https://github.com/cadon/ARKStatsExtractor/files/1754747/ocr_3840x2160_100_ALPHA.zip)

Not perfect, but about as good as is possible to get currently, and still save a great amount of time.

**Comment by Airmanshortstuff** [comment]
I just found out about this tool and was ECSTATIC to find out I didn't have to "hope" I was breeding well. Long story short, I play on the 55" 4K TV in my living room, and OCR won't adjust to the font size needed to read my screen (it maxes out at 31(?) and "species" font size on my screen is 72). my screen resolution is 3840x2160 if that helps. I will pay to have this fixed if that's what it takes. It's worth the money to save the time and guesswork out of pairing my dinos. As it is, I put all my females in a pen with the best male I have, and hope...which makes me wind up killing more babies than I am proud of..

**Comment by Reikal** [comment]
You could try that alpha build I posted, It'll get you stats at least.
4k is still 4K so even at 55" the font should be pixel based. as long as you're running 100% UI that should be the same size 31 stat fonts.

Now I understand how the OCR is saved it seems like it'll be a lot of work to support fonts over size 31.
