### ISSUE TITLE
Damage calculates wrong number of levels?

### ISSUE THREAD

**Issue by dedlfix** [cadon/ARKStatsExtractor#63]
There is a newborn bred Direbear level 171 with these values: 2160.1 Health, 1500 Stamina, 1080 Oxygen, 10200 Food, 1053 Weight, 231.7 Damage, 222.6 Speed, 11200.5 Torpor. Your tool calculates (all locks are closed) 18 levels in damage (and 25 in speed). But both Dododex and the extractor in the wiki http://ark.gamepedia.com/Direbear#Wild_Stats_Level-up calculate 26 level (and 17) instead. Who is right?

**Comment by cadon** [comment]
In this case the tool is right. The wiki-stat-calculator and Dododex can only handle wild creatures. Once a creature is tamed or bred, the stat-values get more complex.
