### ISSUE TITLE
Limit available dino species.

### ISSUE THREAD

**Issue by wmrojer** [cadon/ARKStatsExtractor#630]
Is there any way to limit the available dino species? Like if I can make a json file that removes specific species that are not available on the server?
I currently play on Aberration, and a lot of the species in Smart Breeder isn't available there, so just to make it a bit simpler I would like to disable the species that does not exist there. I don't want to edit the values.json since it's updated so frequently.

**Comment by cadon** [comment]
Why do you want to limit the species? Do you consider the species-selector too full or is there another annoyance?

**Comment by wmrojer** [comment]
It's no biggie. Just to make it easier to select the correct species by shortening the long drop down list. The list of species is starting to get long with the Aberrant versions of so many dinos.

**Comment by cadon** [comment]
v0.26 has extra lists with the last used species and a list with only the species in the library. Also more suggestions of the input.
