### ISSUE TITLE
Charge Pet OCR Read issue

### ISSUE THREAD

**Issue by iMasonite** [cadon/ARKStatsExtractor#631]
When reading a charge pet's stats from the ShooterGame window, the value found is always 4.9 regardless of settings, modifications or attempts to get the actual value. I am unsure if this is happening just for me as I cant seem to find other people having the same issue other than myself on two separate computers.

**Comment by Reikal** [comment]
I couldn't replicate this. Might help if you run the OCR logging and see what it is actually reading (or thinks it's reading)

![image](https://user-images.githubusercontent.com/36644139/36633842-ce76c93c-1993-11e8-98ef-206694f43152.png)
Ignore the weird name, that's just my config not working.

**Comment by cadon** [comment]
Hi, maybe the reading-label is too large, so a part of the stat-name is read and misinterpreted as number? Probably reducing the size of the label on the left side will solve this issue.
