### ISSUE TITLE
Wild-Tamed-Breed and Level always orange

### ISSUE THREAD

**Issue by tyronleo** [cadon/ARKStatsExtractor#632]
Hello,

I cannot set it to work. The multipliers are fine because other people in the same server got it working, but not me. I always get the Wild, Tamed, Breed and level orange, but I don't know why. I attach screenshots. Any help would be appreciated.
![01](https://user-images.githubusercontent.com/36697134/36477091-46b4d768-1700-11e8-9786-9530ef1aebb3.png)
![02](https://user-images.githubusercontent.com/36697134/36477092-46d4ca14-1700-11e8-842b-1b8c8d15c0c5.png)
![03](https://user-images.githubusercontent.com/36697134/36477093-46f1f1ac-1700-11e8-9c8b-0cef681e3005.png)

Thanks in advance :D

**Comment by cadon** [comment]
Hi, the stat-multiplier for WildLevel for weight is definitively larger than 1.0. Ask you serveradmin or other players on the server if they can give you the correct value for that. Do you use any mods that change the stats of creatures, e.g. the classic flyers-mod?

**Comment by tyronleo** [comment]
Hi, thanks a lot for the answer. Theoretically the rates are fine. But of course if you say that there is a problem with the rates surely it is. I'll ask the team. Thanks a lot.

**Comment by cadon** [comment]
It works when the wildLevel multiplier for weight is set to 4.
