### ISSUE TITLE
Can not extract bred dino stats

### ISSUE THREAD

**Issue by eldoco87** [cadon/ARKStatsExtractor#636]
Playing on an unofficial server with the S+Nanny, which only does 25% dino imprint. Tamed extraction works perfectly, but when I breed them I can't extract the bred stats. I gives me an error about baby mature speed and cuddle interval. I asked the server moderator if he has changes his multipliers since last season and he said no. I am out of ideas on how to fix this. 

![ark breeder](https://user-images.githubusercontent.com/36873217/36710056-2cb5dc78-1b41-11e8-9637-9f95d77b33ce.png)

**Comment by kohonac** [comment]
you may want to update ASB to the current version which is 0.25.3 and you have the imprint as 53.5 when the ingame screenshot shows 58% so between those 2 it might fix the trouble.

**Comment by eldoco87** [comment]
No luck with either. If I don't check the "Exactly, don't adjust" box it will automatically change my imprint % that I input.

**Comment by eldoco87** [comment]
When I don't check the "Exactly, don't adjust" button it automatically changes my imprint percentage. I also updated to the 25.3 with no luck


    On Monday, February 26, 2018 11:09 PM, kohonac <notifications@github.com> wrote:
 

 you may want to update ASB to the current version which is 0.25.3 and you have the imprint as 53.5 when the ingame screenshot shows 58% so between those 2 it might fix the trouble.—

**Comment by cadon** [comment]
Hi, if you use mods that alter the gain of the imprinting-progress (e.g. the Nanny), you have to extract the creatures with the "Partly Event"-checkbox enabled. Then it works:

(Rex, Lvl 237, Impr: 58.33%): HP: 13266.1 (49, 0); St: 1890 (35, 0); Ox: 450 (20, 0); Fo: 14740 (34, 0); We: 915.7 (32, 0); Dm: 362.8% (34, 0); Sp: 111.7% (32, 0); To: 26239.9 (236);

**Comment by eldoco87** [comment]
Thank you! Relieved a big headache for me.
