### ISSUE TITLE
Featherlights

### ISSUE THREAD

**Issue by titankeepr** [cadon/ARKStatsExtractor#638]
I don't have any issues getting it to read most dinos, besides the featherlight.
It wont read the food, speed, or range no matter what gamma level or resolution I try.

We all love the tool BTW is a HUGE time saver!

**Comment by titankeepr** [comment]
Oh and I am using the .26

**Comment by cadon** [comment]
Maybe the labels are overlapping the stat-name? Go to the OCR-tab, then the Output-tab, there enable the "logging and editing". Then try to read the inventory again and go to the Labels-tab. If you press on one of the labels in the list, is the rectangle overlapping with some of the letters of the stat-name? It should only cover the numbers of the stats. You can adjust the left side of the labels with the Width-L-control. After adjusting, don't forget to save the ocr-config in the OCR-Info-tab.

**Comment by titankeepr** [comment]
ok I tried that, and charge emission rage was indeed overlaying.
However when I correct the box size and save and re-read in a variety of angles and gamma levels, it still wont read food, rage, and speed.

**Comment by titankeepr** [comment]
![capture](https://user-images.githubusercontent.com/37028436/36940348-5c236dbc-1f39-11e8-9d36-9971b20ead82.PNG)
added a picture once I discovered it was showing a font error

**Comment by cadon** [comment]
all the stat-rectangles have to have the same hight, which is considered the font-size. It seems the charge-emission / melee label is higher than the other stat-values.

**Comment by titankeepr** [comment]
ok as long as I don't touch height this worked!  thanks so much!
