### ISSUE TITLE
sync issues

### ISSUE THREAD

**Issue by Zhinjio** [cadon/ARKStatsExtractor#639]
we're currently using the file sharing aspects of this, and running into lots of syncing issues. It occurred to me that one way to do this might be to have the shared file sit in a git repo, and use the git syncing/merging facilities to manage the versioning of the file instead of relying on gdrive's mechanisms, which don't appear to be up to the task. 

Thoughts? Not sure how hard that would be to code in.

**Comment by cadon** [comment]
Some people reported issues with googledrive. Dropbox seems to do the job better. Using an external (web) storage would probably be better, if well implemented.

**Comment by Zhinjio** [comment]
I'll give dropbox a try with our group and see how that goes.
