### ISSUE TITLE
Efficiency is not a synonym for Effectiveness

### ISSUE THREAD

**Issue by dedlfix** [cadon/ARKStatsExtractor#64]
In the game it is named "Taming Effectiveness", but your tool uses the word "Taming-Efficiency" in both the UI and the code.

It is really effectiveness. The efficiency doesn't count in the tamig process. Effectiveness is how good a method is to reach the target (in this case max bonus levels), but without taking into account how economical this method is. Efficiency on the other hand compares the methods according to the effort or costs. It is clearly the least effort to just collect berries, and producing kibble is expensive. But kibble however is still the method that has the best effect, thus effectiveness.

**Comment by cadon** [comment]
Hehe, thanks for the note about that. Some time ago I apparently got used to use efficiency and stuck to that without further thinking about it. I guess it was more efficient to write than effectiveness ;)
I'll change it in the tool.
