### ISSUE TITLE
ARK-Tools Import Species Labeled Wrong

### ISSUE THREAD

**Issue by corymcdonough** [cadon/ARKStatsExtractor#640]
When I import using ARK-Tools, ARK Smart Breeding loads in some of the creatures under the wrong species name.

Ichthyosaurus (Dolphin_Character_BP_C) creatures become Mosasaurus in ASB
Dire Bear (Direbear_Character_BP_C) creatures become Dire Polar Bear in ASB

**Comment by kohonac** [comment]
if you update to the lastest version the dolphin are correct as i was having the same problem dont know about the bears tho. 
https://github.com/cadon/ARKStatsExtractor/releases/download/v0.26.0/ARK.Smart.Breeding_0.26.0.zip

**Comment by cadon** [comment]
The import now uses the blueprint-path, it should be correct now.
