### ISSUE TITLE
Unable to load my Quetzal's 

### ISSUE THREAD

**Issue by narrowascent** [cadon/ARKStatsExtractor#642]
I am on an unofficial server with classic flyers.   I have followed the troubleshooting guide both in program on the right and followed the getting red stat link.   Here is what I have done:  I have contacted my server admin and we have all the setting values correct for the server so that was verified.   I have loaded additional values the classic flyers from same folder my database is on.   Seemed to work well and reduced the red marks when trying to extract but still had two.  I have checked values down the list and they mach my Quetzal as the images show. Made sure to follow every step of both troubleshooting guids with same results
![20180308_123234_001 1](https://user-images.githubusercontent.com/33567392/37149755-79410cf8-22cf-11e8-9d57-4e132705153d.jpg)
![20180308_123244 1](https://user-images.githubusercontent.com/33567392/37149774-8d55beaa-22cf-11e8-8883-05002113df7d.jpg)
![20180308_123300 1](https://user-images.githubusercontent.com/33567392/37149786-96d288c8-22cf-11e8-96e5-21619616b05f.jpg)

It probably is something I am missing but I tried my best to follow all the steps and I still must be missing something.  Any help would be appreciated.  This tool is amazing and really looking forward to learning how to use it well

**Comment by cadon** [comment]
Hi, at least in the last image you don't have loaded the classicFlyers file.

**Comment by kohonac** [comment]
as Cad said it should look like this when loaded
![image](https://user-images.githubusercontent.com/3374605/37164593-9e4c0270-22af-11e8-8ddf-9c0f551423fa.png)

**Comment by narrowascent** [comment]
Oh wow ok I did load it but must have not saved or something.  will try again.  Thanks
