### ISSUE TITLE
Extraction issue what am I doing wrong

### ISSUE THREAD

**Issue by Cntipede** [cadon/ARKStatsExtractor#644]
trying to enter my breeder mail Sabre to the Library but I am new to this and some stats are showing up red.

https://gyazo.com/c632584be13ccfe240e4d5381d45a05b

**Comment by kohonac** [comment]
looking at this I think that you server multipliers in ASB are not set correctly but in order to help you further it would best if you take a screenshot of your tames inventory in-game and one of the option of ASB as well.

**Comment by Cntipede** [comment]
here is another of the same type issue btw I play an official server.

https://gyazo.com/bdb85c147c8bcf03b181e0824b016e51

https://gyazo.com/b4b3e831430c2be0d9d171b5e72462ae

https://gyazo.com/b47488b1e2e57fabb424fe3e15657b27

**Comment by kohonac** [comment]
![image](https://user-images.githubusercontent.com/3374605/37475065-1041f658-282f-11e8-9db0-ca9144d0abab.png)
the mosa extracts fine with official settings. what version of ASB are you using? also if you have other questions pls stop by the discord
https://discord.gg/t7dnrF

**Comment by Cntipede** [comment]
0.26.2 v

**Comment by kohonac** [comment]
if you set your wild levels to the same as in my screen shot it should extract if you have any further problems please ask here or on discord

**Comment by cadon** [comment]
I'll close this issue for now, seems to work fine. If you have still issues, feel free to reopen this issue.
