### ISSUE TITLE
Oxygen and movement speed on quick wild-creature check. 

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#646]
Oxygen and movement speed always displayed as question marks on quick wild-creature check.

**Comment by cadon** [comment]
Which species? Speed-level cannot be extracted for species that don't use oxygen.

**Comment by deedoubleu** [comment]
Yes, that's probably it. Just checked dodo and phiomia, both show speed correctly.
Solved, ty.
