### ISSUE TITLE
[Issue] Incorrect wild levels and more.

### ISSUE THREAD

**Issue by nosoundftw** [cadon/ARKStatsExtractor#647]
I've been using the app for 2 months, I wasn't able to successfully extract levels before which seems to be fixed now, but two new issues have emerged, first being incorrect wild levels and second being yellow stat boxes which I can't find the right combination of wild-dom levels for, I tried using all the possible combinations but still I get errors and yellow boxes.

**Comment by kohonac** [comment]
screen shots and specific dinos go along way to helping sort out the problem as it is there is no way for the dev to help with the problem as you have not really gave any information
