### ISSUE TITLE
Giga Stats not pulling   Stat-issue

### ISSUE THREAD

**Issue by defyreality** [cadon/ARKStatsExtractor#648]
can't get this giga's stats to pull. have tried all the usual tricks, but no bueno. was raised on xbox pve legacy in the last 2-3months. was raised by another tribe on my server (egg came from my breeders, so i have a good idea of what the base stats should be). probably was partially raised over the v-day 3x event.

have i missed something?

![giga-destroyer-issue](https://user-images.githubusercontent.com/225750/37852494-2b8f691e-2eb9-11e8-901b-1ed06f1cbe9b.png)

**Comment by cadon** [comment]
Hi, try the [latest release](https://github.com/cadon/ARKStatsExtractor/releases/latest), there it works for me.

**Comment by defyreality** [comment]
yes. that got it. apparently i have become too reliant on the auto update check, was stuck on 25.3.
Thank you.

**Comment by cadon** [comment]
There was a change in the supported TLS version on github that makes a manual update necessary for the update-check to work again.
