### ISSUE TITLE
Stat Extract Issues

### ISSUE THREAD

**Issue by vestedwind42043** [cadon/ARKStatsExtractor#649]
Please create an override button for when there are issues like this...I have tried 4 different breeds...I have stat "issues" on all of them...I have verified my server settings...2 of the rex's had been leveled up a bit, but not the torpidity...The Quetz, Thyla, and lvl 59 Rex I tamed just to test it...That's why they all show the name Dylan, but aren't named..
![stat issue 001](https://user-images.githubusercontent.com/37714922/37856652-a1ec49e2-2ec3-11e8-9a8c-80d68abc7a4c.jpg)
![stat issue 002](https://user-images.githubusercontent.com/37714922/37856653-a2119a12-2ec3-11e8-945d-2ca6ad5d6c25.jpg)
![stat issue 003](https://user-images.githubusercontent.com/37714922/37856654-a228b5c6-2ec3-11e8-8676-748ab6c7facf.jpg)
![stat issue 004](https://user-images.githubusercontent.com/37714922/37856655-a23db16a-2ec3-11e8-9e63-048db686a45b.jpg)
![stat issue 005](https://user-images.githubusercontent.com/37714922/37856656-a2516ef8-2ec3-11e8-8847-94b055b61a1c.jpg)
![stat issue 006](https://user-images.githubusercontent.com/37714922/37856657-a2664f26-2ec3-11e8-890d-bf9359545a1c.jpg)
![stat issue 007](https://user-images.githubusercontent.com/37714922/37856658-a27d5414-2ec3-11e8-9a6f-5baf1df616b6.jpg)
![stat issue 008](https://user-images.githubusercontent.com/37714922/37856659-a292a198-2ec3-11e8-98a5-368025c9c600.jpg)
![stat issue 009](https://user-images.githubusercontent.com/37714922/37856660-a2a8b1ea-2ec3-11e8-9c0a-260c798a5cb7.jpg)
![stat issue 010](https://user-images.githubusercontent.com/37714922/37856661-a2bd51ae-2ec3-11e8-8923-d34ccfe31594.jpg)

**Comment by vestedwind42043** [comment]
I entered all the levels correctly...the first 2 rex's I saved the stats to a spread sheet...that's why the levels differ on those 2.
Torpor on my server is 2.5...All multipliers are correct I copied them directly from my server to the program unless the corresponding numbers in the program for the stats are in my ini file are wrong.
I'm playing on Xbox so I don't have any mods.
I'll look for the temporary save...but I just got a mutation on my allo's and can't save any of them either...it's the weight stat on them...The bottom three I literally just tamed to make sure.

**Comment by VolatilePulse** [comment]
I play on Xbox as well. I'm assuming you're either playing on a Nitrado hosted server or a locally hosted server. If you are playing on Nitrado, can you post the screenshots of all of the multipliers? See the below image for what it looks like on their mobile app (it's found under Game Engine Settings).

If you're playing on a pc/Xbox hosted server (single player as well) it will look a bit different, but posting a screenshot of them would greatly help us out to figuring out what's going on. 

![Nitrado - Game Engine Settings](https://i.imgur.com/pH5ZRrg.png)

**Comment by vestedwind42043** [comment]
I posted pics...I use expert settings with nitrado so mine no longer look like that...

**Comment by VolatilePulse** [comment]
Can you copy/paste the multipliers here? I didn't see the pictures when I wrote that response, sorry. But something is definitely wrong from copying from the game.ini to ASB.

**Comment by vestedwind42043** [comment]
I figured...I went back and added them...lol...Here's my game ini copied...

LevelExperienceRampOverrides=
LevelExperienceRampOverrides=
bOnlyAllowSpecifiedEngrams=false
GlobalSpoilingTimeMultiplier=5
GlobalItemDecompositionTimeMultiplier=5
GlobalCorpseDecompositionTimeMultiplier=5
PvPZoneStructureDamageMultiplier=6.0
bPvEDisableFriendlyFire=true
ResourceNoReplenishRadiusPlayers=0.25
ResourceNoReplenishRadiusStructures=0.25
bAutoPvETimer=false
bAutoPvEUseSystemTime=false
AutoPvEStartTimeSeconds=0
AutoPvEStopTimeSeconds=0
LayEggIntervalMultiplier=0.5
DinoTurretDamageMultiplier=1.0
bDisableLootCrates=false
DinoHarvestingDamageMultiplier=3.0
bDisableFriendlyFire=true
CustomRecipeEffectivenessMultiplier=3
CustomRecipeSkillMultiplier=3
MatingIntervalMultiplier=0.02
EggHatchSpeedMultiplier=17
BabyMatureSpeedMultiplier=25
bPassiveDefensesDamageRiderlessDinos=true
KillXPMultiplier=2
HarvestXPMultiplier=2
CraftXPMultiplier=2
GenericXPMultiplier=2
SpecialXPMultiplier=2
PGMapName=PGMap
PGTerrainPropertiesString=
bDisableDinoRiding=false
bDisableDinoTaming=false
bUseCorpseLocator=true
bDisableStructurePlacementCollision=true
FastDecayInterval=43200
bUseSingleplayerSettings=false
bAllowUnlimitedRespecs=true
SupplyCrateLootQualityMultiplier=25
FishingLootQualityMultiplier=25
PerLevelStatsMultiplier_Player[0]=10
PerLevelStatsMultiplier_Player[1]=10
PerLevelStatsMultiplier_Player[2]=5
PerLevelStatsMultiplier_Player[3]=10
PerLevelStatsMultiplier_Player[4]=10
PerLevelStatsMultiplier_Player[5]=10
PerLevelStatsMultiplier_Player[6]=10
PerLevelStatsMultiplier_Player[9]=20
PerLevelStatsMultiplier_Player[7]=500
PerLevelStatsMultiplier_Player[8]=10
PerLevelStatsMultiplier_Player[10]=10
PerLevelStatsMultiplier_Player[11]=10
PerLevelStatsMultiplier_DinoTamed[2]=2.5
PerLevelStatsMultiplier_DinoTamed[1]=2
PerLevelStatsMultiplier_DinoTamed[8]=2
PerLevelStatsMultiplier_DinoTamed[7]=150
PerLevelStatsMultiplier_DinoTamed[9]=4
PerLevelStatsMultiplier_DinoWild[2]=0.5
BabyCuddleIntervalMultiplier=0.033
BabyCuddleGracePeriodMultiplier=3
BabyCuddleLoseImprintQualitySpeedMultiplier=1.0
BabyImprintingStatScaleMultiplier=3
PlayerHarvestingDamageMultiplier=1.0
CropGrowthSpeedMultiplier=1.0
BabyFoodConsumptionSpeedMultiplier=2
bPvEAllowTribeWar=false
bPvEAllowTribeWarCancel=false
CropDecaySpeedMultiplier=1.0
HairGrowthSpeedMultiplier=1.0
FuelConsumptionIntervalMultiplier=1.00
KickIdlePlayersPeriod=3600
MaxNumberOfPlayersInTribe=15
LimitTurretsNum=125

**Comment by VolatilePulse** [comment]
I see the values in the game.ini, but they don't match up what the game is tell me. 😂

I'm heading home soon so I'll verify all of this with my set up. But the server has been restarted since you saved that game.ini, correct?

(P.S. DinoTamed[2] affects 0 tames. :wink:)

**Comment by vestedwind42043** [comment]
yes....about 5 times since then...lol....and yeah...I don't know why I have torpor set on both player and tames...maybe because I was doing it at 3am and just clicking buttons...lol

**Comment by VolatilePulse** [comment]
So, honest conclusion, the game doesn't allow you to change the torpor increase per level. Setting it to 1.0 allowed all of the ones I tried to extract properly. I'm not sure why that is yet though, but try it out and see if it fixes it for you.

**Comment by vestedwind42043** [comment]
Kk. That might fix those. What about the ones where weight, food, and melee are the problem. I’ll be home in a couple hours to try that.

**Comment by vestedwind42043** [comment]
I didn’t post pics of the Allo’s where weight was te issue. I have them saved in a spread sheet and have either killed or traded the dino’s. But I got a mut today and was wanting to figure out which stat was mutated.

**Comment by VolatilePulse** [comment]
It's not a big deal if not, but it's much easier to help you out if you can join the discord channel. We still forward any issues onto the dev there and he's active there as well. It's more like a chat room, but I can help you out in private message as well.

**Comment by vestedwind42043** [comment]
Kk. I’ll find discord and message you when I get home. Because I put everything in a spread sheet it’s not a big deal if we can’t get it fixed right away or it takes a couple days. Thanks for your help.

**Comment by cadon** [comment]
The extraction works now with these values. The torpor multiplier for wild levels is ignored by the game, that is fixed in ASB now.
