### ISSUE TITLE
Diplodocus stats

### ISSUE THREAD

**Issue by emurday** [cadon/ARKStatsExtractor#65]
Just tamed a new diplodocus about 8pm PST on 6/16/2016.  Stats calc seems to be having an issue sorting out points.

![image](https://cloud.githubusercontent.com/assets/7611518/16139625/3cba2402-33fe-11e6-88c0-10060b91f83e.png)

Notes:
- Used Stats Extractor version 0.19.5.0.
- On a public realm (latest patch).
- Tried using the calc both with and without "Since taming no server restart" checked.
- Used a passive tame; our method of passive tame seemed to take approx. 1/3rd the tame time offered by online taming calculators for a similar passive tame.
- Diplo was 120 prior to start of tame.

**Comment by cadon** [comment]
Hi, the stats in the tool were wrong. Get the new values by clicking on ? -> Check for Updates. Thanks for the report.
