### ISSUE TITLE
Import Info from Dino Extract

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#650]
New feature in ark allows you to dump the dino info now from within the game.  Might consider using the information such as coloring or stats (though they are a little odd some of them).

**Comment by kohonac** [comment]
the developer is already working on it

**Comment by Vykan** [comment]
It's really a great idea this data export dinos! :)
Finished galley for the colors ...

However, I can not import the statistical data, perhaps because the file is in French?

> 
[Dino Data]
DinoID1=238976811
DinoID2=104484924
DinoClass=/Game/Aberration/Dinos/LanternPug/LanternPug_Character_BP.LanternPug_Character_BP_C
DinoNameTag=Pug
bIsFemale=True
bNeutered=False
TamerString=Aberrant Dundees
TamedName=BulbDog-F01
ImprinterName=
RandomMutationsMale=0
RandomMutationsFemale=0
BabyAge=1.000000
CharacterLevel=216
DinoImprintingQuality=0.000000

[Colorization]
ColorSet[0]=(R=0.250000,G=0.084211,B=0.025000,A=0.000000)
ColorSet[1]=(R=0.000000,G=0.000000,B=0.000000,A=1.000000)
ColorSet[2]=(R=0.195000,G=0.300000,B=0.195000,A=0.000000)
ColorSet[3]=(R=0.056525,G=0.138854,B=0.665000,A=0.000000)
ColorSet[4]=(R=0.605000,G=0.193228,B=0.090750,A=0.000000)
ColorSet[5]=(R=0.040000,G=0.040000,B=0.040000,A=0.000000)

[Max Character Status Values]
Vie=928.070007
Capacité de Charge=1136.050049
TORPEUR=834.500000
Regeneration de Charge=600.625000
Nourriture=2219.854980
Hydratation =100.000000
Température=0.000000
Poids =168.000000
Rayon des Charges=2.565095
VITESSE=1.300000
RÉSISTANCE=0.000000
COMPÉTENCE D'ARTISANAT=0.000000

[Dino Ancestry]
DinoAncestorsCount=0
DinoAncestorsMale=0
>

**Comment by cadon** [comment]
@Vykan that's interesting, didn't expect that. Usually exported files should have fixed parameter-names. Well, it's an ARK-thing, I guess. I'll add the French-names in the next release. Can you also post the French names of the non-glow-species names (i.e. stamina, oxygen, melee damage), with their used casing?

**Comment by Vykan** [comment]
Ok, i will make a list of all species....

**Comment by Vykan** [comment]
characteristics in french : 

_[Dino Data]
DinoID1=464032635
DinoID2=262248576
DinoClass=/Game/Aberration/Dinos/CaveWolf/CaveWolf_Character_BP.CaveWolf_Character_BP_C
DinoNameTag=CaveWolf
bIsFemale=True
bNeutered=False
TamerString=
TamedName=Rava-F16
ImprinterName=Féniks
RandomMutationsMale=0
RandomMutationsFemale=0
BabyAge=0.024239
CharacterLevel=208
DinoImprintingQuality=0.000000

[Colorization]
ColorSet[0]=(R=0.480000,G=0.310437,B=0.231047,A=1.000000)
ColorSet[1]=(R=0.000000,G=0.000000,B=0.000000,A=1.000000)
ColorSet[2]=(R=0.000000,G=0.000000,B=0.000000,A=1.000000)
ColorSet[3]=(R=0.000000,G=0.000000,B=0.000000,A=1.000000)
ColorSet[4]=(R=0.200000,G=0.200000,B=0.200000,A=0.000000)
ColorSet[5]=(R=0.100000,G=0.075000,B=0.050000,A=0.000000)

[Max Character Status Values]
Vie=3360.070068
Énergie =1330.000000
TORPEUR=6710.500000
OXYGÈNE=690.000000
Nourriture=4968.000000
Hydratation =100.000000
Température=0.000000
Poids =770.000000
CORPS À CORPS=1.311544
VITESSE=0.350000
RÉSISTANCE=0.000000
COMPÉTENCE D'ARTISANAT=0.000000

[Dino Ancestry]
DinoAncestorsCount=0
DinoAncestorsMale=0_

**Comment by Worldgate** [comment]
One weird issue though, when importing dinos from before their change to imprinting, the program doesnt know how to extract the data.  Not sure why.  Wild tames import just fine.

**Comment by cadon** [comment]
@Worldgate what do you mean exactly by this, what does not work? Are the numbers not interpreted correctly? Can you post a screenshot and your multipliers?

**Comment by Worldgate** [comment]
I am using the official servers, the stats wont extract on bred dinos from before when it wasnt 8hrs between imprinting.  I can give you the XML file so you can try.

**Comment by Worldgate** [comment]
```
[Dino Data]
DinoID1=155887826
DinoID2=83288649
DinoClass=/Game/PrimalEarth/Dinos/Sheep/Sheep_Character_BP.Sheep_Character_BP_C
DinoNameTag=Sheep
bIsFemale=True
bNeutered=False
TamerString=Ragnarok
TamedName=Broken1
ImprinterName=Smaug
RandomMutationsMale=0
RandomMutationsFemale=0
BabyAge=1.000000
CharacterLevel=193
DinoImprintingQuality=0.164161

[Colorization]
ColorSet[0]=(R=0.300000,G=0.240000,B=0.180000,A=0.000000)
ColorSet[1]=(R=1.000000,G=0.750000,B=0.500000,A=0.000000)
ColorSet[2]=(R=0.100000,G=0.075000,B=0.050000,A=0.000000)
ColorSet[3]=(R=1.000000,G=0.750000,B=0.500000,A=0.000000)
ColorSet[4]=(R=0.480000,G=0.310437,B=0.231047,A=1.000000)
ColorSet[5]=(R=0.635000,G=0.393327,B=0.301625,A=1.000000)

[Max Character Status Values]
Health=1578.524170
Stamina=450.000000
Torpidity=873.139832
Oxygen=435.000000
food=3990.863281
Water=103.283218
Temperature=0.000000
Weight=137.573242
Melee Damage=1.776053
Movement Speed=0.032832
Fortitude=0.000000
Crafting Skill=0.000000

[Dino Ancestry]
DinoAncestorsCount=2
DinoAncestorsMale=1

[DinoAncestors]
DinoAncestors0=MaleName=Ovis M2 - Lvl 163;MaleDinoID1=43417464;MaleDinoID2=42415294;FemaleName=Ovis F3 - Lvl 213;FemaleDinoID1=405211837;FemaleDinoID2=356159710
DinoAncestors1=MaleName=Ovis M2 - Lvl 176;MaleDinoID1=43417464;MaleDinoID2=42415294;FemaleName=Ovis - Lvl 169;FemaleDinoID1=411111005;FemaleDinoID2=219242077

[DinoAncestorsMale]
DinoAncestorsMale0=MaleName=Ovis M2 - Lvl 176;MaleDinoID1=43417464;MaleDinoID2=42415294;FemaleName=Ovis - Lvl 169;FemaleDinoID1=411111005;FemaleDinoID2=219242077



```

**Comment by mascanio** [comment]
@cadon could we have the names of the stats configurable? So you dont have to add all langs. Or you can put them in a configuration file so is easy to create a pull request for different langs.

I mean with spanish happens the same with french, non fixed params names, I can paste the Spanish names if you want anyway

**Comment by cadon** [comment]
@Worldgate I can extract the levels of that dino:
`Broken1 (Ovis, Lvl 193, Impr: 16.42%, Female): HP: 1578.5 (18, 43); St: 450 (35, 0); Ox: 435 (19, 0); Fo: 3990.9 (18, 0); We: 137.6 (24, 0); Dm: 277.6% (23, 0); Sp: 103.3% (12, 0); To: 873.1 (149);`. Do you have red stats during the extraction?

@mascanio In the next release I'll assume that the stats are always in the same line, so the language / parameter-name does not matter.

**Comment by mascanio** [comment]
@cadon Initially thought the same, but i dont know if that would work with dinos like LanternPug or the ones missing stats (what happens if the export skips the line?)

anyway, thanks and good job

**Comment by cadon** [comment]
all creatures seem to have all stats, some just don't display them (e.g. the aquatic species oxygen). This method could fail because of this, but if it works, I'd go with that much more flexible solution. The release is out, let me know if the import works or if the stats are mixed or wrong.

**Comment by mascanio** [comment]
Seems to work fine with Rexes (only creature that i have exported files now). I cant log to the server ATM, I'll test other creatures when I log (later this night/tomorrow)

**Comment by cadon** [comment]
@mascanio The allosaurus is fixed. Do you still have issues with the megalodon?

**Comment by mascanio** [comment]
sorry for being alte to answer, megalodon and allo seems to be working fine, thanks!
