### ISSUE TITLE
Sabertooth

### ISSUE THREAD

**Issue by Drizzle404** [cadon/ARKStatsExtractor#652]
Tamed a Sabertooth during an Evolution Event. 150 with kibble, 98.6% effectiveness. (150 + 73) The numbers say it's incorrect. I play on official servers. I'm using the default calculation settings.

![2471247](https://user-images.githubusercontent.com/37800343/37903464-49edd410-30b5-11e8-95db-33cec9d230cb.png)

**Comment by kohonac** [comment]
try lowering the TE in orange just above the extract button

**Comment by cadon** [comment]
Try the newest release 0.27, it works there.
