### ISSUE TITLE
Troodon Foot Stat Not Being Accepted

### ISSUE THREAD

**Issue by Enduriel** [cadon/ARKStatsExtractor#657]
I'm having issues pulling bred Food stats from Troodons. This persists after server restart and happens on multiple Troodons. I have attached some screenshots of different ones. Have also tried lvling the food stat but nothing changed. Any help would be appreciated.
![image](https://user-images.githubusercontent.com/28669758/38161356-d19ae35a-34cd-11e8-94d3-47a7d3517585.png)
![image](https://user-images.githubusercontent.com/28669758/38161369-f864548a-34cd-11e8-9fd7-5a672d7c77ba.png)

**Comment by VolatilePulse** [comment]
Out of curiosity, did you happen to read the warning box that says, "The Troodon is known for displaying wrong stat-values after taming. Please try the extraction again after the server restarted."?

**Comment by Enduriel** [comment]
Also do notice how the second one is bred, not tamed.

**Comment by kohonac** [comment]
a screenshot with the server multiplier would help with trying to solve what is going on

**Comment by Enduriel** [comment]
It's acting really odd right now... 
![image](https://user-images.githubusercontent.com/28669758/38165622-b5de1da0-3516-11e8-990b-39500bbde971.png)
There's no way its food is that high because the parents don't have it that high so I'll just wait for another restart, I've bred a few more so should get better stats now.

**Comment by cadon** [comment]
This is a duplicate of #554, I'll close this for now. ARK sometimes uses outdated values for stat-calculation, the Troodon-Food is such an example.
