### ISSUE TITLE
import trouble for featherlights

### ISSUE THREAD

**Issue by kohonac** [cadon/ARKStatsExtractor#658]
several stats are not imported. english client and PC settings. please let me know if there is something else you need
![image](https://user-images.githubusercontent.com/3374605/38169813-25cc5192-3529-11e8-9370-fd9c9ac98c34.png)

[DinoExport_378114156254730976.zip](https://github.com/cadon/ARKStatsExtractor/files/1866104/DinoExport_378114156254730976.zip)

**Comment by cadon** [comment]
The latest release should get the stat-values correctly, the species-names could still not work, the game calls some species differently. I'll add these internal names when they get reported. The featherlight, glowtail and beelzebufo should work in the next release.

**Comment by kohonac** [comment]
thank you and yes they imported correctly with 27.1
