### ISSUE TITLE
Limiting dino colors based on default options.

### ISSUE THREAD

**Issue by VolatilePulse** [cadon/ARKStatsExtractor#66]
When adding dinos, I add a lot, I typically bypass the color selector portion because it's hard to know exactly which one my dino has and some of the colors are very similar in color. The wiki has most, if not all, of the dino colors listed per region and think it would be a lot easier to pick only from the default colors as opposed to just guessing. I would suggest an option to disable the feature so that players with admin privileges can still customize their colors, if they're even concerned with using the color picker to begin with.

**Comment by cadon** [comment]
Hi, highlighting the possible colors is a good idea.
What do you mean by disable the feature, hiding the color-buttons and creature-image? I don't see how that would improve the tool. Do you feel it would be clearer without that?

**Comment by VolatilePulse** [comment]
Sorry, I should have clarified a bit more. The default, checked, option should limit the colors per region. In regards to the Argentavis, regions 0, 2, 3, and 4, would allow color numbers 20, 22, 24, 33, 34, 35, 14, 18, and 13 (which I think is actually wrong, according to their color IDs page, color number 13 doesn't occur naturally and I believe it should be 35). Region 5 would allow 21, 23, 32, 33, 14, 18, and 8 (which again, I believe should be a different number, not sure which though).

The unchecked option should allow any color to be selected since, with the use of admin commands, you can permanently change the color of any region of a tame to any color, including those that don't naturally occur.

I think it would be worth changing the color region numbering in the program to reflect those on the wiki, i.e., 1-6 should be 0-5 instead. The admin commands also follow this numbering scheme.

**Comment by cadon** [comment]
Ah, got it, thanks for the clarification, just misunderstood the last sentence. I'll change the numbering as well.

**Comment by VolatilePulse** [comment]
Awesome, I look forward to seeing that feature implemented. Any chance on adding more dino images to visually see the color regions? The 7 you have are a great start since they're some of the more common ones, but there are a lot missing, and more added regularly.

**Comment by cadon** [comment]
It's planned to add them all, but it's a bit of work to create these files. Do you have any preferences for the next ones?

**Comment by VolatilePulse** [comment]
Not really, I deal mostly with argies. I'd say the most common dinos would be a way to start, doedi, ankylo, quetz, giga, paracer, bronto, turtles. I'd say even just doing 1 every minor version release would great. Do you have to draw the images and then code the color regions or do you already have the images? I was impressed when I first saw the ones you had. Great job thus far, on everything in general as well.

**Comment by cadon** [comment]
Thanks. The images are taken from the devkit, the materials of the creatures have to be adjusted and then I just take a screenshot. I'll see that I add more creatures soon.

**Comment by purplewargreymon** [comment]
i think this would be an increadibly helpful thing, and i think fixing the spinos color regions as they have i think 4 different regions. Thank u for creating such a helpful tool btw.

**Comment by cadon** [comment]
I added the preselected colors for the creatures. If you see errors there, comment here.
