### ISSUE TITLE
Issue with Allossaurus and Thylacoleo

### ISSUE THREAD

**Issue by Casrod** [cadon/ARKStatsExtractor#662]
![image](https://user-images.githubusercontent.com/38160154/38455958-43981856-3a55-11e8-944e-87e1af039cc7.png)
![image](https://user-images.githubusercontent.com/38160154/38455968-61520636-3a55-11e8-9854-7015cf5c9523.png)
![image](https://user-images.githubusercontent.com/38160154/38455978-9cc871c8-3a55-11e8-8a14-eb75a8d72320.png)
![image](https://user-images.githubusercontent.com/38160154/38455979-a542efa4-3a55-11e8-88c3-ad72c8033e1e.png)
I'm getting Issues w both dinos, trying to manual set the points, and i am unable. how do i set em?

**Comment by cadon** [comment]
They work fine for me. Do you have changed the stat-multipliers?
