### ISSUE TITLE
Q: Other Species from Mod

### ISSUE THREAD

**Issue by pApA-fLiK** [cadon/ARKStatsExtractor#663]
Hello Everyone, 

how i can add other species from an mod ? Like Ancient and Dragon Mod ?

**Comment by coldino** [comment]
Questions like these are best asked and answered in [Discord](https://discord.gg/qCYYbQK) as you'll find other people there who have done this before.

ASB can load additional mod files, just like the existing Classic Flyers support. Check the [instructions on the wiki](https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values) and use the [data file for Classic Flyers](https://github.com/cadon/ARKStatsExtractor/blob/master/ARKBreedingStats/json/classicFlyers.json) as an example (which you can view more easily with a formatter such as [this one](https://jsoneditoronline.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcadon%2FARKStatsExtractor%2Fmaster%2FARKBreedingStats%2Fjson%2FclassicFlyers.json)).

The biggest problem is normally getting hold of the values from the mod developer.

**Comment by cadon** [comment]
Mod values are now generated automatically by an external tool. See the discord channel for more info and mod-requests.
