### ISSUE TITLE
red stats

### ISSUE THREAD

**Issue by Sivarias** [cadon/ARKStatsExtractor#664]
Hello,

I'm fairly new to the smart breeder and need some help.  I'm trying to input the stats of a baby argent (now adult) (partial imprint) that was given to us and its stats keep coming up in red.  I got it towards the end of the easter event so I'm not sure if that has anything to do with it.  I am on an official server.  I've attached the two screenshots of what i'm working with here.  Can you please help?

Thanks,
Siv

![image](https://user-images.githubusercontent.com/38293705/38630795-83aad368-3d7d-11e8-9e38-1ff18100f476.png)

![image](https://user-images.githubusercontent.com/38293705/38630808-938c8a6a-3d7d-11e8-8449-c1f3f1115813.png)

**Comment by cadon** [comment]
It works for me. Do you have changed the multiplier-settings?

**Comment by Sivarias** [comment]
i don't think i've changed any of the settings.  what do i need to do?

**Comment by cadon** [comment]
You use a very outdated version. Update to the latest here: https://github.com/cadon/ARKStatsExtractor/releases/latest

**Comment by Sivarias** [comment]
oh wow alright had no idea.  Is there a way to update so i don't lose the stats i've already entered in?

**Comment by cadon** [comment]
The library-file can be used with the updated version as well, all the creatures stored there can be loaded again.

**Comment by Sivarias** [comment]
Thanks so much, its working now!! :)
