### ISSUE TITLE
Pegomastax HP issue

### ISSUE THREAD

**Issue by meza** [cadon/ARKStatsExtractor#665]
I've just tamed a max level pego on our server. I've set the Extractor to the correct server multipliers, and have been using it to great success for a while now. This pego however does not seem to pass the numbers.

![annete](https://user-images.githubusercontent.com/211977/38643052-d7d7acee-3dd3-11e8-836f-c13e30db8462.PNG)
![annetebug](https://user-images.githubusercontent.com/211977/38643055-d960f64c-3dd3-11e8-9dd8-2456c7f70264.PNG)

I've tried with 0.25.3 and now with 0.27.3 too, same thing.

**Comment by kohonac** [comment]
unless im mistaken that pego was admin tamed since the max you can get from a 120 wild is 179 since you are not able to get 100% TE in vanilla. also a screenshot of your multipliers in ASB normally helps sort things out quicker

**Comment by meza** [comment]
It was not an admin tame, it stole about 2k mejos off me, the bastard. Here are the multiplier settings
![multi](https://user-images.githubusercontent.com/211977/38648972-00491650-3dec-11e8-8b98-2a06aae4dd98.PNG)

**Comment by meza** [comment]
It could very well be an ark hiccup

**Comment by cadon** [comment]
The Pego HP is known for issues. Maybe it will sort out after a server-restart or if all players leave the render-distance, or if you level up HP. I'd wait for a couple of days, if it still doesn't work level up HP once.
