### ISSUE TITLE
Colors reset

### ISSUE THREAD

**Issue by TopChelf** [cadon/ARKStatsExtractor#668]
Colors assigned to tames in library all have defaulted to the same colors with the latest update.

**Comment by cadon** [comment]
Can you describe what you did before this issue occured?

**Comment by TopChelf** [comment]
Inventorying as usual in version 0.27.3, launched and was prompted for update to 0.27.5. After update and launch, I opened my file to find that all the tames (rexs) I had added were now the same color signatures as the last saved rex.

**Comment by cadon** [comment]
So after saving in 0.27.3 the colors were ok, and immediately after loading them in 0.27.5 the colors were the same?

**Comment by TopChelf** [comment]
Correct - now in the latest version (after I updated the colors again) most but not all of them have defaulted to the same. In a different color scheme than before.

**Comment by cadon** [comment]
The latest version 0.28.0 fixed an issue regarding colors, maybe this one was releated to that. Is the issue still happening?

**Comment by TopChelf** [comment]
I will start logging colors again and update if I have more problems. Thank you for the continued and excellent support!
