### ISSUE TITLE
export to clipboard

### ISSUE THREAD

**Issue by ibixat** [cadon/ARKStatsExtractor#67]
Would be nice for a feature to export stats to clipboard for sharing info with tribe members quickly.  Could even spice it up with arkml for colored stats based on user settings.  I do it manually now but an export to clipboard with stats colored based on he same colors used in the program would be amazing

**Comment by cadon** [comment]
good idea, I'll include that. Currently you can export all the levels of a dino by clicking on Edit - Copy for Spreadsheet. But that's more for a spreadsheet obviously and too much text for the chat.

**Comment by mirzataha** [comment]
Sorry to post here but it says: The image-files have to be downloaded separately: Creature-Images. Extract the folder "img" in the tool's folder to get better visuals of the creature's colors.

Where is the tools folder?
