### ISSUE TITLE
Option to not create placeholder parents

### ISSUE THREAD

**Issue by Urubaean** [cadon/ARKStatsExtractor#672]
Hi, i've a little problem with the deleted dinos, after restarting the app, they appear again in my library, the app didn't modify the baby and so when i restart the app, "ghost" of parent, without any stats are created, i'ts pretty boring to have to edit manually every dinos for deleted their parents where they are not here anymore (sorry for my bad english ^^")

![bug](https://user-images.githubusercontent.com/38652151/39116658-4981f1dc-46e5-11e8-8131-501d06a6e176.png)

**Comment by cadon** [comment]
Hi, deleted dinos appear again if you use a shared library (with a cloud-service like googledrive or dropbox) and another use has the same library-file opened.
These ghost-creatures are created automatically if you import a save-file. It's on the todo-list to disable the creation of them.

**Comment by cadon** [comment]
Yes, they are created when importing a save-file which has creatures that have parents that are not in this save-file (e.g. dead or uploaded to another server).
A reason why they reappear could be that another user has opened the same file via a cloud-service.

**Comment by cadon** [comment]
Placeholder creatures are not shown in the library anymore and deleting creatures in shared libraries works now.
