### ISSUE TITLE
What do the orange names mean?

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#673]
I updated to latest version, and now all my dinos in the library have orange names. It is really hard to read as some dinos are also in orange boxes.

I cannot find any patch note on this as I missed some versions in between (the updater failed to work).

**Comment by cadon** [comment]
This was added in 0.27.4
> added new setting for max server level, creatures that have a risk of hitting this will be marked with a red text in the library.
You can disable this in the settings - Multipliers - Maximal Levels on Servers - Max Total Level, by setting the value to -1. I'll change the color to a better to read color in the next release.

**Comment by soepie7** [comment]
If that is the case I can confirm it is **not** working. I figured at first it was that, but a=either setting it to -1 or to something way higher than anything I own still makes every single name orange.

**Comment by soepie7** [comment]
![image](https://user-images.githubusercontent.com/21133200/39335165-2b21ec90-49b2-11e8-8fe1-ba3d9af1314b.png)
