### ISSUE TITLE
After importing from two servers my Argies are not showing in the breeding section

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#677]
As the title says, this is a fresh import, no changes of settings that I can see that could affect this.

![capture](https://user-images.githubusercontent.com/1366816/39590413-2868024a-4f44-11e8-9830-7ee0f99d86da.PNG)
![capture1](https://user-images.githubusercontent.com/1366816/39590419-2bb6f44c-4f44-11e8-898a-ee43183005da.PNG)

**Comment by kohonac** [comment]
it looks like that all your male argies are set to unavailable in asb so it cant make a match

**Comment by cyberangel67** [comment]
well it appears there are a few species doing this, this was directly from an import so how does that happen?

**Comment by cadon** [comment]
An option to add creatures with a cooldown in the breeding planner was added. If there are still issues, feel free to reopen.
