### ISSUE TITLE
Add a dino count per server in the server tab

### ISSUE THREAD

**Issue by glitchsniffer** [cadon/ARKStatsExtractor#679]
Myself and many of my tribemates would greatly benefit from a number of dinos per server in the server select tab.  We are limited on how many dinos we can have at a time on each server due to the tame limit.

![asb server](https://user-images.githubusercontent.com/7232465/39611284-45a7973a-4f1c-11e8-943b-1a3568dc1939.JPG)

**Comment by soepie7** [comment]
What else might work is if ctrl+A selected all dinos. Right now it goes to the next creature filter.

**Comment by cadon** [comment]
added both (number and Ctrl+A)
