### ISSUE TITLE
Ptera Stats after nerv

### ISSUE THREAD

**Issue by LameDuck67** [cadon/ARKStatsExtractor#68]
The Stats for the Ptera are not correct any more after the 30%-Nerf (v243).
I can not provide much data, but a bred ptera with 31 levels of damage had 316,3% Dmg before.
After the patch it is only 310,6%. Unfortunately this is a vaild percentage, the calculator said, oh, everything is fine, that bird has 30 levels of damage... rubbish for planing ;)

**Comment by LameDuck67** [comment]
I have tested a bit with several Pteras where the damage has changed.
Probably the additive taming bonus was decreased from 1 down to 0,65.
With that value i got the correct values on my Pteras.

**Comment by purplewargreymon** [comment]
Has the giga nerf been applied already or does th at need fixin as well

**Comment by cbutterfield7** [comment]
I just tamed this and the stats wont extract properly now.
![ptera](https://cloud.githubusercontent.com/assets/9422148/16326281/ce183e5c-398a-11e6-92d1-7b6f716c7076.PNG)
![extractor](https://cloud.githubusercontent.com/assets/9422148/16326288/de0aca3c-398a-11e6-8c6e-bafafc2840c0.PNG)

**Comment by VolatilePulse** [comment]
If I'm not mistaken, the ptera had a 115 wild level and was maybe meat
tamed or hit a couple of times. Try changing the taming effectiveness, I
got a TE or roughly 48%.

**Comment by LameDuck67** [comment]
That ptera could be extracted by me. But I have already set the value from 1 to 0,65:
![ptera](https://cloud.githubusercontent.com/assets/19786696/16328657/a3e5ff28-39dc-11e6-9f35-c6b12283a3e8.jpg)

**Comment by cadon** [comment]
Hi, thanks for the report, the stats-file has been updated. Get the new version by clicking on ? - Check for Updates.

**Comment by Wardjp** [comment]
Incredible turnaround, @cadon , thanks for the incredible work you do for us!
