### ISSUE TITLE
More support for shared libraries

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#684]
I share a library with some tribe mates via dropbox, but we cannot work on it at the same time, because if player A and B add a dino, then they both save in that order, the addition of player A is gone because it's overwritten by player B.

**Comment by kohonac** [comment]
do both of you have both of these checkboxes ticked, also what version you are running might help the developer if there is something not working as intended.

![image](https://user-images.githubusercontent.com/3374605/39704473-49371b86-51c0-11e8-85ab-f3936beaab7f.png)
