### ISSUE TITLE
Read values from ARK Window

### ISSUE THREAD

**Issue by GERDerDennis** [cadon/ARKStatsExtractor#685]
Where is the option? 
![123132132](https://user-images.githubusercontent.com/15837171/39724060-f5dcda56-5247-11e8-971e-b2640bf0121b.JPG)

**Comment by HellFollows** [comment]
@cadon the last 2 updates are broken, you cannot extract, this is a screen of what it looks like now http://prntscr.com/jf35kx

**Comment by mhmr** [comment]
and how to export the dino stats? i cant find any option in ark

**Comment by cadon** [comment]
go to a creature, hold use (default E), choose Options and then Export Data. This is only available on the steam-version afaik.

**Comment by Taiine** [comment]
The OCR worked fine for me and everyone in my tribe that has used it. I can't sort out how to use this tool now. I exported all my creature data but this program can never find them,

**Comment by mhmr** [comment]
Yeah i found it, thanks for implementing this way, it is more efficient than the OCR.
Thanks for the great job guys.

**Comment by FireCulex** [comment]
Took me a while to figure this out, still looking where it stores the creature files, maybe something on the main page explaining the changes better.

**Comment by cadon** [comment]
In the Settings - Import Exported, where you set the path, the usual path is displayed, it's something similar to `C:\Program Files (x86)\Steam\steamapps\common\ARK\ShooterGame\Saved\DinoExports\<ID>`

**Comment by ManaSean** [comment]
I cannot get this to work. No way to change red to green and sometimes no colour at all. Brand new tames show up either red or no colour. Made sure to get correct TE%.
