### ISSUE TITLE
Breeding with Lots of Mutations

### ISSUE THREAD

**Issue by Randomette** [cadon/ARKStatsExtractor#686]
The max mutation count for the breeding plan is 1,000 but we have quite a few that have over 15,000 and I can't use the breeding plan for those. Is there a way you could implement a button or something to ignore mutations? I know I could just not record those but when I get around to breeding my high stats with my clean lines I like having a sure-fire way of knowing it had a mutation without having to go find the mother.

http://puu.sh/Akia5/ec7f4f58c9.png
http://puu.sh/AkibH/809c881884.png

**Comment by Randomette** [comment]
Also the mutations naming option only goes to 99. Again, I know not breeding mutations is a priority but sometimes it can't be avoided when a stat you get from someone else has like 6k mutations cause they've been breeding with mutations for their entire line. By the way, I love how you can see the colors, it really helps me with my color specific breeding even though I lost most of that info during the leak you patched haha. And the import option is amazing and has saved me so much time <3

http://puu.sh/AkiNO/9516b01cca.png

**Comment by cadon** [comment]
You can disable the mutation-limit by setting it to -1
![mutations](https://user-images.githubusercontent.com/8763269/39936474-e58b0ada-554c-11e8-99e3-d4ab49a886e1.png)

If the mutation-counter is larger than 20, it doesn't matter how large it is, so 99 can be seen as a synonym for "many".

**Comment by Randomette** [comment]
I didn't notice the 1 for any mutation so thank you for pointing that out ^.^ and the only reason I want it to be more is so that I can see how many it has but I'll live if it's never implemented. Thank you so much for this tool that makes my life easier <3
