### ISSUE TITLE
Dino changing to Aberrant Anglerfish

### ISSUE THREAD

**Issue by arathein** [cadon/ARKStatsExtractor#687]
Took me a bit to track down how this was happening.
I switch between the extractor and library A LOT and randomly it would seem the dino stats I am trying to extract would suddenly not work because the dino got changed to Abber Angler.

With some trial and error I found that if you click back and forth in the area arrowed in the picture, the dino changes to aber angler.

By no means a show stopping bug but ya know.. now ya know :)

![image](https://user-images.githubusercontent.com/28239481/39949579-2e9d13f0-5541-11e8-9dba-66c6a132c4f5.png)

**Comment by dustinpianalto** [comment]
What version of ASB are you using? I cannot replicate this on either of the last 2 releases.

**Comment by arathein** [comment]
0.28.1

**Comment by arathein** [comment]
IT has happened on multiple versions for me

**Comment by arathein** [comment]
It sometimes does it when I click out of the window and back in, like when I need to go back into ARk to pull up the dino inventory.  What I described was the only way I could reliably recreate it.
cadon wants us to submit stuff when we find it, that is what I am doing.
I made it clear in my message that it is by no means a show stopper, but was letting him know.
He can classify and prioritize it as he sees fit :)

**Comment by VolatilePulse** [comment]
The reason I asked for clarification was trying to figure out how to best reproduce the issue. I will leave ASB open for days without changing the species and it always stays the same for me. I'd like to help track down any bugs you're encountering, but without being able to reproduce, that is difficult.

Dumb questions, I know but I have to ask. What OS are you on and do you use a virus protector? Also, since you tab to Ark and back to ASB, do you not use the OCR or creature export feature?

I meant no disrespect with my previous post, just drinking a bit tonight and trying to help where I can. 😄

**Comment by cadon** [comment]
The first species in the list is the `Aberrant Achatina`, which makes it even stranger. I haven't seen this issue yet. 
* How many times do you have to tab between the `Extractor` and `Library` tab to provoke the species to be set to the `Aberrant Angler`?
*  Do you have an aberrant angler in your library?

**Comment by arathein** [comment]
@cadon I don't have any aber anglers in the library.
It happened again and though I wasn't tracking the exact clicks here is what I did.
Was entering a Meso.. had entered some last night too, breeder has been open since yesterday, I added a meso which of course when you hit add to library takes you to the library tab, I clicked back on extractor, added the next one, I went to add a third and this time when I changed the radio button from Bred to Tamed, it switched the species.

@VolatilePulse No worries, I don't use the OCR function because I have never been able to get it to actually work with my dual monitor setup.  The fact it is so hard to reproduce is super irritating.  I come from a beta testing background so not being able to reliably repro an error when I find it annoys me lol

**Comment by arathein** [comment]
I narrowed it down!
So I was realizing the area I was clicking was right by aber angler in the drop down 
![image](https://user-images.githubusercontent.com/28239481/39968411-10dd05b2-5692-11e8-8c9e-20de52883a5d.png)
From the extractor or Library tab, if you clight right below the tab it switches, so Like click on the tab so it 'hightlights' the tab name, then click or double click just below that box
![image](https://user-images.githubusercontent.com/28239481/39968445-66f7e160-5692-11e8-8088-d41bdafd62e3.png)
![image](https://user-images.githubusercontent.com/28239481/39968453-7b99ad06-5692-11e8-97cc-9c1a3ae4cd79.png)

My guess would be that the species list is "in the back" and that area is clicking through.  Not sure if anything can be done, but at least I was able to reliably recreate it :)
