### ISSUE TITLE
Question on OCR Import

### ISSUE THREAD

**Issue by arathein** [cadon/ARKStatsExtractor#688]
Just trying to gather some information on using the ocr import. @cadon Let me know is this is not the spot for this
@VolatilePulse  Have you been able to get the OCR to work in Windowed Full Screen?
I am using a dual monitor setup, if i use fullscreen in Ark then it goes away when I tab out, however fullscreen seems to be the only way that the OCR will work but I don't know what I am doing either so manybe there is a way to do it in windowed :)

**Comment by cadon** [comment]
For questions you can also use the [discord-server](https://discord.gg/qCYYbQK).
The OCR only works in windows-fullscreen. You also need the correct ocr-config-file for your resolution and UI-scaling.
If you want to import creatures, an alternative way is to use the export-feature of the game: go to creature, hold E, choose Options - Export Data. Then import this file in ASB.

**Comment by arathein** [comment]
@cadon So it only works for me in Fullscreen.  I set the resolution options and adjusted the UI Scale back to 100% and it worked fine.  
It looks like Windowed-Fullscreen actually reduced the UI size on its own, which may be the issue there.
But I'm find using Fullscreen to pull stats :)

**Comment by VolatilePulse** [comment]
As cadon suggested, creature export is another alternative and is strongly recommended over using OCR. It offers more features, less restrictions, and is significantly more accurate.

**Comment by arathein** [comment]
I shall try it out. Thanks :)

**Comment by arathein** [comment]
@cadon @VolatilePulse  I have tried this out, and told my friend that uses ASB about it and this is a game changer for us..  Thanks to both of you for aiming me down that path.
Unfortunately now I really want to go through and export all my dinos lol... but maybe I will just do the color muted ones so I can get the colors right!  Feature request incoming!
