### ISSUE TITLE
Add wild level and tamed level

### ISSUE THREAD

**Issue by Wardjp** [cadon/ARKStatsExtractor#69]
It would be very helpful if in the extractor tab, there was a location where it would display the wild level it extracts for that dino. Also, I'm not sure if it'd be redundant to put this one on the extractor tab, but since breeding takes into account the level a dino tamed out at, it would be super helpful to be able to see the level the extractor determined that dino to be upon tame completion.

**Comment by cadon** [comment]
Hi, good idea. It'll be included in the next release.

**Comment by Wardjp** [comment]
Glad to hear I could help :)
