### ISSUE TITLE
Easy accessible info to check if a hatched baby has good stats

### ISSUE THREAD

**Issue by chronic414** [cadon/ARKStatsExtractor#690]
Hi there,

can you please add a button to switch the view in the library to show the stats instead of the points. At the moment you have to click on one dino to see the actual stats in the upper left corner. Especially when we mass hatching eggs this feature would make life easier to decide to either keep or kill the baby.

And also an option to hide some columns from the library would be cool.

**Comment by cadon** [comment]
Hi, I'll think about a way to see easier if a baby has good stats.
To hide columns, just decrease their width to 0 (drag the column-header splitlines).
