### ISSUE TITLE
Mutation not picking up in extractor

### ISSUE THREAD

**Issue by SLI-Fallen** [cadon/ARKStatsExtractor#691]
Please forgive my ignorance, as I am still trying to learn this complex process.

It is my understanding that it is possible to get a color mutation only, but this will *NOT* count in the mutation count x/20, right?

Because the game is showing me there is a mutation now present. (and I'm pretty sure I got a color mutation) But when this creatures stats were input into the tool, it's showing me ZERO mutations present??

**Comment by dustinpianalto** [comment]
In addition to that, the color mutation can be invisible as well if it mutates a color region that is not shown on that species of dino.

**Comment by SLI-Fallen** [comment]
I am aware of those possibilities based on the creature being bred. This is a Megatherium which does only use two color regions, but according to the Wiki does not have any stat's locked (like a flier does) The body (region 0 color) definitely does NOT show in it's natural color pallete, so it must be a mutation, hense my confusion as to where the mutation is, and why cant I see it in the stats.

Cadon, are you referring to using the capture tool vs manually entering stats? if so, I cannot use it due to I am not using a supported resolution on my monitor, so I never have tried it that way. I do make sure I enter the parents into the tool before extracting.

**Comment by cadon** [comment]
The stat-mutation should be visible in a higher torpor stat, which increases even if a stat without increase was mutated (e.g. speed). Compare the torpor of the offspring with the torpor of both parents to see if there is an increase.
I was refering to the export feature in ARK (look at creature, hold E, choose options - export). The exported file can be imported in Smart Breeding. These file may lack the mutations-info if you didn't open the pedigree of that creature ingame.

**Comment by dustinpianalto** [comment]
While it is true that the Megatherium doesn't have a stat that is "locked" (ie you can still increase the speed post tame) that only applies after the dino is raised and you start leveling it. Every Megatherium that is bred or tamed will have 100% as their base movement speed. If you get a mutation in speed it will still be 100% movement speed. This is true for all dinos that I am aware of.

**Comment by SLI-Fallen** [comment]
Thank you! So, if I understand this correctly, if It was a movement speed mutation, if I level it, I *SHOULD* see greater than the default 1% change for the Megatherium. That's my clue there is where the mutation occurred. They sure don't make this easy do they.  LOL.  What we would ever do without this tool i'll never know. Good thing you like coffee.  ;-)

**Comment by cadon** [comment]
Unfortunately, the mutation in speed will not change anything about the speed-stat, not the current value and not the amount you get when leveling it. The only change that will be noticeable is an increase of the torpor-level and the total level, each by two.

**Comment by arathein** [comment]
@SLI-Fallen Not sure if this was covered, but if you have the parents of the offspring in ASB and the offspring has them listed as the parents, you can used the pedigree tab to see what muted.  In the example below this baby pulled a speed mutation from one of its parents. 
![image](https://user-images.githubusercontent.com/28239481/40269481-e2b5e3f4-5b44-11e8-820a-910f41573119.png)
Pedigree is super helpful to figure out what mutated.  Sometimes they will pull the stat from the lower parent and mutate that, which if they don't get a pretty color with it, puts em on the chopping block for me!

**Comment by SLI-Fallen** [comment]
arathein, THATS IT!! I did not clearly understand WHERE that mutation circle icon showed up, which was what I was looking for! Like I said initially, forgive my ignorance. BTW, It was in fact speed that my first ever mutation occurred (of course candon was spot on!). My most humble thanks to all!
