### ISSUE TITLE
"Ignore Sex in breeding-plan" setting bug

### ISSUE THREAD

**Issue by Archsin** [cadon/ARKStatsExtractor#693]
Checking on "ignore sex" in settings causes "only pairings with XYZ" feature to not properly apply anymore, showing unrelated dinos in the breeding plan. As an side-effect it also lists every pairing redundantly twice, once as both genders

Replicating issue: 
toggle on ignore sex - on library rightclick on dino -> best breeding partners -> following list in breeding plan is no longer filtered, pairing lists twice as both genders
Verification:
toggle ignore sex off - on library rightclick on dino -> best breeding partners -> list is again filtered by chosen dino

ver 0.28.2, win7
- ref: setting on
![image](https://user-images.githubusercontent.com/39405109/40231375-a046e0c8-5aa3-11e8-8147-be7999337fee.png)
- ref: setting off
![image](https://user-images.githubusercontent.com/39405109/40231486-ffeb32fe-5aa3-11e8-9523-6537ca647545.png)

**Comment by cadon** [comment]
Sorry for the long delay, finally fixed now.
