### ISSUE TITLE
Feature Request: pop out text for the color

### ISSUE THREAD

**Issue by arathein** [cadon/ARKStatsExtractor#695]
It would be great if we could get pop out text of what the color is when we hover over it on the pie chart.
Currently the only way to for me to tell the color is to drill into the region and hover over the one it has selected.
I was thinking the pie chart would be an easy place for it and it currently doesn't have any other pop out text like the region buttons themselves.
![image](https://user-images.githubusercontent.com/28239481/40269572-f4259a70-5b45-11e8-8e4f-a0bc8702c764.png)

I'm going to be buying you more coffee soon cuz you just keep making this better :)

**Comment by cadon** [comment]
Good suggestion. It's released.
