### ISSUE TITLE
Bug: Extractor: No way to clear colors other than restarting the app.

### ISSUE THREAD

**Issue by arathein** [cadon/ARKStatsExtractor#696]
Hello friend!
So there looks to be no way to clear the previous dinos colors from the extractor without closing the program and re opening it.
If you click "Clear" at the top it hides the color boxes but doesn't actually clear them 
![image](https://user-images.githubusercontent.com/28239481/40393868-ba31f6d0-5de6-11e8-906d-6da5ec644eb8.png)
![image](https://user-images.githubusercontent.com/28239481/40393881-c8cc7940-5de6-11e8-8bbd-4bcf7094a005.png)

Even after switching species it doesn't clear.. which has resulted in my gigas having color 16 in unknown regions lol
![image](https://user-images.githubusercontent.com/28239481/40393918-ec2e019c-5de6-11e8-8f12-078d66c304ff.png)

**Comment by cadon** [comment]
The colors can be cleared now by clicking on the `Colors` button.
