### ISSUE TITLE
Extraction issue with Pegomastax

### ISSUE THREAD

**Issue by Vykan** [cadon/ARKStatsExtractor#698]
I am having trouble extracting data with Pegomastax, the Stat of Life generates an error that I do not know how to adjust?
I attach the extraction files and a screenshot during the extraction.

Thank you for all this work (I started working on the French translation file and I made some pictures, (where do I send them?)) 

![image](https://user-images.githubusercontent.com/22913843/40577366-2143a688-610d-11e8-8ae1-59257f5e0891.png)

> [Dino Data]
DinoID1=34312974
DinoID2=401836329
DinoClass=/Game/PrimalEarth/Dinos/Pegomastax/Pegomastax_Character_BP.Pegomastax_Character_BP_C
DinoNameTag=Pegomastax
bIsFemale=False
bNeutered=False
TamerString=
TamedName=Pego-M08
ImprinterName=Féniks
RandomMutationsMale=0
RandomMutationsFemale=0
BabyAge=0.002887
CharacterLevel=204
DinoImprintingQuality=0.000000

> [Colorization]
ColorSet[0]=(R=1.000000,G=0.475000,B=0.300000,A=0.000000)
ColorSet[1]=(R=0.200000,G=0.200000,B=0.200000,A=0.000000)
ColorSet[2]=(R=0.300000,G=0.240000,B=0.180000,A=0.000000)
ColorSet[3]=(R=0.000000,G=0.000000,B=0.000000,A=1.000000)
ColorSet[4]=(R=0.480000,G=0.310437,B=0.231047,A=1.000000)
ColorSet[5]=(R=0.300000,G=0.240000,B=0.180000,A=0.000000)

> [Max Character Status Values]
Vie=1520.069946
Énergie =420.000000
TORPEUR=395.899994
OXYGÈNE=690.000000
Nourriture=2018.250000
Hydratation =100.000000
Température=0.000000
Poids =77.000000
CORPS À CORPS=1.693040
VITESSE=0.500000
RÉSISTANCE=0.000000
COMPÉTENCE D'ARTISANAT=0.000000

> [Dino Ancestry]
DinoAncestorsCount=1
DinoAncestorsMale=1

> [DinoAncestors]
DinoAncestors0=MaleName=Pego-M03 - Lvl 202;MaleDinoID1=306624841;MaleDinoID2=151569144;FemaleName=Pego-F02 - Lvl 217;FemaleDinoID1=415595786;FemaleDinoID2=7442562

> [DinoAncestorsMale]
DinoAncestorsMale0=MaleName=Pego-M03 - Lvl 202;MaleDinoID1=306624841;MaleDinoID2=151569144;FemaleName=Pego-F02 - Lvl 217;FemaleDinoID1=415595786;FemaleDinoID2=7442562

**Comment by cadon** [comment]
Hi, Pegomastax has its HP changed some while ago. It's a known issue that the game can still use the old value for months after the change. Usually the value can be updated if you wait for a server-restart and level up the according stat.

You can post the translated file here, e.g. attach it to a post or upload it somewhere and post the link.

**Comment by Vykan** [comment]
Here is the translation of the file in French, it is certainly not the best, but it's as correct as I can.
I will improve some translation during use, the context helps to better perceive the desired meaning.
[translations.txt](https://github.com/cadon/ARKStatsExtractor/files/2045179/translations.txt)

**Comment by Vykan** [comment]
Indeed, the server restart corrected the stats of the incorrect parents.
I'm going to extrapolate for babies, or wait for the next reboot: D
