### ISSUE TITLE
Buggy determination of pterano values

### ISSUE THREAD

**Issue by NakramR** [cadon/ARKStatsExtractor#7]
Pteranodon level 112, kibble tamed. TE 86.5 (was undisturbed, finished taming at level 160).

These are the values pre-nerf. TE 86.5, http://i.imgur.com/mCNeMtL.png

These are the values post-nerf: 4 levels were put in HP, most in damage. None in food. yet: http://i.imgur.com/QZLUi2L.jpg

Going through the code lead me to believe the TamingEfficiency Determination formula 
"
                                tamingEfficiency = Math.Round((inputValue / (1 + stats[c][s][2] * d) - vWildL) / (vWildL * stats[c][s][4]), 3, MidpointRounding.AwayFromZero);
"
Is incorrect.

Either the data for pteranodon (0.18 for stats[4]) is incorrect, or the formula to determine the impact of the TE Post tame Multiplicator is incorrect.

Seeing how food values are problematic too, I'm lead to think it's the latter.

**Comment by cadon** [comment]
Hi,
thanks for the feedback and the screenshots. I tested it with newly spawned Pteras, leveling them up in different ways, and the tool could always find the correct combination. My guess it's the same kind of bug as described in this [thread](https://github.com/cadon/ARKStatsExtractor/issues/2). It seems if a creature is tamed before stat-changes, that the stats somehow are not updated. Maybe it's a caching issue in the game, maybe related to the Torpor-too-high-after-taming-bug.

For the scorpion it was "solved" with a new entry for scorpions, that has different levelup values (see the file stats.txt in the tool-folder). Maybe you can solve it, by reverting the values in the file stats.txt or settings.txt to the values before the nerf. Maybe a server-restart solves the issue.

If you happen to solve the issue, you're more than welcome to let me know.

**Comment by NakramR** [comment]
I have messed around a bit with the values, but can't seem to find the correct ones.

I also have found that these 2 sabertooth kibble tamed 100+ both have wrong values. I don't remember if they're pre-nerf or not.
But it appears that, at the very least for pre-nerfed dinos, those values are incorrect:
http://i.imgur.com/Er9C5q1.jpg
http://i.imgur.com/AmFlPjt.jpg

Hope this data helps. I'm trying to debug on my end, but I'm not as familiar with the data, formulae and code as you are.

**Comment by NakramR** [comment]
And this pteranodon, fresh tamed, 108 kibble perfect (no damage).
http://i.imgur.com/PtaTTqp.jpg
Something's not working correctly...

**Comment by cadon** [comment]
Thanks for the screenshots! It looks like some stats or global multipliers have been changed in one of the last patches again. I'll do some tests later and try to find out what was changed.

**Comment by NakramR** [comment]
I have no idea which of the stats you get from where, and which is derived/guessed. I can help debug the thing (I'm a developer), but I really have no clue what basis you used. Also, do you have an email I can use. Love github, but it's a bit cumbersome.

**Comment by cadon** [comment]
The stats are mainly from the devkit, so the calculations are done like the game does them to get the most precise results.

Each stat has a base value (if not leveled up), the partion (of the base) that gets added if the stat is leveled up in the wild / when tamed, and then some taming-bonus-parameters (absolute addition and percentual addition). These are all saved in the stats.txt. Then there are some extra multipliers to adjust the values of all creatures globally, stored in settings.txt.

My guess is, that these global values for health, melee damage and maybe food got adjusted (and maybe the direwolf got nerfed extra) according to some lately reddit posts.

The easiest way would be to wait for the updated devkit. Maybe one can also guess some numbers in the "Settings"-area of the tool, I think the change was only around 10%. For further questions, you can mail me at cadaei at web.de.
