### ISSUE TITLE
Breeding Value higher than current value

### ISSUE THREAD

**Issue by Shadowlauch** [cadon/ARKStatsExtractor#704]
The current value of the Direbear's damage is lower than the breeding value.
![capture](https://user-images.githubusercontent.com/923322/40889518-5a2e43b6-6768-11e8-878e-e0af3708be48.PNG)

Here is the ingame stats of the bear without actually putting any levels into it.
![capture2](https://user-images.githubusercontent.com/923322/40889536-a71694bc-6768-11e8-88eb-5cbfc170395c.PNG)

**Comment by cadon** [comment]
Yes, that's how it works. You can read more about breeding here: https://ark.gamepedia.com/Breeding

**Comment by Shadowlauch** [comment]
Thanks for the quick answer. And thanks for this tool.
