### ISSUE TITLE
Argen Values for Health and Damage not adding up in program.

### ISSUE THREAD

**Issue by CaptLucky** [cadon/ARKStatsExtractor#705]
The health values for argens and their damage values don't equal values on my smart breeder. Usually the values only have a difference of .2 but it still makes it tedious to look at argens.

**Comment by cadon** [comment]
Hi, there should be no difference, if the stat-multipliers are set correctly. Did you set the multipliers according to your server? Do you use mods that alter the stat-values, e.g. ClassicFlyers? If you still have issues, please post a screenshot of the inventory of a creature that cannot be extracted.
