### ISSUE TITLE
Can't get it to work.

### ISSUE THREAD

**Issue by ManaSean** [cadon/ARKStatsExtractor#709]
Apologies for hijacking other thread.

![smartbreeding](https://user-images.githubusercontent.com/39955547/41016253-b8adc168-6980-11e8-9dc6-36a17a32fd0d.jpg)
Not sure what i am doing wrong. Have exported dino. Was a perfect tame. Bit confused.

**Comment by cadon** [comment]
The server has most probably altered stat-multipliers for damage and HP. If you are the server admin, check the game.ini and gameusersettings.ini of the server. Else you can ask the admin for the stat-multipliers. If you play singleplayer, the settings should be visible in the main-menu.

**Comment by ManaSean** [comment]
You sir are a scholar and a gentleman. One value was incorrect. Thanks for your patience.

**Comment by cadon** [comment]
Thanks, glad it works now.
I'll keep an eye out if I notice any [tentacles](https://ark.gamepedia.com/Explorer_Notes#Sir_Edmund_Rockwell) growing out of me ;)
