### ISSUE TITLE
Beaver damage was nerfed

### ISSUE THREAD

**Issue by Serilyn** [cadon/ARKStatsExtractor#71]
Beaver damage was nerfed in the last ark update (243.0). 

![screenshot 2016-06-24 22 02 25](https://cloud.githubusercontent.com/assets/6901937/16354808/101c5a04-3a58-11e6-8569-8a2138db2b46.png)

Screenshot shows old values in Smart Breeder tool and new values in game. Beaver has never had any points assigned.

Unofficial server. Max wild dino level is 42 with other settings normal.

**Comment by cadon** [comment]
Hi, thanks for the report. I updated the stats, get it via the menubar ? - Check for Updates.
