### ISSUE TITLE
Remove this sad "16" color :)

### ISSUE THREAD

**Issue by Vykan** [cadon/ARKStatsExtractor#710]
Hello,
When I import a creature by drag-and-drop or with import tools, color boxes that are not normally used for a species are saved with **color 16
![couleur 16 non attribuee]**!
There are no solutions to remove this.
How can we remove them?

(https://user-images.githubusercontent.com/22913843/41147728-e0275db8-6b0f-11e8-876c-c2c3fea75c26.png)

**Comment by cadon** [comment]
Thanks for the report! A fix is released.
