### ISSUE TITLE
Issue with Argentavis stats while using classic fliers since TLC update

### ISSUE THREAD

**Issue by Gloilin** [cadon/ARKStatsExtractor#714]
Is there something extra I need to do for this?  I loaded the Classic Fliers json and have all the settings changed to match my server, but my Args are always coming up with Damage and Torpor red.  My Pteras are working fine so thinking it might be using the classic fliers Arg stats that are incorrect now, but I don't know how to change that.  Image of stats attached, using Classic Flyers mod and all stat modifiers are set to 1
![image](https://user-images.githubusercontent.com/40178875/41246755-a48f7e98-6d71-11e8-9f04-9b4787a80228.png)

**Comment by VolatilePulse** [comment]
That's really odd. I can reproduce the issue, however, using the Stat Testing tab I can generate the correct stat levels for the Argentavis. See the attached screenshot to be able to add this one manually. 

![image](https://user-images.githubusercontent.com/6995232/41247782-1c8e9a22-6d7d-11e8-93a4-6675a60d159c.png)
![image](https://user-images.githubusercontent.com/6995232/41247845-3d4c3490-6d7d-11e8-83b8-b3eddc6a1fa2.png)

**Comment by Gloilin** [comment]
Oh okay cool, I'll try using that tab for others as well.  Thanks

**Comment by cadon** [comment]
The creature in the tester is not valid, the sum of the wild-levels need to be the level of the torpor. I think some of the stat-multipliers is still wrong and/or it has something todo with the transition of the argentavis during TLC2 (Harpagornis etc) and / or ARK being ARK and sometimes just showing wrong (i.e. outdated) numbers
