### ISSUE TITLE
Pegomastax not extracting health properly

### ISSUE THREAD

**Issue by sbatten33** [cadon/ARKStatsExtractor#715]
I only have this problem with Pegomastax and even then only the last couple that I have tamed. The extractor seems to not be able to extract a valid health because the value given by the game is in between values that would be valid for wild/taming levels. I set all my setting with respect to this stuff at default and I am playing on single player. Since it only happens with pegomastax, I think either the values given by the game are incorrect, or the values used by Ark Breeder are incorrect. This pego was just tamed with 100% TE and immediately exported so there are no Dom levels to worry about.

Thanks
Shawn

![pegowild8tamed12](https://user-images.githubusercontent.com/40220669/41324483-bc082fae-6e82-11e8-9ea9-d2d8e72b02a8.jpg)
![setting1](https://user-images.githubusercontent.com/40220669/41324484-bc1b5dcc-6e82-11e8-830c-e6cd0e63fbe7.jpg)
![setting2](https://user-images.githubusercontent.com/40220669/41324486-c0f15a22-6e82-11e8-957c-8bc7bd718c47.jpg)
![setting3](https://user-images.githubusercontent.com/40220669/41324487-c41ca15c-6e82-11e8-83f8-e080eb7afab8.jpg)

**Comment by cadon** [comment]
Hi, the pegomastax has known issues with its HP-stat. It was 160 a long time ago, but occasionally the game still uses this outdated value. Usually the correct value (120) is used after a recalculation, which could be triggered by waiting some days / a server restart / after leveling the HP-stat.

**Comment by cadon** [comment]
Regarding the Pegomatax HP issue also see #660.
