### ISSUE TITLE
Feature request: limit dino list

### ISSUE THREAD

**Issue by Zhinjio** [cadon/ARKStatsExtractor#716]
Maybe this already exists and I just can't find it, but it would great to be able to limit the list of possible dinos in searches and extraction matches to just the ones that are on your server. So exclusions for aberration, SE only dinos, etc. Maybe the shortcuts too? Just a thought.

Thanks for considering it.

**Comment by cadon** [comment]
You can filter the creatures in the library according to their server-field in the left-bottom (server-tag). 
Or do you mean that the OCR recognized a species that isn't even possible on the server you're playing?
What do you mean with "searches", the species-selector?

**Comment by Zhinjio** [comment]
Without knowing too much about the internal mechanics of the OCR, I would assume it pattern matches against a list of possible species on the server. It might speed things up to have that list reduced significantly. As it happens, my usage hasn't properly matched the species in probably the last year. I always have to manually select the species before the extractor will work properly.

But yes, at minimum, I'd like to minimize the entries in the dropdown list to just what is available on my server. I'll check out your suggestion when I get home.

Thanks!

**Comment by VolatilePulse** [comment]
We have been trying to sway users away from the use of OCR for extracting creatures in favor of using the creature export feature. This feature allows all users on Steam (even players on official) to extract the stat values, gender, species, level, colors, and ancestors (with a tiny bit of persuasion) with 100% accuracy. Have you tried this feature yet?

**Comment by Zhinjio** [comment]
I haven't! I'll take a look when I get home. That would be awesome. I assume its based on needing some mod, and then importing the file or something. I'll close this once I get home and can check the fix you suggested above.

**Comment by VolatilePulse** [comment]
No mod is needed. The only requirement is that you play on Steam and that you are the owner of the Dino. It sadly doesn't work for wilds and doesn't work if your tribe has personally owned tames while trying to export another players tame. ASB has tried to optimize the process of importing creatures, but I strongly recommend joining us on Discord for further assistance as many of us are more active there than on GitHub.
