### ISSUE TITLE
OCR compatibility for console

### ISSUE THREAD

**Issue by SlimyPython** [cadon/ARKStatsExtractor#717]
Are you able to use OCR on the console
Console: Xbox One S

**Comment by kohonac** [comment]
as far as i know the only way to use it is to take a screen shot then somehow move it to a PC that is running ASB. ASB is a windows only application

**Comment by SlimyPython** [comment]
What is ASB

**Comment by VolatilePulse** [comment]
ASB (Ark Smart Breeding) is this program. No programs currently exist for Xbox that can work side by side with a game. You have the option of uploading screenshots from Xbox and using ASB to extract the information while using OCR, but it's usually easier to just manually enter creatures.

**Comment by SlimyPython** [comment]
thanks
