### ISSUE TITLE
Griffin not extracting health properly

### ISSUE THREAD

**Issue by Emilie217** [cadon/ARKStatsExtractor#718]
![bugged griffin](https://user-images.githubusercontent.com/8075455/41492508-803932dc-70cd-11e8-8581-6acb3cac921d.png)

Unofficial server with times 5 multipliers for taming speed.
I put 1 point in health to see if it would unbug it.  It seems that the issue is the torpor.  The griffin tamed at 208 (140 lvl wild) but the app says 207.

Btw, it would be REALLY cool if the app would simply use the closest 'valid' value to force the creature into the library.  Most of the time when it bugs out like this I don't really care about the bugged stat.  However, the other stats I need for breeding so it would be cool to still be able to put it in the library.

thanks.

**Comment by VolatilePulse** [comment]
I'm unable to extract it using official stat multipliers. Are you playing on Steam? If so, can you provide the creature's export file? Also, do you have access to the game.ini and/or gameusersettings.ini files?

As far as ASB trying to guess the stat levels, that can't happen as the number of mathematical calculations very strongly rely on accurate values and levels. It sounds like you've been struggling with extractions for a while though. Has it always been with griffins, or does it vary? Also, a level 140 should come out as 207. It can only come out as 208 when it is force tamed. How did you tame this one? Does your server offer any mods?

**Comment by Emilie217** [comment]
Yes I'm playing on steam.  Not sure what is the creature's export file.  
Server side, here are the settings (well the relevant ones) : 

DifficultyOffset=1.000000
OverrideOfficialDifficulty=5.0
XPMultiplier=5.000000
TamingSpeedMultiplier=5.000000

MatingIntervalMultiplier=0.20
EggHatchSpeedMultiplier=5.0
BabyMatureSpeedMultiplier=5.0

The only mod I use that override the griffin is this one : https://steamcommunity.com/sharedfiles/filedetails/?id=1134797219

It's weird that it can't guess.  Can you point me to the class that does the calculation?  I'll take a look.
Will be easier to understand via code than words :p

A 140 will come out at 208 if you tame with mutton at times x5
You can check on dododex : http://www.dododex.com/taming/griffin/140?taming=5

And yeah, I often have issues with extractions.  It's mostly on griffins and wyverns.  It's rare that it happens on tamed creatures though.  It's mostly when they're bred.

**Comment by Emilie217** [comment]
I didn't type in anything.  I simply used the auto-extraction.   I checked the values multiple times and they are correct.

**Comment by cadon** [comment]
Can you post a screenshot of Smart Breeding with the entered values and the settings-window with the stat-multipliers?

**Comment by Emilie217** [comment]
Here you go :)

![griffinabs](https://user-images.githubusercontent.com/8075455/41500105-073849bc-715a-11e8-8f49-93891a74d3d3.png)

These I didn't change except for the taming multipliers and breeding intervals and such.
![abssettings](https://user-images.githubusercontent.com/8075455/41500106-0ab55c60-715a-11e8-8a2e-c8b6f3455084.png)

**Comment by cadon** [comment]
The version you're using seems to be very outdated. Try the latest version here: https://github.com/cadon/ARKStatsExtractor/releases/latest

**Comment by Emilie217** [comment]
Yay, it works!

Strange as the first thing I did is going to menu->?->Check for updates and it didn't detect any :/

thank you very much for your help!
I feel silly now...

**Comment by cadon** [comment]
Nice!
There was a change in the encryption of github for downloading files some months ago. Unfortunately this caused the "Check for Updates"-function to not longer work. It's working now, but all the old versions won't show that there are updates available, because they cannot check anymore.
