### ISSUE TITLE
Ankylo MS changed

### ISSUE THREAD

**Issue by jayr0flmc** [cadon/ARKStatsExtractor#72]
They have changed the movementspeed-value of ankylo.
Seems to be now 225% fixed.
Can't add ANY of my ankos into the library just because of this stat. Rest of the stats are all the time fine.

**Comment by cadon** [comment]
Hi, I can't reproduce this. All Ankylos I spawned in get a bonus of 50%, making it 150% for the tamed ones. Can you send a screenshot?

**Comment by jayr0flmc** [comment]
![anko_ms_issues](https://cloud.githubusercontent.com/assets/4201072/16361294/8b8b3b2c-3b8b-11e6-8d67-3918030d2233.png)

**Comment by cadon** [comment]
Is that an official server? If not, it could be the admin changed some multipliers.

**Comment by jayr0flmc** [comment]
Its unoffical and its default multiplier values. Me the admin. ;)

**Comment by cadon** [comment]
I hope it's resolved in the meantime, if not, just reopen this issue.
