### ISSUE TITLE
Pedigree Cross Species Lines

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#721]
Oddly, importing fresh copies of all my dinos is showing anky's as parents to ovi's, etc.  Not sure why.

**Comment by Worldgate** [comment]
In case you want to see.

https://drive.google.com/file/d/1xSSMpqn3AF3bIe4VuE9faxTHkFGA5sOc/view?usp=sharing

**Comment by cadon** [comment]
Hi, thanks for the report and the library file. Do you still have access to creatures and can upload the export-file of them? E.g. `Aberrant Ovis [07] F01` (Aberrant Ovis) and the "parent" `Sprinter` (Anky).

**Comment by Worldgate** [comment]
[Dino Data]
DinoID1=146339995
DinoID2=144512626
DinoClass=/Game/PrimalEarth/Dinos/Sheep/Sheep_Character_BP_Aberrant.Sheep_Character_BP_Aberrant_C
DinoNameTag=Sheep
bIsFemale=True
bNeutered=False
TamerString=Paragon
TamedName=Aberrant Ovis [07] F01
ImprinterName=
RandomMutationsMale=0
RandomMutationsFemale=0
BabyAge=1.000000
CharacterLevel=48
DinoImprintingQuality=0.000000

[Colorization]
ColorSet[0]=(R=0.480000,G=0.310437,B=0.231047,A=1.000000)
ColorSet[1]=(R=0.300000,G=0.240000,B=0.180000,A=0.000000)
ColorSet[2]=(R=1.000000,G=0.750000,B=0.500000,A=0.000000)
ColorSet[3]=(R=0.635000,G=0.393327,B=0.301625,A=1.000000)
ColorSet[4]=(R=0.825000,G=0.704920,B=0.668250,A=1.000000)
ColorSet[5]=(R=0.200000,G=0.200000,B=0.200000,A=0.000000)

[Max Character Status Values]
Health=385.904968
Stamina=100.000000
Torpidity=116.099998
Oxygen=180.000000
food=1379.999146
Water=100.000000
Temperature=0.000000
Weight=93.599998
Melee Damage=0.340639
Movement Speed=0.000000
Fortitude=0.000000
Crafting Skill=0.000000

[Dino Ancestry]
DinoAncestorsCount=0
DinoAncestorsMale=0

**Comment by Worldgate** [comment]
I've started keeping copies of all the xml files in case something bad happens, here they are.

https://drive.google.com/open?id=11-WWdkX5omphgTpoAnLoPTZI0iqt5SOp

**Comment by cadon** [comment]
Uh, so the Aberrant Ovis doesn't list any parents? Then probably the parent-information is not cleared at some point, and all imported creatures without parents get the previously parents assigned. Thanks for all the files, that helped a lot!

**Comment by Worldgate** [comment]
All of the aberration ovi's are wild tames, i never bred them cause most are junk. :)

**Comment by cadon** [comment]
The parent assigning bug was resolved some time ago.
