### ISSUE TITLE
More creature images?

### ISSUE THREAD

**Issue by Randomette** [cadon/ARKStatsExtractor#722]
I would love if more species got images cause I quite enjoy being able to see what a dino looks like. If you could also add something that would allow you to custom generate a dinosaur image that would be amazing :o (but totally unnecessary). I also have experience in photoshop and SAI if you would like some help with the task of actually creating the pngs you use to accomplish that :)

**Comment by coldino** [comment]
It's a bit of a big job, which needs to be done with some precision.
I posted [a guide on the wiki](https://github.com/cadon/ARKStatsExtractor/wiki/Creating-New-Images) for using GIMP to do it, but I'm sure the same could be accomplished in any other package.

If you join the Discord we'll be happy to guide you.

**Comment by Worldgate** [comment]
It's too bad we couldnt just extract the model from the ark files and display them.  Maybe someone smarter than me could make it work. :D

**Comment by coldino** [comment]
Unfortunately that would involve adding a renderer to the app, which would not be sensible.

**Comment by Randomette** [comment]
sure, where can I find a link for the discord? :)
