### ISSUE TITLE
Breeding Plan Bug

### ISSUE THREAD

**Issue by arathein** [cadon/ARKStatsExtractor#723]
Before I could use the show best breeders function and set the # of allowed mutations to 0 to exclude dinos with mutations (Trying to combine clean stats).
For some reason with the most recent version that is no longer working.
Even if I deselect Mutated creatures from the view it still shows them in the plan.

![image](https://user-images.githubusercontent.com/28239481/41699634-5d5f9ab4-74ea-11e8-8abb-b1f8f3c76c8d.png)

**Comment by cadon** [comment]
Thanks for the report. I fixed that in an unversioned reupload of 0.28.6. You have to redownload the zip for that.
