### ISSUE TITLE
Library Colours?

### ISSUE THREAD

**Issue by Skishcat** [cadon/ARKStatsExtractor#726]
More of a question than an issue, sorry.
In my library, there are names of dinos that have different background colours. I presume that no background means they're no good for breeding, and green is good. But I've recently had an addition that has a yellow/orange colour. What does that mean?

**Comment by VolatilePulse** [comment]
Questions are always good. Hopefully it will answer someone else's question in the future.

A colorless background of a creature in the library view simply means that, with the filters you currently have applied, that creature has 0 top stats. A stat is considered a top stat when that creature has the highest number of levels in it. A green background means that creature has one or more top stats (these are typically what you breed together). And a gold (or yellow) background means this creature has all top stats. A gold creature means the only way to get better than it is to farm more wild creatures or getting a mutation. If you have a gold creature, these are the only things you want to mate.

Again, top stats are only considered depending on what stats you have selected in the library view (you can find this in the bottom left box of the library view).

**Comment by Skishcat** [comment]
Awesome! Thanks so much for that.

**Comment by cadon** [comment]
Also see https://github.com/cadon/ARKStatsExtractor/wiki/Library
