### ISSUE TITLE
Breeding plan

### ISSUE THREAD

**Issue by CaileanH** [cadon/ARKStatsExtractor#727]
Ur program is very good designed but i have 1 question , 

My breedingplan doesnt work it says something with tag selector but i dont know what to do,I have 1 male and 1 female in the library so thats not the problem.

Screenshots of my error message: https://gyazo.com/ea6a87c0263d297588e1330f47560122

**Comment by kohonac** [comment]
could you post a screenshot of the library for the rex's please

**Comment by CaileanH** [comment]
sure i can!

https://gyazo.com/e16b1f7dea53dd50e454055c04d3a765

**Comment by VolatilePulse** [comment]
The default behavior of ASB is to ignore any creatures that are growing or have a Mating cool down (previously mated female). If you look at your library after ignoring the mates on cool down, all you have left are females and therefore have no valid Mating pairs.

You can select all of the creatures with a cool down, right click, and remove the cool down. I'm sorry I'm not at my computer right now to give you the exact wording.

**Comment by CaileanH** [comment]
can u maybe give me the exact wording ? because i cant find it . thanks for the help already !

**Comment by kohonac** [comment]
in the library right click then click where i highlighted. there is a column labeled "cooldown/growing" that all your male rexes seem to have. 
![image](https://user-images.githubusercontent.com/3374605/42001208-1e96ae8e-7a18-11e8-944f-e524f8bba17f.png)

**Comment by CaileanH** [comment]
thanks alot!
