### ISSUE TITLE
Bulb dog charge capacity stat issue

### ISSUE THREAD

**Issue by Jiburley** [cadon/ARKStatsExtractor#729]
Official server, 36 point bred bulb dog charge capacity is 1064.1.
Extractor currently requires 1064.
![20180630150509_1](https://user-images.githubusercontent.com/40709802/42121734-bc21ca56-7c77-11e8-95ff-2cda8065093f.jpg)

**Comment by VolatilePulse** [comment]
I can verify. Appears to be an issue with the extractor rounding "1064.05" improperly. Screenshots attached.

![image](https://user-images.githubusercontent.com/6995232/42121863-409aeb00-7c05-11e8-842b-543f3442e5d1.png)
![image](https://user-images.githubusercontent.com/6995232/42121865-45f520b6-7c05-11e8-82a3-6c4d51ec0a69.png)

**Comment by cadon** [comment]
Works now.
