### ISSUE TITLE
Editing a Tame in the Library and changing the Species wipes its name/owner etc.

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#732]
With the problem of extracting data from the Map and importing Tek Rex's, I thought I would edit them and give them the correct Species name, only problem is that removes the creatures name, Owner, Tribe and the server it was from.

Not only that, but it then wants to add it to the library rather than save it.

**Comment by cadon** [comment]
Species can be edited by selecting creatures in the library and then pressing F3, that will leave the other fields.

**Comment by cyberangel67** [comment]
I was actually talking about the F2 (Edit) and as this was almost 2 years ago, this issue seems to be fixed now any way!
