### ISSUE TITLE
Mutations export from ini file

### ISSUE THREAD

**Issue by SpiritOffice** [cadon/ARKStatsExtractor#733]
There is a problem with export mutations values from ini file using 0.28.6.1 version.
Test case data in ini file:
RandomMutationsMale=5
RandomMutationsFemale=7

After importing values you can see in Extractor:
Mutations Female: 0, Male: 5
But on Mouse Down Event on "Add new to library" both values are zeroed.

**Comment by VolatilePulse** [comment]
Sorry for the delayed response. Have you already imported both the mother and the father into ASB? Can you provide all 3 export files? If you could provide the library file as well, that would be really helpful.

I'll wait for your reply before I speculate on a potential issue first.

**Comment by SpiritOffice** [comment]
[dodo_test.zip](https://github.com/cadon/ARKStatsExtractor/files/2178035/dodo_test.zip)
Sorry for a bit late answer. I can't upload that data from the first message. But i made a new server with new clean data. The problem persists.
I made a whole family 11 dodos and some of them got mutations (all ini files included).
Then i tried to import them and still can see no mutations in program.
I also had to click "Last Export" every time twice, because of wrong colors at first click.
No Mother/Father has been recognized either.
Uploaded zip file has all 11 ini files and library xml file.

**Comment by SpiritOffice** [comment]
[dodos.zip](https://github.com/cadon/ARKStatsExtractor/files/2178111/dodos.zip)
Sorry again.
After i wrote my post, i had to rewrite it all over again. I just found a bug in ARK export function! If you do not open the Ancestors window **before** you make "export dino", the whole Ancestors info (inclusive mutations) will be stripped from ini file!
So i just reexported the whole thing and imported in program again.
This time i used "import all creatures in default folder" function. This time Mother/Father are recognized correctly, but not at Import, but only on mouse down event on "Add new to Library".
Mutations are still zeroed.

My old post:
> Sorry for a bit late answer. I can't upload that data from the first message. But i made a new server with new clean data. The problem persists.
I made a whole family 11 dodos and some of them got mutations (all ini files included).
Then i tried to import them and still can see no mutations in program.
I also had to click "Last Export" every time twice, because of wrong colors at first click.
No Mother/Father has been recognized either.
Uploaded zip file has all 11 ini files and library xml file.

**Comment by VolatilePulse** [comment]
As of right now, we have identified an issue with the mutation counters improperly importing. Until the developer returns from his vacation and can issue a fix, the best you can do is manually updating the creature by hand. This is tedious. Instead, you can keep copies of all of your export files until the next update and export them all again.

As far as Ark is cpncerned, this isn't a bug but an ill side effect from intentional design. Basically you need to "download" parental data from the servers. Opening the ancestors tab is a quick hack to fix that one.

**Comment by cadon** [comment]
Thanks for the report, this will be fixed in the next release.
