### ISSUE TITLE
Strange Problems with Ark SmartBreeding

### ISSUE THREAD

**Issue by Sayuchan01** [cadon/ARKStatsExtractor#736]
Story: I downloaded Ark SmartBreeding and together with my Server Admin i typed in the Multiplier. I tried it first on my Rexes, but i get everytime a Error with Torpo and the Extraction failed.

So i thought maybe he changed that stuff since i tamed them. We tamed a Tek Rex and i inserted the Data and it worked first. After some time i updated the extracted fiel (i use Export Dino funktion) and try to extract it again. It wasnt working again. I tamed Dodos and Equus as test but i get the Torpo error again.

The Kids of Rexy and Rosaline produce also errors.

What i did: Checked the stats, Checked about five times the multiplier with my Admin (the only thing we could not find was max wild level etc), tamed other Creatures and tried that programm on them when i was about to tame them and when i tamed them.

https://ibb.co/c4J2bo

https://ibb.co/hjcH98

https://ibb.co/hm5R2T

https://ibb.co/gjkhbo

https://ibb.co/c2gc98

https://ibb.co/mBuJhT

All checked with server, we only couldnt find Max wild level, Max tamed levelups, Max Graph level, Max Total level.

The server got restarted 2 times.

**Comment by Sayuchan01** [comment]
Admin sended me the script:
[/script/shootergame.shootergamemode]
bPvEDisableFriendlyFire=true
bDisableStructurePlacementCollision=true
MatingIntervalMultiplier=0.3
EggHatchSpeedMultiplier=10
BabyMatureSpeedMultiplier=10
BabyCuddleIntervalMultiplier=0.1
PerLevelStatsMultiplier_Player[0]=5
PerLevelStatsMultiplier_Player[1]=5
PerLevelStatsMultiplier_Player[2]=5
PerLevelStatsMultiplier_Player[3]=5
PerLevelStatsMultiplier_Player[4]=5
PerLevelStatsMultiplier_Player[5]=5
PerLevelStatsMultiplier_Player[6]=5
PerLevelStatsMultiplier_Player[7]=5
PerLevelStatsMultiplier_Player[8]=5
PerLevelStatsMultiplier_Player[9]=5
PerLevelStatsMultiplier_Player[10]=5
PerLevelStatsMultiplier_Player[11]=5
PerLevelStatsMultiplier_DinoTamed[0]=2
PerLevelStatsMultiplier_DinoTamed[1]=2
PerLevelStatsMultiplier_DinoTamed[2]=2
PerLevelStatsMultiplier_DinoTamed[3]=2
PerLevelStatsMultiplier_DinoTamed[4]=2
PerLevelStatsMultiplier_DinoTamed[5]=2
PerLevelStatsMultiplier_DinoTamed[6]=2
PerLevelStatsMultiplier_DinoTamed[7]=2
PerLevelStatsMultiplier_DinoTamed[8]=2
PerLevelStatsMultiplier_DinoTamed[9]=2
PerLevelStatsMultiplier_DinoTamed[10]=2
PerLevelStatsMultiplier_DinoTamed[11]=2
PerLevelStatsMultiplier_DinoWild[0]=3
PerLevelStatsMultiplier_DinoWild[1]=3
PerLevelStatsMultiplier_DinoWild[2]=3
PerLevelStatsMultiplier_DinoWild[3]=3
PerLevelStatsMultiplier_DinoWild[4]=3
PerLevelStatsMultiplier_DinoWild[5]=3
PerLevelStatsMultiplier_DinoWild[6]=3
PerLevelStatsMultiplier_DinoWild[7]=3
PerLevelStatsMultiplier_DinoWild[8]=3
PerLevelStatsMultiplier_DinoWild[9]=3
PerLevelStatsMultiplier_DinoWild[10]=3
PerLevelStatsMultiplier_DinoWild[11]=3

[/Script/ShooterGame.ShooterGameUserSettings]
MasterAudioVolume=1.000000
MusicAudioVolume=1.000000
SFXAudioVolume=1.000000
CameraShakeScale=1.000000
bFirstPersonRiding=False
bThirdPersonPlayer=False
bShowStatusNotificationMessages=True
TrueSkyQuality=0.270000
FOVMultiplier=1.000000
GroundClutterDensity=1.000000
bFilmGrain=False
bMotionBlur=True
bUseDFAO=True
bUseSSAO=True
bShowChatBox=True
bCameraViewBob=True
bInvertLookY=False
bFloatingNames=True
bChatBubbles=True
bHideServerInfo=False
bJoinNotifications=False
bCraftablesShowAllItems=True
LookLeftRightSensitivity=1.000000
LookUpDownSensitivity=1.000000
GraphicsQuality=2
ActiveLingeringWorldTiles=10
LastServerSearchType=0
LastServerSearchHideFull=False
LastServerSearchProtected=False
bUseVSync=False
ResolutionSizeX=1280
ResolutionSizeY=720
LastUserConfirmedResolutionSizeX=1280
LastUserConfirmedResolutionSizeY=720
WindowPosX=-1
WindowPosY=-1
bUseDesktopResolutionForFullscreen=False
FullscreenMode=2
LastConfirmedFullscreenMode=2
Version=5

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=3
sg.ShadowQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=3
sg.EffectsQuality=3
sg.TrueSkyQuality=3
sg.GroundClutterQuality=3
sg.IBLQuality=1
sg.HeightFieldShadowQuality=3
ShowMapPlayerLocation=True
ServerHardcore=False
GlobalVoiceChat=False
ProximityChat=False
NoTributeDownloads=False
AllowThirdPersonPlayer=True
AlwaysNotifyPlayerLeft=False
DontAlwaysNotifyPlayerJoined=True
ServerPVE=True
ServerCrosshair=True
ServerForceNoHUD=False
TamingSpeedMultiplier=5
HarvestAmountMultiplier=5
PlayerCharacterWaterDrainMultiplier=0.5
PlayerCharacterFoodDrainMultiplier=0.5
PvEStructureDecayDestructionPeriod=0
NightTimeSpeedScale=0.93
DayTimeSpeedScale=1.04
TamedDinoDamageMultiplier=1
TamedDinoResistanceMultiplier=1
XPMultiplier=2
DisableStructureDecayPvE=True
AllowFlyerCarryPvE=True
MaxStructuresInRange=1300
PvPStructureDecay=true
DisableDinoDecayPvE=true
PvEDinoDecayPeriodMultiplier=1.0
PerPlatformMaxStructuresMultiplier=1.00
AdminLogging=false
OverrideStructurePlatformPrevention=True
PreventOfflinePvP=True
AllowAnyoneBabyImprintCuddle=True
AutoDestroyDecayedDinos=False
PreventTribeAlliances=False
RCONEnabled=True
RCONPort=32330
PreventOfflinePvPInterval=800.000000
TheMaxStructuresInRange=10500.000000
OxygenSwimSpeedStatMultiplier=1.000000
StructurePreventResourceRadiusMultiplier=1.000000
TribeNameChangeCooldown=15.000000
AllowHideDamageSourceFromLogs=True
RaidDinoCharacterFoodDrainMultiplier=1.000000
KickIdlePlayersPeriod=3600.000000
AutoSavePeriodMinutes=30.000000
ListenServerTetherDistanceMultiplier=1.000000
MaxTamedDinos=5000.000000
RCONServerGameLogBuffer=600.000000
ShowFloatingDamageText=True
NonPermanentDiseases=True
AllowMultipleAttachedC4=True
AllowFlyingStaminaRecovery=True
AllowHitMarkers=True
FastDecayUnsnappedCoreStructures=False
DisableImprintDinoBuff=False
PvPDinoDecay=True
OnlyAutoDestroyCoreStructures=True
ClampItemSpoilingTimes=False
AllowRaidDinoFeeding=True
EnableExtraStructurePreventionVolumes=True
PreventSpawnAnimations=False
CrossARKAllowForeignDinoDownloads=False
PreventDiseases=False
TribeLogDestroyedEnemyStructures=False
PvEAllowStructuresAtSupplyDrops=False
UseOptimizedHarvestingHealth=False
DestroyUnconnectedWaterPipes=False
PreventDownloadSurvivors=False
PreventDownloadItems=False
PreventDownloadDinos=False
PreventUploadSurvivors=False
PreventUploadItems=False
PreventUploadDinos=False
AllowCrateSpawnsOnTopOfStructures=False

[MessageOfTheDay]
Message=Welcome to Scuba's ARK! :D
<RichColor Color=1,0.1,0.1>Red Text</>!
Duration=20

[SessionSettings]
SessionName=Scuba's ARK

[/Script/Engine.GameSession]
MaxPlayers=10

**Comment by VolatilePulse** [comment]
Have not had a chance to review everything yet, but the first thing that sticks out to me is your server admin has the torpor multipliers set. Ark does not support anything other than 1 for torpor and in turn reverts to. Try changing the torpor multipliers to 1.0 and see if that fixes it. If not, I'll get to it as soon as I can.

**Comment by Sayuchan01** [comment]
A big thank you, we didnt know that. Now its working proberly^^
