### ISSUE TITLE
Server settings

### ISSUE THREAD

**Issue by TicWE** [cadon/ARKStatsExtractor#737]
Would it be possible to define the server settings from a dino ? Would be amazing

The settings say 
PerLevelStatsMultiplier_DinoTamed[7]=1.5
PerLevelStatsMultiplier_DinoTamed[9]=2.5

But I can't get it right

**Comment by cadon** [comment]
There are too many possible combinations, but often it can be guessed by using common values. Can you post a screenshot of a creature with no domesticated levels, and a screenshot of the same creature with exactly one level in each stat? A low-level dodo would be sufficient.

**Comment by TicWE** [comment]
![2018-07-11 14_50_52-window](https://user-images.githubusercontent.com/29504602/42572626-22d97776-851a-11e8-8451-5c2c9b35abce.png)
![2018-07-11 14_13_54-window](https://user-images.githubusercontent.com/29504602/42572627-22f75ed0-851a-11e8-8584-2dbffc3c9d9b.png)

**Comment by TicWE** [comment]
Here's the settings I am using and the result I am getting : 
10x Taming speed
10x Experience gain
10x Gathering/Harvesting

Breeding Settings:
MatingIntervalMultiplier=0.10
EggHatchSpeedMultiplier=75
BabyMatureSpeedMultiplier=50
BabyFoodConsumptionSpeedMultiplier=2.0
BabyImprintingStatScaleMultiplier=2.15
BabyCuddleIntervalMultiplier=0.040
BabyCuddleGracePeriodMultiplier=1.1
BabyCuddleLoseImprintQualitySpeedMultiplier=1.1

Dino stat modifiers:
PerLevelStatsMultiplier_DinoTamed[7]=1.5
PerLevelStatsMultiplier_DinoTamed[9]=2.5

![2018-07-11 15_14_00-window](https://user-images.githubusercontent.com/29504602/42573754-433f9678-851d-11e8-9943-e9491587e302.png)
![2018-07-11 15_13_45-window](https://user-images.githubusercontent.com/29504602/42573755-435e8678-851d-11e8-94ee-2b12fbb6047d.png)

**Comment by TicWE** [comment]
I'd like you to confirm these settings, but they seem okay to me. But now I can't get it working correctly for my bred aberrant spinos :/

**Comment by cadon** [comment]
Hi, sorry for the late reply. The multipliers look good. There was an issue with aberrant species which should be resolved by now. If you still have issues, feel free to reopen this issue.
