### ISSUE TITLE
One Drive - Sex deleted from majority of dinos

### ISSUE THREAD

**Issue by kf4rtg** [cadon/ARKStatsExtractor#738]
Been sharing a library via OneDrive, ran into an issue several days ago where when my girlfriend added a dino to our library, suddenly the sex of most of the dinos (but not all?) was switched back to unknown.

Has anyone else experienced this? Will spend some time in the coming week to see if we can reproduce the issue.

**Comment by VolatilePulse** [comment]
Sorry to hear about that! This is the first I've heard of this specific situation, but may be related to potentially different versions of ASB being used on the same file, effectively corrupting it. There is also a possibility of some accidentally selecting multiple creatures at once and attempting to change one creatures sex (or other attribute) and in turn changing all of them through right clicking and selecting "Edit All Selected...". Is there any specific order to what creatures were affected? Maybe all from a specific player, tribe, species, etc.?

Obviously, the normal recommendation is to make sure you have backups enabled, but I understand the headache either way and hope you didn't lose too much time.

**Comment by kf4rtg** [comment]
I was actually just adding to my post that I have just noticed that I have both a Gender and a Sex field... When looking at a different file we used to use several months ago from a different server, the only field was Gender

**Comment by kf4rtg** [comment]
I am running through my recycle bin on one drive, to try to determine exactly when this happened.

I do know we are running on the same version of ASB because the app gets opened from onedrive as well, that way we only need to update it once.

Is there any other helpful information I might provide?

**Comment by kf4rtg** [comment]
I have noticed that on the 11th, The sex field dropped off my XML completely on one of the backups, then the third backup, it was back again.
Backup 1:
    <Creature>
      <species>Carnotaurus</species>
      <name>Betch{Carnotaurus)</name>
      <gender>Female</gender>
      <sex>Female</sex>
      <status>Available</status>
      <levelsWild>
        <int>24</int>
        <int>34</int>
        <int>30</int>
        <int>23</int>
        <int>30</int>
        <int>28</int>
        <int>30</int>
        <int>199</int>
      </levelsWild>
Backup 2
    <Creature>
      <species>Carnotaurus</species>
      <name>Betch{Carnotaurus)</name>
      <gender>Female</gender>
      <status>Available</status>
      <levelsWild>
        <int>24</int>
        <int>34</int>
        <int>30</int>
        <int>23</int>
        <int>30</int>
        <int>28</int>
        <int>30</int>
        <int>199</int>
      </levelsWild>
Backup 3

    <Creature>
      <species>Carnotaurus</species>
      <name>Betch{Carnotaurus)</name>
      <gender>Female</gender>
      <sex>Female</sex>
      <status>Available</status>
      <levelsWild>
        <int>24</int>
        <int>34</int>
        <int>30</int>
        <int>23</int>
        <int>30</int>
        <int>28</int>
        <int>30</int>
        <int>199</int>
      </levelsWild>

**Comment by cadon** [comment]
The gender-field was the first field. For some months I added a sex-field and if that is unknown, the info of the gender-field will be copied to the sex-field. The current version does only use the sex-field, the gender-field is only there for backwards-compatibility. I intend to remove the gender-field soon after having both fields for some months now.

The only reason I can think of that the sex-field was removed (and then possibly that info was lost) is, if the save-file was opened by a very (some months) old version, that didn't use the sex-field yet.

**Comment by kf4rtg** [comment]
Thank you for your quick response. The exe file is included in the shared folder with the library, so I don't see how we would have been able to open the library with a different version. I will check out my girlfriend's computer and see if somehow she has another version of the EXE someplace, but I don't see how.

Do you see any issue with the EXE being shared?

I will see if I can gather any more noteworthy information for you. Thanks!

**Comment by kf4rtg** [comment]
Using compare plugin in Notepad ++ I noticed that the server name disappeared, and the added to library date was basically reset
![image](https://user-images.githubusercontent.com/41274752/42770692-17150356-88f3-11e8-879e-617d266585e0.png)

**Comment by VolatilePulse** [comment]
I'm not 100% how ASB handles unknown library entries or attributes, but what you're discribing coincides with the thought that your library was opened with an older version of ASB and during the auto save period, removed all of the new fields. The developer would be able to provide a bit more insight to see if this holds true with design or is at least a likely scenario.

There is no downside to sharing the executable, and is a good way to make sure everyone is using the same version. I'm not quite sure what happened here, but that leads me to my next point.

Feature Request: Limit library access to version number xx.xx.xx or greater when a new attribute is added. Let's say version number 0.30.0 adds the "Mutation Color" attribute to the library, you could then require all access of that library are made through version 0.30.0. The down side is that you can't do anything about versions prior to when you begin this requirement, but could help further prevent issues like this from arising. This will specifically help users that are library sharing with us be able to continue sharing without concerns of the library becoming corrupt.

**Comment by kf4rtg** [comment]
> Feature Request: Limit library access to version number xx.xx.xx or greater when a new attribute is added. Let's say version number 0.30.0 adds the "Mutation Color" attribute to the library, you could then require all access of that library are made through version 0.30.0. The down side is that you can't do anything about versions prior to when you begin this requirement, but could help further prevent issues like this from arising. This will specifically help users that are library sharing with us be able to continue sharing without concerns of the library becoming corrupt.

To add to this, I might suggest a prompt for a conversion process when an older database is accessed by newer software which would change something in the DB. You could add an attribute/field in the XML for EXEVersion or something like that so that you would know what version of the EXE is using the DB.

**Comment by cadon** [comment]
For now, no field has been removed in the development, gender would be the first. If a version of ASB is used to open a file that contains fields it doesn't know, as soon as the file is saved, these fields are gone. So the only way to delete fields (as far as I can think of) is to open a file with an old version that doesn't know a field and then save it.
The version field is a good idea to prevent data-loss like that.

**Comment by cadon** [comment]
file version for the library is added.
