### ISSUE TITLE
What program do i use to open ArkBreedingStats

### ISSUE THREAD

**Issue by kingkalie** [cadon/ARKStatsExtractor#739]
exactly what the title says

**Comment by kf4rtg** [comment]
If I understand you correctly, ArkBreedingStats is a part of Ark Smart Breeding.
This is where you download the latest release of Ark Smart Breeding
https://github.com/cadon/ARKStatsExtractor/releases/latest

**Comment by kingkalie** [comment]
@kf4rtg i found the problem i downloaded the wrong thing thankyou <3
