### ISSUE TITLE
Can't calc bred Pter food and Melee

### ISSUE THREAD

**Issue by Shrev-OG** [cadon/ARKStatsExtractor#74]
Pter's got 0% imprint bonus but cannot calc food or melee, can't calc food or melee for a few tamed pter's either.
![pterdebug](https://cloud.githubusercontent.com/assets/20213018/16466551/8fc36830-3e11-11e6-8c42-5be533cff41e.png)

**Comment by cadon** [comment]
Hi, the values you try to extract come from a ptera that has still the old values. Some weeks ago the melee-damage was nerfed. Either you used an old screenshot of the stats or the game still needs some time to update the values. One way to force an update is to apply a level to a stat.

You also can change the stat-value in the file stats.txt. Look for the line that contains "Pteranodon" and change the 6th line from there from "15,0.05,0.1,.65,0.4" to "15,0.05,0.1,1,0.4". Remember, this makes the stat-values outdated, so you should probably revert this change after a successful extraction.

**Comment by Shrev-OG** [comment]
Thank you for the info, using this tool on XB1 dino's since it's way better than dododex and wiki calcs since they don't offer the after-tame accuracy.
