### ISSUE TITLE
Show Top Level in Library

### ISSUE THREAD

**Issue by Leyren** [cadon/ARKStatsExtractor#740]
Please add the top level of a certain species, instead of only the percentual difference of the level of a single dino of that species to its top level. Many people I know (and myself included) are interested to know what the level of their final breed will be.

**Comment by cadon** [comment]
Good idea, I'll add this info in the breeding-planner.

**Comment by AndrewLBC** [comment]
A friend of mine is able to right click on 'best possible levels' and export to clipboard to paste in chat, yet it doens't work for me. any idea what i'm doing wrong?

**Comment by cadon** [comment]
@AndrewLBC, that's a bug, will work in the next release. It can't work for your friend yet, probably they clicked on the best outcome at the bottom.

**Comment by AndrewLBC** [comment]
I must have misread it then.  anyways, thanks for all the hard work on this program. It's really come a long way and is an essential tool for just about everyone i know who plays ark.
