### ISSUE TITLE
Is there an issue with extracting? Casteroid extracts and LW states 156, when it is 150 Wild

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#741]
As the subject states, I have added all the server info given to me by the server Admin. At this stage I am sure it is right, but when I entered the values the program is telling me that the Wild Level is 156, when it was actually 150.

![capture](https://user-images.githubusercontent.com/1366816/42986818-709da6ae-8c3a-11e8-9f94-f19692e4e141.PNG)

**Comment by cyberangel67** [comment]
Just entered a 3rd Casteroid, its LW came out at 140. Which is the correct Wild Level it was tamed at.

**Comment by VolatilePulse** [comment]
There is currently no known issue with extracting that species. Can you reenter the creatures stats and send a screenshot of ASB after you have click the Extract Level Distribution button?

**Comment by cyberangel67** [comment]
Listen dude, before I report it here, I have already tried it many times before reporting it.

But as your new here, willing to help, I am not new to this program and have been using it for years. I know how to use it and would appreciate a fix ASAP.

**Comment by VolatilePulse** [comment]
I'm aware you've been using the program for many years, I've attempted to help you many times before. I'm actually a moderator for the program and have spent my spare time helping numerous other users. I'd like to help you get this sorted and get the correct information for the developer so a fix can be issued.

I've been using the program probably as long as you have, have introduced several improvements to the program and have worked very closely with the developer troubleshooting and identifying issues. I'm sorry if you are reluctant to accept the help, but several other users in the community have given up helping you as the only person you will talk to is the developer. He's not always around and is rather busy making fixes.

If you'd prefer that only the developer tries to help you out, you might be waiting for an answer for a while, but I'll be sure to let the other ASB experts know.

**Comment by cyberangel67** [comment]
Dude, nobody has given up helping, where did you get that from!

But there is nothing to help, somewhere, somehow ASB is calculating the LW incorrectly on a lot of Dinos. I just tamed another PT 150 Casteroid and ASB says it was a 177 LW.

The values entered are 100% spot on, so unless you have a fix for it. I would just like to report it as broken. Nothing more, nothing less.

**Comment by VolatilePulse** [comment]
I'm trying to help narrow down the issue, hence why I asked for a screenshot of the extraction. This goes a very long way in identifying the issue. I don't think you entered anything incorrectly, I just would like to evaluate the issue firsthand. As of right now you have given us nothing to work on other than the program isn't working properly. There are a ton of lines that are used to calculate things, and while WL might be shown as being inaccurate, there is very likely a miniscule miscalculation taking place elsewhere. As this isn't a regular occurrence, I'd like to take a look at the numbers behind the scene, but I can't do so when no other information is provided.

**Comment by cyberangel67** [comment]
Are you on drugs or something, I posted an image in my initial report. I made sure to have it selected with the tames stats.

**Comment by cyberangel67** [comment]
Here is images of the 150 tame that ASB says is LW 177, I just noticed that ASB says it is also a tame of 54% TE which is also incorrect. It was actually a PT of 99.8%.

![capture](https://user-images.githubusercontent.com/1366816/43016179-5bc77b64-8c95-11e8-89d7-78d7df419afc.PNG)
![capture1](https://user-images.githubusercontent.com/1366816/43016185-5faa19da-8c95-11e8-82fc-41de563c129f.PNG)

**Comment by cadon** [comment]
Hi, it has probably to do with the damage-stat. When after the extraction the stat is yellow, Smart Breeding found multiple possible level-combinations. After clicking on the yellow stat, select the correct combination with the correct LW and TE.

**Comment by cyberangel67** [comment]
Cadon, but that reduces the stat points.

**Comment by cyberangel67** [comment]
Ok I pulled out the Spy Glass and went through the stats of the actual Tame.

It was not only the Dmg, but it was the speed as well.

Speed should have been 37 and Dmg should have been 28.

If I enter these values normally, like that I get no issue. But if I enter the values as 257.5 (weight) and 170 (speed) I get the above image.

**Comment by cadon** [comment]
Yes, for this castoroides Smart Breeding can only narrow it down to some combinations. You have to click on the yellow stat (damage) and on the right you can choose from the possible level combinations. If you know that the beaver was level 150 in the wild, choose the row that has that. This sets the damage to 28 and the speed to 37, as expected.

**Comment by cyberangel67** [comment]
Yes I am aware that you have to do that, but in the past it was only if there was 2 or more yellow as the green ones where always correct.

**Comment by cadon** [comment]
It can also happen with only one stat, especially melee damage, because that stat-value depends on the taming effectiveness. If you know the wild level of the creature it's often easy to find the correct combination for the melee.

**Comment by cyberangel67** [comment]
how do you find the correct combination with dmg?

**Comment by cadon** [comment]
Unfortunately there is no general rule, that's why Smart Breeding can't do it automatically. If you know the wild level, it's much easier because you can just take the row with the correct level. If there are multiple rows with that level, choose one of them and see if the total level of the creature is correct. If there are other yellow stats, see if you can change them so the total level becomes valid. After some trial and error you can usually find the correct combination.
