### ISSUE TITLE
Entering Pteranadon wont extract

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#742]
Nothing to add except the image shows it won't extract

![capture](https://user-images.githubusercontent.com/1366816/42987810-d1c9c0fe-8c3d-11e8-994b-9183b989c464.PNG)

**Comment by VolatilePulse** [comment]
I'm unable to extract it either. Can you provide a screenshot of the creatures inventory as well as your multipliers in ASB?

**Comment by cyberangel67** [comment]
The settings

![capture](https://user-images.githubusercontent.com/1366816/42994202-bfaf99da-8c50-11e8-88b0-558e82a2529a.PNG)

The Birds Stats are

![ark_ survival evolved 20_07_2018 7_19_28 pm](https://user-images.githubusercontent.com/1366816/42994646-f5e083ba-8c51-11e8-9dcd-a8ab2079ef52.png)

**Comment by cyberangel67** [comment]
And yes, the Class Flyers values have been added

**Comment by cyberangel67** [comment]
i'll have to give it another shot, but I tried that 5 times with ClassicFlyers added and got the same result.

**Comment by cadon** [comment]
This is how it looks for me (the settings like in the screenshot you posted).

![pteranodon](https://user-images.githubusercontent.com/8763269/43044228-cd8ecc44-8da2-11e8-8d89-e8cd12baf504.png)

**Comment by cyberangel67** [comment]
I am still having issues with some flyers, that ptera I was able to get but others I have had major trouble with.

An Argentavis I just tamed has serious issues, I have tried all the ways to import the data and selected the red and yellow sections and there are no options to satisfy this.

The speed has "?" but nothing I can do to change this, the values entered are exactly what the stats of the bird says it is.

![capture](https://user-images.githubusercontent.com/1366816/43118920-8d45ffc0-8f57-11e8-881d-33e3675e6059.PNG)

**Comment by cadon** [comment]
Hi, that's probably an old argentavis. There were some changes in the classicFlyers-mod when the new Argentavis was introduced. Old Argentavis could be converted to a Harpagornis, maybe that was done here. Trying to extract it as a Harpagornis yields a value for Stamina (33 levels), but fails on weight. I'm not entirely sure what's causing this issue, but it's probably related to this changing of the stat-values. Maybe this combination of the two extractions represent the real values:

Argentavis (Lvl 217, TE: 99.9%): HP: 2263.1 (26, 0); St: 3225 (33, 0); Ox: 465 (21, 0); Fo: 10400 (42, 0); We: 608 (26, 0); Dm: 355.1% (39, 0); Sp: 100% (29, 0); To: 8376.5 (216);

**Comment by cyberangel67** [comment]
This is a brand new tame, tamed by me only a few days before I commented here.

I can assure you, that it was not converted nor an Older Argy.

**Comment by cyberangel67** [comment]
I will add that the 5 I tamed in the last week, all have this issue.

**Comment by cadon** [comment]
The current version can extract the previously failed argentavis. Maybe it was a float-precision error, the handling of this was improved in the later version.
