### ISSUE TITLE
Add a "Creature ID" value in library/extractor

### ISSUE THREAD

**Issue by Konys1** [cadon/ARKStatsExtractor#745]
Hey,

As someone playing in a tribe, sometimes dinos I use for breed get renamed by tribemates, so unless I make folder in their inventory (which I don't like to do), I have to extract them again to know who they are, so for now I have to type their ID in "notes" which takes time and is annoying :s 
So I was wondering if it was possible to add a creature ID value while importing a dino in extractor, would be a time saver.
And it would also be useful if someone steals a dino I tamed for myself and renames it.

**Comment by PreshusRoze** [comment]
I do the same thing by notating the creature IDs. And would LOVE for this to be an option!
