### ISSUE TITLE
Value Files Missing

### ISSUE THREAD

**Issue by Granape10** [cadon/ARKStatsExtractor#746]
I downloaded all the files and i was given the error "Values-File 'json/values.json' not found.' I looked on the issue page and saw that i needed to extract all the files and the folders from the zip archive. I did this and got the same error when i tried to open it. Either I didn't understand what you meant by extracting all the files from the zip archive or there is some unknown error.

**Comment by cadon** [comment]
Hi, did you download the release (with an .exe-file and the folder json) or the source-code? For just running the application, you need the release-package.
