### ISSUE TITLE
Library Function

### ISSUE THREAD

**Issue by l3uGsY** [cadon/ARKStatsExtractor#747]
I play on a unofficial server and was wondering if you would offer a Catalogue Only option?  

I can add the dinos while they are still wild, but due to PerLevelStatsMultiplier_DinoTamed[#] being off and certain dinos having adjusted stats, It won't add them to the library.  Even when I import the exported files, it throws up red flags on 3 of the stats. 

Can you offer an option that allow you to still add dinos to the library even though the stats don't add up.  I am aware the functionality for other parts wont work, but it would be nice to still catalogue them using the export/import dino function. 

Thank you.

**Comment by cadon** [comment]
Hi, you just have to set the stat-multipliers to the correct values, then you can import the creatures.
If you just want to add the creatures, you can go to the tester-tab and set all the levels to -1 (unknown) and set the other infos like name, owner etc. before adding them to the library. The tool is not designed to work with that, though, so I recommend to just set the stat-multipliers to get all the functions.
