### ISSUE TITLE
How do i start the program?

### ISSUE THREAD

**Issue by GearHead352** [cadon/ARKStatsExtractor#748]
I do not see any .exe or any batch files to start this program. What am I doing wrong?

**Comment by cadon** [comment]
You probably downloaded the source-code. You want the the release, see https://github.com/cadon/ARKStatsExtractor/releases/latest

**Comment by GearHead352** [comment]
No, I downloaded the release and there is no way to start it.

**Comment by GearHead352** [comment]
You're correct. I had the stats extractor.
