### ISSUE TITLE
Issue with Parasaur Stats

### ISSUE THREAD

**Issue by lovelyg4m3r** [cadon/ARKStatsExtractor#75]
So... I am trying to get a 220 Parasaur breed (Incentive for a color breed on the server) and I noticed today that your tool is definitely miscalculating stats. So my M162 parasaur  tamed out with a 298.1 melee. My girl Peach tamed out to a 280.7 and now its telling me that Peach has 4 more points into melee than M162, which is entirely wrong.  :P Because M162 has about 18 more melee than her. 

http://imgur.com/2v0xRqX

**Comment by cadon** [comment]
Hi, it seems the taming effectiveness of Peach is only 7.6%, which reduces the affiniy-bonus a lot. If you use Peach for breeding, the offspring will have their melee-damage calculated with 100% taming effectiveness and have a lot more.
