### ISSUE TITLE
please ask Wildcard to add mother and father IDs to export dino feature

### ISSUE THREAD

**Issue by JuicyJuuce** [cadon/ARKStatsExtractor#750]
If feature request #745 is implemented then also automatically extracting the mother and father and populating the respective fields would be a _huge_ time saver for mass breeders like myself. Adding a new dino would go from these steps:

1) Exporting dino data (quick)
2) Importing it into ARK Smart Breeding (quick)
3) Auto-generating a name (quick)
4) Picking the mother from a potentially very long list (slow)
5) Doing the same for the father (slow)
6) Hit the Add new to Library button (quick)

To:

1) Exporting dino data (quick)
2) Importing it into ARK Smart Breeding (quick)
3) Auto-generating a name (quick)
4) Hit the Add new to Library button (quick)

However, all this would require the ARK devs to add the ID of the mother and father to the export file. It would be very simple for them to do and would save hardcore breeders a lot of time. Have you considered asking them to add this? I'm sure they would listen considering your tool is so widely used by breeders.

(Also, if they show a willingness to add this feature they might later be open to adding other information to the export file like breeding value stats, taming effectiveness, wild level, etc., as well as fixing the seemingly broken RandomMutationsMale/Female and Dino Ancestry fields. This would remove nearly all extraction errors and ambiguous wild levels that are currently encountered while using the export dino feature.)

What do you think?

**Comment by coldino** [comment]
Actually Ark already does all of this! 

Unfortunately the is a slight bug in Ark that means the extra information about parents and mutations is only exported if you first open the ancestry page of the dino in question before you export it. I guess this cause it to fetch the information from the server.

Of course parental looking only works well when the parents have also been imported, so their internal IDs match.

**Comment by JuicyJuuce** [comment]
Ah, thanks! Exactly what I wanted. Also, it seems that parental looking might work based on just the names as well.

I still think it would be worthwhile to ask Wildcard to export things like the underlying breeding stat values, taming effectiveness, wild level, etc., to address the extraction errors that still happen.
