### ISSUE TITLE
Pattern Editor

### ISSUE THREAD

**Issue by BonesBLADE** [cadon/ARKStatsExtractor#753]
Is there a way to edit the pattern editor page to add my own pattern for names? Thanks.

**Comment by cadon** [comment]
No, all the available patterns are hardcoded, they depend on various sources, so making that editable would be complicated. If you have suggestions for new keywords, I can probably add them easily.

**Comment by BonesBLADE** [comment]
Ok thank you for your response. 
I love the program it is one of the best things I have seen for any game in a long time and so much work is put into it.
This is how I name my animals.
Bronto W-M 1 L719       Which = Wild-Male First one Level 719 at tame
Bronto B-F 2 L634        Which = Bread-Female Second one Level 634 when born
The Values I would need are.
1. Look in the library and see if a Name is used for that species and if so use that. (So the first one of every species I would have to manually add the name but after that it would pick it up and use what I put in for the first creature.)
2. Add W for tamed and B for bred
3.  Look to see how many of that sex of the current species are in the library +1
Thank  you so much if you can do this it would save me so much time as I am taming every species on the map and at least 5 of each.

**Comment by cadon** [comment]
What do you mean exactly with the first one? Should this create `Bronto` in your example? So the keyword would check for the first word in the name of the first added creature of a species and use that?

Regarding the second key, I think it's more intuitive to use `T` for tamed and `B` for bred.
The third will be added like that.

**Comment by BonesBLADE** [comment]
For the first one. Yes. The first added Bronto I would have to manually put the name in there because there is nothing for the program to see. After that every time I added a Bronto it would see the name and use it.
Second Yes I agree I suppose I was being lazy as I have over 350 Dinos but I will re name the from W to T if you can put this in the program.
Thank you so much. When I tame all the species I will send you my data base for you to see if you like or I can send what i have now.

**Comment by BonesBLADE** [comment]
I hope I made sense with my last reply, do you understand what I am saying?
Thanks again for your replies and support with your program, again I think it is one of the best programs around for any sort of game like this.

**Comment by cadon** [comment]
Hi, yes, should be all clear now. I haven't had much time lately for developping and will be not available for another week. I'll do a release later today that has these new keys included, but better make sure to create a backup of the library file before using it, I didn't much testing with the new version.

**Comment by BonesBLADE** [comment]
Thank you so much for your time and effort you have put into this program and especially the request of a single person. If you ever developed a game I would buy it and I think you would be one of the few developers that take pride and have consideration for the people that use your product. Thank you again.
