### ISSUE TITLE
Column reordering possiblities on the Library tab.

### ISSUE THREAD

**Issue by EmkioA** [cadon/ARKStatsExtractor#754]
Hello, 

is there a way to reorder or remove / add column on the Library tab?
If not this is a idea of new feature.

**Comment by cadon** [comment]
Reordering the columns is hard to implement with the current framework. You can hide columns by changing their width to zero (drag the column-header-separators to the new width).

**Comment by EmkioA** [comment]
Hello Cadon, i just dont know how to do a pull request but i have implement the column reordering (it was simple).  
Settings.Designer.cs : Line 85+ (add diplay indexes properties to the settings)
`        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int[] columnDisplayIndexes
        {
            get
            {
                return ((int[])(this["columnDisplayIndexes"]));
            }
            set
            {
                this["columnDisplayIndexes"] = value;
            }
        }`

Form1.Desinger.cs : Line 2227 add this text : (activate the columnreorder property)
`this.listViewLibrary.AllowColumnReorder = true;`

Form1.cs : line 220 add those line (load column-indexes
`            // load column-indexes
            int[] ci = Properties.Settings.Default.columnDisplayIndexes;
            if (ci != null)
            {
                for (int c = 0; c < ci.Length && c < listViewLibrary.Columns.Count; c++)
                    listViewLibrary.Columns[c].DisplayIndex = ci[c];
            }`

Line 1157 (replace between both comments) (Save indexes of column).
`            // save column-widths and indexes
            int[] cw = new int[listViewLibrary.Columns.Count];
            int[] ci = new int[listViewLibrary.Columns.Count];
            for (int c = 0; c < listViewLibrary.Columns.Count; c++)
            {
                cw[c] = listViewLibrary.Columns[c].Width;
                ci[c] = listViewLibrary.Columns[c].DisplayIndex;
            }
            Properties.Settings.Default.columnWidths = cw;
            Properties.Settings.Default.columnDisplayIndexes = ci;


            // save listViewSorting`


Thats it

**Comment by cadon** [comment]
Wow, that's great! I never realized there's an option I just have to enable for reordering the columns. Thank you very much for that code. I have implemented it and it will be in the next release.

**Comment by cadon** [comment]
Regarding pull requests in general: You have to fork the project, add your changes with a commit to your fork, then under pull-requests you can ask your code to be included in the initial project.

**Comment by EmkioA** [comment]
Thank you verry much :)  I love your work and happy to help!
