### ISSUE TITLE
Export colors only

### ISSUE THREAD

**Issue by EmkioA** [cadon/ARKStatsExtractor#755]
It could be cool to have a way to export the colors informations.  
Add it to the export to excel or ad a way to export ID/Name/Colors

New feature request.

Thank you

**Comment by cadon** [comment]
I'll add this to the next release.
What is more useful, exporting the color-id, i.e. if the region is Red, the field will contain `1`, or for WolfFur `40` (see https://ark.gamepedia.com/Color_IDs), the color-names (i.e. `Red`, `WolfFur`), both (e.g. `WolfFur (40)`, the Hex color-code (`#c3b39f`), the rgb-values, or a combination of these?
