### ISSUE TITLE
Disabling Dino stats in Overlay

### ISSUE THREAD

**Issue by Reachground** [cadon/ARKStatsExtractor#757]
Hey!

First of all, let me thank you from the bottom of my heart for making ASB. It's an amazing tool that I've used for as long as I've played.

I've recently started to use the overlay timer for torpor/starving/incubation. The problem is that whenever I import a dino, the stats are displayed on my screen as well. I've looked everywhere but can't for the life of me find where to disable it. My solution now is to close ASB or disable the overlay altogether.

It's probably a simple thing that I've just overlooked.

Thanks

**Comment by cadon** [comment]
Hi, you mean after you import a creature with the "import exported" method in ASB (or clicking "Last Imort"), the stats are displayed in the overlay?

**Comment by Reachground** [comment]
Yes! Exactly.

This is how it looks:
![overlay asb](https://user-images.githubusercontent.com/10996358/44530151-10dac480-a6ee-11e8-9993-79053de25603.PNG)

Now I understand that it's a feature and has its uses, but most of the time I don't use it and the placement is annoying since it's close to the center of the screen.

**Comment by cadon** [comment]
I see. Unfortunately I won't be able to fix this for another week now, but as a workaround you should be able to disable the displayed levels by going to Settings -> General -> Overlay -> and uncheck "Automatically extract inventory levels …". I hope at least. I'll look into this later for a real fix.

**Comment by Reachground** [comment]
Oh, so it is a bug? I really thought it was something I missed.

That workaround is perfect. Thanks a lot.

**Comment by cadon** [comment]
Yes, the displayed levels should only be visible if you are in an inventory of a creature and have enabled that option.

**Comment by cadon** [comment]
The bug is fixed.
