### ISSUE TITLE
Window Resizes Don't Actually Work

### ISSUE THREAD

**Issue by aaron-williamson** [cadon/ARKStatsExtractor#76]
When you open the program and try to resize the window, the external window resizes but the actual contents of the window doesn't resize until you close and re-open the program.

**Comment by aaron-williamson** [comment]
This actually appears to be pretty un-reproducible so I'm closing this issue. Will open a new issue if I can figure out how to reproduce it consistently.

**Comment by cadon** [comment]
I saw that sometimes, too. But as you, I wasn't yet able to reproduce it.
