### ISSUE TITLE
Problem starting program

### ISSUE THREAD

**Issue by xgbxfakie** [cadon/ARKStatsExtractor#766]
When ever i try to start the program i get an error that says
**unhandled exception: configuration system failed to initialize** 
i have tried deleting and reinstalling and that wont fix it anyone have any ideas

**Comment by pedrovitor074** [comment]
yeah i have the same error.

**Comment by xgbxfakie** [comment]
The only way i can fix it is by deleting all the files restarting my computer and then re downloading but that only fixes it for about a day or so

**Comment by VolatilePulse** [comment]
Would strongly recommend returning to a previous version as the 2 most recent versions are having issues with the Creature ID field and couple be preventing the program from launching.

**Comment by VolatilePulse** [comment]
A user on Discord has found a solution to this issue and figured I'd share. The user has switched to a version prior to 0.28.9, but unsure if that's directly related. They deleted the %APPDATA%/Local/ARKBreedingStats directory and were then able to launch the program again without any issues. Be warned this will likely reset any preferences you had like column widths, etc.

**Comment by laurencei** [comment]
The solution posted by @VolatilePulse pulse (Deleing the directory in APPDATA) solve this issue for me (latest release).
