### ISSUE TITLE
Can't extract bred dinos

### ISSUE THREAD

**Issue by Pajonibus** [cadon/ARKStatsExtractor#768]
So, I've joined a new server and been using ASB for wild dinos perfectly, but when it comes to bred dinos they always have most  of the stats in red...
![image](https://user-images.githubusercontent.com/38722696/44956585-987ebb00-aec6-11e8-8c5e-bd73af955fb6.png)

I have the settings my admin provided, which are:

Max Wild Dino Level: 150

10x Taming speed
10x Experience gain
10x Gathering/Harvesting

Breeding Settings:
MatingIntervalMultiplier=0.10
EggHatchSpeedMultiplier=75
BabyMatureSpeedMultiplier=50
BabyFoodConsumptionSpeedMultiplier=2.0
BabyImprintingStatScaleMultiplier=2.15
BabyCuddleIntervalMultiplier=0.040
BabyCuddleGracePeriodMultiplier=1.1
BabyCuddleLoseImprintQualitySpeedMultiplier=1.1

Dino stat modifiers:
PerLevelStatsMultiplier_DinoTamed[7]=1.5
PerLevelStatsMultiplier_DinoTamed[9]=2.5
![image](https://user-images.githubusercontent.com/38722696/44956592-af251200-aec6-11e8-83c6-39a95beaa47e.png)

Here's the export from the screenshot above [Export.zip](https://github.com/cadon/ARKStatsExtractor/files/2343394/Export.zip)

My admin won't share his game.ini so this is all I got, any help would be appreciated.

**Comment by Worldgate** [comment]
Did you run the extractor after you imprinted... or right after birth.

**Comment by Pajonibus** [comment]
Alright I thought I had tried both but because I was using S+ Nanny never tried it at actualy 0% imprinted, now I tried it and it worked, thank you for your time ^^"
