### ISSUE TITLE
Issue With Fresh Tame Pteranodon Food/Melee

### ISSUE THREAD

**Issue by aaron-williamson** [cadon/ARKStatsExtractor#77]
I can't confirm for leveled Pteranodons but immediately after tame the Pteranodon's Food and Melee do not evaluate properly. This applies if you tame a Pteranodon, set all stats and levels correctly, "No restart after tame" selected, and then extract the stats.

**Comment by cyberangel67** [comment]
I can't say I am getting that, but I do notice that it thinks it is a higher level than it thinks it is. Btw the stats shown on the left is exactly what I entered and what the bird tamed out at.
![capture](https://cloud.githubusercontent.com/assets/1366816/16716413/481331b4-473f-11e6-9460-76b908ff878a.PNG)

**Comment by aaron-williamson** [comment]
Here's a screenshot of the pterry I tamed and have been having the issue with. It was a 135 wild Pteranodon tamed with 99.3% efficiency. No levels as you can see the next level only costs 10xp, and the stat extractor can't seem to figure it out. I tried locking/unlocking stats, manually setting the taming effectiveness, toggling no server restart, no luck.
![statserror](https://cloud.githubusercontent.com/assets/9038848/16719168/c14f8876-46e4-11e6-8166-80d095ab57ae.png)

**Comment by cadon** [comment]
The Pteranodon got nerfed recently, so the game sometimes still displays the old values. Try to level up any stat to force a recalculation on the stats and then try again to extract. That often does the trick.

**Comment by cyberangel67** [comment]
Have tried that Cadon, but it still extracts it as a wild 203 and not a Wild 120.
![capture](https://cloud.githubusercontent.com/assets/1366816/16733065/5ec338d0-47c3-11e6-9b7e-2ccad28cb546.PNG)

**Comment by cadon** [comment]
Try it with "Since Taming no Server-Restart", if the wild-level is too high.

**Comment by cyberangel67** [comment]
doesnt work 
![capture](https://cloud.githubusercontent.com/assets/1366816/16890047/713ff962-4b2e-11e6-8310-1fe4f72e33b2.PNG)

**Comment by VolatilePulse** [comment]
You entered the level as 286, your current level is 218.

**Comment by cyberangel67** [comment]
No I did not enter the level as 286, it is what the program decided it was tamed at.

**Comment by VolatilePulse** [comment]
I've been able to extract it with a 120 LW after unlocking some of the domesticated stats. See picture for reference. 
![image](https://cloud.githubusercontent.com/assets/6995232/16893509/42b8863e-4b08-11e6-99dd-1257f229a2fa.png)

**Comment by cyberangel67** [comment]
I think I know what the issue is and it is an issue that is going to annoy a lot of people.

During the nerf, there is a delay before the Console gets that nerf and the program then uses the new values where the console uses the old values.

Maybe as an interim solution move the pre nerf to a temporary stats and have an option for console users to click, maybe messy but will stop people who use this program on console having issues extracting all the time.

**Comment by cyberangel67** [comment]
That delay can be up to a month.

**Comment by cadon** [comment]
Hi, thanks for the note. I changed the update-process of the values.json, so console-users can deny the update of that file easier and added a note about how to handle this issue. An in-build functionality to choose between multiple values-files would be nice, but I don't know if that would be worth the work. Creature changes do happen, but not so often anymore, and with sticking to a values-file for some while until the changes hit the consoles seems to be a practicable solution. BTW I just saw your youtube-video about the tool, very nice 👍

**Comment by cyberangel67** [comment]
Yeah I wasn't sure you would want to go that way of doing it inside the program, but thought you should be aware (if you weren't already) that console users can get the changes much later.

Thanks, was quick video put together to help some people out. While doing this I did notice an issue with imprinting and possible a rounding error, which I think you are probably aware off. There has been times when I manually did the calculation the imprint might have been, lets say 91% and to get the values to work in most cases I had to find the rounding error. In this case 91%, was really 90.8% imprinting.

I was also about to do another video on the imprinting, then you changed it to extract it. Grats, I am sure it will still have the rounding error for boosted servers though.

**Comment by cadon** [comment]
Yes, that rounding error kept me from extracting the values from imprinted creatures, now the tool figures the real imprinting-percentage from the given rounded number. If you happen to know of a creature on a boosted server that cannot be extracted due to a rounding error, let me know.

**Comment by cyberangel67** [comment]
Sure thing, here you go. Imprinting done to 91%, but program calculates 97%

BabyCuddleIntervalMultilper is 0.01

![capture](https://cloud.githubusercontent.com/assets/1366816/21963671/c9ea893e-db92-11e6-8997-355584a7b251.PNG)

**Comment by cadon** [comment]
let's continue in #143 as it's a new issue.
