### ISSUE TITLE
View menu, Show Unavailable Creatures (and others) shows nothing

### ISSUE THREAD

**Issue by b-morgan** [cadon/ARKStatsExtractor#770]
According to the status at the bottom of the window, I have 217 creatures in Library (alive: 199, dead: 14, available: 199, unavailable: 4). In the View menu, I have unchecked all except Unavailable Creatures but on the Library tab, nothing shows. If I add Dead Creatures, nothing shows. 

It appears that Male and Female are the only ones that do work.

With Male and Female checked, unchecking Dead Creatures does remove them.

**Comment by Worldgate** [comment]
Are the names 'Father of XXX' or 'Mother of XXX'?

**Comment by b-morgan** [comment]
I don't know. The entire window is empty. The issue here is that nothing shows in the library tab when Male and Female are not checked. I can't see just dead creatures and I can't see just unavailable creatures.

**Comment by VolatilePulse** [comment]
When you select male and female, all species, and unavailable but uncheck available, still nothing appears?

**Comment by kohonac** [comment]
with both male and female unchecked then of course only non-gendered tames will show i.e. griffins

**Comment by b-morgan** [comment]
Apparently, my words don't seem to be working so I'll try adding some pictures...

![asb_all_checked](https://user-images.githubusercontent.com/1547854/45050810-7a889600-b03f-11e8-8bf0-ba2f345cd900.jpg)

From the picture above you can see all View items checked and a screen's worth of my Library. At the bottom, it shows 217 creatures, 199 alive, 14 dead, and 4 unavailable. I expect the next picture below to show 14 dead +4 unavailable = 18 total but instead, nothing is shown.

![asb_dead_unavailable_checked](https://user-images.githubusercontent.com/1547854/45050827-85432b00-b03f-11e8-8497-57504db39518.jpg)

In the picture below, everything is checked except Dead Creatures and, as expected, Jarvis (Argentavis) disappears from the library shown in the first picture.

![asb_all_except_dead](https://user-images.githubusercontent.com/1547854/45051341-12d34a80-b041-11e8-858e-b8c20240906d.jpg)

I expect each item in the View menu to display or not display the item it represents independently from the other items. The current behavior is wrong, IMO.

**Comment by b-morgan** [comment]
@VolatilePulse I'm not sure what you are asking as there is no "available" to check, but I'm guessing you meant to say "unavailable" both times. That is what led to the discovery of the behavior I'm reporting here, The bottom of the screen says there are 4 unavailable and I wanted to know what they were. I can't find the 4 entries corresponding to the count at the bottom.

**Comment by kohonac** [comment]
unless you have griffins and other non gender tames when you uncheck male and female at the same time you are telling ASB it is not allowed to show either of those so what is left to show for the other options?

**Comment by b-morgan** [comment]
I examined the .xml file that is driving ASB and attached is a .zip of the .xml of 3 of the 4 unavailable Creature entries (not sure why one disappeared). I deleted them from the main .xml file but they returned apparently to satisfy some internal consistency requirements.

[UnavailableOnly.zip](https://github.com/cadon/ARKStatsExtractor/files/2349941/UnavailableOnly.zip)

**Comment by b-morgan** [comment]
The internal consistency requirement is apparently missing parents of bred creatures. The entries are visible on the Pedigree tab. I have not been using ASB from the inception of this server, so some activity was not captured (like the death of parents).

**Comment by cadon** [comment]
The creatures that are not showing are probably placeholder-creatures. They are created automatically if a creature has set some parents which are not present in the library. A placeholder-creature then is created to fill gaps in the pedigree. If a creature later is added that appears to be a placeholder, it will replace the latter. This is important if creatures are imported and later its parents are imported. This system relies on the Ark-Id which currently causes some issues, I hope to get this fixed soon.

Placeholder creatures are not shown in the library, they give no useful info (their levels are unknown). They do appear in the pedigree view.

Regarding the other remark about the filtering, currently all creatures that have a property that can be checked are removed from the display if one of these options is unchecked, i.e. a creature is only shown if all its properties are checked. The other way would be to start with an empty list and add all creatures that have any of the checked properties. If that is more intuitive I can change the behaviour.

Placeholder-creatures shouldn't be counted in the status-bar, though. That will be fixed in the next release.

**Comment by b-morgan** [comment]
Thanks for the explanation!

Rather than just change the behavior, could you add one more option, "And / Or" that would switch between the current behavior ("And") and the behavior I was expecting ("Or")? It is obvious from the comments here that the current behavior makes sense to a lot of people but the "Or" behavior has its place as well (BTW, "And" and "Or" could be something else. It's just the engineer in me that picked them).

Would it make sense to add "Placeholder Creature" with the default being unchecked? While they give no useful information, their presence is useful information (i.e. I might need to go find the parent's real data). Alternatively, add an entry in the status-bar labeled "Placeholder" so we know where to go look for additional information (the "pedigree view"). I believe some of the "Unknown" creatures are marked in library with an "X" after the name. I've been changing them to "dead" when I know that is their status.

**Comment by cadon** [comment]
The feature-request for a more flexible library filter is now located in #821. I'm closing this issue for now.
