### ISSUE TITLE
Breeding-Mode gives different answers

### ISSUE THREAD

**Issue by b-morgan** [cadon/ARKStatsExtractor#772]
After starting the program, if I click on the Breeding Plan tab, the Breeding-Mode radio button is set but  the calculations in the details window are not what I expect. Changing the radio button to another mode and returning to the previously selected mode now shows the expected values.

**Comment by cadon** [comment]
What do you mean with `calculations in the details window`? The `Stat Weighting`?

**Comment by b-morgan** [comment]
[Desktop.zip](https://github.com/cadon/ARKStatsExtractor/files/2545136/Desktop.zip)

The attached .zip file contains 3 screenshots. 

ASB1 is after opening ASB, selecting Breeding Plan, and selecting Anklyosaurus. The breeding mode radio button is set to "Top Stats, Conservative".

ASB2 is after selecting the breeding mode radio button "Top Stats, Feeling Lucky".

ASB3 is after selecting the breeding mode radio button "Top Stats, Conservative" again.

Note that the breeding scores are different in ASB1 and ASB3. I believe they should be the same.

**Comment by cadon** [comment]
Thanks for the info. Found it and fixed it.
