### ISSUE TITLE
Enhancement: "Flat" mode for Library tab

### ISSUE THREAD

**Issue by b-morgan** [cadon/ARKStatsExtractor#773]
I'd like to be able to sort the library by added date across all species. Other fields like Name, Owner, Note, Server might also be useful as "flat" sorts. Currently, clicking on these other fields does a secondary sort within each species group which is useful and shouldn't be removed, but the "flat" sort is also useful, IMO.

I believe this would require an additional column for species instead of the current grouping by species so I'd propose that a control of some sort for "Grouped"/"Flat" be implemented.

**Comment by EmkioA** [comment]
Hello, i just made it.  It will be into the next version
