### ISSUE TITLE
Species order varies

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#779]
In the values.json, the DLC creatures are put at the bottom. This is reflected in the program in the list to filter all creatures based on species.

However, in an unfiltered library, the species are sorted alphabetically, causing both lists to have a different order.

Can this be changed to have the full library have the same order as whatever is in values.json?

**Comment by cadon** [comment]
Hi, thanks, never noticed that. This will be fixed in the next release.

**Comment by soepie7** [comment]
I hope you then set it to the point where it follows the order in values.ini: that would allow us to for example have all aberrant species not at the beginning because of the letter A, but have them listed behind their normal counterparts.

**Comment by cadon** [comment]
You'll have the possibility to set an arbitrary sort order in a file. The order in the values.json could change.

**Comment by cadon** [comment]
The format will be changed, the separator character will be `@` and the other text is treated as regex, which allows easier renaming.
