### ISSUE TITLE
Behavior similar ot memory leak

### ISSUE THREAD

**Issue by Walayimuna** [cadon/ARKStatsExtractor#780]
I am having issues with your software, and after some testing with other java applications, it seems to be your software only, on what appears to be a memory leak of some sort.

The more I leave the software open, the slower it gets overall, while everything else on the computer continues to work without issues.

I asked friends that also use your software, however no-one else seems to be having this issue.

Closing the software does not fix it, however logging of and back in or restarting the computer does.

What kind of further information would you required in order to try and address this issue?

**Comment by cadon** [comment]
Hi, if a specific taks creates a memory leak, it can often be seen in an increase of the used RAM-usage.
You can open the task-manager (Ctrl+Shift+ESC) and see how the needed RAM changes. A sign of a memory leak would be if you use the application for around a minute, note the used RAM, then compare the value after some time, e.g. 30 min. If it has incraesed significantly, it's a sign of a memory leak. Then it's interesting, when these increases happen. You can watch the memory-usage while doing stuff in the application.
Usually closing and reopening the application should free the used memory. You can also check the general use of the memory if you notice a slow-down, maybe you see a process that uses a lot of memory.

**Comment by cadon** [comment]
There were a couple of fixes since the issue was opened. I assume it's resolved for now, if not, feel free to reopen this issue.
