### ISSUE TITLE
Copy stats to Stat Testing from Extractor?

### ISSUE THREAD

**Issue by Taiine** [cadon/ARKStatsExtractor#781]
Is there a way or can you add a copy stats from the extractor to the stats testing? 
I ask as sometimes I get dinos that have one or two stats redded out and won't add via the extractor, but with game mods, I know what points they have so can add them manually in the stat tester.

It would be nice if the extracted into, along with colors, ids, etc can be copied to the state testing so the erroring points can be added and the creature added to the data. As is I have color mutations I can't add as the color selection only allows natural colors. 

It would also be a time saver, I was given a bunch of bred troodon eggs and their food stat fails to load in, they have all sorts of color mutations and such but all with the same 39 food stat. If I could just copy their extracted stats to the stat testing and add that in by hand it be soooo much easier than doing 16 of these little guys by hand and missing out on the color data and such.

**Comment by cadon** [comment]
Hi, there's a button in the toolbar `Copy to Tester` and `Copy to Extractor`, respectively.

**Comment by Worldgate** [comment]
Because it's for testing not for storing data.

**Comment by cadon** [comment]
I'll put it on the todo-list.
