### ISSUE TITLE
Extraction via OCR failed but Exported same values work?

### ISSUE THREAD

**Issue by FireCulex** [cadon/ARKStatsExtractor#784]
Am I crazy?

OCR - 
![image](https://user-images.githubusercontent.com/9983630/45870511-e35e5680-bd3f-11e8-85e7-c9072e193b37.png)
Exported -
![image](https://user-images.githubusercontent.com/9983630/45870537-fc670780-bd3f-11e8-89e3-f881febc4c25.png)
Notice the overlay sticks on screen even outside the game and only displayed when exported in-game  into the Extractor.
My Rock Drake and bulbdog show up just fine. 
Singleplayer settings.

**Comment by kohonac** [comment]
if you were to open the ini you would see that the stats have more decimal places, where OCR and ingame only should the decimal to one place, so there are rounding errors which is why the export is the much preferred method of importing

**Comment by cadon** [comment]
I increased the marging of error of the extraction process a bit, so it should allow a larger rounding error (making that marging to big will result in wrong levels). I just tried it with the latest version, the numbers work there.
