### ISSUE TITLE
Generate Automatic Name

### ISSUE THREAD

**Issue by BonesBLADE** [cadon/ARKStatsExtractor#785]
When I use the Generate Automatic Name and put in {dom} it is only coming up with T and not B when they are bread.

**Comment by BonesBLADE** [comment]
It is also not keeping the Tribe name and I have to enter it every time.

**Comment by kohonac** [comment]
what version are you using so that the developer cant track it down faster

**Comment by BonesBLADE** [comment]
Version 28.9.1.
It also isn't filling out the stats when I click when I click on Read Values. All of them bar weight and torp are coming up as 0.00

**Comment by kohonac** [comment]
that version has several bugs. i would suggest going back to version 28.8 until the Developer has a chance to work the bugs out of the newer versions

**Comment by BonesBLADE** [comment]
Is this app going to be updated anymore, just asking as I haven't seen an update for a while and there are a few bugs.

**Comment by cadon** [comment]
Hi, found the issue, this will be fixed in the next release.
