### ISSUE TITLE
Aberrant Otter cannot be extracted

### ISSUE THREAD

**Issue by msjs91011** [cadon/ARKStatsExtractor#787]
having issues importing all wild-tamed aberrant otters. Screenshot attached. No settings in program have been altered. This is on Xbox Official server.

![untitled](https://user-images.githubusercontent.com/43628105/46119964-949b3b80-c1db-11e8-8a71-8fff71e9fe40.png)

**Comment by kohonac** [comment]
there a know bugs with the most resent versions of ASB. i would suggest going back to 28.8 and see if that fixes the import problem.

**Comment by cadon** [comment]
I can extract that otter without issues. Maybe you set the multipliers not correctly?
 (Aberrant Otter, Lvl 203, TE: 90.4%): HP: 315 (36, 0); St: 756 (32, 0); Ox: 2100 (25, 0); Fo: 1320 (23, 0); We: 48.6 (31, 0); Dm: 263.1% (30, 0); Sp: 170% (25, 0); To: 4592.5 (202);

**Comment by msjs91011** [comment]
I left all multipliers and other settings alone because I am on an official
server.

**Comment by cadon** [comment]
Did you enter the numbers manually?

**Comment by msjs91011** [comment]
Yes, triple checked for errors. Can't use OCR because I use a Walmart
laptop lol (1024x768 resolution which ase doesn't support)

On Nov 3, 2018 7:51 PM, "cadon" <notifications@github.com> wrote:

Did you enter the numbers manually?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cadon/ARKStatsExtractor/issues/787#issuecomment-435630037>,
or mute the thread

**Comment by cadon** [comment]
I don't know. As I said, if I enter the values as they are on your screenshot, the extraction works without issues. Can you post a screenshot of your settings?
