### ISSUE TITLE
Ark tools doesn't import mutations

### ISSUE THREAD

**Issue by FireCulex** [cadon/ARKStatsExtractor#789]
Dino Extract will, but Ark-tools does not.

**Comment by coldino** [comment]
*ark-tools* in its current state does not support reading mutations from the save file, and it looks like development on it has stopped, sadly.

Although I have a form of ark-tools with this feature and more added, I won't be taking over maintenance of ark-tools and hence am reluctant to release it.  If you can compile Java, you can grab my fork for yourself.

The good news is that there is a possible replacement for ark-tools on the horizon. No promises, though.
