### ISSUE TITLE
Requests: Delete dead dinos ark data. + Highlight food, Oxegen and speed stats

### ISSUE THREAD

**Issue by Taiine** [cadon/ARKStatsExtractor#791]
So I'm a breeder, I mean a massive breeder... and there's two requests that would help out a lot.

1. An option that when you mark a dino as dead, that it will delete the ark data file for it. I find that the import exported data menu listing gets VERY laggy after a while, making manually deleting those you have culled a bit of a pain, plus every time you delete data from it it takes you to the bottom of the list. I would love an option that can be checked to say if I mark a dino as dead, delete the data file. Also maybe a pop up that asks if I delete a dino from the list if it also wants to delete the ark data as well. Just to make thing's easier to clean up lists. Also, I know there is a button to delete all imported files, but I like keeping them on hand (the ones that are not dead) as the file for the dinos is shared across drop box to other tribemates and our allies, and we already had a 'oops' moment of someone deleting the info for the wrong dinos. So I keep all the data to easily see what got deleted and re-add it back in. Easier than going on a hunt trying to sort out what dinos are no longer listed and getting dupes imported.

2. Add the highlight for the food, oxygen an speed stat in the library view. All the other stats get a green highlight to show the best stats, I'd like that for these three as well, Those stats are just as important as the rest in getting the highest level dino you can. Having a highlight for these stats would help a lot, as I just accidentally culled off a 50 oxygen and 41 food stat argi (much better than the 21 and 29 stats I have in my line atm), and without that my listed best possible levels has dropped. Not happy.

**Comment by cadon** [comment]
Hi, an improvement for the import-files is on the todo-list, like the `delete all files of imported creatures`-buttton. Good idea with the (optional) deletion of a file if the according creature is deleted.

Your second issue can be solved by enabling the highlighting of all stats. By default food and oxygen are disabled. In the library see in the left bottom the `Stats`-tab (you might have to use the arrow-buttons on the right of the tabs) and enable all stats you want to highlight.

**Comment by Taiine** [comment]
Thanks for the reply. I look forward to seeing these changes added as it would be super helpful, and time-saving. I would def love the option of deleting the data if you mark a dino as dead as well as deleted. 

Also oh thanks! I never noticed that little tab.

**Comment by DodoCooker** [comment]
Bottom left of the breeding planner - it's probably set to less than 10 meaning no suggestions with more than that number of mutation-counter will be made.
![image](https://user-images.githubusercontent.com/4038417/46410452-38737280-c719-11e8-8b5f-cca04cc8fda8.png)

**Comment by kohonac** [comment]
@Taiine im not sure where you are saying the the argi from the ingame screenshot isnt showing up but if you are meaning in the breeding planner then it would be filtered by default setting as its mutation count is 21/20. if its someplace else that it is being filtered perhaps a bit more directed information will help with solving this.
