### ISSUE TITLE
Read Values From Ark window missing

### ISSUE THREAD

**Issue by JustANormal** [cadon/ARKStatsExtractor#793]
Hello, I wanted to read the values of my dino with the 'Read Valuse From Ark Window' Button but its not there. Instead there are 2 buttons which are 'Import Exported Data' and 'Last Export'. I Appreciate for any help. 
Thanks

**Comment by JustANormal** [comment]
ok i understand now thanks alot :)

**Comment by kohonac** [comment]
np. if you have any other questions pls feel free to ask here or on discord. :D

**Comment by JustANormal** [comment]
there are alot of rooms on discord, where should i ask?

**Comment by kohonac** [comment]
guess that would depend on the nature of the question but even if its not a topic for that channel no one will yell at you but will probably just help you and let you know a better channel for it.

**Comment by JustANormal** [comment]
then ill ask u perhaps. so i have my server settings an dino stats multiplier all on 1 . and i input the settings on the smart breeder app and i use the export button from steam and imported it to my app. Everything is fine except the health which has a red value. Do u have any idea to solve it?

**Comment by kohonac** [comment]
so have you set ASB to use 1.0 for all stats? or are you using official setting?
![image](https://user-images.githubusercontent.com/3374605/46415904-325ea100-c6db-11e8-9f07-56267c266c29.png)

**Comment by JustANormal** [comment]
i have a private server running and set everything to1 on the multiplier and also on the ASB. Everything works except Health. Tested on couple types of dinos and lvls and still only the health was the issue

**Comment by kohonac** [comment]
are they fresh tame's? if so you may have to restart the server to get them update their stats properly as ARK itself has a could of bugs with stats. some types of dino's are worse than other. also have you gotten any dino's to extract properly yet?

**Comment by JustANormal** [comment]
yes i set all to 1, restart the server, tamed a new dino and extract it still only the health has red value. So far everything seems properly to me except the health

**Comment by kohonac** [comment]
if you drag the game.ini and the GUS.ini to the ASB settings window it will set the multipliers for you. i have a feeling that something its quite set to 1.0. if that fails to work, take a screen shot of a new tame's ingame inventory screen as well as your stat settings in ASB and post them here or in discords #extraction-issue channel. if this step doesnt work im out of ideas right now so someone else may have a idea of what is causing it

**Comment by JustANormal** [comment]
where can i find the game.ini and gus.ini ?

**Comment by kohonac** [comment]
_**yourdrive letter here**_:\SteamLibrary\steamapps\common\ARK\ShooterGame\Saved\Config\WindowsNoEditor
