### ISSUE TITLE
Consideration for ShadowBox users.

### ISSUE THREAD

**Issue by Clutch152** [cadon/ARKStatsExtractor#794]
I play Ark on a Shadow Tech Box because I don't have the luxury of having a desktop due to moving around for work. Using the process name is troublesome due to the fact that the process name "Shadow" appears multiple times in task manager for the various things it handles. I downloaded the source and modified it to better accommodate my needs so I though I would share it here.

In the file https://github.com/cadon/ARKStatsExtractor/blob/master/ARKBreedingStats/Win32Stuff.cs
I changed the function on line 62 to look like this:
```C#
public static Bitmap GetSreenshotOfProcess(string processName, int waitMs, bool hideOverlay = false)// = 500)
{
	Process[] p = Process.GetProcessesByName(processName);
	Bitmap grab = null;

	if (p.Length == 0)
		return null;

	//Shadow Box users have multiple processes named "Shadow" but only one has an actual window.
	//Itterate through processes until window screen grab is NOT null.
	foreach (Process i in p)
	{

		IntPtr proc = i.MainWindowHandle;
		//return PrintWindow(proc); <-- doesn't work, althought it should

		SetForegroundWindow(proc);
		ShowWindow(proc, SW_RESTORE);

		// You need some amount of delay, but 1 second may be overkill
		Thread.Sleep(waitMs);

		grab = GrabCurrentScreen(proc, hideOverlay);

		if (grab != null)
			break;
	}
	return grab;
}
```

Maybe throw in an option to select a specific process or process ID?

**Comment by cadon** [comment]
Thanks, I'll add that.
The process-name can already be selected in Settings - General - OCR, you probably found that already. Is it necessary to also add an option for a process-id?
