### ISSUE TITLE
OCR screen does not load Image

### ISSUE THREAD

**Issue by ToeiRei** [cadon/ARKStatsExtractor#795]
usually it's sufficient to drag an image into the 'experimental OCR' to do some calibration.
Image loading does not work.

**Comment by cadon** [comment]
Hi, is there any error-message?

**Comment by ToeiRei** [comment]
sadly nothing.

**Comment by cadon** [comment]
Do you have checked the checkbox `Enable Logging and Editing` in the `Output`-tab (right top)?

**Comment by ToeiRei** [comment]
that seems to be the bug.
