### ISSUE TITLE
"Top" count in library inaccurate

### ISSUE THREAD

**Issue by MrFluffums** [cadon/ARKStatsExtractor#796]
The "Top" count in Library does not consider the Food or Oxygen stat for dinos where it is functionally relevant or the Speed stat for superficial level inflation for dinos that can gain it. When you have another stat and Food or Oxygen, the Top count is "1" instead of "2."

These stats also are dimmed for the aggregated color ranges, when they are sometimes relevant to be considered normally.

Can we please have the option in Settings to toggle which stats are considered for Top and which stats are considered normal for the color-coded ranges? This wouldn't have to be on a per-dino basis, but even just an overall toggle could be nice.

Two examples of functional use for these stats--as mentioned--are the Phiomia's food stat for force-feeding stim berries for feces, and the Spino's oxygen stat which gives it movement speed in water and underwater time.

**Comment by kohonac** [comment]
there is already the options that you ask for

![image](https://user-images.githubusercontent.com/3374605/47543308-6b330580-d896-11e8-8000-095b42bf72d0.png)
