### ISSUE TITLE
Titanoboa Stat Extraction Fails (health)

### ISSUE THREAD

**Issue by FreidenSchmi** [cadon/ARKStatsExtractor#797]
Playing on my own private server. I can confirm there are no changes to the health stats on wild dinos. Nor can I imagine any mod influencing this in any way. All the other stats works, but health can't compute on any of my Titanoboas.
I use 7xTaming Multiplier and 180 max level dinos.
![danger noodle 269](https://user-images.githubusercontent.com/44497477/47562583-433bb480-d91f-11e8-8033-8672460cee3c.jpg)
![danger noodle titanoboa 180 tame with 99 te](https://user-images.githubusercontent.com/44497477/47562584-433bb480-d91f-11e8-83cd-7d68371a57fa.png)
![nope rope 251](https://user-images.githubusercontent.com/44497477/47562586-43d44b00-d91f-11e8-9d77-bcecde4f247a.jpg)
![nope rope titanoboa 168 tame with 99 te](https://user-images.githubusercontent.com/44497477/47562587-43d44b00-d91f-11e8-8bd8-a9060eca3fb7.png)

**Comment by kohonac** [comment]
did you change the max wild lvl in the settings?

**Comment by FreidenSchmi** [comment]
As noted on my original post I did. Max wild level is 180. This hasn't been an issue at all for any other dinos however

**Comment by cadon** [comment]
Are Titanoboas the only species that doesn't work? Do you have a mod that displays levels, e.g. Superspyglass?

**Comment by cadon** [comment]
I hope it's resolved in the meantime. If not, consider joining the discord channel for faster support.
