### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by BonesBLADE** [cadon/ARKStatsExtractor#798]
Is this app going to be updated anymore, just asking as I haven't seen an update for a while and there are a few bugs.

**Comment by cadon** [comment]
Hi, I'll not update this application very often from now on. Some other devs are joining in, so there should be at least fixes and maybe new features.

**Comment by BonesBLADE** [comment]
Thanks for the update and information.

**Comment by BonesBLADE** [comment]
Thanks for the update and information.
