### ISSUE TITLE
Rafts and MotorRafts aren't breedable and have no stats

### ISSUE THREAD

**Issue by b-morgan** [cadon/ARKStatsExtractor#802]
ASB 0.29.1.0 has eliminated the need for ARK-Tools but it now includes Rafts (Roll Rats) and MotorRafts (Morellatops) in the library. Since I'm playing on The Island, neither of these creatures exists.

Attached are yesterday's (previous ASB version) ARK-Tools extracts of these two "creatures".

[SavedExtracts.zip](https://github.com/cadon/ARKStatsExtractor/files/2545853/SavedExtracts.zip)

I don't know how hard it would be to add to values.json an "ignore" tag but implementing such a tag would allow future "creatures that are not creatures" to be added easily.

**Comment by Flachdachs** [comment]
fixed in 0.29.2
