### ISSUE TITLE
Giganotosaurus wrong incubation time

### ISSUE THREAD

**Issue by VeaceslavGrigoras** [cadon/ARKStatsExtractor#82]
Giganotosaurus egg has wrong incubation time (instead of 50 hours it has 50 days).
Attached screenshot.
![capture_giga](https://cloud.githubusercontent.com/assets/7238084/16907829/684a0bca-4ccf-11e6-94d2-22260a0abdea.PNG)

**Comment by cadon** [comment]
Hi, thanks, will be fixed shortly.
