### ISSUE TITLE
update creature if it's imported again (use ArkId?)

### ISSUE THREAD

**Issue by cadon** [cadon/ARKStatsExtractor#822]

**Comment by jwvanderbeck** [comment]
Saw this in the release notes.  Is this in now? It sounds awesome but doesn't appear to be working for me.  If it is in, under what conditions does it work? Does it only work for new entries from this version on?

**Comment by cadon** [comment]
Yes, it should be added this works with the ArkId that is only included to the creature if it is imported with a savegame or the ingame-export function. If a user enters an ArkId, this is ignored, because this number can be wrong (ARK does show it wrong in some cases). So if a creature is imported with the ArkId and then imported again later, it should update. Creatures added manually cannot be updated.

**Comment by jwvanderbeck** [comment]
All my dinos are always imported with the ingame export feature, then import with "Last Export" button.

When I look at the creature in my library I see two IDs. "Ark-id", and "Ark-id ingame".  When I look at a creature on the extract tab, after importing from export, I see only the "ark-id"  The Ark-id in both cases is the same. but the button says "Add New to Library".
**Edit Creature in Library**
![edit](https://user-images.githubusercontent.com/161126/50047764-d0260300-0070-11e9-9694-49b1a838e47a.PNG)

**Extract from "Last Export" on same creature**
![extract](https://user-images.githubusercontent.com/161126/50047765-d1573000-0070-11e9-8d36-ddb71691fbbe.PNG)

**Comment by cadon** [comment]
I see, apparently the `Last Export` missed the part with the id. It'll be fixed in the next release. This also means, the creatures imported with the `Last Export` function cannot be updated this way, only the ones that are imported via the import-window (`File` - `Import Exported Creatures`).
