### ISSUE TITLE
Mark one pair as just mated causes whole species to show no possible pairings

### ISSUE THREAD

**Issue by b-morgan** [cadon/ARKStatsExtractor#825]
I've attached two screenshots. The first (ASB_Pt1) shows the library view of our Pteranodons. The pair Carlie and Icarus just mated so I selected them on the Breeding Plan page and clicked on "These parents just mated". Instead of the remaining pairings, I got the screen (ASB_Pt2) showing no possible pairings.

There should be 3 females and 2 males available for pairing.

**Comment by b-morgan** [comment]
[ASB_Pt.zip](https://github.com/cadon/ARKStatsExtractor/files/2546499/ASB_Pt.zip)

**Comment by b-morgan** [comment]
Restarting ASB clears things up with the exception that it didn't remember that Carlie and Icarus just mated.

**Comment by b-morgan** [comment]
The issue is repeatable.

**Comment by kohonac** [comment]
a pic of the breeding planner before clicking the just mated button would be more helpful than an stats unsorted library pic is imo

**Comment by cadon** [comment]
Will be fixed soon, also see #827.
