### ISSUE TITLE
Crash while importing from savegame

### ISSUE THREAD

**Issue by ACCakut** [cadon/ARKStatsExtractor#828]
`System.InvalidCastException: Unable to cast object of type 'SavegameToolkit.Arrays.ArkArrayUnknown' to type 'SavegameToolkit.Arrays.ArkArrayStruct'.
   at SavegameToolkit.PropertyContainerExtensions.GetPropertyValue[T,U](IPropertyContainer propertyContainer, String name, Int32 index, U defaultValue, Func`2 map)
   at ARKBreedingStats.ImportSavegame.ConvertGameObject(GameObject creatureObject, Nullable`1 levelStep)
   at ARKBreedingStats.Form1.<>c__DisplayClass93_0.<importCollectionFromSavegame>b__1(GameObject o)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ARKBreedingStats.Form1.<importCollectionFromSavegame>d__93.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
`

Version 0.28.7 (with external jar extractor) works fine, latest 0.29.1 (with internal dll-extractor) shows this error, when importing.

It seems to work fine on old savegames from august (and the corresponding server version), not with newer ones from november (paused playing in between so I unfortunately cannot say, when the problems startet exactly).

Ragnarok without any traveling, an newer savegame with imports from Abberation does work too. Both work with 0.28.7.

Do the different versions (both installed from zip and saved on OneDrive for tribe-sync) interfere with each other? It does not seem so, since the user.config from AppData have different folders, the extraction-directories for savegames have so, too.

Thanks for this great tool and any help with this bug (or failure from me ;-)

**Comment by kohonac** [comment]
did you try this before yesterdays big update for extinction core?

**Comment by VolatilePulse** [comment]
Is there any way you can upload you save file so I can test this further?

**Comment by ACCakut** [comment]
[Ragnarok.zip](https://github.com/cadon/ARKStatsExtractor/files/2572016/Ragnarok.zip)
[ragnarok_20181029_133001.zip](https://github.com/cadon/ARKStatsExtractor/files/2572017/ragnarok_20181029_133001.zip)
[Ragnarok_05.08.2018_15.05.56.zip](https://github.com/cadon/ARKStatsExtractor/files/2572018/Ragnarok_05.08.2018_15.05.56.zip)

**Comment by Flachdachs** [comment]
Fixed in 3f33cae. Großer Hai, René and others are now properly imported.

**Comment by ACCakut** [comment]
Thanks. Umlauts and other special characters of course ;-)

**Comment by matte3310** [comment]
Same issue occurs with version 29.3. Uploaded the save file as requested by **coldino**.
[TheIsland_20.12.2018_22.06.47.zip](https://github.com/cadon/ARKStatsExtractor/files/2705165/TheIsland_20.12.2018_22.06.47.zip)

**Comment by coldino** [comment]
@Flachdachs
Maybe an old version of the library was included in the last release?
Maybe a different, similar issue.

**Comment by Flachdachs** [comment]
Fixed, old library version was accidentally released
