### ISSUE TITLE
Bred spino stat issue

### ISSUE THREAD

**Issue by emurday** [cadon/ARKStatsExtractor#83]
On an official server with x4 multiplier, stat extractor version 0.20.3.0.

The current stamina stat for this animal is identical to the stat at birth.  (Zero points allocated.)
 However, I'm unable to get a stat combo where this is the case, whether I leave stamina locked or unlocked.

Points have only ever been allocated into melee with the exception of a 1 point into speed on this animal.

![image](https://cloud.githubusercontent.com/assets/7611518/17012657/066e0054-4ece-11e6-9237-944e6dfc38de.png)

**Comment by cadon** [comment]
Hi, the extractor finds that one point was put into stamina, at least then it's a valid value for that. Maybe you accidentally assigned a point to stamina once? Or a tribemate?

**Comment by emurday** [comment]
You must be correct, because I can't find the stat anywhere else in my breeding population.  Apologies for the confusion!
