### ISSUE TITLE
Gacha Crafting Skill added to speed

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#831]
Because the Gacha has 8 stats instead of 7, something goes wrong. It just ignores the 8th stat (Crafting Skill) and tries to calculate the points without that stat, causing it to put all the points in Crafting Skill into speed.

**Comment by kohonac** [comment]
the problem is that ASB was written to use only 8 stats and the Gacha has 9 so its not just a matter of calculation but of pretty much everything in the UI as well as any calculation of stats, so the method of input is not relevant

**Comment by Worldgate** [comment]
I've found if you extract the info before adding any levels it works much better, since no data is in crafting yet.

**Comment by cadon** [comment]
Support for the Gacha was added.
