### ISSUE TITLE
Updating fails and restart in a loop

### ISSUE THREAD

**Issue by Dwza** [cadon/ARKStatsExtractor#834]
When i open the program, a message prompts that i have the versin 0.29.1 and there is a new version 0.29.2. If I confirm the update, adb is obviously doing some stuff with the files. But after this is finish, it prompts the message again and again. Checking version is still 0.29.1

**Comment by Flachdachs** [comment]
Did you install the exe or the zip version?

**Comment by b-morgan** [comment]
I am having the same issue with the update from 0.29.2.0 to 0.29.2.1 and I installed from the zip.

**Comment by b-morgan** [comment]
I also have an installation using the installer and it updated correctly.

**Comment by b-morgan** [comment]
I don't believe I'm having a problem with the installer, I'm having a problem with the auto-updater.

@VolatilePulse If your comment is saying installer when it should say auto-updater then the directory I have ASB installed in is owned by me and is not protected (but it is shared via Google Drive).

**Comment by VolatilePulse** [comment]
You mention you're sharing it. Just like local files, the program can't be opened elsewhere when you attempt to update it. The updater is designed to close the program locally, but can't close other instances on someone else's machine. This is true for any sort of program or file. The updater assumes no one else is using it so it attempts to update the file.

If you're sure that isn't your case, I'm not sure what might be going on.

**Comment by Dwza** [comment]
Exe. Update worked before. Had to redownload Exe and reinstall it.

Am Mi., 14. Nov. 2018, 18:39 hat Flachdachs <notifications@github.com>
geschrieben:

**Comment by cadon** [comment]
This issue should be finally resolved in the next release.
