### ISSUE TITLE
Breeding Probabilities

### ISSUE THREAD

**Issue by DodoCooker** [cadon/ARKStatsExtractor#836]
Hi. In the breeding suggestions the probability % is shown as 70% to get the higher stat on each stat point (if you have a pair where only one stat is different you see as 70% chance to get the better one). But the calculation for the breeding values is using the following constants:
private const double probHigherLvl = 0.55; // probability of inheriting the higher level-stat
private const double probLowerLvl = 0.45; // probability of inheriting the higher level-stat
meaning it should be 55% instead.
The most common belief you find out in forums/blogs is the 70/30 split but got debated in the following reddit post to be the 55/45 split which is actually also implemented on the internal calculations in your source: https://www.reddit.com/r/playark/comments/6gsk84/breeding_and_mutation_probabilities_from/

Since i've been breeding for stats lately i started to write down the number of "higher" and "lower" points going through and i got a 51/49 split on about 500 dinos raised so far so i think with random variation in mind the 55/45 is more likely to be the truth than the 70/30 one. Is there a reason the program uses the 70% in the GUI and for the internals 55/45 or is it an oversight (maybe got changed from 70 to 55 sometime in the past but the GUI was overlooked)?
If its an oversight: In BreedingPlan.cs in the function "private void setParents(int comboIndex)" you'll find the line 
                    probabilityBest *= .7; 
which could be changed to
                    probabilityBest *= probHigherLvl;
to use the constant which is already used for the internal calculations.

**Comment by DodoCooker** [comment]
An interesting side note to this is that only the % for best possible dino uses the 70% - the diagram next to it also uses the 55% already :)
![image](https://user-images.githubusercontent.com/4038417/48832149-c7475780-ed78-11e8-9c80-f1c06261c429.png)

**Comment by cadon** [comment]
Hi, thanks for the report and the solution! I indeed forgot to change that part you pointed out. This is fixed in the code and will be in the next release.
