### ISSUE TITLE
Pulling from PS4 (RemotePlay)

### ISSUE THREAD

**Issue by johnnymorris** [cadon/ARKStatsExtractor#837]
Hello, Firstly thank you for this amazing app.

I'm wondering what is the best way to pull the stats from a PlayStation automatically?

At the moment we are entering this manually.

I'm managed to get the RemotePlay. So I can replicate the PS screen on my laptop and my plan was to use the OCR to pull the stats however I'm not sure what I should be entering under "Capture from (ShooterGame is default for the Steam-version)" I've tried:
 - RemotePlay.exe (which is the app under task manager)
 - PS4 Remote Play (which is the name of the application) but nothing seems to work.

I'm also using a laptop and the screen resolution is 1366x768. I've changed the .json file to reflect this but again no joy.

Any pointers?

I'm also considering taking a screenshot and sending to twitter with a hash tag or a private FB album and pulling them this way but again not sure what I would enter and of course this is less automated :)

Thanks !

**Comment by kohonac** [comment]
i dont have any experience or advice on how to set up ASB for the remote play but i can tell you from experience with that low of resolution that OCR will have a very hard time and you will still be correcting and entering data manually
