### ISSUE TITLE
Name generator {species_short] for Aberration

### ISSUE THREAD

**Issue by senesi-t** [cadon/ARKStatsExtractor#844]
I like the parameters for the name generator, but it would be nice to have the "species without the first word" for all aberration dinos.
Or can we have a Name Generator configuration specific string by dino ? For exemple, I want my Rex to have "{species} {tn}" and my Spino "{species} {hp}-{dmg}" ?
Or even made such changes in configurations files ?

**Comment by jwvanderbeck** [comment]
The ability to have templates saved per species would absolutely rock.  I also think a config that lets you map species names to short species names would be cool to do as well.

**Comment by cadon** [comment]
What do you mean exactly by
> a config that lets you map species names to short species names

?

**Comment by jwvanderbeck** [comment]
Something similar to how the app has mappings for what you type in the species name field on the extractor. Only in this case it would be mapping the full (proper) species name, to your desired short name.
So something like:
Allosaurus -> Allo
Snow Owl -> Owl
Doedicurus -> Doed
Otter -> Otter
Rex -> T-Rex

Or whatever.  What this would allow is essentially user chosen short names for their creatures rather than just truncating the first X characters from the proper name.

**Comment by harry323** [comment]
I third this feature request. Is there any chance of getting it implemented? Keeping short names manually gets tedious. I'm taming Thylacoleos and having to switch back and forth between the library and extraction tabs to figure out which one is next is more difficult than having the generator give me the next Thyla XYY. Is there any chance of getting this implemented?

**Comment by cadon** [comment]
The next release will have custom replacements implemented. For now you can use the replace or substring function of the naming-pattern to solve the issue partially.

* `{{#replace: {species} | Abberant | Ab }}` will replace all occurences of `Abberant` with `Ab`.
* `{{#substring: {species} | 0 | 4 }}` will only use the first 4 characters of the species.

The new feature in the next release will let you create a json file with a content similar to

```
{
  "Allosaurus": "Allo",
  "Snow Owl": "Owl"
}
```
which can be accessed by the new function `customreplace` that will look if the passed text is available and replace it with the according entry. E.g. `{{#customreplace: {species} }}` will transform `Snow Owl` to `Owl` for a snow owl and will do nothing for a rex. That way for all species (or other text) custom replacings can be specified. That file has to be named `customReplacings.json` and needs to be in the json-folder of ASB (i.e. in the ASB folder for the zip-version or the local-data folder for the installed version).

**Comment by jwvanderbeck** [comment]
@cadon your continued dedication to this project after so many years is truly outstanding.  Just wanted to say thanks.  I float in and out of playing Ark but this amazing always seems to be here waiting for me when I need it!

**Comment by harry323** [comment]
Agreed with @jwvanderbeck! Thanks @cadon for working tirelessly on this project. As a fan it's wonderful being able to interact with the creator/s of such a great tool.
