### ISSUE TITLE
sortNames.txt is completely ignored

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#845]
I tried multiple things in it, including the example you once provided in a changelog:

`^Aberrant (.*)$@$1a`

`^Tek (.*)$@$1a`

However, it still lists all aberrant species at the top of the list.

**Comment by cadon** [comment]
Do you have the file stored in the json-folder?

**Comment by soepie7** [comment]
Yes I have.

**Comment by cadon** [comment]
Just for clarification, the order of the species set by this file is used in the library and in the species-selection-list on the left of the library. It's not used in the species-selector where the species are listed that match the letters typed in the textbox.
Does it work with simple things, like `Aberrant Doedicurus@zzz`, which should sort the aberrant doedi near the end of the list?

**Comment by soepie7** [comment]
It did not sort it at the bottom. Everything in json/sortNames.txt is ignored.

**Comment by soepie7** [comment]
That's it, I had it all in the json folder for the installed ASB.
