### ISSUE TITLE
Primal Fear support

### ISSUE THREAD

**Issue by FireCulex** [cadon/ARKStatsExtractor#846]
Importing dinos from Primal Fear all result in Aberrant Paracethiums. It won as 4th place in the sponsered mod program. It would be nice to be able to import them. Personally Im less interested in multipliers as I'm in Stat Values or simply just their TamedName.

Ark can export them, but I take it the DinoNameTag is hardcoded in ASB?
```
[Dino Data]
DinoID1=234106197
DinoID2=403481860
DinoClass=/Game/Mods/Primal_Fear/Dinos/Fabled/Fabled_Stego/FabledStego_Character_BP.FabledStego_Character_BP_C
DinoNameTag=FabledStego
bIsFemale=True
bNeutered=False
TamerString=Raiders of the Lost Ark
TamedName=Barry
ImprinterName=
RandomMutationsMale=0
RandomMutationsFemale=0
BabyAge=1.000000
CharacterLevel=229
DinoImprintingQuality=0.000000

[Colorization]
ColorSet[0]=(R=0.004391,G=0.088656,B=0.205079,A=1.000000)
ColorSet[1]=(R=0.002732,G=0.181164,B=0.266356,A=1.000000)
ColorSet[2]=(R=0.514918,G=0.000000,B=0.658375,A=1.000000)
ColorSet[3]=(R=0.002428,G=0.346704,B=0.527115,A=1.000000)
ColorSet[4]=(R=0.366253,G=0.011612,B=0.450786,A=1.000000)
ColorSet[5]=(R=0.026241,G=0.571125,B=0.806952,A=1.000000)

[Max Character Status Values]
Health=116546.671875
Stamina=22560.000000
Torpidity=111680.500000
Oxygen=3400.000000
food=345600.000000
Water=100.000000
Temperature=0.000000
Weight=53120.000000
Melee Damage=8.077533
Movement Speed=1.464000
Fortitude=0.000000
Crafting Skill=0.000000

[Dino Ancestry]
DinoAncestorsCount=0
DinoAncestorsMale=0
```

**Comment by cadon** [comment]
Hi, mods can be added to ASB (like e.g. classicFlyers), but it needs the exact stat-values for each new or changed species. Either you can get them by the mod creator or by testing and spawning a lot of dinos and check their stats. Also see https://github.com/cadon/ARKStatsExtractor/wiki/Mod-Values .

**Comment by coldino** [comment]
For anyone else looking for Primal Fear support, we are distributing experimental values files to support the mod via Discord.
