### ISSUE TITLE
Cryopod status incomplete

### ISSUE THREAD

**Issue by soepie7** [cadon/ARKStatsExtractor#849]
First of all, when editing multiple creatures, you can't select the status "cryopod", only alive/dead/unavailable/obelisk.

Secondly, stats of creatures with the cryopod (or obelisk) status are not included in the calculation of the top stats, even though they can still be bred with.

**Comment by cadon** [comment]
First issue is resolved in v0.29.3.

**Comment by cadon** [comment]
@jwvanderbeck thanks, the cryopod menu-entry be fixed in the next release. Until then you can use the checkbox on the bottom left in the `View`-tab.

**Comment by Flachdachs** [comment]
The fixes for this issue are now released with v0.29.3.1
