### ISSUE TITLE
Name Generator parameters doesn't work 

### ISSUE THREAD

**Issue by Niwaun** [cadon/ARKStatsExtractor#857]
Hi there
Love the program, but ever since playing on Aberration the long names are kinda meh, so wanted to change to {species_short}, but then all dinos are named "{species_short}" instead.
I'm using the zip version because we use it tribe wide.
I've asked everyone to shut it down before changing things.

**Comment by DodoCooker** [comment]
The wiki seems to be out of date - right click on the "G"-button so you see the new options for the short-version (needs to include the length now).
![image](https://user-images.githubusercontent.com/4038417/50283303-c6781300-0455-11e9-9fe4-5d1e1e27a8f7.png)

**Comment by Niwaun** [comment]
Oh nice, thanks!
