### ISSUE TITLE
Extraction issue

### ISSUE THREAD

**Issue by Panda3528** [cadon/ARKStatsExtractor#858]
I'm new to this app and whenever I try to extract my dino's I keep getting a error in the speed section. I disabled the classic flyers mod and have breed a few more dino's since and still keep getting the error. I'm playing on an unofficial server single player and have double checked the game settings and matched them up with the Smart breeder settings. 
 
![img_3989](https://user-images.githubusercontent.com/46040685/50325622-2517ae00-04a3-11e9-867b-bfd58e81e542.jpg)

![img_3988](https://user-images.githubusercontent.com/46040685/50325689-7a53bf80-04a3-11e9-9eb5-cf9ca64b15aa.jpg)

![img_3991](https://user-images.githubusercontent.com/46040685/50325703-90618000-04a3-11e9-9c73-8b1bed0cd47e.jpg)

**Comment by kohonac** [comment]
couple of things 1) is it only flyers your having trouble with? 2) if you tamed/spawned fliers with Classic fliers running it will not revert them back to vanilla when disabled as far as im aware so disabling it wouldnt help 3) if your playing steam and dont know how to use the export feature ingame for importing there is a nice write up in the [discord ](https://discord.gg/9qx4u2S) [#walkthough](https://discord.gg/Xamb2H) section under "for steam players"

as for loading the file that ASB needs for CF go to the file menu and then load the ClassicFlyers.json 
![image](https://user-images.githubusercontent.com/3374605/50326519-b553f400-049f-11e9-8eb9-0fc53def6196.png)

**Comment by cadon** [comment]
Hi, it works if you set TameAdd for Speed to 2.0 in addition to your posted multiplier customizations.
