### ISSUE TITLE
Bug after latest update

### ISSUE THREAD

**Issue by laurencei** [cadon/ARKStatsExtractor#859]
Hi,

I just upgraded to the latest version last night (version 0.29.3.1) from 29.2

After upgrading I noticed all my "top %" are 0 in my library. i.e. all dinos are listed as 0% top rating, for all dinos in all categories:

![image](https://user-images.githubusercontent.com/1210658/50390989-4eca2100-0792-11e9-8d45-2625563e9b20.png)

This includes new imports after the upgrade.

Any ideas why?

**Comment by qfather** [comment]
Same here. Fresh install from the latest zip release on a separate machine. Dino names lack their colours too.

**Comment by Darkchyylde** [comment]
Same. Really quite annoying lol

**Comment by Darkchyylde** [comment]
> I found the issue: it only happens when "Use Filters in TopStat-Calculation" is not checked.

I can't even FIND that check box... O_o

**Comment by laurencei** [comment]
> I found the issue: it only happens when "Use Filters in TopStat-Calculation" is not checked.

Yes - ticking that box solves it for me. So is this a bug? I'll leave the ticket open for now.


@Darkchyylde - here it is:
![image](https://user-images.githubusercontent.com/1210658/50420269-8ebfff80-0889-11e9-9c02-a1c2456dfbbc.png)

**Comment by soepie7** [comment]
It is not just the setting not persisting that is bugged, as this should not be the intended behaviour when the box is not checked either.

With the box not checked, it should mark stats regardless of what filters you said, instead of marking no stats.

**Comment by Darkchyylde** [comment]
Hmmm I just found something else because of this bug. I run a dual monitor set up and my secondary is a smaller monitor so when the program opens on the main and I drag it to the secondary, the window resizes smaller and that checkbox drops below the edge and there's no scroll bar to reach it

**Comment by Sakutera** [comment]
I have the same issue; the checkbox change is not saved unless you also save a change to the xml; goes for any of those checkboxes by the way
