### ISSUE TITLE
Issue  when writing down stats in the extractor tab

### ISSUE THREAD

**Issue by Wizeguy11** [cadon/ARKStatsExtractor#86]
When ever I use this program, it always comes up with at least 1 stat red. I have checked all of the trouble shotting things on the right, and none work. I have triple checked the single player dino stat multipliers and all is correct. Any ideas on how to fix this? All would be much appreciated!

**Comment by cadon** [comment]
Hi, I need more details to help.

What species don't work, can you upload a screenshot of the stats that doesn't work and are you playing on an official server, if not, what are the multipliers used there?

**Comment by Wizeguy11** [comment]
All species don't work. I am playing on a single player server and everything is set to 1. 
![image](https://cloud.githubusercontent.com/assets/20739706/17271161/c644351a-566c-11e6-8e3f-7a0e3939df1f.png)
![20160730154533_1](https://cloud.githubusercontent.com/assets/20739706/17271174/e9a08626-566c-11e6-9595-f83eb8686f8a.jpg)

**Comment by Wizeguy11** [comment]
![image](https://cloud.githubusercontent.com/assets/20739706/17271183/24a3a0aa-566d-11e6-9d26-9cd6cba05e69.png)

**Comment by cadon** [comment]
Hi, these numbers work fine for me. Don't forget to check "Since taming no Server-Restart". Setting all multipliers to 1 if you haven't set them in the game to 1 will not work. If you haven't changed the multipliers on the server, reset the multipliers in the tool to the official ones.

**Comment by Wizeguy11** [comment]
As you can see below, i have ticked "Since taming no server-restart (even tho there was) And most of them are still yellow. It also says near the bottom that the sum is wrong. I have set it so i have put NO dom lvls into it. And it says the sum is wrong?? Any ideas on that? Also can you please check these are the right official stat multipliers? 
![image](https://cloud.githubusercontent.com/assets/20739706/17271672/c5c91a26-5679-11e6-9b76-677dd9b4884c.png)
![image](https://cloud.githubusercontent.com/assets/20739706/17271675/d429b116-5679-11e6-90f8-8df16f03d2d0.png)

**Comment by cadon** [comment]
You mixed the wild-level and the dom-level. Oh, you're using a pretty old version. Try to download the current version 0.20.4, it has a button to easily set the multipliers to the official values.

**Comment by Wizeguy11** [comment]
It's working perfectly now! Thanks man! Much appreciated.
