### ISSUE TITLE
Enhancement: Name Checker

### ISSUE THREAD

**Issue by b-morgan** [cadon/ARKStatsExtractor#860]
For large libraries, checking a name for a new dino against the names already used can be a chore. In addition to the name generator, I like to see a name checker. Enter a name and it will tell you if it is already used.

I was going to say that since "Find Duplicates" already exists, much of the code should be in place, but when I tried "Find Duplicates", it said feature not included, lol.

**Comment by cadon** [comment]
In 0.29.3.2 the background of the name-input is now colored, if the name already exists in the library.
