### ISSUE TITLE
Extraction Issue Griffin

### ISSUE THREAD

**Issue by Yippee38** [cadon/ARKStatsExtractor#862]
I'm playing on the Island with "use single player settings" enabled, and Naj's Speedy Flyers mod (with the add-on for The Island that adds creatures and the one that adds a way to craft the resources for that mod).  I tamed a level 145 Griffin using raw mutton, so it tamed out at 217.  When I tried to put it into ARK Smart Breeding, ever stat worked except for the Health.  I checked to make sure I had the correct stat in there about 5 times.  So then I thought that maybe the values in the .json file for Naj's Speedy Flyers changed.  So I added that again.  Now, all the values are red except for Weight.  I checked the settings in ARK Smart Breeding against my game.ini (I had imported it into settings using drag and drop) to ensure they still match.  They do.

BTW, I've never had Classic Flyers installed on this server.

Any idea what the problem is?  If you think the problem is with Naj's Speedy Flyers, let me know, and I'll talk to the mod author about it.

Here's ARK Smart Breeding:
![Image of ARK Smart Breeding](http://www.yippee38.net/images/Temp/ARK/ARKSmartBreeding.png)
Here are the settings:
![Image of ARK Smart Breeding settings](http://www.yippee38.net/images/Temp/ARK/ARKSmartBreedingSettings.png)
Here are the creature stats:
![Image of creature stats](http://www.yippee38.net/images/Temp/ARK/GriffinStats.jpg)
Showing which mods I have installed:
![Image of installed mods](http://www.yippee38.net/images/Temp/ARK/Mods.jpg)
![Image of more installed mods](http://www.yippee38.net/images/Temp/ARK/Mods2.jpg)
And here's the contents of the .json for Naj's Speedy Flyers.  I've highlighted the section for the Griffin:
![Image of Naj Speedy Flyers json](http://www.yippee38.net/images/Temp/ARK/NAJsFlyerMod.png)

**Comment by VolatilePulse** [comment]
The multipliers file you're using for the mod isn't correct. Using `null` for the values does nothing other than tell ASB to use the official values of that creature. Mods, however, aren't designed this way and we strongly recommend against using null in any multiplier file and instead opt to copy the currently used values from the `values.json` file instead.

That being said, you would need to get the species' correct multipliers. It takes some patience to generate the values so unless you're comfortable with math and tedious work, we typically recommend you contact the mod creator to get the multipliers. You can also join us on Discord and we may be able to provide some better one on one help for generating the values file for this mod.

**Comment by cadon** [comment]
The mod system was reworked, by using the custom stat overrides this mod should work.
