### ISSUE TITLE
Export library for update?

### ISSUE THREAD

**Issue by Skishcat** [cadon/ARKStatsExtractor#867]
I've run into troubles recently with stats being red for no discernible reason. Even creatures that I've already added into the library are getting red stats when I re-extract them, even after server restarts. No multipliers have been changed at all.
So I decided to update the program, but now I can't seem to find out how to transfer all my saved stats to the updated version that downloaded. 
With previous updates, it just updated the version of the program I already had, but this one downloaded a separate program that is fresh and blank...
Pls help~

**Comment by cadon** [comment]
You can just copy your new downloaded app over the old one. If your old library doesn't appear automatically on opening, you can load it via File -> Load…

**Comment by Skishcat** [comment]
Yeah, the old library didn't appear. 
I'm struggling to find what to Load now. I looked in the old versions folder, and there's nothing in there

**Comment by Skishcat** [comment]
Oh I got it!
Thank you so much!
