### ISSUE TITLE
How to Update from version .20.3 to .20.4 without loosing Creature Library

### ISSUE THREAD

**Issue by Hedlice** [cadon/ARKStatsExtractor#87]
Hi, So I saw that you had added an update for including the imprinting bonus's and attempted to update the program. For some reason, it didn't seem to update, so I downloaded the new version. I ran the new version, but don't see any of my dino's in the library. Which file should I cut and paste to import my dino's from the old library to the new one (and is that possible yet?) By the way, I just wanted to say, GREAT JOB ON THIS!!!! My friends and I all use your program and love it!

**Comment by cadon** [comment]
Hi, the format wasn't changed, there shouldn't be any problem with save-files. Can you open your old library via the file-menu (File -> Load)?

**Comment by Hedlice** [comment]
Damn, didn't even see that feature. I was running the program out of it's unzipped file, and didn't even realize it was saving other files elsewhere. Thanks, I was able to load my creature database into the new version.
