### ISSUE TITLE
Griffin Extraction Issue

### ISSUE THREAD

**Issue by skellri** [cadon/ARKStatsExtractor#870]
hello, I'm playing on an official legacy server. Tamed a griffin, and it will not read the health stat values.
[![Screenshot from Gyazo](https://gyazo.com/992b054b093d985e6a0341233602014e/raw)](https://gyazo.com/992b054b093d985e6a0341233602014e)

**Comment by cadon** [comment]
Hi, how did you extract it, entering the values manually, OCR or the export-function?
If I enter the values manually, it works for me.

**Comment by skellri** [comment]
Hiya! Yeah I manually copied the values in myself, my game's screen resolution doesnt allow me to use the read from ARK window option

**Comment by cadon** [comment]
I just realized you use a very outdated version from over a year ago. I suggest to download the [latest release](https://github.com/cadon/ARKStatsExtractor/releases/latest), maybe it's just that.

**Comment by cadon** [comment]
I hope the issue is resolved by now, if not feel free to reopen.
