### ISSUE TITLE
Aberrant Dire Bear Missing

### ISSUE THREAD

**Issue by Powered-Up-Paul** [cadon/ARKStatsExtractor#871]
There is no Aberrant Dire Bear option and the standard DireBear option will not work for the aberrant variant.

**Comment by cadon** [comment]
Hm, it should be there. Do you have the latest app-version 0.29.4 and the values-version 285.106.2?

**Comment by Powered-Up-Paul** [comment]
Yep thankyou don't know why i wasn't using that version. Thankyou very much for the response and love the software.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
