### ISSUE TITLE
Weight value is wrong?

### ISSUE THREAD

**Issue by Zyles** [cadon/ARKStatsExtractor#877]
Have an odd calculation.

I bred Sarcos, second generation and according to the program they have 69 stat in weight, while, first of all, only having 714 in total weight.

And secondly the Bitou2k's Binocular mod in game say that the weight stat is 23.

When I look at my first gen sarcos, they have almost the same total weight. But their stat is not that high.

I double checked all the numbers and entered them correctly.

Example stats of this newly bred Sarco before imprinting:
lvl 227: 29 35 -1 29 69 45 -1 226

What is going on?

**Comment by cadon** [comment]
When you extracted the sarco with the 69 stat-levels in weight, was this stat's background yellow in Smart Breeding? If yes, then this is only one possible level combination, and you have to choose the correct one in a list that appears if you click on that stat. For more infos about that, see the [Manual](https://github.com/cadon/ARKStatsExtractor/wiki/Manual).
That's the first thing that comes into my mind as a possible reason for that. If that's not the case, can you post an ingame screenshot of the sarco with 69 levels in weight along with the stat multiplier settings in ASB?

**Comment by Zyles** [comment]
I don't think it was yellow.

I did another extraction on this Sarco. See image with the very high weight stat.

The weight total checks out, but the stat is way off.

Binos say:
HP 29 +1
ST 35
FO 29
WE 23
DM 45
SP 36
OX 29

![sarco_stats](https://user-images.githubusercontent.com/1741593/52246950-1d438a00-28e8-11e9-8d26-a4f6df4201f8.png)

**Comment by Zyles** [comment]
Server settings can be found here if it helps: https://jamonparadigm.com/ark-servers

**Comment by Zyles** [comment]
Doh!

Apparently the server has some kind of weight boost event on temporarily. Which is why this is completely off.

I made a calc with the bino stats because they show the non weight boosted stat which is correct and it checks out.

Thank you.
