### ISSUE TITLE
Extracting multipliers from Game.ini

### ISSUE THREAD

**Issue by VeaceslavGrigoras** [cadon/ARKStatsExtractor#88]
Hello. I tried to extract and figure out the multipliers from the Game.ini file from my server (I changed them using a custom control panel), but I cant figure out exactly which is which since in the panel they have a little bit different name. It would be a nice feature if the program could extract the multipliers directly from a Game.ini file provided by the user.

Thank you.

**Comment by cadon** [comment]
Hi, good idea, I'll think about it. For now, here're the names of the game.ini you need:
PerLevelStatsMultiplier_DinoTamed_Add, PerLevelStatsMultiplier_DinoTamed_Affinity, PerLevelStatsMultiplier_DinoWild, PerLevelStatsMultiplier_DinoTamed.

You can find out what number the different stats have in the list here: https://ark.gamepedia.com/Server_Configuration (search for the parameters).

**Comment by cadon** [comment]
The feature is added and released (-> 0.20.5).
