### ISSUE TITLE
Import from savegame, Lystrosaurus listed as Abberant Paraceratherium

### ISSUE THREAD

**Issue by Lord-Mercury** [cadon/ARKStatsExtractor#880]

**Comment by cadon** [comment]
do you use a mod that changes creatures like the Lystrosaurus?

**Comment by Lord-Mercury** [comment]
Yes, [Improved Lystrosaurus](https://steamcommunity.com/sharedfiles/filedetails/?id=923689156).

**Comment by cadon** [comment]
Then the blueprint-path and probably the DinoClass-name of the modded species is different, so it cannot be recognized. I'll look into it if that can be fixed.

**Comment by cadon** [comment]
The current version needs mod-value files for each used mod with new or changed species. Mod value files can be requested in the [discord-channel of ASB](https://discord.gg/qCYYbQK).
