### ISSUE TITLE
Extraction Issue

### ISSUE THREAD

**Issue by Snowwolf-WB** [cadon/ARKStatsExtractor#881]
Hi all,
I am having an Issue that the extracted data is not correct.
Then I input the correct Info and still, I can not save the Dino to my library.
The setting are from my hosted server and i have checked and doubble checked and they are correct.
Can someone have a look? if you need any further Info please let me know.

Thanks
![server 1](https://user-images.githubusercontent.com/47764753/52985328-ae8c2380-33f3-11e9-949e-134df70e5609.jpg)
![server 2](https://user-images.githubusercontent.com/47764753/52985329-b055e700-33f3-11e9-87b1-059373d37135.jpg)
![server 3](https://user-images.githubusercontent.com/47764753/52985331-b4820480-33f3-11e9-937e-d79fb65be298.jpg)
![server 4](https://user-images.githubusercontent.com/47764753/52985336-b64bc800-33f3-11e9-9849-4914fdbb1950.jpg)
![server 5](https://user-images.githubusercontent.com/47764753/52985338-b8158b80-33f3-11e9-8a3f-ed41aa3a335f.jpg)
![server 6](https://user-images.githubusercontent.com/47764753/52985459-35410080-33f4-11e9-90d0-47292abbff89.jpg)
![tame 1](https://user-images.githubusercontent.com/47764753/52985341-b946b880-33f3-11e9-87fd-63ecc217695d.jpg)
![tame 2](https://user-images.githubusercontent.com/47764753/52985342-bb107c00-33f3-11e9-9764-e7940ba40600.jpg)
![tame 3](https://user-images.githubusercontent.com/47764753/52985344-bcda3f80-33f3-11e9-9064-4bec0c706e3a.jpg)
[dino level.txt](https://github.com/cadon/ARKStatsExtractor/files/2877933/dino.level.txt)

**Comment by VolatilePulse** [comment]
Had a look over your multipliers and you actually missed the Speed TameAdd value of 1.3 and you typed in the Torpor value incorrectly as well in the extractor. You can view the attached screenshot that has the successful extraction with the corrected multipliers.

I would suggest using the creature export feature of ASB so you won't have to worry about a repeat of the torpor typo (or similar stats) in the future. Information can be found [here](https://github.com/cadon/ARKStatsExtractor/wiki/Importing-Creatures#ark-exports). If you have any future issues, a quicker response can typically be found on our [Discord](https://discord.gg/qCYYbQK).
![image](https://user-images.githubusercontent.com/6995232/52995229-f907a300-33e7-11e9-8c62-e26c667f279f.png)
