### ISSUE TITLE
Possible user error - Importing ark, only imports data as it was at shutdown?

### ISSUE THREAD

**Issue by Wulf2k** [cadon/ARKStatsExtractor#883]
There are a few possible things going on here.

Nitrado server, xbox/UWP.  Save version 10, hex edited to 9 to allow the tools to run.

SmartBreeder is only giving me the status of my animals as they were at the daily server restart, even if I manually give the saveworld command and redownload.

Any idea if there's a live data vs resting data split in the ARK file?

I can restore the server to these ark files without losing the data between server restart and when they were taken, so it's not a simple matter of the file not being written.

**Comment by cadon** [comment]
I haven't heard that there are multiple savefiles. Maybe the creature's data is not updated in ASB? Can you try to import the newer savefile in a new library with no creatures and check if their data is outdated as well?

What data did you notice is not updated? Domesticated levels or creature names?

**Comment by DodoCooker** [comment]
I'm using nitrado and have to say: It is a matter of the file not getting written. If you download the save you'll always get the state of the last restart (Im running a windows server but assume its the same for X-Box). But you should be able to download the compressed backup files - unpack them locally and then import the Backup into the breeding program.

**Comment by Wulf2k** [comment]
cadon:  It's most obviously noticeable with deaths/births/tames.  Creatures don't appear or disappear until I import a post-restart save.  Based on DC's comment, I'll assume this is not an issue and fully my error.

DCodoCooker:  Before creating the issue I'd downloaded what I thought to be the latest .tar.gz copy from the folder and checked it as well, and it still didn't have a creature I'd had tamed for a while.  I should've been more thorough, but you seem confident so I'll just assume that I somehow extracted the wrong copy.  I should probably figure out the timezone offset between Nitrado and myself to be sure of what I'm extracting.

The main difference between Xbox and PC with Nitrado is that for Xbox they do everything they can to stop you from accessing the files directly.

Later tonight I'll tame something up, issue a saveworld command, and then 20 minutes later download both the ark file and the compressed backup.  If I'm remembering right, the gametime should be somewhere in the header for easy comparison.

I'll close the issue after confirming.

**Comment by Wulf2k** [comment]
I didn't do any pet testing, but I can confirm that the incremental save counter was far lower in TheIsland.ark pre-restart than it was immediately following a restart.  I'll just need to be more careful which timestamped backup I'm using from now on.
