### ISSUE TITLE
"value of 10000 is not valid for 'Value'

### ISSUE THREAD

**Issue by Wulf2k** [cadon/ARKStatsExtractor#884]
https://pasteboard.co/I2TxBA9.png

Was looking into a creature that somebody downloaded to my server.  I'm 99.99% sure it was just spawned at a ridiculous level instead of bred, but I got the above error when I right clicked, Edited.

**Comment by cadon** [comment]
Did you click on the selected creature (named HMo) with a torpor-level of 345? Does it have 10000 domestic levels applied? Do you see a level of 10000 somewhere?

**Comment by Wulf2k** [comment]
https://pasteboard.co/I3a3gV7.png

Nothing seems obviously wrong with him in the mini-preview, level 399/417.

I do suspect this dino was spawned on a server with silly multipliers, but I don't suspect the player of being capable of modifying the values directly.  I'm not sure which value would be 10000 for it.

"OMG", the allo directly below it belonging to the same player, gives the exact same error.

Hmo and OMG appear properly in the breeding plan with stats between 40-55.

**Comment by Wulf2k** [comment]
Here's a copy of the ark file if you'd care to see for yourself:

https://fileshare.uhn.ca/download/e6c6fafe-bfbd-453a-924e-7779e7e44735

(Note:  I've never used the above server before, let me know if there's anything sketchy or annoying about them and I'll find somewhere else)

**Comment by cadon** [comment]
I can't access this file ("only accessible from within the  UHN-network"). You can upload the xml-library-file of ASB by just drag&drop it here.

**Comment by Wulf2k** [comment]
<Creature>
      <species>Allosaurus</species>
      <name>HMo</name>
      <sex>Female</sex>
      <status>Available</status>
      <levelsWild>
        <int>43</int>
        <int>40</int>
        <int>36</int>
        <int>54</int>
        <int>58</int>
        <int>63</int>
        <int>51</int>
        <int>345</int>
      </levelsWild>
      <levelsDom>
        <int>5</int>
        <int>20</int>
        <int>5</int>
        <int>0</int>
        <int>5</int>
        <int>18</int>
        <int>0</int>
        <int>0</int>
      </levelsDom>
      <tamingEff>1</tamingEff>
      <imprintingBonus>100</imprintingBonus>
      <owner>MOI</owner>
      <imprinterName>MOI</imprinterName>
      <tribe>War Turtle</tribe>
      <server />
      <guid>025228fb-178a-1a9c-0000-000000000000</guid>
      <ArkId>0</ArkId>
      <ArkIdImported>false</ArkIdImported>
      <isBred>true</isBred>
      <fatherGuid>0e9b1f7a-2049-0e64-0000-000000000000</fatherGuid>
      <motherGuid>00e046d9-5b6a-13ae-0000-000000000000</motherGuid>
      <generation>1</generation>
      <colors>
        <int>33</int>
        <int>32</int>
        <int>32</int>
        <int>32</int>
        <int>26</int>
        <int>33</int>
      </colors>
      <growingUntil>0001-01-01T00:00:00</growingUntil>
      <growingPaused>false</growingPaused>
      <cooldownUntil>0001-01-01T00:00:00</cooldownUntil>
      <domesticatedAt>2019-02-22T11:44:59.1979693-06:00</domesticatedAt>
      <addedToLibrary>2019-02-22T11:44:59.1979693-06:00</addedToLibrary>
      <neutered>false</neutered>
      <mutationsMaternal>0</mutationsMaternal>
      <mutationsPaternal>0</mutationsPaternal>
      <tags />
      <IsPlaceholder>false</IsPlaceholder>
      <growingLeft>PT0S</growingLeft>
    </Creature>

**Comment by Wulf2k** [comment]
[ark.xml.txt](https://github.com/cadon/ARKStatsExtractor/files/2937834/ark.xml.txt)

**Comment by cadon** [comment]
Hi, thanks for the file. It seems this creature has an imprinting-value of 10000 %. Probably an admin used the command `SetImprintQuality 100`. The usually used number for this command is between 0 (=0 %) and 1 (=100 %). Values greater than 1 obviously work, but are probably not intended. If you want to increase the imprinting bonus, it's advised to rather increase the babyStatScaleMultiplier.
Usually the imprinting bonus will not exceed 100 %, with some mods (S+ nanny) it sometimes reaches values around 102 %. Currently ASB can handle values up to 1000 %. I'll increase the value to up to 100 000 % in the next release.

**Comment by Wulf2k** [comment]
Obviously this guy set up some server to spit out animals without understanding what he was doing before downloading it to mine.

Thanks.
