### ISSUE TITLE
GUI issue under Taming tab/Weapon Damage

### ISSUE THREAD

**Issue by harry323** [cadon/ARKStatsExtractor#887]
There is a rendering issue with the weapon damage table where two items overlap. 
![image](https://user-images.githubusercontent.com/46381622/53698258-b5297c00-3d9f-11e9-8083-d3864234f7e2.png)

**Comment by cadon** [comment]
What species was selected before and what species is selected now?

**Comment by harry323** [comment]
The currently selected species is Megalosaurus. And I think the previous one was a Giga. I can't say for certain on the previous but it's the one that's listed as the previous one when I do a species search.

**Comment by cadon** [comment]
It's not showing this issue for me. Does it look for you like this all the time, or only for specific species, and does it matter what species was selected before?

**Comment by harry323** [comment]
Sorry for resurrecting an issue but this is still happening. It's doing it on Therizinos as well. Basically any creature that has a target bonus box.

![image](https://user-images.githubusercontent.com/46381622/71784690-a319fa80-2fbb-11ea-9d9c-92edbeb2baf2.png)

**Comment by cadon** [comment]
sorry for the long delay. The issue is most probably caused by the display scaling of windows. I changed how the controls are drawn, it should be fixed in the next release.
