### ISSUE TITLE
OCR for 1366x768 w/ gamecapture on Switch

### ISSUE THREAD

**Issue by MavDarkness** [cadon/ARKStatsExtractor#889]
Having an extremely hard time getting this to work, even followed steps to get the two to work together from the OCR part of the wiki on here. if anyone has gotten this to work please post it here :) i will also update as i work on this.

**Comment by cadon** [comment]
Hi, sorry to tell you, but at this resolution the OCR probably won't be much of a help, maybe typing the values manually will be faster. That said, by tweaking the OCR by adjusting the labels and single characters, you can improve it a bit. I have no config-file for this resolution yet.
