### ISSUE TITLE
Export Imported Data window will not pop up. 

### ISSUE THREAD

**Issue by TaiineLee** [cadon/ARKStatsExtractor#892]
Whenever I try and import the dinos I've exported from game, the import window doesn't seem to exist. 
![image](https://user-images.githubusercontent.com/48498912/54310518-f47a7880-45a8-11e9-9219-c3b850864aa4.png)
As seen, it's 'there' but no window pops up and often it just pops up as a black bar in that preview. Before it would show the window proper like it does for the main program. 
I've even done tricks to 'reset window position' thinking it may have just been dragged off screen somewhere, but nope. After I installed this current update the window just will not show. I've been forced to rely on the overlay to snatch my dinos info. 
I've already reinstalled and the issue is the same. 
What would be causing this?

**Comment by cadon** [comment]
The size and location of this window are saved in the application-setting (not directly accessible by users), so if it was somehow offscreen, it will always open there, until it's moved back manually. You wrote that you already tried moving it back, so just to make it's not that, try to move the cursor on the window (like in your screenshot), then hold the Shift-key and right-click, then choose `Move`, then tap an arrow-key on the keyboard (e.g. the up-key), then move the mouse, until the window appears.

The fact that in the task-bar preview the window appears to be empty is strange, though. Is the set folder for the import exported creatures in the settings valid?

You can also check the event-viewer ([how to open it](https://www.dummies.com/computers/operating-systems/windows-10/how-to-use-event-viewer-in-windows-10/)), if there is any info about an issue (in the tree-view left top choose event-viewer - windows protocols - application).

**Comment by TaiineLee** [comment]
I have tried the shift/rightclick/move but nothing happens. The set folder is valid and what I've been using before. I have dinos already imported before I installed the update by deleteing all of the files (the xml file for dino info are off dropbox for all tribe members to access) and just dumping in the new. But everything I have tried thus far with the current version up does this. 
I don't see anything with it in the event viewer.  
I even dumped the program, via the zip, and the install into a whole new folder location, for a full fresh reinstall, and same thing. This window just will not pop up like it use to before. No one else in the tribe reports this, but its only myself and two others who are the breeders and I'm not sure if they updated or not. I assume least one has not as they didn't know what I meant when I brought up being stuck using the overlay button to grab stats atm.

**Comment by cadon** [comment]
I could reproduce this issue. It seems it happens if the importExport was minimized before closed.
The window could be retrieved by using the above described solution (Shift + right-click - Move, then press an arrow key once, then move the mouse). I'll include a fix in the next release.
