### ISSUE TITLE
Library - Parent select from wrong gender

### ISSUE THREAD

**Issue by SpeedHighway** [cadon/ARKStatsExtractor#9]
I have two Beelzebufos.  Both are female with the ♀ symbol selected in the Library.  The symbol has the pink background, as well.
For some reason, the Extractor has decided that one of them was bred (I did NOT select this, so I don't know why.)  

More importantly, though, when it allows me to pick the parents, it lists the female dinos under the male selection, and nothing under the female section.  I know that it shouldn't have classified this dino as bred, so maybe that's the issue, but it's still definitely pulling the wrong gender.

**Comment by cadon** [comment]
Hi, thanks for the feedback.
In this tool male and female are displayed with their gender symbol (♀/♂), and father and mother are abbreviated with F and M respectively. Unfortunately these two letters are the same as for the genders, but switched. I added a tooltip to the letters to make it clearer, just hover your cursor over one of the letters to see it.

The tool assumes a creature is bred if its taming effectiveness is 100% (or almost 100% due to rounding errors). Normally non-bred animals never reach this range (maybe lowlevel creatures tamed with kibbles can). Your case shows that this approach can yield false results, so I need to change it. Are you playing on an official server? How did you tame the creature, what level / stats does it have?

To fix the bred-status of the creature you can edit your save-file. Look for your creature and change the line
`<isBred>true</isBred>`
to
`<isBred>false</isBred>`
.

**Comment by SpeedHighway** [comment]
Thanks for the information on fixing the bred-status of the creature.  

As for the 100%, it may have to do with this particular server being set to 10x taming.  An Anklyo, for example, will tame at 100%, with kibble, at level 33 and under and 99.98% - 99.99% up to 120.  As for the beelzebufo, it was tamed with just prime meat (I think it took about 5-6 on the 10x server).  The tool calculated it out at 100%, though, I suppose.  I chose 90-100% as my range, because I didn't remember.

I'm not sure what you mean in your first paragraph.  When I edit a creature, there's a Mother and a Father field.  I assumed that these were a place to designate which other creature was the current one's mother, or father.  However, I have 2 female Beelzabufos, and when I edit the one that's set to 'Bred', there's nothing in the mother column, but the other frog is in the father column.  I'm not sure why anything would be in the father column between a set of two female frogs.

**Comment by NakramR** [comment]
There is technically no difference between a bred dino and a dino tamed with 100% efficiency. Only having parents or not.

**Comment by SpeedHighway** [comment]
Your comment has absolutely nothing to do with the ticket and closing it was inappropriate.

**Comment by NakramR** [comment]
You are correct, I misclicked. It has to do with the fact that the "bred" flag is indistinguishable from 100% efficiency.
Also, if you have wildly different stats, posting said stats would be helpful (screenshots or the actual values)

**Comment by SpeedHighway** [comment]
I'll try and get some screenshots, when I get home, later, to illustrate the stats issue.  Thanks for re-opening.

**Comment by cadon** [comment]
A new version with the option to set a creature to "bred" or "wild" is released.
Regarding the not working dinos: There is likely a bug in ARK, that after a stat-changing, the numbers don't change until a stat is leveled up. I suggest to level up any of the stats of a not working creature, close and reopen its inventar and try it with these numbers again. Maybe you also have to log off/on for the stats to update, or even the server has to be restarted. But I hear that after spending a point in a stat the values are correct.
If you don't want to spend a levelup in these dinos, you can set the values of the calculator to the old values and then extract the stats, that should work, too.

**Comment by SpeedHighway** [comment]
Thanks, I'll try it.  (The server was down all weekend - Thanks Gameservers.com for your "24/7 uptime" - so I was unable to get screenshots for you.)

**Comment by cadon** [comment]
Could you solve the problem?

**Comment by SpeedHighway** [comment]
The new M/F should be easier to understand, thanks.  As for the stats, the server's down, so I can't do anything with it.  I haven't used the app, recently, because it wasn't allowing me to add more than 60% of my dinos due to red numbers (which isn't mentioned in the documentation, btw).

**Comment by cadon** [comment]
Red numbers always mean that the levels couldn't be extracted. IMO without the numbers it doesn't make sense to add a dino to the library (all its displayed information would be misleading and useless).

Did you try all the suggestions mentioned in the doc regarding the red numbers and red controls? If nothing helps, upload a screenshot or send the numbers, so I can check if it's a bug in the tool.

**Comment by cadon** [comment]
I guess the issue is solved. If not, just reopen.
