### ISSUE TITLE
Using the tool under Linux/Ubuntu

### ISSUE THREAD

**Issue by VeaceslavGrigoras** [cadon/ARKStatsExtractor#90]
Hello.
Is it possible to use this tool under Ubuntu? Does it use any specific features? Is it better to recompile under Ubuntu or use wine?
Thank you.

**Comment by cadon** [comment]
The tool is based on .NET, so at least this has to run on the OS you try. Maybe http://www.mono-project.com/ can help you, but I haven't tried that. Wine could work, if .NET runs there.

**Comment by watchingJu** [comment]
Can confirm ... it works with Wine on Xubuntu 14.04.
