### ISSUE TITLE
Manually entering tames, Xbox, constant red

### ISSUE THREAD

**Issue by ElderZimm** [cadon/ARKStatsExtractor#900]
I am using the application, while manually entering tames I cannot get it to take any of my tames. I have used Troodon, Tuso, Gigantopithicus, etc and always have at least one stat go red while extracting.

Official PvP on xbox, what settings could I have off? Please help!

Using default settings and selected "Use official settings" button.

**Comment by VolatilePulse** [comment]
I've used the program fairly extensively with Xbox and aside from small hiccups in the past, Xbox Ark is basically the same as Steam Ark, which is what ASB was designed for. That said though, can you post some screenshots of failed extractions so we can help figure out the issue?

As a side note, Troodon and Pegomastax are currently bugged in Ark and may/may not extract properly. Also imprinted creatures suffer from an imprinting bug, but there are workarounds for that as well.

**Comment by ElderZimm** [comment]
Should I post screen shots of the creature stats? From inventory? As well as the failed extraction? I can get several examples.

**Comment by ElderZimm** [comment]
Also are default settings accurate for official?

**Comment by ElderZimm** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/49173741/55445113-8523f300-556e-11e9-8754-d33d9780b524.png)

**Comment by ElderZimm** [comment]
One quick example, will get more, but I also can't save to the library, is this due to the errors?

**Comment by ElderZimm** [comment]
Also are you imputing manually? I play on the actualy Xbox, not just the xbox version to exporting from the game files I have no idea how to do that.

**Comment by VolatilePulse** [comment]
Come talk to me on [Discord](https://discord.gg/qCYYbQK). Username is Mr. Plow.

**Comment by ElderZimm** [comment]
Issues resolved for now, thank you
