### ISSUE TITLE
HDR colour support

### ISSUE THREAD

**Issue by coldino** [cadon/ARKStatsExtractor#905]
We've already identified an issue with colour matching from export file where HDR values are included (usually only for mutations, but not always).

To fix it we're going to need a better source of true colour data (https://ark.gamepedia.com/Color_IDs does not include this). We're working on this.

**Comment by coldino** [comment]
There may be other issues with colour matching.

Discord user Top Knight reporting incorrect colours for the following creatures, and none of them appear to be HDR:
[DinoExport_3178180145245096.ini.txt](https://github.com/cadon/ARKStatsExtractor/files/3077836/DinoExport_3178180145245096.ini.txt)
[DinoExport_12791971245399899.ini.txt](https://github.com/cadon/ARKStatsExtractor/files/3077837/DinoExport_12791971245399899.ini.txt)

**Comment by cadon** [comment]
HDR colors are now supported when importing.
