### ISSUE TITLE
Issues Syncing Database with Dropbox

### ISSUE THREAD

**Issue by wowregistering** [cadon/ARKStatsExtractor#907]
Using Ark Smart Breeding with a database loaded from a shared Dropbox folder causes a few issues that are preventing me and a few friends from making use of it.

1.  If multiple people make a change within ~10 seconds of someone else making a change only the first change goes through

2. Attempting to remove Entries from the Library is impossible, the database readds the Entry to the database from the other users Library. 
Ex, Member 1 deletes 'dilo123' and now dilo123 is gone on their library, dilo123 still exists on Member 2's Library.  A few seconds later 'dilo123' reappears on Member 1's Library.

I have tried using Google Drive, Dropbox, and a Local Networked folder on different computers in my house and ended up with the same syncing issues on all of them.  

The only Difference between the three syncing locations is the amount of time 'syncs' get lost.  As in, on google drive it would fail to update if changes were made within ~25 seconds, Dropbox ~10 seconds, Local Network share ~5 second.

The Local Share almost eliminates the problem, I can't use the local network share with my friends who do not live with me though.

**Comment by coldino** [comment]
This is as good as the current design can get, unfortunately. It really isn't designed for simultaneous use, but if you have a quick sync time and are editing different creatures there are normally very few problems.

Deleting is also not possible if more than one copy of the library is loaded. Use mark as dead or tagging as a workaround, then delete when only one client has the file open.
