### ISSUE TITLE
Import dino overwriting doesn't overwrite mutation count

### ISSUE THREAD

**Issue by JuicyJuuce** [cadon/ARKStatsExtractor#910]
When a dino is already in your library and you import it again, it should update the information in the library. It does this for every trait except the mutation count.

In the linked gfycat example, the doedicurus in the library has a mutation count of zero for both paternal and maternal, however the actual dino has one maternal mutation (this wasn't captured on the original import because I had not opened its "Show Ancestors" window before importing it). When importing again with the corrected export info, it should update the mutation count but does not.

https://gfycat.com/honestflatazurevase

**Comment by cadon** [comment]
Hi, updating the mutationcounters will be added in the next release. Usually these values won't change, but when importing a creature without opening the ancestors screen first will not import the parents and the mutations-counter, so that's probably what happened here. Thanks for bringing this up.
