### ISSUE TITLE
(x) Mother/Father of removal

### ISSUE THREAD

**Issue by arathein** [cadon/ARKStatsExtractor#914]
Hello - I don't know if this would be a bug of feature request.
I'm not sure the point of the "(x) Mother of..." and "(x) Father of..." entities but for me they are annoying as you can't get rid of them without going into the XML of the library file and tracking them down and deleting the lines.

I created a new library so I could get away from these and now upon importing some dinos it ihas again created these items because it doesn't know who the parent is.  If it doesn't know why can't it just stay blank instead of tossing in this undeletable entity?  If you have these in a library and you delete all the creatures of that species, all these mothers and fathers of remain so the species still lists in the library with no critters.

So if this isn't a bug I guess the feature request would be able to have an option to delete, or even not use the those items when ASB can't figure out the parent.

Thanks!

**Comment by cadon** [comment]
Hi, where do these entries appear and annoy you? They should not appear in places where they would be useless (e.g. the library) and are needed for handling the links between parents and descendants.

**Comment by arathein** [comment]
The problem comes in when you remove the dinos.  So for example, I removed all the otters from my library, otters were still listed as species.  I had to remove the Mother/Father of in the XLM to actually get it to go away.  I was trying to take my main library and break it out by species so I could share specific species with my tribemate easier. 
I ended up just unpodding re exporting and importing them into a new library. Then of course it started there.
I personally don't see what having a "Mother of X" vs having that parent blank gains in the ancestry/pedigree but that is just me.  I change all mine back to blanks, but that doesn't remove the background entity that was created so Mother of X always shows up as in the drop down.

**Comment by cadon** [comment]
Ah, I see. I haven't thought about the scenario that creatures are being deleted and leaving the parent-entries. I'll think about a solution for this.
There's an important reason these entries exist. Once you import a creature, the parent-entries are created automatically, and are recreated if necessary every time the library is loaded. Only this makes it possible to import a creature before importing its parents and link them correctly. This whole procedure should not affect the user, but as you wrote, when deleting creatures the remining parent entries can be annoying.
