### ISSUE TITLE
Point distribution oddity

### ISSUE THREAD

**Issue by ProvokeMe** [cadon/ARKStatsExtractor#916]
Seems the Smart Breeder is incorrectly seeing where prior points have been distributed.  All the stats are green but Smart Breeder thinks I have applied 37 points where I have distributed 47.  This is noted in the extraction screen.  Not sure how to fix/edit this.

Thanks.
![ArgySmartBreeder](https://user-images.githubusercontent.com/51295668/58764268-227db200-8533-11e9-8a2e-da6a13c94da7.JPG)
![ArgySuperScope](https://user-images.githubusercontent.com/51295668/58764271-27426600-8533-11e9-9e62-e30b7bd44324.JPG)

**Comment by coldino** [comment]
Yes, the extraction for weight is very wrong. We'll need more information from you to help:
 * Server multipliers (a screenshot of your ASB settings).
 * Whether you are using any mods that affect creatures.
 * Do other creatures export correctly?
 * The exported creature file, if possible (see https://github.com/cadon/ARKStatsExtractor/wiki/Importing-Creatures)

One thing you can try is turning off "Exactly, don't adjust" for the TE as this is never the case unless the creature was spawned in by an admin.

**Comment by ProvokeMe** [comment]
[cid:image001.png@01D51953.91D2F800]

The map we’re using on our hosted server is Ebenus Astrum.

The “Rare Sightings” mod.
Kraken’s Better Dinos mod

Those are the only ones that I believe would adjust dinos.

Yes.  I have extracted four Direbears successfully.  I have extracted another Argentavis correctly, as well as other dinos.  This one appears to be particularly stubborn.


One thing you can try is turning off "Exactly, don't adjust" for the TE as this is never the case unless the creature was spawned in by an admin.

I have tried it all ways, but I’ll try again.

**Comment by coldino** [comment]
Velox Argentavis is a modded species from the map. There's no support for that currently.
