### ISSUE TITLE
Gacha

### ISSUE THREAD

**Issue by Vakarian96** [cadon/ARKStatsExtractor#917]
Gacha lacks the value of CraftingSkill

**Comment by cadon** [comment]
The gacha is not supported in the latest release. You can try a beta release in the discord-channel (see the channel beta) to try it. Note that this beta-version uses a different library-file format, so if you open an existing library, it will be converted and cannot be opened with the release-version anymore (a backup will be created, though). Feel free to test the beta version, if you find any issues, let us know.
