### ISSUE TITLE
HP on Anky reads correctly, but does not get accepted as valid (Red).

### ISSUE THREAD

**Issue by Belboz99** [cadon/ARKStatsExtractor#918]
I've tried reentering it manually in case some special characters were inadvertently thrown in by the OCR, I've double-checked all the other stats.  What's peculiar is it doesn't even register as any number of points towards that stat.

![Anylosaurus_error](https://user-images.githubusercontent.com/50673400/59117284-fbe4c000-8912-11e9-887b-f81ce3e5d267.png)

**Comment by VolatilePulse** [comment]
You're attempting to extract an Aberrant Ankylosaurus as a normal Ankylosaurus. The Aberrant variant has different health multipliers. Changing the species should resolve this issue.
