### ISSUE TITLE
Bulbdogs Charge Capacity shows as "Stamina" within Pedigree and Breeding Plan tabs.

### ISSUE THREAD

**Issue by Belboz99** [cadon/ARKStatsExtractor#919]
As title says.
![Bulbdog_Stamina](https://user-images.githubusercontent.com/50673400/59117567-ae1c8780-8913-11e9-8344-1f00217fa697.png)

**Comment by cadon** [comment]
Hi, thanks for the report, this will be fixed in the next release.
