### ISSUE TITLE
Add Deinonychus

### ISSUE THREAD

**Issue by Hayath** [cadon/ARKStatsExtractor#923]
Hello ! 

As Deinonychus appears with the new official Valguero map, have you planned to add it ?
It would be so great !

Thanks a lot for your work on Smart Breeding.

**Comment by coldino** [comment]
There's an experimental `values.json` file available for testing in our Discord server.

If you aren't able to get it from there let us know and we'll put a copy here too.

**Comment by Hayath** [comment]
Thanks ! I found it.

**Comment by VolatilePulse** [comment]
For those that are still looking for the Deino support, an updated [values.json](https://raw.githubusercontent.com/cadon/ARKStatsExtractor/master/ARKBreedingStats/json/values.json) file can be found here. Simply close ASB, replace the existing values.json file (found in the ASB/json directory), and launch ASB again.

**Comment by injuringeternity** [comment]
I downloaded the file linked above, closed ASB, replaced the values.json with the downloaded file, and launched ASB.  However, when I go to import exported data in ASB, the Deino that I just exported from Ark is not appearing.  

Thanks so much for all your work in ASB, not having it for the Deino has reminded me how much I rely on it!

**Comment by coldino** [comment]
Maybe you are using the installed version of ASB? If so, you need to save the new `values.json` into `%localappdata%\ARK Smart Breeding\json`. You should be able to copy/paste that location into the Explorer to get there.

**Comment by injuringeternity** [comment]
That worked perfectly, thank you so much!!
