### ISSUE TITLE
Breeding Plan Scores

### ISSUE THREAD

**Issue by TerraSleet** [cadon/ARKStatsExtractor#924]
Hi,
I am having trouble understanding how the Breeding scores are calculated, they seem to suggest sub-optimal pairings. My goal is to breed an Argentavis with the 4 main top stats (HP, Wt, Stm, Dmg), so I selected Top Stats Conservative for this. I also set the weightings on Food + Oxy + Speed to 0. Yet the breeding plan seems to suggest I breed a pair with a much lower chance of getting a max baby. 

See the two attached screenshots, my conclusion is that the lower pair (Unnamed 139 + Unnamed 152) should have a much higher breeding score due to the higher likelihood of producing a top statted baby and the fact that 3 of the 4 desired stats are shared by mother + father, is this correct? Is the breeding score calculation bugged or do I not understand it?

![image](https://user-images.githubusercontent.com/8026531/60578784-bd0f2200-9d79-11e9-9964-ced9b1b57713.png)

![image](https://user-images.githubusercontent.com/8026531/60578730-9ea92680-9d79-11e9-94ad-6a1ab99d67b3.png)

**Comment by DodoCooker** [comment]
The breeding score consists of the actual level of a stat, the top level of it and for conservative also the gender of the dino. In conservative having another male with the same stat makes the score go down a lot and having another female reduces it but not by as much as a male would. This influences the suggestions. From experience i'd say conservative is good for the most part of the breeding but when you get to a point where you are only missing one stat the lucky mode might give better options to get to the goal. 
All in all you can say that the algorithm is good but if you have a little experience in breeding its also good to second guess its suggestions like you did and for your example to go for the 3rd option instead.

**Comment by DodoCooker** [comment]
After having a look at the source i found a flaw with setting at least one stat weighting to 0.0 - There is now a pull request that will improve conservative breeding with 0.0 weight settings.

**Comment by DodoCooker** [comment]
![breeding](https://user-images.githubusercontent.com/4038417/60588482-58fb5680-9d97-11e9-9b3c-a2b7b41033c7.png)
Thats what it would look like with that change (conservative breeding with the 3 stats set to 0.0).

**Comment by TerraSleet** [comment]
Ok, but the question still stands: is the algorithm wrong here? According to the description in the manual of Top Stats Conservative, "Following the top-suggestion in this mode will result in the fastest way to receive a creature with all the top-stats." Yet this scenario seems to depict the opposite - a pairing with a 16.6% chance of creating the best outcome has a much lower breeding score than a pairing with a 2.8% chance of _the same outcome._

**Comment by DodoCooker** [comment]
I guess the short answer is yes the algorithm was indeed wrong - but should my fix make it into the master it will be changed to work better. Currently the algorithm degrades a little when at least one stat is set to 0.0 weighting.
