### ISSUE TITLE
Trouble with argys and classic flyers.

### ISSUE THREAD

**Issue by ITheWolfyzI** [cadon/ARKStatsExtractor#926]
When trying to extract level distribution on flyers that have had levels into movement speed it will not recognise these levels as real, and this also turns health red. Anyone else with this problem or a fix?

**Comment by VolatilePulse** [comment]
Have you loaded the additional values file from within ASB? The program is set to support official creatures and that feature enables custom mod creatures, like ones from classic flyers, to be extracted properly.

**Comment by ITheWolfyzI** [comment]
Thank you very much for this fix. I was unable to find it elsewhere, you have helped me massively :)
