### ISSUE TITLE
New version of values file json/values.json

### ISSUE THREAD

**Issue by Sivarias** [cadon/ARKStatsExtractor#932]
Alright so I click on check for updates and it tells me there is a new version of the values file "json/values.json".  You have 294.101, available is 297.64.2.  Do you want to update it?"  I click yes and then it says Error while checking for values-version, bad remote format.  An exception occurred during a webclient request.  Try checking for an updated version of ASB."  I have the most updated version of the ASB since I just downloaded it a few days ago.  How do I go about fixing this?

**Comment by cadon** [comment]
There's currently a bug, you can download that file manually to fix that, see https://github.com/cadon/ARKStatsExtractor/issues/923#issuecomment-513090580 .
