### ISSUE TITLE
Possible issue with dino stat importing

### ISSUE THREAD

**Issue by radicaled06** [cadon/ARKStatsExtractor#934]
Hello! 
I've tried importing dinos from my unofficial private server, using both the OCR and file import functions. Some of my dinos do not seem to be able to be given correct values, even though I have set ASB to our server settings. We've not changed any stat values at all, simply timers such as taming speed, hatching speed, etc. Stats should remain at official server values. Other than the fact that we have also increased max level caps and such. 
Am I doing something incorrectly? Or is this an issue with the stats themselves? I have updated the json file from here to the current version via the install, but I'm not sure how to change the local json file. 

![20190723013309_1](https://user-images.githubusercontent.com/31147307/61685228-0ce26880-acea-11e9-8e1a-fd495df18fab.jpg)

![Capture12](https://user-images.githubusercontent.com/31147307/61685275-41eebb00-acea-11e9-8d4a-2adeda572e00.JPG)

![Capture13](https://user-images.githubusercontent.com/31147307/61685305-5b900280-acea-11e9-8483-9ea6b547c884.JPG)

**Comment by VolatilePulse** [comment]
I'm not sure what the exact issue is yet, but you're definitely using a creature mod, something like Classic Flyers or Naj's Speedy Flyers. These mods alter the stats of creatures and require ASB to have these new values loaded for it to properly extract them. I tried using both of the aforementioned mods but neither allowed that ptera to extract. Which creature mods are you using?

**Comment by radicaled06** [comment]
We are using the "Improved Flyers" mod to give us the ability to add movement speed points. 

https://steamcommunity.com/sharedfiles/filedetails/?id=1402519919

**Comment by radicaled06** [comment]
I've decided to change our flyer mod, I originally chose that one because it was the most recently updated, but I see now the other two have been updated much more recently. And it simplifies a lot of things. You can close this, it is related to the mod we were using. =]

**Comment by VolatilePulse** [comment]
I figured as much. I was going to see about getting you a file to support it, but got tied up with other issues last night, sorry. I'm assuming you've figured out how to load the additional values to support modded creatures then?

**Comment by radicaled06** [comment]
Yes, I've switched to using classic flyers, we used it before too. And I've imported the stats for that mod. It works, thank you! =]
