### ISSUE TITLE
Deinonychus can not be imported

### ISSUE THREAD

**Issue by Jimbodiah** [cadon/ARKStatsExtractor#938]
Is there a way to add new dinos so they can be imported? Deinonychus and some modded dinos can not be imported.

**Comment by cadon** [comment]
mods need extra mod-value-files to import them. Currently there are a few supported mods, e.g. Classic Flyers. For support of the Deinonychus you can manually save the file [values.json](https://raw.githubusercontent.com/cadon/ARKStatsExtractor/master/ARKBreedingStats/json/values.json) and replace your current one.

**Comment by Zhinjio** [comment]
I replaced the values.json, restarted and it is still not seeing the exported files. Do I need to re-export them or something?

**Comment by cadon** [comment]
Does the Deinonychus appear in the species selector in ASB? If not, you probably replaced the wrong values.json.

**Comment by Zhinjio** [comment]
I'm really confused. The only values.json file I can find is the one under the json directory in the installed directory. The footer reads: v.0.30.1.0 / values: 294.101, additional values from classicFlyers.json v.1.0.18. The newest file that I just opened to verify that it overwrote it shows v.297.64.2. Where the heck is it getting this file from? I even tried manually loading it from "extrasettings" and it doesn't seem to work. Is there another place it might be pulling the old file from?

**Comment by Zhinjio** [comment]
Found it. Somewhere along the way, it started saving to my users/appdata dirs. Fixed. Thank you.
