### ISSUE TITLE
Max Dom Levels.

### ISSUE THREAD

**Issue by deedoubleu** [cadon/ARKStatsExtractor#939]
In Stat Testing it shows 71 as max dom level while it is supposed to be 73 as of August 14, 2018.
https://ark.gamepedia.com/Leveling

**Comment by cadon** [comment]
The max dom level is dependent on the server you play on. For ASB you can this value in the settings. If you play on a server with 73 possible levelups, just set this in settings. If you create a new library, the default value is 73.
