### ISSUE TITLE
Some of the stats in the testing area are not allowing high values

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#94]
We have a baby Spino that we have breed and we can't enter it stats, we have all but the Torpor so I thought I would enter it into the tester and see if I could calculate the Torpor and the food and Torpor when trying to enter the values from the window on the right side reset to 9999 in both input boxes.
![capture1](https://cloud.githubusercontent.com/assets/1366816/17845065/500bd43e-6882-11e6-876d-5f34d8a8cf61.PNG)

**Comment by cadon** [comment]
Hi, the fields in the Tester-tab are for the stat-levels, not the stat-values, so in your case you try to add a level 17569 Spino to the library. The values look like it's Spino around level 329, but the torpor-value seems not to be a valid one. Is this spino on an official server (or a server with official multpliers)? If all the other values are correct, you can try to use 17578.5 as torpor value, and level 329 to extract the creature. Another reason could be if the creature is already imprinted, the tool cannot handle this.

**Comment by cyberangel67** [comment]
omg yeah I worked that out in the end...

But yes I know the torpor is wrong, I was hoping to use the tester to get the right torpor. My tribe mate didn't take notice of the stats before doing the imprint.

**Comment by cadon** [comment]
The Stat-Tester has the imprinting-bonus, so you actually can try around with this to match the correct. Check the bred-checkbox, set the imprinting-bonus to the one of the creature, then increase the level-controls until the stat-value is the one of the creature. But due to a bug in the game the imprinting-bonus is not always assigned to all stats, so it may not work for all stats.

**Comment by cyberangel67** [comment]
Yeah, I was entering it into the library and my tribemate told me the wrong values. So I went to the tester and stupidly entered the real values rather than the points for stats. Oh well, thats what you get for no sleep breeding :-) 

Anyway, all sorted now.
