### ISSUE TITLE
Featherlight import issue

### ISSUE THREAD

**Issue by DaarkOne** [cadon/ARKStatsExtractor#944]
I'm on an official server, it is 2 times taming since it's the weekend and I have 2 featherlights that will not import.
![image](https://user-images.githubusercontent.com/16737960/64071037-dbd54c00-cc36-11e9-83c0-729e44ba194d.png)
This one due to torpor
![image](https://user-images.githubusercontent.com/16737960/64071055-f90a1a80-cc36-11e9-8acf-61e1b24cc9f0.png)
This one due to food and torpor

**Comment by cadon** [comment]
Did you level food? Are there different stat-multipliers on the server? Are other species working?

**Comment by DaarkOne** [comment]
I leveled food on 1, there are only Official modifiers and yes I had a
third featherlight that worked fine as well as other species

**Comment by DaarkOne** [comment]
I leveled food on the one that only has a torpor issue

**Comment by cadon** [comment]
I can extract both now. In the last versions there were improvements regarding rounding errors, maybe that was the reaseon.
