### ISSUE TITLE
Paternal Mutation Count wrong on importing

### ISSUE THREAD

**Issue by cadon** [cadon/ARKStatsExtractor#945]
I did notice that when you import multiple dinos (from an export), it will normally correctly find the number of mutations. HOWEVER, if that last dino you imported had a HIGHER paternal mutation count than the current import, it will still show that higher mutation counter, instead of the correct value from the dino you're importing. Maternal mutation count updates correctly.

_Originally posted by @Zhinjio in https://github.com/cadon/ARKStatsExtractor/issues/654#issuecomment-527291830_

**Comment by cadon** [comment]
I cannot reproduce this issue. Can you post the two export files that cause this issue?

**Comment by Zhinjio** [comment]
I certainly can. But it basically happens every time I import a series of dinos (since I'm doing a fair amount of breeding, this happens almost daily). The only criteria is importing something with a high paternal mutation count first, and then another dino of the same species with a lower mutation count right after. I've seen it. Nothing special about my setup that I'm aware of. I am using classic fliers, but I've had it happen with direbears, wolves and sabers as well.

I'll attach a couple files once I get home from work.

**Comment by Zhinjio** [comment]
Two files, both pteras with high mutation counts. Import the one ending in 205 first, his paternal mutation count is ... 80-something. Also, for some reason, the tribe name doesn't import. Anyway, not the issue at hand.

Once imported (should be clean import, but I can provide my server settings if it isn't obvious). Then, import the other one (Dragonchaser). That one has a LOWER parternal mutation count, 60 I believe, but the import screen still shows 82 from the previous one.

[twoexports.zip](https://github.com/cadon/ARKStatsExtractor/files/3572627/twoexports.zip)

**Comment by Zhinjio** [comment]
Going to take a stab at looking at code to see if I can see any logic problems.

In CreatureInfoInput.cs, lines 408-422 (updateMutations), is it comparing maternal/paternal mutation counts against TOTAL mutation counts to determine whether to use the parent's mutation count?

**Comment by Zhinjio** [comment]
Also, if that is in fact the problem area, you wouldn't have been able to reproduce it if you didn't have the parents in your db.

**Comment by Zhinjio** [comment]
I will probably have to manufacture a case where the parents still exist. I don't keep them around after they stop being useful for my breeding. But I think I can do that. I doubt I'm using the beta, so I can download and try that as well. More to come hopefully this evening.

**Comment by cadon** [comment]
Thanks a lot for these files. I could track the issue down, it was caused by first setting the mutation counter of the creature and after that setting the parents. When the mutation counter was set, the parents of the previously set creature were still set and the imported mutation number was compared to them. If a parent had a higher mutation counter than the offspring, the counter was set automatically to the higher value, because usually the counter can only rise. The parents will be set first now, so it should be fixed. If you want to test the beta-version, you can ask in the discord-channel to be added to the beta-testers.
