### ISSUE TITLE
not recognition deinonychus

### ISSUE THREAD

**Issue by LotekHeavy** [cadon/ARKStatsExtractor#949]
the new dino "deinonychus" fromt the dlc map valguero (https://ark.gamepedia.com/Deinonychus) gets marked as "Aberrant Paraceratherium" when executing the importing from a save game

I use the 0.30.1.0 release, with windows 10.

**Comment by cadon** [comment]
On the discord-server you can find a new file that includes the Deinonychus. Currently automatic updaters are not working, a new release with fixes for this is planned this month.
