### ISSUE TITLE
Pelagornis stats not resolving

### ISSUE THREAD

**Issue by Gangreless** [cadon/ARKStatsExtractor#95]
I saw someone mention they had problems with just the health, 17 days ago, and you suggested putting in a point to make it recalculate. I tried that and it didn't work. I'm having the same issue on all three of my pelas and it's all health/stamina/weight in red. These were all tamed in the past couple days.

**Comment by cadon** [comment]
Hi, I updated the values-file. If it still does not work, try a levelup again. Hope that does it this time.
