### ISSUE TITLE
Extractor added DOM stat to an non upgradable stat (Icthy)

### ISSUE THREAD

**Issue by leo91000** [cadon/ARKStatsExtractor#950]
In game stat :
![ShooterGame_eG8y3yiiFe](https://user-images.githubusercontent.com/1354510/64913008-61c5bc80-d738-11e9-8116-9146ece1354e.png)

Extracted stat ;
![ARK_Smart_Breeding_Dbp47SCVGK](https://user-images.githubusercontent.com/1354510/64913011-6db17e80-d738-11e9-8e80-6ceb419ce4a7.png)

As you can see there is 0 wild level on oxygen and 6 on DOM where it is the reverse and can't edit it. As a result it put 6 point on speed but it have 0

**Comment by cadon** [comment]
Thanks for the report, this will be fixed soon. Until then you can select a different species that uses oxygen and click on the small lock-symbol near the domesticated level value on the oxygen stat. This will prevent the app to assign any levels there. Then select the Ichthy and extract its values. After that you can unlock the lock-icon again.
