### ISSUE TITLE
Extraction Still Doesnt Work

### ISSUE THREAD

**Issue by OfficialOminous** [cadon/ARKStatsExtractor#951]
Hi,

Iv tried using this app a couple years ago and it didnt work then and it doesnt work now. Iv set all the multipliers in single player (it doesnt matter what server im on though) iv even put the stats in manually other than torpor and it just can not extract. I even tried puttin in torpor to make up to 255 levels, why does your app not work for me?
![20190915172623_1](https://user-images.githubusercontent.com/55343257/64918286-8628a400-d7df-11e9-8acb-8997d9976c3c.jpg)

![1](https://user-images.githubusercontent.com/55343257/64918317-d9025b80-d7df-11e9-8dc7-4c7e87be59a6.png)

**Comment by VolatilePulse** [comment]
It appears you are entering the stat levels where you should be entering the stat values (as seen in the creature's inventory). If you would prefer to enter stat levels instead, the stat testing tab accepts levels instead of calculated values.
