### ISSUE TITLE
Library Stat Coloring After Update

### ISSUE THREAD

**Issue by HRock4887** [cadon/ARKStatsExtractor#958]
Just updated smart breeder to 0.33.2.0 and noticed stat coloring in the library does not seem to be working correctly for weight and damage. The top stat for each species is not brightly colored like it is for hp and stam. Not sure if this is a bug or a different problem? Coloring was working correctly yesterday before I updated to the latest version.
![smart breeder ss](https://user-images.githubusercontent.com/55721331/65471001-b77e2100-de2a-11e9-9cae-517378b44d59.PNG)

**Comment by HRock4887** [comment]
Nevermind saw the issue was posted on discord and was able to fix it.

**Comment by cadon** [comment]
There's currently a bug, after opening the application it will not highlight all the set stats like set before, this will be fixed in 0.33.3.
