### ISSUE TITLE
 Parents are not shown when exporting.

### ISSUE THREAD

**Issue by Kazskan** [cadon/ARKStatsExtractor#960]
When I import data of a dino, information of parent don´t appear and I type manually in each dino. 
What am I doing wrong?
Another question. Since last update, while I use a mod, the new import dinos appear under other list with the name of the mod and I can´t select the parents of new dinos because thes ones appear in other list. 
Thanks a lot and sorry for my english.

**Comment by cadon** [comment]
Hi,
### Missing Ancestors from Export
* When exporting creatures, ancestors are not included by default
* Imported creatures without ancestors won't correctly link their parents
* Before exporting, open the Ancestry Tab of the creature in Ark

### Different species
What mod do you use? When the library file was converted to the new format, it should have recognized the species correctly, but it may be that it didn't work in your case. You can change the species of creatures by
* selecting them
* right-click with the mouse, or press F3 on the keyboard
* change the species and confirm the change
Make sure you have a backup of the library, changing the species of creatures can have undesired effects.

**Comment by Kazskan** [comment]
Hi!!
### Missing Ancestors from Export
I will try to review your comments as soon as possible.

### Different species
The mod that I use is "Naj´s Speedy Flyers". The "problematic" dino are Argentavis. When I export them, don´t list different species, it list with header text "Argentavis (Naj´s Speedy Flyers)" and I can´t select parents for the other list of argentavis.
I hope to explain well.

Thanks a lot.

**Comment by VolatilePulse** [comment]
You can't select other creatures because to the game, an Argentavis from official and an Argentavis from Naj's may as well be a Dodo and a Rex. If, during the conversion process, your Argentavis were incorrectly set to being Official ones instead of ones from Naj's, you will need to edit those creatures' species to match what they actually are.

**Comment by Kazskan** [comment]
OK, thank you very much. I will try it.

**Comment by Kazskan** [comment]
> You can't select other creatures because to the game, an Argentavis from official and an Argentavis from Naj's may as well be a Dodo and a Rex. If, during the conversion process, your Argentavis were incorrectly set to being Official ones instead of ones from Naj's, you will need to edit those creatures' species to match what they actually are.

I modified creatures species of all Argentavis and now don´t have any problems, at the moment.


 
> ### Missing Ancestors from Export
> * When exporting creatures, ancestors are not included by default
> * Imported creatures without ancestors won't correctly link their parents
> *** Before exporting, open the Ancestry Tab of the creature in Ark**
 
The problems with ancestors when import-export dinos have improved a lot when seeing ancestors before exporting dinos.

Thanks a lot to all!!!
