### ISSUE TITLE
Error in System.Windows.Forms

### ISSUE THREAD

**Issue by dketcham** [cadon/ARKStatsExtractor#961]
Hello!

Even since updating to the latest version of ARK Smart Breeder, I now get an Unhandled Exception after leaving the application idle while others are making modifications to my new .asb file (we followed the instructions for updating a shared file configuration):
<img width="274" alt="asb error" src="https://user-images.githubusercontent.com/9245756/65657846-cdd2db00-dfea-11e9-8a3d-816deeb2d1f6.png">

The other users that share this file with me also are reporting similar errors as well.  Is there an easy way to troubleshoot what is causing this?

**Comment by cadon** [comment]
Hi, thanks for the report. Probably that exception is related to duplicate creatures. Can you try to find out which action exactly will cause this exception?
I think it's related to deleting a creature in a sync'ed library.

**Comment by dketcham** [comment]
we'll have our group start playing with this tonight.  On a related note, we observed that as a result of upgrading to the newest version, our managarmyrs were not appearing in the dino lists (but a search of the shared file shows that their data still is in there).  Could this potentially be related to those dinos?  I can provide our asb file (or prior xml file) if those would help.

**Comment by cadon** [comment]
The Managarmr-issue should be resolved in 0.33.3. You need to convert the library again, or add the blueprint-path in the savefile manually (remember to create a backup), for more infos see the [release notes](https://github.com/cadon/ARKStatsExtractor/releases/tag/v0.33.3).
Any news about the exception?

**Comment by dketcham** [comment]
thanks RE the managarmr!  We might need to do some heavy lifting RE our dino file, as the manas were not coming back after upgrading the smart breeder + attempting a re-import.

With respect to the error, it appears to do it when we have multiple people accessing the file at the same time (for reference, we are using a OneDrive share), specifically any time we add a dino or remove a dino.  This only appears to happen immediately to the users not adding/removing the dino, but on occasion the same error will occur to the person making a modification to the dino list.
  In addition, the errors we now receive after having upgraded to the latest version appears to have a part of a stack trace (see attached).

![unknown](https://user-images.githubusercontent.com/9245756/65930514-a5bcf080-e3cb-11e9-930a-6957353a2c03.png)

**Comment by cadon** [comment]
Hi, is this bug fixed in 0.34.1?

**Comment by dketcham** [comment]
that's a good question!  we'll download and test tonight

**Comment by dketcham** [comment]
the latest patch appears to have worked.  Thanks so much!

One odd quirk that we're now experiencing (albeit less problematic than crashing) is that any time we add or remove a dinosaur from our library, it keeps switching the filter on our library page to ovis.  This only appears to affect the individual importing/deleting dinosaurs, and not the others viewing the file at the same time.  Would you like me to close this thread and open a new one for that issue?
