### ISSUE TITLE
Dino not importing at all

### ISSUE THREAD

**Issue by IronSage** [cadon/ARKStatsExtractor#963]
My snow owl 193. all stats are good but torpidity is always at red and im on an unofficial server with 10x tamin/breeding no different stat modifiers 

![image](https://user-images.githubusercontent.com/55857285/65725288-17610b80-e067-11e9-910e-68def8b6624c.png)

**Comment by cadon** [comment]
The weight stat-multipliers are very likely increased on your server. I'd ask the admin for the exact values.
