### ISSUE TITLE
Lockup After Saving Dino

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#964]
I have my file open and I can load the stats but if i hit save, the program becomes unresponsive and stops working.  Eventually i get the 'not responding' and closes.

**Comment by Worldgate** [comment]
Here is the file, the asb and some of the exports that are locking up.  Not sure why this started happening, began sometime after i started mass importing and would get the occasional stall, now happens if i have an already existing database.

https://www.dropbox.com/sh/27cl0asrowdmzbh/AAC19Ng3N4TmUJ0NRNnV_0IEa?dl=0

**Comment by Worldgate** [comment]
Update #1: If I open a different asb file, perhaps one for the argents or gigas, it doesn't crash on import.  So maybe the program corrupted that database somehow?

**Comment by cadon** [comment]
Hi, thanks for the report. I can load, save and import your files without issues. What version do you use?

**Comment by Worldgate** [comment]
.2 .3 and .4 i tried.  Wonder why its not working for me. >_<  It's only the ravager one that has the issue too.

**Comment by cadon** [comment]
Is the library shared when you open it? Can you try to save it without the Prettifying option enabled?

**Comment by Worldgate** [comment]
I think I may have figured it out due to a sync log.  Linux doesnt care about case in file names but windows does.  So there was a 'data' and 'Data' directory, and windows was freaking out and switching back and forth between them so it was causing crashing.  Anywho after deleting, several times, both directories in linux (i use nextcloud for syncing) it might be fixed now.

**Comment by cadon** [comment]
Thanks for the feedback how you solved it!
