### ISSUE TITLE
Bug related to manually set timers?

### ISSUE THREAD

**Issue by StartisMC** [cadon/ARKStatsExtractor#965]
![image](https://user-images.githubusercontent.com/27813548/65837552-bb94bd80-e2c6-11e9-937c-d89f746dcaff.png)
Whenever a manually-set timer goes off (or does it's prewarning thing), this pops up and no sound comes from the timers going off. This was not the case before the most recent update to ASB.

**Comment by cadon** [comment]
Thanks for the report. It's a bug and will be fixed soon.
