### ISSUE TITLE
Extraction Settings

### ISSUE THREAD

**Issue by Roach009** [cadon/ARKStatsExtractor#966]
I am trying to set up the program to extract dino stats straight from Ark.  It is pulling the screenshot just not detecting the text.  Any help would be greatly appreciated.

![Screenshot 2019-10-01 11 00 03](https://user-images.githubusercontent.com/53878700/65979620-34b52180-e43b-11e9-9218-2e9ffc19f07b.png)

OS:  Windows 10 64-bit
ASB:  0.34.0.0

**Comment by cadon** [comment]
Hi, using the dino-export function is recommended over using the OCR. See here for more infos about the export: https://github.com/cadon/ARKStatsExtractor/wiki/Importing-Creatures#ark-exports
If you want to use the OCR, you probably have to customize it more, see here: https://github.com/cadon/ARKStatsExtractor/wiki/OCR
