### ISSUE TITLE
Request, Import existing list requires selecting species

### ISSUE THREAD

**Issue by Kirstarix** [cadon/ARKStatsExtractor#967]
Hi

I have one list for Tek Rexs and one for Giga's. Each time changing the lists I have to select the species each time, could that info for species be saved to the list and filled upon importing and no need to select each time?

Above is only a request, and thanks so much for the software this it's really nice time saver

**Comment by VolatilePulse** [comment]
I'm not quite sure what you're asking to be honest. Do you have a screenshot or library you can provide to highlight the issue you're experiencing? From what I gathered from you comment, I think what you're looking for already exists.

**Comment by Kirstarix** [comment]
Hi when you save a dino list, it's saved as a asb file, upon opening one. When a different list is already present you must select the correct species or nothing will propagate. I hope that makes sence.

**Comment by VolatilePulse** [comment]
The `.asb` file is the library file. A library is designed to contain all of your creatures for a server/cluster. You can have two (or more) species in one library file. This allows you to quickly switch between species that you may be breeding and be able to apply setting changes across the entire library at once.

I'm not positive I've completely understood though. I'll try to load up a library and see if I can show what I mean in more detail.

**Comment by Kirstarix** [comment]
It's not an issue, but if you open up one of the .asb that is solely for one species, you must select the species each time. So each time you load up a different list you must change species each time.
 
Its ok

**Comment by VolatilePulse** [comment]
Which version of ASB are you using? It can be found in the status bar at the bottom of the program or by selecting `? -> about...` in the menu bar at the top of the program.

**Comment by Kirstarix** [comment]
0.34.0.0 << latest?? a downloaded update earlier today

**Comment by VolatilePulse** [comment]
Okay, I think I understand a bit better. After you add a new creature to the library, you'd like the library view to "update" to just that species for you?

**Comment by Kirstarix** [comment]
Say we have a asb list with tek rexs, we import the file and in species, it will show Tek Rex upon importing list. And then if we change to a new list lets say gigas, upon import it wont show Tek Rex(what is happening atm and nothing appears as its the wrong species) but now show what the species is being gigas and everything propagates.

I hope that makes sence

**Comment by VolatilePulse** [comment]
So, I think I have fully understood it now. When you say list, you mean save file, the `.asb` library file, correct? And when you say import the file, I assume you mean loading a different save file (or list) into ASB, correct? And the view that you're talking about is the species that is selected in the `Breeding Planner`, correct?

I've attached a screenshot to hopefully reproduce what you're talking about. You can see that the Breeding Planner is currently attempting to display "qualifying" Argentavis breeding pairs, however, the library only contains Pteranodons. You would prefer that, if a species isn't available, it should attempt to show you a species that exists in that library (or list)?

![image](https://user-images.githubusercontent.com/6995232/66107631-b1a4e000-e58e-11e9-9de6-2969356e22b1.png)

**Comment by Kirstarix** [comment]
Yes :)
