### ISSUE TITLE
Updating Creature in library wipes cooldown/growing times

### ISSUE THREAD

**Issue by Kirstarix** [cadon/ARKStatsExtractor#970]
Hi
Bug, broken
If you choose to re-export an existing dino, let's say a tek rex because we want fresh new timers in the library since getting dino out of cryopod.

Choose "Last Export" button >> "Update creature in library" button. And the library's growing time will be blank. But if we delete out the dino and follow steps to add dino the timer will be there

Plus exiting Ark Smart Breeding and starting it up again wipes the "Cooldown/Growing" times in the library.  Or loading up a list asb file the times "Cooldown/Growing" won't be there in the library.

**Comment by Kirstarix** [comment]
The last update fixes all the later above from Orig post except the very bottom of the page

> 0.34.3
> Fixes
> Exception fixes when loading libraries.

But updating a creature in library does not update the cooldown/growing time(old-time remains the same after updating), and needs to be deleted and added back in. It's only a minor issue now ty :)

**Comment by cadon** [comment]
Hi, I just tested imporintg creatures with a cryo-cooldown. It seems this cooldown is not saved in the export file, so ASB cannot update that value. In my tests ASB didn't change that value at all, a previously set cooldown timer wasn't changed by re-importing a creature. If you want to update cooldowns, you have to do so manually.
