### ISSUE TITLE
High stats coloured green not showing for damage column

### ISSUE THREAD

**Issue by MeinGeheimnis** [cadon/ARKStatsExtractor#976]
Damage column doesn't colour the highest desirable value for breeding etc., green. Still works for all other stat columns as far as I can tell.

**Comment by Kirstarix** [comment]
Do you have a screenshot? Like below
![TekRex](https://user-images.githubusercontent.com/56104287/66466953-e94be480-eac6-11e9-9661-49b82e5c2191.png)

**Comment by cadon** [comment]
Only stats you have selected to be shown are highlighted. To change the stats go to the library-tab, lower left look for the `Stats` tab (you may have to click on the small arrow to the right), select the stats and then hit Apply.

**Comment by deedoubleu** [comment]
Ty, solved my problem.
