### ISSUE TITLE
unable to extract stats from bred direwolves

### ISSUE THREAD

**Issue by bucketsjen** [cadon/ARKStatsExtractor#98]
The last couple days, I have not been able to extract the values of bred direwolves (tried on 4 that I have currently). It lights the HP up in red, but everything is correct. I read the patch notes and I don't see that they changed the values, so I'm kinda perplexed...

**Comment by Darinth** [comment]
They ninja nerfed the base HP to 330.

**Comment by cadon** [comment]
thanks, file is updated
