### ISSUE TITLE
Dino Export bug, workaround?

### ISSUE THREAD

**Issue by Kirstarix** [cadon/ARKStatsExtractor#980]
Hi
In Steam\steamapps\common\ARK\ShooterGame\Saved\DinoExports
Is where the dino export of each dino goes, and on some dinos not all, the files are missing the matrilineal/patrilineal mutations count. Even though the dino has mutations it will be listed like below
RandomMutationsMale=0
RandomMutationsFemale=0
When this happens it tends to also happen the parents and ancestors count will be 0
[Dino Ancestry]
DinoAncestorsCount=0
DinoAncestorsMale=0

My question is, is there a workaround for this?? Using a cryopod and releasing the dino will not fix it(have not tried a beacon), plus sorting the files to last modified up top and deleting it and then exporting the dino in-game again will end up with the same result. Just passing the info on and hoping maybe the devs at ark need this info? Or is it already a known issue?
![Dino](https://user-images.githubusercontent.com/56104287/66702276-1a3b4c00-ed49-11e9-9c6b-ee8b1349f285.png)

**Comment by VolatilePulse** [comment]
This is a limitation of the server code for Ark. The server doesn't send that information unless requested. But there is a fairly quick workaround. Before you export a creature, open the creatures ancestry tab. That's enough to force the server to send the data and the export file will contain the data. But you must open the ancestry tab before exporting.
