### ISSUE TITLE
Mutation workaround?

### ISSUE THREAD

**Issue by DJQuadRocks** [cadon/ARKStatsExtractor#981]
Since opening the creatures ancestry tab is the only workaround for detecting mutations, would it be feasible to add a check that if a stat from the bred creature has a +2 (or +4) stat from the parents, it's a mutation?

Also, does the breeding plan take into account what to breed to work toward to get an exact 20/20 mutation?

Thanks!

**Comment by cadon** [comment]
Hi,
checking only the stats is not enough. One parent could have 10 levels in stat and the other 12 levels, if the offspring has 12 levels it can be either inherited from the second parent or there could be a mutation from the first one. The pedigree view uses this method to draw a small green circle if there is a possible mutation. On the other hand, the regular display of occured mutations in the creature infos relies only on the number of mutations of the parents and the creature itself.

Regarding the breeding plan request, it doesn't matter if a creature has 20/20 mutations or more, so there's no benefit to reach exactly 20 mutations. You can limit the breeding pairs regarding their current mutation-counter, e.g. if you only want to see suggestions with parents below 10 mutations.

**Comment by DJQuadRocks** [comment]
Thanks for the reply. If the limit is set for the mutation counter, does the breeding plan then take into account to maximize the mutations or is it strictly the highest values?

As you can probably tell I'm new to stacking mutations and the YouTube videos I've seen don't make much sense to me. Right now I'm at a point where I have the highest stat breeders for most creatures and the mutations are normally a low mix of around 6/3, 4/6, etc.

**Comment by cadon** [comment]
If you set a mutation limit in the breeding planner, it just ignores all creatures that have a mutation-counter greater than that number for the breeding suggestions.

Regarding mutations I recommend to watch [Consolitude's video](https://www.youtube.com/watch?v=k3LHIjYUQZI)
