### ISSUE TITLE
request for Library to have sort category for paternal and maternal

### ISSUE THREAD

**Issue by Kirstarix** [cadon/ARKStatsExtractor#982]
Hi
Just a request.
I don't find in the library Total Mutations very important compared to knowing mutations for paternal and maternal separately. Be nice to have it separate paternal and maternal.

I am aware in pedigree if you mouse over it gives this info for each one. But for the library, it is where most of the time is spent there for me.

This is 192 mutations gen1 for paternal and maternal, 485 base melee.
![giga1](https://user-images.githubusercontent.com/56104287/67360310-db0ec580-f5a8-11e9-9382-b5ffcac9b03a.png)

Then this is 192 mutations gen2 maternal only, 485 base melee, gets confusing not knowing what is what without having them separated in library
![giga2](https://user-images.githubusercontent.com/56104287/67360410-3b056c00-f5a9-11e9-9cb2-6f510ea05e88.png)

As both dino have total 192, but the female gen2 offspring now has 192 only in matrilinear line and patriline at 0/20.

I do call each dino name by mutations, but I can make errors, and this would solve that. And I don't care for whatever happens to total mutations category in the library tab, it can be kept or removed would not worry me

**Comment by VolatilePulse** [comment]
There's no benefit to knowing how the mutation counter is split as the creature's mutation counter is the sum of both parents' contribution. Breeding relies on the creature's mutation counter, not either of it's parents' mutation counter.

The short of it, both of those creatures have a mutation counter of 192 and neither can contribute to new mutations.

**Comment by Kirstarix** [comment]
but the bottom pic patrilinear is not maxed out. Its at 0/20, and was lead to believe providing thats not maxed out you can go new mutations?

**Comment by VolatilePulse** [comment]
Mutations and breeding are very complicated topics. The ancestry tab only shows what the parents' mutation counters were plus any potentially new mutations. As mentioned earlier, both of those creatures have 192/20 and can't contribute to new mutations. However, they can still both have an offspring that gets a mutation, but only if their mate has 19/20 or less of it's combined mutation counters.

There is no way to "reset" a counter, but you can attempt to mate a creature that has met or exceeded 20 mutations. Typically this involves either mating the creature with a tamed creature or a bred creature that has no mutations on either side.

I would strongly advise getting passed the use of the Matrilineal/Patrilineal mutation counters as anything more than a way to get that creature's actual mutation counter.

**Comment by Kirstarix** [comment]
Last time I was breeding on official, this is exactly what I explained above without going into all the details of how you breed super dinos. I'll post back in a couple of months' time with the next-gen giga exceeding with higher mutations and higher melee and will post the pics. Meaning proving you don't exceed on one side that you can continue mutations. Its why there are so many dinos with such high amounts but 99% of players out there don't know what there doing and are what circulates.

**Comment by coldino** [comment]
@VolatilePulse is correct.

For each parent, it is only the sum of its mutation counts that decides if it can contribute mutations. That does not stop you from having way more than 20 or even 40 mutations, however. Using any parent with a sum of <20 will allow mutations to continue.

Please read [this reddit post](https://www.reddit.com/r/playark/comments/66n962/mutations_and_you_a_guide_on_breeding_mutations/) for details. The information in it has stood the test of time, and many people challenging it.

**Comment by cadon** [comment]
Some confusion in this topic might come from observing mutations from the offspring's view. If a creature hatches or is born, it selects stats from parents it will inherit. It also checks each of the parent's mutation counter and a chance is calculated if a mutation will happen. If the baby's maternal or paternal mutation-counter is less than 20, it has a chance for a mutation for itself (but not for possible offspring of that baby!). This view of the mutation process is rather theoretical and does probably only confuse.

So if the combined mutation counter that is displayed in the library is 20 or greater, that creature will not give a chance for mutations in an offspring.
