### ISSUE TITLE
Official Mutated Tek Q Red Speed Box

### ISSUE THREAD

**Issue by arathein** [cadon/ARKStatsExtractor#983]
Just updated to the most recent version of ASB, when I export the dino from Ark and load it into ASB all the stats are right but speed which is a red box.
[DinoExport_193496224170785214.zip](https://github.com/cadon/ARKStatsExtractor/files/3769779/DinoExport_193496224170785214.zip)
I zipped the export file for you
Official servers are currently running 2x breeding but that wouldn't effect these stats so not sure what the deal is
Quetz Screen
![image](https://user-images.githubusercontent.com/28239481/67531766-9018af00-f689-11e9-9264-b9da923de8f7.png)
ASB Screen
![image](https://user-images.githubusercontent.com/28239481/67531801-aaeb2380-f689-11e9-9659-32971961fa2e.png)

**Comment by cadon** [comment]
Hi, should work again in v0.34.4.
