### ISSUE TITLE
Missing <ID> at end of file path!

### ISSUE THREAD

**Issue by Uhtredofbebbanberg** [cadon/ARKStatsExtractor#984]
![image](https://user-images.githubusercontent.com/57013065/67590080-abce9480-f71f-11e9-9a6a-d0e05661ea72.png)

**Comment by Uhtredofbebbanberg** [comment]
the app will not let me extract dinos directly until I have a <id> at the end of the file path

**Comment by cadon** [comment]
Did you already export any creatures in ARK? Usually ARK creates the folder with the id automatically once a creature is exported.

**Comment by Uhtredofbebbanberg** [comment]
yes, I've exported multiple times, still not creating a <id>.

**Comment by cadon** [comment]
did you look in the correct ARK folder? If you have multiple installations of ARK, you need to look in the one you're currently running.
