### ISSUE TITLE
Export Dinos as Baby - Mutation not displayed

### ISSUE THREAD

**Issue by Tschugge** [cadon/ARKStatsExtractor#986]
When a dino is born, it can be exported directly. If the dinosaur has received a mutation, it will not be displayed. If it is fully grown, it must be exported again.

I just wanted to ask if that was wanted - or a mistake. Excuse me. I do not speak English. Translater.

Thank you for Helping.

**Comment by cadon** [comment]
Hi, did you open the ancestors window in ARK prior to exporting the creature? The export file does only contain the mutations-info if you have opened the ancestor info before.

**Comment by Tschugge** [comment]
Didnt know that. Thx you for the info :)
