### ISSUE TITLE
Direwolf Health stat needs update

### ISSUE THREAD

**Issue by Tallyhoo** [cadon/ARKStatsExtractor#99]
They ninja nerfed Direwolves' health, not sure about any other dinos yet(update-rex HP stat changed too). But Health stat in the extractor needs an update now

**Comment by Darinth** [comment]
Base health appears to have changed to 330.

**Comment by emurday** [comment]
Came here to submit a ticket but will just add to this one in case it helps.  This animal was a 120 wild with no stats yet allocated post-tame (official server):

![image](https://cloud.githubusercontent.com/assets/7611518/18368359/72353410-75d4-11e6-9d57-15d374affce9.png)

**Comment by cadon** [comment]
thanks, it's updated
