### ISSUE TITLE
Can I add Simplified Chinese language files myself?

### ISSUE THREAD

**Issue by lxitdn** [cadon/ARKStatsExtractor#994]
Can I add Simplified Chinese language files myself? I want to translate it into my native language, thank you
My email: 666666@gitxp.com
Hope to reply, look forward to

I copied the string file, translated it to my native language, and added it to the settings options file, but it was not called automatically. How to properly call this file?

**Comment by VolatilePulse** [comment]
You will need to submit a pull request in order for the language to be added into the program. If you haven't already, follow the instructions [here](https://github.com/cadon/ARKStatsExtractor/wiki/Translations) and as soon as possible, we will add the file into the next release.

**Comment by cadon** [comment]
Chinese translations is now added for the supported strings in the latest release.
