### ISSUE TITLE
Need help with exporting

### ISSUE THREAD

**Issue by StreamingSmitty** [cadon/ARKStatsExtractor#995]
![image](https://user-images.githubusercontent.com/57917277/69082123-b6b5d580-09fc-11ea-87bd-99969258dc44.png)

What should I do to make the Food stat not red?

**Comment by VolatilePulse** [comment]
If I remember correctly, Daeodon benefit from having their food leveled so they can heal for longer before beginning to starve. If you have leveled food on this creature, you will need to click on the red lock. The lock tells ASB that you know for certain no levels were applied to this Stat so ASB takes your word and tries to extract the stat level based on that information.

**Comment by StreamingSmitty** [comment]
But I did apply LOTS of levels to food

**Comment by VolatilePulse** [comment]
According to your screenshot, you told ASB you haven't leveled food at all. If you don't want that, remove the red lock from food by clicking on it.
