### ISSUE TITLE
Updater issue

### ISSUE THREAD

**Issue by Plasma-Softworks** [cadon/ARKStatsExtractor#996]
Getting an updating pop up asking to update, when I click yes nothing happens and about 10 minutes later I will get another update request.

**Comment by VolatilePulse** [comment]
What version are you on?

**Comment by Plasma-Softworks** [comment]
I am on 0.34.4.
Wow your reply was quick man!

**Comment by VolatilePulse** [comment]
I try to stay on top of issues I can deal with. There is indeed an update, 0.34.6, and I suspect the reason you are having issues is because you installed ASB into a protected directory, most commonly Program Files. We are aware there is no notification that the update couldn't be installed (in fact, it says it is successful). Unfortunately, the only workaround is installing (or unzipping) ASB into a non protected directory, like My Documents.

**Comment by Knightnight123** [comment]
I had the same issue. my download was in documents. I had to manually go to the .exe in the folder to open the program there and then the update button worked.  IDK why when before I was using the windows 10 start to open the .exe. I tried opening it this way many times with it not working when pressing yes.

**Comment by Knightnight123** [comment]
i was able to recreate and get video.  
Video :      https://vimeo.com/374462910

**Comment by VolatilePulse** [comment]
@Knightnight123 When you use the Windows 10 Start Menu to launch ASB, can you select `Open File Location` in the right hand pane and verify that it is indeed the same file you are launching manually? If it is, I'm really confused as there should be absolutely no difference between launching it from the Start Menu or from File Explorer.

**Comment by Knightnight123** [comment]
Yes it is the same file. sorry for the late respond

**Comment by VolatilePulse** [comment]
That's interesting. We aren't quite sure what may be causing the issue though. Some additional information may prove helpful though. Do you recall if you used the installer and installed ASB or if you used the portable version and unzipped/extracted the program?

**Comment by Taiine** [comment]
I have never been able to update the program via the pop up. 
Open program
New version Available do I want to install the update now? 
Click Yes
Program closes. 
Program Re-opens
New version (same one) Available do I want to install the update now? 
Repeat unless I tell it no, and go to the site and manually download the update.

**Comment by cadon** [comment]
Do you use the installed version (setup….exe) or the portable (.zip)?

**Comment by cadon** [comment]
That issue should be fixed now.
