### ISSUE TITLE
Translation file created

### ISSUE THREAD

**Issue by MicheaBoab** [cadon/ARKStatsExtractor#998]
I have made a translation file for Simplified Chinese, I'm wondering is it ok to add the simplified Chinese file in the next release?

Looking forward to helping
 Thank you very much
[Simplified Chinese.txt](https://github.com/cadon/ARKStatsExtractor/files/3884237/Simplified.Chinese.txt)

**Comment by cadon** [comment]
Thank you for your work on that! I'll include it in the next release.
