### ISSUE TITLE
Unknown species

### ISSUE THREAD

**Issue by PapaBear93** [cadon/ARKStatsExtractor#999]
I keep getting a unknown species error when I attempt to import a exported dino. It says the reason is a mod is used but there are no mods selected and the dinos exported are from official small tribes. I did a clean install hoping it would fix the problem but it is still happening.

**Comment by cadon** [comment]
can you post the content of the exported file (it should have a name like `DinoExport_012345678901234567.ini`)?

**Comment by PapaBear93** [comment]
Any idea where I would find that? I'm not too savvy with computers.

**Comment by PapaBear93** [comment]
[Dino Data]
DinoID1=403246846
DinoID2=434221268
DinoClass=/Game/Extinction/Dinos/GasBag/GasBags_Character_BP.GasBags_Character_BP_C
DinoNameTag=GasBags
bIsFemale=True
bNeutered=False
TamerString=Wet Works
TamedName=FFA/Weight
ImprinterName=Blackst
RandomMutationsMale=0
RandomMutationsFemale=0
BabyAge=1.000000
CharacterLevel=314
DinoImprintingQuality=1.000000

[Colorization]
ColorSet[0]=(R=0.250000,G=0.185219,B=0.133750,A=1.000000)
ColorSet[1]=(R=0.780000,G=0.700000,B=1.000000,A=0.000000)
ColorSet[2]=(R=0.250000,G=0.084211,B=0.025000,A=0.000000)
ColorSet[3]=(R=1.000000,G=0.475000,B=0.300000,A=0.000000)
ColorSet[4]=(R=0.300000,G=0.300000,B=0.150000,A=0.000000)
ColorSet[5]=(R=0.190000,G=0.137402,B=0.098800,A=0.000000)

[Max Character Status Values]
Health=29964.722656
Stamina=2520.000000
Torpidity=8737.699219
Oxygen=7955.200195
food=16800.000000
Water=120.000008
Temperature=0.000000
Weight=6269.400391
Melee Damage=3.315920
Movement Speed=0.200000
Fortitude=0.000000
Crafting Skill=0.000000

[Dino Ancestry]
DinoAncestorsCount=0
DinoAncestorsMale=0

**Comment by cadon** [comment]
That file looks fine. What happens if you drag&drop it into the extractor in ASB?
Does maybe the message about the mod only appear if you try to import all of your exported dinos?

**Comment by PapaBear93** [comment]
I am still able to extract either way but I just get that error message when I import my exported tames on the app.

**Comment by cadon** [comment]
Can you post a screenshot of the message?

**Comment by PapaBear93** [comment]
![Unknown Species](https://user-images.githubusercontent.com/49250495/69690790-e6b74580-109a-11ea-9789-370c04674375.png)

**Comment by PapaBear93** [comment]
It happens with every creature.

**Comment by cadon** [comment]
My best guess is that you somehow exported a raft (technically rafts are considered as species by the game and it may be possible to export them like creatures). ASB can't import the raft, so that's why this message appears.
If you don't have many exported files, I'd open each and check if it is the file for the raft and then delete it (or move it to another folder if you still need it). After that the import should work.

**Comment by cadon** [comment]
Rafts are now ignored when importing, the issue should be resolved. If not, feel free to reopen this issue.
